--- RB_REMOVE RELATIONSHIP FOR PA ADN BPT ---

ALTER TABLE "PLANNEDACTIVITIES" DROP CONSTRAINT "FK_PLANNEDACTIVITIES_PLANNEDACTIVITYCATEGORY_PLANNEDACTIVITYCATEGORYID";
ALTER TABLE "BUDGETPROJECTTRACKERS" DROP CONSTRAINT "FK_BUDGETPROJECTTRACKERS_CATEGORY_CATEGORYID";


--- RB_NEW_CATEGORYTABLE --- 

DROP TABLE "PLANNEDACTIVITYCATEGORY";
DROP SEQUENCE "PLANNEDACTIVITYCATEGORY_SEQ"

--- RB_PLANNEDACTIVITIES ---

ALTER TABLE "PLANNEDACTIVITIES" DROP COLUMN "PLANNEDACTIVITYTEAM";
ALTER TABLE "PLANNEDACTIVITIES" DROP COLUMN "PRIORITY";
ALTER TABLE "PLANNEDACTIVITIES" DROP COLUMN "PLANNEDACTIVITYCATEGORYID";
ALTER TABLE "PLANNEDACTIVITIES" DROP COLUMN "PLANNEDACTIVITYCATEGORY";
ALTER TABLE "PLANNEDACTIVITIES" DROP COLUMN "LCMCATEGORIES";

--- RB_BUILDCONSTRUCTIONS ---

ALTER TABLE "BUILDCONSTRUCTIONS" RENAME COLUMN "ISCLOUDASSET" TO "ISCLUODASSET";


--- RB_GLOSSARYITEMS --- 

ALTER TABLE "GLOSSARYITEMS" DROP COLUMN "ISTSRFIELD";

ALTER TABLE "GLOSSARYITEMS" ADD "DESCRIPTION1" NVARCHAR2(2000);

UPDATE GLOSSARYITEMS G SET DESCRIPTION1 = (SELECT DESCRIPTION FROM GLOSSARYITEMS WHERE G.GLOSSARYITEMSID = GLOSSARYITEMSID ) ;
COMMIT;
ALTER TABLE GLOSSARYITEMS DROP COLUMN DESCRIPTION;

ALTER TABLE GLOSSARYITEMS RENAME COLUMN DESCRIPTION1 TO DESCRIPTION;
COMMIT;
