CREATE SEQUENCE "NETWORKELEMENT_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL for Table NETWORKELEMENT
--------------------------------------------------------

  CREATE TABLE "NETWORKELEMENT" 
   (	"NETWORKELEMENTID" NUMBER(20,0) DEFAULT "NETWORKELEMENT_SEQ"."NEXTVAL", 
	"OPCO" NVARCHAR2(50), 
	"OEM" NVARCHAR2(50), 
	"ELEMENTNAME" NVARCHAR2(50), 
	"DATAACQUISITIONDATE" TIMESTAMP (6), 
	"NODETYPE" NVARCHAR2(50), 
	"PLATFORMTYPE" NVARCHAR2(50), 
	"SITELOCATION" NVARCHAR2(50), 
	"SOFTWAREINSTALLDATE" TIMESTAMP (6), 
	"SOFTWAREINSTALLDATEAP" TIMESTAMP (6), 
	"SOFTWAREINSTALLDATECP" TIMESTAMP (6), 
	"SOFTWAREPRODUCTDATE" TIMESTAMP (6), 
	"SOFTWAREPRODUCTDATEAP" TIMESTAMP (6), 
	"SOFTWAREPRODUCTDATECP" TIMESTAMP (6), 
	"SOFTWAREPRODUCTNUMBER" NVARCHAR2(50), 
	"SOFTWAREPRODUCTNUMBERAP" NVARCHAR2(50), 
	"SOFTWAREPRODUCTNUMBERCP" NVARCHAR2(50), 
	"SOFTWARERELEASEINFORMATION" NVARCHAR2(50), 
	"SOFTWARERELEASEINFORMATIONAP" NVARCHAR2(50), 
	"SOFTWARERELEASEINFORMATIONCP" NVARCHAR2(50), 
	"SPARE1OSSORENM" NVARCHAR2(50), 
	"SPARE2XMLVERSION" NVARCHAR2(50), 
	"XMLLASTPARSEFILEDATE" TIMESTAMP (6), 
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index NETWORKELEMENTIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "NETWORKELEMENTIDX" ON "NETWORKELEMENT" ("NETWORKELEMENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table NETWORKELEMENT
--------------------------------------------------------

  ALTER TABLE "NETWORKELEMENT" ADD CONSTRAINT "PK_NETWORKELEMENT" PRIMARY KEY ("NETWORKELEMENTID")
  USING INDEX "NETWORKELEMENTIDX"  ENABLE;
  ALTER TABLE "NETWORKELEMENT" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "NETWORKELEMENT" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "NETWORKELEMENT" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "NETWORKELEMENT" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table NETWORKELEMENT
--------------------------------------------------------

  ALTER TABLE "NETWORKELEMENT" ADD CONSTRAINT "FK_NETWORKELEMENT_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "NETWORKELEMENT" ADD CONSTRAINT "FK_NETWORKELEMENT_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;