CREATE SEQUENCE "IDENTITIES_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL for Table IDENTITIES
--------------------------------------------------------

  CREATE TABLE "IDENTITIES" 
   (	"IDENTITIESID" NUMBER(20,0) DEFAULT "IDENTITIES_SEQ"."NEXTVAL", 
	"NETWORKELEMENTID" NUMBER(20,0), 
	"OPCO" NVARCHAR2(50), 
	"OEM" NVARCHAR2(50), 
	"ELEMENTNAME" NVARCHAR2(50), 
	"IPADDRESS" NVARCHAR2(50), 
	"APNODEAIPADDRESS" NVARCHAR2(50), 
	"APNODEBIPADDRESS" NVARCHAR2(50), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6), 
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index IDENTITIESIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDENTITIESIDX" ON "IDENTITIES" ("IDENTITIESID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table IDENTITIES
--------------------------------------------------------

  ALTER TABLE "IDENTITIES" ADD CONSTRAINT "PK_IDENTITIES" PRIMARY KEY ("IDENTITIESID")
  USING INDEX "IDENTITIESIDX"  ENABLE;
  ALTER TABLE "IDENTITIES" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "IDENTITIES" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "IDENTITIES" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "IDENTITIES" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table IDENTITIES
--------------------------------------------------------

  ALTER TABLE "IDENTITIES" ADD CONSTRAINT "FK_IDENTITIES_NETWORKELEMENT_NETWORKELEMENTID" FOREIGN KEY ("NETWORKELEMENTID")
	  REFERENCES "NETWORKELEMENT" ("NETWORKELEMENTID") ENABLE;
  ALTER TABLE "IDENTITIES" ADD CONSTRAINT "FK_IDENTITIES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "IDENTITIES" ADD CONSTRAINT "FK_IDENTITIES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
