CREATE SEQUENCE "COMPONENT_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL for Table COMPONENT
--------------------------------------------------------

  CREATE TABLE "COMPONENT" 
   (	"COMPONENTID" NUMBER(20,0) DEFAULT "COMPONENT_SEQ"."NEXTVAL", 
	"SOFTWARECOMPONENTID" NUMBER(20,0), 
	"COMPONENTNAME" NVARCHAR2(100), 
	"PRODUCTIONDATE" TIMESTAMP (6), 
	"PRODUCTIONNUMBER" NVARCHAR2(200), 
	"PRODUCTIONREVISION" NVARCHAR2(100), 
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index COMPONENTIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "COMPONENTIDX" ON "COMPONENT" ("COMPONENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table COMPONENT
--------------------------------------------------------

  ALTER TABLE "COMPONENT" ADD CONSTRAINT "PK_COMPONENT" PRIMARY KEY ("COMPONENTID")
  USING INDEX "COMPONENTIDX"  ENABLE;
  ALTER TABLE "COMPONENT" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "COMPONENT" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "COMPONENT" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "COMPONENT" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMPONENT
--------------------------------------------------------

  ALTER TABLE "COMPONENT" ADD CONSTRAINT "FK_COMPONENT_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "COMPONENT" ADD CONSTRAINT "FK_COMPONENT_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "COMPONENT" ADD CONSTRAINT "FK_COMPONENT_SOFTWARECOMPONENT_SOFTWARECOMPONENTID" FOREIGN KEY ("SOFTWARECOMPONENTID")
	  REFERENCES "SOFTWARECOMPONENT" ("SOFTWARECOMPONENTID") ENABLE;
