CREATE SEQUENCE "SOFTWARECONFIGURATION_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL for Table SOFTWARECONFIGURATION
--------------------------------------------------------

  CREATE TABLE "SOFTWARECONFIGURATION" 
   (	"SOFTWARECONFIGURATIONID" NUMBER(20,0) DEFAULT "SOFTWARECONFIGURATION_SEQ"."NEXTVAL", 
	"NETWORKELEMENTID" NUMBER(20,0), 
	"OPCO" NVARCHAR2(50), 
	"OEM" NVARCHAR2(50), 
	"ELEMENTNAME" NVARCHAR2(50), 
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index SOFTWARECONFIGURATIONIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOFTWARECONFIGURATIONIDX" ON "SOFTWARECONFIGURATION" ("SOFTWARECONFIGURATIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table SOFTWARECONFIGURATION
--------------------------------------------------------

  ALTER TABLE "SOFTWARECONFIGURATION" ADD CONSTRAINT "PK_SOFTWARECONFIGURATION" PRIMARY KEY ("SOFTWARECONFIGURATIONID")
  USING INDEX "SOFTWARECONFIGURATIONIDX"  ENABLE;
  ALTER TABLE "SOFTWARECONFIGURATION" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);  
  ALTER TABLE "SOFTWARECONFIGURATION" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "SOFTWARECONFIGURATION" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "SOFTWARECONFIGURATION" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SOFTWARECONFIGURATION
--------------------------------------------------------

  ALTER TABLE "SOFTWARECONFIGURATION" ADD CONSTRAINT "FK_SOFTWARECONFIGURATION_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "SOFTWARECONFIGURATION" ADD CONSTRAINT "FK_SOFTWARECONFIGURATION_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "SOFTWARECONFIGURATION" ADD CONSTRAINT "FK_SOFTWARECONFIGURATION_NETWORKELEMENT_NETWORKELEMENTID" FOREIGN KEY ("NETWORKELEMENTID")
	  REFERENCES "NETWORKELEMENT" ("NETWORKELEMENTID") ENABLE;
