CREATE SEQUENCE "FUNCTION_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL for Table FUNCTION
--------------------------------------------------------

  CREATE TABLE "FUNCTION" 
   (	"FUNCTIONID" NUMBER(20,0) DEFAULT "FUNCTION_SEQ"."NEXTVAL", 
	"SOFTWARECONFIGURATIONID" NUMBER(20,0), 
	"FUNCTIONNAME" NVARCHAR2(50), 
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index FUNCTIONIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNCTIONIDX" ON "FUNCTION" ("FUNCTIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table FUNCTION
--------------------------------------------------------

  ALTER TABLE "FUNCTION" ADD CONSTRAINT "PK_FUNCTION" PRIMARY KEY ("FUNCTIONID")
  USING INDEX "FUNCTIONIDX"  ENABLE;
  ALTER TABLE "FUNCTION" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);  
  ALTER TABLE "FUNCTION" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "FUNCTION" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "FUNCTION" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FUNCTION
--------------------------------------------------------

  ALTER TABLE "FUNCTION" ADD CONSTRAINT "FK_FUNCTION_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "FUNCTION" ADD CONSTRAINT "FK_FUNCTION_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "FUNCTION" ADD CONSTRAINT "FK_FUNCTION_SOFTWARECONFIGURATION_SOFTWARECONFIGURATIONID" FOREIGN KEY ("SOFTWARECONFIGURATIONID")
	  REFERENCES "SOFTWARECONFIGURATION" ("SOFTWARECONFIGURATIONID") ENABLE;
