CREATE SEQUENCE "SUBFUNCTION_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL for Table SUBFUNCTION
--------------------------------------------------------

  CREATE TABLE "SUBFUNCTION" 
   (	"SUBFUNCTIONID" NUMBER(20,0) DEFAULT "SUBFUNCTION_SEQ"."NEXTVAL", 
	"FUNCTIONAREAID" NUMBER(20,0), 
	"SUBFUNCTIONNAME" NVARCHAR2(50), 
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index SUBFUNCTIONIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUBFUNCTIONIDX" ON "SUBFUNCTION" ("SUBFUNCTIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table SUBFUNCTION
--------------------------------------------------------

  ALTER TABLE "SUBFUNCTION" ADD CONSTRAINT "PK_SUBFUNCTION" PRIMARY KEY ("SUBFUNCTIONID")
  USING INDEX "SUBFUNCTIONIDX"  ENABLE;
  ALTER TABLE "SUBFUNCTION" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "SUBFUNCTION" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "SUBFUNCTION" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "SUBFUNCTION" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SUBFUNCTION
--------------------------------------------------------

  ALTER TABLE "SUBFUNCTION" ADD CONSTRAINT "FK_SUBFUNCTION_FUNCTIONAREA_FUNCTIONAREAID" FOREIGN KEY ("FUNCTIONAREAID")
	  REFERENCES "FUNCTIONAREA" ("FUNCTIONAREAID") ENABLE;
  ALTER TABLE "SUBFUNCTION" ADD CONSTRAINT "FK_SUBFUNCTION_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "SUBFUNCTION" ADD CONSTRAINT "FK_SUBFUNCTION_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
