CREATE SEQUENCE "XMLPARSERUN_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL for Table XMLPARSERUN
--------------------------------------------------------

  CREATE TABLE "XMLPARSERUN" 
   (	"XMLPARSERUNID" NUMBER(20,0) DEFAULT "XMLPARSERUN_SEQ"."NEXTVAL", 
	"FILENAME" NVARCHAR2(400), 
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp),
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp),	
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index XMLPARSERUN_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "XMLPARSERUN_IDX" ON "XMLPARSERUN" ("XMLPARSERUNID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table XMLPARSERUN
--------------------------------------------------------

  ALTER TABLE "XMLPARSERUN" ADD CONSTRAINT "PK_XMLPARSERUN" PRIMARY KEY ("XMLPARSERUNID")
  USING INDEX "XMLPARSERUN_IDX"  ENABLE;
  ALTER TABLE "XMLPARSERUN" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "XMLPARSERUN" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "XMLPARSERUN" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "XMLPARSERUN" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table XMLPARSERUN
--------------------------------------------------------

  ALTER TABLE "XMLPARSERUN" ADD CONSTRAINT "FK_XMLPARSERUN_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "XMLPARSERUN" ADD CONSTRAINT "FK_XMLPARSERUN_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;