using CAM.DataAttributes.Grid;
using CAM.DataTransferObjects.QueryDto.Base;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using OracleModels.DBModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CAM.DataTransferObjects.Entita.SoftwareConfiguration
{
    public class SoftwareConfigurationDto
    {
        #region //SoftwareConfiguration
        [OrderGrid(Order = 4)]
        [Default]
        public string ElementName { get; set; }
        [OrderGrid(Order = 5)]
        [Default]
        public string Oem { get; set; }
        
        //public string creationUser { get; set; }
        //public DateTime creationDate { get; set; }
        //public string modificationUser { get; set; }
        //public DateTime modificationDate { get; set; }
        #endregion

        //public IDictionary<short, string> Function { get; set; }
        #region //Function
        [OrderGrid(Order = 6)]
        //[Default]
        public long FunctionId { get; set; }
        [OrderGrid(Order = 7)]
        [Default]
        public string FunctionName { get; set; }
        //public string FunctionCreationUser { get; set; }
        //public DateTime FunctionCreationDate { get; set; }
        //public string FunctionModificationUser { get; set; }
        //public DateTime FunctionModificationDate { get; set; }
        #endregion
        #region //FunctionArea

        [OrderGrid(Order = 8)]
        //[Default]
        public long FunctionAreaId { get; set; }
        [OrderGrid(Order = 9)]
        [Default]
        public string FunctionAreaName { get; set; }
        public string FunctionAreaApplicationName { get; set; }
        public string BorderGatewayFunctionId { get; set; }
        public string CallRetentionTimer { get; set; }
        public string CapacityForPriorityCalls { get; set; }
        public string DateTimeoffSet { get; set; }
        public string DirectMediaRouting { get; set; }
        public string DnPrefix { get; set; }
        public string EnableOnDemandScaling { get; set; }
        public string EvsSupportedInMrf { get; set; }
        public string FailOverDetectionTimer { get; set; }
        public string ID { get; set; }
        public string LocalDateTime { get; set; }
        public string LocationName { get; set; }
        public string LogicalName { get; set; }
        public string ManagedElementId { get; set; }
        public string ManagedElementType { get; set; }
        public string ManagedElementTypeList { get; set; }
        public string MediaIpVersion { get; set; }
        public string MediaResourceFunctionId { get; set; }
        public string MmasId { get; set; }
        public string MtasFunctionBlackListTime { get; set; }
        public string MtasFunctionFullDiskPercentage { get; set; }
        public string MtasFunctionInvalidAddress { get; set; }
        public string MtasFunctionMaxSessionDuration { get; set; }
        public string MtasFunctionMccMnc { get; set; }
        public string MtasFunctionNetTraceVersion { get; set; }
        public string MtasFunctionRestart { get; set; }
        public string MtasFunctionVersion { get; set; }
        public string NetworkManagedElementId { get; set; }
        public string NeType { get; set; }
        public string PlatformType { get; set; }
        public string Release { get; set; }
        public string ScaleInThresHold { get; set; }
        public string ScaleOutThresHold { get; set; }
        public string ScalingMonitorInterval { get; set; }
        public string ShuttingDownTimer { get; set; }
        public string SignalingLocalPort { get; set; }
        public string FunAreaSignalingVlanId { get; set; }
        public string SiteId { get; set; }
        public string SiteLocation { get; set; }
        public string Slaacinuse { get; set; }
        public string SwVersion { get; set; }
        public string SystemFunctionsId { get; set; }
        public string TimeZone { get; set; }
        public string TranscodingRetention { get; set; }
        public string TransportId { get; set; }
        public string UserDefinedState { get; set; }
        public string FunAreaUserLabel { get; set; }
        public string VendorName { get; set; }
        public string Site { get; set; }
        public string Spdh { get; set; }
        public string IpoamId { get; set; }
        public string SacMode { get; set; }
        public string MimInfo { get; set; }
        public string MbacMode { get; set; }
        public string FunAreaCodingLaw { get; set; }
        public string DscpaudIo { get; set; }
        public string JavaCafId { get; set; }
        public string IpSystemId { get; set; }
        public string TfoipeMode { get; set; }
        public string DscpMarking { get; set; }
        public string EquipmentId { get; set; }
        public string FunAreaProductName { get; set; }
        public string ProductType { get; set; }
        public string Ipbcpt1Timer { get; set; }
        public string MbacThresHold { get; set; }
        public string DdbFunctionId { get; set; }
        public string DscFunctionId { get; set; }
        public string IpWorksRootId { get; set; }
        public string ProductNumber { get; set; }
        public string DscpMultiMedia { get; set; }
        public string LastHwpiChange { get; set; }
        public string LastUppiChange { get; set; }
        public string MrfCfunctionId { get; set; }
        public string MrfPfunctionId { get; set; }
        public string FunAreaMsProcessingId { get; set; }
        public string RtcPonnbActive { get; set; }
        public string SwitchFabricId { get; set; }
        public string SwManagementId { get; set; }
        public string SwServerUrlList { get; set; }
        public string ProductRevision { get; set; }
        public string FeatureStatEg722 { get; set; }
        public string IsLsupervisionId { get; set; }
        public string LicenseStatEg722 { get; set; }
        public string LicenseStateIpv6 { get; set; }
        public string LicenseStateMrfc { get; set; }
        public string MgwApplicationId { get; set; }
        public string MtasFunctionFqdn { get; set; }
        public string DoclibUserDefined { get; set; }
        public string SignallingProxyId { get; set; }
        public string HealthCheckResult { get; set; }
        public string AccessSignallingId { get; set; }
        public string LicenseCapacityBgf { get; set; }
        public string LicenseStateBgfEvs { get; set; }
        public string LicenseStateMrfEvs { get; set; }
        public string LogOnServerAddress { get; set; }
        public string TransportNetworkId { get; set; }
        public string LicenseCapacityMrfp { get; set; }
        public string LicenseStateBgfAtgw { get; set; }
        public string LicenseStateBgfIpv6 { get; set; }
        public string LicenseStateBgfSrtp { get; set; }
        public string LicenseStateHdAudio { get; set; }
        public string LicenseStateMrfIpv6 { get; set; }
        public string MbacLicensingStatus { get; set; }
        public string MbacWeightingFactor { get; set; }
        public string SerSupervisionTimer { get; set; }
        public string HealthCheckSchedule { get; set; }
        public string FeatureStateBgfSmsrp { get; set; }
        public string LicenseCapacityVideo { get; set; }
        public string LicenseStateBgfSmsrp { get; set; }
        public string ManagedElementDataId { get; set; }
        public string PowerSaveModeEnabled { get; set; }
        public string SpeechActivityFactor { get; set; }
        public string DocumentServerAddress { get; set; }
        public string FeatureStateBgfWebrtc { get; set; }
        public string LicenseStateBgfWebrtc { get; set; }
        public string MtasFunctionMmtasName { get; set; }
        public string MtasFunctionSccasName { get; set; }
        public string EthernetSwitchFabricId { get; set; }
        public string InteractiveMessagingId { get; set; }
        public string MbacCongestionDscpMode { get; set; }
        public string Piugroupescalationtype { get; set; }
        public string Saclowerthresholdalarm { get; set; }
        public string Scclowerthresholdalarm { get; set; }
        public string G711packetizationtimenb { get; set; }
        public string G729lowerthresholdalarm { get; set; }
        public string Mbaccongestiondscpvalue { get; set; }
        public string Mbacmeasurementinterval { get; set; }
        public string Sachigherthresholdalarm { get; set; }
        public string Scchigherthresholdalarm { get; set; }
        public string Voiplowerthresholdalarm { get; set; }
        public string Policycontrolfunctionid { get; set; }
        public string Amrwblowerthresholdalarm { get; set; }
        public string Autoconfigurationallowed { get; set; }
        public string G729higherthresholdalarm { get; set; }
        public string Voiphigherthresholdalarm { get; set; }
        public string Applicationconfiguration { get; set; }
        public string Mtasfunctionnwfoiwasname { get; set; }
        public string Mtasfunctionnwpriwasname { get; set; }
        public string Amrwbhigherthresholdalarm { get; set; }
        public string Licensecapacityvoicetrans { get; set; }
        public string Minimumhdvolumecfreespace { get; set; }
        public string Featurestatecontentsharing { get; set; }
        public string Intermittentfaultthreshold { get; set; }
        public string Licensestatecontentsharing { get; set; }
        public string Maxbandwidthforiptransport { get; set; }
        public string Featurestatedtmfsuppression { get; set; }
        public string Featurestatemscpoolproxygsm { get; set; }
        public string Licensecapacityhdvoicetrans { get; set; }
        public string Licensestatebgfprioritycall { get; set; }
        public string Licensestatemrfprioritycall { get; set; }
        public string Featurestatevoicetranscoding { get; set; }
        public string Rtcpbearersupervisiontimermb { get; set; }
        public string Rtcpbearersupervisiontimernb { get; set; }
        public string Cappercentreservedforwpscalls { get; set; }
        public string Featurestatemscpoolproxywcdma { get; set; }
        public string Explicitcongestionnotification { get; set; }
        public string Mbaclostpacketscalculationmode { get; set; }
        public string Rtcpbearersupervisiontimeraoip { get; set; }
        public string Rtcpbearersupervisiontimervoip { get; set; }
        public string Licensecapacityaudioconference { get; set; }
        public string Licensecapacityvideoconference { get; set; }
        public string Licensecapacityhdvidoconfernce { get; set; }
        public string MtasVtpadminState { get; set; }
        public string MtasFulldiskpercentage { get; set; }
        public string MtasAdministrativestate { get; set; }
        public string MtasMaxsessionduration { get; set; }
        public string MtasNotfulldiskpercentage { get; set; }
        public string MtasMaxnumofsesionsaction { get; set; }
        public string MtasMaxnumofsessions { get; set; }
        public string MtasMaxnumsubscriptsesion { get; set; }
        public string MtasScalingterminatwaitime { get; set; }
        public string MtasAdminStateafterrestrt { get; set; }
        //public string FunctionAreaCreationuser { get; set; }
        //public DateTime FunctionAreaCreationdate { get; set; }
        //public string FunctionAreaModificationuser { get; set; }
        //public DateTime FunctionAreaModificationdate { get; set; }
        #endregion
        #region //SubFunction
        [OrderGrid(Order = 10)]
        public long SubFunctionId { get; set; }
        [OrderGrid(Order = 11)]
        [Default]
        public string SubFunctionName { get; set; }

        //public string SubFunctionCreationuser { get; set; }
        //public DateTime SubFunctionCreationdate { get; set; }
        //public string SubFunctionModificationuser { get; set; }
        //public DateTime SubFunctionModificationdate { get; set; }
        #endregion
        #region //SubFunctionArea

        [OrderGrid(Order = 12)]
        //[Default]
        public long SubFunctionAreaId { get; set; }
        [OrderGrid(Order = 13)]
        [Default]
        public string SubFunctionAreaName { get; set; }

        [OrderGrid(Order = 14)]
        [Default]
        [MailTo]
        public string CreationUser { get; set; }
        //public string SubFunctionareacreationUser { get; set; }
        [OrderGrid(Order = 15)]
        [DateRangeGrid]
        [Default]
        public DateTime CreationDate { get; set; }
        //public DateTime SubFunctionareacreationDate { get; set; }
        [OrderGrid(Order = 16)]
        [Default]
        [MailTo]
        public string ModificationUser { get; set; }
        //public string SubFunctionareamodificationUser { get; set; }
        [OrderGrid(Order = 17)]
        [DateRangeGrid]
        [Default]
        public DateTime ModificationDate { get; set; }
        //public DateTime SubFunctionareamodificationDate { get; set; }
        public string Actioncapable { get; set; }
        public string Actioncapableinfo { get; set; }
        public string Active { get; set; }
        public string Activeswversion { get; set; }
        public string Admclasspath { get; set; }
        public string Administrativestate { get; set; }
        public string Admmain { get; set; }
        public string Admoptions { get; set; }
        public string Alphaindex { get; set; }
        public string Announcementsid { get; set; }
        public string Applicationname { get; set; }
        public string Area1 { get; set; }
        public string Assocmaxrtx { get; set; }
        public string Autoconfig { get; set; }
        public string Autoconfigidentity { get; set; }
        public string Autoconfigidentity2 { get; set; }
        public string Bcfdomainnameentry { get; set; }
        public string Bcfenabled { get; set; }
        public string Bcfoperationalstate { get; set; }
        public string Betaindex { get; set; }
        public string Bgfnetworksid { get; set; }
        public string Bgfresourceid { get; set; }
        public string Bgftrafficsupervisionid { get; set; }
        public string Brmid { get; set; }
        public string Capacityalarmhysteresis { get; set; }
        public string Capacityalarmthreshold { get; set; }
        public string Ccauagentuserlimit { get; set; }
        public string Ccauid { get; set; }
        public string Ccaureportingperiod { get; set; }
        public string Ccauserveruserlimit { get; set; }
        public string Ccauuoiaddress { get; set; }
        public string Ccauuoiport { get; set; }
        public string Ccauuoiretrytimeout { get; set; }
        public string Ccauuoitlsport { get; set; }
        public string Classnames { get; set; }
        public string Cookielife { get; set; }
        public string CscfCxalwaysuserelmbasedrout { get; set; }
        public string CscfDmainbasedpsiroutingentry { get; set; }
        public string CscfDmainroutActmatchTable { get; set; }
        public string CscfDmainroutSelectconfig { get; set; }
        public string CscfEnableglobalnumbernormal { get; set; }
        public string CscfEnumlocalnumbersenabled { get; set; }
        public string CscfGlobalnumnormalPhcontxt { get; set; }
        public string CscfMaxnonsupervisesessiondur { get; set; }
        public string CscfNablerecordroutesubscribe { get; set; }
        public string CscfNumprtbiltyrejectfailenum { get; set; }
        public string CscfReducedtransactlifespan { get; set; }
        public string CscfRemdialogonnegNotifyresp { get; set; }
        public string CscfReplsreqUriwithdefTimpu { get; set; }
        public string CscfServeduseridentityselect { get; set; }
        public string Cscfactiveusermethod { get; set; }
        public string Cscfadministrativestate { get; set; }
        public string Cscfakaalgorithmentry { get; set; }
        public string Cscfcicroutingenabled { get; set; }
        public string Cscfcxdestinationhost { get; set; }
        public string Cscfcxdestinationrealm { get; set; }
        public string Cscfcxoriginhost { get; set; }
        public string Cscfcxoriginrealm { get; set; }
        public string Cscfdatabasesweepertime { get; set; }
        public string Cscfdomainalias { get; set; }
        public string Cscfdomainroutingactiveconfig { get; set; }
        public string Cscfdomainroutingenabled { get; set; }
        public string Cscfdomainroutingsyncconfig { get; set; }
        public string Cscfdomainroutingsyncstate { get; set; }
        public string Cscfenumtopdomain { get; set; }
        public string Cscfextnetselonenumpstn { get; set; }
        public string Cscfextnetselonrnbeforeenum { get; set; }
        public string Cscfforkingtimer { get; set; }
        public string Cscfgaugeinterval { get; set; }
        public string Cscfispbehavior { get; set; }
        public string Cscfonwardroutingenabled { get; set; }
        public string Cscfoverridedefaultcontext { get; set; }
        public string Cscfphonecontext { get; set; }
        public string Cscfprovidedefaultcontext { get; set; }
        public string Cscfrequireuserequalphone { get; set; }
        public string Cscfscscffailovertimer { get; set; }
        public string Cscfsendrequestudponly { get; set; }
        public string Cscfsessionrefreshdefault { get; set; }
        public string Cscfsessionrefreshmax { get; set; }
        public string Cscfsessionrefreshmin { get; set; }
        public string Cscfsippmkey { get; set; }
        public string Cscfsmpauthorization { get; set; }
        public string Cscftimerbvalue { get; set; }
        public string Cscftimercvalue { get; set; }
        public string Cscftimerdalue { get; set; }
        public string Cscftimerfvalue { get; set; }
        public string Cscftimert1value { get; set; }
        public string Cscftimert2value { get; set; }
        public string Cscftimert4value { get; set; }
        public string Cscftrustednetwork { get; set; }
        public string Cscfunallocatetroutingenabled { get; set; }
        public string Cscfusagestate { get; set; }
        public string Datadirectories { get; set; }
        public string Defaultlanguagecode { get; set; }
        public string Dnscachesize { get; set; }
        public string Dnsclient1ref { get; set; }
        public string Dnsclient2ref { get; set; }
        public string Dnsexpiredcachebehavior { get; set; }
        public string Dnsid { get; set; }
        public string Dnslocaladdress { get; set; }
        public string Dnsretransmissiontimer { get; set; }
        public string Dnsserverentry { get; set; }
        public string Dscp { get; set; }
        public string Dscp00 { get; set; }
        public string Dscp01 { get; set; }
        public string Dscp02 { get; set; }
        public string Dscp03 { get; set; }
        public string Dscp04 { get; set; }
        public string Dscp05 { get; set; }
        public string Dscp06 { get; set; }
        public string Dscp07 { get; set; }
        public string Dscp08 { get; set; }
        public string Dscp09 { get; set; }
        public string Dscp10 { get; set; }
        public string Dscp11 { get; set; }
        public string Dscp12 { get; set; }
        public string Dscp13 { get; set; }
        public string Dscp14 { get; set; }
        public string Dscp15 { get; set; }
        public string Dscp16 { get; set; }
        public string Dscp17 { get; set; }
        public string Dscp18 { get; set; }
        public string Dscp19 { get; set; }
        public string Dscp20 { get; set; }
        public string Dscp21 { get; set; }
        public string Dscp22 { get; set; }
        public string Dscp23 { get; set; }
        public string Dscp24 { get; set; }
        public string Dscp25 { get; set; }
        public string Dscp26 { get; set; }
        public string Dscp27 { get; set; }
        public string Dscp28 { get; set; }
        public string Dscp29 { get; set; }
        public string Dscp30 { get; set; }
        public string Dscp31 { get; set; }
        public string Dscp32 { get; set; }
        public string Dscp33 { get; set; }
        public string Dscp34 { get; set; }
        public string Dscp35 { get; set; }
        public string Dscp36 { get; set; }
        public string Dscp37 { get; set; }
        public string Dscp38 { get; set; }
        public string Dscp39 { get; set; }
        public string Dscp40 { get; set; }
        public string Dscp41 { get; set; }
        public string Dscp42 { get; set; }
        public string Dscp43 { get; set; }
        public string Dscp44 { get; set; }
        public string Dscp45 { get; set; }
        public string Dscp46 { get; set; }
        public string Dscp47 { get; set; }
        public string Dscp48 { get; set; }
        public string Dscp49 { get; set; }
        public string Dscp50 { get; set; }
        public string Dscp51 { get; set; }
        public string Dscp52 { get; set; }
        public string Dscp53 { get; set; }
        public string Dscp54 { get; set; }
        public string Dscp55 { get; set; }
        public string Dscp56 { get; set; }
        public string Dscp57 { get; set; }
        public string Dscp58 { get; set; }
        public string Dscp59 { get; set; }
        public string Dscp60 { get; set; }
        public string Dscp61 { get; set; }
        public string Dscp62 { get; set; }
        public string Dscp63 { get; set; }
        public string Dscpdns { get; set; }
        public string Dscpsignaling { get; set; }
        public string Dscptopbitid { get; set; }
        public string Enablepathmtudiscovery { get; set; }
        public string Excessivetrafficthreshold { get; set; }
        public string Exportpackagelabelprefix { get; set; }
        public string ExtSelectActiveconfiguration { get; set; }
        public string ExtSelectDefaultpoolname { get; set; }
        public string ExtSelectIntialTablename { get; set; }
        public string ExtSelectIntialtransitName { get; set; }
        public string ExtSelectSynchronizatinstate { get; set; }
        public string ExtSelectTablesynchrnization { get; set; }
        public string Extnetselectionmaxtables { get; set; }
        public string Fallbacktimer { get; set; }
        public string Filemid { get; set; }
        public string Fingerprint { get; set; }
        public string Fingerprintupdateable { get; set; }
        public string Fmid { get; set; }
        public string Forcedsipuriescaping { get; set; }
        public string Gatewayaddress { get; set; }
        public string Generalprocessorunitid { get; set; }
        public string Healthcheckmid { get; set; }
        public string Heartbeatinterval { get; set; }
        public string Hostid { get; set; }
        public string HssAdministrativestate { get; set; }
        public string HssErewildcardsupport { get; set; }
        public string HssExtdbconfiglogactive { get; set; }
        public string HssExtdbconfigrootdnlist { get; set; }
        public string HssExtdbconfigurllist { get; set; }
        public string HssExtdbmaxconcurrentclients { get; set; }
        public string HssExtdburlpasswordlist { get; set; }
        public string HssIsdatacacheused { get; set; }
        public string HssNodeidentity { get; set; }
        public string HssSmnodeidentity { get; set; }
        public string Icmpbarringtime { get; set; }
        public string Icmpenabled { get; set; }
        public string Icmpintermittencyinterval { get; set; }
        public string Icmpintermittenttolerance { get; set; }
        public string Icmpmessagedistribution { get; set; }
        public string Icscfdomainnameentry { get; set; }
        public string Icscfnoninvitefailovertimer { get; set; }
        public string Icscftransitenabled { get; set; }
        public string funareaId { get; set; }
        public string Imsakaregistrarusesrcip { get; set; }
        public string Imsakaremovedialogunprotrereg { get; set; }
        public string Imsakareusetcptermcall { get; set; }
        public string Initrto { get; set; }
        public string Interface1 { get; set; }
        public string Interface2 { get; set; }
        public string Ipaccesshostgpbid { get; set; }
        public string Ipaddress1 { get; set; }
        public string Ipaddress2 { get; set; }
        public string Ipaddressesinuselist { get; set; }
        public string Ipdefaultttl { get; set; }
        public string Ippoolrangeend { get; set; }
        public string Ippoolrangestart { get; set; }
        public string Ippoolstate { get; set; }
        public string Ipsubnet { get; set; }
        public string Javacafappid { get; set; }
        public string Jvmid { get; set; }
        public string L3ref { get; set; }
        public string Lastexecutedjob { get; set; }
        public string Lastinventorychange { get; set; }
        public string Lastlicenseinventoryrefresh { get; set; }
        public string Lasttransferresult { get; set; }
        public string Lastupdatetime { get; set; }
        public string Licenseexpirationwarning { get; set; }
        public string Lmid { get; set; }
        public string Lmstate { get; set; }
        public string Localfilestorepath { get; set; }
        public string Localipaddress { get; set; }
        public string Localportnumber { get; set; }
        public string Localserverid { get; set; }
        public string Lockingcode { get; set; }
        public string Logactive { get; set; }
        public string Logmid { get; set; }
        public string M3uanoofattempsofdauds { get; set; }
        public string Maxburst { get; set; }
        public string Maxnoofreportfiles { get; set; }
        public string Maxrnitrt { get; set; }
        public string Maxrto { get; set; }
        public string Maxsctppdusize { get; set; }
        public string Maxsizechangebuf { get; set; }
        public string Maxsizereroutbuf { get; set; }
        public string Maxwaittimepertcpframe { get; set; }
        public string Mediavlanid { get; set; }
        public string Minrto { get; set; }
        public string MpvLogstatus { get; set; }
        public string Mrfconfigurationid { get; set; }
        public string Mrfh248controlid { get; set; }
        public string Mrfresourceid { get; set; }
        public string Mrfsipcontrolid { get; set; }
        public string Mtaschargacrstoragemaxfilesize { get; set; }
        public string Mtaschargacrstoragemaxnbracr { get; set; }
        public string Mtaschargeventmeasurementtimer { get; set; }
        public string Mtascharging { get; set; }
        public string Mtaschargingacrbackupfiles { get; set; }
        public string Mtaschargingacrstorage { get; set; }
        public string Mtaschargingacrstoragemaxtime { get; set; }
        public string Mtaschargingdeactivateddests { get; set; }
        public string Mtaschargingdefaultcdfaddress { get; set; }
        public string Mtaschargingoriginatingonline { get; set; }
        public string Mtaschargingrttiadminstate { get; set; }
        public string Mtaschargingterminatingonline { get; set; }
        public string Mtaschargingxtimer { get; set; }
        public string Mtaschargoriginatingoffline { get; set; }
        public string Mtaschargreportredirectnum { get; set; }
        public string Mtaschargschduleconfrnceofline { get; set; }
        public string Mtaschargsubscribecreditnotif { get; set; }
        public string Mtaschargterminatingoffline { get; set; }
        public string Mtascomdeetslclstormaxfilesize { get; set; }
        public string Mtascomdeetslclstormaxnbracr { get; set; }
        public string Mtascomdetaillclstormaxtime { get; set; }
        public string Mtascomdetails { get; set; }
        public string Mtascomdetailsinterfaceversion { get; set; }
        public string Mtascomdetailsprimecdsaddress { get; set; }
        public string Mtascomdetailssecondcdsaddress { get; set; }
        public string Mtascomdetailsservcontext { get; set; }
        public string Mtascommondata { get; set; }
        public string Mtascondetailsreportingtype { get; set; }
        public string Mtascsi { get; set; }
        public string Mtascsiadministrativestate { get; set; }
        public string Mtascsiglobaltitle { get; set; }
        public string Mtascsiremotescfsubsystemnum { get; set; }
        public string Mtascsiscfsubsystemnumber { get; set; }
        public string Mtascsissfsubsystemnumber { get; set; }
        public string Mtasdxmsretryaftermaximum { get; set; }
        public string Mtasgls { get; set; }
        public string Mtasmediaframework { get; set; }
        public string Mtasmrfc { get; set; }
        public string Mtaspx { get; set; }
        public string Mtasservices { get; set; }
        public string Mtassh { get; set; }
        public string Mtassip { get; set; }
        public string Mtassipcalloutofbluerouting { get; set; }
        public string Mtassipcancel2finalresptimer { get; set; }
        public string Mtassipcnameport { get; set; }
        public string Mtassipdefaultminse { get; set; }
        public string Mtassipdefaultsessionexpiry { get; set; }
        public string Mtassipdisablelargemsgcheck { get; set; }
        public string Mtassipfailovertimeinvite { get; set; }
        public string Mtassipfailovertimenoninvite { get; set; }
        public string Mtassipicscfname { get; set; }
        public string Mtassipinvite2finalresptimer { get; set; }
        public string Mtassipipdscpmarking { get; set; }
        public string Mtassipipversion { get; set; }
        public string Mtassipoptionsuri { get; set; }
        public string Mtassiporiginatingaschaining { get; set; }
        public string Mtassippresenceport { get; set; }
        public string Mtassipprotocolmtasorigcall { get; set; }
        public string Mtassippsiport { get; set; }
        public string Mtassiprsport { get; set; }
        public string Mtassipsccorigport { get; set; }
        public string Mtassipsccorigunregport { get; set; }
        public string Mtassipscctermport { get; set; }
        public string Mtassipscctermunregport { get; set; }
        public string Mtassipsdpans200 { get; set; }
        public string Mtassipserveruseragentheader { get; set; }
        public string Mtassipsteppingolinesesionvr { get; set; }
        public string Mtassipstport { get; set; }
        public string Mtassipsuperviseallsessions { get; set; }
        public string Mtassiptcpconnectiontimeout { get; set; }
        public string Mtassiptimerb { get; set; }
        public string Mtassiptimerf { get; set; }
        public string Mtassiptimert1 { get; set; }
        public string Mtassiptimert2 { get; set; }
        public string Mtassiptrafficorigunregipport { get; set; }
        public string Mtassiptraficoriginatingipport { get; set; }
        public string Mtassiptraficterminatingipport { get; set; }
        public string Mtassiptransportincontact { get; set; }
        public string Mtassipuesessiontimersupport { get; set; }
        public string Mtassubsdata { get; set; }
        public string Mtassubsdatacachecontactdata { get; set; }
        public string Mtassubsdatacachepani { get; set; }
        public string Mtassubsdatadefaultregtimer { get; set; }
        public string Mtassubsdataderegtimer { get; set; }
        public string Mtassubsdatahssoverloadtimer { get; set; }
        public string Mtassubsdatainitregfetchdelay { get; set; }
        public string Mtassubsdatamobileclass { get; set; }
        public string Mtassubsdatapinformat { get; set; }
        public string Mtassubsdataregistrationmode { get; set; }
        public string Mtassubsdataservicerecordlimit { get; set; }
        public string Mtassubsdatastlastsessiontimer { get; set; }
        public string Mtassubsdatavoltecasename { get; set; }
        public string Mtassupportfunctionsid { get; set; }
        public string Mtassystemconstant { get; set; }
        public string Mtassystemconstantsc { get; set; }
        public string Mtassystemconstantsc1 { get; set; }
        public string Mtassystemconstantsc10 { get; set; }
        public string Mtassystemconstantsc2 { get; set; }
        public string Mtassystemconstantsc3 { get; set; }
        public string Mtassystemconstantsc4 { get; set; }
        public string Mtassystemconstantsc5 { get; set; }
        public string Mtassystemconstantsc6 { get; set; }
        public string Mtassystemconstantsc7 { get; set; }
        public string Mtassystemconstantsc8 { get; set; }
        public string Mtassystemconstantsc9 { get; set; }
        public string Mtastrace { get; set; }
        public string Mtastracedefcritconfigprminute { get; set; }
        public string Mtastracedeftraceprintsubsckey { get; set; }
        public string Mtastracedefwarningprminute { get; set; }
        public string Mtastracedisableehser { get; set; }
        public string Mtasubdataregeventrsponsetimer { get; set; }
        public string Mtaswebservices { get; set; }
        public string Mtaswebserviceslocalport { get; set; }
        public string Mtaswsnamedb { get; set; }
        public string Mtasxdms { get; set; }
        public string Mtasxdmscai3gadminstate { get; set; }
        public string Mtasxdmscai3ginactivitytimeout { get; set; }
        public string Mtasxdmscai3ginterfacepriority { get; set; }
        public string Mtasxdmscai3glogging { get; set; }
        public string Mtasxdmscai3gmaximumsessions { get; set; }
        public string Mtasxdmsccmpadminstate { get; set; }
        public string Mtasxdmsccmpinterfacepriority { get; set; }
        public string Mtasxdmsretryafterminimum { get; set; }
        public string Mtasxdmsutadministrativestate { get; set; }
        public string Mtasxdmsutinterfacepriority { get; set; }
        public string Mtasxdmsxcaprespcontenttype { get; set; }
        public string Mtp3bspituid { get; set; }
        public string Networkappearance { get; set; }
        public string Networkind { get; set; }
        public string Networkprefixlength1 { get; set; }
        public string Networkprefixlength2 { get; set; }
        public string Nodebehaviour { get; set; }
        public string Nonregisteredusersallowedforec { get; set; }
        public string Nonreguserallowforecnrmlbearer { get; set; }
        public string Noofattempofassociationest { get; set; }
        public string Noofcongestlevelforni { get; set; }
        public string NumNormalTablesyncstate { get; set; }
        public string Pathmaxrtx { get; set; }
        public string Pmid { get; set; }
        public string Pool { get; set; }
        public string Portnumber { get; set; }
        public string Primarypathmaxrtx { get; set; }
        public string RadLogstatus { get; set; }
        public string Readonlyclassnames { get; set; }
        public string Reassemblytimeout { get; set; }
        public string Referencetolicenseserver { get; set; }
        public string Replicationgroup { get; set; }
        public string Reportprogress { get; set; }
        public string Resendtfcinterval { get; set; }
        public string Routesetcongesttestflag { get; set; }
        public string Rpuid { get; set; }
        public string Sacktimer { get; set; }
        public string Sbglistid { get; set; }
        public string Scscfcontacturimatchingenabled { get; set; }
        public string Scscfdomainnameentry { get; set; }
        public string Sctpendpointid { get; set; }
        public string Sctpprofileid { get; set; }
        public string Secmid { get; set; }
        public string Serverreconnectattemptinterval { get; set; }
        public string Serversynchronizationinterval { get; set; }
        public string Sigcompcompressionalgorithm { get; set; }
        public string Sigcompcompressiontype { get; set; }
        public string Signalingippoolid { get; set; }
        public string Signalingvlanid { get; set; }
        public string Signallingpointcode { get; set; }
        public string Siospare { get; set; }
        public string Smmstate { get; set; }
        public string Sppriority { get; set; }
        public string Sptimer { get; set; }
        public string Statusindinterval { get; set; }
        public string Subnetmasklength { get; set; }
        public string Swinventoryid { get; set; }
        public string Swmid { get; set; }
        public string Sysmid { get; set; }
        public string Testpatternsltm { get; set; }
        public string Transferlogstatus { get; set; }
        public string Transfrhandler { get; set; }
        public string Userlabel { get; set; }
        public string Usesgwmgmtmapping { get; set; }
        public string Version { get; set; }
        public string Ignoreicmpdestunreachable { get; set; }
        public string Ignorertcpbye { get; set; }
        public string Imbasicmessageid { get; set; }
        public string Immessagecompositionid { get; set; }
        public string Imserviceid { get; set; }
        public string Imstreamer { get; set; }
        public string Internallinkgroupid { get; set; }
        public string Ipaccesshostetid { get; set; }
        public string Ipaccesshostgpbmoref { get; set; }
        public string Ipaddress { get; set; }
        public string Ipinterfacemoref { get; set; }
        public string Ipmuxcollectiontime { get; set; }
        public string Ipmuxlocaludpport { get; set; }
        public string Ipmuxrtpheadercompression { get; set; }
        public string Ipnetworkid { get; set; }
        public string Isdnv110resynctimer { get; set; }
        public string Isdnv110synctimer { get; set; }
        public string Iteration { get; set; }
        public string Languagecode { get; set; }
        public string Linespeechleveldl { get; set; }
        public string Linespeechlevelul { get; set; }
        public string Listofmessages { get; set; }
        public string Lockout { get; set; }
        public string Lowfreqlevel { get; set; }
        public string Maxconsecutivesrejs { get; set; }
        public string Maxduration { get; set; }
        public string Mccmode { get; set; }
        public string Messageid { get; set; }
        public string Mgclabel { get; set; }
        public string Mindigitpause { get; set; }
        public string Minduration { get; set; }
        public string Mininterworkingduration { get; set; }
        public string Mininterworkingpause { get; set; }
        public string Mobileaccessconn { get; set; }
        public string Mrfcapplicationid { get; set; }
        public string Mspgid { get; set; }
        public string Mtaschargingacrcachingmaxtime { get; set; }
        public string Mtascharginganiwithouttrigger { get; set; }
        public string Mtaschargingccrcachingmaxtime { get; set; }
        public string Mtaschargingtimezonesource { get; set; }
        public string Mtaschargingtxtimer { get; set; }
        public string Mtascomdetailsreportingtype { get; set; }
        public string Mtasdns { get; set; }
        public string Mtasdnsmonitoringenabled { get; set; }
        public string Mtashttp { get; set; }
        public string Mtashttprequesttimeout { get; set; }
        public string Mtaslicenses { get; set; }
        public string Mtasscaling { get; set; }
        public string Mtasscalingscalein { get; set; }
        public string Mtasscalingscaleout { get; set; }
        public string Mtassipasgenericport { get; set; }
        public string Mtassipipaddresslist { get; set; }
        public string Mtassipipdscpprioritymarking { get; set; }
        public string Mtassipipversionpreference { get; set; }
        public string Mtassipretryaftersupport { get; set; }
        public string Mtassipretryaftertime { get; set; }
        public string Mtassipsdpstrictmatching { get; set; }
        public string Mtassiptcpsessiondelayack { get; set; }
        public string Mtassiptcpsessionnodelay { get; set; }
        public string Mtassiptraffictermunregipport { get; set; }
        public string Mtassiptransparentearlybye { get; set; }
        public string Mtassiptransparenttelcontact { get; set; }
        public string Mtassubsdataregeventnotifier { get; set; }
        public string Mtassubsdatasccatcfinfoinhss { get; set; }
        public string Mtasxdmscai3gipaddresslist { get; set; }
        public string Mtasxdmsretryaftermaximum { get; set; }
        public string Mtasxdmsutheader { get; set; }
        public string Mtasxdmsutipaddresslist { get; set; }
        public string Mtasxdmsutvalidation { get; set; }
        public string Mtp2profileituid { get; set; }
        public string Mtp2tpituid { get; set; }
        public string Mtp3bapmoref { get; set; }
        public string Networkidentity { get; set; }
        public string Networkprefix { get; set; }
        public string Networkprefixlength { get; set; }
        public string Noisereductionconfiguration { get; set; }
        public string Noisereductionmode { get; set; }
        public string Nonlinearprocessormode { get; set; }
        public string Notificationconfigid { get; set; }
        public string Nraoipmode { get; set; }
        public string Nriumode { get; set; }
        public string Nrmode { get; set; }
        public string Nrserviceid { get; set; }
        public string Nrtdmmode { get; set; }
        public string Ntpdscp { get; set; }
        public string Ntpservermode { get; set; }
        public string Numberofslots { get; set; }
        public string Operationalstate { get; set; }
        public string Os155spistandbyid { get; set; }
        public string Os155spiworkingid { get; set; }
        public string Otpdiaproduct { get; set; }
        public string Partialfill { get; set; }
        public string Payloadprocessorfailuretimer { get; set; }
        public string Pcfconfigid { get; set; }
        public string Pcmserviceid { get; set; }
        public string Pcmsystemnr { get; set; }
        public string Pcscfdomainnameentry { get; set; }
        public string Pluginunitid { get; set; }
        public string Poolid { get; set; }
        public string Priority { get; set; }
        public string Prioritycallssupport { get; set; }
        public string Productname { get; set; }
        public string Rdisecondarysf { get; set; }
        public string Remotesiteprefix { get; set; }
        public string Reportperiod { get; set; }
        public string Reservedby { get; set; }
        public string Resourceaccesscontainerid { get; set; }
        public string Rlpmaxretransmission { get; set; }
        public string Rlpmultilinkwindowsizeiwfms { get; set; }
        public string Rlpmultilinkwindowsizemsiwf { get; set; }
        public string Rlpreseqtimert4a { get; set; }
        public string Rlpreseqtimert4b { get; set; }
        public string Rlpretranstimert1 { get; set; }
        public string Rlptimert1a { get; set; }
        public string Rlptimert1b { get; set; }
        public string Rlpwindowsizeiwfms { get; set; }
        public string Rlpwindowsizemsiwf { get; set; }
        public string Routeparamgrpmoref { get; set; }
        public string Rpumoref { get; set; }
        public string Rtprtcpserviceid { get; set; }
        public string Smsnotificationfrom { get; set; }
        public string Startupcontactpoints { get; set; }
        public string Subrackid { get; set; }
        public string Subracknumber { get; set; }
        public string Subrackposition { get; set; }
        public string Subrackprodtyperef { get; set; }
        public string Subracktype { get; set; }
        public string Switchmodule { get; set; }
        public string Switchmodulenumber1 { get; set; }
        public string Switchmodulenumber2 { get; set; }
        public string Tdmtermgrpid { get; set; }
        public string Tdmtermgrpmos { get; set; }
        public string Tfoserviceid { get; set; }
        public string Tonedisablerhangovermode { get; set; }
        public string Tonedisablermode { get; set; }
        public string Udiasynctransgsmsupport { get; set; }
        public string Uetraceid { get; set; }
        public string NodeUser { get; set; }
        public string Vendorid { get; set; }
        public string Vmgwid { get; set; }
        public string Vmidinalarmadditionaltext { get; set; }
        public string Vpp1moref { get; set; }
        public string Vpp2moref { get; set; }
        public string Codinglaw { get; set; }
        public string Maxinitrt { get; set; }
        public string Msprocessingid { get; set; }
        public string Cscftimerdvalue { get; set; }
        public string Cscfispoperationalstate { get; set; }
        public string Cscfunallocatedroutingenabled { get; set; }
        public string Dasid { get; set; }
        public string HssCommonfeaturenodeidentity { get; set; }
        public string HssEsmnodeidentity { get; set; }
        public string Entitydataid { get; set; }
        public string Firmwarerevision { get; set; }
        public string Flexiblediameterid { get; set; }
        public string Emergencycallpriority { get; set; }
        public string Mtasscaltimebasedscalenabled { get; set; }
        public string Mtassubsdtasccinitselctawarnes { get; set; }
        public string Mtasxdmscai3girsdeftimpuusage { get; set; }
        public string Mtassubsdtammteldvicefilexclde { get; set; }
        public string Mtastraceehprintreasonsubsid { get; set; }
        public string Mtasxdmscallidnumnormtranslat { get; set; }
        public string Mtassubsdtamteldvicefiltinclde { get; set; }
        public string Mtastrcehprintresonsipresonhed { get; set; }
        public string Mtastrcehprtresonsiprdndercode { get; set; }
        public string Mtassubsdtadisblenotifirsupdte { get; set; }
        public string Mtastrcehprintreasonsipwarnhed { get; set; }
        public string Mtaschargccrstoragemaxnoofccr { get; set; }
        public string Mtaschargccrstormaxtimeperfile { get; set; }
        public string Mtaschargsubsccrednotifvddir { get; set; }
        public string Mtaschargmrfusrinputerhandlprf { get; set; }
        public string Mtaschargsubscrednotifmrfoffer { get; set; }
        public string Mtaschargccrstoragemaxfilesize { get; set; }
        public string Mtaschrgsubcrnotifoferestmdtrg { get; set; }
        public string Mtassipenblsesionreferlyupdte { get; set; }
        public string Mtassipadditionalinfoinnegresp { get; set; }
        public string Mtassipsuportpserveduserheader { get; set; }
        public string Mtassipofferanswerexchangectrl { get; set; }
        public string Mtassipsdpinsesionrefreshresp { get; set; }
        public string Noofattmpofassociationestablsh { get; set; }
        public string Mtassipremsuportedhedineresp { get; set; }
        public string Mtasipremreferparaminerlyupdte { get; set; }
        public string Mtasiptermioncnclndanscrsovr { get; set; }
        public string Mtasipchngreferoleininvndupdte { get; set; }
        public string Mtassipsesrefnegoinerlyupdte { get; set; }
        public string Degcausemsp { get; set; }
        public string Bgfmediaqualitymonitoringid { get; set; }
        public string Ds0bundleid { get; set; }
        public string Malicioustrafficlogging { get; set; }
        public string Crcerrorthreshold { get; set; }
        public string Excessivetrafficlogging { get; set; }
        public string Malicioustrafficthreshold { get; set; }
        public string Imstreamerlabel { get; set; }
        public string Piubackupidentity { get; set; }
        public string Imstreamerid { get; set; }
        public string Piuidentity { get; set; }
        public string Lapdrpumoref { get; set; }
        public string Lapdid { get; set; }
        public string Vid { get; set; }
        public string Vlantype { get; set; }
        public string Vlanid { get; set; }
        public string Otherloadername { get; set; }
        public string Deviceloadername { get; set; }
        public string Loadmoduleid { get; set; }
        public string Issignedsw { get; set; }
        public string Productdata { get; set; }
        public string Loadmodulefilepath { get; set; }
        public string Programmustbesingleton { get; set; }
        public string Moppletentries { get; set; }
        public string Deviceloaderinformation { get; set; }
        public string Filestate { get; set; }
        public string Oseprogramloadclass { get; set; }
        public string Reliableprogramlabel { get; set; }
        public string Oseprogramheapsize { get; set; }
        public string Preload { get; set; }
        public string Loadertype { get; set; }
        public string Isdirectory { get; set; }
        public string Fileformat { get; set; }
        public string Oseprogrampoolsiz { get; set; }
        public string Upfilepathonftpserver { get; set; }
        public string Origucfchecksum { get; set; }
        public string Ucfchecksum { get; set; }
        public string Replication { get; set; }
        public string Admactiveslot { get; set; }
        public string Switchover { get; set; }
        public string Normalisation { get; set; }
        public string Admpassiveslot { get; set; }
        public string Reliableprogramuniterid { get; set; }
        public string Swallocationid { get; set; }
        public string Role { get; set; }
        public string Slotlist { get; set; }
        public string Repertoirelist { get; set; }
        public string Repertoireid { get; set; }
        public string Name { get; set; }
        public string Boardwidth { get; set; }
        public string Defallowedseqrestarts { get; set; }
        public string Lmfilesinstallstate { get; set; }
        public string Piutypeid { get; set; }
        public string Qoshigherthreshold { get; set; }
        public string Qoslowerthreshold { get; set; }
        public string Msdevicepoolid { get; set; }
        public string Idlelevelhigherthreshold { get; set; }
        public string Capcitylvlrsrvdforprioritycall { get; set; }
        public string Idlelevellowerthreshold { get; set; }
        public string Opusserviceid { get; set; }
        public string Mpcserviceid { get; set; }
        public string Comfortnoiselevel { get; set; }
        public string Dbrule { get; set; }
        public string Transparentmode { get; set; }
        public string Comfortnoise { get; set; }
        public string Continuitycheckserviceid { get; set; }
        public string Maxadmittedpause { get; set; }
        public string Waitackentime { get; set; }
        public string Mintonetime { get; set; }
        public string Maintime { get; set; }
        public string Initialdelay { get; set; }
        public string Endmaintime { get; set; }
        public string G722serviceid { get; set; }
        public string Initdejitterbuffersizeatmran { get; set; }
        public string Tonesenderserviceid { get; set; }
        public string Csdmodemserviceid { get; set; }
        public string V25callingtoneenabled { get; set; }
        public string Nocarriertimer { get; set; }
        public string Modemtransmitlevel { get; set; }
        public string Receivethresholdlevel { get; set; }
        public string T30errorcorrectionmode { get; set; }
        public string T38faxserviceid { get; set; }
        public string Licensestatet38fax { get; set; }
        public string Featurestateasc { get; set; }
        public string Ascserviceid { get; set; }
        public string Licensestateasc { get; set; }
        public string Csdgsmfhserviceid { get; set; }
        public string Gsmv110synchframes { get; set; }
        public string Gsmv110synchtimer { get; set; }
        public string Noofatrausynchframes { get; set; }
        public string Gsmv110resynchtimer { get; set; }
        public string Tinit { get; set; }
        public string Ninit { get; set; }
        public string Upfhserviceid { get; set; }
        public string Trc { get; set; }
        public string Nrc { get; set; }
        public string Dsploadlowthreshold { get; set; }
        public string Evsserviceid { get; set; }
        public string Dsploadhighthreshold { get; set; }
        public string Vbdserviceid { get; set; }
        public string Detectionfilterlist { get; set; }
        public string Expediteansdetection { get; set; }
        public string Licensestatevbdgw { get; set; }
        public string Amrwbserviceid { get; set; }
        public string Ipetserviceid { get; set; }
        public string Mobilecrosstalkcontrolmode { get; set; }
        public string Mcctdmmode { get; set; }
        public string Mccserviceid { get; set; }
        public string Mccaoipmode { get; set; }
        public string Mcciumode { get; set; }
        public string Subrackprodtypeid { get; set; }
        public string Fanconfiguration { get; set; }
        public string Boardpositions { get; set; }
        public string Maxpowerdissipation { get; set; }
        public string Defnumberofslots { get; set; }
        public string Transmissiontype { get; set; }
        public string Switchoveronethlinkqosdegr { get; set; }
        public string Switchoveronnexthopfault { get; set; }
        public string Addrcollsolvedthreshold { get; set; }
        public string Nexthopslowsupervisiontimer { get; set; }
        public string Addrcollsupervisiontimer { get; set; }
        public string Bgfnetworksupervisionid { get; set; }
        public string Nexthopreachablethreshold { get; set; }
        public string Nexthopfastsupervisiontimer { get; set; }
        public string Nexthopdownsupervisiontimer { get; set; }
        public string Dscptopbit { get; set; }
        public string Bgfdscptopbitid { get; set; }
        public string Efrserviceid { get; set; }
        public string Profiledata { get; set; }
        public string Amrserviceid { get; set; }
        public string Highfreqlevel { get; set; }
        public string Dtmfsenderserviceid { get; set; }
        public string Aal2spid { get; set; }
        public string G711packetlossconcealmentext { get; set; }
        public string A2ea { get; set; }
        public string Dtxsupport { get; set; }
        public string Gsmfrserviceid { get; set; }
        public string Csdgsmfaxserviceid { get; set; }
        public string Gsmhrserviceid { get; set; }
        public string G711packetlossconcealmentnb { get; set; }
        public string G711packetlossconcealmentmb { get; set; }
        public string G711packetlossconcealmentunid { get; set; }
        public string Delayaftericmpdestunreach { get; set; }
        public string Delayafterrtcpbye { get; set; }
        public string Featurestateipmultiplexing { get; set; }
        public string Featurestateipmuxextsipi { get; set; }
        public string G729serviceid { get; set; }
        public string Ecserviceid { get; set; }
        public string Endpathdelay { get; set; }
        public string Csddigitalserviceid { get; set; }
        public string Gttserviceid { get; set; }
        public string Baudrateul { get; set; }
        public string G719serviceid { get; set; }
        public string Cabinetposition { get; set; }
        public string Devicename { get; set; }
        public string Activegcptransportlayer { get; set; }
        public string Handoffmgcid { get; set; }
        public string Gcpassociationmoref { get; set; }
        public string Gcpprofile { get; set; }
        public string Availabilitystatus { get; set; }
        public string Emergencycapacitymargin { get; set; }
        public string Bgfapplicationid { get; set; }
        public string Cdvt { get; set; }
        public string Ds0bundlemoref { get; set; }
        public string Duration { get; set; }
        public string Hdfilename { get; set; }
        public string Filename { get; set; }
        public string Filepath { get; set; }
        public string Hdfilepath { get; set; }
        public string Oseprogrampoolsize { get; set; }
        public string Progresscount { get; set; }
        public string Hsivariant { get; set; }
        public string Progresstotal { get; set; }
        public string Progressheaderaddinfo { get; set; }
        public string Actualtypeofup { get; set; }
        public string Actionresult { get; set; }
        public string Password { get; set; }
        public string Maxtimebetweenupgradeevents { get; set; }
        public string Progressheader { get; set; }
        public string Upgradepackageid { get; set; }
        public string State { get; set; }
        public string Sendevents { get; set; }
        public string Preupgradestate { get; set; }
        public string Steplabel { get; set; }
        public string Requestedtypeofup { get; set; }
        public string Filterdtmfforvoipcalls { get; set; }
        public string Detectionsensitivity { get; set; }
        public string Powerthreshold { get; set; }
        public string Dtmfreceiverserviceid { get; set; }
        public string Mindejitterbuffersizemb { get; set; }
        public string Jitterservicetypeipcn { get; set; }
        public string Mindejitterbuffersizevoip { get; set; }
        public string Jitterservicetypemb { get; set; }
        public string Mindejitterbuffersizeext { get; set; }
        public string Maxdejitterbuffersizemb { get; set; }
        public string Jitterservicetypeatmcn { get; set; }
        public string Maxdejitterbuffersizeipran { get; set; }
        public string Jitterservicetypeaoip { get; set; }
        public string Mindejitterbuffersizeaoip { get; set; }
        public string Mindejitterbuffersizeipcn { get; set; }
        public string Maxdejitterbuffersizeatmran { get; set; }
        public string Mindejitterbuffersizeatmcn { get; set; }
        public string Maxdejitterbuffersizeatmcn { get; set; }
        public string Initialdejitterbuffersizemb { get; set; }
        public string Jitterhandlingserviceid { get; set; }
        public string Initialdejitterbuffersizeipran { get; set; }
        public string Initialdejitterbuffersizevoip { get; set; }
        public string Initialdejitterbuffersizeatmcn { get; set; }
        public string Dejitterbuffersizet38faxmb { get; set; }
        public string Mindejitterbuffersizeipran { get; set; }
        public string Maxdejitterbuffersizeaoip { get; set; }
        public string Weightfactor { get; set; }
        public string Licensestateadaptivejittercomp { get; set; }
        public string Maxdejitterbuffersizeext { get; set; }
        public string Dejitterbuffersizevbdmb { get; set; }
        public string Maxdejitterbuffersizeipcn { get; set; }
        public string Jitterservicetypeipran { get; set; }
        public string Mindejitterbuffersizeatmran { get; set; }
        public string Initialdejitterbuffersizeext { get; set; }
        public string Initialdejitterbuffersizeaoip { get; set; }
        public string Maxdejitterbuffersizevoip { get; set; }
        public string Jitterservicetypeatmran { get; set; }
        public string Dejitterbuffersizet38faxext { get; set; }
        public string Dejitterbuffersizevbdext { get; set; }
        public string Jitterservicetypeext { get; set; }
        public string Jitterservicetypevoip { get; set; }
        public string Initialdejitterbuffersizeipcn { get; set; }
        //public virtual Subfunction Subfunction { get; set; }
        #endregion
        #region //SubfunctionArea2
        public decimal Subfunctionarea2id { get; set; }
        //public int Subfunctionarea2Creationuser { get; set; }
        //public DateTime Subfunctionarea2Creationdate { get; set; }
        //public int? Subfunctionarea2Modificationuser { get; set; }
        //public DateTime Subfunctionarea2Modificationdate { get; set; }
        public string Tsack { get; set; }
        public string Maxincomingstream { get; set; }
        public string Heartbeatmaxburst { get; set; }
        public string Potentiallyfailedmaxrtx { get; set; }
        public string Mbuffer { get; set; }
        public string Npercentage { get; set; }
        public string Bundlingtimer { get; set; }
        public string Minimumrto { get; set; }
        public string Allowedincrementcookielife { get; set; }
        public string Maxshutdownrtratt { get; set; }
        public string Validcookielife { get; set; }
        public string Initialadrecwin { get; set; }
        public string Maxoutgoingstream { get; set; }
        public string Numberofassociations { get; set; }
        public string Initialrto { get; set; }
        public string Pathselection { get; set; }
        public string Bundlingactivated { get; set; }
        public string Switchbackminthreshold { get; set; }
        public string Switchbackmaxthreshold { get; set; }
        public string Sctpid { get; set; }
        public string Keychangeperiod { get; set; }
        public string Rtoalphaindex { get; set; }
        public string Maxuserdatasize { get; set; }
        public string Heartbeatstatus { get; set; }
        public string Rtobetaindex { get; set; }
        public string Maxinitialrtratt { get; set; }
        public string Heartbeatpathprobinginterval { get; set; }
        public string Sctpassocdeletetimeout { get; set; }
        public string Prioritydatadscpservice { get; set; }
        public string Intervaloobpkts { get; set; }
        public string Associationmaxrtx { get; set; }
        public string Switchbackmode { get; set; }
        public string Maximumrto { get; set; }
        public string Nthreshold { get; set; }
        public string Pvaluelimit { get; set; }
        public string Dmaxlimit { get; set; }
        public string Consecutiveidenticalresults { get; set; }
        public string Upsenabled { get; set; }
        public string Userplanesupervisionid { get; set; }
        public string Corbasecurityactive { get; set; }
        public string Crlearlyupdateinterval { get; set; }
        public string Targetmonitorportactive { get; set; }
        public string Localaadbinstallationfailure { get; set; }
        public string Debugportsactive { get; set; }
        public string Webserver { get; set; }
        public string Targetmonitorport { get; set; }
        public string Logindelay { get; set; }
        public string Operationalsecuritylevel { get; set; }
        public string Localauthenticationfileversion { get; set; }
        public string Nooffailedloginattempts { get; set; }
        public string Trustedcertificateinstallfail { get; set; }
        public string Certexpirwarntime { get; set; }
        public string Requestedsecuritylevel { get; set; }
        public string Failedloginattemptperiod { get; set; }
        public string Authorizationcachetimeout { get; set; }
        public string Userlockoutperiod { get; set; }
        public string Filetransferclientmode { get; set; }
        public string Localauthorizationfileversion { get; set; }
        public string Userauthenticationandauth { get; set; }
        public string Autoupdatecertenrollmentserver { get; set; }
        public string Telnetandftpserversactive { get; set; }
        public string Installedtrustedcertificates { get; set; }
        public string Aaserveripaddresslist { get; set; }
        public string Securityid { get; set; }
        public string Certrevstatuscheck { get; set; }
        public string Performancedatavolume { get; set; }
        public string Maxnoofcounters { get; set; }
        public string Warningalarmlimitpercent { get; set; }
        public string Minoralarmceasingdelta { get; set; }
        public string Transactiontimeout { get; set; }
        public string Maxnoofpmfiles { get; set; }
        public string Warningalarmceasingdelta { get; set; }
        public string Pmserviceid { get; set; }
        public string Maxnoofmonitors { get; set; }
        public string Agentipaddress { get; set; }
        public string Snmpid { get; set; }
        public string Agentport { get; set; }
        public string Minimumsnmpversion { get; set; }
        public string Logserviceid { get; set; }
        public string Filefetcherid { get; set; }
        public string Httpgetsupervisiontimer { get; set; }
        public string Performancesupervisionid { get; set; }
        public string Status { get; set; }
        public string Numberofcounterinstances { get; set; }
        public string Performanceindicatorid { get; set; }
        public string Scheduleinfo { get; set; }
        public string Executiontype { get; set; }
        public string Systemcheckid { get; set; }
        public string Checkresult { get; set; }
        public string Gpstoutcleapsecondschangedate { get; set; }
        public string Gpstoutcleapseconds { get; set; }
        public string Daylightsavingtimeendrule { get; set; }
        public string Timesettingid { get; set; }
        public string Daylightsavingtimeon { get; set; }
        public string Timeoffset { get; set; }
        public string Daylightsavingtimeoffset { get; set; }
        public string Daylightsavingtimestartrule { get; set; }
        public string Dcgstate { get; set; }
        public string Datacollectiongenerationid { get; set; }
        public string Pushpmfunctionid { get; set; }
        public string Integrationunlockstateinfo { get; set; }
        public string Lastlicensingpichange { get; set; }
        public string Licensingid { get; set; }
        public string Emergencystateinfo { get; set; }
        public string Ds0bundlemorefa { get; set; }
        public string Ds0bundlemorefb { get; set; }
        public string Tdmcrossconnectionid { get; set; }
        public string Chid { get; set; }
        public string Chrpumoref { get; set; }
        public string Bgfsmsrpsupportedtlsversions { get; set; }
        public string Userplanesecurityid { get; set; }
        public string Nodecertificates { get; set; }
        public string Mescrpumoref { get; set; }
        public string Mescid { get; set; }
        public string Localconnsupthreshold { get; set; }
        public string Ipconnectivitysupervisionid { get; set; }
        public string Featurestateipconnsup { get; set; }
        public string Remoteipconnconsfailures { get; set; }
        public string Remoteipconnsupactive { get; set; }
        public string Localipconnsupactive { get; set; }
        public string Remotesitesuptrafficreduction { get; set; }
        public string Remotesitetrafflevactive { get; set; }
        public string Licensestateipconnsup { get; set; }
        public string Webserverid { get; set; }
        public string Ncliid { get; set; }
        #endregion
    }
    public class SoftwareConfigurationDtoGrid : SoftwareConfigurationDto
    {
        [OrderGrid(Order = 1)]
        public long SoftwareConfigurationId { get; set; }

        [OrderGrid(Order = 2)]
        public long NetworkElementId { get; set; }

        [OrderGrid(Order = 3)]
        [Default]
        public string OpCo { get; set; }

    }
}
