UPDATE MAJORSOFTWAREBUILDS  SET ISVMWARE = 0 WHERE MAJORSOFTWAREBUILDSID IN (SELECT MSB.MAJORSOFTWAREBUILDSID FROM MAJORSOFTWAREBUILDS MSB JOIN ORIGINALEQUIPMENTMANUFACTURERS OEM ON OEM.ORGEQPMANUFACTURERID = MSB.ORGEQPMANUFACTURERID WHERE OEM.ORIGINALEQUIPMENTMANUFACTURER = 'VMWARE');

COMMIT;

