--------- Roll Back Script

 
ALTER TABLE  DCFLIFECYCLE  drop column OPCODESCRIPTION  ;
ALTER TABLE  DCFLIFECYCLE  drop column DCFDESCRIPTION  ;
ALTER TABLE  DCFLIFECYCLE  drop column CATEGORYTYPE ;
ALTER TABLE  DCFLIFECYCLE  drop column PLANNEDDETAILS ;
ALTER TABLE  DCFLIFECYCLE  drop column  DCDESCRIPTION  ;
ALTER TABLE DCFLIFECYCLE RENAME COLUMN CURRENTDETAILS TO DETAILS;

ALTER TABLE  RESOURCEKEYMASTER  DROP COLUMN  BUILDBAGID  ;
ALTER TABLE  RESOURCEKEYMASTER  DROP COLUMN  COMPONENTID  ;

ALTER TABLE  NETWORKELEMENTSASPLANNED  ADD  ISRELEASEDETAILASSETUNKNOWN NUMBER(1,0)   NULL;
ALTER TABLE  PLANNEDACTIVITIES  ADD COLUMN ACTIVITYDETAILSTEXT NVARCHAR2(2000)   NULL;


ALTER TABLE  LCMENGINEERING  MODIFY  BUILDBAGID  NUMBER(19,0)   null;
ALTER TABLE  NETWORKELEMENTSASPLANNED  MODIFY  BUILDBAGID  NUMBER(19,0)   null;
ALTER TABLE  PLANNEDACTIVITIES  MODIFY  BUILDBAGID  NUMBER(19,0)   null;
  
 
