ALTER TABLE NODEPARSEHISTORY DROP COLUMN NODEPROCESSSTARTTIME;
ALTER TABLE NODEPARSEHISTORY DROP COLUMN NODEPROCESSENDTIME;
ALTER TABLE NODEPARSEHISTORY DROP COLUMN NODETYPE;

ALTER TABLE XMLPARSERUN DROP COLUMN FILEPROCESSSTARTTIME;
ALTER TABLE XMLPARSERUN DROP COLUMN FILEPROCESSENDTIME;
ALTER TABLE XMLPARSERUN DROP COLUMN FEEDBACKLOOPAUDITID;

ALTER TABLE "XMLPARSERUN"
DROP CONSTRAINT "FK_XMLPARSERUN_FEEDBACKLOOPAUDITS_FEEDBACKLOOPAUDITID";


COMMIT;