/// <reference path="../Common/custom.d.ts" />
// tslint:disable
/**
 * Cam Vodafone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { QueryResultDtoOfReportHardwareDtoGrid } from "../../Model/Report/ReportHardwareModel";
import { headerObj } from "../header";

import {
  FetchArgs,
  FetchAPI,
  FilterValueDto,
  BASE_PATH,
  BaseAPI,
  RequiredError,
} from "../Common/CommonBusiness";
import { Configuration } from "../Common/configuration";
import { ReturnFile } from "../../Model/Common";
import { ReportHardwareQueryDto } from "../../Model/Report/Export";
/**
 * ReportHardwareApi - fetch parameter creator
 * @export
 */
export const ReportHardwareApiFetchParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @param {ReportHardwareQueryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reportHardwareExportReport(
      body: ReportHardwareQueryDto,
      options: any = {}
    ): FetchArgs {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling reportHardwareExportReport."
        );
      }
      const localVarPath = `/api/ReportHardware/ExportReport`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "POST" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"ReportHardwareQueryDto" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {ReportHardwareQueryDto} body
     * @param {string} [propertyName]
     * @param {string} [propertyFilter]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reportHardwareGetFilterResult(
      body: ReportHardwareQueryDto,
      propertyName?: string,
      propertyFilter?: string,
      options: any = {}
    ): FetchArgs {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling reportHardwareGetFilterResult."
        );
      }
      const localVarPath = `/api/ReportHardware/Filter`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "POST" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (propertyName !== undefined) {
        localVarQueryParameter["propertyName"] = propertyName;
      }

      if (propertyFilter !== undefined) {
        localVarQueryParameter["propertyFilter"] = propertyFilter;
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"ReportHardwareQueryDto" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {ReportHardwareQueryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reportHardwareGetReport(
      body: ReportHardwareQueryDto,
      options: any = {}
    ): FetchArgs {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling reportHardwareGetReport."
        );
      }
      const localVarPath = `/api/ReportHardware/Get`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "POST" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"ReportHardwareQueryDto" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ReportHardwareApi - functional programming interface
 * @export
 */
export const ReportHardwareApiFp = function (configuration?: Configuration) {
  return {
    /**
     *
     * @param {ReportHardwareQueryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reportHardwareExportReport(
      body: ReportHardwareQueryDto,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ReturnFile> {
      const localVarFetchArgs = ReportHardwareApiFetchParamCreator(
        configuration
      ).reportHardwareExportReport(body, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return {
              File: response.blob(),
              FileName: response.headers.get("Content-Disposition"),
            } as ReturnFile;
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {ReportHardwareQueryDto} body
     * @param {string} [propertyName]
     * @param {string} [propertyFilter]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reportHardwareGetFilterResult(
      body: ReportHardwareQueryDto,
      propertyName?: string,
      propertyFilter?: string,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<Array<FilterValueDto>> {
      const localVarFetchArgs = ReportHardwareApiFetchParamCreator(
        configuration
      ).reportHardwareGetFilterResult(
        body,
        propertyName,
        propertyFilter,
        options
      );
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {ReportHardwareQueryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reportHardwareGetReport(
      body: ReportHardwareQueryDto,
      options?: any
    ): (
      fetch?: FetchAPI,
      basePath?: string
    ) => Promise<QueryResultDtoOfReportHardwareDtoGrid> {
      const localVarFetchArgs = ReportHardwareApiFetchParamCreator(
        configuration
      ).reportHardwareGetReport(body, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
  };
};

/**
 * ReportHardwareApi - factory interface
 * @export
 */
export const ReportHardwareApiFactory = function (
  configuration?: Configuration,
  fetch?: FetchAPI,
  basePath?: string
) {
  return {
    /**
     *
     * @param {ReportHardwareQueryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reportHardwareExportReport(body: ReportHardwareQueryDto, options?: any) {
      return ReportHardwareApiFp(configuration).reportHardwareExportReport(
        body,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {ReportHardwareQueryDto} body
     * @param {string} [propertyName]
     * @param {string} [propertyFilter]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reportHardwareGetFilterResult(
      body: ReportHardwareQueryDto,
      propertyName?: string,
      propertyFilter?: string,
      options?: any
    ) {
      return ReportHardwareApiFp(configuration).reportHardwareGetFilterResult(
        body,
        propertyName,
        propertyFilter,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {ReportHardwareQueryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reportHardwareGetReport(body: ReportHardwareQueryDto, options?: any) {
      return ReportHardwareApiFp(configuration).reportHardwareGetReport(
        body,
        options
      )(fetch, basePath);
    },
  };
};

/**
 * ReportHardwareApi - object-oriented interface
 * @export
 * @class ReportHardwareApi
 * @extends {BaseAPI}
 */
export class ReportHardwareApi extends BaseAPI {
  /**
   *
   * @param {ReportHardwareQueryDto} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ReportHardwareApi
   */
  public reportHardwareExportReport(
    body: ReportHardwareQueryDto,
    options?: any
  ) {
    return ReportHardwareApiFp(this.configuration).reportHardwareExportReport(
      body,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {ReportHardwareQueryDto} body
   * @param {string} [propertyName]
   * @param {string} [propertyFilter]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ReportHardwareApi
   */
  public reportHardwareGetFilterResult(
    body: ReportHardwareQueryDto,
    propertyName?: string,
    propertyFilter?: string,
    options?: any
  ) {
    return ReportHardwareApiFp(
      this.configuration
    ).reportHardwareGetFilterResult(
      body,
      propertyName,
      propertyFilter,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {ReportHardwareQueryDto} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ReportHardwareApi
   */
  public reportHardwareGetReport(body: ReportHardwareQueryDto, options?: any) {
    return ReportHardwareApiFp(this.configuration).reportHardwareGetReport(
      body,
      options
    )(this.fetch, this.basePath);
  }
}
