ALTER TABLE PASSTHROUGHLCM DROP COLUMN "APPLICATIONOPERATINGSYS";
ALTER TABLE PASSTHROUGHLCM DROP COLUMN "EOFSDATE";
ALTER TABLE PASSTHROUGHLCM DROP COLUMN "EOSLKPIDAILY";
ALTER TABLE PASSTHROUGHLCM DROP COLUMN "EOSLKPIFROZEN"; 
ALTER TABLE PASSTHROUGHLCM DROP COLUMN "EOSLKPIFORECAST"; 
ALTER TABLE PASSTHROUGHLCM DROP COLUMN "PRODUCTIMPORTANCEHISTORY2";
ALTER TABLE PASSTHROUGHLCM DROP COLUMN "NOTES";

