--------------------------------------------------------
--  DDL for Sequence COMPONENTMANUFACTURER_SEQ
--------------------------------------------------------
 
CREATE SEQUENCE  "COMPONENTMANUFACTURER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
 
 
--------------------------------------------------------
--  DDL for Table COMPONENTMANUFACTURERS
--------------------------------------------------------
 
  CREATE TABLE COMPONENTMANUFACTURERS 
   (	
    "COMPONENTMANUFACTURERID" NUMBER(19,0) DEFAULT "COMPONENTMANUFACTURER_SEQ"."NEXTVAL", 
	"COMPONENTMANUFACTURER" NVARCHAR2(50), 
	"COMPONENTNAME" NVARCHAR2(50),
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index COMPONENTMANUFACTURERIDX
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "COMPONENTMANUFACTURERIDX" ON "COMPONENTMANUFACTURERS" ("COMPONENTMANUFACTURERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table COMPONENTMANUFACTURERS
--------------------------------------------------------
 
ALTER TABLE "COMPONENTMANUFACTURERS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "COMPONENTMANUFACTURERS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "COMPONENTMANUFACTURERS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "COMPONENTMANUFACTURERS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "COMPONENTMANUFACTURERS" ADD CONSTRAINT "PK_COMPONENTMANUFACTURERS" PRIMARY KEY ("COMPONENTMANUFACTURERID") USING INDEX "COMPONENTMANUFACTURERIDX"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPONENTMANUFACTURERS
--------------------------------------------------------
 
ALTER TABLE "COMPONENTMANUFACTURERS" ADD CONSTRAINT "FK_COMPONENTMANUFACTURERS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "COMPONENTMANUFACTURERS" ADD CONSTRAINT "FK_COMPONENTMANUFACTURERS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
COMMIT;

----------------------

------------- Create TEMPORARY  COMPONENTSOFTWAREBUILDS Table for Furture Refrence
create table TEMP_COMPONENTSOFTWAREBUILDS
(
COMPONENTSOFTWAREBUILDID  NUMBER(19) NOT NULL,
ORGEQPMANUFACTURERID   NUMBER(5) NOT NULL ,
PRODUCTNAMEID   NUMBER(20)   )

INSERT INTO TEMP_COMPONENTSOFTWAREBUILDS (COMPONENTSOFTWAREBUILDID, ORGEQPMANUFACTURERID, PRODUCTNAMEID)
SELECT COMPONENTSOFTWAREBUILDID, ORGEQPMANUFACTURERID, PRODUCTNAMEID FROM componentsoftwarebuilds;

commit;

-------------------------------------------- Insert COMPONENTMANUFACTURER from COMPONENTSOFTWAREBUILDS table

INSERT INTO COMPONENTMANUFACTURERS (COMPONENTMANUFACTURER, COMPONENTNAME)
SELECT  oem.ORIGINALEQUIPMENTMANUFACTURER as MANUFACTURERNAME,
pn.DESCRIPTION as PRODUCTNAME
FROM COMPONENTSOFTWAREBUILDS csb
JOIN ORIGINALEQUIPMENTMANUFACTURERS oem
ON csb.ORGEQPMANUFACTURERID = oem.ORGEQPMANUFACTURERID
JOIN PRODUCTNAME pn
ON csb.PRODUCTNAMEID = pn.PRODUCTNAMEID;

commit;
