
ALTER TABLE "COMPONENTSOFTWAREBUILDS" ADD "COMPONENTMANUFACTURERID" NUMBER(19,0);
ALTER TABLE "COMPONENTSOFTWAREBUILDS" ADD CONSTRAINT "FK_COMPONENTMANUFACTURERS_COMPONENTMANUFACTURERS_COMPONENTMANUFACTURERID" FOREIGN KEY ("COMPONENTMANUFACTURERID") REFERENCES "COMPONENTMANUFACTURERS" ("COMPONENTMANUFACTURERID") ENABLE;

COMMIT;



-------------------------------------------- Update COMPONENTMANUFACTURERID  value for COMPONENTMANUFACTURER from COMPONENTSOFTWAREBUILDS  PRODUCTNAME and ORIGINALEQUIPMENTMANUFACTURER table
MERGE INTO COMPONENTSOFTWAREBUILDS csb
USING (
    SELECT *
    FROM (
        SELECT 
            csb.ROWID AS csb_rowid,
            cm.COMPONENTMANUFACTURERID,
            ROW_NUMBER() OVER (PARTITION BY csb.ROWID ORDER BY cm.COMPONENTMANUFACTURERID) AS rn
        FROM COMPONENTSOFTWAREBUILDS csb
        JOIN ORIGINALEQUIPMENTMANUFACTURERS oem
            ON csb.ORGEQPMANUFACTURERID = oem.ORGEQPMANUFACTURERID
        JOIN PRODUCTNAME pn
            ON csb.PRODUCTNAMEID = pn.PRODUCTNAMEID
        JOIN COMPONENTMANUFACTURERS cm
            ON cm.COMPONENTMANUFACTURER = oem.ORIGINALEQUIPMENTMANUFACTURER
           AND cm.COMPONENTNAME = pn.DESCRIPTION
    )
    WHERE rn = 1
) matched_data
ON (csb.ROWID = matched_data.csb_rowid)
WHEN MATCHED THEN
    UPDATE SET csb.COMPONENTMANUFACTURERID = matched_data.COMPONENTMANUFACTURERID;

commit;
 
 
 ------------------- REmove  product and oem
ALTER TABLE "COMPONENTSOFTWAREBUILDS" DROP CONSTRAINT "FK_COMPONENTSOFTWAREBUILDS_PRODUCTNAME_PRODUCTNAMEID";
ALTER TABLE "COMPONENTSOFTWAREBUILDS" DROP CONSTRAINT "FK_COMPONENTSOFTWAREBUILDS_ORIGINALEQUIPMENTMANUFACTURERS_ORIGINALEQUIPMENTMANUFACTURERID";


ALTER TABLE "COMPONENTSOFTWAREBUILDS" DROP COLUMN "PRODUCTNAMEID";
ALTER TABLE "COMPONENTSOFTWAREBUILDS" DROP COLUMN "ORGEQPMANUFACTURERID";