
--------------------------------------------------------
--  DDL FOR SEQUENCE CNFNAME_SQE
--------------------------------------------------------

   CREATE SEQUENCE "CNFNAME_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE CNFNAME
--------------------------------------------------------

  CREATE TABLE CNFNAME 
   (	
    CNFNAMEID NUMBER(19,0) DEFAULT CNFNAME_SQE.NEXTVAL  NOT NULL, 
	CNFDESCRIPTION NVARCHAR2(50)  NOT NULL, 
	PRODUCTID NUMBER(20,0) , 	 
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_CNFNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CNFNAME" ON CNFNAME ("CNFNAMEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE CNFNAME MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE CNFNAME MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE CNFNAME MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE CNFNAME MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE CNFNAME ADD CONSTRAINT "PK_CNFNAME" PRIMARY KEY ("CNFNAMEID")
  USING INDEX "PK_CNFNAME"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE CNFNAME ADD CONSTRAINT "FK_CNFNAME_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE CNFNAME ADD CONSTRAINT "FK_CNFNAME_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE CNFNAME ADD CONSTRAINT "FK_CNFNAME_PRODUCTNAME_PRODUCTID" FOREIGN KEY ("PRODUCTID")
	  REFERENCES "PRODUCTNAME" ("PRODUCTNAMEID") ENABLE;
	  
COMMIT;

---------------------------

--------------------------------------------------------
--  DDL FOR SEQUENCE CNFCLUSTER_SQE
--------------------------------------------------------

   CREATE SEQUENCE "CNFCLUSTER_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE CNFCLUSTER
--------------------------------------------------------

  CREATE TABLE CNFCLUSTER 
   (	
    CNFCLUSTERID NUMBER(19,0) DEFAULT CNFCLUSTER_SQE.NEXTVAL  NOT NULL, 
	CNFCLUSTERNAME NVARCHAR2(100)  NOT NULL, 
	NODEPOOL NVARCHAR2(50)  NOT NULL, 
	CNFNAMEID NUMBER(19,0) , 	 
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_CNFCLUSTER
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CNFCLUSTER" ON CNFCLUSTER ("CNFCLUSTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE CNFCLUSTER MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE CNFCLUSTER MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE CNFCLUSTER MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE CNFCLUSTER MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE CNFCLUSTER ADD CONSTRAINT "PK_CNFCLUSTER" PRIMARY KEY ("CNFCLUSTERID")
  USING INDEX "PK_CNFCLUSTER"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE CNFCLUSTER ADD CONSTRAINT "FK_CNFCLUSTER_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE CNFCLUSTER ADD CONSTRAINT "FK_CNFCLUSTER_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE CNFCLUSTER ADD CONSTRAINT "FK_CNFCLUSTER_CNFNAME_CNFNAMEID" FOREIGN KEY ("CNFNAMEID")
	  REFERENCES "CNFNAME" ("CNFNAMEID") ENABLE;
	  
COMMIT;

-----------------------

--------------------------------------------------------
--  DDL FOR SEQUENCE PODTYPEINFO_SQE
--------------------------------------------------------

   CREATE SEQUENCE "PODTYPEINFO_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER
   NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE PODTYPEINFO
--------------------------------------------------------

  CREATE TABLE PODTYPEINFO 
   (	
    PODTYPEINFOID NUMBER(19,0) DEFAULT PODTYPEINFO_SQE.NEXTVAL  NOT NULL, 
	PODTYPEINFONAME NVARCHAR2(50)  NOT NULL, 
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) ,
	PODROLEDESCRIPTION NVARCHAR2(150)  NOT NULL 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_PODTYPEINFO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PODTYPEINFO" ON PODTYPEINFO ("PODTYPEINFOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE PODTYPEINFO MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE PODTYPEINFO MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE PODTYPEINFO MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE PODTYPEINFO MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
    
     ALTER TABLE PODTYPEINFO ADD CONSTRAINT "PK_PODTYPEINFO" PRIMARY KEY ("PODTYPEINFOID")
  USING INDEX "PK_PODTYPEINFO"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE PODTYPEINFO ADD CONSTRAINT "FK_PODTYPEINFO_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE PODTYPEINFO ADD CONSTRAINT "FK_PODTYPEINFO_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  

--------------------------------------------------------
--  DDL FOR SEQUENCE FUNCTIONSTANDARDNAME_SQE
--------------------------------------------------------

   CREATE SEQUENCE "FUNCTIONSTANDARDNAME_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE FUNCTIONSTANDARDNAME
--------------------------------------------------------

  CREATE TABLE FUNCTIONSTANDARDNAME 
   (	
    FUNCTIONSTANDARDNAMEID NUMBER(19,0) DEFAULT FUNCTIONSTANDARDNAME_SQE.NEXTVAL  NOT NULL, 
	FUNCTIONNAME NVARCHAR2(250)  NOT NULL, 
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6)  
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_FUNCTIONSTANDARDNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_FUNCTIONSTANDARDNAME" ON FUNCTIONSTANDARDNAME ("FUNCTIONSTANDARDNAMEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE FUNCTIONSTANDARDNAME MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE FUNCTIONSTANDARDNAME MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE FUNCTIONSTANDARDNAME MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE FUNCTIONSTANDARDNAME MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
    
     ALTER TABLE FUNCTIONSTANDARDNAME ADD CONSTRAINT "PK_FUNCTIONSTANDARDNAME" PRIMARY KEY ("FUNCTIONSTANDARDNAMEID")
  USING INDEX "PK_FUNCTIONSTANDARDNAME"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE FUNCTIONSTANDARDNAME ADD CONSTRAINT "FK_FUNCTIONSTANDARDNAME_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE FUNCTIONSTANDARDNAME ADD CONSTRAINT "FK_FUNCTIONSTANDARDNAME_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
	  	  
------------------------------------------- CNFINFO

--------------------------------------------------------
--  DDL FOR SEQUENCE CNFINFO_SQE
--------------------------------------------------------

   CREATE SEQUENCE "CNFINFO_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE CNFINFO
--------------------------------------------------------

  CREATE TABLE CNFINFO 
   (	
    CNFINFOID NUMBER(19,0) DEFAULT CNFINFO_SQE.NEXTVAL  NOT NULL, 
	CNFNAMEID NUMBER(19,0)  NOT NULL, 
	NODEPOOLBREAKUP NUMBER(1) default 0 NOT NULL , 
	SPECIALREQUIREMENTS NVARCHAR2(100)  NOT NULL, 
	HYPERTHREADING NVARCHAR2(100)  NOT NULL, 
	OVERPROVISIONING NVARCHAR2(100)  NOT NULL, 
	WORKERNODECONFIGURATION NVARCHAR2(100)  NOT NULL, 
	HARDWARE NVARCHAR2(100)  NOT NULL, 
	CPUKUBELET NUMBER(20,2) DEFAULT 0.5 NOT NULL , 
	MEMKUBELET NUMBER(10) DEFAULT 1 NOT NULL , 
	CPUSYSTEM NUMBER(20,2) DEFAULT 0.5 NOT NULL , 
	MEMSYSTEM NUMBER(10)  DEFAULT 1 NOT NULL, 
	VERTICALDOMAIN  NVARCHAR2(200)  NOT NULL, 
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_CNFINFO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CNFINFO" ON CNFINFO ("CNFINFOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE CNFINFO MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE CNFINFO MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE CNFINFO MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE CNFINFO MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE CNFINFO ADD CONSTRAINT "PK_CNFINFO" PRIMARY KEY ("CNFINFOID")
  USING INDEX "PK_CNFINFO"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE CNFINFO ADD CONSTRAINT "FK_CNFINFO_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE CNFINFO ADD CONSTRAINT "FK_CNFINFO_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
   ALTER TABLE CNFINFO ADD CONSTRAINT "FK_CNFINFO_CNFNAME_CNFNAMEID" FOREIGN KEY ("CNFNAMEID")
	  REFERENCES "CNFNAME" ("CNFNAMEID") ENABLE;
	  
-------------------------------------------------	  
	
--------------------------------------------------------
--  DDL FOR SEQUENCE CNFCLUSTERINFO_SQE
--------------------------------------------------------

   CREATE SEQUENCE "CNFCLUSTERINFO_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE CNFCLUSTERINFO
--------------------------------------------------------

  CREATE TABLE CNFCLUSTERINFO 
   (	
    CNFCLUSTERINFOID NUMBER(19,0) DEFAULT CNFCLUSTERINFO_SQE.NEXTVAL  NOT NULL, 
	CNFINFOID NUMBER(19,0)  NOT NULL, 
	CNFCLUSTERID NUMBER(19,0)  NOT NULL, 
	PODTYPEINFOID NUMBER(19,0)  NOT NULL, 
	OPCOID NUMBER(5,0)  NOT NULL,
	SITEID NUMBER(5,0)  NOT NULL,	
	FUNCTIONSTANDARDID NUMBER (19,0)  NOT NULL, 
	PRIORITYID NVARCHAR2(50)  NOT NULL, 	
	PODROLEDESCRIPTIONID NUMBER (19,0) , 
	DAEMONSETPOD NUMBER(1) , 
	INTRAPODRULES NVARCHAR2(10) , 
	INTERPODRULES  NVARCHAR2(10) , 
	ISENHANCEDHA NUMBER(1) , 
	PODTYPEQOS NVARCHAR2(50) , 
	ISPERSISTANCESTORAGEFLAG  NVARCHAR2(20) , 
	ISPRODHPAENABLE  NUMBER(1) ,  
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_CNFCLUSTERINFO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CNFCLUSTERINFO" ON CNFCLUSTERINFO ("CNFCLUSTERINFOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE CNFCLUSTERINFO MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE CNFCLUSTERINFO MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE CNFCLUSTERINFO MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE CNFCLUSTERINFO MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "PK_CNFCLUSTERINFO" PRIMARY KEY ("CNFCLUSTERINFOID")
  USING INDEX "PK_CNFCLUSTERINFO"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_CNFINFO_CNFINFOID" FOREIGN KEY ("CNFINFOID")
	  REFERENCES "CNFINFO" ("CNFINFOID") ENABLE;	  
  ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_PODTYPEINFO_PODTYPEINFOID" FOREIGN KEY ("PODTYPEINFOID")
	  REFERENCES "PODTYPEINFO" ("PODTYPEINFOID") ENABLE;
  ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_OPCOS_OPCOID" FOREIGN KEY ("OPCOID")
	  REFERENCES "OPCOS" ("OPCOID") ENABLE;
  ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_LOCATIONS_CNFNAMEID" FOREIGN KEY ("SITEID")
	  REFERENCES "LOCATIONS" ("LOCATIONID") ENABLE;	  
	  
  ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_PODTYPEINFO_PODROLEDESCRIPTIONID" FOREIGN KEY ("PODROLEDESCRIPTIONID")
	  REFERENCES "PODTYPEINFO" ("PODTYPEINFOID") ENABLE;	 
  ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_FUNCTIONSTANDARDNAME_FUNCTIONSTANDARDID" FOREIGN KEY ("FUNCTIONSTANDARDID")
	  REFERENCES "FUNCTIONSTANDARDNAME" ("FUNCTIONSTANDARDNAMEID") ENABLE;	

 ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_CNFCLUSTER_CNFCLUSTERID" FOREIGN KEY ("CNFCLUSTERID")
	  REFERENCES "CNFCLUSTER" ("CNFCLUSTERID") ENABLE;	

 ALTER TABLE CNFCLUSTERINFO ADD NODEPOOL NUMBER(19,0)  NULL;
 
--------------------------------------------------------
--  DDL FOR SEQUENCE CNFCAPACITY_SQE
--------------------------------------------------------

   CREATE SEQUENCE "CNFCAPACITY_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE CNFCAPACITY
--------------------------------------------------------

  CREATE TABLE CNFCAPACITY 
   (	
    CNFCAPACITYID NUMBER(19,0) DEFAULT CNFCAPACITY_SQE.NEXTVAL  NOT NULL, 
	CNFCLUSTERINFOID NUMBER(19,0)  NOT NULL, 	
	FINANCIALYEAR  NUMBER(5) NOT NULL,  
	NOOFCNFINSTANCESPERSITE  NUMBER(10),  
	NUMBEROFPODSPERPODTYPE  NUMBER(10),  
	VCPUREQUESTFORPODTYPE NUMBER(19),  
	MEMREQUESTFORPODTYPE NVARCHAR2(50) ,  	
	NONPRESISTENTSTORAGEFORPRODTYPE NVARCHAR2(200) , 
	ISPRESISTENTVOLUMESREQUIRED	 NUMBER(1),  
	PERSISTENTVOLUMNEACCESSMODE  NVARCHAR2(200) , 	
	PERSISTENTSTORAGEFORPODTYPE	 NVARCHAR2(200) , 	
	STORAGEIOPSFORPODTYPE NVARCHAR2(200) ,  
	STORAGERWORKLOADDISTRIBUTION NVARCHAR2(200) , 
	NORTHSOUTHBANDWIDTHFORPODTYPE NVARCHAR2(200) , 	
	EASTWESTBANDWIDTHFORPODTYPE	NVARCHAR2(50) , 
	SPECIALREQUIREMENTPERPODTYPE NVARCHAR2(50) , 	
	CAPACITYSPECIALREQUIREMENT 	NVARCHAR2(250) , 	
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_CNFCAPACITY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CNFCAPACITY" ON CNFCAPACITY ("CNFCAPACITYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE CNFCAPACITY MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE CNFCAPACITY MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE CNFCAPACITY MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE CNFCAPACITY MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE CNFCAPACITY ADD CONSTRAINT "PK_CNFCAPACITY" PRIMARY KEY ("CNFCAPACITYID")
  USING INDEX "PK_CNFCAPACITY"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE CNFCAPACITY ADD CONSTRAINT "FK_CNFCAPACITY_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE CNFCAPACITY ADD CONSTRAINT "FK_CNFCAPACITY_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE CNFCAPACITY ADD CONSTRAINT "FK_CNFCAPACITY_CNFCLUSTERINFO_CNFCLUSTERINFOID" FOREIGN KEY ("CNFCLUSTERINFOID")
	  REFERENCES "CNFCLUSTERINFO" ("CNFCLUSTERINFOID") ENABLE;	 	   