-----------------------CNFNAME  Table

insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'SC(BSF/DRA)',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'SC(SCP/DA)',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'SC(SEPP/DEA)',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'EVNFM',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'CCDM',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'CCSM',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'CNOM',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'PXP',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'redis 3',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'data-aggregrator 3',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'ams-protocol-correlator 2',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'cp-kafka 3',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'kakfa connect 2',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'elastic search 3',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'Prometheus 1',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'Promtail 6',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'Loki 1',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'Grafana (Main Site) 2',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'ams-pmc 2',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'MariaDB Galera 3',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'Keycloak 2',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'oauth2-proxy 2',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'ams-rules-builder 2',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'minio 4',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'minio-replicate',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'CoreDNS 2',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'etcd 3',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'calico 6',1,1);

Commit;

------------------------------CNFCLUSTERNAME 
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'BSF Cluster', 'NP1', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'SC(BSF/DRA)';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'SCP Cluster', 'NP2', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'SC(SCP/DA)';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'SEPP Cluster', 'NP3', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'SC(SEPP/DEA)';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'EVNFM Cluster', 'NP4', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'EVNFM';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'CCDM Cluster', 'NP5', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'CCDM';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'CCSM Cluster', 'NP6', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'CCSM';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'CNOM Cluster', 'NP7', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'CNOM';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP8', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'PXP';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP9', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'redis 3';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP10', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'data-aggregrator 3';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP11', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'ams-protocol-correlator 2';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP12', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'cp-kafka 3';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP13', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'kakfa connect 2';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP14', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'elastic search 3';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP15', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'Prometheus 1';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP16', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'Promtail 6';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP17', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'Loki 1';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP18', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'Grafana (Main Site) 2';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP19', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'ams-pmc 2';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP20', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'MariaDB Galera 3';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP21', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'Keycloak 2';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP22', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'oauth2-proxy 2';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP23', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'ams-rules-builder 2';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP24', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'minio 4';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP25', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'minio-replicate';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP26', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'CoreDNS 2';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP27', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'etcd 3';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'Signalling Edge ', 'NP28', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'calico 6';

Commit;
---------------------------------------------------functionstandardname

insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-Common Services',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-BSF',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-DRA',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-SCP',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-DA',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-SEPP',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-DEA',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('VNF LCM',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('UDR',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('UDM/AUSF',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('CNOM',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('Signalling Edge ',1,1);

Commit;

------------------------------------------- Pod Type 
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-mediator','CM_Mediator',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-mediator-key-init','CM_Mediator_Key_Init',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-mediator-notifier','CM_Mediator_Notifier',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-yang-provider','CM_Yang_Provider',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ctrl-bro','Backup_and_Restore_Orchestrator',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-coordinator-zk','Data_Coordinator_ZK',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-distributed-coordinator-ed','Distributed_Coordinator_ED',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-distributed-coordinator-ed-agent','Distributed_Coordinator_ED_Agent',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-distributed-coordinator-ed-sc','Distributed_Coordinator_ED_SC',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg','Document_DB_PG',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg-bragent','Document_DB_PG_BR_Agent',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-message-bus-kf','Message_Bus_KF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-curator','Search_Engine_Curator',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-data','Search_Engine_Data',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-ingest-tls','Search_Engine_Ingest',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-master','Search_Engine_Master',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-wide-column-database-cd-operator','eric-data-wide-column-database-cd-operator',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-fh-alarm-handler','Alarm_Handler',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-fh-snmp-alarm-provider','SNMP_Alarm_Provider',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-lm-combined-server-license-consumer-handler','License_Manager_Consumer_Handler',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-lm-combined-server-license-server-client','License_Manager_Server_Client',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-log-transformer','Log_Transformer',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-odca-diagnostic-data-collector','Diagnostic_Data_Collector',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-odca-diagnostic-data-collector-manual','Diagnostic_Data_Collector_Manual',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-bulk-reporter','PM_Bulk_Reporter',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-server','PM_Server',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-admin-user-management','Admin_User_Management',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-certm','Certificate_Management',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-key-management-main','Key_Management',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-ldap-server','LDAP_Server',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-ldap-server-proxy','LDAP_Server_BR_Agent',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-sip-tls-main','Service_Identity_Provider_TLS',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-si-application-sys-info-handler','eric-si-application-sys-info-handler',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-tm-ingress-controller-cr-contour','Ingress_Controller_CR_Contour',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cnom-server','CNOM_Server',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sc-hcagent','Health_Check_Agent',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sc-manager','SC_Manager',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sc-monitor','Monitor',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-log-shipper','Log_Shipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-tm-ingress-controller-cr-envoy','Ingress_Controller_CR_Envoy',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-stm-diameter','Diameter',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-wide-column-database-cd','Wide_Column_Database_CD',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-bsf-diameter','BSF_Diameter',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-bsf-manager','BSF_Manager',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-bsf-manager-vtap1','BSF_Manager_vTAP1',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-bsf-worker','BSF_Worker',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-bsf-worker-vtap2','BSF_Worker_vTAP2',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-probe-virtual-tap-broker-vtap2','Probe vTAP Broker',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('DRA Manager','DRA Manager',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('DRA Worker','DRA Worker',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-scp-manager','SCP_Manager',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-scp-manager-vtap1','SCP_Manager_vTAP1',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-scp-worker','SCP_Worker',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-scp-worker-vtap2','eric-scp-worker-vtap2',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sc-rlf','SC_Rate Limiting',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('DA Manager','DA Manager',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('DA Worker','DA Worker',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sepp-manager','SEPP_Manager',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sepp-manager-vtap1','SEPP_Manager_vTAP1',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sepp-worker','SEPP_Worker',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sepp-worker-vtap2','eric-sepp-worker-vtap2',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('DEA Manager','DEA Manager',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('DEA Worker','DEA Worker',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('General','General',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-nudrfe','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-notificationsubscription','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-gudrestfe','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-provisioningfe','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-eda-provisioning','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-ldapfe','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-ldap-balancer','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-kvdb-ag-server','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-kvdb-ag-locator','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-kvdb-ag-operator','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-kvdb-ag-admin-mgr','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-rest-notifchecker','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-rest-notifsender','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-soap-notifchecker','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-soap-notifsender','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-nrfproxy','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-cmagent','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-message-bus-kf','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-udr-ldap-traffic','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-udr-ldap-provisioning','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-udr-traffic','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-udr-intersite','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-data-model-controller','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-dbmanager','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-dbmonitor','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-message-bus-monitor','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-system-status-provider','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-system-monitor','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-app-counters','Data access/visualization',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-migration-orchestrator','Data access/visualization',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-migration-task','Data access/visualization',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-consistency-check-orchestrator','Data access/visualization',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-consistency-check-worker','Data access/visualization',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-import-export-orchestrator','Data access/visualization',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-license-handler','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-cmmanager','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-provisioningrm','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-bulk-data-synchronizer','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-mediator','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-yang-provider','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cnom-document-database-mg','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cnom-server','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-mediator-notifier','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg-bragent','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-bulk-reporter','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-server','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-fh-alarm-handler','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-fh-snmp-alarm-provider','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-log-shipper','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-log-transformer','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-data','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-ingest','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-ingest-tls','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-master','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-odca-diagnostic-data-collector','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-odca-diagnostic-data-collector-manual','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-mesh-controller','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-ldap-server','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-ldap-server-proxy','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-distributed-coordinator-ed','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-distributed-coordinator-ed-agent','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-access-mgmt','Security',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-key-management-main','Security',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-sip-tls-main','Security',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-certm','Security',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-admin-user-management','Security',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-nrf-discovery-agent','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-nrf-notify-agent','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-nrf-register-agent','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-coordinator-zk','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ctrl-bro','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-tm-ingress-controller-cr-contour','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-tm-ingress-controller-cr-envoy','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-lm-combined-server-license-consumer-handler','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-lm-combined-server-license-server-client','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-object-storage-mn','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-object-storage-mn-mgt','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-nrf-accesstoken-agent','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-si-application-sys-info-handler','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-resource-monitor','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-access-mgmt-sip-oauth2','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-application-resource-monitor','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-mapi-provisioning','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-mb-kf','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-oauth-token-validator','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-proclog-cassandra-stasher','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-proclog-manager','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-service-locator-registry','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-user-data-activator','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-user-data-activator-synchronizer','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-wide-column-database-cd','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-wide-column-database-cd-bra','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-wide-column-database-cd-operator','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-probe-virtual-tap-broker','UDR microservice',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-backup-ca','CA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccdm-extraction-ca','CA',1,1);
--insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('Resiliency and SW upgrade','',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-nrf-discovery-agent','NRF ',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-nrf-notify-agent','NRF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-nrf-register-agent','NRF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-authconf','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-blackhole','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-capacity','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-cancelepclocation','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-iratamflocation','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-iwk5g2g','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-keymanager','CCSM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-lmagent','CCSM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmamdata','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmmultipledataset','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmnotif','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmnssai','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmsmdata','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmsmfselect','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmsubscriptions','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmuectxtsmf','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-ueauth','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-uecmamfget','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-uecmamfderegnotifier','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-uecmamfregupdate','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-uecmreg','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-uecmsmfderegistration','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-uecmsmfregistration','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-pcscfrestoration','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-ueshcm','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ausf-capacity','AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ausf-engine','AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-nfcontroller','CCSM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-eir-eireic','EIR',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-eir-socshipper','EIR',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-mediator','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-server','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-bulk-reporter','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-log-shipper','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-object-storage-mn','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-data','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-ingest','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-master','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-odca-diagnostic-data-collector','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-message-bus-kf','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-coordinator-zk','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-log-transformer','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-fh-alarm-handler','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-fh-snmp-alarm-provider','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-yang-provider','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ctrl-bro','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-ldap-server','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-key-management-main','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-sip-tls-main','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-distributed-coordinator-ed','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cnom-server','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cnom-document-database-mg','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sw-inventory-manager','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-tm-ingress-controller-cr-envoy','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-certm','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-admin-user-management','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-mesh-controller','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-ausf-traffic','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-udm-traffic','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-eir-traffic','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-epc-soap-traffic','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-mapproxy-2-sctp-service','CCSM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-topicwatcher','CCSM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-mapproxy-1-sctp-service','CCSM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg-ah','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg-lm','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg-bragent','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-ingest-tls','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-mediator-notifier','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-odca-diagnostic-data-collector-manual','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-distributed-coordinator-ed-agent','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-tm-ingress-controller-cr-contour','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-ldap-server-proxy','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-eir-cmagent','EIR',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-cmagent','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-iratsndereg','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-iratamfdereg','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-pcscfrestnotif','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-mtlocation','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-mtueinfo','UDM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-udm-internal-traffic','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-nrfgw','CCSM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-mapproxy-1','CCSM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-mapproxy-2','CCSM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-autonrf','CCSM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-cmagent','CCSM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-mapproxy-1-config-validator','CCSM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-mapproxy-1-state-provider-proxy','CCSM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-lm-unique-object-reporter','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-object-storage-mn-mgt','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-probe-virtual-tap-broker','CCSM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('CNOM-RESOURCES: ','CNOM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_1','cSE_POD_1',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_2','cSE_POD_2',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_3','cSE_POD_3',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_4','cSE_POD_4',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_5','cSE_POD_5',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_6','cSE_POD_6',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_7','cSE_POD_7',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_8','cSE_POD_8',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_9','cSE_POD_9',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_10','cSE_POD_10',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_11','cSE_POD_11',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_12','cSE_POD_12',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_13','cSE_POD_13',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_14','cSE_POD_14',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_15','cSE_POD_15',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_16','cSE_POD_16',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_17','cSE_POD_17',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_18','cSE_POD_18',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_19','cSE_POD_19',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_20','cSE_POD_20',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('cSE_POD_21','cSE_POD_21',1,1);


Commit;

------------------------------ functionstandardname

insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-Common Services',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-BSF',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-DRA',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-SCP',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-DA',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-SEPP',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-DEA',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('VNF LCM',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('UDR',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('UDM/AUSF',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('CNOM',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('Signalling Edge ',1,1);


Commit;