 -------------------------------
 ---SEQUENCE for Table DYNAMICREPORTS
 -------------------------------
 
  CREATE SEQUENCE "DYNAMICREPORTS_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  COMMIT;
 
 -------------------------------
 ---DDL for Table DYNAMICREPORTS
 -------------------------------
  CREATE TABLE "DYNAMICREPORTS" 
   (	
   	"DYNAMICREPORTSID" NUMBER DEFAULT "DYNAMICREPORTS_SEQ"."NEXTVAL",
	"USERID" NUMBER(10,0),
	"REPORTNAME" NVARCHAR2(2000),
	"JSONGRIDCUSTOMIZATIONDATA" NCLOB,
	"PUBLISHED" NUMBER(1,0) DEFAULT 0,
	"ISSCHEDULED" TIMESTAMP (6),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6) 	 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" 
LOB ("JSONGRIDCUSTOMIZATIONDATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index DYNAMICREPORTS_PK
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "DYNAMICREPORTS_PK" ON "DYNAMICREPORTS" ("DYNAMICREPORTSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table DYNAMICREPORTS
--------------------------------------------------------
 
  ALTER TABLE "DYNAMICREPORTS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "DYNAMICREPORTS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "DYNAMICREPORTS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "DYNAMICREPORTS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "DYNAMICREPORTS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "DYNAMICREPORTS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "DYNAMICREPORTS" MODIFY ("JSONGRIDCUSTOMIZATIONDATA" NOT NULL ENABLE);
  ALTER TABLE "DYNAMICREPORTS" MODIFY ("DYNAMICREPORTSID" NOT NULL ENABLE);
  ALTER TABLE "DYNAMICREPORTS" ADD CONSTRAINT "DYNAMICREPORTS_PK" PRIMARY KEY ("DYNAMICREPORTSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DYNAMICREPORTS
--------------------------------------------------------
 
  ALTER TABLE "DYNAMICREPORTS" ADD CONSTRAINT "FK_DYNAMICREPORTS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "DYNAMICREPORTS" ADD CONSTRAINT "FK_DYNAMICREPORTS_ASPNETUSERS_USERID" FOREIGN KEY       ("USERID")REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "DYNAMICREPORTS" ADD CONSTRAINT "FK_DYNAMICREPORTS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")REFERENCES "ASPNETUSERS" ("ID") ENABLE;