---Alter Scrip for ASPNETUSERROLES--
ALTER TABLE "ASPNETUSERROLES" ADD OPCOID NUMBER(5,0);
ALTER TABLE "ASPNETUSERROLES" ADD VERTICALRESPONSIBLEID NUMBER(10,0);
ALTER TABLE "ASPNETUSERROLES" ADD CREATIONUSER NUMBER(10,0); 
ALTER TABLE "ASPNETUSERROLES" ADD CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp); 
ALTER TABLE "ASPNETUSERROLES" ADD MODIFICATIONUSER NUMBER(10,0); 
ALTER TABLE "ASPNETUSERROLES" ADD MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp); 
ALTER TABLE "ASPNETUSERROLES" ADD DELETED NUMBER(1,0) DEFAULT 0; 
ALTER TABLE "ASPNETUSERROLES" ADD DELETIONDATE TIMESTAMP (6);   
ALTER TABLE "ASPNETUSERROLES" ADD CONSTRAINT
"FKASPNETUSERROLES_VERTICALRESPONSIBLES_VERTICALRESPONSIBLEID" FOREIGN KEY ("VERTICALRESPONSIBLEID")
REFERENCES "VERTICALRESPONSIBLES" ("VERTICALRESPONSIBLEID") ENABLE;
ALTER TABLE "ASPNETUSERROLES" ADD CONSTRAINT "FK_ASPNETUSERROLES_OPCOS_OPCOID" FOREIGN KEY ("OPCOID")REFERENCES "OPCOS" ("OPCOID") ENABLE;