--------  SCRIPT FOR APPSETTINGS---------------
INSERT INTO "APPSETTINGS" (APPSETTINGID, DESCRIPTION, CREATIONUSER, MODIFICATIONUSER) VALUES ('6', N'ExodusTargetPlatformFilter', '1', '1');
Commit;
 
--------  SCRIPT FOR APPSETTINGSCONFIGURATION---------------
INSERT INTO "APPSETTINGSCONFIGURATION" (APPSETTINGID, SETTINGSVALUE, CREATIONUSER, MODIFICATIONUSER) VALUES ('6', N'CEE-CNIS', '1', '1');  
INSERT INTO "APPSETTINGSCONFIGURATION" (APPSETTINGID, SETTINGSVALUE, CREATIONUSER, MODIFICATIONUSER) VALUES ('6', N'CCD-CNIS', '1', '1');
INSERT INTO "APPSETTINGSCONFIGURATION" (APPSETTINGID, SETTINGSVALUE, CREATIONUSER, MODIFICATIONUSER) VALUES ('6', N'RHOCPVIRT', '1', '1');
INSERT INTO "APPSETTINGSCONFIGURATION" (APPSETTINGID, SETTINGSVALUE, CREATIONUSER, MODIFICATIONUSER) VALUES ('6', N'NRHOSO', '1', '1');
INSERT INTO "APPSETTINGSCONFIGURATION" (APPSETTINGID, SETTINGSVALUE, CREATIONUSER, MODIFICATIONUSER) VALUES ('6', N'NRHO', '1', '1');
INSERT INTO "APPSETTINGSCONFIGURATION" (APPSETTINGID, SETTINGSVALUE, CREATIONUSER, MODIFICATIONUSER) VALUES ('6', N'RHOCP', '1', '1');
Commit;


