 
DROP SEQUENCE  "VNFVMCAPACITY_SEQ";
DROP TABLE VNFVMCAPACITY;   
  
DROP SEQUENCE  "VNFVMINSTANCES_SEQ";
DROP TABLE VNFVMINSTANCES;  
 
 DROP SEQUENCE  "VNFINFO_SEQ";
DROP TABLE VNFINFO;

DROP SEQUENCE  "VMTYPENAME_SEQ";
DROP TABLE VMTYPENAME; 

DROP SEQUENCE  "CLUSTERNAME_SEQ";
DROP TABLE CLUSTERNAME; 

 DROP SEQUENCE  "VNFNAME_SEQ";
DROP TABLE VNFNAME;  

ALTER TABLE LOCATIONS DROP COLUMN SHORTDESCRIPTION;
