CREATE SEQUENCE "GLOSSARYITEMS_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE TABLE "GLOSSARYITEMS" 
(
    "GLOSSARYITEMSID" NUMBER(19,0) DEFAULT "GLOSSARYITEMS_SEQ"."NEXTVAL",
    "HEADER" NVARCHAR2(50),
    "DESCRIPTION" NVARCHAR2(300),
    "CREATIONUSER" NUMBER(10,0) DEFAULT 1,
    "CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp),
    "MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1,
    "MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp),
    "DELETED" NUMBER(1,0) DEFAULT 0,
    "DELETIONDATE" TIMESTAMP(6)
) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";

CREATE UNIQUE INDEX "GLOSSARYITEMSIDX" ON "GLOSSARYITEMS" ("GLOSSARYITEMSID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";

ALTER TABLE "GLOSSARYITEMS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "GLOSSARYITEMS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "GLOSSARYITEMS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "GLOSSARYITEMS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "GLOSSARYITEMS" ADD CONSTRAINT "PK_GLOSSARYITEMS" PRIMARY KEY ("GLOSSARYITEMSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ENABLE;

ALTER TABLE "GLOSSARYITEMS" ADD CONSTRAINT "FK_GLOSSARYITEMS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
  REFERENCES "ASPNETUSERS" ("ID") ENABLE;

ALTER TABLE "GLOSSARYITEMS" ADD CONSTRAINT "FK_GLOSSARYITEMS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
  REFERENCES "ASPNETUSERS" ("ID") ENABLE;

ALTER TABLE "GLOSSARYITEMS"
MODIFY("GLOSSARYITEMSID"  DEFAULT "GLOSSARYITEMS_SEQ"."NEXTVAL");
