ALTER TABLE "GLOSSARYITEMS" MODIFY ("DESCRIPTION" NVARCHAR2(2000));

set define off;
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Supported Services', 'Supported Services');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('lCM Policy', 'lCM Policy');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Lcm Deployment Status', 'Lcm Deployment Status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Activity Index', 'Planned Activity Index');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MS1 Event Type', 'MS1 Event Type');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MS1 Base Line Date', 'MS1 Base Line Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MS1 Latest Planning Date', 'MS1 Latest Planning Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MS1 Status', 'MS1 Status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MS2 Event Type', 'MS2 Event Type');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MS2 Base Line Date', 'MS2 Base Line Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MS3 Latest Planning Date', 'MS3 Latest Planning Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MS3 Status', 'MS3 Status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MS3 Event Type', 'MS3 Event Type');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MS3 Base Line Date', 'MS3 Base Line Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MS4 Latest Planning Date', 'MS4 Latest Planning Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MS4 Status', 'MS4 Status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MS4 Event Type', 'MS4 Event Type');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MS4 Base Line Date', 'MS4 Base Line Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MS2 Latest Planning Date', 'MS2 Latest Planning Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MS2 Status', 'MS2 Status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Notes1', 'Notes1');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Notes2', 'Notes2');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('PPM Import Date', 'PPM Import Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Activity', 'Activity');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Rule Element Count', 'Rule Element Count');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Lcm Deployment Status', 'Lcm Deployment Status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Start Date', 'Start Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('End Date', 'End Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Design Component', 'Planned Design Component');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Customer Wheel', 'Customer Wheel');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Successor Planned Activity Type Resource', 'Successor Planned Activity Type Resource');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Rule For Successor Planned Activity Creation', 'Rule For Successor Planned Activity Creation');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Criticality Rating', 'Criticality Rating');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('DA Exportable', 'DA Exportable');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Deployment Status', 'Deployment Status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('GDPR Classification', 'GDPR Classification');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('PCI/SOX - radio buttons', 'PCI/SOX');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('C3/C4', 'C3/C4');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Mission Critical', 'Mission Critical');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Security Element', 'Security Element');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Country Specific Criticality', 'Country Specific Criticality');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Family', 'Software Family');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Name Original Equipment Manufacturer', 'The common name for the Original Equipment Manufacturer responsible for the development of the system');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Name Original Equipment Manufacturer', 'The common name for the Original Equipment Manufacturer responsible for the development of the system');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('SubNetwork Boundary', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Vodafone Name', 'SW App - VF Name '||'('||'Vodafone Name'||')'||'');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Subnetwork Boundary Name', 'Subnetwork Boudary '||'('||'Subnetwork Boundary Name)');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Product Name', 'Product Name - VF Name '||'('||'Product Name'||')'||'');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Hardware Solution', 'Particularly where the Build Construction is ''Proprietary'' the Equipment manufacture can use the same hardware Platform for mulitple applications with specific vertical integration points. In order to differentiate this it is common for the hardware solution to have the same name as the application running on it. This is therefore a Product Name. TEMS uses the same approach where the Build Construction is COTS. Where the Build Construction is NFVI/NFCI the phrase ''Multiple Applications'' is used.');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Authentication Type', 'Authentication Type');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('3rd Party Access Type', '3rd Party Access Type');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Functional Release Cycle Period', 'Functional Release Cycle Period');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('License Model', 'License Model');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Security Manager', 'Security Manager');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Lcm Export Setting', 'Lcm Export Setting');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Operational Contact', 'Operational Contact');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Instance Level Resilience', 'Instance Level Resilience');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Method of Business Continuity', 'Method of Business Continuity');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Site Resilience', 'Site Resilience');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Subnetwork Boundary Index', 'Subnetwork Boundary Index');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Alias', 'Alias');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Subnetwork Boundary Name', 'Subnetwork Boundary Name');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('SW Application Name', 'SW Application Name');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Asset Deployment Status', 'Asset Deployment Status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Platform', 'Generally this is static information as changing the platform conmotes modernizing/replacing the solution. The common name used for the collection of compatible hardware brought together in an architecture. Where the hardware is related to NFVI/NFCI TEMS uses the same values as Build Construction; Where the Build Construction is ''Proprietary'' the value represents the name used by the equipment manufacturer for the architectural solution; Where the Build Construction is COTS the model name from the equipment manufacturer is used.');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Sharing Type', 'Sharing Type');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('LCM Policy', 'lCM Policy');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Business Critical', 'Business Critical');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Implementation', 'Implementation');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Security Tier Zone', 'Security Tier Zone');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Hardware Type', 'Generally this is dynamic information reflecting components that can be life cycle managed. Strictly there are many hardware components that can be upgraded individually and in TEMS we link the value here to the primary component that can be used for scaling also.');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Other Hardware Info', 'A free format text field to add information as seen useful and provide synergy across Opco');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Last Time Buy', 'Towards the end of the product life cycle the manufacturer will announce a last time buy for new deployments. This is the date wanted in this attribute if it has been announced. For existing deployments it is usual that expansions and upgrades are still possible, so the last time buy for upgrades and expansions may be later.');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Last Time Buy upgrades', 'Towards the end of the product life cycle the manufacturer will announce a last time buy for new deployments. For existing deployments it is usual that expansions and upgrades are still possible, so the last time buy for upgrades may be later.  This is the date wanted in this attribute if it has been announced. ');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Last Time Buy Expansions', 'Towards the end of the product life cycle the manufacturer will announce a last time buy for new deployments. For existing deployments it is usual that expansions and upgrades are still possible, so the last time buy for expansions may be later.  This is the date wanted in this attribute if it has been announced. ');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('End Of Maintenance', 'Equipment Manufacturer terminology can vary, but the concepts are the same. There is a period of the product life cycle where the manufacturer actively enhances/optimizes the product making patch releases available in a regular way based on in service performance seen around the deployments across different service providers. In TEMS we call this the Maintenance period. At End of Maintenance the Equipment Manufacturer scales down and no longer provides this active engagement. However, for a period of time they will continue to address specific trouble reports from a Service Provider providing patches to that Service Provider as necessary. In TEMS we call this the Support period. After End of Support the Equipment Manufacurer will no longer address trouble reports raised by a Service provider. It is possible for a Service Provider to pay for Extended Support. If this is the case for a specific Opco it will be specified in another part of TEMS.');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('End Of Maintenance', 'Equipment Manufacturer terminology can vary, but the concepts are the same. There is a period of the product life cycle where the manufacturer actively enhances/optimizes the product making patch releases available in a regular way based on in service performance seen around the deployments across different service providers. In TEMS we call this the Maintenance period. At End of Maintenance the Equipment Manufacturer scales down and no longer provides this active engagement. However, for a period of time they will continue to address specific trouble reports from a Service Provider providing patches to that Service Provider as necessary. In TEMS we call this the Support period. After End of Support the Equipment Manufacurer will no longer address trouble reports raised by a Service provider. It is possible for a Service Provider to pay for Extended Support. If this is the case for a specific Opco it will be specified in another part of TEMS.');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('End Of Support', 'End Of Support');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Data Acquisition Date', 'Data Acquisition Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Install Date', 'Software Install Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Production Date', 'Software Production Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Last Modified', 'Last Modified');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Last Time Buy Upgrades', 'Last Time Buy Upgrades');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Last Time Buy Expansions', 'Last Time Buy Expansions');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Last Time Buy New', 'Last Time Buy New');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('General Available Date', 'General Available Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('End Of Support', '<b>*Info not mandatory. Fill out only if useful for Vertical*</b>
Date declared by the Vendor within the official commercial roadmap
Date after which no further software remedy for a security vulnerability issue will be made available by the Vendor.
This date may be the same or later than the declared EOM date.');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Vulnerability Status', 'A free format text field to add information as seen useful and provide synergy across Opco');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Last Modified', 'An automatically populated date showing the last time the entry in the table was modified.');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Product Name', 'The Product Name of the software application as used by the Developer');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Version', 'This is dynamic information reflecting the functional build level that is life cycle managed. The End of Maintenance date, End of Support date and roadmapped functionality apply at this level. The patch level is not something that should be including in this part of TEMS. The patch level will be found in the implementation specific parts of TEMS.');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('General Availability Date', 'This is the General Availability Date of the product from the Equipment Manufacturer');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Delivery Method', 'A field depicting whether the normal lifecycle of the product follows an agile delivery methodology such as the Ericsson OneTrack method (Smaller but more frequent functional releases) or a more traditional life cycle approach (lager less frequent functional releases)');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Operating System', 'TEMS Foreign Index belonging to related table');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Operating System', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('System Type Index', 'TEMS Index unique to the table row');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('System Solution', 'An aggregation of different attributes to provide a human readable context for the System Type');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Constraint '||'('||'Scaling'||')'||'', 'Where software or hardware products are indicated as having ''last Time Buy'' dates associated with them then the earliest appropriate date will be automatically pulled through and displayed in this field.');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Third Party Hardware Components', 'TEMS Foreign Index belonging to related table');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Third Party Software Components', 'TEMS Foreign Index belonging to related table');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Constraint (LCM)', 'Where software or hardware products are indicated as having ''last Time Buy'' dates associated with them then the earliest appropriate date will be automatically pulled through and displayed in this field.');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Product Importance', '<ul><li><b>Strategic</b>:
Key assets to technology evolution with a clear modernisation/evolution plan since capabilities directly impact services that can be offered to customers</li><li><b>Non-Strategic</b>:<ol><li>Assets that have no future strategic role and subject to a clear decommission/removal</li><li>Assets that are key to the ongoing needs of the network but whose features are considered stable and whose feature roadmaps are not directly beneficial to Vodafone’s needs</li></ol></ul>The description may change due to perticular requirements of verticals');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Vertical Responsible', 'That part of the organization responsible for the System Type Solution. It is feasible that different parts of the organization use the same products and so this attribute is made part of the unique definition for the entry.');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Sub-Domain Responsible', 'The sub part of the organization that is responsible for the technology management of the System Type solution');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Sub-Domain SPOC', 'The team lead of the sub part of the organization responsible for the technology management of the System Type solution');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Asset Category', '1st level of asset categorization');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Asset Class', '2nd level of asset categorization');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Asset Type', '3rd level of asset categorization');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Vodafone Name Ids', 'SW App - VF Name '||'('||'Vodafone Name'||')'||'');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Original Design Component Index', 'Original Design Component Index');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Design Component Index', 'Planned Design Component Index');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Vodafone Name', 'SW App - VF Name '||'('||'Vodafone Name'||')'||'');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Name 3GPP', 'Name 3GPP');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Equipment Manufacturer Software', 'Equipment Manufacturer Software');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Major Software', 'Major Software');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Equipment Manufacturer Hardware', 'Equipment Manufacturer Hardware');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Major Hardware', 'Major Hardware');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Design Component Index', 'Design Component Index');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Design Component Family Index', 'Design Component Family Index');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Design Component', 'Design Component');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Design Component Name', 'Planned Design Component Name');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Release Information', 'Software Release Information');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('OpCo Id', 'OpCo Id');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('DCF', 'DCF');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Operational Contact', 'Operational Contact');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Hardware Support Provider', 'Hardware Support Provider');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Hardware Support Type', 'Hardware Support Type');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Hardware End of Support Contract Date', 'Hardware End of Support Contract Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Identity', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Category', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Support Provider', 'Software Support Provider');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software In-Warranty', 'Software In-Warranty');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('SW In-Warranty', 'SW In-Warranty');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software End Of Warranty Date', 'Software End Of Warranty Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Support Type', 'Software Support Type');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software End Of Support Contract', 'Software End Of Support Contract');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('ID', 'Identifier for data record');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Local Market', 'OpCo where the asset is hosted');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Vertical Engineering Team', 'Vertical engineering department in GNED accountable for the asset');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Vertical Sub-Domain', 'Vertical engineering team in GNED accountable for the asset');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Engineering Contact Point', 'Engineering contact point accountable for the asset');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Operations Contact Point', 'Operations contact point accountable for the asset');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Asset Description', 'Brief description of asset');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Vendor', 'Name of asset manufacturer');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Hardware Model', 'HW Model currently installed');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Number of nodes in service production', 'Number of nodes in which is intalled the current HW model or SW release');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Number of nodes in service lab', 'Number of nodes in which is intalled the current HW model or SW release');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Operations Maintenance Contract', '<ul><li>Yes = it exists an active maintenance contract agreed with Vendor</li><li>No = it doesn''t exists a maintenance contract agreed with Vendor</li><li>No '||'('||'VF decision'||')'||' = It doesn''t exist a maintenance contract agreed with Vendor because of a VF internal decision due to budget constraints </li><li>Full extended maintenance = extended maintenance contract that contains full maintenance criteria '||'('||'see below'||')'||'</li><li>Partial extended maintenance = agreement with Vendor for extended support but that does not include full maintenance criteria '||'('||'see below'||')'||'</li></ul><dl>Full maintenance criteria<ul><li>Hardware: Vendor grants remote or on-site hardware fault repairing</li><li>Software: Vendor grants defect corrections, patches, or security updates</li></ul>');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Vendor End Of Maintenance Date', 'Date declared by the Vendor within the official commercial roadmap
Date after which no further defect corrections, patches, security updates, remote or on-site hardware fault repairing is available from Vendor');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('LCM Status', 'The field calculate automatically LCM status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Asset Virtualized', '<ul><li><b>Yes</b> = Virtualized Asset</li><li><b>No</b> = Physical Asset</li></ul>');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Version', 'SW Version currently installed');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Service Boundary', 'Service Boundary');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Service Boundary Description', 'Service Boundary Description');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Service Boundary Id', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('GDPR Relevant', 'GDPR Relevant');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Action', '<ul><li><b>Yes</b> = A remediation action has been clearly identified for the asset</li><li><b>No</b> = No action has been clearly identified</li></ul>');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Edu-Spoc', 'Edu-Spoc');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Date of last review or update', 'Date of last review or update');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Spare 1 '||'('||'Original LCM HW or SW Index'||')'||'', 'Spare 1 '||'('||'Original LCM HW or SW Index'||')'||'');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Spare 2 '||'('||'Original LCM HW Index'||')'||'', 'Spare 2 '||'('||'Original LCM HW Index'||')'||'');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Activities', 'Activities');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Implementation Year', 'Planned Implementation Year');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Activity Details', 'Activity Details');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Activity Details', 'Activity Details');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Activity Status', 'Activity Status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Benefits', 'Benefits');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Benefit Text Network Element', 'Benefit Text Network Element');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Drivers Network Element', 'Drivers Network Element');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Rule Network Element', 'Rule Network Element');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Rule Linked Dc', 'Rule Linked Dc');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Rule Activity Details '||'('||'LCM'||')'||'', 'Rule Activity Details '||'('||'LCM'||')'||'');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Activity Details '||'('||'NEAP'||')'||'', 'Activity Details '||'('||'NEAP'||')'||'');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('LCM Label Software', 'LCM Label Software');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('LCM Label Hardware', 'LCM Label Hardware');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Is For Lcm', 'Is For Lcm');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Is For Network Element', 'Is For Network Element');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Budget Availability', 'Budget Availability');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Budget Availability', 'Budget Availability');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Delivery Project Name', 'Delivery Project Name');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Delivery Plan Available', 'Delivery Plan Available');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Driver', 'Driver');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planning Risks '||'('||'LCM'||')'||'', 'Planning Risks '||'('||'LCM'||')'||'');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Local Approval', 'Local Approval');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Local Approval', 'Local Approval');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planning Activity Status', 'Planning Activity Status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planning Activity Status', 'Planning Activity Status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Max Order', 'Max Order');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Responsibility Phase', 'Responsibility Phase');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Original LCM Hyperlink', 'Original LCM Hyperlink');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Completion', 'Planned Completion');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Notes', 'Notes');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Risk Engineering Evaluation', 'Risk Engineering Evaluation');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Risk Engineering Notes', 'Risk Engineering Notes');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Risk Operational Evaluation', 'Risk Operational Evaluation');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Risk Operational Notes', 'Risk Operational Notes');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Activity Description', 'Planned Activity Description');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Budget Value', 'Budget Value');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Budget Tracking', 'Budget Tracking');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planning Activity Type', 'Planning Activity Type');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planning Risk', 'Planning Risk');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Delivery Project', 'Delivery Project');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Product Importance', 'This can take values of Strategic and Non-Strategic. • Strategic  Key assets to technology evolution with a clear modernisation/evolution plan since capabilities directly impact services that can be offered to customers • Non-Strategic  1. Assets that have no future strategic role and subject to a clear decommission/removal 2. Assets that are key to the ongoing needs of the network but whose features are considered stable and whose feature roadmaps are not directly beneficial to Vodafone’s needs');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Relates To', 'Relates To');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Action', 'Planned Action');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Activity Association', 'Planned Activity Association');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Activity Status', 'Planned Activity Status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('System Solution', 'System Solution');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Description', 'Description');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Equipment Manufacturer Support', 'Equipment Manufacturer Support');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Asset Class', 'Asset Class');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Asset Category', 'Within TEMS assets are described in a hieracrhy of Category, Class and Type. Category is the highest level and this is used to differentiate between System Types used as Network Elements, IPT '||'('||'Customer Care'||')'||' Applications, Networking Equipment, FCAPS Applications and Office Applications.');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Bundle ID', 'Bundle ID');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Bundle Budget', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Business Service Name', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('LCM Status ENG', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('LCM Status OPS', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('OPS Maintenance contract end date', 'OPS Maintenance contract end date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('ENG risk evaluation', 'ENG risk evaluation');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('ENG Risk evaluation notes', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('OPS risk evaluation', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('OPS Risk evaluation notes', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Delivery Status', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Delivery Status', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Vertical Owner', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('VNF Type', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Equipment Manufacturer Certified Release', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Element Name', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Current Release', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Design Component', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('NFVI Bundle ID', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Release '||'('||'Pre Upg'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Equipment Status', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('NFVI Site Designation', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Description Of Planned Action', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Software Version', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Product Name', 'Product Name');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Project Status', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Project End Date', 'Project End Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Tracking Number/Project Name', 'Tracking Number/Project Name');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Next Step', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Status: 12K Switch', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Status: Lab-MC', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Status: Lab-SC', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Status: Live-MC', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Status: Live-SC', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Remarks', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Build Construction', 'Within TEMS different hardware solutions are categorized by Build Construction. Proprietary - The OEM provides both the Hardware and the Software solution and there is a strong vertical integration between the two. COTS - Where Commercial Off The Shelf equipment is used the vertical integration between software and hardware uses standard APIs so the equipment manufacturers are fully decoupled. Typically it is used with specific solutions where Vodafone '||'('||'perhaps in conjunction with a third party'||')'||' have integrated application, middleware and operating system with a COTS hardware solution such as an HP Proliant solution. Voice Core remain responsible for the asset and its life cycle management. Blueprint NFVI/NFCI - A Virtual/Container infrastructure following a Vodafone Defined blueprint architecture and representing a strategic deployment. It hosts multiple applications. The Infrastructure team '||'('||'Not Voice Core'||')'||' are responsible for the asset and its life cycle management. Other NFVI/NFCI - A Virtual/Container infrastructure following deployed before the  blueprint architecture solutions were available. They are not strategic deployment and are being phased out - for example Cisco V-Block. It hosts multiple applications. The Infrastructure team '||'('||'Not Voice Core'||')'||' are responsible for the asset and its life cycle management.');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Hardware Model', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('OPS Maintenance contract end date', 'OPS Maintenance contract end date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('System Type Name Given by the vendor', 'In the System Type table we use the product name of the software application. In TEMS t is automatically pulled through from the Major Software table.');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Spare 1', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('LCM Label', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('JSON Form', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Is Hardware Supported?', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Is Software Supported?', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Design Component Family Index', 'Design Component Family Index');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Full or Partial Support', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('MADE FOR SPARES?', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Renewal In Progress?', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Spares Provisioned', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Lcm Engineering Index', 'Lcm Engineering Index');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('HW End Of Support Contract', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('SW End Of Support Contract', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Reasons for no Support', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Hardware Index', 'TEMS Index unique to the table row');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Hardware Index', 'TEMS Foreign Index belonging to related table');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Index', 'TEMS Index unique to the table row');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Project Status Rule', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Ops Update Tracker', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Eng Update Tracker', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('EOM Control', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Extended Support Option Offered By Vendor', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Managed By GDC', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Asset Out of Scope For Reporting Purposes', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Overall risk evaluation', 'Overall risk evaluation');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('LCM Status Ops', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('LCM Status Eng', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Budget Estimated', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Identified Action', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Output To Lcm Hardware', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Vendor End Of Vulnerability/Security Support Date', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Lcm Status', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Cross Settings', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Lcm Status Eng', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Lcm Status Ops', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Last Modified By', 'Last Modified By');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Capacity Plan Reference', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Network Construct', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Location Type', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Id', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Is For Create', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Is For Edit', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Activity linked', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Description', 'Description');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Node Index', 'Node Index');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Deployment Status', 'Deployment Status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Automated Feedback', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Element Deployment Name', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Functional Entity', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Node Type', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Manual Override', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Version Information', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Product Number', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Production Date', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Install Date', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Hardware Acquisition', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Data Acquisition Date', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Data Acquisition Method', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Element Manager', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Exportable', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Severity', 'Not Used Currently');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('ID', 'Identifier for data record');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Product Name Ids', 'SW App - VF Name '||'('||'Software Application Type Ids'||')'||'');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Element Manager Export File Format', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('For Add Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('For Edit Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Rule Acticvity Details Add Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Activity Details Add Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Activity Details For Virtualized Add Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Rule Add Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Add Asset Hardware', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Add Asset Label Hardware', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Add Asset Label Software', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Driver Text Add Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Benefit Text Add Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planning Risks Add Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('On BareMetal Add Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('On Virtualized Add Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Rule Acticvity Details Edit Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Activity Details Edit Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Activity Details For Virtualized Edit Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Rule Edit Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Edit Asset Hardware', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Edit Asset Label Hardware', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Edit Asset Label Software', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Driver Text Edit Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Benefit Text Edit Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planning Risks Edit Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('on BareMetal Edit Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Delivery', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Technology Area Management', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('ID', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('On Virtualized Edit Asset', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Settings Update Planned Activity Description', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('For Virtualized', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Activity Details For Virtualized Network Element', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Plannig Risk Network Element', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('On Bare Metal', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('On Virtualized', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Rule Activity Details For Network Element', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('On LCM Hardware', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('On LCM Software', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('On Network Element Hardware', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('On Network Element Software', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Network Element Label Software', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Class Description', 'Class Description');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Category Description ', 'Category Description');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Type Description', 'Type Description');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Resource Key', 'Resource Key');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Previous Resource Key', 'Previous Resource Key');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Asset Id', 'Asset Id');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Value', 'Value');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Network Element Label Hardware', 'Network Element Label Hardware');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Deployment Status ID', 'Deployment Status I');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Deployment Status Description', 'Deployment Status Description');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Allowed Planned', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Activity Required', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Read Only Planned', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Current Design Component', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Take From Asset Type Table', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('KPI ID & Name', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Month/Year', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Target Monthly Value '||'('||'Old'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Target Monthly Value '||'('||'Proposed'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Target Monthly Value '||'('||'NEW'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Actual Monthly Value '||'('||'OLD'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('SW OEM', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('SW Release Number', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('HW Platform', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Actual Monthly Value '||'('||'New'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Actual Registered Value '||'('||'OLD'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Default Value', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Location Type', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Opco', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Design Component Index', 'Design Component Index');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Actual Registered Value '||'('||'NEW'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Design Component Required', 'Planned Design Component');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Actual Provisioned Value '||'('||'OLD'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Actual Provisioned Value '||'('||'NEW'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Submission Date', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('System Type Identity Name', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('System Function', 'System Function');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Internet Facing', 'Internet Facing');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('System Is Shared', 'System Is Shared');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Additional Information 1', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Additional Information 2', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Status', 'Not Used Currently');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Submitted By', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('EOY Target '||'('||'Old'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('EOY Target '||'('||'New'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Design Component Family', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Kpi Name', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Rejected/Approved', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Activity Details '||'('||'LCM'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Drivers '||'('||'LCM'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Benefits '||'('||'LCM'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Drivers '||'('||'DA'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Benefits '||'('||'DA'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planning Risks  '||'('||'DA'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planning Risks '||'('||'LCM'||')'||'', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('OpCo', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('OpCo', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Environment', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Color', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Location', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Location Type', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Is Software', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Is Hardware', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Source Asset Id', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Name', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Type', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Description', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Status', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me IP Address', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Virtual Flg', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Siem Integration Flg', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me 2 Fa Integration Flg', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Security Tier', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Idm Integration Flg', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Cyberark Integration Flg', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Service Type', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Serial Number', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('OPS Maintenance contract end date', 'OPS Maintenance contract end date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Completion', 'Planned Completion');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Vendor End Of Maintenance Date', 'Vendor End Of Maintenance Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Start Date', 'Start Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Project End Date', 'Project End Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Vendor End Of Vulnerability Security Support Date', 'Vendor End Of Vulnerability Security Support Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Mac Address', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Last Scan Date', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Last Major Upgrade Date', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Installation Date', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Is For Design Aspect', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Design Aspect HW', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Design Aspect SW', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Activity Details Design Aspect', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Rule For Design Aspect', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Design Aspect Label SW', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Design Aspect Label HW', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Gdpr Relevant Flg', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Fqdn', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me External Connection Flg', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Environment', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Location Type', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Me Criticality', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('LCM Policy', 'LCM Policy');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('SW Application Name', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Business Critical', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('OS Eeosl Contract Date', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('OS Eosl Contract Date', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('OS Name', 'Not Used Currently');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Organisation Name', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Location Name', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Eeosl Contract Date', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Eosl Contract Date', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Lcm Prod Name', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Support Contract', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Criticality', 'Criticality');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Activity Index', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Rule', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Order', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Original EquipmentManu Facturer', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('DCF Name', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('OpCo', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Description', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Supported Services', 'Supported Services');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Used Functional Entities', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Authenication Type', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Security Manager', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('License Model', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Third Party Access', 'Third Party Access');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('LCM Policy', 'LCM Policy');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('PCI/SOX', 'PCI/SOX');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Site Resilience', 'Site Resilience');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('SW Delivery Life Cycle', 'SW Delivery Life Cycle');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Business Continuity Method', 'Business Continuity Method');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Instanse Resilience', 'Instanse Resilience');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Business Critical,', 'Business Critical');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Security Tier Zone', 'Security Tier Zone');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Type of Network Element', 'Type of Network Element');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('EX Networks', 'EX Networks');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('LCM Spreadsheet HW ID', 'LCM Spreadsheet HW ID');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('LCM Spreadsheet SW ID', 'LCM Spreadsheet SW ID');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Archived', 'Archived');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Subnetwork Boundary', 'Subnetwork Boundary');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('End Date', 'End Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Design Component', 'Planned Design Component');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Activity Type is for', 'Planned Activity Type is for');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Planned Activity Type  is for', 'Planned Activity Type is for');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Original Equipment Manufacturer', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Network Element Id', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Platform Type', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Site Location', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Install Date AP', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Install Date CP', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Product Date', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Product Date AP', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Product Date CP', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Product Number AP', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Product Number CP', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Release Information AP', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Release Information CP', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('xml Last Parse File Date', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Creation User', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Creation Date', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Modification User', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Modification Date', 'Description here..');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('IdentityId', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('ApNodeA Ipaddress', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('ApNodeB Ipaddress', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('IP Address', 'IP Address');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Hardware Configuration Id', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Product No', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Product Revision', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Unit Location', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Configuration Id', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Software Component Id', '');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Risk Cluster', 'Risk Cluster');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Custom1', 'Custom1');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Custom2', 'Custom2');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('KPI Status Service', 'KPI Status Service');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Custom', 'Custom');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Reason for no plan', 'Reason for no plan');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Comment on Project Status', 'Comment on Project Status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('RAG Status', 'RAG Status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Security Risk '||'('||'Potential'||')'||'', 'Security Risk '||'('||'Potential'||')'||'');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Security Risk '||'('||'Effective'||')'||'', 'Security Risk '||'('||'Effective'||')'||'');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Security Mitigation', 'Security Mitigation');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Security Risk Overall', 'Security Risk Overall');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Included in Security Scanning', 'Included in Security Scanning');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Asset Status', 'Asset Status');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Last Scan Date', 'Last Scan Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('ENG KPI2', 'ENG KPI2');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Last Upgrade Date', 'Last Upgrade Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Main Organization', 'Main Organization');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Serial Number', 'Serial Number');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('IP Address', 'IP Address');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Host Name', 'Host Name');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Exp. LCM status at end of FY24', 'Exp. LCM status at end of FY24');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Nominal Capacity Limit', 'Nominal Capacity Limit');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Max Allowed Loading', 'Max Allowed Loading');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Designed Capacity Limit', 'Designed Capacity Limit');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Is Software Extended Support Offered By Vendor', 'Is Software Extended support option offered by vendor');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('HW Resource Key', 'HW Resource Key');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Previous HW Resource Key', 'Previous HW Resource Key');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('SW Resource Key', 'SW Resource Key');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Previous SW Resource Key', 'Previous SW Resource Key');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Is Hardware Extended Support Offered By Vendor', 'Is Hardware Extended Support Offered By Vendor');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Program', 'Program');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('WBS Code', 'WBS Code');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('BPT ID', 'BPT ID');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('PPM ID', 'PPM ID');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Project Owner', 'Project Owner');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('RA ID', 'RA ID');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Request ID', 'Request ID');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Original LCM Spreadsheet ID', 'Original LCM Spreadsheet ID');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Product Importance History2', 'Product Importance History2');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('LCM Status '||'('||'june 2021'||')'||'', 'LCM Status '||'('||'june 2021'||')'||'');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('ID_NEW', 'ID_NEW');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Cloud Version', 'Cloud Version');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Lab SW Release', 'Lab SW Release');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Certified SW release for NFVI bundle  3.2.1', 'Certified SW release for NFVI bundle  3.2.1');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Previous ID', 'Previous ID');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Delivery Tracking Index', 'Delivery Tracking Index');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Delivery Tracking Index', 'Delivery Tracking Index');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Activity Index', 'Activity Index');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Asset Name', 'Asset Name');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Resource Type', 'Type of the resource');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Key Status', 'Status of key');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Resource LifeCycle Id', 'Unique ID of Resource LifeCycle Id');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Resource KeyMaster Id', 'Unique ID of Resource KeyMaster ');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Resource Type Id', 'Unique ID of Resource Types');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('DCF LifeCycle Id', 'Unique ID for DCF LifeCycle');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('DCF Long Description', 'Description about Design Component Family');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Design Component Id', 'Unique ID for Design Component');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Event', 'Event');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Event Number', 'Event Number');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Hardware Install Date', 'Hardware Install Date');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Event Id', 'Unique ID for Events');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Event Name', 'Name of the Event');
INSERT INTO GLOSSARYITEMS (HEADER, DESCRIPTION) VALUES ('Details', 'details');
commit;
set define off;