DROP SEQUENCE CNFHARDWARE_SQE;
DROP TABLE CNFHARDWARE ;

DROP SEQUENCE CNFPRIORITY_SQE;
DROP TABLE CNFPRIORITY ;

DROP SEQUENCE CNFCLUSTERINFO_SQE;
DROP TABLE CNFCLUSTERINFO  ;

DROP SEQUENCE CNFPODINFO_SQE;
DROP TABLE CNFPODINFO ;  

DROP SEQUENCE CNFCAPACITY_SQE;
DROP TABLE CNFCAPACITY  ;

RENAME CNFINFO_BACKUP TO CNFINFO;
RENAME CNFCLUSTERINFO_BACKUP TO CNFCLUSTERINFO;
RENAME CNFCAPACITY_BACKUP TO CNFCAPACITY;

alter table cnfcluster drop column alaisname; 


 ALTER TABLE CNFCLUSTERINFO ADD   NOOFCNFINSTANCESPERSITE  NUMBER(10);
ALTER TABLE CNFPODINFO ADD  NUMBEROFPODSPERPODTYPE  NUMBER(10);
ALTER TABLE CNFCAPACITY DROP COLUMN   NOOFCNFINSTANCESPERSITE  ;
ALTER TABLE CNFCAPACITY DROP COLUMN   NUMBEROFPODSPERPODTYPE ;



  ALTER TABLE VNFINFO ADD   NOOFVNFINSTANCES  NUMBER(19);
  ALTER TABLE VNFINFO ADD NOOFVMSPERTYPE  NUMBER(19);

UPDATE VNFINFO vc
SET (vc.NOOFVNFINSTANCES, vc.NOOFVMSPERTYPE) = (
    SELECT vi.NOOFVNFINSTANCES, vi.NOOFVMSPERTYPE
    FROM VNFINFO vi
    WHERE vi.VNFINFOID = vc.VNFINFOID
)
WHERE EXISTS (
    SELECT 1
    FROM VNFVMCAPACITY vi
    WHERE vi.VNFINFOID = vc.VNFINFOID
);
Commit;
 
ALTER TABLE VNFVMCAPACITY DROP COLUMN   NOOFVNFINSTANCES  ; 
ALTER TABLE VNFVMCAPACITY DROP COLUMN   NOOFVMSPERTYPE  ; 

