
----------------ALTER SCRIPT FOR PASSTHROUGHLCM------------------

RENAME "PASSTHROUGHLCM_SEQ" TO "SWPASSTHROUGHLCM_SEQ";

ALTER TABLE "PASSTHROUGHLCM" RENAME TO "SWPASSTHROUGHLCM";

ALTER TABLE "SWPASSTHROUGHLCM" MODIFY PASSTHROUGHLCMID DEFAULT "SWPASSTHROUGHLCM_SEQ"."NEXTVAL";

ALTER TABLE "SWPASSTHROUGHLCM" RENAME CONSTRAINT "FK_PASSTHROUGHLCM_ASPNETUSERS_CREATIONUSER" TO "FK_SWPASSTHROUGHLCM_ASPNETUSERS_CREATIONUSER";
ALTER TABLE "SWPASSTHROUGHLCM" RENAME CONSTRAINT "FK_PASSTHROUGHLCM_ASPNETUSERS_MODIFICATIONUSER" TO "FK_SWPASSTHROUGHLCM_ASPNETUSERS_MODIFICATIONUSE";
ALTER TABLE "SWPASSTHROUGHLCM" RENAME CONSTRAINT "FK_PASSTHROUGHLCM_VERTICALRESPONSIBLES_NONTEMSVERTICAL" TO "FK_SWPASSTHROUGHLCM_VERTICALRESPONSIBLES_NONTEMSVERTICAL";

ALTER TABLE "SWPASSTHROUGHLCM" ADD "SWRESOURCEKEY" NVARCHAR2(500);

ALTER TABLE "SWPASSTHROUGHLCM" ADD CONSTRAINT "SWPASSTHROUGHLCM_SWRESOURCEKEY" UNIQUE ("SWRESOURCEKEY");

ALTER TABLE "SWPASSTHROUGHLCM" DROP COLUMN "HWOPERATIONSCONTACTPOINT" ;
ALTER TABLE "SWPASSTHROUGHLCM" DROP COLUMN "HWVENDOR" ;
ALTER TABLE "SWPASSTHROUGHLCM" DROP COLUMN "HWOPERATIONSMAINTENANCECONTRACT" ;
ALTER TABLE "SWPASSTHROUGHLCM" DROP COLUMN "HWVENDORENDOFMAINTENANCEDATE" ;
ALTER TABLE "SWPASSTHROUGHLCM" DROP COLUMN "PLANNEDHWMODEL" ;
ALTER TABLE "SWPASSTHROUGHLCM" DROP COLUMN "HWOPSMAINTENANCECONTRACTENDDATE" ;
ALTER TABLE "SWPASSTHROUGHLCM" DROP COLUMN "LCMSTATUSENGHARDWARE" ;
ALTER TABLE "SWPASSTHROUGHLCM" DROP COLUMN "LCMSTATUSOPSHARDWARE" ;

----------------ALTER SCRIPT FOR PASSTHROUGH------------------

RENAME "PASSTHROUGH_SEQ" TO "ASSETPASSTHROUGH_SEQ";

ALTER TABLE "PASSTHROUGH" RENAME TO "ASSETPASSTHROUGH";

ALTER TABLE "ASSETPASSTHROUGH" MODIFY "PASSTHROUGHID" DEFAULT "ASSETPASSTHROUGH_SEQ"."NEXTVAL";

ALTER TABLE "ASSETPASSTHROUGH" RENAME CONSTRAINT "FK_PASSTHROUGH_ASPNETUSERS_CREATIONUSER" TO "FK_ASSETPASSTHROUGH_ASPNETUSERS_CREATIONUSER";
ALTER TABLE "ASSETPASSTHROUGH" RENAME CONSTRAINT "FK_PASSTHROUGH_ASPNETUSERS_MODIFICATIONUSER" TO "FK_ASSETPASSTHROUGH_ASPNETUSERS_MODIFICATIONUSER";
ALTER TABLE "ASSETPASSTHROUGH" RENAME CONSTRAINT "FK_PASSTHROUGH_VERTICALRESPONSIBLES_NONTEMSVERTICAL" TO "FK_ASSETPASSTHROUGH_VERTICALRESPONSIBLES_NONTEMSVERTICAL";
--------DROP CONSTRAINT------
ALTER TABLE "ASSETPASSTHROUGH" DROP CONSTRAINT "FK_PASSTHROUGH_PASSTHROUGHLCM_VODAFONEUNIQUEIDENTIFIER";
--------ADD CONSTRAINT-------
UPDATE ASSETPASSTHROUGH SET VODAFONEUNIQUEIDENTIFIER = NULL;
COMMIT;
ALTER TABLE "ASSETPASSTHROUGH" ADD RESOURCEKEY NVARCHAR2(200);
ALTER TABLE "ASSETPASSTHROUGH" ADD CONSTRAINT "FK_PASSTHROUGH_SWPASSTHROUGHLCM_RESOURCEKEY" FOREIGN KEY ("RESOURCEKEY") REFERENCES "SWPASSTHROUGHLCM" ("SWRESOURCEKEY") ENABLE;
ALTER TABLE "ASSETPASSTHROUGH" MODIFY VODAFONEUNIQUEIDENTIFIER NUMBER(19,0) DEFAULT "ASSETPASSTHROUGH_SEQ"."NEXTVAL";



-----------------HWRESOURCEKEY--------------
ALTER TABLE HWPASSTHROUGHLCM ADD "HWRESOURCKEY" NVARCHAR2(200);