--------------------------------------------------------
--  DDL FOR SEQUENCE USERDEFINEDREPORTSLOGS_SEQ
--------------------------------------------------------
 
CREATE SEQUENCE "USERDEFINEDREPORTSLOGS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;
 
 
 
--------------------------------------------------------
--  DDL FOR TABLE USERDEFINEDREPORTSLOGS
--------------------------------------------------------

CREATE TABLE USERDEFINEDREPORTSLOGS (
"USERDEFINEDREPORTSLOGID" NUMBER(10,0) DEFAULT "USERDEFINEDREPORTSLOGS_SEQ"."NEXTVAL",
"REPORTNAME" NVARCHAR2(300),
"REPORTFORMAT" NVARCHAR2(10),
"REPORTDOWNLOADEDPATH" NVARCHAR2(300),
"REPORTSTATUS" NVARCHAR2(300),
"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"DELETED" NUMBER(1,0) DEFAULT 0, 
"DELETIONDATE" TIMESTAMP (6)
)SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_SEVERITY
--------------------------------------------------------
 
CREATE UNIQUE INDEX "PK_USERDEFINEDREPORTSLOGID" ON "USERDEFINEDREPORTSLOGS" ("USERDEFINEDREPORTSLOGID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE USERDEFINEDREPORTSLOGS
--------------------------------------------------------
 
ALTER TABLE "USERDEFINEDREPORTSLOGS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "USERDEFINEDREPORTSLOGS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "USERDEFINEDREPORTSLOGS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "USERDEFINEDREPORTSLOGS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "USERDEFINEDREPORTSLOGS" ADD CONSTRAINT "PK_USERDEFINEDREPORTSLOGS" PRIMARY KEY ("USERDEFINEDREPORTSLOGID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE USERDEFINEDREPORTSLOGS
--------------------------------------------------------
 
ALTER TABLE "USERDEFINEDREPORTSLOGS" ADD CONSTRAINT "FK_USERDEFINEDREPORTSLOGS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "USERDEFINEDREPORTSLOGS" ADD CONSTRAINT "FK_USERDEFINEDREPORTSLOGS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
 
COMMIT;
  