
--------------------------------------------------------
--  DDL for Sequence SWCONFIGSUBFUNCTION_SEQ
--------------------------------------------------------

CREATE SEQUENCE "SWCONFIGSUBFUNCTION_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;




--------------------------------------------------------
--  DDL for Table SWCONFIGSUBFUNCTION
--------------------------------------------------------

CREATE TABLE "SWCONFIGSUBFUNCTION" 
("SWCONFIGSUBFUNCTIONID" NUMBER(10,0) DEFAULT "SWCONFIGSUBFUNCTION_SEQ"."NEXTVAL", 
"SWCONFIGFUNCTIONAREAID" NUMBER(20,0), 
"SUBFUNCTIONNAME" NVARCHAR2(50),
"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
"DELETED" NUMBER(1,0) DEFAULT 0, 
"DELETIONDATE" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;

--------------------------------------------------------
--  DDL for Index PK_SWCONFIGSUBFUNCTION
--------------------------------------------------------

CREATE UNIQUE INDEX "PK_SWCONFIGSUBFUNCTION" ON "SWCONFIGSUBFUNCTION" ("SWCONFIGSUBFUNCTIONID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table SWCONFIGSUBFUNCTION
--------------------------------------------------------

ALTER TABLE "SWCONFIGSUBFUNCTION" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "SWCONFIGSUBFUNCTION" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "SWCONFIGSUBFUNCTION" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "SWCONFIGSUBFUNCTION" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "SWCONFIGSUBFUNCTION" ADD CONSTRAINT "PK_SWCONFIGSUBFUNCTION" PRIMARY KEY ("SWCONFIGSUBFUNCTIONID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SWCONFIGFUNCTIONAREAS
--------------------------------------------------------

ALTER TABLE "SWCONFIGSUBFUNCTION" ADD CONSTRAINT "FK_SWCONFIGSUBFUNCTION_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "SWCONFIGSUBFUNCTION" ADD CONSTRAINT "FK_SWCONFIGSUBFUNCTION_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "SWCONFIGSUBFUNCTION" ADD CONSTRAINT "FK_SWCONFIGSUBFUNCTION_SWCONFIGFUNCTIONAREAS_SWCONFIGFUNCTIONAREAID" FOREIGN KEY ("SWCONFIGFUNCTIONAREAID")
REFERENCES "SWCONFIGFUNCTIONAREAS" ("SWCONFIGFUNCTIONAREAID") ENABLE;

COMMIT;