
--------------------------------------------------------
--  DDL for Sequence SWCONFIGSUBFUNCTIONAREA_SEQ
--------------------------------------------------------

CREATE SEQUENCE "SWCONFIGSUBFUNCTIONAREA_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;




--------------------------------------------------------
--  DDL for Table SWCONFIGSUBFUNCTIONAREAS
--------------------------------------------------------

CREATE TABLE "SWCONFIGSUBFUNCTIONAREAS" 
("SWCONFIGSUBFUNCTIONAREAID" NUMBER(10,0) DEFAULT "SWCONFIGSUBFUNCTIONAREA_SEQ"."NEXTVAL", 
"SWCONFIGSUBFUNCTIONID" NUMBER(10,0), 
"SUBFUNCTIONAREANAME" NVARCHAR2(50),
"SUBFUNCTIONAREADESCRIPTION" NCLOB,
"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
"DELETED" NUMBER(1,0) DEFAULT 0, 
"DELETIONDATE" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;

--------------------------------------------------------
--  DDL for Index PK_SWCONFIGSUBFUNCTIONAREA
--------------------------------------------------------

CREATE UNIQUE INDEX "PK_SWCONFIGSUBFUNCTIONAREAS" ON "SWCONFIGSUBFUNCTIONAREAS" ("SWCONFIGSUBFUNCTIONAREAID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table SWCONFIGSUBFUNCTIONAREAS
--------------------------------------------------------

ALTER TABLE "SWCONFIGSUBFUNCTIONAREAS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "SWCONFIGSUBFUNCTIONAREAS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "SWCONFIGSUBFUNCTIONAREAS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "SWCONFIGSUBFUNCTIONAREAS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "SWCONFIGSUBFUNCTIONAREAS" ADD CONSTRAINT "PK_SWCONFIGSUBFUNCTIONAREAS" PRIMARY KEY ("SWCONFIGSUBFUNCTIONAREAID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SWCONFIGSUBFUNCTIONAREAS
--------------------------------------------------------

ALTER TABLE "SWCONFIGSUBFUNCTIONAREAS" ADD CONSTRAINT "FK_SWCONFIGSUBFUNCTIONAREAS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "SWCONFIGSUBFUNCTIONAREAS" ADD CONSTRAINT "FK_SWCONFIGSUBFUNCTIONAREAS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "SWCONFIGSUBFUNCTIONAREAS" ADD CONSTRAINT "FK_SWCONFIGSUBFUNCTIONAREAS_SWCONFIGSUBFUNCTION_SWCONFIGSUBFUNCTIONID" FOREIGN KEY ("SWCONFIGSUBFUNCTIONID")
REFERENCES "SWCONFIGSUBFUNCTION" ("SWCONFIGSUBFUNCTIONID") ENABLE;

COMMIT;