--------------------------------------------------------
--  DDL FOR SEQUENCE ORGANISATION_SEQ
--------------------------------------------------------
 
CREATE SEQUENCE "ORGANISATION_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;
 
--------------------------------------------------------
--  DDL FOR TABLE ORGANISATION
--------------------------------------------------------

CREATE TABLE ORGANISATION (
"ORGANISATIONID" NUMBER(19,0) DEFAULT "ORGANISATION_SEQ"."NEXTVAL",
"MAINORGANISATION" NVARCHAR2(200),
"HEADOFORGANISATIONID" NUMBER(10,0),
"SUBPRACTICE" NVARCHAR2(200),
"SUBPRACTICECONTACTID" NUMBER(10,0),
"OPCOID" NUMBER(5,0),
"VERTICALRESPONSIBLEID" NUMBER(10,0),
"SUBDOMAINRESPONSIBLEID" NUMBER(10,0),
"CONTACTID" NUMBER(10,0),
"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"DELETED" NUMBER(1,0) DEFAULT 0, 
"DELETIONDATE" TIMESTAMP (6)
)SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_ORGANISATION
--------------------------------------------------------
 
CREATE UNIQUE INDEX "PK_ORGANISATION" ON "ORGANISATION" ("ORGANISATIONID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE ORGANISATION
--------------------------------------------------------
 
ALTER TABLE "ORGANISATION" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "ORGANISATION" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "ORGANISATION" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "ORGANISATION" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "ORGANISATION" MODIFY ("OPCOID" NOT NULL ENABLE);
ALTER TABLE "ORGANISATION" MODIFY ("HEADOFORGANISATIONID" NOT NULL ENABLE);
ALTER TABLE "ORGANISATION" MODIFY ("SUBPRACTICECONTACTID" NOT NULL ENABLE);
ALTER TABLE "ORGANISATION" MODIFY ("VERTICALRESPONSIBLEID" NOT NULL ENABLE);
ALTER TABLE "ORGANISATION" MODIFY ("SUBDOMAINRESPONSIBLEID" NOT NULL ENABLE);
ALTER TABLE "ORGANISATION" MODIFY ("CONTACTID" NOT NULL ENABLE);
ALTER TABLE "ORGANISATION" ADD CONSTRAINT "PK_ORGANISATION" PRIMARY KEY ("ORGANISATIONID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE ORGANISATION 
--------------------------------------------------------
 
ALTER TABLE "ORGANISATION" ADD CONSTRAINT "FK_ORGANISATION_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "ORGANISATION" ADD CONSTRAINT "FK_ORGANISATION_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "ORGANISATION" ADD CONSTRAINT "FK_ORGANISATION_ASPNETUSERS_HEADOFORGANISATIONID" FOREIGN KEY ("HEADOFORGANISATIONID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "ORGANISATION" ADD CONSTRAINT "FK_ORGANISATION_ASPNETUSERS_CONTACTID" FOREIGN KEY ("CONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "ORGANISATION" ADD CONSTRAINT "FK_ORGANISATION_ASPNETUSERS_SUBPRACTICECONTACTID" FOREIGN KEY ("SUBPRACTICECONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "ORGANISATION" ADD CONSTRAINT "FK_ORGANISATION_OPCOS_OPCOID" FOREIGN KEY ("OPCOID") REFERENCES "OPCOS" ("OPCOID") ENABLE;
ALTER TABLE "ORGANISATION" ADD CONSTRAINT "FK_ORGANISATION_VERTICALRESPONSIBLES_VERTICALRESPONSIBLEID" FOREIGN KEY ("VERTICALRESPONSIBLEID") REFERENCES "VERTICALRESPONSIBLES" ("VERTICALRESPONSIBLEID") ENABLE;
ALTER TABLE "ORGANISATION" ADD CONSTRAINT "FK_ORGANISATION_SUBDOMAINRESPONSIBLES_SUBDOMAINRESPONSIBLEID" FOREIGN KEY ("SUBDOMAINRESPONSIBLEID") REFERENCES "SUBDOMAINRESPONSIBLES" ("SUBDOMAINRESPONSIBLEID") ENABLE;
COMMIT;
