--------------------------------------------------------
--  DDL FOR TABLE ASPNETMODULES_SEQ
--------------------------------------------------------

CREATE SEQUENCE "ASPNETMODULES_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE ASPNETMODULES
---------------------------------------


CREATE TABLE "ASPNETMODULES" 
(	"ASPNETMODULEID" NUMBER(10,0) DEFAULT "ASPNETMODULES_SEQ"."NEXTVAL", 	
	"MODULE" NVARCHAR2(250),
	"ALIASNAME" NVARCHAR2(250),
	"CATEGORY" NVARCHAR2(200),
	"ISDEFAULT" NUMBER(1,0),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
	
  --------------------------------------------------------
--  DDL FOR INDEX PK_ASPNETMODULES
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_ASPNETMODULES" ON "ASPNETMODULES" ("ASPNETMODULEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE ASPNETMODULES
--------------------------------------------------------
 
  ALTER TABLE "ASPNETMODULES" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASPNETMODULES" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASPNETMODULES" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASPNETMODULES" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASPNETMODULES" ADD CONSTRAINT "PK_ASPNETMODULES" PRIMARY KEY ("ASPNETMODULEID") USING INDEX "PK_ASPNETMODULES"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE ASPNETMODULES
--------------------------------------------------------

  ALTER TABLE "ASPNETMODULES" ADD CONSTRAINT "FK_ASPNETMODULES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "ASPNETMODULES" ADD CONSTRAINT "FK_ASPNETMODULES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  
  COMMIT;
  
  
  
  --------------------------------------------------------
--  DDL FOR TABLE ASPNETUSERROLEPERMISSIONS_SEQ
--------------------------------------------------------

CREATE SEQUENCE "ASPNETUSERROLEPERMISSIONS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE ASPNETUSERROLEPERMISSIONS
---------------------------------------


CREATE TABLE "ASPNETUSERROLEPERMISSIONS" 
(	"ASPNETUSERROLEPERMISSIONID" NUMBER(10,0) DEFAULT "ASPNETUSERROLEPERMISSIONS_SEQ"."NEXTVAL", 	
	"ROLEID" NUMBER(10,0),
	"MODULEID" NUMBER(10,0),
	"PERMISSIONLEVEL" NUMBER(5,0),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
	
  --------------------------------------------------------
--  DDL FOR INDEX PK_ASPNETUSERROLEPERMISSIONS
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_ASPNETUSERROLEPERMISSIONS" ON "ASPNETUSERROLEPERMISSIONS" ("ASPNETUSERROLEPERMISSIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE ASPNETUSERROLEPERMISSIONS
--------------------------------------------------------
 
  ALTER TABLE "ASPNETUSERROLEPERMISSIONS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSERROLEPERMISSIONS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSERROLEPERMISSIONS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSERROLEPERMISSIONS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSERROLEPERMISSIONS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSERROLEPERMISSIONS" ADD CONSTRAINT "PK_ASPNETUSERROLEPERMISSIONS" PRIMARY KEY ("ASPNETUSERROLEPERMISSIONID") USING INDEX "PK_ASPNETUSERROLEPERMISSIONS"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE ASPNETUSERROLEPERMISSIONS
--------------------------------------------------------

  ALTER TABLE "ASPNETUSERROLEPERMISSIONS" ADD CONSTRAINT "FK_ASPNETUSERROLEPERMISSIONS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "ASPNETUSERROLEPERMISSIONS" ADD CONSTRAINT "FK_ASPNETUSERROLEPERMISSIONS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "ASPNETUSERROLEPERMISSIONS" ADD CONSTRAINT "FK_ASPNETUSERROLEPERMISSIONS_ASPNETMODULES_MODULEID" FOREIGN KEY ("MODULEID") REFERENCES "ASPNETMODULES" ("ASPNETMODULEID") ENABLE;
  ALTER TABLE "ASPNETUSERROLEPERMISSIONS" ADD CONSTRAINT "FK_ASPNETUSERROLEPERMISSIONS_ASPNETROLES_ROLEID" FOREIGN KEY ("ROLEID") REFERENCES "ASPNETROLES" ("ID") ENABLE;
  COMMIT;
  
 ------------------------- 
ALTER TABLE GRIDCUSTOMCOLUMN ADD  ACHIEVEMENTDATE  NUMBER(10); 
ALTER TABLE GRIDCUSTOMCOLUMN ADD  SIGNPOSTDATE  NUMBER(10); 
ALTER TABLE ORGANISATION ADD   ISDESIGNCONTACT  NUMBER(1)  ; 

COMMIT; 