--------------------------------------------------------
--  DDL for Sequence PASSTHROUGH_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PASSTHROUGH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4041 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table PASSTHROUGH
--------------------------------------------------------

  CREATE TABLE "PASSTHROUGH" 
   (
    "PASSTHROUGHID" NUMBER(19,0) DEFAULT "PASSTHROUGH_SEQ"."NEXTVAL", 
    "NONTEMSVERTICAL" NUMBER(19,0) DEFAULT null, 
	"VODAFONEUNIQUEIDENTIFIER" NVARCHAR2(50), 
	"ASSETNAME" NVARCHAR2(250), 
	"ASSETDESCRIPTIONORPURPOSE" NVARCHAR2(2000), 
	"ASSETTYPE" NVARCHAR2(50), 
	"BUSINESSOWNER" NVARCHAR2(250), 
	"SUPPORTOWNER" NVARCHAR2(250), 
	"SUPPORTTEAM" NVARCHAR2(250), 
	"SUPPORTTEAMSPLACEINTHEORGANISATION" NVARCHAR2(250), 
	"ASSETFUNCTION" NVARCHAR2(250), 
	"DEPLOYMENTORLIFECYCLESTATUS" NVARCHAR2(250), 
	"RELATEDRISKIDSFROMRISKREGISTERS" NVARCHAR2(250), 
	"REGULATORYSCOPE" NVARCHAR2(50), 
	"COUNTRYWHEREASSETISLOCATED" NVARCHAR2(50), 
	"GEOLOCATION" NVARCHAR2(250), 
	"INFRASTRUCTURE" NVARCHAR2(250), 
	"UPSTREAMDEPENDENCIES" NVARCHAR2(2000), 
	"DOWNSTREAMDEPENDENCIES" NVARCHAR2(2000), 
	"CHANGESTOTHEASSETSINCEDEPLOYMENT" NVARCHAR2(50), 
	"CLOUDHOSTEDASSET" NVARCHAR2(50), 
	"CLOUDTYPE" NVARCHAR2(50), 
	"CLOUDVENDOR" NVARCHAR2(50), 
	"EQUIPMENTNAME" NVARCHAR2(250), 
	"HOSTLOCATIONWITHINPHYSICALLOCATION" NVARCHAR2(50), 
	"SOFTWAREVENDORNAME" NVARCHAR2(250), 
	"FIRMWAREVERSIONPATCHLEVEL" NVARCHAR2(50), 
	"MAINTENANCESUPPORTSUPPLIER" NVARCHAR2(250), 
	"DEPENDANTHARDWARE" NVARCHAR2(250), 
	"INSTANCETYPE" NVARCHAR2(50), 
	"OPERATINGSYSTEMNAME" NVARCHAR2(50), 
	"OPERATINGSYSTEMSWVVERSION" NVARCHAR2(50), 
	"OPERATINGSYSTEMSWVERSIONPATCHLEVEL" NVARCHAR2(50), 
	"SYSTEMNAMEDNS" NVARCHAR2(2000), 
	"SYSTEMNAMEMANAGEMENTIPADDRESS" NVARCHAR2(250), 
	"SYSTEMNAMENETBIOS" NVARCHAR2(50), 
	"SYSTEMNAMEHOSTNAME" NVARCHAR2(50), 
	"HARDWAREVENDORNAME" NVARCHAR2(250), 
	"MAINTENANCESUPPORTSUPPLIERSECOND" NVARCHAR2(250), 
	"DEPENDANTSYSTEMSOFTWARE" NVARCHAR2(50), 
	"RESILIENCEMODEL" NVARCHAR2(50), 
	"GEOGRAPHICSITERESILIENCE" NVARCHAR2(2000), 
	"LOCALSITERESILIENCE" NVARCHAR2(2000), 
	"NAMEOFPRODUCTSDEPENDANTONASSET" NVARCHAR2(250), 
	"TECHNICALSERVICENAMES" NVARCHAR2(2000), 
	"CUSTOMER" NVARCHAR2(250), 
	"PRIVILEGEDACCESSLOGGING" NVARCHAR2(50), 
	"BOARDORMODULENAMECOMPONENTNAME" NCLOB, 
	"EXPOSEDEDGE" NVARCHAR2(50), 
	"EXTERNALLYFACINGSYSTEM" NVARCHAR2(50), 
	"MANAGEMENTPLANE" NVARCHAR2(50), 
	"NETWORKOVERSIGHTFUNCTION" NVARCHAR2(50), 
	"PECN" NVARCHAR2(50), 
	"PECS" NVARCHAR2(50), 
	"SECURITYCRITICALFUNCTION" NVARCHAR2(50), 
	"PRODUCTIMPORTANCE" NVARCHAR2(50), 
	"CRITICAL" NVARCHAR2(50), 
	"CRITICALITYTYPE" NVARCHAR2(2000), 
	"PARTNUMBER" NVARCHAR2(50), 
	"DESCRIPTIONOFPLANNEDACTION" NVARCHAR2(250), 
	"IDENTIFIEDACTION" NVARCHAR2(50), 
	"PRODORLAB" NVARCHAR2(50), 
	"LOCALMARKETOWNERSHIP" NVARCHAR2(50), 
	"BUDGETESTIMATED" NVARCHAR2(50), 
	"BUNDLEBUDGET" NVARCHAR2(50), 
	"ASSURANCECALL" NVARCHAR2(250), 
	"COMMENTONPROJECTSTATUS" NVARCHAR2(2000), 
	"PROJECTSTATUS" NVARCHAR2(50), 
	"SERVICELEVEL" NVARCHAR2(50), 
	"LASTPENTESTREFNO" NVARCHAR2(2000), 
	"PIDATA" NVARCHAR2(50), 
	"ENCRYPTEDPIDATA" NVARCHAR2(50), 
	"RECORDCLASSIFIER" NUMBER(10,0), 
	"VENDORHARDWAREENDOFSUPPORTDATE" NVARCHAR2(50), 
	"MAINTENANCEHARDWAREENDOFSUPPORTDATE" NVARCHAR2(50), 
	"DATEASSETMOVEDTOLIVESTATUS" NVARCHAR2(50), 
	"DATEASSETDECOMMISSIONED" NVARCHAR2(50), 
	"VENDORSOFTWAREENDOFSUPPORTDATE" NVARCHAR2(50), 
	"MAINTENANCESOFTWAREENDOFSUPPORTDATE" NVARCHAR2(50), 
	"LASTUPGRADEDATE" NVARCHAR2(50), 
	"LASTPENTESTDATE" NVARCHAR2(50), 
	"PROJECTENDDATE" NVARCHAR2(50), 
	"MODEL" NCLOB, 
	"FIRMWAREVERSION" NCLOB, 
	"BOARDORMODULETYPECOMPONENTSUBTYPE" NCLOB, 
	"BOARDORMODULETYPECOMPONENTVERSIONNUMBER" NCLOB, 
	"SERIALNUMBER" NCLOB,
	"HARDWARETYPEOFHARDWAREASSET" NVARCHAR2(50),
	"HWENDOFSALE " NVARCHAR2(50),
	"SOFTWAREPRODUCTTYPE" NVARCHAR2(50),
	"SOFTWAREPRODUCTVERSION" NVARCHAR2(50),
	"APPLICATIONHOSTEDONSOFTWARE" NVARCHAR2(200),
	"UUIDORSERIALNUMBEROFSOFTWARE." NVARCHAR2(200),
	"SWENDOFSALE" NVARCHAR2(50),
	"VERTICALENGINEERINGTEAM" NVARCHAR2(200),
	"VERTICALSUBDOMAIN" NVARCHAR2(200),
	"PLATFORM" NVARCHAR2(50),
	"RISKCLUSTER" NVARCHAR2(50),
	"OPERATIONSCONTACTPOINT" NVARCHAR2(200),
	"ASSETCLASS" NVARCHAR2(50),
	"OPERATIONSMAINTENANCECONTRACT" NVARCHAR2(200),
	"VENDORENDOFMAINTENANCE DATE" NVARCHAR2(50),
	"OPSMAINTENANCECONTRACTENDDATE" NVARCHAR2(50),
	"INCIDENTCLASS" NVARCHAR2(50),
	"OCCURRENCEPROBABILITY" NVARCHAR2(50),
	"ORGANIZATIONORPERSONGROUP" NVARCHAR2(200),
	"TYPEOFNETWORKELEMENT" NVARCHAR2(50),
	"APPLICATION" NVARCHAR2(50),
	"PHYSICALSERVERHOSTNAME" NVARCHAR2(50),
	"PHYSICALSERVERIPADDRESS" NVARCHAR2(50),
	"PHYSICALSERVERSERIALNUMBER" NVARCHAR2(50),
	"PHYSICALSERVERHW MODEL" NVARCHAR2(50),
	"PHYSICALSERVERVENDOR" NVARCHAR2(50),
	"VIRTUALSERVERHOSTEDON" NVARCHAR2(50),
	"VIRTUALSERVERMANUFACTURER" NVARCHAR2(50),
	"VIRTUALSERVERTYPEOFDEVICE" NVARCHAR2(50),
	"VIRTUALMACHINETYPE" NVARCHAR2(50),
	"VIRTUALSERVERSERIALNUMBER" NVARCHAR2(50),
	"VIRTUALSERVERTYPE" NVARCHAR2(50),
	"OSSTARTDATE" NVARCHAR2(50),
	"OSINSTALLATIONDATE" NVARCHAR2(50),
	"OSSTATUS" NVARCHAR2(50),
	"SOFTWARENAME" NVARCHAR2(50),
	"VERSION" NVARCHAR2(50),
	"RELEASE" NVARCHAR2(50),
	"LANGUAGE" NVARCHAR2(50),
	"HWOPSCONTRACTSTATUS" NVARCHAR2(200),	
	"HWOPSCONTRACTENDDATE"	NVARCHAR2(200),
	"SWOPSCONTRACTSTATUS" NVARCHAR2(200),	
	"SWOPSCONTRACTENDDATE"	NVARCHAR2(200),
	"HWOPERATIONSCONTACTPOINT" NVARCHAR2(200),	
	"SWOPERATIONSCONTACTPOINT"	NVARCHAR2(200),
	"PLANNEDHWMODEL" NVARCHAR2(200),
	"ASSETCATEGORY" NVARCHAR2(200),
	"LOCATIONORDATACENTRE" NVARCHAR2(200),
	"VIRTUALSERVERIPADDRESS" NVARCHAR2(200),
	"PHYSICALSERVEROSNAME" NVARCHAR2(200),
	"PHYSICALOSVERSION" NVARCHAR2(200),
	"PHYSICALSERVEROSSTARTDATE" NVARCHAR2(200),
	"PHYSICALSERVEROSINSTALLATIONDATE" NVARCHAR2(200),
	"PHYSICALSERVEROSSTATUS" NVARCHAR2(200),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" 
 LOB ("BOARDORMODULENAMECOMPONENTNAME") STORE AS SECUREFILE (
  TABLESPACE "CAMDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("MODEL") STORE AS SECUREFILE (
  TABLESPACE "CAMDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("FIRMWAREVERSION") STORE AS SECUREFILE (
  TABLESPACE "CAMDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("BOARDORMODULETYPECOMPONENTSUBTYPE") STORE AS SECUREFILE (
  TABLESPACE "CAMDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("BOARDORMODULETYPECOMPONENTVERSIONNUMBER") STORE AS SECUREFILE (
  TABLESPACE "CAMDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("SERIALNUMBER") STORE AS SECUREFILE (
  TABLESPACE "CAMDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index PK_PASSTHROUGH
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PASSTHROUGH" ON "PASSTHROUGH" ("PASSTHROUGHID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table PASSTHROUGH
--------------------------------------------------------

  ALTER TABLE "PASSTHROUGH" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "PASSTHROUGH" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "PASSTHROUGH" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "PASSTHROUGH" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "PASSTHROUGH" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "PASSTHROUGH" ADD CONSTRAINT "PK_PASSTHROUGH" PRIMARY KEY ("PASSTHROUGHID")
  USING INDEX "PK_PASSTHROUGH"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PASSTHROUGH
--------------------------------------------------------

  ALTER TABLE "PASSTHROUGH" ADD CONSTRAINT "FK_PASSTHROUGH_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "PASSTHROUGH" ADD CONSTRAINT "FK_PASSTHROUGH_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "PASSTHROUGH" ADD CONSTRAINT "FK_PASSTHROUGH_APPSETTINGSCONFIGURATION_NONTEMSVERTICAL" FOREIGN KEY ("NONTEMSVERTICAL")
	  REFERENCES "APPSETTINGSCONFIGURATION" ("APPCONFIGURATIONSETTINGID") ENABLE;
