--------------------------------------------------------
--  DDL for Sequence NONTEMSPASSTHROUGHCONFIG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NONTEMSPASSTHROUGHCONFIG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100080 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table NONTEMSPASSTHROUGHCONFIG
--------------------------------------------------------

  CREATE TABLE "NONTEMSPASSTHROUGHCONFIG" 
   (	"NONTEMSPASSTHROUGHCONFIGID" NUMBER(19,0) DEFAULT "NONTEMSPASSTHROUGHCONFIG_SEQ"."NEXTVAL", 
	"ELEMENTNAME" NVARCHAR2(50), 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index PK_NONTEMSPASSTHROUGHCONFIG
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_NONTEMSPASSTHROUGHCONFIG" ON "NONTEMSPASSTHROUGHCONFIG" ("NONTEMSPASSTHROUGHCONFIGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table NONTEMSPASSTHROUGHCONFIG
--------------------------------------------------------

  ALTER TABLE "NONTEMSPASSTHROUGHCONFIG" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "NONTEMSPASSTHROUGHCONFIG" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "NONTEMSPASSTHROUGHCONFIG" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "NONTEMSPASSTHROUGHCONFIG" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "NONTEMSPASSTHROUGHCONFIG" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "NONTEMSPASSTHROUGHCONFIG" ADD CONSTRAINT "PK_NONTEMSPASSTHROUGHCONFIG" PRIMARY KEY ("NONTEMSPASSTHROUGHCONFIGID")
  USING INDEX "PK_NONTEMSPASSTHROUGHCONFIG"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NONTEMSPASSTHROUGHCONFIG
--------------------------------------------------------

  ALTER TABLE "NONTEMSPASSTHROUGHCONFIG" ADD CONSTRAINT "FK_NONTEMSPASSTHROUGHCONFIG_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "NONTEMSPASSTHROUGHCONFIG" ADD CONSTRAINT "FK_NONTEMSPASSTHROUGHCONFIG_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
