

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_MTX_2', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'al';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_A5SHQ', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'cz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5CA2_CMP_DATACENTER', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5CA2_VIM_DATACENTER', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5CA2_PIM_DATACENTER', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5CA1_PIM_DATACENTER', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5CA1_CMP_DATACENTER', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5CA1_VIM_DATACENTER', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'CAAS-LAB-DC01', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'gr';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITTC1DC00001', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITTC1DC00002', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_MATL', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_LAB', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'ro';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_MTX2', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'al';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_MTX1', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'al';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_SPE2', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'ce';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_PHJAZ', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'cz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_BMSCB', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'cz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_PZMSC', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'cz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BRLNCCA1_PIM_DATACENTER', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DTMD4CA1_PIM_DATACENTER', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH7CA1_PIM_DATACENTER', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BRLNCCA1_VIM_DATACENTER', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BRLNCCA1_CMP_DATACENTER', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DTMD4CA1_VIM_DATACENTER', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DTMD4CA1_CMP_DATACENTER', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH7CA1_VIM_DATACENTER', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH7CA1_CMP_DATACENTER', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'CAAS-KAL-DC01', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'gr';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'CAAS-MET-DC01', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'gr';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'CAAS-PAL-DC01', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'gr';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Aveiro.CaaS', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Alfragide.CaaS', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Boavista.CaaS', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC-PIPERA', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'ro';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_CLUJ', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'ro';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_DBC', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'ro';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_PIPERA', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'ro';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'UKXGLVVC02005-nvi', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'UKXGRVVC02005-nvi', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'UKBKNLVVC02005-NVI', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'UKXGLVVC02001-nvi', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'UKXGRVVC02001-nvi', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'UKXOMVVC02001-nvi', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'UKXOMVVC02005-nvi', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'UKBKNLVVC02001-NVI', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Alfragide.CSO', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Boavista.GSS', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Alfragide.MGMT', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Alfragide.ORACLE', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BoavistaOracle.CSO', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BoavistaMGMT.CSO', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'A5SHQ', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'cz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS3_vSphere_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS3_Management_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS3_vCloud_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS8_vCloud_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS8_vSphere_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS8_Management_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS3_Element_Manager_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS8_Element_Manager_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS2_vCloud_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS9_vCloud_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS2_vSphere_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS9_vSphere_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS2_Management_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS9_Management_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS2_Element_Manager_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS9_Element_Manager_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS4_vCloud_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS4_EMS_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS4_vSphere_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS4_SRIOV_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS4_VIM_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS4_Edge_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS4_PIM_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5_vCloud_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS4_VIC_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5_EMS_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5_VIM_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5_Edge_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5_vSphere_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS4VS2_PIM_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5VS2_PIM_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5_PIM_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS4VS2_EMS_DATACENTER', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS4VS2_VCD_DATACENTER', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS4VS2_VIM_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS4VS2_VSP_DATACENTER', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5VS2_EMS_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5VS2_VCD_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5VS2_VIM_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5VS2_VSP_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'TS5VS2_TST_DATACENTER', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'NVI-LAB-DC01', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'gr';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'NVI-LAB-DC02', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'gr';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITTC1BDC1001', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITTC1-DC01', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITTC1-DC02', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'SRVSTPNFV', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MGMTSTPNFV', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'NVI-PIP-DC01', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'ro';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MTX1', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'al';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MTX2', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'al';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'NVI-SPE2-DC01', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'ce';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'NVI-SPE7-DC01', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'ce';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'SPE2', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'ce';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'PZMSC', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'cz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'PHJAZ', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'cz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BMSCB', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'cz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'RN2_Management_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'RN2_Element_Manager_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'RN2_vCloud_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'RN2_vSphere_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'HAMM1_Management_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'HAMM1_Element_Manager_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'HAMM1_vCloud_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'LPZG1_Management_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'LPZG1_Element_Manager_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'LPZG1_vCloud_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'LPZG1_vSphere_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH4_Management_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH4_Element_Manager_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH4_vCloud_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'OFBH2_Management_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'OFBH2_Element_Manager_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'OFBH2_vCloud_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'RN2VB2_Management_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'RN2VB2_Element_Manager_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'RN2VB2_vSphere_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'RN2VB2_vCloud_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'HMBG6_Management_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'HMBG6_Element_Manager_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'HMBG6_vSphere_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'HMBG6_vCloud_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'RN2_AMP_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'RN2VB2_AMP_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'HAMM1_AMP_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'HMBG6_AMP_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'LPZG1_AMP_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH4_AMP_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'OFBH2_AMP_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'RN2VS1_VIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'RN2VS1_EMS_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BRLNC_vCloud_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'FKFT7_VIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'FKFT7_EMS_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'FKFT7_vCloud_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'FKFT7_vSphere_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'FKFT7_Edge_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'HNVR4_VIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'HNVR4_EMS_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'HNVR4_vCloud_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'LPZG1VS1_VIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'LPZG1VS1_EMS_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'LPZG1VS1_vCloud_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH7_VIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH7_vCloud_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH7_EMS_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH7_vSphere_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH7_Edge_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'RN2VS1_vCloud_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'RN2VS1_PIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'FKFT7_PIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'HNVR4_PIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'LPZG1VS1_PIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH7_PIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'RN2VS1_SRIOV_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BRLNC_SRIOV_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DTMD4_SRIOV_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'FKFT7_SRIOV_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'HNVR4_SRIOV_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'LPZG1VS1_SRIOV_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH7_SRIOV_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'STGT2_SRIOV_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BRLNC_Management_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BRLNC_Element_Manager_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BRLNC_Edge_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BRLNC_Infrastructure_Management_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BRLNC_vSphere_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DTMD4_VIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DTMD4_EMS_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DTMD4_vCloud_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DTMD4_vSphere_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'STGT2_VIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'STGT2_EMS_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'STGT2_vCloud_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DTMD4_Edge_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BRLNCVS2_PIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DTMD4_PIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DTMD4VS2_PIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'FKFT7VS2_PIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH7VS2_PIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BRLNC_vCloud-2_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'STGT2_PIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BRLNCVS2_VIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BRLNCVS2_VCD_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DTMD4VS2_VIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DTMD4VS2_VCD_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'FKFT7VS2_VIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'FKFT7VS2_VSP_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'FKFT7VS2_VCD_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH7VS2_VIM_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH7VS2_VCD_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BRLNCVS2_VSP_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BRLNCVS2_EMS_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DTMD4VS2_VSP_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DTMD4VS2_EMS_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'FKFT7VS2_EMS_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH7VS2_VSP_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MNCH7VS2_EMS_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'NVI-MET-DC01', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'gr';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'NVI-MET-DC02', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'gr';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'NVI-PAL-DC02', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'gr';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'NVI-PAL-DC01', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'gr';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'NVI-KAL-DC01', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'gr';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'NVI-KAL-DC02', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'gr';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'NVI-MET-DC03', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'gr';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'NVI-PAL-DC03', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'gr';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITBO2DC02001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITBO2BDC1000', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITMI5DC02001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITNA2DC02001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITRM3DC02001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITBO2BDC1001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITCZ2BDC1001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITMI5BDC1001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITNA2BDC1001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITPD1BDC1000', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITPI2BDC1001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITRM4BDC1001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITTO1BDC1001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITMI5DC01001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITRM3DC01001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITMI5DCAUDEP', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITRM3DCAUDEP', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITCT2DC02001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITRM4DC02001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITNA2BDC1000', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITBA1BDC1001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITCA1BDC1001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITMI5BDC1000', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITRM4BDC1000', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Boavista', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Alfragide', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MGMTAVENFV', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'SRVAVENFV', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Matinha', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'pt';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'NVI-CLU-DC01', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'ro';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'NVI-PIP-DC01', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'ro';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DBC', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'ro';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'XBE-SVC (Basingstoke)', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'XEH-SVC', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'XLD-SVC', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'XMS-SVC (Milton Keynes)', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'XGL-SVC', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'XGR-SVC', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'XOM-SVC', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BKNL-SVC', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'XBE-MGMT (Basingstoke)', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'XMS-MGMT (Milton Keynes)', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'uk';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'RM_C_Datacenter', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DLSFARM-MI3', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'GEA-Prod', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'FARM_E', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'GEA-Prod-Synergy', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITTC1-DCMAE01', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITTC1-MEC', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITMI5SFDC1001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITMI5SFDC1000', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITRM2SFDC1000', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITRM2SFDC1001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITMI5SFMAEDC001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITRM2SFMAEDC001', opcoid, 1, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ITTC1OCP', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC-PROD_Zone5', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC-PROD_Zone2', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DeviceProvisioning BPoP (Nutanix)', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Spectrum', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'VOP', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'WIFI-Core BPoP (HPE)', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'xCCM', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'f-brei-DTPLN-V2P', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'GigaTV-Prod', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'f-brei-REPLAY', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'f-brei-DTPLN-REPLAY160', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'm-medi-DTPLN-V2P', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'm-medi-GigaTV-OPS', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'f-brei-GigaTV-OPS', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BM-MICH_RES_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'BM-MICH_VIM_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'F-BREI_RES_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'F-BREI_VIM_Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'de';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'VELOCLOUD_PGW_MI3', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'VELOCLOUD_PGW_RM4', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Datacenter', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Datacenter_MI', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Datacenter_BG', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'INM-MI5', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Datacenter-VF-PROD-RM', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Datacenter-VF-PROD-MI', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Datacenter_CH13', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Roma-Torrespaccata', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'it-server-farm';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC-LKKP-Service', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'ls';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC-MSWP-Service', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'ls';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC-LKKP-Management', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'ls';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC-MSWP-Management', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'ls';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC-MSWT-Management', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'ls';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC-MSWT-Service', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'ls';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Vodacom Mozambique', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'mz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'Vodacom Business', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'mz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'ADC', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'mz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MDC', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'mz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_ADC', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'mz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_MDC', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'mz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_TES_MDC', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'mz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'DC_MDC_TES', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'mz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MBEZI', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'tz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MBEZI-Resource', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'tz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'KWALE', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'tz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'KWALE-Resource', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'tz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'KWALE-Management', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'tz';

insert into datacenter (DESCRIPTION,OPCOID,ENVIRONMENTZONE,CREATIONUSER,MODIFICATIONUSER)
 SELECT 'MBEZI-Management', opcoid, 0, 1, 1 FROM opcos WHERE LOWER(opco) = 'tz';
commit;