--------------------------------------------------------
--  DDL FOR TABLE TEMSFNTREPORT_SEQ
--------------------------------------------------------

CREATE SEQUENCE "TEMSFNTREPORT_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE TEMSFNTREPORT 
---------------------------------------


CREATE TABLE "TEMSFNTREPORT" 
(	"TEMSFNTREPORTID" NUMBER(19,0) DEFAULT "TEMSFNTREPORT_SEQ"."NEXTVAL", 
	"HOSTNAME" NVARCHAR2(250),
	"SERIALNUMBEROFHARDWAREASSET" NVARCHAR2(250),
	"LOCATIONOFHARDWAREASSET" NVARCHAR2(250),
	"HARDWARETYPEOFHARDWAREASSET" NVARCHAR2(250),
	"VENDOR" NVARCHAR2(250),
	"IPADDRESSOFHARDWAREASSET" NVARCHAR2(250),
	"MARKET" NVARCHAR2(250),
	"HWENDOFLIFE" NVARCHAR2(250),
	"HWENDOFSUPPORT" NVARCHAR2(250),
	"HWENDOFSALE" NVARCHAR2(250),
	"HARDWAREMODULES" NCLOB,
	"SOFTWAREPRODUCTTYPE" NVARCHAR2(250),
	"SOFTWAREPRODUCTVERSION" NVARCHAR2(250),
	"SOFTWAREISVIRTUALIZED" NVARCHAR2(250),
	"OPERATING SYSTEMOFVIRTUALMACHINE" NVARCHAR2(250),
	"APPLICATIONHOSTEDONSOFTWARE" NVARCHAR2(250),
	"UUIDSERIALNUMBEROFSOFTWARE." NVARCHAR2(250),
	"SOFTWAREVENDOR" NVARCHAR2(250),
	"LOCATIONOFSOFTWARE" NVARCHAR2(250),
	"SERVICETYPE" NVARCHAR2(250),
	"SWENDOFLIFE" NVARCHAR2(250),
	"SWENDOFSUPPORT" NVARCHAR2(250),
	"SWENDOFSALE" NVARCHAR2(250),
	"VERTICALENGINEERINGTEAM" NVARCHAR2(250),
	"VERTICALSUBDOMAIN" NVARCHAR2(250),
	"PLATFORM" NVARCHAR2(250),
	"RISKCLUSTER" NVARCHAR2(250),
	"OPERATIONSCONTACTPOINT" NVARCHAR2(250),
	"ASSETCATEGORY" NVARCHAR2(250),
	"ASSETCLASS" NVARCHAR2(250),
	"ASSETTYPE" NVARCHAR2(250),
	"ASSETDESCRIPTION" NVARCHAR2(250),
	"PRODUCTIMPORTANCE" NVARCHAR2(250),
	"OPERATIONSMAINTENANCECONTRACT" NVARCHAR2(250),
	"VENDORENDOFMAINTENANCEDATE" NVARCHAR2(250),
	"IDENTIFIEDACTION" NVARCHAR2(250),
	"DESCRIPTIONOFPLANNEDACTION" NVARCHAR2(250),
	"MODEL" NCLOB,
	"BUSINESSSERVICENAME" NVARCHAR2(250),
	"OPMAINTENANCECONTRACTENDDATE" NVARCHAR2(250),
	"INCIDENTCLASS" NVARCHAR2(250),
	"OCCURRENCEPROBABILITY" NVARCHAR2(250),
	"MEVERTICALRESPOSIBLE" NVARCHAR2(250),
	"ASSETSTATUS" NVARCHAR2(250),
	"TYPEOFNETWORKELEMENT" NVARCHAR2(250),
	"LOCALMARKET" NVARCHAR2(250),
	"APPLICATION" NVARCHAR2(250),
	"CLOUD" NVARCHAR2(250),
	"PHYSICALSERVERHOSTNAME" NVARCHAR2(250),
	"PHYSICALSERVERIPADDRESS" NVARCHAR2(250),
	"PHYSICALSERVERSERIALNUMBER" NVARCHAR2(250),
	"PHYSICALSERVERHWMODEL" NVARCHAR2(250),
	"PHYSICALSERVERVENDOR" NVARCHAR2(250),
	"VIRTUALSERVERHOSTEDON" NVARCHAR2(250),
	"VIRTUALSERVERMANUFACTURER" NVARCHAR2(250),
	"VIRTUALSERVERTYPEOFDEVICE" NVARCHAR2(250),
	"VIRTUALMACHINETYPE" NVARCHAR2(250),
	"VIRTUALSERVERIPADDRESS" NVARCHAR2(250),
	"VIRTUALSERVERSERIALNUMBER" NVARCHAR2(250),
	"VIRTUALSERVERTYPE" NVARCHAR2(250),
	"OSNAME" NVARCHAR2(250),
	"OSVERSION" NVARCHAR2(250),
	"OSSTARTDATE" NVARCHAR2(250),
	"OSINSTALLATIONDATE" NVARCHAR2(250),
	"OSSTATUS" NVARCHAR2(250),
	"SOFTWARENAME" NVARCHAR2(250),
	"VERSION" NVARCHAR2(250),
	"RELEASE" NVARCHAR2(250),
	"MANUFACTURER" NVARCHAR2(250),
	"LANGUAGE" NVARCHAR2(250),
	"HWOPSCONTRACTSTATUS" NVARCHAR2(250),
	"HWOPSCONTRACTENDDATE" NVARCHAR2(250),
	"SWOPSCONTRACTSTATUS" NVARCHAR2(250),
	"SWOPSCONTRACTENDDATE" NVARCHAR2(250),
	"HWOPERATIONSCONTACTPOINT" NVARCHAR2(250),
	"SWOPERATIONSCONTACTPOINT" NVARCHAR2(250),
	"PHYSICALSERVEROSNAME" NVARCHAR2(250),
	"PHYSICALSERVEROSVERSION" NVARCHAR2(250),
	"PHYSICALSERVEROSSTARTDATE" NVARCHAR2(250),
	"PHYSICALSERVEROSINSTALLATIONDATE" NVARCHAR2(250),
	"PHYSICALSERVEROSSTATUS" NVARCHAR2(250),
	"PLANNEDHWMODEL" NVARCHAR2(250),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
  
  --------------------------------------------------------
--  DDL FOR INDEX PK_TEMSFNTREPORT
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_TEMSFNTREPORT" ON "TEMSFNTREPORT" ("TEMSFNTREPORTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE TEMSFNTREPORT
--------------------------------------------------------
 
  ALTER TABLE "TEMSFNTREPORT" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "TEMSFNTREPORT" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "TEMSFNTREPORT" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "TEMSFNTREPORT" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "TEMSFNTREPORT" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "TEMSFNTREPORT" ADD CONSTRAINT "PK_TEMSFNTREPORT" PRIMARY KEY ("TEMSFNTREPORTID") USING INDEX "PK_TEMSFNTREPORT"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE TEMSFNTREPORT
--------------------------------------------------------

  ALTER TABLE "TEMSFNTREPORT" ADD CONSTRAINT "FK_TEMSFNTREPORT_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "TEMSFNTREPORT" ADD CONSTRAINT "FK_TEMSFNTREPORT_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  COMMIT;