DROP SEQUENCE PLANNEDACTIVITYTYPESID_SEQ;

CREATE SEQUENCE  "PLANNEDACTIVITYTYPESID_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999 
INCREMENT BY 1 START WITH  20 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT" ) 
VALUES ('Decommision Node', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,0,0,1);
COMMIT;

update plannedactivityresources set rulelinkeddc = 20 where PLANNEDACTIVITYRESOURCE = 'Decommission Node';
commit;