CREATE SEQUENCE LCMDEPLOYMENTSTATUS_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  COMMIT



--------------------------------------------------------
--  DDL for Table LCMDEPLOYMENTSTATUS
--------------------------------------------------------

  --------------------------------------------------------
--  DDL for Table LCMDEPLOYMENTSTATUS
--------------------------------------------------------

  CREATE TABLE "LCMDEPLOYMENTSTATUS" 
   (	"ID" NUMBER(5,0) DEFAULT "LCMDEPLOYMENTSTATUS_SEQ"."NEXTVAL", 
	"CREATIONUSER" NUMBER(10,0) DEFAULT (null), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT (null), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6) DEFAULT (null), 
	"DESCRIPTION" NVARCHAR2(2000) DEFAULT (null)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index LCMDEPLOYMENTSTATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LCMDEPLOYMENTSTATUS_PK" ON "LCMDEPLOYMENTSTATUS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table LCMDEPLOYMENTSTATUS
--------------------------------------------------------

  ALTER TABLE "LCMDEPLOYMENTSTATUS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LCMDEPLOYMENTSTATUS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "LCMDEPLOYMENTSTATUS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "LCMDEPLOYMENTSTATUS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "LCMDEPLOYMENTSTATUS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "LCMDEPLOYMENTSTATUS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "LCMDEPLOYMENTSTATUS" ADD CONSTRAINT "LCMDEPLOYMENTSTATUS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;
  ALTER TABLE "LCMDEPLOYMENTSTATUS" MODIFY ("DELETED" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LCMDEPLOYMENTSTATUS
--------------------------------------------------------

  ALTER TABLE "LCMDEPLOYMENTSTATUS" ADD CONSTRAINT "FK_LCMDEPLOYMENTSTATUS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "LCMDEPLOYMENTSTATUS" ADD CONSTRAINT "FK_LCMDEPLOYMENTSTATUS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;


  
ALTER TABLE LCMDEPLOYMENTSTATUS
MODIFY(ID  DEFAULT "LCMDEPLOYMENTSTATUS_SEQ"."NEXTVAL");

  --/inserting the values

  -- ****** Replace 177 with admin Id
INSERT INTO LCMDEPLOYMENTSTATUS (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER  ) VALUES ('Planned',177,177);
INSERT INTO LCMDEPLOYMENTSTATUS (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER  ) VALUES ('Commissioning',177,177);
INSERT INTO LCMDEPLOYMENTSTATUS (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER  ) VALUES ('Decommissioning',177,177);
INSERT INTO LCMDEPLOYMENTSTATUS (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER  ) VALUES ('In-Service',177,177);
INSERT INTO LCMDEPLOYMENTSTATUS (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER  ) VALUES ('Removed',177,177);
commit;
