
ALTER TABLE LCMENGINEERING
	ADD "LCMDEPLOYMENTSTATUSID" NUMBER(5,0);


ALTER TABLE "LCMENGINEERING" ADD CONSTRAINT "FK_LCMENGINEERING_LCMDEPLOYMENTSTATUS_LCMDEPLOYMENTSTATUSID" FOREIGN KEY ("LCMDEPLOYMENTSTATUSID")
	REFERENCES "LCMDEPLOYMENTSTATUS" ("ID") ENABLE;