ALTER TABLE SETTINGSUPDATEPLANNEDACTIVITY
	ADD PLANNEDACTIVITYRESOURCEID NUMBER(5,0);


ALTER TABLE "SETTINGSUPDATEPLANNEDACTIVITY" ADD CONSTRAINT "FK_SETTINGSUPDATEPLANNEDACTIVITY_PLANNEDACTIVITYRESOURCES_PLANNEDACTIVITYRESOURCEID" FOREIGN KEY ("PLANNEDACTIVITYRESOURCEID")
	REFERENCES "PLANNEDACTIVITYRESOURCES" ("PLANNEDACTIVITYRESOURCEID") ENABLE;
