ALTER TABLE SETTINGSUPDATEPLANNEDACTIVITY
	ADD SUCCESSORPLANNEDACTIVITYRESOURCEID NUMBER(5,0);


ALTER TABLE "SETTINGSUPDATEPLANNEDACTIVITY" ADD CONSTRAINT "FK_SETTINGSUPDATEPLANNEDACTIVITY_PLANNEDACTIVITYRESOURCES_SUCCESSORPLANNEDACTIVITYRESOURCEID" FOREIGN KEY ("SUCCESSORPLANNEDACTIVITYRESOURCEID")
	REFERENCES "PLANNEDACTIVITYRESOURCES" ("PLANNEDACTIVITYRESOURCEID") ENABLE;

