CREATE SEQUENCE SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  COMMIT




--------------------------------------------------------
--  DDL for Table SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS
--------------------------------------------------------

  CREATE TABLE "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS" 
   (	"ID" NUMBER(5,0) DEFAULT "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS_SEQ"."NEXTVAL", 
	"SETTINGUPDATEPLANNEDACTIVITYID" NUMBER(5,0) DEFAULT (null), 
	"ASSETDEPLOYMENTSTATUSID" NUMBER(5,0) DEFAULT (null), 
	"CREATIONUSER" NUMBER(10,0) DEFAULT (null), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT (null), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6) DEFAULT (null)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS_PK" ON "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS
--------------------------------------------------------


  ALTER TABLE "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS" MODIFY ("SETTINGUPDATEPLANNEDACTIVITYID" NOT NULL ENABLE);
  ALTER TABLE "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS" MODIFY ("ASSETDEPLOYMENTSTATUSID" NOT NULL ENABLE);
  ALTER TABLE "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS" ADD CONSTRAINT "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;
  ALTER TABLE "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS
--------------------------------------------------------

  ALTER TABLE "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS" ADD CONSTRAINT "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS_SETTINGSUPDATEPLANNEDACTIVITY" FOREIGN KEY ("SETTINGUPDATEPLANNEDACTIVITYID")
	  REFERENCES "SETTINGSUPDATEPLANNEDACTIVITY" ("SETTINGSUPDATEPLNACTID") ENABLE;
  ALTER TABLE "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS" ADD CONSTRAINT "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS_ASSETDEPLOYMENTSTATUS" FOREIGN KEY ("ASSETDEPLOYMENTSTATUSID")
	  REFERENCES "DEPLOYMENTSTATUSES" ("DEPLOYMENTSTATUSID") ENABLE;
  ALTER TABLE "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS" ADD CONSTRAINT "FK_SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS" ADD CONSTRAINT "FK_SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;

  ALTER TABLE SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS
  MODIFY(ID  DEFAULT "SETTINGUPDATEPLANNEDACTIVITYASSETDEPLOYMENTSTATUS_SEQ"."NEXTVAL");