<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="6.2.8" />
	  <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="2.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CAM.BusinessManager\CAM.BusinessManager.csproj" />
    <ProjectReference Include="..\CAM.DataTransferObjects\CAM.DataTransferObjects.csproj" />
  </ItemGroup>

</Project>
