--------------------------------------------------------
--  RB Script for  MAJORHARDWAREBUILDASIS 
--------------------------------------------------------


DROP SEQUENCE  "MAJORHARDWAREBUILDASIS_SQE";
DROP TABLE "MAJORHARDWAREBUILDASIS";


ALTER TABLE ASSETHARDWAREANCILLARY ADD   MAJORHARDWAREID  NUMBER(19,0);
ALTER TABLE ASSETHARDWAREANCILLARY ADD CONSTRAINT "FK_ASSETHARDWAREANCILLARY_MAJORHARDWAREBUILDS_MAJORHARDWAREID" FOREIGN KEY ("MAJORHARDWAREID")
REFERENCES "MAJORHARDWAREBUILDS" ("MAJORHARDWAREID") ENABLE;
	  


MERGE INTO ASSETHARDWAREANCILLARY AC
USING (
SELECT x.majorhardwareid,
bk.MAJORHARDWAREID , bk.ASSETHARDWAREANCILLARYID
FROM   assethardwareancillary x
join assethardwareancillaryMajorHwID_backup bk  on bk.ASSETHARDWAREANCILLARYID = x.ASSETHARDWAREANCILLARYID 
) SRC
ON (AC.ASSETHARDWAREANCILLARYID = SRC.ASSETHARDWAREANCILLARYID)
WHEN MATCHED THEN
UPDATE SET AC.MAJORHARDWAREID = SRC.MAJORHARDWAREID;
COMMIT;

	  
	  
ALTER TABLE ASSETHARDWAREANCILLARY DROP COLUMN  MAJORHARDWAREBUILDASISID  ;
