DROP SEQUENCE "ASSETMAPINFO_SEQ";
DROP TABLE "ASSETMAPINFO";

DROP SEQUENCE "ASSETASISSDIINFO_SEQ";
DROP TABLE "ASSETASISSDIINFO";

DROP SEQUENCE "ASSETASISHWANCILLARYDATA_SEQ";
DROP TABLE "ASSETASISHWANCILLARYDATA";

DROP SEQUENCE "ASSETASISSDISWITCHINFO_SEQ";
DROP TABLE "ASSETASISSDISWITCHINFO";