 
DROP SEQUENCE ASPNETUSERROLEPERMISSIONS_SEQ;
DROP TABLE ASPNETUSERROLEPERMISSIONS;

DROP SEQUENCE ASPNETMODULES_SEQ;
DROP TABLE ASPNETMODULES;
 
ALTER TABLE GRIDCUSTOMCOLUMN DROP COLUMN  ACHIEVEMENTDATE ; 
ALTER TABLE GRIDCUSTOMCOLUMN DROP COLUMN   SIGNPOSTDATE  ; 
ALTER TABLE ORGANISATION DROP COLUMN    ISDESIGNCONTACT  ; 

COMMIT; 