 
--------------------------------------------------------
--  DDL FOR SEQUENCE DAASSETMIGRATION_SQE
--------------------------------------------------------

CREATE SEQUENCE "DAASSETMIGRATION_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE DAASSETMIGRATION
--------------------------------------------------------
CREATE TABLE DAASSETMIGRATION 
   (	
    DAASSETMIGRATIONID NUMBER(19,0) DEFAULT DAASSETMIGRATION_SQE.NEXTVAL  NOT NULL, 
	PLANNEDACTIVITYID NUMBER(19,0) NOT NULL,
	NETWORKELEMENTASPLANNEDID NUMBER(19) NOT NULL,
	NEWELEMENTNAME NVARCHAR2(2000) ,
	TARGETDESIGNCOMPONENETID NUMBER(19),
	ENVIRONMENTID      NUMBER(5)  ,     
	DEPLOYMENTSTATUSID NUMBER(5) ,      
	--DEPLOYMENTTYPEID    NUMBER(5) ,
	OPCOID NUMBER(5,0) NOT NULL,
	LOCATIONID NUMBER(5,0) NOT NULL,
	RFODATE TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	RFSDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MIGRATIONCOMPLETIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	TRAFFICNODEPERCENTAGE   NVARCHAR2(20) ,
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_DAASSETMIGRATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_DAASSETMIGRATION" ON DAASSETMIGRATION ("DAASSETMIGRATIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
 --------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE DAASSETMIGRATION MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE DAASSETMIGRATION MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE DAASSETMIGRATION MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE DAASSETMIGRATION MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE DAASSETMIGRATION ADD CONSTRAINT "PK_DAASSETMIGRATION" PRIMARY KEY ("DAASSETMIGRATIONID") ;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE DAASSETMIGRATION ADD CONSTRAINT "FK_DAASSETMIGRATION_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE DAASSETMIGRATION ADD CONSTRAINT "FK_DAASSETMIGRATION_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE; 

 ALTER TABLE DAASSETMIGRATION ADD CONSTRAINT "FK_DAASSETMIGRATION_NETWORKELEMENTSASPLANNED_NETWORKELEMENTASPLANNEDID" FOREIGN KEY ("NETWORKELEMENTASPLANNEDID")
	  REFERENCES "NETWORKELEMENTSASPLANNED" ("NETWORKELEMENTASPLANNEDID") ENABLE; 	

ALTER TABLE DAASSETMIGRATION ADD CONSTRAINT "FK_DAASSETMIGRATION_DESIGNCOMPONENTS_TARGETDESIGNCOMPONENETID" FOREIGN KEY ("TARGETDESIGNCOMPONENETID")
	  REFERENCES "DESIGNCOMPONENTS" ("DESIGNCOMPONENTID") ENABLE; 	
	  
	  	
ALTER TABLE DAASSETMIGRATION ADD CONSTRAINT "FK_DAASSETMIGRATION_OPCOS_OPCOID" FOREIGN KEY ("OPCOID")
	  REFERENCES "OPCOS" ("OPCOID") ENABLE;
ALTER TABLE DAASSETMIGRATION ADD CONSTRAINT "FK_DAASSETMIGRATION_LOCATIONS_LOCATIONID" FOREIGN KEY ("LOCATIONID")
	  REFERENCES "LOCATIONS" ("LOCATIONID") ENABLE;	 

ALTER TABLE DAASSETMIGRATION ADD CONSTRAINT "FK_DAASSETMIGRATION_PLANNEDACTIVITIES_PLANNEDACTIVITYID" FOREIGN KEY ("PLANNEDACTIVITYID")
	  REFERENCES "PLANNEDACTIVITIES" ("PLANNEDACTIVITYID") ENABLE; 	


 ALTER TABLE DAASSETMIGRATION ADD CONSTRAINT "FK_DAASSETMIGRATION_ENVIRONMENTS_ENVIRONMENTID" FOREIGN KEY ("ENVIRONMENTID")
	  REFERENCES "ENVIRONMENTS" ("ENVIRONMENTID") ENABLE; 

 ALTER TABLE DAASSETMIGRATION ADD CONSTRAINT "FK_DAASSETMIGRATION_DEPLOYMENTSTATUSES_DEPLOYMENTSTATUSID" FOREIGN KEY ("DEPLOYMENTSTATUSID")
	  REFERENCES "DEPLOYMENTSTATUSES" ("DEPLOYMENTSTATUSID") ENABLE; 


ALTER TABLE DAASSETMIGRATION modify   LOCATIONID NUMBER(5,0)  NULL;


 --ALTER TABLE DAASSETMIGRATION ADD CONSTRAINT "FK_DAASSETMIGRATION_DEPLOYMENTTYPES_DEPLOYMENTTYPEID" FOREIGN KEY ("DEPLOYMENTTYPEID")  REFERENCES "DEPLOYMENTTYPES" ("DEPLOYMENTTYPEID") ENABLE; 
-------------------------------------------------	  
-------------------------------------------------	  


--------------------------------------------------------
--  DDL FOR SEQUENCE VNFHARDWARE_SQE
--------------------------------------------------------

CREATE SEQUENCE "VNFHARDWARE_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE VNFHARDWARE
--------------------------------------------------------

CREATE TABLE VNFHARDWARE 
   (	
    VNFHARDWAREID NUMBER(19,0) DEFAULT VNFHARDWARE_SQE.NEXTVAL  NOT NULL, 
	DESCRIPTION NVARCHAR2(50)  NOT NULL, 	 
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_VNFHARDWARE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_VNFHARDWARE" ON VNFHARDWARE ("VNFHARDWAREID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE VNFHARDWARE MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE VNFHARDWARE MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE VNFHARDWARE MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE VNFHARDWARE MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE VNFHARDWARE ADD CONSTRAINT "PK_VNFHARDWARE" PRIMARY KEY ("VNFHARDWAREID")
  USING INDEX "PK_VNFHARDWARE"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE VNFHARDWARE ADD CONSTRAINT "FK_VNFHARDWARE_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE VNFHARDWARE ADD CONSTRAINT "FK_VNFHARDWARE_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
 
COMMIT;
