CREATE TABLE CNFINFO_BACKUP AS SELECT * FROM CNFINFO;
CREATE TABLE CNFCLUSTERINFO_BACKUP AS SELECT * FROM CNFCLUSTERINFO;
CREATE TABLE CNFCAPACITY_BACKUP AS SELECT * FROM CNFCAPACITY;

DROP SEQUENCE CNFINFO_SQE;
DROP TABLE CNFINFO_BACKUP  CASCADE CONSTRAINTS PURGE ;

DROP SEQUENCE CNFCLUSTERINFO_SQE;
DROP TABLE CNFCLUSTERINFO CASCADE CONSTRAINTS PURGE ;

DROP SEQUENCE CNFCAPACITY_SQE;
DROP TABLE CNFCAPACITY CASCADE CONSTRAINTS PURGE ;

-- NEW COLUMN IN  CNFCLUSTER
delete from CNFCLUSTER;
commit;
ALTER TABLE CNFCLUSTER ADD ALAISNAME NVARCHAR2(100)  NOT NULL;

------------------ CNF HARDWARE 

--------------------------------------------------------
--  DDL FOR SEQUENCE CNFHARDWARE_SQE
--------------------------------------------------------

CREATE SEQUENCE "CNFHARDWARE_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE CNFHARDWARE
--------------------------------------------------------

CREATE TABLE CNFHARDWARE 
   (	
    CNFHARDWAREID NUMBER(19,0) DEFAULT CNFHARDWARE_SQE.NEXTVAL  NOT NULL, 
	DESCRIPTION NVARCHAR2(50)  NOT NULL, 	 
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_CNFHARDWARE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CNFHARDWARE" ON CNFHARDWARE ("CNFHARDWAREID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE CNFHARDWARE MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE CNFHARDWARE MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE CNFHARDWARE MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE CNFHARDWARE MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE CNFHARDWARE ADD CONSTRAINT "PK_CNFHARDWARE" PRIMARY KEY ("CNFHARDWAREID")
  USING INDEX "PK_CNFHARDWARE"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE CNFHARDWARE ADD CONSTRAINT "FK_CNFHARDWARE_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE CNFHARDWARE ADD CONSTRAINT "FK_CNFHARDWARE_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
 
COMMIT;


------------------ CNF Priority

--------------------------------------------------------
--  DDL FOR SEQUENCE CNFPRIORITY_SQE
--------------------------------------------------------

   CREATE SEQUENCE "CNFPRIORITY_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE CNFPRIORITY
--------------------------------------------------------

  CREATE TABLE CNFPRIORITY 
   (	
    CNFPRIORITYID NUMBER(19,0) DEFAULT CNFPRIORITY_SQE.NEXTVAL  NOT NULL, 
	DESCRIPTION NVARCHAR2(50)  NOT NULL, 	 
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_CNFPRIORITY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CNFPRIORITY" ON CNFPRIORITY ("CNFPRIORITYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE CNFPRIORITY MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE CNFPRIORITY MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE CNFPRIORITY MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE CNFPRIORITY MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE CNFPRIORITY ADD CONSTRAINT "PK_CNFPRIORITY" PRIMARY KEY ("CNFPRIORITYID")
  USING INDEX "PK_CNFPRIORITY"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE CNFPRIORITY ADD CONSTRAINT "FK_CNFPRIORITY_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE CNFPRIORITY ADD CONSTRAINT "FK_CNFPRIORITY_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
 
COMMIT;

-------------------- CNF CLUSTER INFO

	  	  
------------------------------------------- CNFINFO

--------------------------------------------------------
--  DDL FOR SEQUENCE CNFCLUSTERINFO_SQE
--------------------------------------------------------

   CREATE SEQUENCE "CNFCLUSTERINFO_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE CNFCLUSTERINFO
--------------------------------------------------------

  CREATE TABLE CNFCLUSTERINFO 
   (	
    CNFCLUSTERINFOID NUMBER(19,0) DEFAULT CNFCLUSTERINFO_SQE.NEXTVAL  NOT NULL, 	
	CNFNAMEID NUMBER(19,0)  NOT NULL, 
	CNFCLUSTERID NUMBER(19,0)  NOT NULL,
	OPCOID NUMBER(5,0)  NOT NULL,
	SITEID NUMBER(5,0)  NOT NULL,
	CNFHARDWAREID NUMBER(19,0)  NOT NULL,	
	NODEPOOLBREAKUP NUMBER(1) DEFAULT 0 NOT NULL , 
	SPECIALREQUIREMENTS NVARCHAR2(100)  NOT NULL, 
	HYPERTHREADING NVARCHAR2(100)  NOT NULL, 
	OVERPROVISIONING NVARCHAR2(100)  NOT NULL, 
	WORKERNODECONFIGURATION NVARCHAR2(100)  NOT NULL, 
	HARDWARE NVARCHAR2(100)  NOT NULL, 
	CPUKUBELET NUMBER(20,2) DEFAULT 0.5 NOT NULL , 
	MEMKUBELET NUMBER(10) DEFAULT 2 NOT NULL , 
	CPUSYSTEM NUMBER(20,2) DEFAULT 0.5 NOT NULL , 
	MEMSYSTEM NUMBER(10)  DEFAULT 2 NOT NULL, 
	VERTICALRESPONSIBLEID  NUMBER(10) NOT NULL, 
	COMMENTS NVARCHAR2(500) ,
	NOTES NVARCHAR2(500), 
	FILENAME NVARCHAR2(200) NOT NULL,
	REVISION NVARCHAR2(10) NOT NULL, 
	AGGREGATEIMAGECLUSTERSIZE NVARCHAR2(20) NOT NULL ,
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_CNFCLUSTERINFO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CNFCLUSTERINFO" ON CNFCLUSTERINFO ("CNFCLUSTERINFOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE CNFCLUSTERINFO MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE CNFCLUSTERINFO MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE CNFCLUSTERINFO MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE CNFCLUSTERINFO MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "PK_CNFCLUSTERINFO" PRIMARY KEY ("CNFCLUSTERINFOID")
  USING INDEX "PK_CNFCLUSTERINFO"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
 ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_CNFNAME_CNFNAMEID" FOREIGN KEY ("CNFNAMEID")
	  REFERENCES "CNFNAME" ("CNFNAMEID") ENABLE;
	
ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_OPCOS_OPCOID" FOREIGN KEY ("OPCOID")
	  REFERENCES "OPCOS" ("OPCOID") ENABLE;
ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_LOCATIONS_CNFNAMEID" FOREIGN KEY ("SITEID")
	  REFERENCES "LOCATIONS" ("LOCATIONID") ENABLE;	  
 ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_CNFCLUSTER_CNFCLUSTERID" FOREIGN KEY ("CNFCLUSTERID")
	  REFERENCES "CNFCLUSTER" ("CNFCLUSTERID") ENABLE;	

 ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_CNFHARDWARE_CNFHARDWAREID" FOREIGN KEY ("CNFHARDWAREID")
	  REFERENCES "CNFHARDWARE" ("CNFHARDWAREID") ENABLE;	
 ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_VERTICALRESPONSIBLES_VERTICALRESPONSIBLEID" FOREIGN KEY ("VERTICALRESPONSIBLEID")
	  REFERENCES "VERTICALRESPONSIBLES" ("VERTICALRESPONSIBLEID") ENABLE;		  
-------------------------------------------------	  
	
--------------------------------------------------------
--  DDL FOR SEQUENCE CNFPODINFO_SQE
--------------------------------------------------------

   CREATE SEQUENCE "CNFPODINFO_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE CNFPODINFO
--------------------------------------------------------
 
  CREATE TABLE CNFPODINFO 
   (	
    CNFPODINFOID NUMBER(19,0) DEFAULT CNFPODINFO_SQE.NEXTVAL  NOT NULL, 
	CNFCLUSTERINFOID NUMBER(19,0) NOT NULL,  
	PODTYPEINFOID NUMBER(19,0)  NOT NULL, 	
	FUNCTIONSTANDARDID NUMBER (19,0)  NOT NULL, 
	PRIORITYID NUMBER (19,0)  NOT NULL, 	
   
	DAEMONSETPOD NUMBER(1) , 
	INTRAPODRULES NVARCHAR2(10) , 
	INTERPODRULES  NVARCHAR2(10) , 
	ISENHANCEDHA NUMBER(1) , 
	PODTYPEQOS NVARCHAR2(50) , 
	ISPERSISTANCESTORAGEFLAG  NVARCHAR2(20) , 
	ISPRODHPAENABLE  NUMBER(1) ,  
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_CNFPODINFO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CNFPODINFO" ON CNFPODINFO ("CNFPODINFOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE CNFPODINFO MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE CNFPODINFO MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE CNFPODINFO MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE CNFPODINFO MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE CNFPODINFO ADD CONSTRAINT "PK_CNFPODINFO" PRIMARY KEY ("CNFPODINFOID")
  USING INDEX "PK_CNFPODINFO"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE CNFPODINFO ADD CONSTRAINT "FK_CNFPODINFO_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE CNFPODINFO ADD CONSTRAINT "FK_CNFPODINFO_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
   
ALTER TABLE CNFPODINFO ADD CONSTRAINT "FK_CNFPODINFO_PODTYPEINFO_PODTYPEINFOID" FOREIGN KEY ("PODTYPEINFOID")
	  REFERENCES "PODTYPEINFO" ("PODTYPEINFOID") ENABLE;
	  
--ALTER TABLE CNFPODINFO ADD CONSTRAINT "FK_CNFPODINFO_PODTYPEINFO_PODROLEDESCRIPTIONID" FOREIGN KEY ("PODROLEDESCRIPTIONID")
	  --REFERENCES "PODTYPEINFO" ("PODTYPEINFOID") ENABLE;	
	  
ALTER TABLE CNFPODINFO ADD CONSTRAINT "FK_CNFPODINFO_FUNCTIONSTANDARDNAME_FUNCTIONSTANDARDID" FOREIGN KEY ("FUNCTIONSTANDARDID")
	  REFERENCES "FUNCTIONSTANDARDNAME" ("FUNCTIONSTANDARDNAMEID") ENABLE;	

 ALTER TABLE CNFPODINFO ADD CONSTRAINT "FK_CNFPODINFO_CNFCLUSTERINFO_CNFCLUSTERINFOID" FOREIGN KEY ("CNFCLUSTERINFOID")
	  REFERENCES "CNFCLUSTERINFO" ("CNFCLUSTERINFOID") ENABLE;	
	  
	 ALTER TABLE CNFPODINFO ADD CONSTRAINT "FK_CNFPODINFO_CNFPRIORITY_PRIORITYID" FOREIGN KEY ("PRIORITYID")
	  REFERENCES "CNFPRIORITY" ("CNFPRIORITYID") ENABLE;	
	  
---------------------------------

--------------------------------------------------------
--  DDL FOR SEQUENCE CNFCAPACITY_SQE
--------------------------------------------------------

CREATE SEQUENCE "CNFCAPACITY_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE CNFCAPACITY
--------------------------------------------------------

CREATE TABLE CNFCAPACITY 
   (	
    CNFCAPACITYID NUMBER(19,0) DEFAULT CNFCAPACITY_SQE.NEXTVAL  NOT NULL, 
	CNFPODINFOID NUMBER(19,0)  NOT NULL, 	
	FINANCIALYEAR  NUMBER(5) NOT NULL,  
	FINANCIALVERSION  NUMBER(8) NOT NULL,   
	VCPUREQUESTFORPODTYPE NUMBER(19), 
	VCPULIMITFORPODTYPE NUMBER(19),  
	PCPUREQUESTFORPODTYPE NUMBER(19),  	
	MEMREQUESTFORPODTYPE NUMBER(19,5), 
	MEMLIMITFORPODTYPE NUMBER(19,5) , 	
	NONPRESISTENTSTORAGEFORPRODTYPE NVARCHAR2(200) , 
	ISPRESISTENTVOLUMESREQUIRED	 NUMBER(1),  
	PERSISTENTVOLUMNEACCESSMODE  NVARCHAR2(200) , 	
	PERSISTENTSTORAGEFORPODTYPE	 NVARCHAR2(200) , 	
	STORAGEIOPSFORPODTYPE NVARCHAR2(200) ,  
	STORAGERWORKLOADDISTRIBUTION NVARCHAR2(200) , 
	NORTHSOUTHBANDWIDTHFORPODTYPE NVARCHAR2(200) , 	
	EASTWESTBANDWIDTHFORPODTYPE	NVARCHAR2(50) , 
	SPECIALREQUIREMENTPERPODTYPE NVARCHAR2(50) , 	
	CAPACITYSPECIALREQUIREMENT 	NVARCHAR2(250) ,  	
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_CNFCAPACITY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CNFCAPACITY" ON CNFCAPACITY ("CNFCAPACITYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE CNFCAPACITY MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE CNFCAPACITY MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE CNFCAPACITY MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE CNFCAPACITY MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE CNFCAPACITY ADD CONSTRAINT "PK_CNFCAPACITY" PRIMARY KEY ("CNFCAPACITYID")
  USING INDEX "PK_CNFCAPACITY"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE CNFCAPACITY ADD CONSTRAINT "FK_CNFCAPACITY_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE CNFCAPACITY ADD CONSTRAINT "FK_CNFCAPACITY_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE CNFCAPACITY ADD CONSTRAINT "FK_CNFCAPACITY_CNFPODINFO_CNFPODINFOID" FOREIGN KEY ("CNFPODINFOID")
	  REFERENCES "CNFPODINFO" ("CNFPODINFOID") ENABLE;	 	     	
	  
 
ALTER TABLE CNFCAPACITY ADD   NOOFCNFINSTANCESPERSITE  NUMBER(10);
ALTER TABLE CNFCAPACITY ADD   NUMBEROFPODSPERPODTYPE  NUMBER(10);
 
 