-----------------------Cnf Hardware  Table
TRUNCATE TABLE cnfcapacity;
TRUNCATE TABLE cnfpodinfo;
TRUNCATE TABLE cnfclusterinfo;

TRUNCATE TABLE cnfpodinfo;
TRUNCATE TABLE CNFHARDWARE;
TRUNCATE TABLE CNFCLUSTER;
TRUNCATE TABLE cnfname;
TRUNCATE TABLE podtypeinfo;

Commit;
insert into cnfhardware (DESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'Cascadelake',1,1); 
Commit;
 

insert into verticalresponsibles (VERTICALRESPONSIBLE, CREATIONUSER, MODIFICATIONUSER) values  ( 'VINO',1,1); 
insert into verticalresponsibles (VERTICALRESPONSIBLE, CREATIONUSER, MODIFICATIONUSER) values  ( 'SDD',1,1); 
insert into verticalresponsibles (VERTICALRESPONSIBLE, CREATIONUSER, MODIFICATIONUSER) values  ( 'Voice Core',1,1); 
insert into verticalresponsibles (VERTICALRESPONSIBLE, CREATIONUSER, MODIFICATIONUSER) values  ( 'Other',1,1); 
Commit;

------------------------------ Priority 
insert into cnfpriority (DESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'preemptive-high-priority','1','1');
insert into cnfpriority (DESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'nonPreemptive-high-priority','1','1');
insert into cnfpriority (DESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'preemptive-medium-high-priority','1','1');
insert into cnfpriority (DESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'nonPreemptive-medium-high-priority','1','1');
insert into cnfpriority (DESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'preemptive-medium-priority','1','1');
insert into cnfpriority (DESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'nonPreemptive-medium-priority','1','1');
insert into cnfpriority (DESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'preemptive-low-priority','1','1');
insert into cnfpriority (DESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'nonPreemptive--low-priority','1','1');
Commit; 

-----------------------------------------
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'SC(BSF)',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'SC(SCP)',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'EVNFM',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'CCDM',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'CCSM',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'CNOM',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'EDA2',1,1);
insert into cnfname (CNFDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values  ( 'SC(SEPP)',1,1);

Commit; 
------------------------------ functionstandardname

insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-Common Services',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-BSF',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-DRA',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-SCP',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-DA',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-SEPP',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('SC-DEA',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('VNF LCM',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('UDR',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('UDM/AUSF',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('CNOM',1,1);
insert into functionstandardname (FUNCTIONNAME, CREATIONUSER, MODIFICATIONUSER) values ('Signalling Edge ',1,1);


Commit;

-----------------------------------------------------------
 
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL,ALAISNAME, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'BSF Cluster', 'SC-BSF-NP1', 'BSF Cluster', SC(BSF),1 FROM cnfname WHERE CNFDESCRIPTION = 'SC(BSF)';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL,ALAISNAME, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'SCP Cluster', 'SC-SCP-NP1', 'SCP Cluster', SC(SCP),1 FROM cnfname WHERE CNFDESCRIPTION = 'SC(SCP)';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL,ALAISNAME, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'EVNFM Cluster', 'EVNFM-NP1', 'EVNFM-NP1', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'EVNFM';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL,ALAISNAME, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'CCDM Cluster', 'CCDM-NP1', 'CCDM - NP1', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'CCDM';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL,ALAISNAME, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'CCDM Cluster', 'CCDM-NP1', 'CCDM-NP1', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'CCDM';

insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL,ALAISNAME, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'CCDM Cluster', 'CCSM-NP1', 'CCSM - NP1', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'CCSM';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL,ALAISNAME, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'CNOM Cluster', 'CNOM-NP1', 'CNOM-NP1', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'CNOM';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL,ALAISNAME, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'EDA Cluster', 'EDA-NP1', 'EDA-NP1', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'EDA2';
insert into CNFCLUSTER (CNFNAMEID,CNFCLUSTERNAME,NODEPOOL,ALAISNAME, CREATIONUSER, MODIFICATIONUSER)SELECT cnfnameid, 'SEPP Cluster', 'SC-SEPP-NP1', 'SC-SEPP-NP1', 1,1 FROM cnfname WHERE CNFDESCRIPTION = 'SC(SEPP)';
Commit; 

-------------

insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-mediator','CM_Mediator',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-mediator-key-init','CM_Mediator_Key_Init',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-mediator-notifier','CM_Mediator_Notifier',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-yang-provider','CM_Yang_Provider',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ctrl-bro','Backup_and_Restore_Orchestrator',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-coordinator-zk','Data_Coordinator_ZK',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-distributed-coordinator-ed','Distributed_Coordinator_ED',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-distributed-coordinator-ed-agent','Distributed_Coordinator_ED_Agent',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-distributed-coordinator-ed-sc','Distributed_Coordinator_ED_SC',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg','Document_DB_PG',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg-bragent','Document_DB_PG_BR_Agent',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-message-bus-kf','Message_Bus_KF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-curator','Search_Engine_Curator',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-data','Search_Engine_Data',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-ingest-tls','Search_Engine_Ingest',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-master','Search_Engine_Master',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-wide-column-database-cd-operator','eric-data-wide-column-database-cd-operator',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-fh-alarm-handler','Alarm_Handler',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-fh-snmp-alarm-provider','SNMP_Alarm_Provider',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-lm-combined-server-license-consumer-handler','License_Manager_Consumer_Handler',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-lm-combined-server-license-server-client','License_Manager_Server_Client',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-log-transformer','Log_Transformer',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-odca-diagnostic-data-collector','Diagnostic_Data_Collector',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-odca-diagnostic-data-collector-manual','Diagnostic_Data_Collector_Manual',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-bulk-reporter','PM_Bulk_Reporter',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-server','PM_Server',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-admin-user-management','Admin_User_Management',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-certm','Certificate_Management',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-key-management-main','Key_Management',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-ldap-server','LDAP_Server',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-ldap-server-proxy','LDAP_Server_BR_Agent',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-sip-tls-main','Service_Identity_Provider_TLS',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-si-application-sys-info-handler','eric-si-application-sys-info-handler',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-tm-ingress-controller-cr-contour','Ingress_Controller_CR_Contour',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cnom-server','CNOM_Server',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sc-hcagent','Health_Check_Agent',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sc-manager','SC_Manager',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sc-monitor','Monitor',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-log-shipper','Log_Shipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-tm-ingress-controller-cr-envoy','Ingress_Controller_CR_Envoy',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-stm-diameter','Diameter',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-wide-column-database-cd','Wide_Column_Database_CD',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-bsf-diameter','BSF_Diameter',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-bsf-manager','BSF_Manager',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-bsf-manager-vtap1','BSF_Manager_vTAP1',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-bsf-worker','BSF_Worker',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-bsf-worker-vtap2','BSF_Worker_vTAP2',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-probe-virtual-tap-broker-vtap2','Probe vTAP Broker',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-scp-manager','SCP_Manager',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-scp-manager-vtap1','SCP_Manager_vTAP1',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-scp-worker','SCP_Worker',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-scp-worker-vtap2','eric-scp-worker-vtap2',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sc-rlf','SC_Rate Limiting',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('General','General',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('CNOM-RESOURCES: ','CNOM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-aaa','eric-act-aaa',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-activation-cli','eric-act-data-view-engine,eric-act-massive-cli-api',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-activation-engine','eric-act-data-view-engine',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-activation-orchestrator-deployer','eric-act-service-model-deployer',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-activation-orchestrator','eric-act-activation-orchestrator',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-activation-replicator','eric-act-activation-replicator',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-application-resource-monitor','monitor',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-csr-data-collection','eric-act-csr-data-collection',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-cudb-activation-blocker','eric-act-cudb-activation-blocker',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-inbound-async','eric-act-inbound-async',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-inbound-batch-handler','eric-act-inbound-batch-handler',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-inbound-interfaces','eric-act-inbound-interfaces',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-inbound-mml','eric-act-inbound-mml',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-mutex-handler','eric-act-mutex-handler',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-proclog-cassandra-stasher','stasher',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-proclog-manager','manager',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-rest-provisioning','eric-act-rest-provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-service-locator-registry','slr',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-smtp-sender','eric-act-smtp-sender',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-tomcat','tomcat',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cnom-document-database-mg','eric-cnom-document-database-mg,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cnom-server','server,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ctrl-bro','eric-ctrl-bro',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-coordinator-zk-agent','eric-data-coordinator-zk-agent,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-coordinator-zk','datacoordinatorzk,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-distributed-coordinator-ed-agent','eric-data-distributed-coordinator-ed-agent,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-distributed-coordinator-ed','dced,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg','eric-data-document-database-pg,eric-data-document-database-pg-metrics,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg-bragent','eric-data-document-database-pg-bra,eric-data-document-database-pg-brm,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-message-bus-kf','messagebuskf,jmxexporter,logshipper,metricsexporter',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-data','logshipper,metrics,data,tlsproxy',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-ingest-tls','logshipper,metrics,ingest,tlsproxy',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-ingest','logshipper,metrics,ingest,tlsproxy',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-master','logshipper,metrics,master,tlsproxy',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-wide-column-database-cd-datacenter1-bra','bra,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-wide-column-database-cd','brsc,cassandra,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-fh-alarm-handler','eric-fh-alarm-handler,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-fh-snmp-alarm-provider','eric-fh-snmp-alarm-provider,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-wide-column-database-cd-operator','logshipper,operator',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-lm-combined-server-license-consumer-handler','eric-lm-license-consumer-handler,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-lm-combined-server-license-server-client','eric-lm-license-server-client,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-log-transformer','logtransformer,logshipper,metrics,tlsproxy',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-server','eric-pm-configmap-reload,eric-pm-exporter,eric-pm-reverseproxy,eric-pm-server,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-key-management-main','kms,logshipper,shelter',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-sip-tls-main','logshipper,sip-tls,sip-tls-supervisor',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-tm-ingress-controller-cr-contour','contour,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-tm-ingress-controller-cr-envoy','envoy,logshipper',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-resource-monitor','eric-pm-resource-monitor',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sepp-manager','SEPP_Manager',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sepp-manager-vtap1','SEPP_Manager_vTAP1',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sepp-worker','SEPP_Worker',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sepp-worker-vtap2','eric-sepp-worker-vtap2',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-nudrfe','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-notificationsubscription','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-gudrestfe','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-provisioningfe','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-eda-provisioning','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-ldapfe','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-ldap-balancer','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-kvdb-ag-server','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-kvdb-ag-locator','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-kvdb-ag-operator','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-kvdb-ag-admin-mgr','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-rest-notifchecker','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-rest-notifsender','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-soap-notifchecker','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-soap-notifsender','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-nrfproxy','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-cmagent','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-message-bus-kf','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-udr-ldap-traffic','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-udr-ldap-provisioning','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-udr-traffic','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-udr-intersite','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-data-model-controller','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-dbmanager','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-dbmonitor','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-message-bus-monitor','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-system-status-provider','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-system-monitor','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-app-counters','Data access/visualization',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-migration-orchestrator','Data access/visualization',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-migration-task','Data access/visualization',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-consistency-check-orchestrator','Data access/visualization',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-consistency-check-worker','Data access/visualization',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-import-export-orchestrator','Data access/visualization',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-license-handler','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-cmmanager','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-provisioningrm','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-bulk-data-synchronizer','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udr-prov-sync-fe','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-mediator','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-yang-provider','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cnom-server','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-mediator-notifier','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg-bragent','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-bulk-reporter','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-server','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-fh-alarm-handler','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-fh-snmp-alarm-provider','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-log-shipper','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-log-transformer','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-data','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-ingest','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-ingest-tls','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-master','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-odca-diagnostic-data-collector','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-odca-diagnostic-data-collector-manual','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-mesh-controller','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-ldap-server','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-ldap-server-proxy','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-distributed-coordinator-ed','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-distributed-coordinator-ed-agent','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-access-mgmt','Security',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-key-management-main','Security',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-sip-tls-main','Security',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-certm','Security',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-admin-user-management','Security',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-nrf-discovery-agent','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-nrf-notify-agent','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-nrf-register-agent','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-coordinator-zk','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ctrl-bro','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-tm-ingress-controller-cr-contour','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-tm-ingress-controller-cr-envoy','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-lm-combined-server-license-consumer-handler','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-lm-combined-server-license-server-client','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-object-storage-mn','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-object-storage-mn-mgt','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-nrf-accesstoken-agent','Monitoring/HA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-si-application-sys-info-handler','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-resource-monitor','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-access-mgmt-sip','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-probe-virtual-tap-broker','Traffic',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-application-resource-monitor','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-mapi-provisioning','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-mb-kf','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-oauth-token-validator','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-proclog-cassandra-stasher','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-proclog-manager','OAM',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-service-locator-registry','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-user-data-activator','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-act-user-data-activator-synchronizer','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-wide-column-database-cd','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-wide-column-database-cd-bra','Provisioning',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-wide-column-database-cd-operator','Database',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-backup-ca','CA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccdm-extraction-ca','CA',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('Resiliency and SW upgrade','',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-mediator','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-mediator-notifier','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cm-yang-provider','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-cnom-server','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ctrl-bro','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-coordinator-zk','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-distributed-coordinator-ed','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-distributed-coordinator-ed-agent','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg-ah','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg-bragent','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-document-database-pg-lm','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-message-bus-kf','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-object-storage-mn','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-object-storage-mn-kes','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-object-storage-mn-mgt','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-data','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-ingest','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-ingest-tls','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-data-search-engine-master','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-fh-alarm-handler','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-fh-snmp-alarm-provider','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-ausf-traffic','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-eir-traffic','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-nrfagent-internal-traffic','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-udm-internal-traffic','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ingressgw-udm-traffic','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-lm-combined-server-license-consumer-handler','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-lm-combined-server-license-server-client','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-lm-unique-object-reporter','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-log-shipper','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-log-transformer','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-mesh-controller','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-odca-diagnostic-data-collector','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-odca-diagnostic-data-collector-manual','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-bulk-reporter','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-resource-monitor','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-pm-server','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-admin-user-management','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-certm','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-key-management-main','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-ldap-server','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-ldap-server-proxy','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-sec-sip-tls-main','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-si-application-sys-info-handler','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-tm-ingress-controller-cr-contour-v1','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-tm-ingress-controller-cr-envoy','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-autonrf','ADP',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-cmagent','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-cmreconciler','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-cmvalidator','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-datainjector','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-diacmagent','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-keymanager','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-lmagent','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-mapproxy-1','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-mapproxy-1-config-validator','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-mapproxy-1-state-provider-proxy','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-mapproxy-2','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-mapproxy-3','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-mapproxy-4','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-nfcontroller','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-nrfgw','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-smsengine','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-sracmagent','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ccsm-topicwatcher','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-probe-virtual-tap-broker','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-slt-dsl','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-stm-diameter','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-eir-capacity','CCSM Common Services',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-eir-cmagent','EIR',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-eir-diametereireic','EIR',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-eir-eireic','EIR',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-eir-gsmadbhandler','EIR',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-eir-mapeireic','EIR',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-eir-s13diameter','EIR',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-eir-socshipper','EIR',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-nrf-accesstoken-agent','NRF Interaction',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-nrf-discovery-agent','NRF Interaction',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-nrf-notify-agent','NRF Interaction',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-nrf-register-agent','NRF Interaction',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-svc-routing-agent','NRF Interaction',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ausf-capacity','NRF Interaction',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ausf-cmjobloader','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-ausf-engine','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-amfeenotifications','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-amfeesubscriptions','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-authconf','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-blackhole','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-cancelepclocation','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-capacity','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-cmagent','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-eapauth','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-eapprimeauth','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-epsauth','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-gbaauth','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-iratamfdereg','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-iratamflocation','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-iratsndereg','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-iwk5g2g','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-mtlocation','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-mtsmsdeliverystatus','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-mtsmsreadystatus','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-mtsmsroutinginfo','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-mtsmswaitingdata','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-mtueinfo','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-pcscfrestnotif','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-pcscfrestoration','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmamdata','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmimplicitunsub','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmmultipledataset','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmnotif','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmnssai','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmsmdata','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmsmfselect','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmsmsdata','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmsmsmngdata','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmsubscriptions','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmuectxtsmf','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-sdmuectxtsmsf','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-ueauth','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-uecmamfderegnotifier','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-uecmamfget','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-uecmamfregupdate','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-uecmreg','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-uecmsmfderegistration','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-uecmsmfregistration','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-uecmsmsfdereg','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-uecmsmsfregget','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-uecmsmsfregistration','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-ueshcm','UDM/AUSF',1,1);
insert into podtypeinfo (PODTYPEINFONAME,PODROLEDESCRIPTION, CREATIONUSER, MODIFICATIONUSER) values ('eric-udm-umtsauth','UDM/AUSF',1,1);
Commit;

-----------------
 