
ALTER TABLE VNFVMCAPACITY ADD   NOOFVNFINSTANCES  NUMBER(19);
ALTER TABLE VNFVMCAPACITY ADD   NOOFVMSPERTYPE  NUMBER(19);

UPDATE VNFVMCAPACITY vc
SET (vc.NOOFVNFINSTANCES, vc.NOOFVMSPERTYPE) = (
    SELECT vi.NOOFVNFINSTANCES, vi.NOOFVMSPERTYPE
    FROM VNFINFO vi
    WHERE vi.VNFINFOID = vc.VNFINFOID
)
WHERE EXISTS (
    SELECT 1
    FROM VNFINFO vi
    WHERE vi.VNFINFOID = vc.VNFINFOID
);
Commit;
 
ALTER TABLE VNFINFO DROP COLUMN  NOOFVNFINSTANCES  ;
ALTER TABLE VNFINFO DROP COLUMN NOOFVMSPERTYPE;