 
ALTER TABLE CNFPODINFO ADD   PODROLEDESCRIPTIONID  NUMBER(19,0)  ;
ALTER TABLE CNFCLUSTERINFO ADD   CNFCLUSTERNODEPOOLID  NUMBER(19,0)  ; 

ALTER TABLE CNFPODINFO ADD CONSTRAINT "FK_CNFPODINFO_PODTYPEINFO_PODROLEDESCRIPTIONID" FOREIGN KEY ("PODROLEDESCRIPTIONID")
REFERENCES "PODTYPEINFO" ("PODTYPEINFOID") ENABLE;	

ALTER TABLE CNFCLUSTERINFO ADD CONSTRAINT "FK_CNFCLUSTERINFO_CNFCLUSTER_CNFCLUSTERNODEPOOLID" FOREIGN KEY ("CNFCLUSTERNODEPOOLID")
REFERENCES "CNFCLUSTER" ("CNFCLUSTERID") ENABLE;		  


UPDATE CNFPODINFO SET  PODROLEDESCRIPTIONID =  PODTYPEINFOID;
UPDATE CNFCLUSTERINFO SET  CNFCLUSTERNODEPOOLID = CNFCLUSTERID;
COMMIT;


ALTER TABLE  CNFCLUSTERINFO MODIFY WORKERNODECONFIGURATION NULL;
ALTER TABLE  CNFCLUSTERINFO MODIFY HARDWARE NULL;
ALTER TABLE  CNFCLUSTERINFO MODIFY CPUKUBELET NULL;
ALTER TABLE  CNFCLUSTERINFO MODIFY MEMKUBELET NULL;
ALTER TABLE  CNFCLUSTERINFO MODIFY CPUSYSTEM NULL;
ALTER TABLE  CNFCLUSTERINFO MODIFY MEMSYSTEM NULL;