Set DEFINE OFF;	 
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values('CNFINFO','k8ClusterName','K8 Cluster Name',1,0,1,2,1, 'CbomTest',1,1);
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values('CNFINFO','nodePool','Nodepool Name',2,0,1,2,1, 'CbomTest',1,1);
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values('CNFINFO','comments','Comments (This columns will not be processed by cindox)',3,0,1,2,1, 'CbomTest',1,1);
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values('CNFINFO','nodePoolBreakup','Nodepool Breakup *(If ""Yes"" selected, VF may/maynot split the nodepool to achieve best possible hardware utilisation)',4,0,1,2,1, 'CbomTest',1,1);
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values('CNFINFO','specialRequirements','Special Requirement.(Any special requiremet will create a separate physical cluster for the nodepool)',5,0,1,2,1, 'CbomTest',1,1);
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values('CNFINFO','hyperThreading','Hyperthreading*(Option only available for Control Plane)*',6,0,1,2,1, 'CbomTest',1,1);
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values('CNFINFO','overProvisioning','OverProvisioning (To be enabled only for control plane and if HT is disabled)',7,0,1,2,1, 'CbomTest',1,1);
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values('CNFINFO','workerNodeConfiguration','Worker Node Configuration(Note:To be filled by Vodafone not by vendor)',8,0,1,2,1, 'CbomTest',1,1);
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values('CNFINFO','cpuKubelet','cpu kubelet (if empty, defaults to a reservation of 500m, does not accept values over 1)',10,0,1,2,1, 'CbomTest',1,1);
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values('CNFINFO','memKubelet','mem kubelet  (if empty assumes 2, cannot be more then 4)',11,0,1,2,1, 'CbomTest',1,1);
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values('CNFINFO','cpuSystem','cpu system (if empty, defaults to a reservation of 500m, does not accept values over 1) ',12,0,1,2,1, 'CbomTest',1,1);
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values('CNFINFO','memSystem','mem system (if empty assumes 2, cannot be more then 4)',13,0,1,2,1, 'CbomTest',1,1);
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values('CNFINFO','note','*Note:Hyperthreading enabled does not mean double the cpu performance, only after discussion and approval with CNF vendor shoud it be enabled.',14,0,1,2,1, 'CbomTest',1,1);
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values('CNFINFO','k8ClusterName','K8 Cluster Name',16,0,1,2,1, 'CbomTest',1,1);
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values('CNFINFO','aggregateImageClusterSize','Aggergate image size on k8 cluster(Note: if left empty default 10 GB will be assumed )',17,0,1,2,1, 'CbomTest',1,1);
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values('CNFINFO','hardware','Hardware(Note:To be filled by Vodafone not by vendor)',9,0,1,2,1, 'CbomTest',1,1);
SET DEFINE ON;
COMMIT; 



update exceltemplateconfiguration set  COLUMNHEADERNAME = 'Nodepool Breakup *(If "Yes" selected, VF may/maynot split the nodepool to achieve best possible hardware utilisation)' where PROCESSNAME = 'CNFINFO' and COLUMNORDER = 4;
commit;