--------------------------------------------------------
--  DDL FOR TABLE INFRACLUSTERASPLANNED_SEQ
--------------------------------------------------------

CREATE SEQUENCE "INFRACLUSTERASPLANNED_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE INFRACLUSTERASPLANNED 
---------------------------------------


CREATE TABLE "INFRACLUSTERASPLANNED" 
(	"INFRACLUSTERASPLANNEDID" NUMBER(19,0) DEFAULT "INFRACLUSTERASPLANNED_SEQ"."NEXTVAL", 	
	"OPCOID" NUMBER(5,0),
	"LOCATIONID" NUMBER(5,0),
	"SITE" NVARCHAR2(100),
	"PLATFORMID"  NUMBER(5,0),
	"CLUSTERTYPEID" NUMBER(19,0),
	"CLUSTERNAME" NVARCHAR2(255),
	"HARDWARETYPE" NUMBER(19,0),
	"DEPLOYMENTSTATUSID" NUMBER(5,0),
	"VERTICALRESPONSIBLEID" NUMBER(10,0)	,
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
	
  --------------------------------------------------------
--  DDL FOR INDEX PK_INFRACLUSTERASPLANNED
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_INFRACLUSTERASPLANNED" ON "INFRACLUSTERASPLANNED" ("INFRACLUSTERASPLANNEDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE INFRACLUSTERASPLANNED
--------------------------------------------------------
 
  ALTER TABLE "INFRACLUSTERASPLANNED" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "INFRACLUSTERASPLANNED" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "INFRACLUSTERASPLANNED" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "INFRACLUSTERASPLANNED" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "INFRACLUSTERASPLANNED" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "INFRACLUSTERASPLANNED" ADD CONSTRAINT "PK_INFRACLUSTERASPLANNED" PRIMARY KEY ("INFRACLUSTERASPLANNEDID") USING INDEX "PK_INFRACLUSTERASPLANNED"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE INFRACLUSTERASPLANNED
--------------------------------------------------------

  ALTER TABLE "INFRACLUSTERASPLANNED" ADD CONSTRAINT "FK_INFRACLUSTERASPLANNED_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "INFRACLUSTERASPLANNED" ADD CONSTRAINT "FK_INFRACLUSTERASPLANNED_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;

  ALTER TABLE "INFRACLUSTERASPLANNED" ADD CONSTRAINT "FK_INFRACLUSTERASPLANNED_LOCATIONS_LOCATIONID" FOREIGN KEY ("LOCATIONID") REFERENCES "LOCATIONS" ("LOCATIONID") ENABLE;  
 
 ALTER TABLE "INFRACLUSTERASPLANNED" ADD CONSTRAINT "FK_INFRACLUSTERASPLANNED_OPCOS_LOCATIONID" FOREIGN KEY ("OPCOID") REFERENCES "OPCOS" ("OPCOID") ENABLE;
  
  ALTER TABLE "INFRACLUSTERASPLANNED" ADD CONSTRAINT "FK_INFRACLUSTERASPLANNED_DEPLOYMENTSTATUSES_DEPLOYMENTSTATUSID" FOREIGN KEY ("DEPLOYMENTSTATUSID") REFERENCES "DEPLOYMENTSTATUSES" ("DEPLOYMENTSTATUSID") ENABLE;	  
  
  ALTER TABLE "INFRACLUSTERASPLANNED" ADD CONSTRAINT "FK_INFRACLUSTERASPLANNED_MAJORHARDWAREBUILDS_HARDWARETYPE" FOREIGN KEY ("HARDWARETYPE") REFERENCES "MAJORHARDWAREBUILDS" ("MAJORHARDWAREID") ENABLE;
  
  ALTER TABLE "INFRACLUSTERASPLANNED" ADD CONSTRAINT "FK_INFRACLUSTERASPLANNED_MAJORSOFTWAREBUILDS_CLUSTERTYPEID" FOREIGN KEY ("CLUSTERTYPEID") REFERENCES "MAJORSOFTWAREBUILDS" ("MAJORSOFTWAREBUILDSID") ENABLE;
  
  ALTER TABLE "INFRACLUSTERASPLANNED" ADD CONSTRAINT "FK_INFRACLUSTERASPLANNED_PLATFORMS_CLUSTERTYPEID" FOREIGN KEY ("PLATFORMID") REFERENCES "PLATFORMS" ("PLATFORMID") ENABLE;
 
 ALTER TABLE "INFRACLUSTERASPLANNED" ADD CONSTRAINT "FK_INFRACLUSTERASPLANNED_VERTICALRESPONSIBLES_VERTICALRESPONSIBLEID" FOREIGN KEY ("VERTICALRESPONSIBLEID") REFERENCES "VERTICALRESPONSIBLES" ("VERTICALRESPONSIBLEID") ENABLE;	 
   
  COMMIT;
  
 -------------------------------------------------
--------------------------------------------------------
--  DDL FOR TABLE NETWORKELEMENTCLUSTERASPLANNED_SEQ
--------------------------------------------------------

CREATE SEQUENCE "NETWORKELEMENTCLUSTERASPLANNED_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE NETWORKELEMENTCLUSTERASPLANNED 
---------------------------------------


CREATE TABLE "NETWORKELEMENTCLUSTERASPLANNED" 
(	"NETWORKELEMENTCLUSTERASPLANNEDID" NUMBER(19,0) DEFAULT "NETWORKELEMENTCLUSTERASPLANNED_SEQ"."NEXTVAL", 	
	"INFRACLUSTERASPLANNEDID" NUMBER(19,0),
	"APPLICATIONID" NUMBER(20,0),
	"APPCLUSTERNAME" NVARCHAR2(255),	 
	"DEPLOYMENTSTATUSID" NUMBER(5,0),	
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
	
  --------------------------------------------------------
--  DDL FOR INDEX PK_NETWORKELEMENTCLUSTERASPLANNED
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_NETWORKELEMENTCLUSTERASPLANNED" ON "NETWORKELEMENTCLUSTERASPLANNED" ("NETWORKELEMENTCLUSTERASPLANNEDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE NETWORKELEMENTCLUSTERASPLANNED
--------------------------------------------------------
 
  ALTER TABLE "NETWORKELEMENTCLUSTERASPLANNED" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "NETWORKELEMENTCLUSTERASPLANNED" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "NETWORKELEMENTCLUSTERASPLANNED" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "NETWORKELEMENTCLUSTERASPLANNED" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "NETWORKELEMENTCLUSTERASPLANNED" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "NETWORKELEMENTCLUSTERASPLANNED" ADD CONSTRAINT "PK_NETWORKELEMENTCLUSTERASPLANNED" PRIMARY KEY ("NETWORKELEMENTCLUSTERASPLANNEDID") USING INDEX "PK_NETWORKELEMENTCLUSTERASPLANNED"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE NETWORKELEMENTCLUSTERASPLANNED
--------------------------------------------------------

  ALTER TABLE "NETWORKELEMENTCLUSTERASPLANNED" ADD CONSTRAINT "FK_NETWORKELEMENTCLUSTERASPLANNED_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "NETWORKELEMENTCLUSTERASPLANNED" ADD CONSTRAINT "FK_NETWORKELEMENTCLUSTERASPLANNED_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;

  ALTER TABLE "NETWORKELEMENTCLUSTERASPLANNED" ADD CONSTRAINT "FK_NETWORKELEMENTCLUSTERASPLANNED_INFRACLUSTERASPLANNED_INFRACLUSTERASPLANNEDID" FOREIGN KEY ("INFRACLUSTERASPLANNEDID") REFERENCES "INFRACLUSTERASPLANNED" ("INFRACLUSTERASPLANNEDID") ENABLE;  
 
  ALTER TABLE "NETWORKELEMENTCLUSTERASPLANNED" ADD CONSTRAINT "FK_NETWORKELEMENTCLUSTERASPLANNED_PRODUCTNAME_PRODUCTNAMEID" FOREIGN KEY ("APPLICATIONID") REFERENCES "PRODUCTNAME" ("PRODUCTNAMEID") ENABLE;
  
 ALTER TABLE "NETWORKELEMENTCLUSTERASPLANNED" ADD CONSTRAINT "FK_NETWORKELEMENTCLUSTERASPLANNED_DEPLOYMENTSTATUSES_DEPLOYMENTSTATUSID" FOREIGN KEY ("DEPLOYMENTSTATUSID") REFERENCES "DEPLOYMENTSTATUSES" ("DEPLOYMENTSTATUSID") ENABLE;	 
  
  COMMIT; 
  
 -------------------------------------
--------------------------------------------------------
--  DDL FOR TABLE CLUSTERUPGRADESTATUS_SEQ
--------------------------------------------------------

CREATE SEQUENCE "CLUSTERUPGRADESTATUS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE CLUSTERUPGRADESTATUS 
---------------------------------------


CREATE TABLE "CLUSTERUPGRADESTATUS" 
(	"CLUSTERUPGRADESTATUSID" NUMBER(19,0) DEFAULT "CLUSTERUPGRADESTATUS_SEQ"."NEXTVAL", 	
	"INFRACLUSTERASPLANNEDID" NUMBER(19,0),
	"NETWORKELEMENTCLUSTERASPLANNEDID" NUMBER (19,0),
	"PLANNEDACTIVITYID" NUMBER (19,0),
	"STATUSID" NUMBER(5,0),	
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
	
  --------------------------------------------------------
--  DDL FOR INDEX PK_CLUSTERUPGRADESTATUS
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_CLUSTERUPGRADESTATUS" ON "CLUSTERUPGRADESTATUS" ("CLUSTERUPGRADESTATUSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE CLUSTERUPGRADESTATUS
--------------------------------------------------------
 
  ALTER TABLE "CLUSTERUPGRADESTATUS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CLUSTERUPGRADESTATUS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CLUSTERUPGRADESTATUS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CLUSTERUPGRADESTATUS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CLUSTERUPGRADESTATUS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "CLUSTERUPGRADESTATUS" ADD CONSTRAINT "PK_CLUSTERUPGRADESTATUS" PRIMARY KEY ("CLUSTERUPGRADESTATUSID") USING INDEX "PK_CLUSTERUPGRADESTATUS"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE CLUSTERUPGRADESTATUS
--------------------------------------------------------

  ALTER TABLE "CLUSTERUPGRADESTATUS" ADD CONSTRAINT "FK_CLUSTERUPGRADESTATUS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CLUSTERUPGRADESTATUS" ADD CONSTRAINT "FK_CLUSTERUPGRADESTATUS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;

  ALTER TABLE "CLUSTERUPGRADESTATUS" ADD CONSTRAINT "FK_CLUSTERUPGRADESTATUS_INFRACLUSTERASPLANNED_INFRACLUSTERASPLANNEDID" FOREIGN KEY ("INFRACLUSTERASPLANNEDID") REFERENCES "INFRACLUSTERASPLANNED" ("INFRACLUSTERASPLANNEDID") ENABLE;  
 
  ALTER TABLE "CLUSTERUPGRADESTATUS" ADD CONSTRAINT "FK_CLUSTERUPGRADESTATUS_NETWORKELEMENTCLUSTERASPLANNED_NETWORKELEMENTCLUSTERASPLANNEDID" FOREIGN KEY ("NETWORKELEMENTCLUSTERASPLANNEDID") REFERENCES "NETWORKELEMENTCLUSTERASPLANNED" ("NETWORKELEMENTCLUSTERASPLANNEDID") ENABLE;
  
 ALTER TABLE "CLUSTERUPGRADESTATUS" ADD CONSTRAINT "FK_CLUSTERUPGRADESTATUS_PLANNEDACTIVITIES_PLANNEDACTIVITYID" FOREIGN KEY ("PLANNEDACTIVITYID") REFERENCES "PLANNEDACTIVITIES" ("PLANNEDACTIVITYID") ENABLE;	 
  
 
update  PLANNEDACTIVITYTYPES  set PLANNEDACTIVITYTYPEDESCRIPTION = 'Add New Cluster' where PLANNEDACTIVITYTYPEDESCRIPTION = 'AddNewCluster';
Commit;  