--------------------------------------------------------
--  DDL FOR TABLE ASPNETUSEROPCOS_SEQ
--------------------------------------------------------

CREATE SEQUENCE "ASPNETUSEROPCOS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE ASPNETUSEROPCOS 
---------------------------------------


CREATE TABLE "ASPNETUSEROPCOS" 
(	"ASPNETUSEROPCOID" NUMBER(10,0) DEFAULT "ASPNETUSEROPCOS_SEQ"."NEXTVAL",
	"USERID" NUMBER(10,0),
	"OPCOID" NUMBER(5,0),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
  
  --------------------------------------------------------
--  DDL FOR INDEX PK_ASPNETUSEROPCOS
-------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_ASPNETUSEROPCOS" ON "ASPNETUSEROPCOS" ("ASPNETUSEROPCOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE ASPNETUSEROPCOS
--------------------------------------------------------
 
  ALTER TABLE "ASPNETUSEROPCOS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSEROPCOS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSEROPCOS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSEROPCOS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSEROPCOS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSEROPCOS" ADD CONSTRAINT "PK_ASPNETUSEROPCOS" PRIMARY KEY ("ASPNETUSEROPCOID") USING INDEX "PK_ASPNETUSEROPCOS"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE ASPNETUSEROPCOS
--------------------------------------------------------

  ALTER TABLE "ASPNETUSEROPCOS" ADD CONSTRAINT "FK_ASPNETUSEROPCOS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "ASPNETUSEROPCOS" ADD CONSTRAINT"FK_ASPNETUSEROPCOS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "ASPNETUSEROPCOS" ADD CONSTRAINT"FK_ASPNETUSEROPCOS_ASPNETUSERS_USERID" FOREIGN KEY ("USERID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "ASPNETUSEROPCOS" ADD CONSTRAINT"FK_ASPNETUSEROPCOS_OPCOS_OPCOID" FOREIGN KEY ("OPCOID") REFERENCES "OPCOS" ("OPCOID") ENABLE;
  COMMIT;
  
 -------------------------- SEPARATE OPCO FROM ASPNETUSERROLES  TO ASPNETUSEROPCOS
INSERT INTO ASPNETUSEROPCOS (USERID, OPCOID,CREATIONUSER,MODIFICATIONUSER)
SELECT DISTINCT R1.USERID, R1.OPCOID,1,1
FROM ASPNETUSERROLES R1 WHERE NOT EXISTS (
SELECT 1  FROM ASPNETUSEROPCOS UO  WHERE UO.USERID = R1.USERID  AND UO.OPCOID = R1.OPCOID );

COMMIT; 