--------------------------------------------------------
--  DDL FOR TABLE ASPNETUSERVERTICALS_SEQ
--------------------------------------------------------

CREATE SEQUENCE "ASPNETUSERVERTICALS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE ASPNETUSERVERTICALS 
---------------------------------------


CREATE TABLE "ASPNETUSERVERTICALS" 
(	"ASPNETUSERVERTICALID" NUMBER(10,0) DEFAULT "ASPNETUSERVERTICALS_SEQ"."NEXTVAL",
	"USERID" NUMBER(10,0),
	"ORGANISATIONID" NUMBER(19,0),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
  
  --------------------------------------------------------
--  DDL FOR INDEX PK_ASPNETUSERVERTICALS
-------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_ASPNETUSERVERTICALS" ON "ASPNETUSERVERTICALS" ("ASPNETUSERVERTICALID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE ASPNETUSERVERTICALS
--------------------------------------------------------
 
  ALTER TABLE "ASPNETUSERVERTICALS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSERVERTICALS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSERVERTICALS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSERVERTICALS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSERVERTICALS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSERVERTICALS" ADD CONSTRAINT "PK_ASPNETUSERVERTICALS" PRIMARY KEY ("ASPNETUSERVERTICALID") USING INDEX "PK_ASPNETUSERVERTICALS"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE ASPNETUSERVERTICALS
--------------------------------------------------------

  ALTER TABLE "ASPNETUSERVERTICALS" ADD CONSTRAINT "FK_ASPNETUSERVERTICALS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "ASPNETUSERVERTICALS" ADD CONSTRAINT"FK_ASPNETUSERVERTICALS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "ASPNETUSERVERTICALS" ADD CONSTRAINT"FK_ASPNETUSERVERTICALS_ASPNETUSERS_USERID" FOREIGN KEY ("USERID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "ASPNETUSERVERTICALS" ADD CONSTRAINT"FK_ASPNETUSERVERTICALS_ORGANISATION_ORGANISATIONID" FOREIGN KEY ("ORGANISATIONID") REFERENCES "ORGANISATION" ("ORGANISATIONID") ENABLE;
  COMMIT;
  