------------------------------------ ASPNETUSER TABLE CHANGES
ALTER TABLE ASPNETUSERS ADD ISSUBDOMAINSPOC NUMBER(1,0) DEFAULT 0;
ALTER TABLE ASPNETUSERS ADD ISEDUSPOC NUMBER(1,0) DEFAULT 0;
ALTER TABLE ASPNETUSERS ADD ISDESIGNCONTACT NUMBER(1,0) DEFAULT 0;
ALTER TABLE ASPNETUSERS ADD SUBDOMAINRESPONSIBLEID NUMBER(10,0);

ALTER TABLE "ASPNETUSERS" ADD CONSTRAINT"FK_ASPNETUSERS_SUBDOMAINRESPONSIBLES_SUBDOMAINRESPONSIBLEID" FOREIGN KEY ("SUBDOMAINRESPONSIBLEID") REFERENCES "SUBDOMAINRESPONSIBLES" ("SUBDOMAINRESPONSIBLEID") ENABLE;


-------------- UPDATE SUBDOMAINRESPONSIBLE TO USER TABLE

MERGE INTO ASPNETUSERS u USING ( SELECT * FROM (  SELECT org.*, ROW_NUMBER() OVER (
PARTITION BY CONTACTID  ORDER BY SUBDOMAINRESPONSIBLEID DESC ) rn  FROM ORGANISATION org )  WHERE rn = 1 ) org ON (org.CONTACTID = u.ID)
WHEN MATCHED THEN
UPDATE SET 
    u.SUBDOMAINRESPONSIBLEID = org.SUBDOMAINRESPONSIBLEID,
    u.ISSUBDOMAINSPOC       = org.ISSUBDOMAINSPOC,
    u.ISEDUSPOC             = org.ISEDUSPOC,
    u.ISDESIGNCONTACT       = org.ISDESIGNCONTACT;
	
COMMIT;

--------------------- ORGANISATION TABLE ADD COLUMN
CREATE TABLE ORGANISATION_BACKUP AS SELECT * FROM ORGANISATION;

ALTER TABLE ORGANISATION ADD VERTICALID NUMBER(10,0);

ALTER TABLE "ORGANISATION" ADD CONSTRAINT"FK_ORGANISATION_VERTICALRESPONSIBLES_VERTICALRESPONSIBLEID" FOREIGN KEY ("VERTICALID") REFERENCES "VERTICALRESPONSIBLES" ("VERTICALRESPONSIBLEID") ENABLE;

--------------------- ORGANISATION TABLE ONE TIME TABLE POPULATION 
TRUNCATE TABLE ORGANISATION;
COMMIT;

INSERT INTO ORGANISATION (MAINORGANISATIONID,PRACTICEID,VERTICALID,SUBDOMAINRESPONSIBLEID,CONTACTID,CREATIONUSER,MODIFICATIONUSER)
SELECT  M.MAINORGANISATIONID,    P.PRACTICEID,    V.VERTICALRESPONSIBLEID,1,1,1,1
FROM VERTICALRESPONSIBLES V CROSS JOIN MAINORGANISATION M CROSS JOIN PRACTICE P
WHERE M.MAINORGANISATIONDESCRIPTION ='NSE'
AND P.PRACTICEDESCRIPTION  = 'C' || CHR(38) || 'S';

COMMIT;

 -------------------------- VERTICAL ASSIGN TO USER
CREATE TABLE ASPNETUSERROLES_BACKUP AS SELECT * FROM ASPNETUSERROLES;

INSERT INTO aspnetuserverticals (USERID, ORGANISATIONID,CREATIONUSER,MODIFICATIONUSER)
SELECT DISTINCT r1.USERID, org.ORGANISATIONID, 1 as CREATIONUSER, 1 as MODIFICATIONUSER
FROM aspnetuserroles r1 
join verticalresponsibles v1 on v1.VERTICALRESPONSIBLEID = r1.VERTICALRESPONSIBLEID
Join ORGANISATION org on org.VERTICALID = r1.VERTICALRESPONSIBLEID and org.VERTICALID is not null
WHERE NOT EXISTS (
SELECT 1  FROM aspnetuserverticals uo  WHERE uo.USERID = r1.USERID  AND uo.ORGANISATIONID = org.ORGANISATIONID );

COMMIT; 


--------------------- ORGANISATION TABLE  DROP COLUMN

ALTER TABLE ORGANISATION DROP COLUMN SUBDOMAINRESPONSIBLEID;
ALTER TABLE ORGANISATION DROP COLUMN CONTACTID;
ALTER TABLE ORGANISATION DROP COLUMN ISSUBDOMAINSPOC;
ALTER TABLE ORGANISATION DROP COLUMN ISEDUSPOC;
ALTER TABLE ORGANISATION DROP COLUMN ISDESIGNCONTACT;

--------------------- ASPNETUSERROLES TABLE  DROP COLUMN
ALTER TABLE ASPNETUSERROLES DROP COLUMN OPCOID;
ALTER TABLE ASPNETUSERROLES DROP COLUMN VERTICALRESPONSIBLEID;
