--------------------- ORGANISATION TABLE ONE TIME TABLE POPULATION 

INSERT INTO ORGANISATION (MAINORGANISATIONID,PRACTICEID,VERTICALID,CREATIONUSER,MODIFICATIONUSER)
SELECT  M.MAINORGANISATIONID,    P.PRACTICEID,    V.VERTICALRESPONSIBLEID,1,1
FROM VERTICALRESPONSIBLES V CROSS JOIN MAINORGANISATION M CROSS JOIN PRACTICE P
WHERE M.MAINORGANISATIONDESCRIPTION ='NSE'
AND P.PRACTICEDESCRIPTION  = 'C' || CHR(38) || 'S';

COMMIT;


-------------- UPDATE SUBDOMAINRESPONSIBLE TO USER TABLE
UPDATE  ASPNETUSERS SET  ISSUBDOMAINSPOC = 0,ISEDUSPOC = 0,ISDESIGNCONTACT = 0  ;
COMMIT;

MERGE INTO ASPNETUSERS u USING ( SELECT * FROM (  SELECT org.*, ROW_NUMBER() OVER (
PARTITION BY CONTACTID  ORDER BY SUBDOMAINRESPONSIBLEID DESC ) rn  FROM ORGANISATION org )  WHERE rn = 1 ) org ON (org.CONTACTID = u.ID)
WHEN MATCHED THEN
UPDATE SET 
    u.SUBDOMAINRESPONSIBLEID = org.SUBDOMAINRESPONSIBLEID,
    u.ISSUBDOMAINSPOC       = org.ISSUBDOMAINSPOC,
    u.ISEDUSPOC             = org.ISEDUSPOC,
    u.ISDESIGNCONTACT       = org.ISDESIGNCONTACT;
	
COMMIT;

-------------------------- SEPARATE OPCO FROM ASPNETUSERROLES  TO ASPNETUSEROPCOS
INSERT INTO ASPNETUSEROPCOS (USERID, OPCOID,CREATIONUSER,MODIFICATIONUSER)
SELECT DISTINCT R1.USERID, R1.OPCOID,1,1
FROM ASPNETUSERROLES R1 WHERE NOT EXISTS (
SELECT 1  FROM ASPNETUSEROPCOS UO  WHERE UO.USERID = R1.USERID  AND UO.OPCOID = R1.OPCOID );

COMMIT;

-------------------------- VERTICAL ASSIGN TO USER

INSERT INTO aspnetuserverticals (USERID, ORGANISATIONID,CREATIONUSER,MODIFICATIONUSER)
SELECT DISTINCT r1.USERID, org.ORGANISATIONID
FROM aspnetuserroles r1 
join verticalresponsibles v1 on v1.VERTICALRESPONSIBLEID = r1.VERTICALRESPONSIBLEID
Join ORGANISATION org on org.VERTICALID = r1.VERTICALRESPONSIBLEID
WHERE NOT EXISTS (
SELECT 1  FROM aspnetuserverticals uo  WHERE uo.USERID = r1.USERID  AND uo.ORGANISATIONID = org.ORGANISATIONID );

COMMIT;