

ALTER TABLE SUBNETWORKBOUNDARIES
	ADD "VODAFONENAMEID" NUMBER(10,0);


ALTER TABLE "CAMSDBUSER"."SUBNETWORKBOUNDARIES" ADD CONSTRAINT "FK_SUBNETWORKBOUNDARIES_VODAFONENAMES_VODAFONENAMESID" FOREIGN KEY ("VODAFONENAMEID")
	REFERENCES "CAMSDBUSER"."VODAFONENAMES" ("ID") ENABLE;