--------  SCRIPT FOR APPSETTINGS---------------
INSERT INTO  "APPSETTINGS" (APPSETTINGID, DESCRIPTION, CREATIONUSER, MODIFICATIONUSER) VALUES ('6', N'TEMSROLE', '1', '1'); 
Commit;

--------  SCRIPT FOR APPSETTINGSCONFIGURATION---------------
INSERT INTO "APPSETTINGSCONFIGURATION" (APPSETTINGID, SETTINGSVALUE, CREATIONUSER, MODIFICATIONUSER) SELECT 6, ID, 1, 1 FROM ASPNETROLES
WHERE NAME = 'SW Product Owner';
INSERT INTO "APPSETTINGSCONFIGURATION" (APPSETTINGID, SETTINGSVALUE, CREATIONUSER, MODIFICATIONUSER) SELECT 6, ID, 1, 1 FROM ASPNETROLES
WHERE NAME = 'HW Product Owner';
 
Commit;