ALTER TABLE DAASSETMIGRATION DROP COLUMN ISDECOMMISSIONED;
COMMIT;

----------RB SCRIPT FOR THE DAASSETMIGRATION------------
 
ALTER TABLE DAASSETMIGRATION DROP COLUMN PLATFORMID;
ALTER TABLE DAASSETMIGRATION DROP COLUMN PRODUCTNAMEID;
 
--------------------------END----------------------------
