// import { ApiCallWithErrorHandling, BASE_PATH } from "./Common/CommonBusiness";
// import setLoader from "../Redux/Action/LoaderAction";

// import { headerObj, requestHeader } from "./header";
// import { DesignAspectsCreateResponse } from "./../Model/DesignAspects";
// const axios = require("axios");

// export const createDesignAspects = (
//   id?: number
// ): Promise<DesignAspectsCreateResponse> => {
//   return axios.get(BASE_PATH + "/api/DesignAspect/Create", {
//     params: { dcfId: id },
//     Headers: requestHeader,
//   });
// };

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/// <reference path="./Common/custom.d.ts" />
// tslint:disable
/**
 * Cam Vodafone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * Do not edit the class manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./Common/configuration";
import { headerObj } from "./header";

import {
  DataRemediationDto,
  ResultDto,
  ResultDtoOfResultDataRemediationDto,
} from "../Model/CommonModels";
import {
  BASE_PATH,
  FetchArgs,
  FetchAPI,
  RequiredError,
  FilterValueDto,
} from "./Common/CommonBusiness";
import { BaseAPI } from "./Common/CommonBusiness";
import {
  DesignAspectDtoCreate,
  DesignAspectDtoUpdate,
  QueryResultDtoOfDesignAspectDtoGrid,
  DesignAspectQueryObjectGrid as DesignAspectQueryDto,
} from "../Model/DesignAspects";
import { FileResult, ReturnFile } from "../Model/Common";
/**
 * DesignAspectApi - fetch parameter creator
 * @export
 */
export const DesignAspectApiFetchParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @param {DataRemediationDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectApplyDataRemediation(
      body: DataRemediationDto,
      options: any = {}
    ): FetchArgs {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling designAspectApplyDataRemediation."
        );
      }
      const localVarPath = `/api/DesignAspect/ApplyDataRemediation`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "PUT" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"DataRemediationDto" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {DesignAspectDtoCreate} body
     * @param {boolean} [forced]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectCreate(
      body: DesignAspectDtoCreate,
      forced?: boolean,
      options: any = {}
    ): FetchArgs {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling designAspectCreate."
        );
      }
      const localVarPath = `/api/DesignAspect`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "POST" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (forced !== undefined) {
        localVarQueryParameter["forced"] = forced;
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"DesignAspectDtoCreate" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectReset(id: any, options: any = {}): FetchArgs {
      const localVarPath = `/api/DesignAspect/Reset`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (id) {
        localVarQueryParameter["id"] = id;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },

    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectDelete(id?: number, options: any = {}): FetchArgs {
      const localVarPath = `/api/DesignAspect/Delete`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign(
        { method: "DELETE" },
        options
      );
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (id !== undefined) {
        localVarQueryParameter["id"] = id;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {boolean} [onlyPlannedActivities]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectDeleteDeep(
      id?: number,
      onlyPlannedActivities?: boolean,
      options: any = {}
    ): FetchArgs {
      const localVarPath = `/api/DesignAspect/DeleteDeep`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign(
        { method: "DELETE" },
        options
      );
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (id !== undefined) {
        localVarQueryParameter["id"] = id;
      }

      if (onlyPlannedActivities !== undefined) {
        localVarQueryParameter["onlyPlannedActivities"] = onlyPlannedActivities;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {DesignAspectQueryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectExportReport(
      body: DesignAspectQueryDto,
      options: any = {}
    ): FetchArgs {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling designAspectExportReport."
        );
      }
      const localVarPath = `/api/DesignAspect/ExportReport`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "POST" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"DesignAspectQueryDto" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetCreateResourceDesignAspect(
      dcfId: string,
      options: any = {}
    ): FetchArgs {
      const localVarPath = `/api/DesignAspect/Create`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      console.log(dcfId);

      if (dcfId !== "" && dcfId !== "null" && dcfId !== "undefined") {
        localVarQueryParameter["dcfId"] = dcfId;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDCFName(dcfId: string, options: any = {}): FetchArgs {
      const localVarPath = `/api/DesignAspect/GetDCFName`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (dcfId !== "" && dcfId !== "null" && dcfId !== undefined) {
        localVarQueryParameter["dcfId"] = dcfId;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getLinkSubnetworkWithSupportedService(
      dcfId: string,
      supportedServiceId: string,
      options: any = {}
    ): FetchArgs {
      const localVarPath = `/api/DesignComponentFamily/LinkSubnetworkWithSupportedService`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (dcfId !== "" && dcfId !== "null" && dcfId !== undefined) {
        localVarQueryParameter["designComponentFamilyId"] = dcfId;
      }

      if (
        supportedServiceId !== "" &&
        supportedServiceId !== "null" &&
        supportedServiceId !== undefined
      ) {
        localVarQueryParameter["supportedServiceId"] = supportedServiceId;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    getUpdateDAMigration(
      paId: number,
      dcId: number,
      targetDcfId: number,
      options: any = {}
    ): FetchArgs {
      const localVarPath = `/api/LcmEngineering/GetUpdateDaMigrationRecords`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (paId !== undefined) {
        localVarQueryParameter["paId"] = paId;
      }

      if (dcId !== undefined) {
        localVarQueryParameter["currentDcfId"] = dcId;
      }

      if (targetDcfId !== undefined) {
        localVarQueryParameter["targetDcfId"] = targetDcfId;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getLinkNetworkFunction(
      dcfId: string,
      networkFunctionId: string,
      options: any = {}
    ): FetchArgs {
      const localVarPath = `/api/DesignComponentFamily/LinkDCFWithNetworkFunction`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (dcfId !== "" && dcfId !== "null" && dcfId !== undefined) {
        localVarQueryParameter["designComponentFamilyId"] = dcfId;
      }

      if (
        networkFunctionId !== "" &&
        networkFunctionId !== "null" &&
        networkFunctionId !== undefined
      ) {
        localVarQueryParameter["networkFunctionId"] = networkFunctionId;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },

    /**
     *
     * @param {DesignAspectQueryDto} body
     * @param {string} [propertyName]
     * @param {string} [propertyFilter]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetFilterResult(
      body: DesignAspectQueryDto,
      propertyName?: string,
      propertyFilter?: string,
      options: any = {}
    ): FetchArgs {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling designAspectGetFilterResult."
        );
      }
      const localVarPath = `/api/DesignAspect/Filter`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "POST" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (propertyName !== undefined) {
        localVarQueryParameter["propertyName"] = propertyName;
      }

      if (propertyFilter !== undefined) {
        localVarQueryParameter["propertyFilter"] = propertyFilter;
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"DesignAspectQueryDto" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {DesignAspectQueryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetDesignAspect(
      body: DesignAspectQueryDto,
      options: any = {}
    ): FetchArgs {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling designAspectGetDesignAspect."
        );
      }
      const localVarPath = `/api/DesignAspect/Get`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "POST" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"DesignAspectQueryDto" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },

    /**
     *
     * @param {DesignAspectQueryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */

    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetRelatedRecords(id: number, options: any = {}): FetchArgs {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          "id",
          "Required parameter id was null or undefined when calling designAspectGetRelatedRecords."
        );
      }
      const localVarPath = `/api/DesignAspect/GetRelatedRecords`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (id) {
        localVarQueryParameter["id"] = id;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetUpdateResourceDesignAspect(
      id: number,
      options: any = {}
    ): FetchArgs {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          "id",
          "Required parameter id was null or undefined when calling designAspectGetUpdateResourceDesignAspect."
        );
      }
      const localVarPath = `/api/DesignAspect/Update`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (id) {
        localVarQueryParameter["id"] = id;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} [designComponentFamilyId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectServicesAndNetworks(
      designComponentFamilyId?: number,
      options: any = {}
    ): FetchArgs {
      const localVarPath = `/api/DesignAspect/GetServicesAndNetworks`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (designComponentFamilyId !== undefined) {
        localVarQueryParameter["dcfId"] = designComponentFamilyId;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },

    /**
     *
     * @param {number} [opCoId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetDesginComponentFamily(
      opcoId?: number,
      options: any = {}
    ): FetchArgs {
      const localVarPath = `/api/DesignAspect/GetDCFsPerOpco`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (opcoId !== undefined) {
        localVarQueryParameter["opcoId"] = opcoId;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },

    /**
     *
     * @param {DesignAspectDtoUpdate} body
     * @param {boolean} [forced]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectPut(
      body: DesignAspectDtoUpdate,
      forced?: boolean,
      options: any = {}
    ): FetchArgs {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling designAspectPut."
        );
      }
      const localVarPath = `/api/DesignAspect`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "PUT" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (forced !== undefined) {
        localVarQueryParameter["forced"] = forced;
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"DesignAspectDtoUpdate" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectRestore(id?: number, options: any = {}): FetchArgs {
      const localVarPath = `/api/DesignAspect/Restore`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "PUT" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (id !== undefined) {
        localVarQueryParameter["id"] = id;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * DesignAspectApi - functional programming interface
 * @export
 */
export const DesignAspectApiFp = function (configuration?: Configuration) {
  return {
    /**
     *
     * @param {DataRemediationDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectApplyDataRemediation(
      body: DataRemediationDto,
      options?: any
    ): (
      fetch?: FetchAPI,
      basePath?: string
    ) => Promise<ResultDtoOfResultDataRemediationDto> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).designAspectApplyDataRemediation(body, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },

    /**
     *
     * @param {DesignAspectDtoCreate} body
     * @param {boolean} [forced]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectCreate(
      body: DesignAspectDtoCreate,
      forced?: boolean,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).designAspectCreate(body, forced, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },

    /**
     *
     * @param {any} body
     * @param {boolean} [forced]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectReset(
      id: any,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).designAspectReset(id, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectDelete(
      id?: number,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).designAspectDelete(id, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {boolean} [onlyPlannedActivities]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectDeleteDeep(
      id?: number,
      onlyPlannedActivities?: boolean,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).designAspectDeleteDeep(id, onlyPlannedActivities, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {DesignAspectQueryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectExportReport(
      body: DesignAspectQueryDto,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ReturnFile> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).designAspectExportReport(body, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return {
              File: response.blob(),
              FileName: response.headers.get("Content-Disposition"),
            } as ReturnFile;
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetCreateResourceDesignAspect(
      dcfId?: string,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<DesignAspectDtoCreate> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).designAspectGetCreateResourceDesignAspect(dcfId!, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDCFNAme(
      dcfId?: string,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<string> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).getDCFName(dcfId!, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getLinkSubnetworkWithSupportedService(
      dcfId?: string,
      supportedServiceId?: string,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<string> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).getLinkSubnetworkWithSupportedService(
        dcfId!,
        supportedServiceId!,
        options
      );
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    getUpdateDAMigration(
      paId: number,
      dcId: number,
      targetDcfId: number,
      options: any = {}
    ): (fetch?: FetchAPI, basePath?: string) => Promise<string> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).getUpdateDAMigration(paId, dcId, targetDcfId, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getLinkNetworkFunction(
      dcfId?: string,
      networkFunctionId?: string,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<string> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).getLinkNetworkFunction(dcfId!, networkFunctionId!, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {DesignAspectQueryDto} body
     * @param {string} [propertyName]
     * @param {string} [propertyFilter]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetFilterResult(
      body: DesignAspectQueryDto,
      propertyName?: string,
      propertyFilter?: string,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<Array<FilterValueDto>> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).designAspectGetFilterResult(
        body,
        propertyName,
        propertyFilter,
        options
      );
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {DesignAspectQueryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetDesignAspect(
      body: DesignAspectQueryDto,
      options?: any
    ): (
      fetch?: FetchAPI,
      basePath?: string
    ) => Promise<QueryResultDtoOfDesignAspectDtoGrid> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).designAspectGetDesignAspect(body, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetRelatedRecords(
      id: number,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).designAspectGetRelatedRecords(id, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetUpdateResourceDesignAspect(
      id: number,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<DesignAspectDtoUpdate> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).designAspectGetUpdateResourceDesignAspect(id, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {number} [designComponentFamilyId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectServicesAndNetworks(
      designComponentFamilyId?: number,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).designAspectServicesAndNetworks(designComponentFamilyId, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },

    /**
     *
     * @param {number} [opCoId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetDesginComponentFamily(
      opcoId?: number,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).designAspectGetDesginComponentFamily(opcoId, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {DesignAspectDtoUpdate} body
     * @param {boolean} [forced]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectPut(
      body: DesignAspectDtoUpdate,
      forced?: boolean,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).designAspectPut(body, forced, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectRestore(
      id?: number,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = DesignAspectApiFetchParamCreator(
        configuration
      ).designAspectRestore(id, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
  };
};

/**
 * DesignAspectApi - factory interface
 * @export
 */
export const DesignAspectApiFactory = function (
  configuration?: Configuration,
  fetch?: FetchAPI,
  basePath?: string
) {
  return {
    /**
     *
     * @param {DataRemediationDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectApplyDataRemediation(body: DataRemediationDto, options?: any) {
      return DesignAspectApiFp(configuration).designAspectApplyDataRemediation(
        body,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {DesignAspectDtoCreate} body
     * @param {boolean} [forced]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectCreate(
      body: DesignAspectDtoCreate,
      forced?: boolean,
      options?: any
    ) {
      return DesignAspectApiFp(configuration).designAspectCreate(
        body,
        forced,
        options
      )(fetch, basePath);
    },

    /**
     *
     * @param {any} body
     * @param {boolean} [forced]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectReset(id: any, options?: any) {
      return DesignAspectApiFp(configuration).designAspectReset(id, options)(
        fetch,
        basePath
      );
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectDelete(id?: number, options?: any) {
      return DesignAspectApiFp(configuration).designAspectDelete(id, options)(
        fetch,
        basePath
      );
    },
    /**
     *
     * @param {number} [id]
     * @param {boolean} [onlyPlannedActivities]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectDeleteDeep(
      id?: number,
      onlyPlannedActivities?: boolean,
      options?: any
    ) {
      return DesignAspectApiFp(configuration).designAspectDeleteDeep(
        id,
        onlyPlannedActivities,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {DesignAspectQueryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectExportReport(body: DesignAspectQueryDto, options?: any) {
      return DesignAspectApiFp(configuration).designAspectExportReport(
        body,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetCreateResourceDesignAspect(dcfId?: string, options?: any) {
      return DesignAspectApiFp(
        configuration
      ).designAspectGetCreateResourceDesignAspect(dcfId, options)(
        fetch,
        basePath
      );
    },

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDCFName(dcfId?: string, options?: any) {
      return DesignAspectApiFp(configuration).getDCFNAme(dcfId, options)(
        fetch,
        basePath
      );
    },

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getLinkSubnetworkWithSupportedService(
      dcfId?: string,
      supportedServiceId?: string,
      options?: any
    ) {
      return DesignAspectApiFp(
        configuration
      ).getLinkSubnetworkWithSupportedService(
        dcfId,
        supportedServiceId,
        options
      )(fetch, basePath);
    },
    getUpdateDAMigration(
      paId: number,
      dcId: number,
      targetDcfId: number,
      options: any = {}
    ) {
      return DesignAspectApiFp(configuration).getUpdateDAMigration(
        paId,
        dcId,
        targetDcfId,
        options
      )(fetch, basePath);
    },

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getLinkNetworkFunction(
      dcfId?: string,
      networkFunctionId?: string,
      options?: any
    ) {
      return DesignAspectApiFp(configuration).getLinkNetworkFunction(
        dcfId,
        networkFunctionId,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {DesignAspectQueryDto} body
     * @param {string} [propertyName]
     * @param {string} [propertyFilter]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetFilterResult(
      body: DesignAspectQueryDto,
      propertyName?: string,
      propertyFilter?: string,
      options?: any
    ) {
      return DesignAspectApiFp(configuration).designAspectGetFilterResult(
        body,
        propertyName,
        propertyFilter,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {DesignAspectQueryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetDesignAspect(body: DesignAspectQueryDto, options?: any) {
      return DesignAspectApiFp(configuration).designAspectGetDesignAspect(
        body,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetRelatedRecords(id: number, options?: any) {
      return DesignAspectApiFp(configuration).designAspectGetRelatedRecords(
        id,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetUpdateResourceDesignAspect(id: number, options?: any) {
      return DesignAspectApiFp(
        configuration
      ).designAspectGetUpdateResourceDesignAspect(id, options)(fetch, basePath);
    },
    /**
     *
     * @param {number} [designComponentFamilyId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectServicesAndNetworks(
      designComponentFamilyId?: number,
      options?: any
    ) {
      return DesignAspectApiFp(configuration).designAspectServicesAndNetworks(
        designComponentFamilyId,
        options
      )(fetch, basePath);
    },

    /**
     *
     * @param {number} [opCoId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectGetDesginComponentFamily(opcoId?: number, options?: any) {
      return DesignAspectApiFp(
        configuration
      ).designAspectGetDesginComponentFamily(opcoId, options)(fetch, basePath);
    },
    /**
     *
     * @param {DesignAspectDtoUpdate} body
     * @param {boolean} [forced]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectPut(
      body: DesignAspectDtoUpdate,
      forced?: boolean,
      options?: any
    ) {
      return DesignAspectApiFp(configuration).designAspectPut(
        body,
        forced,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    designAspectRestore(id?: number, options?: any) {
      return DesignAspectApiFp(configuration).designAspectRestore(id, options)(
        fetch,
        basePath
      );
    },
  };
};

/**
 * DesignAspectApi - object-oriented interface
 * @export
 * @class DesignAspectApi
 * @extends {BaseAPI}
 */
export class DesignAspectApi extends BaseAPI {
  /**
   *
   * @param {DataRemediationDto} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public designAspectApplyDataRemediation(
    body: DataRemediationDto,
    options?: any
  ) {
    return DesignAspectApiFp(
      this.configuration
    ).designAspectApplyDataRemediation(body, options)(
      this.fetch,
      this.basePath
    );
  }

  /**
   *
   * @param {DesignAspectDtoCreate} body
   * @param {boolean} [forced]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public designAspectCreate(
    body: DesignAspectDtoCreate,
    forced?: boolean,
    options?: any
  ) {
    return DesignAspectApiFp(this.configuration).designAspectCreate(
      body,
      forced,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {any} body
   * @param {boolean} [forced]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public designAspectReset(id: any, options?: any) {
    return DesignAspectApiFp(this.configuration).designAspectReset(id, options)(
      this.fetch,
      this.basePath
    );
  }

  /**
   *
   * @param {number} [id]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public designAspectDelete(id?: number, options?: any) {
    return DesignAspectApiFp(this.configuration).designAspectDelete(
      id,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {number} [id]
   * @param {boolean} [onlyPlannedActivities]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public designAspectDeleteDeep(
    id?: number,
    onlyPlannedActivities?: boolean,
    options?: any
  ) {
    return DesignAspectApiFp(this.configuration).designAspectDeleteDeep(
      id,
      onlyPlannedActivities,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {DesignAspectQueryDto} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public designAspectExportReport(body: DesignAspectQueryDto, options?: any) {
    return DesignAspectApiFp(this.configuration).designAspectExportReport(
      body,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public designAspectGetCreateResourceDesignAspect(
    dcfId?: string,
    options?: any
  ) {
    return DesignAspectApiFp(
      this.configuration
    ).designAspectGetCreateResourceDesignAspect(dcfId, options)(
      this.fetch,
      this.basePath
    );
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public getDCFName(dcfId?: string, options?: any) {
    return DesignAspectApiFp(this.configuration).getDCFNAme(dcfId, options)(
      this.fetch,
      this.basePath
    );
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public getLinkSubnetworkWithSupportedService(
    dcfId?: string,
    supportedServiceId?: string,
    options?: any
  ) {
    return DesignAspectApiFp(
      this.configuration
    ).getLinkSubnetworkWithSupportedService(
      dcfId,
      supportedServiceId,
      options
    )(this.fetch, this.basePath);
  }

  public getUpdateDAMigration(
    paId: number,
    dcId: number,
    targetDcfId: number,
    options: any = {}
  ) {
    return DesignAspectApiFp(this.configuration).getUpdateDAMigration(
      paId,
      dcId,
      targetDcfId,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public getLinkNetworkFunction(
    dcfId?: string,
    networkFunctionId?: string,
    options?: any
  ) {
    return DesignAspectApiFp(this.configuration).getLinkNetworkFunction(
      dcfId,
      networkFunctionId,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {DesignAspectQueryDto} body
   * @param {string} [propertyName]
   * @param {string} [propertyFilter]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public designAspectGetFilterResult(
    body: DesignAspectQueryDto,
    propertyName?: string,
    propertyFilter?: string,
    options?: any
  ) {
    return DesignAspectApiFp(this.configuration).designAspectGetFilterResult(
      body,
      propertyName,
      propertyFilter,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {DesignAspectQueryDto} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public designAspectGetDesignAspect(
    body: DesignAspectQueryDto,
    options?: any
  ) {
    return DesignAspectApiFp(this.configuration).designAspectGetDesignAspect(
      body,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {number} id
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public designAspectGetRelatedRecords(id: number, options?: any) {
    return DesignAspectApiFp(this.configuration).designAspectGetRelatedRecords(
      id,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {number} id
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public designAspectGetUpdateResourceDesignAspect(id: number, options?: any) {
    return DesignAspectApiFp(
      this.configuration
    ).designAspectGetUpdateResourceDesignAspect(id, options)(
      this.fetch,
      this.basePath
    );
  }

  /**
   *
   * @param {number} [designComponentFamilyId]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public designAspectServicesAndNetworks(
    designComponentFamilyId?: number,
    options?: any
  ) {
    return DesignAspectApiFp(
      this.configuration
    ).designAspectServicesAndNetworks(designComponentFamilyId, options)(
      this.fetch,
      this.basePath
    );
  }

  /**
   *
   * @param {number} [opCoId]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public designAspectGetDesginComponentFamily(opcoId?: number, options?: any) {
    return DesignAspectApiFp(
      this.configuration
    ).designAspectGetDesginComponentFamily(opcoId, options)(
      this.fetch,
      this.basePath
    );
  }

  /**
   *
   * @param {DesignAspectDtoUpdate} body
   * @param {boolean} [forced]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public designAspectPut(
    body: DesignAspectDtoUpdate,
    forced?: boolean,
    options?: any
  ) {
    return DesignAspectApiFp(this.configuration).designAspectPut(
      body,
      forced,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {number} [id]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DesignAspectApi
   */
  public designAspectRestore(id?: number, options?: any) {
    return DesignAspectApiFp(this.configuration).designAspectRestore(
      id,
      options
    )(this.fetch, this.basePath);
  }
}
