ALTER TABLE "COMPONENTSOFTWAREBUILDS" ADD "PRODUCTNAMEID" NUMBER(20,0);
ALTER TABLE "COMPONENTSOFTWAREBUILDS" ADD "ORGEQPMANUFACTURERID" NUMBER(5,0);

ALTER TABLE "COMPONENTSOFTWAREBUILDS" ADD CONSTRAINT "FK_COMPONENTSOFTWAREBUILDS_PRODUCTNAME_PRODUCTNAMEID" FOREIGN KEY ("PRODUCTNAMEID") REFERENCES "PRODUCTNAME" ("PRODUCTNAMEID") ENABLE;
ALTER TABLE "COMPONENTSOFTWAREBUILDS" ADD CONSTRAINT "FK_COMPONENTSOFTWAREBUILDS_ORIGINALEQUIPMENTMANUFACTURERS_ORIGINALEQUIPMENTMANUFACTURERID" FOREIGN KEY ("ORGEQPMANUFACTURERID") REFERENCES "ORIGINALEQUIPMENTMANUFACTURERS" ("ORGEQPMANUFACTURERID") ENABLE;

ALTER TABLE "COMPONENTSOFTWAREBUILDS" DROP CONSTRAINT "FK_COMPONENTMANUFACTURERS_COMPONENTMANUFACTURERS_COMPONENTMANUFACTURERID";
ALTER TABLE "COMPONENTSOFTWAREBUILDS" DROP COLUMN "COMPONENTMANUFACTURERID";

COMMIT;
