
--------------------------------DML SCRIPT REMOVE ENTRY IN  AUDITTABLESANDCOLUMNS 
 

DROP SEQUENCE  "CNFCAPACITY_SQE";
DROP TABLE CNFCAPACITY; 

DROP SEQUENCE  "CNFCLUSTERINFO_SQE";
DROP TABLE CNFCLUSTERINFO;

DROP SEQUENCE  "CNFINFO_SQE";
DROP TABLE CNFINFO; 

DROP SEQUENCE  "CNFNAME_SQE";
DROP TABLE CNFNAME;   
  
DROP SEQUENCE  "CNFCLUSTER_SQE";
DROP TABLE CNFCLUSTER;  
 
DROP SEQUENCE  "PODTYPEINFO_SQE";
DROP TABLE PODTYPEINFO;

DROP SEQUENCE  "FUNCTIONSTANDARDNAME_SQE";
DROP TABLE FUNCTIONSTANDARDNAME;  