ALTER TABLE "DCFLIFECYCLE" DROP CONSTRAINT "FK_DCFLIFECYCLE_DESIGNCOMPONENTFAMILIES_DESIGNCOMPONENTFAMILYID";
ALTER TABLE "DCFLIFECYCLE" DROP CONSTRAINT "FK_DCFLIFECYCLE_DESIGNCOMPONENTS_DESIGNCOMPONENTID";
ALTER TABLE "DCFLIFECYCLE" DROP CONSTRAINT "FK_DCFLIFECYCLE_LCMENGINEERING_OPCOS_OPCOID";


