------------------------------------RB SCRIPTS -----------------
ALTER TABLE "BUILDBAGS" DROP COLUMN "VISIBLEFLAG";

------------------------------------RB SCRIPTS FOR ASSETPASSTHROUGH-----------------
ALTER TABLE "ASSETPASSTHROUGH" DROP CONSTRAINT "FK_PASSTHROUGH_PASSTHROUGHLCM_VODAFONEUNIQUEIDENTIFIER";

ALTER TABLE "ASSETPASSTHROUGH" ADD CONSTRAINT "FK_PASSTHROUGH_PASSTHROUGHLCM_VODAFONEUNIQUEIDENTIFIER" FOREIGN KEY ("VODAFONEUNIQUEIDENTIFIER") REFERENCES "ASSETPASSTHROUGH" ("REPORTID") ENABLE;

ALTER TABLE "ASSETPASSTHROUGH" RENAME CONSTRAINT "FK_ASSETPASSTHROUGH_ASPNETUSERS_CREATIONUSER" TO "FK_PASSTHROUGH_ASPNETUSERS_CREATIONUSER";
ALTER TABLE "ASSETPASSTHROUGH" RENAME CONSTRAINT "FK_ASSETPASSTHROUGH_ASPNETUSERS_MODIFICATIONUSER" TO "FK_PASSTHROUGH_ASPNETUSERS_MODIFICATIONUSER";
ALTER TABLE "ASSETPASSTHROUGH" RENAME CONSTRAINT "FK_ASSETPASSTHROUGH_VERTICALRESPONSIBLES_NONTEMSVERTICAL" TO "FK_PASSTHROUGH_VERTICALRESPONSIBLES_NONTEMSVERTICAL";

RENAME  "ASSETPASSTHROUGH_SEQ" TO "PASSTHROUGH_SEQ" ;
ALTER TABLE "ASSETPASSTHROUGH" RENAME TO "PASSTHROUGH";
ALTER TABLE "ASSETPASSTHROUGH" MODIFY PASSTHROUGHID DEFAULT "PASSTHROUGH_SEQ"."NEXTVAL";

------------------------------------RB SCRIPTS FOR SWPASSTHROUGHLCM-----------------

ALTER TABLE "SWPASSTHROUGHLCM" ADD "HWOPERATIONSCONTACTPOINT" NVARCHAR2(200);
ALTER TABLE "SWPASSTHROUGHLCM" ADD "HWVENDOR" NVARCHAR2(200);
ALTER TABLE "SWPASSTHROUGHLCM" ADD "HWOPERATIONSMAINTENANCECONTRACT" NVARCHAR2(200);
ALTER TABLE "SWPASSTHROUGHLCM" ADD "HWVENDORENDOFMAINTENANCEDATE" NVARCHAR2(200);
ALTER TABLE "SWPASSTHROUGHLCM" ADD "PLANNEDHWMODEL" NVARCHAR2(200);
ALTER TABLE "SWPASSTHROUGHLCM" ADD "HWOPSMAINTENANCECONTRACTENDDATE" NVARCHAR2(200);
ALTER TABLE "SWPASSTHROUGHLCM" ADD "LCMSTATUSENGHARDWARE" NVARCHAR2(200);
ALTER TABLE "SWPASSTHROUGHLCM" ADD "LCMSTATUSOPSHARDWARE" NVARCHAR2(200);

ALTER TABLE "SWPASSTHROUGHLCM" DROP CONSTRAINT "SWPASSTHROUGHLCM_SWRESOURCEKEY";
ALTER TABLE "SWPASSTHROUGHLCM" DROP COLUMN "SWRESOURCEKEY";

ALTER TABLE "SWPASSTHROUGHLCM" RENAME CONSTRAINT "FK_SWPASSTHROUGHLCM_ASPNETUSERS_CREATIONUSER" TO "FK_PASSTHROUGHLCM_ASPNETUSERS_CREATIONUSER";
ALTER TABLE "SWPASSTHROUGHLCM" RENAME CONSTRAINT "FK_SWPASSTHROUGHLCM_ASPNETUSERS_MODIFICATIONUSE" TO "FK_PASSTHROUGHLCM_ASPNETUSERS_MODIFICATIONUSER";
ALTER TABLE "SWPASSTHROUGHLCM" RENAME CONSTRAINT "FK_SWPASSTHROUGHLCM_VERTICALRESPONSIBLES_NONTEMSVERTICAL" TO "FK_PASSTHROUGHLCM_VERTICALRESPONSIBLES_NONTEMSVERTICAL";

RENAME "SWPASSTHROUGHLCM_SEQ" TO "PASSTHROUGHLCM_SEQ";

ALTER TABLE "SWPASSTHROUGHLCM" RENAME TO "PASSTHROUGHLCM";

ALTER TABLE "SWPASSTHROUGHLCM" MODIFY PASSTHROUGHLCMID DEFAULT "PASSTHROUGHLCM_SEQ"."NEXTVAL";
