Alter table plannedactivityresources
Add  "DESIGNASPECTLABELSOFTWARE" NVARCHAR2(2000) NULL;


Alter table plannedactivityresources
Add  "DESIGNASPECTLABELHARDWARE" NVARCHAR2(2000) NULL;


Alter table plannedactivityresources
Add  "FORDESIGNASPECT" NUMBER(1,0) NULL ;


Alter table plannedactivityresources
Add  "ACTIVITYDETAILSDESIGNASPECT" NVARCHAR2(2000) NULL;


Alter table plannedactivityresources
Add  "DESIGNASPECTSOFTWARE" NUMBER(1,0) NULL ;

Alter table plannedactivityresources
Add  "DESIGNASPECTHARDWARE" NUMBER(1,0) NULL ;

Alter table plannedactivityresources
Add  "DESIGNASPECTSOFTWARE" NUMBER(1,0) NULL ;

Alter table plannedactivityresources
Add  "DESIGNASPECTHARDWARE" NUMBER(1,0) NULL ;


Alter table plannedactivityresources
Add  "RULEDESIGNASPECT" NUMBER(10,0) NULL ;


Alter table PLANNEDACTIVITYRESOURCES
Add  "DESIGNASPECTEXPORTABLE"  NUMBER(1,0) DEFAULT (0) NOT NULL ENABLE ;


Alter table PLANNEDACTIVITYRESOURCEBENEFIT
Add  "FORDESIGNASPECT" NUMBER(1,0) NULL ;

Alter table PLANNEDACTIVITYRESOURCEDRIVER
Add  "FORDESIGNASPECT" NUMBER(1,0) NULL ;

Alter table PLANNEDACTIVITYRESOURCEPLANNINGRISK
Add  "FORDESIGNASPECT" NUMBER(1,0) NULL ;


Alter table PLANNEDACTIVITIES
Add "DESIGNASPECTID"  NUMBER(19,0) NULL ;


ALTER TABLE "CAMSDBUSER"."PLANNEDACTIVITIES" ADD CONSTRAINT "FK_PLANNEDACTIVITIES_DESIGNASPECTS_ID" FOREIGN KEY ("DESIGNASPECTID")
REFERENCES "CAMSDBUSER"."DESIGNASPECTS" ("ID") ENABLE;


Alter table PLANNEDACTIVITIES
Add "DESIGNCOMPONENTFAMILYID"  NUMBER(19,0) NULL ;


ALTER TABLE "CAMSDBUSER"."PLANNEDACTIVITIES" ADD CONSTRAINT "FK_PLANNEDACTIVITIES_DESIGNCOMPONENTFAMILY_ID" FOREIGN KEY ("DESIGNCOMPONENTFAMILYID")
REFERENCES "CAMSDBUSER"."DESIGNCOMPONENTFAMILIES" ("DESIGNCOMPONENTFAMILYID") ENABLE;
