alter table DESIGNCOMPONENTS RENAME column SERVICEBOUNDARYID to SUBNETWORKBOUNDARYID;

update designcomponents set subnetworkboundaryid =232 where subnetworkboundaryid =0;
 
commit;

ALTER TABLE "CAMSDBUSER"."DESIGNCOMPONENTS" ADD CONSTRAINT "FK_DESIGNCOMPONENTS_SUBNETWORKBOUNDARIES_ID" FOREIGN KEY ("SUBNETWORKBOUNDARYID")
	  REFERENCES "CAMSDBUSER"."SUBNETWORKBOUNDARIES" ("ID") ENABLE;

cOMMIT;