
CREATE SEQUENCE DESIGNCOMPONENTFAMILYNETWORKFUNCTION_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
--------------------------------------------------------
--  DDL for Table DESIGNCOMPONENTFAMILYNETWORKFUNCTION
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Table DESIGNCOMPONENTFAMILYNETWORKFUNCTION
--------------------------------------------------------

  CREATE TABLE "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION" 
   (	"ID" NUMBER(19,0) DEFAULT "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION_SEQ"."NEXTVAL", 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DESIGNCOMPONENTFAMILYID" NUMBER(19,0), 
	"NETWORKFUNCTIONID" NUMBER(10,0), 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index DESIGNCOMPONENTFAMILYNETWORKFUNCTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION_PK" ON "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table DESIGNCOMPONENTFAMILYNETWORKFUNCTION
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION" ADD CONSTRAINT "DESIGNCOMPONENTFAMILYNETWORKFUNCTION_PK" PRIMARY KEY ("ID")
  USING INDEX "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION_PK"  ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION" MODIFY ("DELETED" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DESIGNCOMPONENTFAMILYNETWORKFUNCTION
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION" ADD CONSTRAINT "FK_DESIGNCOMPONENTFAMILYNETWORKFUNCTION_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION" ADD CONSTRAINT "FK_DESIGNCOMPONENTFAMILYNETWORKFUNCTION_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION" ADD CONSTRAINT "DESIGNCOMPONENTFAMILYNETWORKFUNCTION_FK1" FOREIGN KEY ("DESIGNCOMPONENTFAMILYID")
	  REFERENCES "CAMSDBUSER"."DESIGNCOMPONENTFAMILIES" ("DESIGNCOMPONENTFAMILYID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION" ADD CONSTRAINT "DESIGNCOMPONENTFAMILYNETWORKFUNCTION_FK2" FOREIGN KEY ("NETWORKFUNCTIONID")
	  REFERENCES "CAMSDBUSER"."NETWORKFUNCTIONS" ("ID") ENABLE;


ALTER TABLE CAMSDBUSER.DESIGNCOMPONENTFAMILYNETWORKFUNCTION
MODIFY(ID  DEFAULT "CAMSDBUSER"."DESIGNCOMPONENTFAMILYNETWORKFUNCTION_SEQ"."NEXTVAL");