alter table DESIGNCOMPONENTFAMILIES RENAME column SERVICEBOUNDARYID to SUBNETWORKBOUNDARYID;
alter table DESIGNCOMPONENTFAMILIES RENAME column IMPLEMENTATION to LCMPOLICY;
ALTER TABLE DESIGNCOMPONENTFAMILIES MODIFY ( LCMPOLICY NUMBER(5,0));
ALTER TABLE DESIGNCOMPONENTFAMILIES Add "IMPLEMENTATION" Number(1,0) DEFAULT (0) NOT NULL ENABLE ;

ALTER TABLE DESIGNCOMPONENTFAMILIES 
Add "CRITICALITYRATING" Number(10,0)  NULL  ;

ALTER TABLE DESIGNCOMPONENTFAMILIES
Add "GDPRCLASSIFICATION" Number(10,0)  NULL  ;


ALTER TABLE DESIGNCOMPONENTFAMILIES
Add "PCI/SOX" Number(1,0) DEFAULT (0) NOT NULL ENABLE  ;

ALTER TABLE DESIGNCOMPONENTFAMILIES
Add "C3/C4" Number(1,0) DEFAULT (0) NOT NULL ENABLE ;


ALTER TABLE DESIGNCOMPONENTFAMILIES
Add "MISSIONCRITICAL" Number(1,0) DEFAULT (0) NOT NULL ENABLE ;


ALTER TABLE DESIGNCOMPONENTFAMILIES
Add "SECURITYELEMENT" Number(1,0) DEFAULT (0) NOT NULL ENABLE ;


ALTER TABLE DESIGNCOMPONENTFAMILIES
Add "COUNTRYSPECIFICCRITICALITY" Number(1,0) DEFAULT (0) NOT NULL ENABLE ;


ALTER TABLE DESIGNCOMPONENTFAMILIES 
Add "CRITICALASSETTYPEID" Number(10,0)  NULL  ;


ALTER TABLE "CAMSDBUSER"."DESIGNCOMPONENTFAMILIES" ADD CONSTRAINT "FK_DESIGNCOMPONENTFAMILIES_CRITICALASSETTYPES_ID" FOREIGN KEY ("CRITICALASSETTYPEID")
REFERENCES "CAMSDBUSER"."CRITICALASSETTYPES" ("ID") ENABLE;


ALTER TABLE DESIGNCOMPONENTFAMILIES
DROP CONSTRAINT FK_DESIGNCOMPONENTFAMILIES_SECURITYTIREZONE_SECURITYTIREZONEID;


alter table DESIGNCOMPONENTFAMILIES drop column SECURITYTIREZONEID;

alter table DESIGNCOMPONENTFAMILIES drop column CRITICALNATIONALINFRASTRUCTURE;

