
CREATE SEQUENCE DESIGNASPECTS_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
--------------------------------------------------------
--  DDL for Table DESIGNASPECTS
--------------------------------------------------------

  CREATE TABLE "CAMSDBUSER"."DESIGNASPECTS" 
   (	"ID" NUMBER(19,0) DEFAULT "CAMSDBUSER"."DESIGNASPECTS_SEQ"."NEXTVAL", 
	"DESIGNCOMPONENTFAMILYID" NUMBER(19,0), 
	"OPCOID" NUMBER(5,0), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"AUTHENICATIONTYPEID" NUMBER(10,0), 
	"SECURITYMANAGERID" NUMBER(10,0), 
	"LICENSEMODELID" NUMBER(10,0), 
	"THIRDPARTYACCESSID" NUMBER(10,0), 
	"SITERESILIENCEID" NUMBER(10,0), 
	"SWDELIVERYLIFECYCLEID" NUMBER(10,0),  
	"INSTANCERESILIENCEID" NUMBER(10,0), 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETIONDATE" TIMESTAMP (6), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"GEORESILIENCEID" NUMBER(10,0), 
	"CRITICALNATIONALINFRASTRUCTURE" NUMBER(1,0), 
	"SECURITYTIREZONEID" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index DESIGNASPECTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMSDBUSER"."DESIGNASPECTS_PK" ON "CAMSDBUSER"."DESIGNASPECTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table DESIGNASPECTS
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" ADD CONSTRAINT "DESIGNASPECTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CAMDB"  ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" MODIFY ("DESIGNCOMPONENTFAMILYID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" MODIFY ("CRITICALNATIONALINFRASTRUCTURE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DESIGNASPECTS
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" ADD CONSTRAINT "FK_DESIGNASPECTS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" ADD CONSTRAINT "FK_DESIGNASPECTS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" ADD CONSTRAINT "DESIGNASPECTS_AUTHENICATIONTYPE" FOREIGN KEY ("AUTHENICATIONTYPEID")
	  REFERENCES "CAMSDBUSER"."AUTHENICATIONTYPES" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" ADD CONSTRAINT "DESIGNASPECTS_INSTANCERESILIENCE" FOREIGN KEY ("INSTANCERESILIENCEID")
	  REFERENCES "CAMSDBUSER"."INSTANCERESILIENCE" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" ADD CONSTRAINT "DESIGNASPECTS_SITERESILIENCE" FOREIGN KEY ("SITERESILIENCEID")
	  REFERENCES "CAMSDBUSER"."SITERESILIENCE" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" ADD CONSTRAINT "DESIGNASPECTS_SWDELIVERYLIFECYCLE" FOREIGN KEY ("SWDELIVERYLIFECYCLEID")
	  REFERENCES "CAMSDBUSER"."SWDELIVERYLIFECYCLE" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" ADD CONSTRAINT "DESIGNASPECTS_DESIGNCOMPONENTFAMILIE" FOREIGN KEY ("DESIGNCOMPONENTFAMILYID")
	  REFERENCES "CAMSDBUSER"."DESIGNCOMPONENTFAMILIES" ("DESIGNCOMPONENTFAMILYID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" ADD CONSTRAINT "DESIGNASPECTS_LICENSEMODEL" FOREIGN KEY ("LICENSEMODELID")
	  REFERENCES "CAMSDBUSER"."LICENSEMODELS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" ADD CONSTRAINT "DESIGNASPECTS_OPCO" FOREIGN KEY ("OPCOID")
	  REFERENCES "CAMSDBUSER"."OPCOS" ("OPCOID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" ADD CONSTRAINT "DESIGNASPECTS_THIRDPARTYACCESSTYPE" FOREIGN KEY ("THIRDPARTYACCESSID")
	  REFERENCES "CAMSDBUSER"."THIRDPARTYACCESSTYPES" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" ADD CONSTRAINT "DESIGNASPECTS_SECURITYMANAGER" FOREIGN KEY ("SECURITYMANAGERID")
	  REFERENCES "CAMSDBUSER"."SECURITYMANAGER" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" ADD CONSTRAINT "DESIGNASPECTS_GEORESILIENCE" FOREIGN KEY ("GEORESILIENCEID")
	  REFERENCES "CAMSDBUSER"."GEORESILIENCE" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTS" ADD CONSTRAINT "DESIGNASPECTS_SECURITYTIREZONE" FOREIGN KEY ("SECURITYTIREZONEID")
	  REFERENCES "CAMSDBUSER"."SECURITYTIREZONE" ("SECURITYTIREZONEID") ENABLE;

        
ALTER TABLE CAMSDBUSER.DESIGNASPECTS
MODIFY(ID  DEFAULT "CAMSDBUSER"."DESIGNASPECTS_SEQ"."NEXTVAL");