CREATE SEQUENCE DESIGNASPECTSNETWORKFUNCTIONS_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DESIGNASPECTSNETWORKFUNCTIONS
--------------------------------------------------------

  CREATE TABLE "CAMSDBUSER"."DESIGNASPECTSNETWORKFUNCTIONS" 
   (	"ID" NUMBER(10,0) DEFAULT "CAMSDBUSER"."DESIGNASPECTSNETWORKFUNCTIONS_SEQ"."NEXTVAL", 
	"DESIGNASPECTID" NUMBER(19,0), 
	"NETWORKFUNCTIONID" NUMBER(10,0), 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index DESIGNASPECTSNETWORKFUNCTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMSDBUSER"."DESIGNASPECTSNETWORKFUNCTIONS_PK" ON "CAMSDBUSER"."DESIGNASPECTSNETWORKFUNCTIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table DESIGNASPECTSNETWORKFUNCTIONS
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSNETWORKFUNCTIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSNETWORKFUNCTIONS" MODIFY ("DESIGNASPECTID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSNETWORKFUNCTIONS" MODIFY ("NETWORKFUNCTIONID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSNETWORKFUNCTIONS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSNETWORKFUNCTIONS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSNETWORKFUNCTIONS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSNETWORKFUNCTIONS" ADD CONSTRAINT "DESIGNASPECTSNETWORKFUNCTIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DESIGNASPECTSNETWORKFUNCTIONS
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSNETWORKFUNCTIONS" ADD CONSTRAINT "DESIGNASPECTSNETWORKFUNCTIONS_NETWORKFUNCTION" FOREIGN KEY ("NETWORKFUNCTIONID")
	  REFERENCES "CAMSDBUSER"."NETWORKFUNCTIONS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSNETWORKFUNCTIONS" ADD CONSTRAINT "DESIGNASPECTSNETWORKFUNCTIONS_DESIGNASSPECT" FOREIGN KEY ("DESIGNASPECTID")
	  REFERENCES "CAMSDBUSER"."DESIGNASPECTS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSNETWORKFUNCTIONS" ADD CONSTRAINT "FK_DESIGNASPECTSNETWORKFUNCTIONS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSNETWORKFUNCTIONS" ADD CONSTRAINT "FK_DESIGNASPECTSNETWORKFUNCTIONS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;

 ALTER TABLE CAMSDBUSER.DESIGNASPECTSNETWORKFUNCTIONS
MODIFY(ID  DEFAULT "CAMSDBUSER"."DESIGNASPECTSNETWORKFUNCTIONS_SEQ"."NEXTVAL");
