CREATE SEQUENCE DESIGNASPECTSSUPPORTEDSVR_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL for Table SUBNETWORKSUPPORTEDSVR
--------------------------------------------------------

  CREATE TABLE "CAMSDBUSER"."DESIGNASPECTSSUPPORTEDSVR" 
   (	"ID" NUMBER(10,0) DEFAULT "CAMSDBUSER"."DESIGNASPECTSSUPPORTEDSVR_SEQ"."NEXTVAL", 
	"DESIGNASPECTID" NUMBER(19,0), 
	"SERVICEID" NUMBER(10,0), 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index DESIGNASPECT_SUPPORTEDSVR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMSDBUSER"."DESIGNASPECT_SUPPORTEDSVR_PK" ON "CAMSDBUSER"."DESIGNASPECTSSUPPORTEDSVR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table DESIGNASPECTSSUPPORTEDSVR
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSSUPPORTEDSVR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSSUPPORTEDSVR" MODIFY ("DESIGNASPECTID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSSUPPORTEDSVR" MODIFY ("SERVICEID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSSUPPORTEDSVR" ADD CONSTRAINT "DESIGNASPECT_SUPPORTEDSVR_PK" PRIMARY KEY ("ID")
  USING INDEX "CAMSDBUSER"."DESIGNASPECT_SUPPORTEDSVR_PK"  ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSSUPPORTEDSVR" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSSUPPORTEDSVR" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSSUPPORTEDSVR" MODIFY ("DELETED" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DESIGNASPECTSSUPPORTEDSVR
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSSUPPORTEDSVR" ADD CONSTRAINT "DESIGNASPECTSSUPPORTEDSVR_SUPPORTEDSERVICE" FOREIGN KEY ("SERVICEID")
	  REFERENCES "CAMSDBUSER"."SUPPORTEDSERVICES" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSSUPPORTEDSVR" ADD CONSTRAINT "DESIGNASPECTSSUPPORTEDSVR_DESIGNASSPECT" FOREIGN KEY ("DESIGNASPECTID")
	  REFERENCES "CAMSDBUSER"."DESIGNASPECTS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSSUPPORTEDSVR" ADD CONSTRAINT "FK_DESIGNASPECTSSUPPORTEDSVR_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."DESIGNASPECTSSUPPORTEDSVR" ADD CONSTRAINT "FK_DESIGNASPECTSSUPPORTEDSVR_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;
      
 ALTER TABLE CAMSDBUSER.DESIGNASPECTSSUPPORTEDSVR
MODIFY(ID  DEFAULT "CAMSDBUSER"."DESIGNASPECTSSUPPORTEDSVR_SEQ"."NEXTVAL");
