
RENAME SERVICEBOUNDARIES TO SUBNETWORKBOUNDARIES;

ALTER TABLE SUBNETWORKBOUNDARIES
Add "ALIAS" NVARCHAR2(2000) NULL ;

ALTER TABLE SUBNETWORKBOUNDARIES
Add "DEFAULT" Number(1,0) DEFAULT (0) NOT NULL ENABLE ;


alter table SUBNETWORKBOUNDARIES RENAME column SERVICEBOUNDARY to DESCRIPTION;

alter table SUBNETWORKBOUNDARIES RENAME column SERVICEBOUNDARYID to ID;

ALTER TABLE SUBNETWORKBOUNDARIES Add "ORDER" Number(10,0)  NULL  ;

Insert into SUBNETWORKBOUNDARIES (CREATIONUSER,MODIFICATIONUSER,DELETED,DELETIONDATE,DESCRIPTION,"DEFAULT",ALIAS,"ORDER") values (1,1,0,null,'Subnetwork0',1,'All Supported Services',0);

Commit;


