--------------------------------------------------------
--  File created - Wednesday-May-11-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMERWHEELS
--------------------------------------------------------

CREATE SEQUENCE THIRDPARTYACCESSTYPES_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

  CREATE TABLE "CAMSDBUSER"."THIRDPARTYACCESSTYPES" 
   (	"ID" NUMBER(10,0) DEFAULT "CAMSDBUSER"."THIRDPARTYACCESSTYPES_SEQ"."NEXTVAL", 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6), 
	"DESCRIPTION" NVARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index PK_THIRDPARTYACCESSTYPES
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMSDBUSER"."PK_THIRDPARTYACCESSTYPES" ON "CAMSDBUSER"."THIRDPARTYACCESSTYPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table THIRDPARTYACCESSTYPES
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."THIRDPARTYACCESSTYPES" ADD CONSTRAINT "PK_THIRDPARTYACCESSTYPES" PRIMARY KEY ("ID")
  USING INDEX "CAMSDBUSER"."PK_THIRDPARTYACCESSTYPES"  ENABLE;
  ALTER TABLE "CAMSDBUSER"."THIRDPARTYACCESSTYPES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."THIRDPARTYACCESSTYPES" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."THIRDPARTYACCESSTYPES" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."THIRDPARTYACCESSTYPES" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."THIRDPARTYACCESSTYPES" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."THIRDPARTYACCESSTYPES" MODIFY ("DELETED" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table THIRDPARTYACCESSTYPES
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."THIRDPARTYACCESSTYPES" ADD CONSTRAINT "FK_THIRDPARTYACCESSTYPES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."THIRDPARTYACCESSTYPES" ADD CONSTRAINT "FK_THIRDPARTYACCESSTYPES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;

ALTER TABLE CAMSDBUSER.THIRDPARTYACCESSTYPES
MODIFY(ID  DEFAULT "CAMSDBUSER"."THIRDPARTYACCESSTYPES_SEQ"."NEXTVAL");