CREATE SEQUENCE LCMOPERATIONALCONTRACTS_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

--------------------------------------------------------
--  DDL for Table LCMOPERATIONALCONTRACTS
--------------------------------------------------------

  CREATE TABLE "CAMSDBUSER"."LCMOPERATIONALCONTRACTS" 
   (	"ID" NUMBER(5,0) DEFAULT "CAMSDBUSER"."LCMOPERATIONALCONTRACTS_SEQ"."NEXTVAL", 
	"LCMID" NUMBER(19,0), 
	"OPERATIONALCONTRACTID" NUMBER(5,0), 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index LCMOPERATIONALCONTRACTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMSDBUSER"."LCMOPERATIONALCONTRACTS_PK" ON "CAMSDBUSER"."LCMOPERATIONALCONTRACTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table LCMOPERATIONALCONTRACTS
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."LCMOPERATIONALCONTRACTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."LCMOPERATIONALCONTRACTS" MODIFY ("LCMID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."LCMOPERATIONALCONTRACTS" MODIFY ("OPERATIONALCONTRACTID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."LCMOPERATIONALCONTRACTS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."LCMOPERATIONALCONTRACTS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."LCMOPERATIONALCONTRACTS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."LCMOPERATIONALCONTRACTS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."LCMOPERATIONALCONTRACTS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."LCMOPERATIONALCONTRACTS" ADD CONSTRAINT "LCMOPERATIONALCONTRACTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LCMOPERATIONALCONTRACTS
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."LCMOPERATIONALCONTRACTS" ADD CONSTRAINT "LCMOPERATIONALCONTRACTS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."LCMOPERATIONALCONTRACTS" ADD CONSTRAINT "LCMOPERATIONALCONTRACTS_OPERATIONCONTRACTID" FOREIGN KEY ("OPERATIONALCONTRACTID")
	  REFERENCES "CAMSDBUSER"."OPERATIONALCONTRACTS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."LCMOPERATIONALCONTRACTS" ADD CONSTRAINT "LCMOPERATIONALCONTRACTS_LCMID" FOREIGN KEY ("LCMID")
	  REFERENCES "CAMSDBUSER"."LCMENGINEERING" ("LCMENGINEERINGID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."LCMOPERATIONALCONTRACTS" ADD CONSTRAINT "LCMOPERATIONALCONTRACTS_MODIFIEDUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;


  ALTER TABLE CAMSDBUSER.LCMOPERATIONALCONTRACTS
MODIFY(ID  DEFAULT "CAMSDBUSER"."LCMOPERATIONALCONTRACTS_SEQ"."NEXTVAL");

commit;