CREATE SEQUENCE OPERATIONALCONTRACTS_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
  
 --------------------------------------------------------
--  DDL for Table OPERATIONALCONTRACTS
--------------------------------------------------------

  CREATE TABLE "CAMSDBUSER"."OPERATIONALCONTRACTS" 
   (	"ID" NUMBER(5,0) DEFAULT "CAMSDBUSER"."OPERATIONALCONTRACTS_SEQ"."NEXTVAL", 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index OPERATIONALCONTRACTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMSDBUSER"."OPERATIONALCONTRACTS_PK" ON "CAMSDBUSER"."OPERATIONALCONTRACTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table OPERATIONALCONTRACTS
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."OPERATIONALCONTRACTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."OPERATIONALCONTRACTS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."OPERATIONALCONTRACTS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."OPERATIONALCONTRACTS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."OPERATIONALCONTRACTS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."OPERATIONALCONTRACTS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."OPERATIONALCONTRACTS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."OPERATIONALCONTRACTS" ADD CONSTRAINT "OPERATIONALCONTRACTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OPERATIONALCONTRACTS
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."OPERATIONALCONTRACTS" ADD CONSTRAINT "OPERATIONALCONTRACTS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."OPERATIONALCONTRACTS" ADD CONSTRAINT "OPERATIONALCONTRACTS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;

 
        
ALTER TABLE CAMSDBUSER.OPERATIONALCONTRACTS
MODIFY(ID  DEFAULT "CAMSDBUSER"."OPERATIONALCONTRACTS_SEQ"."NEXTVAL");

commit;