------------ROLLBACK SCRIPT FOR LCMENGINEERING------------------

ALTER TABLE "LCMENGINEERING" DROP "BUILDBAGID";
ALTER TABLE "LCMENGINEERING" DROP CONSTRAINT "FK_LCMENGINEERING_BUILDBAGS_BUILDBAGID";

ALTER TABLE "NETWORKELEMENTSASPLANNED" DROP "BUILDBAGID";
ALTER TABLE "NETWORKELEMENTSASPLANNED" DROP CONSTRAINT "FK_NETWORKELEMENTSASPLANNED_BUILDBAGS_BUILDBAGID";

ALTER TABLE "PLANNEDACTIVITIES" DROP "BUILDBAGID";
ALTER TABLE "PLANNEDACTIVITIES" DROP CONSTRAINT "FK_PLANNEDACTIVITIES_BUILDBAGS_BUILDBAGID";

----------------------END-----------------------------