--------------------------------------------------------
--  DDL FOR TABLE COMPONENTSOFTWAREBUILDSID_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "COMPONENTSOFTWAREBUILDID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
COMMIT;
--------------------------------------------------------
--  DDL FOR TABLE COMPONENTSOFTWAREBUILDS
--------------------------------------------------------
 
  CREATE TABLE "COMPONENTSOFTWAREBUILDS" 
   (	
    "COMPONENTSOFTWAREBUILDID" NUMBER(19,0) DEFAULT "COMPONENTSOFTWAREBUILDID_SEQ"."NEXTVAL", 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC (SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC (SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6), 
	"ORGEQPMANUFACTURERID" NUMBER(5,0), 
	"SOFTWAREVERSION" NVARCHAR2(255), 
	"LASTTIMEBUYNEW" DATE, 
	"LASTTIMEBUYUPGRADES" DATE, 
	"LASTTIMEBUYEXPANSIONS" DATE, 
	"ENDOFMAINTENANCE" DATE, 
	"ENDOFSUPPORT" DATE, 
	"GENERAAVAILABLEDATE" DATE, 
	"DELIVERYMETHOD" NVARCHAR2(50), 
	"SPAREFIELDSJSON" NCLOB, 
	"OPERATINGSYSTEMID" NUMBER(5,0), 
	"VULNERABILITYSTATUS" NVARCHAR2(2000), 
	"EOMSTATUS" NUMBER(5,0) DEFAULT 0, 
	"PRODUCTNAMEID" NUMBER(20,0), 
	"CRITICALASSETTYPEID" NUMBER(10,0), 
	"DESCRIPTION" NVARCHAR2(2000) DEFAULT (NULL)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" 
  LOB ("SPAREFIELDSJSON") STORE AS SECUREFILE (
  TABLESPACE "CAMDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL FOR INDEX PK_COMPONENTSOFTWAREBUILDS
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_COMPONENTSOFTWAREBUILDS" ON "COMPONENTSOFTWAREBUILDS" ("COMPONENTSOFTWAREBUILDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;

--------------------------------------------------------
--  CONSTRAINTS FOR TABLE COMPONENTSOFTWAREBUILDS
--------------------------------------------------------
 
  ALTER TABLE "COMPONENTSOFTWAREBUILDS" ADD CONSTRAINT "PK_COMPONENTSOFTWAREBUILDS" PRIMARY KEY ("COMPONENTSOFTWAREBUILDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;
  ALTER TABLE "COMPONENTSOFTWAREBUILDS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "COMPONENTSOFTWAREBUILDS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "COMPONENTSOFTWAREBUILDS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "COMPONENTSOFTWAREBUILDS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "COMPONENTSOFTWAREBUILDS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "COMPONENTSOFTWAREBUILDS" MODIFY ("ORGEQPMANUFACTURERID" NOT NULL ENABLE);
  ALTER TABLE "COMPONENTSOFTWAREBUILDS" MODIFY ("SOFTWAREVERSION" NOT NULL ENABLE);
  ALTER TABLE "COMPONENTSOFTWAREBUILDS" MODIFY ("EOMSTATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE COMPONENTSOFTWAREBUILDS
--------------------------------------------------------
 
  ALTER TABLE "COMPONENTSOFTWAREBUILDS" ADD CONSTRAINT "FK_COMPONENTSOFTWAREBUILDS_OPERATINGSYSTEMS_OPERATINGSYSTEMID" FOREIGN KEY ("OPERATINGSYSTEMID") REFERENCES "OPERATINGSYSTEMS" ("OPERATINGSYSTEMID") ENABLE;
  ALTER TABLE "COMPONENTSOFTWAREBUILDS" ADD CONSTRAINT "FK_COMPONENTSOFTWAREBUILDS_CRITICALASSETTYPES_ID" FOREIGN KEY ("CRITICALASSETTYPEID") REFERENCES "CRITICALASSETTYPES" ("ID") ENABLE;
  ALTER TABLE "COMPONENTSOFTWAREBUILDS" ADD CONSTRAINT "FK_COMPONENTSOFTWAREBUILDS_ORIGINALEQUIPMENTMANUFACTURERS_ORIGINALEQUIPMENTMANUFACTURERID" FOREIGN KEY ("ORGEQPMANUFACTURERID") REFERENCES "ORIGINALEQUIPMENTMANUFACTURERS" ("ORGEQPMANUFACTURERID") ENABLE;
  ALTER TABLE "COMPONENTSOFTWAREBUILDS" ADD CONSTRAINT "FK_COMPONENTSOFTWAREBUILDS_PRODUCTNAME_PRODUCTNAMEID" FOREIGN KEY ("PRODUCTNAMEID") REFERENCES "PRODUCTNAME" ("PRODUCTNAMEID") ENABLE;
  ALTER TABLE "COMPONENTSOFTWAREBUILDS" ADD CONSTRAINT "FK_COMPONENTSOFTWAREBUILDS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "COMPONENTSOFTWAREBUILDS" ADD CONSTRAINT "FK_COMPONENTSOFTWAREBUILDS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  
  COMMIT;