--------------------------------------------------------
--  DDL FOR SEQUENCE COMPONENTSOFTWAREBUILDSDESIGNCONTACTID_SEQ
--------------------------------------------------------
 
   CREATE SEQUENCE  "COMPONENTSOFTWAREBUILDSDESIGNCONTACTID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
   COMMIT;

--------------------------------------------------------
--  DDL FOR TABLE COMPONENTSOFTWAREBUILDSDESIGNCONTACTS
--------------------------------------------------------
 
  CREATE TABLE "COMPONENTSOFTWAREBUILDSDESIGNCONTACTS" 
   (	
    "COMPONENTSOFTWAREBUILDSDESIGNCONTACTID" NUMBER(19,0) DEFAULT "COMPONENTSOFTWAREBUILDSDESIGNCONTACTID_SEQ"."NEXTVAL", 
	"DESIGNCONTACTID" NUMBER(10,0), 
	"COMPONENTSOFTWAREBUILDID" NUMBER(19,0), 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_COMPONENTSOFTWAREBUILDSDESIGNCONTACTS
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_COMPONENTSOFTWAREBUILDSDESIGNCONTACTS" ON "COMPONENTSOFTWAREBUILDSDESIGNCONTACTS" ("COMPONENTSOFTWAREBUILDSDESIGNCONTACTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE COMPONENTSOFTWAREBUILDSDESIGNCONTACTS
--------------------------------------------------------
 
  ALTER TABLE "COMPONENTSOFTWAREBUILDSDESIGNCONTACTS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "COMPONENTSOFTWAREBUILDSDESIGNCONTACTS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "COMPONENTSOFTWAREBUILDSDESIGNCONTACTS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "COMPONENTSOFTWAREBUILDSDESIGNCONTACTS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "COMPONENTSOFTWAREBUILDSDESIGNCONTACTS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "COMPONENTSOFTWAREBUILDSDESIGNCONTACTS" MODIFY ("DESIGNCONTACTID" NOT NULL ENABLE);
  ALTER TABLE "COMPONENTSOFTWAREBUILDSDESIGNCONTACTS" MODIFY ("COMPONENTSOFTWAREBUILDID" NOT NULL ENABLE);
  ALTER TABLE "COMPONENTSOFTWAREBUILDSDESIGNCONTACTS" ADD CONSTRAINT "PK_COMPONENTSOFTWAREBUILDSDESIGNCONTACTS" PRIMARY KEY ("COMPONENTSOFTWAREBUILDSDESIGNCONTACTID") USING INDEX "PK_COMPONENTSOFTWAREBUILDSDESIGNCONTACTS"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE COMPONENTSOFTWAREBUILDSDESIGNCONTACTS
--------------------------------------------------------
 
  ALTER TABLE "COMPONENTSOFTWAREBUILDSDESIGNCONTACTS" ADD CONSTRAINT "FK_COMPONENTSOFTWAREBUILDSDESIGNCONTACTS_ASPNETUSERS_DESIGNCONTACTID" FOREIGN KEY ("DESIGNCONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "COMPONENTSOFTWAREBUILDSDESIGNCONTACTS" ADD CONSTRAINT "FK_COMPONENTSOFTWAREBUILDSDESIGNCONTACTS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "COMPONENTSOFTWAREBUILDSDESIGNCONTACTS" ADD CONSTRAINT "FK_COMPONENTSOFTWAREBUILDSDESIGNCONTACTS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "COMPONENTSOFTWAREBUILDSDESIGNCONTACTS" ADD CONSTRAINT "FK_COMPONENTSOFTWAREBUILDSDESIGNCONTACTS_COMPONENTSOFTWAREBUILDS_COMPONENTSOFTWAREBUILDID" FOREIGN KEY ("COMPONENTSOFTWAREBUILDID") REFERENCES "COMPONENTSOFTWAREBUILDS" ("COMPONENTSOFTWAREBUILDID") ENABLE;
  
  COMMIT;  
  