--------------------------------------------------------
--  DDL FOR SEQUENCE BUILDBAGID_SEQ
--------------------------------------------------------
 
   CREATE SEQUENCE  "BUILDBAGID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
   COMMIT;

--------------------------------------------------------
--  DDL FOR TABLE BUILDBAGS
--------------------------------------------------------
 
  CREATE TABLE "BUILDBAGS" 
   (	
    "BUILDBAGID" NUMBER(19,0) DEFAULT "BUILDBAGID_SEQ"."NEXTVAL", 
	"BAGDESCRIPTION" NVARCHAR2 (500) not null,
	"BAGVERSION" NVARCHAR2 (20) not null,	
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_BUILDBAGS
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_BUILDBAGS" ON "BUILDBAGS" ("BUILDBAGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE BUILDBAGS
--------------------------------------------------------
 
  ALTER TABLE "BUILDBAGS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "BUILDBAGS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "BUILDBAGS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "BUILDBAGS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "BUILDBAGS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "BUILDBAGS" ADD CONSTRAINT "PK_BUILDBAGS" PRIMARY KEY ("BUILDBAGID") USING INDEX "PK_BUILDBAGS"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE BUILDBAGS
-------------------------------------------------------- 
  ALTER TABLE "BUILDBAGS" ADD CONSTRAINT "FK_BUILDBAGS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "BUILDBAGS" ADD CONSTRAINT "FK_BUILDBAGS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  COMMIT;