--------------------------------DML SCRIPT FOR AUDITTABLESANDCOLUMNS (Componentsoftwarebuilds) ENTITY ------------------------------------

INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Componentsoftwarebuildid', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Creationuser', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Creationdate', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Modificationuser', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Modificationdate', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Deleted', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Deletiondate', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Orgeqpmanufacturerid', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Softwareversion', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Lasttimebuynew', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Lasttimebuyupgrades', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Lasttimebuyexpansions', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Endofmaintenance', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Endofsupport', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Generaavailabledate', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Deliverymethod', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Sparefieldsjson', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Operatingsystemid', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Vulnerabilitystatus', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Eomstatus', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Productnameid', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Criticalassettypeid', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Componentsoftwarebuilds', 'Description', '1');
commit;
--------------------------------DML SCRIPT FOR AUDITTABLESANDCOLUMNS (Buildbags) ENTITY ------------------------------------

INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Buildbags', 'Buildbagid', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Buildbags', 'Bagdescription', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Buildbags', 'Creationuser', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Buildbags', 'Creationdate', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Buildbags', 'Modificationuser', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Buildbags', 'Modificationdate', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Buildbags', 'Deleted', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Buildbags', 'Deletiondate', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Buildbags', 'Bagversion', '1');
commit;
