
------------ALTER SCRIPT FOR LCMENGINEERING------------------

ALTER TABLE "LCMENGINEERING" ADD "BUILDBAGID" NUMBER(19,0);
ALTER TABLE "LCMENGINEERING" ADD CONSTRAINT "FK_LCMENGINEERING_BUILDBAGS_BUILDBAGID" FOREIGN KEY ("BUILDBAGID") REFERENCES "BUILDBAGS" ("BUILDBAGID") ENABLE;

ALTER TABLE "NETWORKELEMENTSASPLANNED" ADD "BUILDBAGID" NUMBER(19,0);
ALTER TABLE "NETWORKELEMENTSASPLANNED" ADD CONSTRAINT "FK_NETWORKELEMENTSASPLANNED_BUILDBAGS_BUILDBAGID" FOREIGN KEY ("BUILDBAGID") REFERENCES "BUILDBAGS" ("BUILDBAGID") ENABLE;

ALTER TABLE "PLANNEDACTIVITIES" ADD "BUILDBAGID" NUMBER(19,0);
ALTER TABLE "PLANNEDACTIVITIES" ADD CONSTRAINT "FK_PLANNEDACTIVITIES_BUILDBAGS_BUILDBAGID" FOREIGN KEY ("BUILDBAGID") REFERENCES "BUILDBAGS" ("BUILDBAGID") ENABLE;



ALTER TABLE NETWORKELEMENTSASPLANNED DROP COLUMN ISRELEASEDDETAILSKNOWN;



delete gridcustomcolumn   where  classname='BuildBagDtoGrid';
commit;


----------------------END-----------------------------
