---- Drop Seq and Table - Dn't change Order

DROP SEQUENCE CLUSTERUPGRADESTATUS_SEQ;
DROP TABLE CLUSTERUPGRADESTATUS;

DROP SEQUENCE INFRACLUSTERASPLANNED_SEQ;
DROP SEQUENCE NETWORKELEMENTCLUSTERASPLANNED_SEQ;

DROP TABLE NETWORKELEMENTCLUSTERASPLANNED;
DROP TABLE INFRACLUSTERASPLANNED;

COMMIT;