
--------------------------------------------------------
--  DDL for Sequence RECONCILIATION_SEQ
--------------------------------------------------------

CREATE SEQUENCE "RECONCILIATION_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;




--------------------------------------------------------
--  DDL for Table RECONCILIATIONS
--------------------------------------------------------

CREATE TABLE "RECONCILIATIONS" 
("RECONCILIATIONID" NUMBER(20,0) DEFAULT "RECONCILIATION_SEQ"."NEXTVAL", 
"OPCO" NVARCHAR2(50), 
"ELEMENTNAME" NVARCHAR2(50), 
"DEPLOYMENTSTATUS" NVARCHAR2(50), 
"CURRENTSWVERSION" NVARCHAR2(50), 
"NEWSWVERSION" NVARCHAR2(50), 
"STATUS" NVARCHAR2(1000),
"ASSETID" NUMBER(19,0), 	
"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
"DELETED" NUMBER(1,0) DEFAULT 0, 
"DELETIONDATE" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;

--------------------------------------------------------
--  DDL for Index PK_RECONCILIATIONS
--------------------------------------------------------

CREATE UNIQUE INDEX "PK_RECONCILIATIONS" ON "RECONCILIATIONS" ("RECONCILIATIONID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table RECONCILIATIONS
--------------------------------------------------------

ALTER TABLE "RECONCILIATIONS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "RECONCILIATIONS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "RECONCILIATIONS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "RECONCILIATIONS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "RECONCILIATIONS" ADD CONSTRAINT "PK_RECONCILIATIONS" PRIMARY KEY ("RECONCILIATIONID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECONCILIATIONS
--------------------------------------------------------

ALTER TABLE "RECONCILIATIONS" ADD CONSTRAINT "FK_RECONCILIATIONS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "RECONCILIATIONS" ADD CONSTRAINT "FK_RECONCILIATIONS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
  REFERENCES "ASPNETUSERS" ("ID") ENABLE;

COMMIT;