-------------------------------------------------------
--  DDL for Sequence PLANNEDACTIVITYCATEGORY_SEQ
--------------------------------------------------------
 
CREATE SEQUENCE  "PLANNEDACTIVITYCATEGORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
 
 
--------------------------------------------------------
--  DDL for Table PLANNEDACTIVITYCATEGORY
--------------------------------------------------------
 
  CREATE TABLE PLANNEDACTIVITYCATEGORY
   (	
    "PLANNEDACTIVITYCATEGORYID" NUMBER(5,0) DEFAULT "PLANNEDACTIVITYCATEGORY_SEQ"."NEXTVAL", 
	"CATEGORYDESCRIPTION" NVARCHAR2(150),
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index PLANNEDACTIVITYCATEGORYIDX
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PLANNEDACTIVITYCATEGORYIDX" ON "PLANNEDACTIVITYCATEGORY" ("PLANNEDACTIVITYCATEGORYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table PLANNEDACTIVITYCATEGORY
--------------------------------------------------------
 
ALTER TABLE "PLANNEDACTIVITYCATEGORY" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "PLANNEDACTIVITYCATEGORY" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "PLANNEDACTIVITYCATEGORY" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "PLANNEDACTIVITYCATEGORY" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "PLANNEDACTIVITYCATEGORY" ADD CONSTRAINT "PK_PLANNEDACTIVITYCATEGORY" PRIMARY KEY ("PLANNEDACTIVITYCATEGORYID") USING INDEX "PLANNEDACTIVITYCATEGORYIDX"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLANNEDACTIVITYCATEGORY
--------------------------------------------------------
 
ALTER TABLE "PLANNEDACTIVITYCATEGORY" ADD CONSTRAINT "FK_PLANNEDACTIVITYCATEGORY_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "PLANNEDACTIVITYCATEGORY" ADD CONSTRAINT "FK_PLANNEDACTIVITYCATEGORY_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
COMMIT;

 


