--------------------------------------------------------
--  DDL for Sequence BUDGETPROJECTTRACKER_SEQ
--------------------------------------------------------
 
CREATE SEQUENCE  "BUDGETPROJECTTRACKERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
 
 
--------------------------------------------------------
--  DDL for Table BUDGETPROJECTTRACKERS
--------------------------------------------------------
 
  CREATE TABLE BUDGETPROJECTTRACKERS 
   (	
    "BUDGETPROJECTTRACKERID" NUMBER(19,0) DEFAULT "BUDGETPROJECTTRACKERS_SEQ"."NEXTVAL", 
	"BUDGETLINECODE" NVARCHAR2(256),
	"UPLOADSTATUS" NVARCHAR2(256),
	"UPLOADMODE" NVARCHAR2(256),
	"CURRENTTRACKINGNUMBER" NVARCHAR2(256),
	"NEWTRACKINGNUMBER" NVARCHAR2(256),
	"WBS" NVARCHAR2(256),
	"OPCOID" NUMBER(5,0),
	"OPCO" NVARCHAR2(50),
	"DOMAIN" NVARCHAR2(256),
	"TEAM" NVARCHAR2(256),
	"BUDGETOWNER" NVARCHAR2(2000),
	"PROGRAM" NVARCHAR2(256),
	"BUDGETPROJECT" NVARCHAR2(256),
	"ACTIVITY" NVARCHAR2(256),
	"PRIORITY" NVARCHAR2(256),
	"DRIVER" NVARCHAR2(256),
	"BENEFITS" NVARCHAR2(256),
	"RISKS" NVARCHAR2(256),
	"CATEGORY" NVARCHAR2(256),
	"CATEGORYID" NUMBER(5,0),
	"NWELEMENT" NVARCHAR2(256),
	"VIRTUALIZEDNWELEMENT" NVARCHAR2(256),
	"VENDOR" NVARCHAR2(256),
	"LCMCATEGORIESID" NUMBER(5,0),
	"LCMCATEGORIES" NVARCHAR2(256),
	"OHPLEV1" NVARCHAR2(256),
	"OHPLEV2" NVARCHAR2(256),
	"HFMLEV1" NVARCHAR2(256),
	"HFMLEV2" NVARCHAR2(256),
	"FY" NVARCHAR2(256),
	"OPERATIONAL" NVARCHAR2(256),
	"TRANSFERS" NVARCHAR2(256),
	"COST1STEST" NVARCHAR2(256),
	"VALIDATION" NVARCHAR2(256),
	"SIGNOFF" NVARCHAR2(256),
	"SUB" NVARCHAR2(256),
	"FINALRESUB" NVARCHAR2(256),
	"LATESTSCENARIO" NVARCHAR2(256),
	"CURRENCY" NVARCHAR2(256),
	"ADJUSTMENTS" NVARCHAR2(256),
	"YTDACTUALS" NVARCHAR2(256),
	"PLANNEDABSORPTION" NVARCHAR2(256),
	"DEVIATION" NVARCHAR2(256),
	"APR" NVARCHAR2(256),
	"MAY" NVARCHAR2(256),
	"JUN" NVARCHAR2(256),
	"JUL" NVARCHAR2(256),
	"AUG" NVARCHAR2(256),
	"SEP" NVARCHAR2(256),
	"OCT" NVARCHAR2(256),
	"NOV" NVARCHAR2(256),
	"DEC" NVARCHAR2(256),
	"JAN" NVARCHAR2(256),
	"FEB" NVARCHAR2(256),
	"MAR" NVARCHAR2(256),
	"APPROVEDBUDGET" NVARCHAR2(256),
	"COMMITMENT" NVARCHAR2(256),
	"BUDGETPROJECTDEPENDENCY" NVARCHAR2(256),
	"LOCALPROGRAM" NVARCHAR2(256),
	"LOCALBUDGETPROJECT" NVARCHAR2(256),
	"LOCALDRIVER" NVARCHAR2(256),
	"LOCALPRIORITIZATION" NVARCHAR2(256),
	"PPMID" NVARCHAR2(256),
	"PPMBUDGETPROJECTID" NVARCHAR2(256),
	"COSTCENTRE" NVARCHAR2(256),
	"WPID" NVARCHAR2(256),
	"GROUPBUDGETOPCOID" NVARCHAR2(256),
	"INTERNALPROGRAM" NVARCHAR2(256),
	"VERTICALPROJECT" NVARCHAR2(256),
	"DOMAINSPECIFICLABELS" NVARCHAR2(256),
	"LABELSMARKETVSVERTICAL" NVARCHAR2(256),
	"OTHERMINORVENDORS" NVARCHAR2(256),
	"EXTERNALDEMANDBUDGET" NVARCHAR2(256),
	"OPEXIMPACT" NVARCHAR2(256),
	"LEGALENTITY" NVARCHAR2(256),
	"YEARLYTRANSFERSTRACK" NVARCHAR2(256),
	"YEARLYADJUSTMENTSTRACK" NVARCHAR2(256),
	"MCUSTOM02" NVARCHAR2(256),
	"MCUSTOM03" NVARCHAR2(256),
	"MCUSTOM04" NVARCHAR2(256),
	"MCUSTOM05" NVARCHAR2(256),
	"MCUSTOM06" NVARCHAR2(256),
	"MCUSTOM07" NVARCHAR2(256),
	"MCUSTOM08" NVARCHAR2(256),
	"MCUSTOM09" NVARCHAR2(256),
	"MCUSTOM10" NVARCHAR2(256),
	"VCUSTOM01" NVARCHAR2(256),
	"VCUSTOM02" NVARCHAR2(256),
	"VCUSTOM03" NVARCHAR2(256),
	"VCUSTOM04" NVARCHAR2(256),
	"VCUSTOM05" NVARCHAR2(256),
	"DCUSTOM01" NVARCHAR2(256),
	"DCUSTOM02" NVARCHAR2(256),
	"DCUSTOM03" NVARCHAR2(256),
	"DCUSTOM04" NVARCHAR2(256),
	"DCUSTOM05" NVARCHAR2(256),
	"LSDB" NVARCHAR2(256),
	"LS012" NVARCHAR2(256),
	"LS210" NVARCHAR2(256),
	"LS57" NVARCHAR2(256),
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6),
	"ARCHIVE" NUMBER(1,0) DEFAULT 0, 
	"PLANNEDACTIVITYID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index BUDGETPROJECTTRACKERIDX
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "BUDGETPROJECTTRACKERIDX" ON "BUDGETPROJECTTRACKERS" ("BUDGETPROJECTTRACKERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table BUDGETPROJECTTRACKERS
--------------------------------------------------------
 
ALTER TABLE "BUDGETPROJECTTRACKERS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "BUDGETPROJECTTRACKERS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "BUDGETPROJECTTRACKERS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "BUDGETPROJECTTRACKERS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "BUDGETPROJECTTRACKERS" ADD CONSTRAINT "PK_BUDGETPROJECTTRACKERS" PRIMARY KEY ("BUDGETPROJECTTRACKERID") USING INDEX "BUDGETPROJECTTRACKERIDX"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUDGETPROJECTTRACKERS
--------------------------------------------------------
 
ALTER TABLE "BUDGETPROJECTTRACKERS" ADD CONSTRAINT "FK_BUDGETPROJECTTRACKERS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "BUDGETPROJECTTRACKERS" ADD CONSTRAINT "FK_BUDGETPROJECTTRACKERS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "BUDGETPROJECTTRACKERS" ADD CONSTRAINT "FK_BUDGETPROJECTTRACKERS_OPCOS_OPCOID" FOREIGN KEY ("OPCOID") REFERENCES "OPCOS" ("OPCOID") ENABLE;
ALTER TABLE "BUDGETPROJECTTRACKERS" ADD CONSTRAINT "FK_BUDGETPROJECTTRACKERS_CATEGORY_CATEGORYID" FOREIGN KEY ("CATEGORYID") REFERENCES "PLANNEDACTIVITYCATEGORY" ("PLANNEDACTIVITYCATEGORYID") ENABLE;
ALTER TABLE "BUDGETPROJECTTRACKERS" ADD CONSTRAINT "FK_BUDGETPROJECTTRACKERS_PLANNEDACTIVITY_PLANNEDACTIVITYID" FOREIGN KEY ("PLANNEDACTIVITYID") REFERENCES "PLANNEDACTIVITIES" ("PLANNEDACTIVITYID") ENABLE;

COMMIT;

----------------------


