ALTER TABLE "PLANNEDACTIVITIES" ADD "PLANNEDACTIVITYTEAM" NVARCHAR2(150);
ALTER TABLE "PLANNEDACTIVITIES" ADD "PRIORITY" NVARCHAR2(150);
ALTER TABLE "PLANNEDACTIVITIES" ADD "PLANNEDACTIVITYCATEGORYID" NUMBER(5,0);
ALTER TABLE "PLANNEDACTIVITIES" ADD "PLANNEDACTIVITYCATEGORY" NVARCHAR2(150);
ALTER TABLE "PLANNEDACTIVITIES" ADD "LCMCATEGORIES" NUMBER(5,0);


ALTER TABLE "PLANNEDACTIVITIES" ADD CONSTRAINT "FK_PLANNEDACTIVITIES_PLANNEDACTIVITYCATEGORY_PLANNEDACTIVITYCATEGORYID" FOREIGN KEY ("PLANNEDACTIVITYCATEGORYID") REFERENCES "PLANNEDACTIVITYCATEGORY" ("PLANNEDACTIVITYCATEGORYID") ENABLE;
