--------------------------------------------------------
--  DDL for Sequence EXCELTEMPLATECONFIGURATION_SEQ
--------------------------------------------------------
 
CREATE SEQUENCE  "EXCELTEMPLATECONFIGURATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
 
 
--------------------------------------------------------
--  DDL for Table EXCELTEMPLATECONFIGURATION
--------------------------------------------------------
 
  CREATE TABLE EXCELTEMPLATECONFIGURATION
   (	
    "EXCELTEMPLATECONFIGURATIONID" NUMBER(10,0) DEFAULT "EXCELTEMPLATECONFIGURATION_SEQ"."NEXTVAL",
	"PROCESSNAME" NVARCHAR2(150),
	"PROPERTYNAME" NVARCHAR2(150),
	"COLUMNHEADERNAME" NVARCHAR2(150),
	"COLUMNORDER" NUMBER(10,0),
	"FONTCOLOR" NVARCHAR2(150),
	"CELLCOLOR" NVARCHAR2(150),
	"ISIMPORTFIELD" NUMBER(1,0) DEFAULT 0,
	"ISEXPORTFIELD" NUMBER(1,0) DEFAULT 0,
	"ISMANDATORY" NUMBER(1,0) DEFAULT 0,
	"DATATYPE" NVARCHAR2(150),
	"DEFAULTVALUE" NVARCHAR2(150),
	"MAPPINGREFERENCE" NVARCHAR2(150),
	"ISMERGED" NUMBER(1,0) DEFAULT 0,
	"MERGESTARTCOLUMN" NUMBER(10,0),
	"MERGEENDCOLUMN" NUMBER(10,0),
	"ROWSTARTING" NUMBER(10,0),
	"HEADERROWSTARTING" NUMBER(10,0),
	"TEMPLATEFILENAME" NVARCHAR2(50),
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index EXCELTEMPLATECONFIGURATIONIDX
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "EXCELTEMPLATECONFIGURATIONIDX" ON "EXCELTEMPLATECONFIGURATION" ("EXCELTEMPLATECONFIGURATIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table EXCELTEMPLATECONFIGURATION
--------------------------------------------------------
 
ALTER TABLE "EXCELTEMPLATECONFIGURATION" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "EXCELTEMPLATECONFIGURATION" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "EXCELTEMPLATECONFIGURATION" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "EXCELTEMPLATECONFIGURATION" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "EXCELTEMPLATECONFIGURATION" ADD CONSTRAINT "PK_EXCELTEMPLATECONFIGURATION" PRIMARY KEY ("EXCELTEMPLATECONFIGURATIONID") USING INDEX "EXCELTEMPLATECONFIGURATIONIDX"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXCELTEMPLATECONFIGURATION
--------------------------------------------------------
 
ALTER TABLE "EXCELTEMPLATECONFIGURATION" ADD CONSTRAINT "FK_EXCELTEMPLATECONFIGURATION_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "EXCELTEMPLATECONFIGURATION" ADD CONSTRAINT "FK_EXCELTEMPLATECONFIGURATION_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
COMMIT;