
--- CATEGORY RECORDS ---

INSERT INTO PLANNEDACTIVITYCATEGORY (CATEGORYDESCRIPTION) VALUES ('Capitalization');
INSERT INTO PLANNEDACTIVITYCATEGORY (CATEGORYDESCRIPTION) VALUES ('Challenge');
INSERT INTO PLANNEDACTIVITYCATEGORY (CATEGORYDESCRIPTION) VALUES ('HW');
INSERT INTO PLANNEDACTIVITYCATEGORY (CATEGORYDESCRIPTION) VALUES ('HW, PS');
INSERT INTO PLANNEDACTIVITYCATEGORY (CATEGORYDESCRIPTION) VALUES ('HW, SW');
INSERT INTO PLANNEDACTIVITYCATEGORY (CATEGORYDESCRIPTION) VALUES ('PS');
INSERT INTO PLANNEDACTIVITYCATEGORY (CATEGORYDESCRIPTION) VALUES ('SI');
INSERT INTO PLANNEDACTIVITYCATEGORY (CATEGORYDESCRIPTION) VALUES ('SW');
INSERT INTO PLANNEDACTIVITYCATEGORY (CATEGORYDESCRIPTION) VALUES ('SW, PS');
INSERT INTO PLANNEDACTIVITYCATEGORY (CATEGORYDESCRIPTION) VALUES ('WP (Group only)');

COMMIT;
