ALTER TABLE "BUILDCONSTRUCTIONS" RENAME COLUMN "ISCLUODASSET" TO "ISCLOUDASSET";

ALTER TABLE "GLOSSARYITEMS" ADD "ISTSRFIELD" NUMBER(1,0) DEFAULT 0;


ALTER TABLE "GLOSSARYITEMS" ADD "DESCRIPTION1" VARCHAR2(4000);

UPDATE GLOSSARYITEMS G SET DESCRIPTION1 = (SELECT DESCRIPTION FROM GLOSSARYITEMS WHERE G.GLOSSARYITEMSID = GLOSSARYITEMSID ) ;
COMMIT;

ALTER TABLE GLOSSARYITEMS DROP COLUMN DESCRIPTION;

ALTER TABLE GLOSSARYITEMS RENAME COLUMN DESCRIPTION1 TO DESCRIPTION;
COMMIT;
