-------------- NETWORKELEMENTSASPLANNED ADD DATE FOR EXODUS REPORT

ALTER TABLE NETWORKELEMENTSASPLANNED drop column   ASSETRFODATE  ;
ALTER TABLE NETWORKELEMENTSASPLANNED drop column  ASSETRFSDATE  ;