-----------------------------------------------------------
--  DDL FOR NETWORKELEMENTSASPLANNED AND BUILDCONSTRUCTIONS
-----------------------------------------------------------

		ALTER TABLE NETWORKELEMENTSASPLANNED ADD ASSETLIVESTATUSDATE TIMESTAMP(6);
		ALTER TABLE NETWORKELEMENTSASPLANNED ADD ASSETDECOMMISSIONEDDATE TIMESTAMP(6);
		ALTER TABLE BUILDCONSTRUCTIONS ADD ISCLUODASSET NUMBER(1,0) DEFAULT 0;
        
--------------------------------------------------------
--  DDL FOR SEQUENCE SYSTEMNAMES_SEQ
--------------------------------------------------------
CREATE SEQUENCE "SYSTEMNAMES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE SYSTEMNAMES
--------------------------------------------------------
CREATE TABLE SYSTEMNAMES (
    SYSTEMNAMEID NUMBER(19, 0) DEFAULT SYSTEMNAMES_SEQ.NEXTVAL NOT NULL,
    SYSTEMNAMEDESCRIPTION NVARCHAR2(2000),
    CREATIONUSER     NUMBER(10, 0) DEFAULT 1,
    CREATIONDATE     TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    MODIFICATIONUSER NUMBER(10, 0) DEFAULT 1,
    MODIFICATIONDATE TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    DELETED          NUMBER(1, 0) DEFAULT 0,
    DELETIONDATE     TIMESTAMP(6)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "CAMDB";
  
--------------------------------------------------------
--  DDL FOR INDEX PK_SYSTEMNAMES
--------------------------------------------------------
CREATE UNIQUE INDEX "PK_SYSTEMNAMES" ON
    SYSTEMNAMES (
        "SYSTEMNAMEID"
    )
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "CAMDB";
 --------------------------------------------------------
--  CONSTRAINTS FOR TABLE SYSTEMNAMES
--------------------------------------------------------

ALTER TABLE SYSTEMNAMES MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE SYSTEMNAMES MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE SYSTEMNAMES MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE SYSTEMNAMES MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE SYSTEMNAMES ADD CONSTRAINT "PK_SYSTEMNAMES" PRIMARY KEY ("SYSTEMNAMEID")
USING INDEX "PK_SYSTEMNAMES"  ENABLE;
  
  --------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE SYSTEMNAMES
--------------------------------------------------------

ALTER TABLE SYSTEMNAMES ADD CONSTRAINT "FK_SYSTEMNAMES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE SYSTEMNAMES ADD CONSTRAINT "FK_SYSTEMNAMES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;

COMMIT;


-----------------------------------------------------------
--  DDL FOR NETWORKELEMENTSASPLANNED
-----------------------------------------------------------

ALTER TABLE NETWORKELEMENTSASPLANNED ADD DOMIANNAMEID NUMBER(19,0);
ALTER TABLE "NETWORKELEMENTSASPLANNED" ADD CONSTRAINT "FK_NETWORKELEMENTSASPLANNED_SYSTEMNAMES_LOCATIONID" FOREIGN KEY ("DOMIANNAMEID") REFERENCES "SYSTEMNAMES" ("SYSTEMNAMEID") ENABLE;


COMMIT;

-----------------------------------------------------------
--  DDL FOR TSRPASSTHROUGH
-----------------------------------------------------------
ALTER TABLE TSRPASSTHROUGH MODIFY CRITICALITYTYPE NVARCHAR2(2000);
ALTER TABLE TSRPASSTHROUGH MODIFY GEOGRAPHICSITERESILIENCE NVARCHAR2(2000);
ALTER TABLE TSRPASSTHROUGH MODIFY LOCALSITERESILIENCE NVARCHAR2(2000);