 
--------------------------------DML SCRIPT FOR AUDITTABLESANDCOLUMNS (Vnfinfo) ENTITY  

INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfinfo', 'Vnfnameid', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfinfo', 'Clusterid', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfinfo', 'Vmtypenameid', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfinfo', 'Nsxt', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfinfo', 'Intravmtype', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfinfo', 'Intervmtype', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfinfo', 'Vmworkloadtype', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfinfo', 'Vmstorageblocksize', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfinfo', 'Creationuser', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfinfo', 'Creationdate', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfinfo', 'Modificationuser', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfinfo', 'Modificationdate', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfinfo', 'Deleted', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfinfo', 'Deletiondate', '1');

--------------------------------DML SCRIPT FOR AUDITTABLESANDCOLUMNS (Vnfvminstances) ENTITY  

INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvminstances', 'Vnfinfoid', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvminstances', 'Opcoid', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvminstances', 'Locationid', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvminstances', 'Noofvnfinstances', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvminstances', 'Noofvmspertype', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvminstances', 'Numa', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvminstances', 'Socket', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvminstances', 'Creationuser', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvminstances', 'Creationdate', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvminstances', 'Modificationuser', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvminstances', 'Modificationdate', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvminstances', 'Deleted', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvminstances', 'Deletiondate', '1');

--------------------------------DML SCRIPT FOR AUDITTABLESANDCOLUMNS (Vnfvmcapacity) ENTITY  

INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Vnfvminstanceid', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Financialyear', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Vcpupervm', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Rxtxcpucount', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Rampervm', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Datadisk', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Osdisk', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Iopsrunning', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Iopsloading', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Vmworkloaddistribution', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Northsouthboundbandwidth', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Eastwestboundbandwidth', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Otherrequirements', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Backuprequired', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Probingrequired', '1'); 
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Creationuser', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Creationdate', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Modificationuser', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Modificationdate', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Deleted', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Vnfvmcapacity', 'Deletiondate', '1');

commit;

 