-----------------------------------------------------------
--  DDL FOR NETWORKELEMENTSASPLANNED
-----------------------------------------------------------
ALTER TABLE NETWORKELEMENTSASPLANNED DROP COLUMN DOMIANNAMEID;
ALTER TABLE NETWORKELEMENTSASPLANNED DROP CONSTRAINT FK_NETWORKELEMENTSASPLANNED_SYSTEMNAMES_LOCATIONID;
ALTER TABLE NETWORKELEMENTSASPLANNED ADD ELEMENTDOMIANNAME NVARCHAR2(2000);
ALTER TABLE TSRPASSTHROUGH MODIFY SYSTEMNAMEDNS NVARCHAR2(2000);
ALTER TABLE OPERATINGSYSTEMS ADD OPERATINGSYSTEMVERSION NVARCHAR2(50);