CREATE SEQUENCE "RESOURCEKEYMASTER_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL for Table RESOURCEKEYMASTER
--------------------------------------------------------

   CREATE TABLE "RESOURCEKEYMASTER" 
(
    "RESOURCEKEYMASTERID" NUMBER(19,0) DEFAULT "RESOURCEKEYMASTER_SEQ"."NEXTVAL",
    "RESOURCETYPESID" NUMBER(19,0),
    "RESOURCEKEY" NVARCHAR2(10),
    "OPCOID" NUMBER(5,0),
    "DCFID" NUMBER(19,0),
	"RESOURCELIFECYCLEID" NUMBER(19,0),
	"KEYSTATUS" NUMBER(1,0),
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
    "CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
    "MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
    "MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp),
    "DELETED" NUMBER(1,0) DEFAULT 0,
	"DELETIONDATE" TIMESTAMP (6)	
)SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";
--------------------------------------------------------
--  DDL for Index RESOURCEKEYMASTERIDX
--------------------------------------------------------
  CREATE UNIQUE INDEX "RESOURCEKEYMASTERIDX" ON "RESOURCEKEYMASTER" ("RESOURCEKEYMASTERID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";
--------------------------------------------------------
--  Constraints for Table RESOURCEKEYMASTER
--------------------------------------------------------
  ALTER TABLE "RESOURCEKEYMASTER" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "RESOURCEKEYMASTER" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "RESOURCEKEYMASTER" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "RESOURCEKEYMASTER" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "RESOURCEKEYMASTER" ADD CONSTRAINT "RESOURCEKEYMASTER_PK" PRIMARY KEY ("RESOURCEKEYMASTERID")
   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table RESOURCEKEYMASTER
--------------------------------------------------------
ALTER TABLE "RESOURCEKEYMASTER" ADD CONSTRAINT "FK_RESOURCEKEYMASTER_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
REFERENCES "ASPNETUSERS" ("ID") ENABLE;	  

ALTER TABLE "RESOURCEKEYMASTER" ADD CONSTRAINT "FK_RESOURCEKEYMASTER_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
REFERENCES "ASPNETUSERS" ("ID") ENABLE;

ALTER TABLE "RESOURCEKEYMASTER" ADD CONSTRAINT "FK_RESOURCEKEYMASTER_RESOURCETYPES_RESOURCETYPESID" FOREIGN KEY ("RESOURCETYPESID")
REFERENCES "RESOURCETYPES" ("RESOURCETYPESID") ENABLE;

ALTER TABLE "RESOURCEKEYMASTER" ADD CONSTRAINT "FK_RESOURCEKEYMASTER_DESIGNCOMPONENTS_DESIGNCOMPONENTFAMILYID" FOREIGN KEY ("DCFID")
REFERENCES "DESIGNCOMPONENTFAMILIES" ("DESIGNCOMPONENTFAMILYID") ENABLE;

ALTER TABLE "RESOURCEKEYMASTER" ADD CONSTRAINT "FK_RESOURCEKEYMASTER_LCMENGINEERING_OPCOS_OPCOID" FOREIGN KEY ("OPCOID")
REFERENCES "OPCOS" ("OPCOID") ENABLE;

ALTER TABLE "RESOURCEKEYMASTER"
MODIFY("RESOURCEKEYMASTERID"  DEFAULT "RESOURCEKEYMASTER_SEQ"."NEXTVAL");

ALTER TABLE RESOURCEKEYMASTER
ADD CONSTRAINT UK_RESOURCEKEYMASTER_RESOURCEKEY UNIQUE (RESOURCEKEY);
