
CREATE SEQUENCE "LCMEXPORTSETTINGS_SEQ" INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999 MINVALUE 1 NOCACHE;
COMMIT;

  CREATE TABLE "LCMEXPORTSETTINGS" 
   (	"ID" NUMBER(10,0) DEFAULT "LCMEXPORTSETTINGS_SEQ"."NEXTVAL", 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6), 
	"DESCRIPTION" NVARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
  COMMIT;
--------------------------------------------------------
--  DDL for Index PK_LCMEXPORTSETTINGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_LCMEXPORTSETTINGS" ON "LCMEXPORTSETTINGS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  COMMIT;
--------------------------------------------------------
--  Constraints for Table LCMEXPORTSETTINGS
--------------------------------------------------------

  ALTER TABLE "LCMEXPORTSETTINGS" ADD CONSTRAINT "PK_LCMEXPORTSETTINGS" PRIMARY KEY ("ID")
  USING INDEX "PK_LCMEXPORTSETTINGS"  ENABLE;
  ALTER TABLE "LCMEXPORTSETTINGS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LCMEXPORTSETTINGS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "LCMEXPORTSETTINGS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "LCMEXPORTSETTINGS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "LCMEXPORTSETTINGS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "LCMEXPORTSETTINGS" MODIFY ("DELETED" NOT NULL ENABLE);
  COMMIT;
--------------------------------------------------------
--  Ref Constraints for Table LCMEXPORTSETTINGS
--------------------------------------------------------

  ALTER TABLE "LCMEXPORTSETTINGS" ADD CONSTRAINT "FK_LCMEXPORTSETTINGS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "LCMEXPORTSETTINGS" ADD CONSTRAINT "FK_LCMEXPORTSETTINGS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
COMMIT;
ALTER TABLE LCMEXPORTSETTINGS
MODIFY(ID  DEFAULT "LCMEXPORTSETTINGS_SEQ"."NEXTVAL");
COMMIT;


