
--------------------------------------------------------
--  DDL for Sequence SWCONFIGFUNCTIONAREA_SEQ
--------------------------------------------------------

CREATE SEQUENCE "SWCONFIGFUNCTIONAREA_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;




--------------------------------------------------------
--  DDL for Table SWCONFIGFUNCTIONAREAS
--------------------------------------------------------

CREATE TABLE "SWCONFIGFUNCTIONAREAS" 
("SWCONFIGFUNCTIONAREAID" NUMBER(20,0) DEFAULT "SWCONFIGFUNCTIONAREA_SEQ"."NEXTVAL", 
"FUNCTIONID" NUMBER(20,0), 
"FUNCTIONAREANAME" NVARCHAR2(50),
"FUNCTIONAREADESCRIPTION" NCLOB,
"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
"DELETED" NUMBER(1,0) DEFAULT 0, 
"DELETIONDATE" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;

--------------------------------------------------------
--  DDL for Index PK_SWCONFIGFUNCTIONAREAS
--------------------------------------------------------

CREATE UNIQUE INDEX "PK_SWCONFIGFUNCTIONAREAS" ON "SWCONFIGFUNCTIONAREAS" ("SWCONFIGFUNCTIONAREAID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table SWCONFIGFUNCTIONAREAS
--------------------------------------------------------

ALTER TABLE "SWCONFIGFUNCTIONAREAS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "SWCONFIGFUNCTIONAREAS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "SWCONFIGFUNCTIONAREAS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "SWCONFIGFUNCTIONAREAS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "SWCONFIGFUNCTIONAREAS" ADD CONSTRAINT "PK_SWCONFIGFUNCTIONAREAS" PRIMARY KEY ("SWCONFIGFUNCTIONAREAID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SWCONFIGFUNCTIONAREAS
--------------------------------------------------------

ALTER TABLE "SWCONFIGFUNCTIONAREAS" ADD CONSTRAINT "FK_SWCONFIGFUNCTIONAREAS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "SWCONFIGFUNCTIONAREAS" ADD CONSTRAINT "FK_SWCONFIGFUNCTIONAREAS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "SWCONFIGFUNCTIONAREAS" ADD CONSTRAINT "FK_SWCONFIGFUNCTIONAREAS_FUNCTIOIN_FUNCTIONAREATESTID" FOREIGN KEY ("FUNCTIONID")
REFERENCES "FUNCTION" ("FUNCTIONID") ENABLE;

COMMIT;