----------------------------------------------------------
-- ROLLBACK SCRIPT FOR TABLE SWCONFIGSUBFUNCTION
----------------------------------------------------------
ALTER TABLE "SWCONFIGSUBFUNCTION" DROP CONSTRAINT "FK_SWCONFIGSUBFUNCTION_ASPNETUSERS_CREATIONUSER";
ALTER TABLE "SWCONFIGSUBFUNCTION" DROP CONSTRAINT "FK_SWCONFIGSUBFUNCTION_ASPNETUSERS_MODIFICATIONUSER";
ALTER TABLE "SWCONFIGSUBFUNCTION" DROP CONSTRAINT "FK_SWCONFIGSUBFUNCTION_SWCONFIGFUNCTIONAREAS_SWCONFIGFUNCTIONAREAID";
DROP SEQUENCE "SWCONFIGSUBFUNCTION_SEQ";
DROP TABLE "SWCONFIGSUBFUNCTION";
COMMIT;