----------------------------------------------------------
-- ROLLBACK SCRIPT FOR TABLE SWCONFIGSUBFUNCTIONAREAS
----------------------------------------------------------
ALTER TABLE "SWCONFIGSUBFUNCTIONAREAS" DROP CONSTRAINT "FK_SWCONFIGSUBFUNCTIONAREAS_ASPNETUSERS_CREATIONUSER";
ALTER TABLE "SWCONFIGSUBFUNCTIONAREAS" DROP CONSTRAINT "FK_SWCONFIGSUBFUNCTIONAREAS_ASPNETUSERS_MODIFICATIONUSER";
ALTER TABLE "SWCONFIGSUBFUNCTIONAREAS" DROP CONSTRAINT "FK_SWCONFIGSUBFUNCTIONAREAS_SWCONFIGSUBFUNCTION_SWCONFIGSUBFUNCTIONID";
DROP SEQUENCE "SWCONFIGSUBFUNCTIONAREA_SEQ";
DROP TABLE "SWCONFIGSUBFUNCTIONAREAS";
COMMIT;