----DROP CONSTRAINT FK_LCMENGINEERING_DESIGNCOMPONENTFAMILIES_DESIGNCOMPONENTFAMILYID -----
ALTER TABLE LCMENGINEERING DROP CONSTRAINT "FK_LCMENGINEERING_DESIGNCOMPONENTFAMILIES_DESIGNCOMPONENTFAMILYID" FOREIGN KEY ("DESIGNCOMPONENTFAMILYID") REFERENCES "DESIGNCOMPONENTFAMILIES" ("DESIGNCOMPONENTFAMILYID") ENABLE;

ALTER TABLE LCMENGINEERING DROP DESIGNCOMPONENTFAMILYID;

----DROP CONSTRAINT FK_NETWORKELEMENTSASPLANNED_DESIGNCOMPONENTFAMILIES_DESIGNCOMPONENTFAMILYID -----
ALTER TABLE NETWORKELEMENTSASPLANNED DROP CONSTRAINT "FK_NETWORKELEMENTSASPLANNED_DESIGNCOMPONENTFAMILIES_DESIGNCOMPONENTFAMILYID" FOREIGN KEY ("DESIGNCOMPONENTFAMILYID") REFERENCES "DESIGNCOMPONENTFAMILIES" ("DESIGNCOMPONENTFAMILYID") ENABLE;
      
ALTER TABLE NETWORKELEMENTSASPLANNED DROP DESIGNCOMPONENTFAMILYID;
