--------------------------------------------------------
--  DDL for Sequence NFVISOFTWARECOMPATIBILITY_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "NFVISOFTWARECOMPATIBILITY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
 
--------------------------------------------------------
--  DDL for Table NFVISOFTWARECOMPATIBILITY
--------------------------------------------------------

  CREATE TABLE NFVISOFTWARECOMPATIBILITY 
   (	
    "NFVISOFTWARECOMPATIBILITYID" NUMBER(19,0) DEFAULT "NFVISOFTWARECOMPATIBILITY_SEQ"."NEXTVAL", 
	"PLAFTFORMID" NUMBER(19,0),
	"PRODUCTID" NUMBER(20,0),	
	"MINIMUMSUPPORTEDVERSION" NVARCHAR2(50), 
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index NFVISOFTWARECOMPATIBILITYIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "NFVISOFTWARECOMPATIBILITYIDX" ON "NFVISOFTWARECOMPATIBILITY" ("NFVISOFTWARECOMPATIBILITYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table NFVISOFTWARECOMPATIBILITY
--------------------------------------------------------
ALTER TABLE "NFVISOFTWARECOMPATIBILITY" MODIFY ("PLAFTFORMID" NOT NULL ENABLE);
ALTER TABLE "NFVISOFTWARECOMPATIBILITY" MODIFY ("PRODUCTID" NOT NULL ENABLE);
ALTER TABLE "NFVISOFTWARECOMPATIBILITY" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "NFVISOFTWARECOMPATIBILITY" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "NFVISOFTWARECOMPATIBILITY" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "NFVISOFTWARECOMPATIBILITY" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "NFVISOFTWARECOMPATIBILITY" ADD CONSTRAINT "PK_NFVISOFTWARECOMPATIBILITY" PRIMARY KEY ("NFVISOFTWARECOMPATIBILITYID") USING INDEX "NFVISOFTWARECOMPATIBILITYIDX"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NFVISOFTWARECOMPATIBILITY
--------------------------------------------------------

ALTER TABLE "NFVISOFTWARECOMPATIBILITY" ADD CONSTRAINT "FK_NFVISOFTWARECOMPATIBILITY_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "NFVISOFTWARECOMPATIBILITY" ADD CONSTRAINT "FK_NFVISOFTWARECOMPATIBILITY_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;

ALTER TABLE "NFVISOFTWARECOMPATIBILITY" ADD CONSTRAINT "FK_NFVISOFTWARECOMPATIBILITY_MAJORSOFTWAREBUILDS_PLAFTFORMID" FOREIGN KEY ("PLAFTFORMID") REFERENCES "MAJORSOFTWAREBUILDS" ("MAJORSOFTWAREBUILDSID") ENABLE;

ALTER TABLE "NFVISOFTWARECOMPATIBILITY" ADD CONSTRAINT "FK_NFVISOFTWARECOMPATIBILITY_PRODUCTNAME_PRODUCTID" FOREIGN KEY ("PRODUCTID") REFERENCES "PRODUCTNAME" ("PRODUCTNAMEID") ENABLE;

ALTER TABLE  NFVISOFTWARECOMPATIBILITY  ADD  VENDORID NUMBER(5,0)  not   NULL;

ALTER TABLE "NFVISOFTWARECOMPATIBILITY" ADD CONSTRAINT "FK_NFVISOFTWARECOMPATIBILITY_ORIGINALEQUIPMENTMANUFACTURERS_VENDORID" FOREIGN KEY ("VENDORID") REFERENCES "ORIGINALEQUIPMENTMANUFACTURERS" ("ORGEQPMANUFACTURERID") ENABLE;


COMMIT;

 