 
--------------------------------DML SCRIPT FOR AUDITTABLESANDCOLUMNS (Nfvisoftwarecompatibility) ENTITY  

INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Nfvisoftwarecompatibility', 'Plaftformid', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Nfvisoftwarecompatibility', 'Productid', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Nfvisoftwarecompatibility', 'Creationuser', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Nfvisoftwarecompatibility', 'Creationdate', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Nfvisoftwarecompatibility', 'Modificationuser', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Nfvisoftwarecompatibility', 'Modificationdate', '0');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Nfvisoftwarecompatibility', 'Deleted', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Nfvisoftwarecompatibility', 'Deletiondate', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Nfvisoftwarecompatibility', 'Minimumsupportedversion', '1');
INSERT INTO AUDITTABLESANDCOLUMNS (ENTITYNAME, ENTITYFIELD, ISLOGENABLED) VALUES ('Nfvisoftwarecompatibility', 'Vendorid', '1');
commit;
