CREATE SEQUENCE USERSLOGGINGLEVELS_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  COMMIT

--------------------------------------------------------
--  DDL for Table USERSLOGGINGLEVELS
--------------------------------------------------------

  CREATE TABLE "CAMSDBUSER"."USERSLOGGINGLEVELS" 
   (	"LOGLEVEL" NVARCHAR2(50), 
	"CREATIONUSER" NUMBER(10,0) DEFAULT (null), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT (null), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6), 
	"LOGLEVELID" NUMBER(10,0) DEFAULT "CAMSDBUSER"."USERSLOGGINGLEVELS_SEQ"."NEXTVAL"
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index USERSLOGGINGLEVELS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMSDBUSER"."USERSLOGGINGLEVELS_PK" ON "CAMSDBUSER"."USERSLOGGINGLEVELS" ("LOGLEVELID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table USERSLOGGINGLEVELS
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."USERSLOGGINGLEVELS" MODIFY ("LOGLEVELID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."USERSLOGGINGLEVELS" ADD CONSTRAINT "USERSLOGGINGLEVELS_PK" PRIMARY KEY ("LOGLEVELID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;
  ALTER TABLE "CAMSDBUSER"."USERSLOGGINGLEVELS" MODIFY ("LOGLEVEL" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."USERSLOGGINGLEVELS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."USERSLOGGINGLEVELS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."USERSLOGGINGLEVELS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."USERSLOGGINGLEVELS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."USERSLOGGINGLEVELS" MODIFY ("DELETED" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table USERSLOGGINGLEVELS
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."USERSLOGGINGLEVELS" ADD CONSTRAINT "FK_USERSLOGGINGLEVELS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."USERSLOGGINGLEVELS" ADD CONSTRAINT "FK_USERSLOGGINGLEVELS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;





INSERT INTO userslogginglevels (loglevel,CREATIONUSER,MODIFICATIONUSER  ) VALUES ('Info',177,177);
commit;