
ALTER TABLE DAASSETMIGRATION ADD BOMSUBMITTEDDATE TIMESTAMP(6);
ALTER TABLE DAASSETMIGRATION ADD HWPORAISEDDATE TIMESTAMP(6);
ALTER TABLE DAASSETMIGRATION ADD HWPOARRIVEDDATE TIMESTAMP(6);
ALTER TABLE DAASSETMIGRATION ADD RFADATE TIMESTAMP(6);
COMMIT;

ALTER TABLE NETWORKELEMENTSASPLANNED ADD BOMSUBMITTEDDATE TIMESTAMP(6);
ALTER TABLE NETWORKELEMENTSASPLANNED ADD HWPORAISEDDATE TIMESTAMP(6);
ALTER TABLE NETWORKELEMENTSASPLANNED ADD HWPOARRIVEDDATE TIMESTAMP(6);
ALTER TABLE NETWORKELEMENTSASPLANNED ADD RFADATE TIMESTAMP(6);
COMMIT;
