-------------- NETWORKELEMENTSASPLANNED ADD DATE FOR EXODUS REPORT

ALTER TABLE NETWORKELEMENTSASPLANNED ADD   ASSETRFODATE   TIMESTAMP(6) ;
ALTER TABLE NETWORKELEMENTSASPLANNED ADD   ASSETRFSDATE   TIMESTAMP(6) ;