--ALTER TABLE SOFTWAREAPPLICATIONTYPES
--DROP CONSTRAINT FK_SOFTWAREAPPLICATIONTYPES_VODAFONENAMES_VODAFONENAMESID;

--ALTER TABLE MAJORSOFTWAREBUILDS
--DROP CONSTRAINT FK_MAJORSOFTWAREBUILDS_SOFTWAREAPPLICATIONTYPES_SOFTWAREAPPLICATIONTYPESID

--ALTER TABLE DESIGNCOMPONENTFAMILIES
--DROP CONSTRAINT FK_DESIGNCOMPONENTFAMILIES_SOFTWAREAPPLICATIONTYPES_SOFTWAREAPPLICATIONTYPESID

--ALTER TABLE SUBNETWORKBOUNDARIES
--DROP CONSTRAINT FK_SUBNETWORKBOUNDARIES_SOFTWAREAPPLICATIONTYPES_SOFTWAREAPPLICATIONTYPESID


--DROP TABLE SOFTWAREAPPLICATIONTYPES


ALTER TABLE MAJORSOFTWAREBUILDS 
RENAME COLUMN SOFTWAREAPPLICATIONTYPEID TO PRODUCTNAMEID;

ALTER TABLE DESIGNCOMPONENTFAMILIES
RENAME COLUMN SOFTWAREAPPLICATIONTYPEID TO PRODUCTNAMEID;

ALTER TABLE SUBNETWORKBOUNDARIES
RENAME COLUMN SOFTWAREAPPLICATIONTYPEID TO PRODUCTNAMEID;

ALTER TABLE MAJORSOFTWAREBUILDS 
RENAME COLUMN SOFTWAREAPPLICATION TO SOFTWAREVERSION;
commit;
