
CREATE SEQUENCE PRODUCTNAME_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


--------------------------------------------------------
--  DDL for Table PRODUCTNAME
--------------------------------------------------------

  CREATE TABLE "PRODUCTNAME" 
   (	"PRODUCTNAMEID" NUMBER(20,0) DEFAULT "PRODUCTNAME_SEQ"."NEXTVAL", 
	"DESCRIPTION" VARCHAR2(255 BYTE) DEFAULT (null), 
	"CREATIONUSER" NUMBER(10,0) DEFAULT (null), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT (null), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6) DEFAULT (null), 
	"VODAFONENAMESID" NUMBER(10,0) DEFAULT (null)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index PRODUCTNAME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRODUCTNAME_PK" ON "PRODUCTNAME" ("PRODUCTNAMEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table PRODUCTNAME
--------------------------------------------------------

  ALTER TABLE "PRODUCTNAME" MODIFY ("PRODUCTNAMEID" NOT NULL ENABLE);
  ALTER TABLE "PRODUCTNAME" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "PRODUCTNAME" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "PRODUCTNAME" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "PRODUCTNAME" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "PRODUCTNAME" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "PRODUCTNAME" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "PRODUCTNAME" ADD CONSTRAINT "PRODUCTNAME_PK" PRIMARY KEY ("PRODUCTNAMEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table PRODUCTNAME
--------------------------------------------------------

  ALTER TABLE "PRODUCTNAME" ADD CONSTRAINT "FK_PRODUCTNAME_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "PRODUCTNAME" ADD CONSTRAINT "FK_PRODUCTNAME_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "PRODUCTNAME" ADD CONSTRAINT "FK_PRODUCTNAME_VODAFONENAMES_VODAFONENAMESID" FOREIGN KEY ("VODAFONENAMESID")
	  REFERENCES "VODAFONENAMES" ("ID") ENABLE;

ALTER TABLE PRODUCTNAME
MODIFY(ID  DEFAULT "PRODUCTNAME_SEQ"."NEXTVAL");