
--------------------------------------------------------
--  DDL for Sequence RISKCLUSTER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE "RISKCLUSTER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;




--------------------------------------------------------
--  DDL for Table RISKCLUSTERS
--------------------------------------------------------

  CREATE TABLE "RISKCLUSTERS" 
   (	"RISKCLUSTERID" NUMBER(10,0) DEFAULT "RISKCLUSTER_SEQ"."NEXTVAL", 
	"DESCRIPTION" NVARCHAR2(50),
	"RISKLEVEL" NVARCHAR2(50),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6) 	
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index PK_RISKCLUSTERID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RISKCLUSTERID" ON "RISKCLUSTERS" ("RISKCLUSTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table RISKCLUSTERS
--------------------------------------------------------

  ALTER TABLE "RISKCLUSTERS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "RISKCLUSTERS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "RISKCLUSTERS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "RISKCLUSTERS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "RISKCLUSTERS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "RISKCLUSTERS" ADD CONSTRAINT "PK_RISKCLUSTERID" PRIMARY KEY ("RISKCLUSTERID")
  USING INDEX "PK_RISKCLUSTERID"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RISKCLUSTERS
--------------------------------------------------------

  ALTER TABLE "RISKCLUSTERS" ADD CONSTRAINT "FK_RISKCLUSTER_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "RISKCLUSTERS" ADD CONSTRAINT "FK_RISKCLUSTERS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
	  COMMIT;
  
