
--------------------------------------------------------
--  DDL for Sequence RISKCLUSTERVODAFONENAMES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE "RISKCLUSTERVODAFONENAMES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;




--------------------------------------------------------
--  DDL for Table RISKCLUSTERVODAFONENAMES
--------------------------------------------------------

  CREATE TABLE "RISKCLUSTERVODAFONENAMES" 
   (	"RISKCLUSTERVODAFONENAMEID" NUMBER(10,0) DEFAULT "RISKCLUSTERVODAFONENAMES_SEQ"."NEXTVAL", 
    "RISKCLUSTERID" NUMBER(10,0),
	"VODAFONENAMEID" NUMBER(10,0),	
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6) 	
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index PK_RISKCLUSTERVODAFONENAMEID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RISKCLUSTERVODAFONENAMEID" ON "RISKCLUSTERVODAFONENAMES" ("RISKCLUSTERVODAFONENAMEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table RISKCLUSTERVODAFONENAMES
--------------------------------------------------------

  ALTER TABLE "RISKCLUSTERVODAFONENAMES" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "RISKCLUSTERVODAFONENAMES" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "RISKCLUSTERVODAFONENAMES" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "RISKCLUSTERVODAFONENAMES" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "RISKCLUSTERVODAFONENAMES" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "RISKCLUSTERVODAFONENAMES" ADD CONSTRAINT "PK_RISKCLUSTERVODAFONENAMEID" PRIMARY KEY ("RISKCLUSTERVODAFONENAMEID")
  USING INDEX "PK_RISKCLUSTERVODAFONENAMEID"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RISKCLUSTERVODAFONENAMES
--------------------------------------------------------

	ALTER TABLE "RISKCLUSTERVODAFONENAMES" ADD CONSTRAINT "FK_RISKCLUSTERVODAFONENAMES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	ALTER TABLE "RISKCLUSTERVODAFONENAMES" ADD CONSTRAINT "FK_RISKCLUSTERVODAFONENAMES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	ALTER TABLE "RISKCLUSTERVODAFONENAMES" ADD CONSTRAINT "FK_RISKCLUSTERVODAFONENAMES_RISKCLUSTERS_RISKCLUSTERID" FOREIGN KEY ("RISKCLUSTERID")
	REFERENCES "RISKCLUSTERS" ("RISKCLUSTERID") ENABLE;
	ALTER TABLE "RISKCLUSTERVODAFONENAMES" ADD CONSTRAINT "FK_RISKCLUSTERVODAFONENAMES_VODAFONENAMES_VODAFONENAMEID" FOREIGN KEY ("VODAFONENAMEID")
	REFERENCES "VODAFONENAMES" ("ID") ENABLE;
	  
	  COMMIT;
  
