SET DEFINE OFF;



INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('UPF','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('UDR','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('UDM','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('SMF','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('SEPP','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('SEAF','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('SCP','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('PCF','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('NSSF','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('NRF','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('NEF','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('CHF','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('AUSF','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('AMF','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('5G EIR','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('X86 Compute','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('VNFM','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('VIM (eg Openstack)','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('SDN (Underlay) Core Controllers','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('SDN (Underlay) BH Controllers','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('SDN (Overlay) Controllers','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Orchestrator','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Hypervisor (ESXi, KVM)','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('CaaS','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('STP','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('DRA','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('HSS','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('HLR','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('CSDB','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('AuC','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Voice PCRF','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('SGSN/MME assets','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Securnet Assets','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('MSP/WAP GW ','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Gn/Gp DNS ','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Data PCRF','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('AAA','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('IP backend to remote Cable node','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('FTTH','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('FTTC','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('D-CCAP node (Remote PHY )','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('D-CCAP node (Remote MAC/PHY )','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('CO hosted xDSL','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Centralised CMTS','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('ACS/SDN Cont.','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('VPN Concentrator','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('USE OTHER CLUSTER','',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Switch','Low',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Supervisor','N.A.',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Router','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Radius','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Perimeter Router','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('NTP','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Load Balancer','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Line card','N.A.',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Ipsec Router','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Guest NAC','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Firewall','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('DNS','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Console Concentrator','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Access Point','Low',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Access Control Server','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('SRAN Baseband','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('RNC','Low',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Radio Equipment','Low',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('OSS (valid only for OSS assets in MAE)','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('BSC','Low',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('5G nodes','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('4G nodes','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('3G nodes','Low',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('2G nodes','Low',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Tools and databases update','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Site Built','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('OSS upgrade','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('New RAN SW releases upgrade','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Integration','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Installation','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Field Maintenance','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Fault Management','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Acceptance','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Distrib. MEC','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Core MEC','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('SA','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('NSA','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('NB-IoT','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('C-GSN','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('5G','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('4G','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('SON','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Remote Mgmt','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Probes, Call trace','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('PM, FM, Inventory','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('EMS (Core)','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('EMS (Access)','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Config Mgmt','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Workforce mgt','Medium/low',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('SLA mgt','Medium/low',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Service & Resource Diagnosis','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Service & Customer Monitoring','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Security mgt','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Resource Order management','Medium/low',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Remote Access','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Probes & call Trace','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Planning','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Other','Low',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Lab instrumentation','Medium/low',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('IT system mgt','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('IT System management','Medium/low',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Incident & Problem Mgt','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Identity Management','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Geo Information Management','Low',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Customer Experience management','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('BPM & Workflow','Medium/low',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Automation tools','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Access Control','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('WebRTC','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('SS7 Firewall','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Optimizer','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('NGIN','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('MSP','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Messaging','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Clean Pipe','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('CCS/SPO','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('TMF','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('IoT Core/C-SGN','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('DNS','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Core 5G(SA)','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('BNG','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('4G/5G NSA Packet Core EPC','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Value Added Services','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('TV Monitoring & Tools','Low',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('TV Distribution services','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('TV Compression services','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('TV Back end services','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Operation and Self-Care Portals','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Media Resource Function','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Call Control Applications','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Advanced Call Control Applications','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Enterprise CPE/Router','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Consumer CPE/Router','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Sec.GW','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Optical Backhaul','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Optical Backbone','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('NAT/FW','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('IP Microwave','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('IP Core Backbone','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('IP Backhaul','Medium',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Lawful intercept','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Contact Center','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('CLF','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('TSC-S','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('TAS','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('SBC','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('PCRF','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('MSS','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('MSC-S','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('MGW','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Interconnect-SBC','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('ENUM','High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('CSCF','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('CS','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('BGCF','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('Access-SBC','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('BSF','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('DRA','Very High',1,1,0);
INSERT INTO riskclusters (DESCRIPTION,RISKLEVEL,CREATIONUSER,MODIFICATIONUSER,DELETED) Values ('STP','Very High',1,1,0);

Commit;

CREATE TABLE Cluster_VFName (VFID INT, VFName NVARCHAR2(50), RiskClusterID INT, RiskCluster NVARCHAR2(50));

INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('UPF','UPF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('UDR','UDR');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('UDM','UDM');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SMF','SMF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SEPP','SEPP');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SEAF','SEAF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SCP','SCP');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('PCF','PCF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('NSSF','NSSF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('NRF','NRF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('NEF','NEF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('CHF','CHF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('AUSF','AUSF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('AMF','AMF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('5G EIR','5G EIR');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('X86 Compute','X86 Compute');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('VNFM','VNFM');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('VIM (eg Openstack)','VIM (eg Openstack)');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SDN (Underlay) Core Controllers','SDN (Underlay) Core Controllers');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SDN (Underlay) BH Controllers','SDN (Underlay) BH Controllers');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SDN (Overlay) Controllers','SDN (Overlay) Controllers');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Orchestrator','Orchestrator');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Hypervisor (ESXi, KVM)','Hypervisor (ESXi, KVM)');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('CaaS','CaaS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('STP','STP');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('DRA','DRA');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('UDM','UDM');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('HSS','HSS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('HLR','HLR');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('CSDB','CSDB');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('AuC','AuC');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Voice PCRF','Voice PCRF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SGSN/MME assets','SGSN/MME assets');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Securnet Assets','Securnet Assets');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('PCF','PCF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('MSP/WAP GW ','MSP/WAP GW ');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Gn/Gp DNS ','Gn/Gp DNS ');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Data PCRF','Data PCRF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('AAA','AAA');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('IP backend to remote Cable node','IP backend to remote Cable node');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('FTTH','FTTH');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('FTTC','FTTC');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('D-CCAP node (Remote PHY )','D-CCAP node (Remote PHY )');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('D-CCAP node (Remote MAC/PHY )','D-CCAP node (Remote MAC/PHY )');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('CO hosted xDSL','CO hosted xDSL');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Centralised CMTS','Centralised CMTS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('ACS/SDN Cont.','ACS/SDN Cont.');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('VPN Concentrator','VPN Concentrator');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('USE OTHER CLUSTER','USE OTHER CLUSTER');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Switch','Switch');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Supervisor','Supervisor');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Router','Router');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Radius','Radius');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Perimeter Router','Perimeter Router');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('NTP','NTP');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Load Balancer','Load Balancer');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Line card','Line card');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Ipsec Router','Ipsec Router');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Guest NAC','Guest NAC');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Firewall','Firewall');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('DNS','DNS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Console Concentrator','Console Concentrator');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Access Point','Access Point');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Access Control Server','Access Control Server');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SRAN Baseband','SRAN Baseband');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('RNC','RNC');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Radio Equipment','Radio Equipment');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('OSS (valid only for OSS assets in MAE)','OSS (valid only for OSS assets in MAE)');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('BSC','BSC');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('5G nodes','5G nodes');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('4G nodes','4G nodes');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('3G nodes','3G nodes');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('2G nodes','2G nodes');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Tools and databases update','Tools and databases update');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Site Built','Site Built');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('OSS upgrade','OSS upgrade');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('New RAN SW releases upgrade','New RAN SW releases upgrade');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Integration','Integration');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Installation','Installation');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Field Maintenance','Field Maintenance');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Fault Management','Fault Management');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Acceptance','Acceptance');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Distrib. MEC','Distrib. MEC');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Core MEC','Core MEC');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SA','SA');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('NSA','NSA');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('NB-IoT','NB-IoT');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('C-GSN','C-GSN');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('5G','5G');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('4G','4G');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SON','SON');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Remote Mgmt','Remote Mgmt');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Probes, Call trace','Probes, Call trace');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('PM, FM, Inventory','PM, FM, Inventory');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('EMS (Core)','EMS (Core)');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('EMS (Access)','EMS (Access)');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Config Mgmt','Config Mgmt');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Workforce mgt','Workforce mgt');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SLA mgt','SLA mgt');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Service & Resource Diagnosis','Service & Resource Diagnosis');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Service & Customer Monitoring','Service & Customer Monitoring');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Security mgt','Security mgt');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Resource Order management','Resource Order management');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Remote Access','Remote Access');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Probes & call Trace','Probes & call Trace');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Planning','Planning');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Other','Other');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Lab instrumentation','Lab instrumentation');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('IT system mgt','IT system mgt');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('IT System management','IT System management');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Incident & Problem Mgt','Incident & Problem Mgt');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Identity Management','Identity Management');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Geo Information Management','Geo Information Management');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Customer Experience management','Customer Experience management');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('BPM & Workflow','BPM & Workflow');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Automation tools','Automation tools');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Access Control','Access Control');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('WebRTC','WebRTC');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SS7 Firewall','SS7 Firewall');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Optimizer','Optimizer');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('NGIN','NGIN');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('MSP','MSP');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Messaging','Messaging');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Clean Pipe','Clean Pipe');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('CCS/SPO','CCS/SPO');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('TMF','TMF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('IoT Core/C-SGN','IoT Core/C-SGN');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('DNS','DNS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Core 5G(SA)','Core 5G(SA)');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('BNG','BNG');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('4G/5G NSA Packet Core EPC','4G/5G NSA Packet Core EPC');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Value Added Services','Value Added Services');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('TV Monitoring & Tools','TV Monitoring & Tools');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('TV Distribution services','TV Distribution services');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('TV Compression services','TV Compression services');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('TV Back end services','TV Back end services');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Operation and Self-Care Portals','Operation and Self-Care Portals');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Media Resource Function','Media Resource Function');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Call Control Applications','Call Control Applications');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Advanced Call Control Applications','Advanced Call Control Applications');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Enterprise CPE/Router','Enterprise CPE/Router');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Consumer CPE/Router','Consumer CPE/Router');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Sec.GW','Sec.GW');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Optical Backhaul','Optical Backhaul');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Optical Backbone','Optical Backbone');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('NAT/FW','NAT/FW');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('IP Microwave','IP Microwave');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('IP Core Backbone','IP Core Backbone');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('IP Backhaul','IP Backhaul');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Lawful intercept','Lawful intercept');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Contact Center','Contact Center');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('CLF','CLF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('TSC-S','TSC-S');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('TAS','TAS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SBC','SBC');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('PCRF','PCRF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('MSS','MSS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('MSC-S','MSC-S');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('MGW','MGW');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Interconnect-SBC','Interconnect-SBC');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('ENUM','ENUM');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('CSCF','CSCF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('CS','CS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('BGCF','BGCF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Access-SBC','Access-SBC');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('AGCF','CO hosted xDSL');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Backend','CSDB');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('BSF','BSF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('C4','CS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('C5','CS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Call Recording','CS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('CCDM','UDR');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('CCF','CSCF');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('CCSM','UDM');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('CRE','DRA');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('CUDB','CSDB');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Diameter Firewall','DRA');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Diameter Signalling','DRA');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('DNS','DNS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('EIR','CSDB');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Element Manager','EMS (Core)');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('EMM','CCS/SPO');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('G51','CS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('GMS','CS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('IPControl','DNS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('MRF','CS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('NPDB','CSDB');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Provisioning GW','EMS (Core)');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('QSBC','SBC');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('RSP','STP');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SCCPR','DRA');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SDL','CSDB');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Service Application Server','TAS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Smart Edge','TAS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('SoftSwitch','CS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('UPG','CSDB');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('USSD-GW','CS');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('Ut-Proxy','CSDB');
INSERT INTO Cluster_VFName (VFName, RiskCluster) Values ('WRT','WebRTC');

Commit;

desc vodafonenames;
Select Count(1) from riskclusters;
Select Count(1) from Cluster_VFName where vfid is null;


MERGE INTO Cluster_VFName rc using 
(
    select t1.rowid as rid , t2.ID as updatevalue 
    from Cluster_VFName t1
    join vodafonenames t2 ON t2.Description = t1.VFName
) src
on (rc.rowid = src.rid)
WHEN MATCHED THEN UPDATE
     SET rc.VFID = updatevalue;
Commit;

MERGE INTO Cluster_VFName rc using 
(
    select Distinct t1.rowid as rid , t2.RiskClusterID as updatevalue 
    from Cluster_VFName t1
    join riskclusters t2 ON t2.Description = t1.RiskCluster
) src
on (rc.rowid = src.rid)
WHEN MATCHED THEN UPDATE
     SET rc.RiskClusterID = updatevalue;
Commit;

--Select Distinct Description from riskclusters
--Select * from riskclusters where  Description IN (Select Description from riskclusters GROUP BY Description HAVING Count(Description) > 1);
--Select RiskCluster, RiskClusterId from Cluster_VFName where RiskClusterId IS NULL;
--Select Distinct VFID, RiskClusterID from Cluster_VFName
--Select Distinct RISKCLUSTERID,VODAFONENAMEID from RiskClusterVodafoneNames
--Delete from riskclusters where RiskClusterId in (286,325,326);
--commit;


INSERT INTO RiskClusterVodafoneNames (RISKCLUSTERID,VODAFONENAMEID,CREATIONUSER,MODIFICATIONUSER, DELETED)
SELECT Distinct RiskClusterID,VFID,1,1,0 from Cluster_VFName;

Commit;