DROP SEQUENCE PLANNEDACTIVITYTYPESID_SEQ;
 
CREATE SEQUENCE  "PLANNEDACTIVITYTYPESID_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999 
INCREMENT BY 1 START WITH  37 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
 
 DELETE PLANNEDACTIVITYTYPES WHERE PLANNEDACTIVITYTYPEDESCRIPTION = 'No Planned Activity For DA';
 
 COMMIT;