
ALTER TABLE DAASSETMIGRATION DROP COLUMN BOMSUBMITTEDDATE;
ALTER TABLE DAASSETMIGRATION DROP COLUMN HWPORAISEDDATE;
ALTER TABLE DAASSETMIGRATION DROP COLUMN HWPOARRIVEDDATE;
ALTER TABLE DAASSETMIGRATION DROP COLUMN RFADATE;
COMMIT;

ALTER TABLE NETWORKELEMENTSASPLANNED DROP COLUMN BOMSUBMITTEDDATE;
ALTER TABLE NETWORKELEMENTSASPLANNED DROP COLUMN HWPORAISEDDATE;
ALTER TABLE NETWORKELEMENTSASPLANNED DROP COLUMN HWPOARRIVEDDATE;
ALTER TABLE NETWORKELEMENTSASPLANNED DROP COLUMN RFADATE;
COMMIT;

