ALTER TABLE VNFCLUSTERINFO ADD HARDWARETYPE NVARCHAR2(50);  

MERGE INTO VNFCLUSTERINFO t
USING VNFHARDWARE s
ON (t.HARDWARETYPEID = s.VNFHARDWAREID)
WHEN MATCHED THEN UPDATE SET t.HARDWARETYPE = s.DESCRIPTION;

ALTER TABLE VNFCLUSTERINFO MODIFY HARDWARETYPE NOT NULL;

ALTER TABLE VNFCLUSTERINFO DROP COLUMN HARDWARETYPEID;
