CREATE SEQUENCE CATEGORIES_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  COMMIT;
  
  --------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "CATEGORIES" 
   (	"ID" NUMBER(10,0) DEFAULT "CATEGORIES_SEQ"."NEXTVAL"  NOT NULL, 
	"DESCRIPTION" VARCHAR2(255 BYTE) NOT NULL,
	"CREATIONUSER" NUMBER(10,0) NOT NULL, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp)  NOT NULL, 
	"MODIFICATIONUSER" NUMBER(10,0) NOT NULL, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp) NOT NULL , 
	"DELETED" NUMBER(1,0) DEFAULT 0 NOT NULL, 
	"DELETIONDATE" TIMESTAMP (6) NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CAMDB" ;
  COMMIT;
--------------------------------------------------------
--  DDL for Index CATEGORIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CATEGORIES_PK" ON "CATEGORIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------
  ALTER TABLE "CATEGORIES" ADD CONSTRAINT "CATEGORIES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATEGORIES
--------------------------------------------------------
  ALTER TABLE "CATEGORIES" ADD CONSTRAINT "FK_CATEGORIES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CATEGORIES" ADD CONSTRAINT "FK_CATEGORIES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  
  ALTER TABLE CATEGORIES
MODIFY(ID  DEFAULT "CATEGORIES_SEQ"."NEXTVAL");
COMMIT;

-----------------------------------------------------
-- insert default categories
----------------------------------------------------
  -- ****** Replace 177 with admin Id
set define off;
INSERT INTO CATEGORIES (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER  ) VALUES ('IP Address',177,177);
INSERT INTO CATEGORIES (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER  ) VALUES ('Point Code',177,177);
INSERT INTO CATEGORIES (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER  ) VALUES ('FQDN',177,177);
INSERT INTO CATEGORIES (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER  ) VALUES ('Global Title',177,177);
INSERT INTO CATEGORIES (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER  ) VALUES ('O&M Host Name',177,177);
commit;
set define on;