CREATE SEQUENCE CLASSES_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  COMMIT;
  
  --------------------------------------------------------
--  DDL for Table CLASSES
--------------------------------------------------------

  CREATE TABLE "CLASSES" 
   (	"ID" NUMBER(10,0) DEFAULT "CLASSES_SEQ"."NEXTVAL", 
	"DESCRIPTION" VARCHAR2(255 BYTE) NOT NULL,
	"CATEGORYID" NUMBER(10,0) NOT NULL,
	"CREATIONUSER" NUMBER(10,0) NOT NULL, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) NOT NULL, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6) NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index CLASSES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLASSES_PK" ON "CLASSES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table CLASSES
--------------------------------------------------------

  ALTER TABLE "CLASSES" ADD CONSTRAINT "CLASSES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLASSES
--------------------------------------------------------

  ALTER TABLE "CLASSES" ADD CONSTRAINT "FK_CLASSES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CLASSES" ADD CONSTRAINT "FK_CLASSES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CLASSES" ADD CONSTRAINT "FK_CLASSES_CATEGORIES_CATEGORYID" FOREIGN KEY ("CATEGORYID")
	  REFERENCES "CATEGORIES" ("ID") ENABLE;

  
  ALTER TABLE CLASSES
MODIFY(ID  DEFAULT "CLASSES_SEQ"."NEXTVAL");
COMMIT;

-----------------------------------------------------
-- insert default classes
----------------------------------------------------
  -- ****** Replace 177 with admin Id
INSERT INTO CLASSES (DESCRIPTION,CATEGORYID,CREATIONUSER,MODIFICATIONUSER  ) VALUES ('VRF',1,177,177);
INSERT INTO CLASSES (DESCRIPTION,CATEGORYID,CREATIONUSER,MODIFICATIONUSER  ) VALUES ('VPN',1,177,177);
INSERT INTO CLASSES (DESCRIPTION,CATEGORYID,CREATIONUSER,MODIFICATIONUSER  ) VALUES ('AN',1,177,177);
commit;