CREATE SEQUENCE TYPES_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  COMMIT;
  
  --------------------------------------------------------
--  DDL for Table TYPES
--------------------------------------------------------

  CREATE TABLE "TYPES" 
   ("ID" NUMBER(10,0) DEFAULT "TYPES_SEQ"."NEXTVAL", 
	"DESCRIPTION" VARCHAR2(255 BYTE) NOT NULL, 
	"CLASSID" NUMBER(10,0) NOT NULL,
	"CREATIONUSER" NUMBER(10,0) NOT NULL, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) NOT NULL, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6) NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index TYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TYPES_PK" ON "TYPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table TYPES
--------------------------------------------------------
  ALTER TABLE "TYPES" ADD CONSTRAINT "TYPES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TYPES
--------------------------------------------------------

  ALTER TABLE "TYPES" ADD CONSTRAINT "FK_TYPES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "TYPES" ADD CONSTRAINT "FK_TYPES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE; 
 ALTER TABLE "TYPES" ADD CONSTRAINT "FK_TYPES_CLASSES_CLASSID" FOREIGN KEY (CLASSID)
	  REFERENCES "CLASSES" ("ID") ENABLE;
  
  ALTER TABLE TYPES
MODIFY(ID  DEFAULT "TYPES_SEQ"."NEXTVAL");
COMMIT