CREATE SEQUENCE IDENTITIESASIS_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  COMMIT;
  
  --------------------------------------------------------
--  DDL for Table IDENTITIESASIS
--------------------------------------------------------

  CREATE TABLE "IDENTITIESASIS" 
   ("ID" NUMBER(10,0) DEFAULT "IDENTITIESASIS_SEQ"."NEXTVAL" NOT NULL, 
	"VALUE" VARCHAR2(255 BYTE) NULL, 
	"RESOURCEKEY" VARCHAR2(255 BYTE) NULL, 
	"PREVIOUSRESOURCEKEY" VARCHAR2(255 BYTE) NULL, 
	"ASSETID" NUMBER(19,0) NOT NULL,
	"CATEGORYID" NUMBER(10,0) NULL,
	"CLASSID" NUMBER(10,0) NULL,
	"TYPEID" NUMBER(10,0) NULL,
	"CREATIONUSER" NUMBER(10,0) NOT NULL, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp) NOT NULL, 
	"MODIFICATIONUSER" NUMBER(10,0) NOT NULL, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp)  NOT NULL, 
	"DELETED" NUMBER(1,0) DEFAULT 0  NOT NULL, 
	"DELETIONDATE" TIMESTAMP (6) NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index IDENTITIESASIS_PK
--------------------------------------------------------
  CREATE UNIQUE INDEX "IDENTITIESASIS_PK" ON "IDENTITIESASIS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table IDENTITIESASIS
--------------------------------------------------------

  ALTER TABLE "IDENTITIESASIS" ADD CONSTRAINT "IDENTITIESASIS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IDENTITIESASIS
--------------------------------------------------------

  ALTER TABLE "IDENTITIESASIS" ADD CONSTRAINT "FK_IDENTITIESASIS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "IDENTITIESASIS" ADD CONSTRAINT "FK_IDENTITIESASIS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
 ALTER TABLE "IDENTITIESASIS" ADD CONSTRAINT "FK_IDENTITIESASIS_CATEGORIES_CATEGORYID" FOREIGN KEY ("CATEGORYID")
	  REFERENCES "CATEGORIES" ("ID") ENABLE;
 ALTER TABLE "IDENTITIESASIS" ADD CONSTRAINT "FK_IDENTITIESASIS_CLASSES_CLASSID" FOREIGN KEY (CLASSID)
	  REFERENCES "CLASSES" ("ID") ENABLE;
 ALTER TABLE "IDENTITIESASIS" ADD CONSTRAINT "FK_IDENTITIESASIS_TYPES_TYPEID" FOREIGN KEY (TYPEID)
	  REFERENCES "TYPES" ("ID") ENABLE;
 ALTER TABLE "IDENTITIESASIS" ADD CONSTRAINT "FK_IDENTITIESASIS_ASSETS_ASSETID" FOREIGN KEY (ASSETID)
	  REFERENCES "NETWORKELEMENTSASPLANNED" ("NETWORKELEMENTASPLANNEDID") ENABLE;
  
  ALTER TABLE IDENTITIESASIS
MODIFY(ID  DEFAULT "IDENTITIESASIS_SEQ"."NEXTVAL");
COMMIT;