CREATE SEQUENCE LCMDBEXPORTUPDATEHISTORY_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  COMMIT;

--------------------------------------------------------
--  DDL for Table LCMDBEXPORTUPDATEHISTORY
--------------------------------------------------------

  CREATE TABLE "LCMDBEXPORTUPDATEHISTORY" 
   (	"ID" NUMBER(5,0) DEFAULT "LCMDBEXPORTUPDATEHISTORY_SEQ"."NEXTVAL", 
	"LASTHWUPDATEDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"LASTSWUPDATEDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp),
	"CREATIONUSER" NUMBER(10,0) DEFAULT (null), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT (null), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6) DEFAULT (null)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index LCMDBEXPORTUPDATEHISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LCMDBEXPORTUPDATEHISTORY_PK" ON "LCMDBEXPORTUPDATEHISTORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table LCMDBEXPORTUPDATEHISTORY
--------------------------------------------------------

  ALTER TABLE "LCMDBEXPORTUPDATEHISTORY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LCMDBEXPORTUPDATEHISTORY" MODIFY ("LASTHWUPDATEDATE" NOT NULL ENABLE);
    ALTER TABLE "LCMDBEXPORTUPDATEHISTORY" MODIFY ("LASTSWUPDATEDATE" NOT NULL ENABLE);
  ALTER TABLE "LCMDBEXPORTUPDATEHISTORY" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "LCMDBEXPORTUPDATEHISTORY" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "LCMDBEXPORTUPDATEHISTORY" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "LCMDBEXPORTUPDATEHISTORY" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "LCMDBEXPORTUPDATEHISTORY" ADD CONSTRAINT "LCMDBEXPORTUPDATEHISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX "LCMDBEXPORTUPDATEHISTORY_PK"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LCMDBEXPORTUPDATEHISTORY
--------------------------------------------------------

  ALTER TABLE "LCMDBEXPORTUPDATEHISTORY" ADD CONSTRAINT "FK_LCMDBEXPORTUPDATEHISTORY_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "LCMDBEXPORTUPDATEHISTORY" ADD CONSTRAINT "FK_LCMDBEXPORTUPDATEHISTORY_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;

  ALTER TABLE LCMDBEXPORTUPDATEHISTORY
MODIFY(ID  DEFAULT "LCMDBEXPORTUPDATEHISTORY_SEQ"."NEXTVAL");

INSERT INTO LCMDBEXPORTUPDATEHISTORY(LASTHWUPDATEDATE,LASTSWUPDATEDATE, CREATIONUSER, CREATIONDATE, MODIFICATIONUSER, MODIFICATIONDATE)
VALUES (CURRENT_TIMESTAMP - 1, CURRENT_TIMESTAMP - 1, 177, CURRENT_TIMESTAMP, 177, CURRENT_TIMESTAMP);
commit;
