---------------------------------------------------
--add asset fields
--------------------------------------------------
ALTER TABLE NETWORKELEMENTSASPLANNED ADD
(
"HWRESOURCEKEY" VARCHAR2(255 BYTE) NULL,
"PREVIOUSHWRESOURCEKEY" VARCHAR2(255 BYTE) NULL,
"SWRESOURCEKEY" VARCHAR2(255 BYTE) NULL,
"PREVIOUSSWRESOURCEKEY" VARCHAR2(255 BYTE) NULL
);
COMMIT;

-------------------------------------------------------
--ADD LCM ENGINEERING FIEDLS
-------------------------------------------------------
ALTER TABLE LCMENGINEERING ADD
(
"RESOURCEKEY" VARCHAR2(255 BYTE) NULL,
"PREVIOUSRESOURCEKEY" VARCHAR2(255 BYTE) NULL,
"ISEXTENDEDSUPPORTOFFEREDBYVENDOR" NUMBER(1,0) NULL,
"HWISEXTENDEDSUPPORTOFFEREDBYVENDOR" NUMBER(1,0) NULL
);
COMMIT;
--------------------------------------------------------
--ADD DESIGN ASPECTS FIELDS
--------------------------------------------------------
ALTER TABLE DESIGNASPECTS ADD
(
"NOMINALCAPACITYLIMIT" VARCHAR2(255 BYTE) NULL,
"DESIGNEDCAPACITYLIMIT" VARCHAR2(255 BYTE) NULL,
"MAXALLOWEDLOADING" VARCHAR2(255 BYTE) NULL
);
COMMIT;

--need to double check if this field or no try to run it
ALTER TABLE MAJORSOFTWAREBUILDS 
RENAME COLUMN "Description" TO "DESCRIPTION";

ALTER TABLE MAJORHARDWAREBUILDS 
RENAME COLUMN "Description" TO "DESCRIPTION";

commit;
