CREATE SEQUENCE DELIVERYTRACKINGS_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  COMMIT;
  
  --------------------------------------------------------
--  DDL for Table DELIVERYTRACKINGS
--------------------------------------------------------

  CREATE TABLE "DELIVERYTRACKINGS" 
   (	"ID" NUMBER(10,0) DEFAULT "DELIVERYTRACKINGS_SEQ"."NEXTVAL"  NOT NULL, 
	"PLANNEDACTIVITYID" NUMBER(19, 0) NULL,
	"ACTIVITY" VARCHAR2(255 BYTE) NULL,
    "MS1EVENTTYPE" NUMBER(10, 0) NULL,
    "MS1BASELINEDATE" TIMESTAMP (6) NULL,
    "MS1LATESTPLANNINGDATE" TIMESTAMP (6) NULL,
    "MS1STATUS" NUMBER(10, 0) NULL,
    "MS2EVENTTYPE" NUMBER(10, 0) NULL,
    "MS2BASELINEDATE" TIMESTAMP (6) NULL,
    "MS2LATESTPLANNINGDATE" TIMESTAMP (6) NULL,
    "MS2STATUS" NUMBER(10, 0) NULL,
    "MS3EVENTTYPE" NUMBER(10, 0) NULL,
    "MS3BASELINEDATE" TIMESTAMP (6) NULL,
    "MS3LATESTPLANNINGDATE" TIMESTAMP (6) NULL,
    "MS3STATUS" NUMBER(10, 0) NULL,
    "MS4EVENTTYPE" NUMBER(10, 0) NULL,
    "MS4BASELINEDATE" TIMESTAMP (6) NULL,
    "MS4LATESTPLANNINGDATE" TIMESTAMP (6) NULL,
    "MS4STATUS" NUMBER(10, 0) NULL,
    "PPMIMPORTDATE" TIMESTAMP (6) NULL,
    "NOTES1" VARCHAR2(255 BYTE) NULL,
	"NOTES2" VARCHAR2(255 BYTE) NULL,
    "CREATIONUSER" NUMBER(10,0) NOT NULL, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp)  NOT NULL, 
	"MODIFICATIONUSER" NUMBER(10,0) NOT NULL, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp) NOT NULL , 
	"DELETED" NUMBER(1,0) DEFAULT 0 NOT NULL, 
	"DELETIONDATE" TIMESTAMP (6) NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CAMDB" ;
  COMMIT;
--------------------------------------------------------
--  DDL for Index DELIVERYTRACKINGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DELIVERYTRACKINGS_PK" ON "DELIVERYTRACKINGS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB" ;
  COMMIT;
--------------------------------------------------------
--  Constraints for Table DELIVERYTRACKINGS
--------------------------------------------------------
  ALTER TABLE "DELIVERYTRACKINGS" ADD CONSTRAINT "DELIVERYTRACKINGS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB"  ENABLE;
  COMMIT;
--------------------------------------------------------
--  Ref Constraints for Table DELIVERYTRACKINGS
--------------------------------------------------------
  ALTER TABLE "DELIVERYTRACKINGS" ADD CONSTRAINT "FK_DELIVERYTRACKINGS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "DELIVERYTRACKINGS" ADD CONSTRAINT "FK_DELIVERYTRACKINGS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
   ALTER TABLE "DELIVERYTRACKINGS" ADD CONSTRAINT "FK_DELIVERYTRACKINGS_PLANNEDACTIVITIES_PLANNEDACTIVITYID" FOREIGN KEY ("PLANNEDACTIVITYID")
	  REFERENCES "PLANNEDACTIVITIES" ("PLANNEDACTIVITYID") ENABLE;
  ALTER TABLE DELIVERYTRACKINGS
MODIFY(ID  DEFAULT "DELIVERYTRACKINGS_SEQ"."NEXTVAL");
COMMIT;

-------------------------------------------------------------
--ADD DELEVIRY TRACKING AVAILABLE TO PLANNED ACTIVITY
-------------------------------------------------------------
ALTER TABLE PLANNEDACTIVITIES ADD "DELIVERYPLANAVAILABLE" NUMBER(1,0) DEFAULT 0 NOT NULL;
COMMIT;