
---------RB SCRIPT FOR SYSTEMVERIFICATIONPROBLEMS------------
DROP SEQUENCE SYSTEMVERIFICATIONPROBLEMS_SEQ;
DROP TABLE SYSTEMVERIFICATIONPROBLEMS;
COMMIT;
---------RB SCRIPT FOR SEVERITY---------
DROP SEQUENCE SEVERITY_SEQ;
DROP TABLE SEVERITY;
COMMIT;
---------RB SCRIPT FOR PROBLEMCATEGORY-------
DROP SEQUENCE PROBLEMCATEGORY_SEQ;
DROP TABLE PROBLEMCATEGORY;
COMMIT;