--- EXoDus - PRODUCT Table add new column

ALTER TABLE PRODUCTNAME DROP COLUMN  ISPLATFORMSOFTWARE 0;
 
---------------- New two rules for DA - Exodus 
DROP SEQUENCE PLANNEDACTIVITYTYPESID_SEQ;

CREATE SEQUENCE  "PLANNEDACTIVITYTYPESID_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999 
INCREMENT BY 1 START WITH  18 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


delete from PLANNEDACTIVITYTYPES where  PLANNEDACTIVITYTYPEDESCRIPTION in ('Infra Readiness','Platform Migration'); 

COMMIT; 

DROP SEQUENCE DAMIGRATIONSTATUS_SQE;
DROP TABLE DAMIGRATIONSTATUS ; 