using CAM.Entities.Mappers.Identity;
using CAM.Entities.Models.PassThroughData;
using OracleModels.DBModels;

namespace CAM.Entities.Mappers.Entity
{
    public class AssetPassThroughMapper
    {
        public static AssetPassThrough Get(Assetpassthrough model)
        {
            if (model == null)
                return null;
            var result = new AssetPassThrough()
            {
                PassThroughId = model.Passthroughid,
                NonTemsVertical = model.Nontemsvertical,
                VerticalName=model.NontemsverticalNavigation?.Verticalresponsible,
                VodafoneUniqueIdentifier = model.Vodafoneuniqueidentifier,
                AssetName = model.Assetname,
                AssetDescriptionOrPurpose = model.Assetdescriptionorpurpose,
                AssetType = model.Assettype,
                BusinessOwner = model.Businessowner,
                SupportOwner = model.Supportowner,
                SupportTeam = model.Supportteam,
                SupportTeamsPlaceInTheOrganisation = model.Supportteamsplaceintheorganisation,
                AssetFunction = model.Assetfunction,
                DeploymentOrLifeCycleStatus = model.Deploymentorlifecyclestatus,
                RelatedRiskIdsFromRiskRegisters = model.Relatedriskidsfromriskregisters,
                RegulatoryScope = model.Regulatoryscope,
                CountryWhereAssetIsLocated = model.Countrywhereassetislocated,
                Geolocation = model.Geolocation,
                Infrastructure = model.Infrastructure,
                UpStreamDependencies = model.Upstreamdependencies,
                DownStreamDependencies = model.Downstreamdependencies,
                ChangesToTheassetSinceDeployment = model.Changestotheassetsincedeployment,
                CloudHostedAsset = model.Cloudhostedasset,
                CloudType = model.Cloudtype,
                CloudVendor = model.Cloudvendor,
                EquipmentName = model.Equipmentname,
                HostLocationWithInPhysicalLocation = model.Hostlocationwithinphysicallocation,
                FirmwareVersionPatchLevel = model.Firmwareversionpatchlevel,
                MaintenanceSupportSupplier = model.Maintenancesupportsupplier,
                DependantHardware = model.Dependanthardware,
                InstanceType = model.Instancetype,
                OperatingSystemName = model.Operatingsystemname,
                OperatingSystemSwvVersion = model.Operatingsystemswvversion,
                OperatingSystemSwVersionPatchLevel = model.Operatingsystemswversionpatchlevel,
                SystemNameDns = model.Systemnamedns,
                SystemNameManagementIpAddress = model.Systemnamemanagementipaddress,
                SystemNameNetBios = model.Systemnamenetbios,
                SystemNameHostName = model.Systemnamehostname,
                MaintenanceSupportSupplierSecond = model.Maintenancesupportsuppliersecond,
                DependantSystemSoftware = model.Dependantsystemsoftware,
                ResilienceModel = model.Resiliencemodel,
                GeographicSiteResilience = model.Geographicsiteresilience,
                LocalSiteResilience = model.Localsiteresilience,
                NameOfProductsDependantOnAsset = model.Nameofproductsdependantonasset,
                Customer = model.Customer,
                PrivilegedAccessLogging = model.Privilegedaccesslogging,
                BoardOrModuleNameComponentName = model.Boardormodulenamecomponentname,
                ExposedEdge = model.Exposededge,
                ExternallyFacingSystem = model.Externallyfacingsystem,
                ManagementPlane = model.Managementplane,
                NetworkOverSightFunction = model.Networkoversightfunction,
                Pecn = model.Pecn,
                Pecs = model.Pecs,
                SecurityCriticalFunction = model.Securitycriticalfunction,
                Critical = model.Critical,
                PartNumber = model.Partnumber,
                ProdOrLab = model.Prodorlab,
                LocalMarketOwnerShip = model.Localmarketownership,
                AssuranceCall = model.Assurancecall,
                ServiceLevel = model.Servicelevel,
                LastPenTestRefNo = model.Lastpentestrefno,
                PiData = model.Pidata,
                EncryptedPiData = model.Encryptedpidata,
                MaintenanceHardwareEndOfSupportDate = model.Maintenancehardwareendofsupportdate,
                DateAssetMovedToLiveStatus = model.Dateassetmovedtolivestatus,
                DateAssetDecommissioned = model.Dateassetdecommissioned,
                FirmwareVersion = model.Firmwareversion,
                BoardOrModuleTypeComponentSubtype = model.Boardormoduletypecomponentsubtype,
                BoardOrModuleTypeComponentVersionNumber = model.Boardormoduletypecomponentversionnumber,
                SerialNumber = model.Serialnumber,
                HardwareTypeofHardwareAsset = model.Hardwaretypeofhardwareasset,
                HwEndofSale = model.Hwendofsale,
                SoftwareProductType = model.Softwareproducttype,
                ApplicationHostedonSoftware = model.Applicationhostedonsoftware,
                UuidorSerialNumberofSoftware = model.Uuidorserialnumberofsoftware,
                SwEndofSale = model.Swendofsale,
                Application = model.Application,
                PhysicalServerHostName = model.Physicalserverhostname,
                PhysicalServerIpaddress = model.Physicalserveripaddress,
                PhysicalServerSerialNumber = model.Physicalserverserialnumber,
                PhysicalServerHwModel = model.PhysicalserverhwModel,
                PhysicalServerVendor = model.Physicalservervendor,
                VirtualServerHostedon = model.Virtualserverhostedon,
                VirtualServerManufacturer = model.Virtualservermanufacturer,
                VirtualServerTypeofDevice = model.Virtualservertypeofdevice,
                VirtualMachineType = model.Virtualmachinetype,
                VirtualServerSerialNumber = model.Virtualserverserialnumber,
                VirtualServerType = model.Virtualservertype,
                OsStartDate = model.Osstartdate,
                OsInstallationDate = model.Osinstallationdate,
                OsStatus = model.Osstatus,
                SoftwareName = model.Softwarename,
                Version = model.Version,
                Release = model.Release,
                Language = model.Language,
                HwOpsContractStatus = model.Hwopscontractstatus,
                SwOpsContractStatus = model.Swopscontractstatus,
                PlannedHwModel = model.Plannedhwmodel,
                LocationOrDatacentre = model.Locationordatacentre,
                PhysicalServerOSName = model.Physicalserverosname,
                PhysicalOSVersion = model.Physicalosversion,
                PhysicalServerOSStartDate = model.Physicalserverosstartdate,
                PhysicalServerOSinstallationdate = model.Physicalserverosinstallationdate,
                PhysicalServerOSstatus = model.Physicalserverosstatus,
                Cloud = model.Cloud,
                ResourceKey = model.Resourcekey,
                CreationDate = model.Creationdate,
                CreationUser = model.Creationuser,
                ModificationDate = model.Modificationdate,
                ModificationUser = model.Modificationuser,
                CreationUserEntity = ApplicationUserMapper.GetApplicationUserMapper(model.CreationuserNavigation),
                ModificationUserEntity = ApplicationUserMapper.GetApplicationUserMapper(model.ModificationuserNavigation),    
                
            };
            if (model.ResourcekeyNavigation != null)
                result.ResourceKeyNavigation = SwPassThroughLcmMapper.Get(model.ResourcekeyNavigation);
            return result;
        }

        public static Assetpassthrough Set(AssetPassThrough model)
        {
            if (model == null)
                return null;
            var result = new Assetpassthrough()
            {
                Passthroughid = model.PassThroughId,
                Nontemsvertical = (int?)model.NonTemsVertical,
                Vodafoneuniqueidentifier = model.VodafoneUniqueIdentifier,
                Assetname = model.AssetName,
                Assetdescriptionorpurpose = model.AssetDescriptionOrPurpose,
                Assettype = model.AssetType,
                Businessowner = model.BusinessOwner,
                Supportowner = model.SupportOwner,
                Supportteam = model.SupportTeam,
                Supportteamsplaceintheorganisation = model.SupportTeamsPlaceInTheOrganisation,
                Assetfunction = model.AssetFunction,
                Deploymentorlifecyclestatus = model.DeploymentOrLifeCycleStatus,
                Relatedriskidsfromriskregisters = model.RelatedRiskIdsFromRiskRegisters,
                Regulatoryscope = model.RegulatoryScope,
                Countrywhereassetislocated = model.CountryWhereAssetIsLocated,
                Geolocation = model.Geolocation,
                Infrastructure = model.Infrastructure,
                Upstreamdependencies = model.UpStreamDependencies,
                Downstreamdependencies = model.DownStreamDependencies,
                Changestotheassetsincedeployment = model.ChangesToTheassetSinceDeployment,
                Cloudhostedasset = model.CloudHostedAsset,
                Cloudtype = model.CloudType,
                Cloudvendor = model.CloudVendor,
                Equipmentname = model.EquipmentName,
                Hostlocationwithinphysicallocation = model.HostLocationWithInPhysicalLocation,
                Firmwareversionpatchlevel = model.FirmwareVersionPatchLevel,
                Maintenancesupportsupplier = model.MaintenanceSupportSupplier,
                Dependanthardware = model.DependantHardware,
                Instancetype = model.InstanceType,
                Operatingsystemname = model.OperatingSystemName,
                Operatingsystemswvversion = model.OperatingSystemName,
                Operatingsystemswversionpatchlevel = model.OperatingSystemSwVersionPatchLevel,
                Systemnamedns = model.SystemNameDns,
                Systemnamemanagementipaddress = model.SystemNameManagementIpAddress,
                Systemnamenetbios = model.SystemNameNetBios,
                Systemnamehostname = model.SystemNameHostName,
                Maintenancesupportsuppliersecond = model.MaintenanceSupportSupplierSecond,
                Dependantsystemsoftware = model.DependantSystemSoftware,
                Resiliencemodel = model.ResilienceModel,
                Geographicsiteresilience = model.GeographicSiteResilience,
                Localsiteresilience = model.LocalSiteResilience,
                Nameofproductsdependantonasset = model.NameOfProductsDependantOnAsset,
                Customer = model.Customer,
                Privilegedaccesslogging = model.PrivilegedAccessLogging,
                Boardormodulenamecomponentname = model.BoardOrModuleNameComponentName,
                Exposededge = model.ExposedEdge,
                Externallyfacingsystem = model.ExternallyFacingSystem,
                Managementplane = model.ManagementPlane,
                Networkoversightfunction = model.NetworkOverSightFunction,
                Pecn = model.Pecn,
                Pecs = model.Pecs,
                Securitycriticalfunction = model.SecurityCriticalFunction,
                Critical = model.Critical,
                Partnumber = model.PartNumber,
                Prodorlab = model.ProdOrLab,
                Localmarketownership = model.LocalMarketOwnerShip,
                Assurancecall = model.AssuranceCall,
                Servicelevel = model.ServiceLevel,
                Lastpentestrefno = model.LastPenTestRefNo,
                Pidata = model.PiData,
                Encryptedpidata = model.EncryptedPiData,
                Maintenancehardwareendofsupportdate = model.MaintenanceHardwareEndOfSupportDate,
                Dateassetmovedtolivestatus = model.DateAssetMovedToLiveStatus,
                Dateassetdecommissioned = model.DateAssetDecommissioned,
                Firmwareversion = model.FirmwareVersion,
                Boardormoduletypecomponentsubtype = model.BoardOrModuleTypeComponentSubtype,
                Boardormoduletypecomponentversionnumber = model.BoardOrModuleTypeComponentVersionNumber,
                Serialnumber = model.SerialNumber,
                Hardwaretypeofhardwareasset = model.HardwareTypeofHardwareAsset,
                Hwendofsale = model.HwEndofSale,
                Softwareproducttype = model.SoftwareProductType,
                Applicationhostedonsoftware = model.ApplicationHostedonSoftware,
                Uuidorserialnumberofsoftware = model.UuidorSerialNumberofSoftware,
                Swendofsale = model.SwEndofSale,
                Application = model.Application,
                Physicalserverhostname = model.PhysicalServerHostName,
                Physicalserveripaddress = model.PhysicalServerIpaddress,
                Physicalserverserialnumber = model.PhysicalServerSerialNumber,
                PhysicalserverhwModel = model.PhysicalServerHwModel,
                Physicalservervendor = model.PhysicalServerVendor,
                Virtualserverhostedon = model.VirtualServerHostedon,
                Virtualservermanufacturer = model.VirtualServerManufacturer,
                Virtualservertypeofdevice = model.VirtualServerTypeofDevice,
                Virtualmachinetype = model.VirtualMachineType,
                Virtualserverserialnumber = model.VirtualServerSerialNumber,
                Virtualservertype = model.VirtualServerType,
                Osstartdate = model.OsStartDate,
                Osinstallationdate = model.OsInstallationDate,
                Osstatus = model.OsStatus,
                Softwarename = model.SoftwareName,
                Version = model.Version,
                Release = model.Release,
                Language = model.Language,
                Hwopscontractstatus = model.HwOpsContractStatus,
                Swopscontractstatus = model.SwOpsContractStatus,
                Plannedhwmodel = model.PlannedHwModel,
                Locationordatacentre = model.LocationOrDatacentre,
                Physicalserverosname = model.PhysicalServerOSName,
                Physicalosversion = model.PhysicalOSVersion,
                Physicalserverosstartdate = model.PhysicalServerOSStartDate,
                Physicalserverosinstallationdate = model.PhysicalServerOSinstallationdate,
                Physicalserverosstatus = model.PhysicalServerOSstatus,
                Cloud = model.Cloud,
                Resourcekey = model.ResourceKey
            };
            return result;
        }

    }
}
