using CAM.Entities.Mappers.Identity;
using CAM.Entities.Models.PassThroughData;
using OracleModels.DBModels;

namespace CAM.Entities.Mappers.Entity
{
    public class SwPassThroughLcmMapper
    {
        public static SwPassThroughLcm Get(Swpassthroughlcm model)
        {
            if (model == null)
                return null;
            var result = new SwPassThroughLcm()
            {
                PassThroughLcmId = model.Passthroughlcmid,
                NonTemsVertical = model.Nontemsvertical,
                ReportId = model.Reportid,
                LocalMarket = model.Localmarket,
                VerticalEngineeringTeam = model.Verticalengineeringteam,
                VerticalSubDomain = model.Verticalsubdomain,
                EngineeringContactPoint = model.Engineeringcontactpoint,
                SWOperationsContactPoint = model.Swoperationscontactpoint,
                AssetCategory = model.Assetcategory,
                AssetClass = model.Assetclass,
                AssetType = model.Assettype,
                AssetDescription = model.Assetdescription,
                AssetVirtualized = model.Assetvirtualized,
                ProductImportance = model.Productimportance,
                SWVendor = model.Swvendor,
                HardwareModel = model.Hardwaremodel,
                ProductCode = model.Productcode,
                SoftwareVersion = model.Softwareversion,
                NumberOfNodes = model.Numberofnodes,
                HandedOverToOperation = model.Handedovertooperation,
                SWOperationsMaintenanceContract = model.Swoperationsmaintenancecontract,
                ContractRenewalPlan = model.Contractrenewalplan,
                SWVendorEndOfMaintenanceDate = model.Swvendorendofmaintenancedate,
                VendorEndOfVulnerabilitySecuritySupportDate = model.Vendorendofvulnerabilitysecuritysupportdate,
                LcmStatus = model.Lcmstatus,
                IdentifiedAction = model.Identifiedaction,
                DescriptionOfPlannedAction = model.Descriptionofplannedaction,
                PlannedSoftwareVersion = model.Plannedsoftwareversion,
                ProjectStatus = model.Projectstatus,
                ReasonfornoPlan = model.Reasonfornoplan,
                CommentonProjectStatus = model.Commentonprojectstatus,
                ProjectEndDate = model.Projectenddate,
                RagStatus = model.Ragstatus,
                TrackingNumberProjectName = model.Trackingnumberprojectname,
                Program = model.Program,
                WbsCode = model.Wbscode,
                BptID = model.Bptid,
                PpmID = model.Ppmid,
                ScopeOfSimplification = model.Scopeofsimplification,
                DataSource = model.Datasource,
                ProjectOwner = model.Projectowner,
                BudgetEstimated = model.Budgetestimated,
                Notes = model.Notes,
                BundleBudget = model.Bundlebudget,
                BundleId = model.Bundleid,
                AssetServiceFunctionality = model.Assetservicefunctionality,
                Platform = model.Platform,
                LcmStatusEngSoftware = model.Lcmstatusengsoftware,
                LcmStatusOpsSoftware = model.Lcmstatusopssoftware,
                SWOpsMaintenanceConractEndDate = model.Swopsmaintenanceconractenddate,
                EngRiskEvaluation = model.Engriskevaluation,
                EngRiskEvaluationNotes = model.Engriskevaluationnotes,
                OpsRiskEvaluation = model.Opsriskevaluation,
                OpsRiskEvaluationNotes = model.Opsriskevaluationnotes,
                IncidentClass = model.Incidentclass,
                OccurrenceProbability = model.Occurrenceprobability,
                NewopsRiskEvaluation = model.Newopsriskevaluation,
                OverallRiskEvaluation = model.Overallriskevaluation,
                RiskCluster = model.Riskcluster,
                SecurityRiskPotential = model.Securityriskpotential,
                VulnerabilityScore = model.Vulnerabilityscore,
                Comments = model.Comments,
                QId = model.Qid,
                RequestID = model.Requestid,
                VulnerabilityRating = model.Vulnerabilityrating,
                SecurityRiskEffective = model.Securityriskeffective,
                SecurityMitigation = model.Securitymitigation,
                SecurityRiskOverall = model.Securityriskoverall,
                IncludedinSecurityScanning = model.Includedinsecurityscanning,
                RaId = model.Raid,
                LcmCumulativeRiskId = model.Lcmcumulativeriskid,
                LcmCumulativeRiskLevel = model.Lcmcumulativerisklevel,
                CyberRiskRequestId = model.Cyberriskrequestid,
                Criticality = model.Criticality,
                AssetStatus = model.Assetstatus,
                GdprRelevant = model.Gdprrelevant,
                LastScanDate = model.Lastscandate,
                LastUpgradeDate = model.Lastupgradedate,
                AssetOutofScopeForReportingPurposes = model.Assetoutofscopeforreportingpurposes,
                MainOrganization = model.Mainorganization,
                IsExtendedSupportOfferedByVendor = model.Isextendedsupportofferedbyvendor,
                EomControl = model.Eomcontrol,
                EngUpdateTracker = model.Engupdatetracker,
                OpsUpdateTracker = model.Opsupdatetracker,
                TypeOfNetworkElement = model.Typeofnetworkelement,
                EngKpi2 = model.Engkpi2,
                IpAddress = model.Ipaddress,
                SerialNumber = model.Serialnumber,
                Hostname = model.Hostname,
                ExNetworks = model.Exnetworks,
                OriginalLcmId = model.Originallcmid,
                ApplicationOperatingSys = model.Applicationoperatingsys,
                EofsDate = model.Eofsdate,
                EoslKpiDaily = model.Eoslkpidaily,
                EoslKpiForecast = model.Eoslkpiforecast,
                EoslKpiFrozen = model.Eoslkpifrozen,
                ProductImportanceHistory2 = model.Productimportancehistory2,
                SwResourceKey = model.Swresourcekey,
                CreationDate = model.Creationdate,
                CreationUser = model.Creationuser,
                ModificationDate = model.Modificationdate,
                ModificationUser = model.Modificationuser,
                CreationUserEntity = ApplicationUserMapper.GetApplicationUserMapper(model.CreationuserNavigation),
                ModificationUserEntity = ApplicationUserMapper.GetApplicationUserMapper(model.ModificationuserNavigation),                              
            };
            return result;
        }

        public static Swpassthroughlcm Set(SwPassThroughLcm model)
        {
            if (model == null)
                return null;
            var result = new Swpassthroughlcm()
            {
                Passthroughlcmid = model.PassThroughLcmId,
                Nontemsvertical = (int?)model.NonTemsVertical,
                Reportid = model.ReportId,
                Localmarket = model.LocalMarket,
                Verticalengineeringteam = model.VerticalEngineeringTeam,
                Verticalsubdomain = model.VerticalSubDomain,
                Engineeringcontactpoint = model.EngineeringContactPoint,
                Swoperationscontactpoint = model.SWOperationsContactPoint,
                Assetcategory = model.AssetCategory,
                Assetclass = model.AssetClass,
                Assettype = model.AssetType,
                Assetdescription = model.AssetDescription,
                Assetvirtualized = model.AssetVirtualized,
                Productimportance = model.ProductImportance,
                Swvendor = model.SWVendor,
                Hardwaremodel = model.HardwareModel,
                Productcode = model.ProductCode,
                Softwareversion = model.SoftwareVersion,
                Numberofnodes = model.NumberOfNodes,
                Handedovertooperation = model.HandedOverToOperation,
                Swoperationsmaintenancecontract = model.SWOperationsMaintenanceContract,
                Contractrenewalplan = model.ContractRenewalPlan,
                Swvendorendofmaintenancedate = model.SWVendorEndOfMaintenanceDate,
                Vendorendofvulnerabilitysecuritysupportdate = model.VendorEndOfVulnerabilitySecuritySupportDate,
                Lcmstatus = model.LcmStatus,
                Identifiedaction = model.IdentifiedAction,
                Descriptionofplannedaction = model.DescriptionOfPlannedAction,
                Plannedsoftwareversion = model.PlannedSoftwareVersion,
                Projectstatus = model.ProjectStatus,
                Reasonfornoplan = model.ReasonfornoPlan,
                Commentonprojectstatus = model.CommentonProjectStatus,
                Projectenddate = model.ProjectEndDate,
                Ragstatus = model.RagStatus,
                Trackingnumberprojectname = model.TrackingNumberProjectName,
                Program = model.Program,
                Wbscode = model.WbsCode,
                Bptid = model.BptID,
                Ppmid = model.PpmID,
                Scopeofsimplification = model.ScopeOfSimplification,
                Datasource = model.DataSource,
                Projectowner = model.ProjectOwner,
                Budgetestimated = model.BudgetEstimated,
                Notes = model.Notes,
                Bundlebudget = model.BundleBudget,
                Bundleid = model.BundleId,
                Assetservicefunctionality = model.AssetServiceFunctionality,
                Platform = model.Platform,
                Lcmstatusengsoftware = model.LcmStatusEngSoftware,
                Lcmstatusopssoftware = model.LcmStatusOpsSoftware,
                Swopsmaintenanceconractenddate = model.SWOpsMaintenanceConractEndDate,
                Engriskevaluation = model.EngRiskEvaluation,
                Engriskevaluationnotes = model.EngRiskEvaluationNotes,
                Opsriskevaluation = model.OpsRiskEvaluation,
                Opsriskevaluationnotes = model.OpsRiskEvaluationNotes,
                Incidentclass = model.IncidentClass,
                Occurrenceprobability = model.OccurrenceProbability,
                Newopsriskevaluation = model.NewopsRiskEvaluation,
                Overallriskevaluation = model.OverallRiskEvaluation,
                Riskcluster = model.RiskCluster,
                Securityriskpotential = model.SecurityRiskPotential,
                Vulnerabilityscore = model.VulnerabilityScore,
                Comments = model.Comments,
                Qid = model.QId,
                Requestid = model.RequestID,
                Vulnerabilityrating = model.VulnerabilityRating,
                Securityriskeffective = model.SecurityRiskEffective,
                Securitymitigation = model.SecurityMitigation,
                Securityriskoverall = model.SecurityRiskOverall,
                Includedinsecurityscanning = model.IncludedinSecurityScanning,
                Raid = model.RaId,
                Lcmcumulativeriskid = model.LcmCumulativeRiskId,
                Lcmcumulativerisklevel = model.LcmCumulativeRiskLevel,
                Cyberriskrequestid = model.CyberRiskRequestId,
                Criticality = model.Criticality,
                Assetstatus = model.AssetStatus,
                Gdprrelevant = model.GdprRelevant,
                Lastscandate = model.LastScanDate,
                Lastupgradedate = model.LastUpgradeDate,
                Assetoutofscopeforreportingpurposes = model.AssetOutofScopeForReportingPurposes,
                Mainorganization = model.MainOrganization,
                Isextendedsupportofferedbyvendor = model.IsExtendedSupportOfferedByVendor,
                Eomcontrol = model.EomControl,
                Engupdatetracker = model.EngUpdateTracker,
                Opsupdatetracker = model.OpsUpdateTracker,
                Typeofnetworkelement = model.TypeOfNetworkElement,
                Engkpi2 = model.EngKpi2,
                Ipaddress = model.IpAddress,
                Serialnumber = model.SerialNumber,
                Hostname = model.Hostname,
                Exnetworks = model.ExNetworks,
                Originallcmid = model.OriginalLcmId,
                Applicationoperatingsys = model.ApplicationOperatingSys,
                Eofsdate = model.EofsDate,
                Eoslkpidaily = model.EoslKpiDaily,
                Eoslkpiforecast = model.EoslKpiForecast,
                Eoslkpifrozen = model.EoslKpiFrozen,
                Productimportancehistory2 = model.ProductImportanceHistory2,
                Swresourcekey = model.SwResourceKey,

            };
            return result;
        }

    }
}
