using CAM.Entities.Mappers.Identity;
using CAM.Entities.Mappers.Lookup;
using CAM.Entities.Models;
using OracleModels.DBModels;
using System;

namespace CAM.Entities.Mappers.Entity
{
    public class TsrPassThroughMapper
    {
        public static TsrPassThrough Get(Tsrpassthrough model)
        {
            if (model == null)
                return null;
            var result = new TsrPassThrough()
            {
                TsrPassThroughId = model.Tsrpassthroughid,
                AssetId = model.Assetid,
                VodafoneUniqueIdentifier = model.Vodafoneuniqueidentifier,
                AssetName = model.Assetname,
                AssetDescriptionOrPurpose = model.Assetdescriptionorpurpose,
                AssetType = model.Assettype,
                BusinessOwner = model.Businessowner,
                SupportOwner = model.Supportowner,
                SupportTeam = model.Supportteam,
                SupportTeamsPlaceInTheOrganisation = model.Supportteamsplaceintheorganisation,
                AssetFunction = model.Assetfunction,
                DeploymentOrLifeCycleStatus = model.Deploymentorlifecyclestatus,
                RelatedRiskIdsFromRiskRegisters = model.Relatedriskidsfromriskregisters,
                RegulatoryScope = model.Regulatoryscope,
                CountryWhereAssetIsLocated = model.Countrywhereassetislocated,
                Geolocation = model.Geolocation,
                Infrastructure = model.Infrastructure,
                UpStreamDependencies = model.Upstreamdependencies,
                DownStreamDependencies = model.Downstreamdependencies,
                ChangesToTheassetSinceDeployment = model.Changestotheassetsincedeployment,
                CloudHostedAsset = model.Cloudhostedasset,
                CloudType = model.Cloudtype,
                CloudVendor = model.Cloudvendor,
                EquipmentName = model.Equipmentname,
                HostLocationWithInPhysicalLocation = model.Hostlocationwithinphysicallocation,
                SoftwareVendorName = model.Softwarevendorname,
                Model = model.Model,
                FirmwareVersion = model.Firmwareversion,
                FirmwareVersionPatchLevel = model.Firmwareversionpatchlevel,
                MaintenanceSupportSupplier = model.Maintenancesupportsupplier,
                VendorHardwareEndOfSupportDate = model.Vendorhardwareendofsupportdate,
                MaintenanceHardwareEndOfSupportDate = model.Maintenancehardwareendofsupportdate,
                DependantHardware = model.Dependanthardware,
                InstanceType = model.Instancetype,
                OperatingSystemName = model.Operatingsystemname,
                OperatingSystemSwvVersion = model.Operatingsystemswvversion,
                OperatingSystemSwVersionPatchLevel = model.Operatingsystemswversionpatchlevel,
                SystemNameDns = model.Systemnamedns,
                SystemNameManagementIpAddress = model.Systemnamemanagementipaddress,
                SystemNameNetBios = model.Systemnamenetbios,
                SystemNameHostName = model.Systemnamehostname,
                DateAssetMovedToLiveStatus = model.Dateassetmovedtolivestatus,
                DateAssetDecommissioned = model.Dateassetdecommissioned,
                HardwareVendorName = model.Hardwarevendorname,
                VendorSoftwareEndOfSupportDate = model.Vendorsoftwareendofsupportdate,
                MaintenanceSoftwareEndOfSupportDate = model.Maintenancesoftwareendofsupportdate,
                DependantSystemSoftware = model.Dependantsystemsoftware,
                ResilienceModel = model.Resiliencemodel,
                GeographicSiteResilience = model.Geographicsiteresilience,
                LocalSiteResilience = model.Localsiteresilience,
                NameOfProductsDependantOnAsset = model.Nameofproductsdependantonasset,
                TechnicalServiceNames = model.Technicalservicenames,
                Customer = model.Customer,
                PrivilegedAccessLogging = model.Privilegedaccesslogging,
                BoardOrModuleNameComponentName = model.Boardormodulenamecomponentname,
                BoardOrModuleTypeComponentSubtype = model.Boardormoduletypecomponentsubtype,
                BoardOrModuleTypeComponentVersionNumber = model.Boardormoduletypecomponentversionnumber,
                ExposedEdge = model.Exposededge,
                ExternallyFacingSystem = model.Externallyfacingsystem,
                ManagementPlane = model.Managementplane,
                NetworkOverSightFunction = model.Networkoversightfunction,
                Pecn = model.Pecn,
                Pecs = model.Pecs,
                SecurityCriticalFunction = model.Securitycriticalfunction,
                ProductImportance = model.Productimportance,
                Critical = model.Critical,
                CriticalityType = model.Criticalitytype,
                SerialNumber = model.Serialnumber,
                PartNumber = model.Partnumber,
                DescriptionOfPlannedaction = model.Descriptionofplannedaction,
                IdentifiedAction = model.Identifiedaction,
                LastUpgradeDate = model.Lastupgradedate,
                ProdOrLab = model.Prodorlab,
                LocalMarketOwnerShip = model.Localmarketownership,
                BudgetEstimated = model.Budgetestimated,
                BundleBudget = model.Bundlebudget,
                AssuranceCall = model.Assurancecall,
                CommentOnProjectStatus = model.Commentonprojectstatus,
                ProjectEndDate = model.Projectenddate,
                ProjectStatus = model.Projectstatus,
                ServiceLevel = model.Servicelevel,
                LastPenTestDate = model.Lastpentestdate,
                LastPenTestRefNo = model.Lastpentestrefno,
                PiData = model.Pidata,
                EncryptedPiData = model.Encryptedpidata,
                RecordClassifier = model.Recordclassifier,
                ProductName = model.Productname,
                SoftwareVersion = model.Softwareversion,
                SubDomainResponsible = model.Subdomainresponsible,
                IsSortingAllowed = model.Issortingallowed,
                CreationDate = model.Creationdate,
                CreationUser = model.Creationuser,
                ModificationDate = model.Modificationdate,
                ModificationUser = model.Modificationuser,
                CreationUserEntity = ApplicationUserMapper.GetApplicationUserMapper(model.CreationuserNavigation),
                ModificationUserEntity = ApplicationUserMapper.GetApplicationUserMapper(model.ModificationuserNavigation),                              
            };
            return result;
        }

        public static Tsrpassthrough Set(TsrPassThrough model)
        {
            if (model == null)
                return null;
            var result = new Tsrpassthrough()
            {
                Tsrpassthroughid = model.TsrPassThroughId,
                Assetid = model.AssetId,
                Vodafoneuniqueidentifier = model.VodafoneUniqueIdentifier,
                Assetname = model.AssetName,
                Assetdescriptionorpurpose = model.AssetDescriptionOrPurpose,
                Assettype = model.AssetType,
                Businessowner = model.BusinessOwner,
                Supportowner = model.SupportOwner,
                Supportteam = model.SupportTeam,
                Supportteamsplaceintheorganisation = model.SupportTeamsPlaceInTheOrganisation,
                Assetfunction = model.AssetFunction,
                Deploymentorlifecyclestatus = model.DeploymentOrLifeCycleStatus,
                Relatedriskidsfromriskregisters = model.RelatedRiskIdsFromRiskRegisters,
                Regulatoryscope = model.RegulatoryScope,
                Countrywhereassetislocated = model.CountryWhereAssetIsLocated,
                Geolocation = model.Geolocation,
                Infrastructure = model.Infrastructure,
                Upstreamdependencies = model.UpStreamDependencies,
                Downstreamdependencies = model.DownStreamDependencies,
                Changestotheassetsincedeployment = model.ChangesToTheassetSinceDeployment,
                Cloudhostedasset = model.CloudHostedAsset,
                Cloudtype = model.CloudType,
                Cloudvendor = model.CloudVendor,
                Equipmentname = model.EquipmentName,
                Hostlocationwithinphysicallocation = model.HostLocationWithInPhysicalLocation,
                Softwarevendorname = model.SoftwareVendorName,
                Model = model.Model,
                Firmwareversion = model.FirmwareVersion,
                Firmwareversionpatchlevel = model.FirmwareVersionPatchLevel,
                Maintenancesupportsupplier = model.MaintenanceSupportSupplier,
                Vendorhardwareendofsupportdate = model.VendorHardwareEndOfSupportDate,
                Maintenancehardwareendofsupportdate = model.MaintenanceHardwareEndOfSupportDate,
                Dependanthardware = model.DependantHardware,
                Instancetype = model.InstanceType,
                Operatingsystemname = model.OperatingSystemName,
                Operatingsystemswvversion = model.OperatingSystemSwvVersion,
                Operatingsystemswversionpatchlevel = model.OperatingSystemSwVersionPatchLevel,
                Systemnamedns = model.SystemNameDns,
                Systemnamemanagementipaddress = model.SystemNameManagementIpAddress,
                Systemnamenetbios = model.SystemNameNetBios,
                Systemnamehostname = model.SystemNameHostName,
                Dateassetmovedtolivestatus = model.DateAssetMovedToLiveStatus,
                Dateassetdecommissioned = model.DateAssetDecommissioned,
                Hardwarevendorname = model.HardwareVendorName,
                Vendorsoftwareendofsupportdate = model.VendorSoftwareEndOfSupportDate,
                Maintenancesoftwareendofsupportdate = model.MaintenanceSoftwareEndOfSupportDate,
                Dependantsystemsoftware = model.DependantSystemSoftware,
                Resiliencemodel = model.ResilienceModel,
                Geographicsiteresilience = model.GeographicSiteResilience,
                Localsiteresilience = model.LocalSiteResilience,
                Nameofproductsdependantonasset = model.NameOfProductsDependantOnAsset,
                Technicalservicenames = model.TechnicalServiceNames,
                Customer = model.Customer,
                Privilegedaccesslogging = model.PrivilegedAccessLogging,
                Boardormodulenamecomponentname = model.BoardOrModuleNameComponentName,
                Boardormoduletypecomponentsubtype = model.BoardOrModuleTypeComponentSubtype,
                Boardormoduletypecomponentversionnumber = model.BoardOrModuleTypeComponentVersionNumber,
                Exposededge = model.ExposedEdge,
                Externallyfacingsystem = model.ExternallyFacingSystem,
                Managementplane = model.ManagementPlane,
                Networkoversightfunction = model.NetworkOverSightFunction,
                Pecn = model.Pecn,
                Pecs = model.Pecs,
                Securitycriticalfunction = model.SecurityCriticalFunction,
                Productimportance = model.ProductImportance,
                Critical = model.Critical,
                Criticalitytype = model.CriticalityType,
                Serialnumber = model.SerialNumber,
                Partnumber = model.PartNumber,
                Descriptionofplannedaction = model.DescriptionOfPlannedaction,
                Identifiedaction = model.IdentifiedAction,
                Lastupgradedate = model.LastUpgradeDate,
                Prodorlab = model.ProdOrLab,
                Localmarketownership = model.LocalMarketOwnerShip,
                Budgetestimated = model.BudgetEstimated,
                Bundlebudget = model.BundleBudget,
                Assurancecall = model.AssuranceCall,
                Commentonprojectstatus = model.CommentOnProjectStatus,
                Projectenddate = model.ProjectEndDate,
                Projectstatus = model.ProjectStatus,
                Servicelevel = model.ServiceLevel,
                Lastpentestdate = model.LastPenTestDate,
                Lastpentestrefno = model.LastPenTestRefNo,
                Pidata = model.PiData,
                Encryptedpidata = model.EncryptedPiData,
                Recordclassifier = model.RecordClassifier,
                Productname = model.ProductName,
                Subdomainresponsible = model.SubDomainResponsible,
                Softwareversion = model.SoftwareVersion,
                Issortingallowed = model.IsSortingAllowed
            };
            return result;
        }

    }
}
