CREATE TABLE ASPNETUSERS_BACKUP AS SELECT  * FROM ASPNETUSERS;
CREATE TABLE ASPNETUSERROLES_BACKUP AS SELECT  * FROM ASPNETUSERROLES;
CREATE TABLE SYSTEMTYPES_BACKUP AS SELECT  * FROM SYSTEMTYPES;   
CREATE TABLE SYSTEMTYPESSUBDOMAINSPOC_BACKUP AS SELECT  * FROM SYSTEMTYPESSUBDOMAINSPOC;
CREATE TABLE LCMENGINEERINGSUBDOMAINSPOC_BACKUP AS SELECT  * FROM LCMENGINEERINGSUBDOMAINSPOC; 
CREATE TABLE LCMENGINEERINGEDUSPOC_BACKUP AS SELECT  * FROM LCMENGINEERINGEDUSPOC; 
CREATE TABLE DESIGNCOMPONENTS_BACKUP AS SELECT  * FROM DESIGNCOMPONENTS; 
CREATE TABLE DESIGNCOMPONENTFAMILIES_BACKUP AS SELECT  * FROM DESIGNCOMPONENTFAMILIES; 
CREATE TABLE NETWORKELEMENTASPLANNEDEDUSPOC_BACKUP AS SELECT  * FROM NETWORKELEMENTASPLANNEDEDUSPOC;
CREATE TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_BACKUP AS SELECT  * FROM NETWORKELEMENTASPLANNEDSUBDOMAINSPOC;

CREATE TABLE organisation_BACKUP AS SELECT  * FROM organisation;

COMMIT;
 

--CREATE TABLE MAJORHARDWAREBUILDS_BACKUP AS SELECT  * FROM MAJORHARDWAREBUILDS;
--CREATE TABLE MAJORSOFTWAREBUILDS_BACKUP AS SELECT  * FROM MAJORSOFTWAREBUILDS;
---CREATE TABLE SOFTWAREBUILDCOMPATIBILITY_BACKUP AS SELECT  * FROM SOFTWAREBUILDCOMPATIBILITY;
--CREATE TABLE SYSTEMTYPESMAJORHARDWAREBUILDS_BACKUP AS SELECT  * FROM SYSTEMTYPESMAJORHARDWAREBUILDS;  
--CREATE TABLE LCMENGINEERING_BACKUP AS SELECT  * FROM LCMENGINEERING; 
--CREATE TABLE DESIGNASPECTS_BACKUP AS SELECT  * FROM DESIGNASPECTS; 
--CREATE TABLE PLANNEDACTIVITIES_BACKUP AS SELECT  * FROM PLANNEDACTIVITIES;
--CREATE TABLE NETWORKELEMENTSASPLANNED_BACKUP AS SELECT  * FROM NETWORKELEMENTSASPLANNED;