--------------------------------------------------------
--  DDL FOR SEQUENCE MAINORGANISATION_SEQ
--------------------------------------------------------
 
CREATE SEQUENCE "MAINORGANISATION_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;
 
 
 
--------------------------------------------------------
--  DDL FOR TABLE MAINORGANISATION
--------------------------------------------------------

CREATE TABLE MAINORGANISATION (
"MAINORGANISATIONID" NUMBER(10,0) DEFAULT "MAINORGANISATION_SEQ"."NEXTVAL",
"MAINORGANISATIONDESCRIPTION" NVARCHAR2(30),
"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"DELETED" NUMBER(1,0) DEFAULT 0, 
"DELETIONDATE" TIMESTAMP (6)
)SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_MAINORGANISATION
--------------------------------------------------------
 
CREATE UNIQUE INDEX "PK_MAINORGANISATION" ON "MAINORGANISATION" ("MAINORGANISATIONID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE MAINORGANISATION
--------------------------------------------------------
 
ALTER TABLE "MAINORGANISATION" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "MAINORGANISATION" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "MAINORGANISATION" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "MAINORGANISATION" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "MAINORGANISATION" ADD CONSTRAINT "PK_MAINORGANISATION" PRIMARY KEY ("MAINORGANISATIONID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB"  ENABLE;
COMMIT;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE MAINORGANISATION
--------------------------------------------------------
 
ALTER TABLE "MAINORGANISATION" ADD CONSTRAINT "FK_MAINORGANISATION_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "MAINORGANISATION" ADD CONSTRAINT "FK_MAINORGANISATION_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
 
COMMIT;

--------------------------------------------------------
-- INSERT QUERY FOR MAINORGANISATION
--------------------------------------------------------
INSERT INTO MAINORGANISATION (MAINORGANISATIONID,MAINORGANISATIONDESCRIPTION) VALUES(1,'NSE');

COMMIT;