ALTER TABLE "NETWORKELEMENTSASIS" ADD "PLATFORMTYPE" NVARCHAR2(50);
ALTER TABLE "NETWORKELEMENTSASIS" ADD "HARDWARETYPE" NVARCHAR2(50);
ALTER TABLE "NETWORKELEMENTSASIS" ADD "SOFTWARERELEASEINFORMATION" NVARCHAR2(50);
COMMIT;