----------------------------------------------
-- AlTER SCRIPT FOR LCMENGINEERING ------
--ALTER TABLE LCMENGINEERING ADD VERTICALRESPONSIBLEID NUMBER(10,0);
--ALTER TABLE LCMENGINEERING ADD CONSTRAINT "FK_LCMENGINEERING_VERTICALRESPONSIBLES_VERTICALRESPONSIBLEID" FOREIGN KEY ("VERTICALRESPONSIBLEID") REFERENCES "VERTICALRESPONSIBLES" ("VERTICALRESPONSIBLEID") ENABLE;

ALTER TABLE LCMENGINEERINGEDUSPOC ADD DESIGNCONTACTID NUMBER(10,0);
ALTER TABLE "LCMENGINEERINGEDUSPOC" ADD CONSTRAINT "FK_LCMENGINEERINGEDUSPOC_ASPNETUSERS_DESIGNCONTACTID" FOREIGN KEY ("DESIGNCONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;

ALTER TABLE LCMENGINEERINGSUBDOMAINSPOC ADD DESIGNCONTACTID NUMBER(10,0);
ALTER TABLE "LCMENGINEERINGSUBDOMAINSPOC" ADD CONSTRAINT "FK_LCMENGINEERINGSUBDOMAINSPOC_ASPNETUSERS_DESIGNCONTACTID" FOREIGN KEY ("DESIGNCONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;

COMMIT;

----------------------------------------------
-- AlTER SCRIPT FOR NETWORKELEMENTASPLANNED------

ALTER TABLE NETWORKELEMENTASPLANNEDEDUSPOC ADD DESIGNCONTACTID NUMBER(10,0);
ALTER TABLE "NETWORKELEMENTASPLANNEDEDUSPOC" ADD CONSTRAINT "FK_NETWORKELEMENTASPLANNEDEDUSPOC_ASPNETUSERS_DESIGNCONTACTID" FOREIGN KEY ("DESIGNCONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;

ALTER TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC ADD DESIGNCONTACTID NUMBER(10,0);
ALTER TABLE "NETWORKELEMENTASPLANNEDSUBDOMAINSPOC" ADD CONSTRAINT "FK_NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_ASPNETUSERS_DESIGNCONTACTID" FOREIGN KEY ("DESIGNCONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;

COMMIT;


ALTER TABLE LCMENGINEERINGSUBDOMAINSPOC MODIFY SUBDOMAINSPOCID  NULL;
ALTER TABLE LCMENGINEERINGEDUSPOC MODIFY SUBDOMAINSPOCID  NULL;
ALTER TABLE NETWORKELEMENTASPLANNEDEDUSPOC MODIFY SUBDOMAINSPOCID  NULL;
ALTER TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC MODIFY SUBDOMAINSPOCID  NULL;
COMMIT; 