--------------------------------------------------------
--  DDL FOR SEQUENCE MAJORSWBUIDLSDESIGNCONTACTS_SEQ
--------------------------------------------------------

CREATE SEQUENCE "MAJORHWBUIDLSDESIGNCONTACTS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;

--------------------------------------------------------
--  DDL for Table MAJORHWBUIDLSDESIGNCONTACTS
--------------------------------------------------------

  CREATE TABLE "MAJORHWBUILDSDESIGNCONTACTS" 
   (	
    "MAJORHWBUILDSDESIGNCONTACTSID" NUMBER(19,0) DEFAULT "MAJORHWBUIDLSDESIGNCONTACTS_SEQ"."NEXTVAL",
	"DESIGNCONTACTID" NUMBER(10,0),
	"MAJORHARDWAREBUILDSID" NUMBER(19,0),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;

--------------------------------------------------------
--  DDL for Index PK_MAJORHWBUIDLSDESIGNCONTACTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_MAJORHWBUIDLSDESIGNCONTACTS" ON "MAJORHWBUILDSDESIGNCONTACTS" ("MAJORHWBUILDSDESIGNCONTACTSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table MAJORHWBUIDLSDESIGNCONTACTS
--------------------------------------------------------

  ALTER TABLE "MAJORHWBUILDSDESIGNCONTACTS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "MAJORHWBUILDSDESIGNCONTACTS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "MAJORHWBUILDSDESIGNCONTACTS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "MAJORHWBUILDSDESIGNCONTACTS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "MAJORHWBUILDSDESIGNCONTACTS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "MAJORHWBUILDSDESIGNCONTACTS" MODIFY ("DESIGNCONTACTID" NOT NULL ENABLE);
  ALTER TABLE "MAJORHWBUILDSDESIGNCONTACTS" MODIFY ("MAJORHARDWAREBUILDSID" NOT NULL ENABLE);
  ALTER TABLE "MAJORHWBUILDSDESIGNCONTACTS" ADD CONSTRAINT "PK_MAJORHWBUIDLSDESIGNCONTACTS" PRIMARY KEY ("MAJORHWBUILDSDESIGNCONTACTSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAJORHWBUIDLSDESIGNCONTACTS
--------------------------------------------------------

ALTER TABLE "MAJORHWBUILDSDESIGNCONTACTS" ADD CONSTRAINT "FK_MAJORHWBUIDLSDESIGNCONTACTS_ORGANISATION_DESIGNCONTACTID" FOREIGN KEY ("DESIGNCONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "MAJORHWBUILDSDESIGNCONTACTS" ADD CONSTRAINT "FK_MAJORHWBUIDLSDESIGNCONTACTS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "MAJORHWBUILDSDESIGNCONTACTS" ADD CONSTRAINT "FK_MAJORHWBUIDLSDESIGNCONTACTS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "MAJORHWBUILDSDESIGNCONTACTS" ADD CONSTRAINT "FK_MAJORHWBUIDLSDESIGNCONTACTS_MAJORHARDWAREBUILDS_MAJORHARDWAREBUILDSID" FOREIGN KEY ("MAJORHARDWAREBUILDSID") REFERENCES "MAJORHARDWAREBUILDS" ("MAJORHARDWAREID") ENABLE;
COMMIT;