--------------------------------------------- MAJORSWBUIDLSDESIGNCONTACTS FOR EXISTING RECORD 

INSERT INTO MAJORSWBUILDSDESIGNCONTACTS (DESIGNCONTACTID, MAJORSOFTWAREBUILDSID,CREATIONUSER,MODIFICATIONUSER)  SELECT DISTINCT UR.ID ,MSW.MAJORSOFTWAREBUILDSID ,1 ,1  FROM MAJORSOFTWAREBUILDS MSW  JOIN SYSTEMTYPES ST ON MSW.MAJORSOFTWAREBUILDSID = ST.MAJORSOFTWAREBUILDSID  JOIN SYSTEMTYPESSUBDOMAINSPOC STSDMS ON STSDMS.SYSTEMTYPEID = ST.SYSTEMTYPEID JOIN SUBDOMAINSPOCS SDMS ON SDMS.SUBDOMAINSPOCID = STSDMS.SUBDOMAINSPOCID JOIN ASPNETUSERS UR ON UR.EMAIL = SDMS.SUBDOMAINSPOC  JOIN VERTICALRESPONSIBLES V ON ST.VERTICALRESPONSIBLEID = V.VERTICALRESPONSIBLEID  JOIN ASPNETUSERROLES AUR ON AUR.USERID = UR.ID  ; 
COMMIT; 

 --------------------------------------- LCMENGINEERINGSUBDOMAINSPOC 

CREATE TABLE LCMSUBDOMAINSPOC_TEMPRECORDS AS SELECT  LCMENGINEERINGSUBDOMAINSPOCID, LCMENGEENERINGID,SUBDOMAINSPOCID  FROM LCMENGINEERINGSUBDOMAINSPOC; 

SELECT COUNT(*) FROM LCMSUBDOMAINSPOC_TEMPRECORDS;


UPDATE LCMENGINEERINGSUBDOMAINSPOC ULCM SET DESIGNCONTACTID = ( SELECT  UR.ID FROM   LCMSUBDOMAINSPOC_TEMPRECORDS LSP   JOIN SUBDOMAINSPOCS SP ON LSP.SUBDOMAINSPOCID = SP.SUBDOMAINSPOCID  JOIN ASPNETUSERS UR ON SP.SUBDOMAINSPOC = UR.EMAIL WHERE ULCM.LCMENGINEERINGSUBDOMAINSPOCID = LSP.LCMENGINEERINGSUBDOMAINSPOCID AND ULCM.LCMENGEENERINGID = LSP.LCMENGEENERINGID );
COMMIT;

DROP TABLE LCMSUBDOMAINSPOC_TEMPRECORDS;
 
---UPDATE LCMENGINEERINGSUBDOMAINSPOC ULCM SET DESIGNCONTACTID = ( SELECT  UR.ID FROM   LCMENGINEERINGSUBDOMAINSPOC LSP   JOIN SUBDOMAINSPOCS SP ON LSP.SUBDOMAINSPOCID = SP.SUBDOMAINSPOCID  JOIN ASPNETUSERS UR ON SP.SUBDOMAINSPOC = UR.EMAIL WHERE SP.ISSUBDOMAIN = 1 AND ULCM.LCMENGINEERINGSUBDOMAINSPOCID = LSP.LCMENGINEERINGSUBDOMAINSPOCID );
--COMMIT;


--------------------------------------- LCMENGINEERINGEDUSPOC

CREATE TABLE LCMENGINEERINGEDUSPOC_TEMPRECORDS AS SELECT  LCMENGINEERINGEDUSPOCID, LCMENGEENERINGID,SUBDOMAINSPOCID  FROM LCMENGINEERINGEDUSPOC; 

SELECT COUNT(*) FROM LCMENGINEERINGEDUSPOC_TEMPRECORDS;


UPDATE LCMENGINEERINGEDUSPOC ULCM SET DESIGNCONTACTID = ( SELECT  UR.ID FROM   LCMENGINEERINGEDUSPOC_TEMPRECORDS LSP   JOIN SUBDOMAINSPOCS SP ON LSP.SUBDOMAINSPOCID = SP.SUBDOMAINSPOCID  JOIN ASPNETUSERS UR ON SP.SUBDOMAINSPOC = UR.EMAIL WHERE ULCM.LCMENGINEERINGEDUSPOCID = LSP.LCMENGINEERINGEDUSPOCID AND ULCM.LCMENGEENERINGID = LSP.LCMENGEENERINGID );
COMMIT;

DROP TABLE LCMENGINEERINGEDUSPOC_TEMPRECORDS;
COMMIT; 
 
---UPDATE LCMENGINEERINGEDUSPOC ULCM SET DESIGNCONTACTID = ( SELECT  UR.ID FROM   LCMENGINEERINGEDUSPOC LEP   JOIN SUBDOMAINSPOCS SP ON LEP.SUBDOMAINSPOCID = SP.SUBDOMAINSPOCID   JOIN ASPNETUSERS UR ON SP.SUBDOMAINSPOC = UR.EMAIL   WHERE SP.ISEDU = 1 AND ULCM.LCMENGINEERINGEDUSPOCID = LEP.LCMENGINEERINGEDUSPOCID );
---COMMIT; 

--------------------------------------- NETWORKELEMENTASPLANNEDSUBDOMAINSPOC 
 
CREATE TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_TEMPRECORDS AS SELECT  NTKELEMENTASPLNSUBDOMAINSPOCID,NETWORKELEMENTASPLANNEDID,SUBDOMAINSPOCID  FROM NETWORKELEMENTASPLANNEDSUBDOMAINSPOC; 

SELECT COUNT(*) FROM NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_TEMPRECORDS;


UPDATE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC ULCM SET DESIGNCONTACTID = ( SELECT  UR.ID FROM   NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_TEMPRECORDS LSP   JOIN SUBDOMAINSPOCS SP ON LSP.SUBDOMAINSPOCID = SP.SUBDOMAINSPOCID  JOIN ASPNETUSERS UR ON SP.SUBDOMAINSPOC = UR.EMAIL WHERE ULCM.NTKELEMENTASPLNSUBDOMAINSPOCID = LSP.NTKELEMENTASPLNSUBDOMAINSPOCID AND ULCM.NETWORKELEMENTASPLANNEDID = LSP.NETWORKELEMENTASPLANNEDID );
COMMIT;

DROP TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_TEMPRECORDS;
COMMIT;

---UPDATE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC ULCM SET DESIGNCONTACTID = ( SELECT  UR.ID FROM   NETWORKELEMENTASPLANNEDSUBDOMAINSPOC LSP   JOIN SUBDOMAINSPOCS SP ON LSP.SUBDOMAINSPOCID = SP.SUBDOMAINSPOCID  JOIN ASPNETUSERS UR ON SP.SUBDOMAINSPOC = UR.EMAIL WHERE SP.ISSUBDOMAIN = 1 AND ULCM.NTKELEMENTASPLNSUBDOMAINSPOCID = LSP.NTKELEMENTASPLNSUBDOMAINSPOCID );
---COMMIT;


--------------------------------------- NETWORKELEMENTASPLANNEDEDUSPOC 

CREATE TABLE NETWORKELEMENTASPLANNEDEDUSPOC_TEMPRECORDS AS SELECT  NTKELEMENTASPLNEDUSPOCID,NETWORKELEMENTASPLANNEDID,SUBDOMAINSPOCID  FROM NETWORKELEMENTASPLANNEDEDUSPOC; 

SELECT count(*) FROM NETWORKELEMENTASPLANNEDEDUSPOC_TEMPRECORDS;


UPDATE NETWORKELEMENTASPLANNEDEDUSPOC ULCM SET DESIGNCONTACTID = ( SELECT  UR.ID FROM   NETWORKELEMENTASPLANNEDEDUSPOC_TEMPRECORDS LSP   JOIN SUBDOMAINSPOCS SP ON LSP.SUBDOMAINSPOCID = SP.SUBDOMAINSPOCID  JOIN ASPNETUSERS UR ON SP.SUBDOMAINSPOC = UR.EMAIL WHERE ULCM.NTKELEMENTASPLNEDUSPOCID = LSP.NTKELEMENTASPLNEDUSPOCID AND ULCM.NETWORKELEMENTASPLANNEDID = LSP.NETWORKELEMENTASPLANNEDID );
COMMIT;

DROP TABLE NETWORKELEMENTASPLANNEDEDUSPOC_TEMPRECORDS;
COMMIT;

---UPDATE NETWORKELEMENTASPLANNEDEDUSPOC ULCM SET DESIGNCONTACTID = ( SELECT  UR.ID FROM   NETWORKELEMENTASPLANNEDEDUSPOC LEP   JOIN SUBDOMAINSPOCS SP ON LEP.SUBDOMAINSPOCID = SP.SUBDOMAINSPOCID   JOIN ASPNETUSERS UR ON SP.SUBDOMAINSPOC = UR.EMAIL   WHERE SP.ISEDU = 1 AND ULCM.NTKELEMENTASPLNEDUSPOCID = LEP.NTKELEMENTASPLNEDUSPOCID );
-----COMMIT; 