ALTER TABLE "SYSTEMTYPES" DROP CONSTRAINT "FK_SYSTEMTYPES_VERTICALRESPONSIBLES_VERTICALRESPONSIBLEID";
ALTER TABLE "SYSTEMTYPES" DROP CONSTRAINT "FK_SYSTEMTYPES_SUBDOMAINRESPONSIBLES_SUBDOMAINRESPONSIBLEID";
ALTER TABLE "SYSTEMTYPES" DROP COLUMN "VERTICALRESPONSIBLEID";
ALTER TABLE "SYSTEMTYPES" DROP COLUMN "SUBDOMAINRESPONSIBLEID";
ALTER TABLE "SYSTEMTYPES" DROP COLUMN "SUBDOMAINSPOC";
COMMIT;