----------------------------------------------------------
-- AlTER SCRIPT FOR ALL EDU AND SUBDOMAINSPOCS -----------


ALTER TABLE LCMENGINEERINGEDUSPOC DROP CONSTRAINT "FK_LCMENGINEERINGEDUSPOC_SUBDOMAINSPOCS_SUBDOMAINSPOCID";
ALTER TABLE LCMENGINEERINGSUBDOMAINSPOC DROP CONSTRAINT "FK_LCMENGINEERINGSUBDOMAINSPOC_SUBDOMAINSPOCS_SUBDOMAINSPOCID";
ALTER TABLE NETWORKELEMENTASPLANNEDEDUSPOC DROP CONSTRAINT "FK_NETWORKELEMENTASPLANNEDEDUSPOC_SUBDOMAINSPOCS_SUBDOMAINSPOCID";
ALTER TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC DROP CONSTRAINT "FK_NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_SUBDOMAINSPOCS_SUBDOMAINSPOCID";
COMMIT;



----------------------------------------------
-- AlTER SCRIPT FOR MAJORHARDWAREBUILDS ------
--ALTER TABLE MAJORHARDWAREBUILDS DROP CONSTRAINT "FK_MAJORHARDWAREBUILDS_ASPNETUSERS_DESIGNCONTACT";
--ALTER TABLE MAJORHARDWAREBUILDS DROP COLUMN DESIGNCONTACTID;
--COMMIT;
---------------------------------------------- 
-- AlTER SCRIPT FOR MAJORSOFTWAREBUILDS ------
--ALTER TABLE MAJORSOFTWAREBUILDS DROP CONSTRAINT "FK_MAJORSOFTWAREBUILDS_ASPNETUSERS_DESIGNCONTACT";
--ALTER TABLE MAJORSOFTWAREBUILDS DROP COLUMN DESIGNCONTACTID;
--COMMIT;

-- AlTER SCRIPT FOR LCMENGINEERING ------
--ALTER TABLE LCMENGINEERING DROP CONSTRAINT "FK_LCMENGINEERING_VERTICALRESPONSIBLES_VERTICALRESPONSIBLEID"  ;
--ALTER TABLE LCMENGINEERING DROP COLUMN VERTICALRESPONSIBLEID ;
---COMMIT;

