----------------------------------------------
-- AlTER SCRIPT FOR MAJORHARDWAREBUILDS ------
ALTER TABLE MAJORHARDWAREBUILDS ADD DESIGNCONTACTID NUMBER(10,0);
ALTER TABLE MAJORHARDWAREBUILDS ADD CONSTRAINT "FK_MAJORHARDWAREBUILDS_ASPNETUSERS_DESIGNCONTACT" FOREIGN KEY ("DESIGNCONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
COMMIT;
---------------------------------------------- 
-- AlTER SCRIPT FOR MAJORSOFTWAREBUILDS ------
ALTER TABLE MAJORSOFTWAREBUILDS ADD DESIGNCONTACTID NUMBER(10,0);
ALTER TABLE MAJORSOFTWAREBUILDS ADD CONSTRAINT "FK_MAJORSOFTWAREBUILDS_ASPNETUSERS_DESIGNCONTACT" FOREIGN KEY ("DESIGNCONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
COMMIT;