----------ROLLBACK SCRIPT FOR APPSETTING AND CONFIG TABLES---------

DROP SEQUENCE  "APPSETTINGSCONFIGURATION_SEQ";
DROP TABLE APPSETTINGSCONFIGURATION;
DROP SEQUENCE  "APPSETTINGS_SEQ";
DROP TABLE APPSETTINGS;


------------------------------END----------------------------------