-----RB SCRIPT FOR PASSTHROUGH ----

DROP SEQUENCE  "PASSTHROUGH_SEQ";
DROP TABLE "PASSTHROUGH" ;


-----RB SCRIPT FOR PASSTHROUGH ----
DROP SEQUENCE  "NONTEMSPASSTHROUGHCONFIG_SEQ";
DROP TABLE "NONTEMSPASSTHROUGHCONFIG";