 
DROP SEQUENCE DATACENTER_SQE;
DROP TABLE DATACENTER ; 

DROP SEQUENCE ASSETCLUSTERTYPE_SQE;
DROP TABLE ASSETCLUSTERTYPE ; 

 
DROP SEQUENCE ASSETCLUSTER_SQE;
DROP TABLE ASSETCLUSTER ; 

DROP SEQUENCE ASSETHARDWAREANCILLARY_SQE;
DROP TABLE ASSETHARDWAREANCILLARY ; 
    