DROP SEQUENCE INTRAVMTYPE_SEQ;
DROP TABLE INTRAVMTYPE  CASCADE CONSTRAINTS PURGE ;

DROP SEQUENCE INTERVMTYPE_SEQ;
DROP TABLE INTERVMTYPE CASCADE CONSTRAINTS PURGE ;

DROP SEQUENCE VMWORKLOADTYPE_SEQ;
DROP TABLE VMWORKLOADTYPE CASCADE CONSTRAINTS PURGE ;

DROP SEQUENCE VNFCLUSTERINFO_SEQ;
DROP TABLE VNFCLUSTERINFO  CASCADE CONSTRAINTS PURGE ;

DROP SEQUENCE VNFINFO_SEQ;
DROP TABLE VNFINFO CASCADE CONSTRAINTS PURGE ;

DROP SEQUENCE VNFVMCAPACITY_SEQ;
DROP TABLE VNFVMCAPACITY CASCADE CONSTRAINTS PURGE ;
 