-------RB SCRIPT FOR PLANNEDACTIVITIES--------

ALTER TABLE PLANNEDACTIVITIES DROP COLUMN PROJECTDESCRIPTION;

-------RB SCRIPT FOR DAPLANNEDACTIVITYDCF--------
DROP SEQUENCE  DAPLANNEDACTIVITYDCF_SEQ;
DROP TABLE DAPLANNEDACTIVITYDCF;

