ALTER TABLE DESIGNCOMPONENTFAMILIES DROP COLUMN "PCI/SOX";

ALTER TABLE DESIGNCOMPONENTFAMILIES DROP COLUMN "C3/C4";

ALTER TABLE DESIGNCOMPONENTFAMILIES DROP COLUMN GDPRCLASSIFICATION;

ALTER TABLE DESIGNCOMPONENTFAMILIES DROP COLUMN INTERNETFACING;

ALTER TABLE DESIGNCOMPONENTFAMILIES DROP COLUMN MISSIONCRITICAL;

ALTER TABLE DESIGNCOMPONENTFAMILIES DROP COLUMN SECURITYELEMENT;

ALTER TABLE DESIGNCOMPONENTFAMILIES DROP COLUMN LCMPOLICY;

ALTER TABLE DESIGNCOMPONENTFAMILIES DROP COLUMN CRITICALITY;

ALTER TABLE DESIGNCOMPONENTFAMILIES DROP COLUMN CRITICALASSETTYPEID;

ALTER TABLE DESIGNCOMPONENTFAMILIES DROP COLUMN GDPRRELEVANT;

DROP TABLE DESIGNCOMPONENTFAMILYCUSTOMERWHEEL ;
DROP TABLE DESIGNCOMPONENTFAMILYSYSTEMFUNCTION;