
CREATE SEQUENCE LOCATIONDEPLOYMENTTYPES_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

--------------------------------------------------------
--  DDL for Table LOCATIONDEPLOYMENTTYPES
--------------------------------------------------------

  CREATE TABLE "CAMSDBUSER"."LOCATIONDEPLOYMENTTYPES" 
   (	"ID" NUMBER(19,0) DEFAULT "CAMSDBUSER"."LOCATIONDEPLOYMENTTYPES_SEQ"."NEXTVAL", 
	"CREATIONUSER" NUMBER(10,0) DEFAULT (null), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT (null), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (null), 
	"DELETIONDATE" TIMESTAMP (6) DEFAULT (null), 
	"LOCATIONID" NUMBER(5,0) DEFAULT (null), 
	"DEPLOYMENTTYPEID" NUMBER(5,0) DEFAULT (null)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index LOCATIONDEPLOYMENTTYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMSDBUSER"."LOCATIONDEPLOYMENTTYPES_PK" ON "CAMSDBUSER"."LOCATIONDEPLOYMENTTYPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table LOCATIONDEPLOYMENTTYPES
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."LOCATIONDEPLOYMENTTYPES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."LOCATIONDEPLOYMENTTYPES" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."LOCATIONDEPLOYMENTTYPES" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."LOCATIONDEPLOYMENTTYPES" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."LOCATIONDEPLOYMENTTYPES" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."LOCATIONDEPLOYMENTTYPES" ADD CONSTRAINT "LOCATIONDEPLOYMENTTYPES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCATIONDEPLOYMENTTYPES
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."LOCATIONDEPLOYMENTTYPES" ADD CONSTRAINT "FK_LOCATIONDEPLOYMENTTYPES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."LOCATIONDEPLOYMENTTYPES" ADD CONSTRAINT "FK_LOCATIONDEPLOYMENTTYPES_LOCATIONS_LOCATIONID" FOREIGN KEY ("LOCATIONID")
	  REFERENCES "CAMSDBUSER"."LOCATIONS" ("LOCATIONID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."LOCATIONDEPLOYMENTTYPES" ADD CONSTRAINT "FK_LOCATIONDEPLOYMENTTYPES_DEPLOYMENTTYPES_DEPLOYMENTTYPEID" FOREIGN KEY ("DEPLOYMENTTYPEID")
	  REFERENCES "CAMSDBUSER"."DEPLOYMENTTYPES" ("DEPLOYMENTTYPEID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."LOCATIONDEPLOYMENTTYPES" ADD CONSTRAINT "FK_LOCATIONDEPLOYMENTTYPES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;


ALTER TABLE CAMSDBUSER.LOCATIONDEPLOYMENTTYPES
MODIFY(ID  DEFAULT "CAMSDBUSER"."LOCATIONDEPLOYMENTTYPES_SEQ"."NEXTVAL");

COMMIT;


