using CAM.DataTransferObjects.QueryDto.Base;
using System.Collections.Generic;

namespace CAM.DataTransferObjects.QueryDto.BPT
{
    public class BPTQueryDto : QueryObject
    {
        public List<long> BudgetProjectTackerId { get; set; }
        public List<string> BudgetLineCode { get; set; }
        public List<string> UploadStatus { get; set; }
        public List<string> UploadMode { get; set; }
        public List<string> CurrentTrackingNumber { get; set; }
        public List<string> NewTrackingNumber { get; set; }
        public List<string> Wbs { get; set; }
        public List<short> OpcoId { get; set; }
        public List<string> Opco { get; set; }
        public List<string> Domain { get; set; }
        public List<string> Team { get; set; }
        public List<short> TeamId { get; set; }
        public List<string> BudgetOwner { get; set; }
        public List<short> BudgetOwnerid { get; set; }
        public List<string> Program { get; set; }
        public List<string> BudgetProject { get; set; }
        public List<long> Activity { get; set; }
        public List<string> Priority { get; set; }
        public List<string> Driver { get; set; }
        public List<string> Benefits { get; set; }
        public List<string> Risks { get; set; }
        public List<string> Category { get; set; }
        public List<short> CategoryId { get; set; }
        public List<string> Nwelement { get; set; }
        public List<string> VirtualizedNwElement { get; set; }
        public List<string> Vendor { get; set; }
        public List<short> LcmCategoriesId { get; set; }
        public List<string> LcmCategories { get; set; }
        public List<string> OhpLev1 { get; set; }
        public List<string> OhpLev2 { get; set; }
        public List<string> HfmLev1 { get; set; }
        public List<string> HfmLev2 { get; set; }
        public List<string> Fy { get; set; }
        public List<string> Operational { get; set; }
        public List<string> Transfers { get; set; }
        public List<string> Cost1sTest { get; set; }
        public List<string> Validation { get; set; }
        public List<string> SignOff { get; set; }
        public List<string> Sub { get; set; }
        public List<string> FinalReSub { get; set; }
        public List<string> LatestScenario { get; set; }
        public List<string> Currency { get; set; }
        public List<string> Adjustments { get; set; }
        public List<string> YtdActuals { get; set; }
        public List<string> PlannedAbsorption { get; set; }
        public List<string> Deviation { get; set; }
        public List<string> Apr { get; set; }
        public List<string> May { get; set; }
        public List<string> Jun { get; set; }
        public List<string> Jul { get; set; }
        public List<string> Aug { get; set; }
        public List<string> Sep { get; set; }
        public List<string> Oct { get; set; }
        public List<string> Nov { get; set; }
        public List<string> Dec { get; set; }
        public List<string> Jan { get; set; }
        public List<string> Feb { get; set; }
        public List<string> Mar { get; set; }
        public List<string> ApprovedBudget { get; set; }
        public List<string> Commitment { get; set; }
        public List<string> BudgetProjectDependency { get; set; }
        public List<string> LocalProgram { get; set; }
        public List<string> LocalBudgetProject { get; set; }
        public List<string> LocalDriver { get; set; }
        public List<string> LocalPrioritization { get; set; }
        public List<string> PpmId { get; set; }
        public List<string> PpmBudgetProjectId { get; set; }
        public List<string> CostCentre { get; set; }
        public List<string> WpId { get; set; }
        public List<string> GroupBudgetOpcoId { get; set; }
        public List<string> InternalProgram { get; set; }
        public List<string> VerticalProject { get; set; }
        public List<string> DomainSpecificLabels { get; set; }
        public List<string> LabelsMarketVsVertical { get; set; }
        public List<string> OtherMinorVendors { get; set; }
        public List<string> ExternalDemandBudget { get; set; }
        public List<string> OpexImpact { get; set; }
        public List<string> LegalEntity { get; set; }
        public List<string> YearlyTransfersTrack { get; set; }
        public List<string> YearlyAdjustmentsTrack { get; set; }
        public List<string> Mcustom02 { get; set; }
        public List<string> Mcustom03 { get; set; }
        public List<string> Mcustom04 { get; set; }
        public List<string> Mcustom05 { get; set; }
        public List<string> Mcustom06 { get; set; }
        public List<string> Mcustom07 { get; set; }
        public List<string> Mcustom08 { get; set; }
        public List<string> Mcustom09 { get; set; }
        public List<string> Mcustom10 { get; set; }
        public List<string> Vcustom01 { get; set; }
        public List<string> Vcustom02 { get; set; }
        public List<string> Vcustom03 { get; set; }
        public List<string> Vcustom04 { get; set; }
        public List<string> Vcustom05 { get; set; }
        public List<string> Dcustom01 { get; set; }
        public List<string> Dcustom02 { get; set; }
        public List<string> Dcustom03 { get; set; }
        public List<string> Dcustom04 { get; set; }
        public List<string> Dcustom05 { get; set; }
        public List<string> Lsdb { get; set; }
        public List<string> Ls012 { get; set; }
        public List<string> Ls210 { get; set; }
        public List<string> Ls57 { get; set; }
        public List<bool> Archive { get; set; }
        public List<long> PlannedActivityId { get; set; }
        public List<string> VerticalName { get; set; }
    }
}
