--------------------------------------------------------
--  DDL for Sequence APPSETTINGS_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "APPSETTINGS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


--------------------------------------------------------
--  DDL for Table APPCONFIGURATIONS
--------------------------------------------------------

  CREATE TABLE APPSETTINGS 
   (	
    "APPSETTINGID" NUMBER(19,0) DEFAULT "APPSETTINGS_SEQ"."NEXTVAL", 
	"DESCRIPTION" NVARCHAR2(50), 
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index APPSETTINGSIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPSETTINGSIDX" ON "APPSETTINGS" ("APPSETTINGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table APPSETTINGS
--------------------------------------------------------

ALTER TABLE "APPSETTINGS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "APPSETTINGS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "APPSETTINGS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "APPSETTINGS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "APPSETTINGS" ADD CONSTRAINT "PK_APPSETTINGS" PRIMARY KEY ("APPSETTINGID") USING INDEX "APPSETTINGSIDX"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APPSETTINGS
--------------------------------------------------------

ALTER TABLE "APPSETTINGS" ADD CONSTRAINT "FK_APPSETTINGS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "APPSETTINGS" ADD CONSTRAINT "FK_APPSETTINGS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
COMMIT;