--------------------------------------------------------
--  DDL for Sequence APPSETTINGSCONFIGURATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "APPSETTINGSCONFIGURATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

--------------------------------------------------------
--  DDL for Table APPSETTINGSCONFIGURATION
--------------------------------------------------------

  CREATE TABLE APPSETTINGSCONFIGURATION 
   (	
    "APPCONFIGURATIONSETTINGID" NUMBER(19,0) DEFAULT "APPSETTINGSCONFIGURATION_SEQ"."NEXTVAL", 
	"APPSETTINGID" NUMBER(19,0), 
	"SETTINGSVALUE" NVARCHAR2(50), 
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index APPSETTINGSCONFIGURATIONIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPSETTINGSCONFIGURATIONIDX" ON "APPSETTINGSCONFIGURATION" ("APPCONFIGURATIONSETTINGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table APPSETTINGSCONFIGURATION
--------------------------------------------------------

ALTER TABLE "APPSETTINGSCONFIGURATION" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "APPSETTINGSCONFIGURATION" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "APPSETTINGSCONFIGURATION" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "APPSETTINGSCONFIGURATION" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "APPSETTINGSCONFIGURATION" ADD CONSTRAINT "PK_APPSETTINGSCONFIGURATION" PRIMARY KEY ("APPCONFIGURATIONSETTINGID") USING INDEX "APPSETTINGSCONFIGURATIONIDX"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APPSETTINGSCONFIGURATION
--------------------------------------------------------

ALTER TABLE "APPSETTINGSCONFIGURATION" ADD CONSTRAINT "FK_APPSETTINGSCONFIGURATION_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "APPSETTINGSCONFIGURATION" ADD CONSTRAINT "FK_APPSETTINGSCONFIGURATION_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "APPSETTINGSCONFIGURATION" ADD CONSTRAINT "FK_APPSETTINGSCONFIGURATION_APPSETTINGS_APPSETTINGID" FOREIGN KEY ("APPSETTINGID") REFERENCES "APPSETTINGS" ("APPSETTINGID") ENABLE;
COMMIT;

