ALTER TABLE ASPNETUSERS DROP COLUMN ISSUBDOMAINSPOC;
ALTER TABLE ASPNETUSERS DROP COLUMN ISEDUSPOC;
ALTER TABLE ASPNETUSERS DROP COLUMN ISDESIGNCONTACT;
ALTER TABLE ASPNETUSERS DROP COLUMN SUBDOMAINRESPONSIBLEID;
