ALTER TABLE ASPNETUSERROLES ADD OPCOID NUMBER(5,0);
ALTER TABLE ASPNETUSERROLES ADD VERTICALRESPONSIBLEID NUMBER(10,0);


  ALTER TABLE "ASPNETUSERROLES" ADD CONSTRAINT"FK_ASPNETUSERROLES_OPCOS_OPCOID" FOREIGN KEY ("OPCOID") REFERENCES "OPCOS" ("OPCOID") ENABLE;
  ALTER TABLE "ASPNETUSERROLES" ADD CONSTRAINT"FK_ASPNETUSERROLES_VERTICALRESPONSIBLES_VERTICALRESPONSIBLEID" FOREIGN KEY ("VERTICALRESPONSIBLEID") REFERENCES "VERTICALRESPONSIBLES" ("VERTICALRESPONSIBLEID") ENABLE;