ALTER TABLE ORGANISATION ADD SUBDOMAINRESPONSIBLEID NUMBER(10,0);
ALTER TABLE ORGANISATION ADD CONTACTID NUMBER(10,0);
ALTER TABLE ORGANISATION ADD ISSUBDOMAINSPOC NUMBER(1,0);
ALTER TABLE ORGANISATION ADD ISEDUSPOC NUMBER(1,0);
ALTER TABLE ORGANISATION ADD ISDESIGNCONTACT NUMBER(1,0);
ALTER TABLE ORGANISATION DROP COLUMN VERTICALID;

  ALTER TABLE "ORGANISATION" ADD CONSTRAINT"FK_ORGANISATION_SUBDOMAINRESPONSIBLES_SUBDOMAINRESPONSIBLEID" FOREIGN KEY ("SUBDOMAINRESPONSIBLEID") REFERENCES "SUBDOMAINRESPONSIBLES" ("SUBDOMAINRESPONSIBLEID") ENABLE;
  
  ALTER TABLE "ORGANISATION" ADD CONSTRAINT"FK_ORGANISATION_ASPNETUSERS_CONTACTID" FOREIGN KEY ("CONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;  