--- EXoDus - PRODUCT Table add new column

ALTER TABLE PRODUCTNAME ADD  ISPLATFORMSOFTWARE NUMBER(1) DEFAULT 0;

------------- New Rule for DA - PA
DROP SEQUENCE PLANNEDACTIVITYTYPESID_SEQ;

CREATE SEQUENCE  "PLANNEDACTIVITYTYPESID_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999 
INCREMENT BY 1 START WITH  18 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT" ) 
VALUES ('Infra Readiness', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,0,0,1);

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT" ) 
VALUES ('Platform Migration', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,0,0,1);

COMMIT;

 UPDATE productname pn SET pn.ISPLATFORMSOFTWARE = CASE WHEN EXISTS (  SELECT 1 FROM majorsoftwarebuilds msw WHERE msw.PRODUCTNAMEID = pn.PRODUCTNAMEID AND msw.deleted = 0 AND msw.isvmware = 1 ) THEN 1 ELSE 0    END;
Commit; 

---------------------------------
 
ALTER TABLE VNFNAME MODIFY PRODUCTID  NULL;
ALTER TABLE PODTYPEINFO MODIFY PODROLEDESCRIPTION  NULL;
ALTER TABLE VNFCLUSTERINFO MODIFY NOOFBLADES  NULL;

--------------------------------------------------------
--  DDL FOR SEQUENCE DAMIGRATIONSTATUS_SQE
--------------------------------------------------------

CREATE SEQUENCE "DAMIGRATIONSTATUS_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE DAMIGRATIONSTATUS
--------------------------------------------------------

CREATE TABLE DAMIGRATIONSTATUS 
   (	
    DAMIGRATIONSTATUID NUMBER(19,0) DEFAULT DAMIGRATIONSTATUS_SQE.NEXTVAL  NOT NULL, 
	PLANNEDACTIVITYID NUMBER(19,0) NOT NULL,
	OPCOID NUMBER(5,0) NOT NULL,
	LOCATIONID NUMBER(5,0) NOT NULL,
	STATUSID NUMBER(5,0)  NOT NULL, 	 
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_DAMIGRATIONSTATUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_DAMIGRATIONSTATUS" ON DAMIGRATIONSTATUS ("DAMIGRATIONSTATUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
 --------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE DAMIGRATIONSTATUS MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE DAMIGRATIONSTATUS MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE DAMIGRATIONSTATUS MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE DAMIGRATIONSTATUS MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE DAMIGRATIONSTATUS ADD CONSTRAINT "PK_DAMIGRATIONSTATU" PRIMARY KEY ("DAMIGRATIONSTATUID") ;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE DAMIGRATIONSTATUS ADD CONSTRAINT "FK_DAMIGRATIONSTATUS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE DAMIGRATIONSTATUS ADD CONSTRAINT "FK_DAMIGRATIONSTATUS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE; 
	
ALTER TABLE DAMIGRATIONSTATUS ADD CONSTRAINT "FK_DAMIGRATIONSTATUS_OPCOS_OPCOID" FOREIGN KEY ("OPCOID")
	  REFERENCES "OPCOS" ("OPCOID") ENABLE;
ALTER TABLE DAMIGRATIONSTATUS ADD CONSTRAINT "FK_DAMIGRATIONSTATUS_LOCATIONS_LOCATIONID" FOREIGN KEY ("LOCATIONID")
	  REFERENCES "LOCATIONS" ("LOCATIONID") ENABLE;	 

 ALTER TABLE DAMIGRATIONSTATUS ADD CONSTRAINT "FK_DAMIGRATIONSTATUS_PLANNEDACTIVITIES_PLANNEDACTIVITYID" FOREIGN KEY ("PLANNEDACTIVITYID")
	  REFERENCES "PLANNEDACTIVITIES" ("PLANNEDACTIVITYID") ENABLE; 		  
-------------------------------------------------	  