-------------------------------------------------------
--  DDL for Sequence PROJECTPLANAUDIT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJECTPLANAUDIT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

--------------------------------------------------------
--  DDL for Table PROJECTPLANAUDIT
--------------------------------------------------------

  CREATE TABLE "PROJECTPLANAUDIT" 
   (	"PROJECTPLANAUDITID" NUMBER(19,0) DEFAULT "PROJECTPLANAUDIT_SEQ"."NEXTVAL", 
    "PROJECTSPLANID" NUMBER(19,0),
	"OLDVALUE" NVARCHAR2(2000), 
    "NEWVALUE" NVARCHAR2(2000),
    "PROCESSTYPE" NUMBER(5,0),
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index PROJECTPLANAUDITIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECTPLANAUDITIDX" ON "PROJECTPLANAUDIT" ("PROJECTPLANAUDITID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table PROJECTPLANAUDIT
--------------------------------------------------------

  ALTER TABLE "PROJECTPLANAUDIT" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "PROJECTPLANAUDIT" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECTPLANAUDIT" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "PROJECTPLANAUDIT" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECTPLANAUDIT" ADD CONSTRAINT "PK_PROJECTPLANAUDIT" PRIMARY KEY ("PROJECTPLANAUDITID")
  USING INDEX "PROJECTPLANAUDITIDX"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJECTPLANAUDIT
--------------------------------------------------------

  ALTER TABLE "PROJECTPLANAUDIT" ADD CONSTRAINT "FK_PROJECTPLANAUDIT_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "PROJECTPLANAUDIT" ADD CONSTRAINT "FK_PROJECTPLANAUDIT_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "PROJECTPLANAUDIT" ADD CONSTRAINT "FK_PROJECTPLANAUDIT_PROJECTSPLAN_PROJECTSPLANID" FOREIGN KEY ("PROJECTSPLANID")
	  REFERENCES "PROJECTSPLAN" ("PROJECTSPLANID") ENABLE;      



----Alter Table projectplan ---------------------
UPDATE PROJECTSPLAN SET BASELINESTARTDATE = PLANNINGSTARTDATE;
UPDATE PROJECTSPLAN SET BASELINEENDDATE = PLANNINGENDDATE;
COMMIT;