--------------------------------------------------------
--  DDL FOR TABLE SERVICEMASTER_SEQ
--------------------------------------------------------

CREATE SEQUENCE "SERVICEMASTER_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE SERVICEMASTER 
---------------------------------------


CREATE TABLE "SERVICEMASTER" 
(	"SERVICEMASTERID" NUMBER(10,0) DEFAULT "SERVICEMASTER_SEQ"."NEXTVAL", 	
	"DESCRIPTION" NVARCHAR2(250),	
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
  
  --------------------------------------------------------
--  DDL FOR INDEX PK_SERVICEMASTER
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_SERVICEMASTER" ON "SERVICEMASTER" ("SERVICEMASTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE SERVICEMASTER
--------------------------------------------------------
 
  ALTER TABLE "SERVICEMASTER" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMASTER" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMASTER" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMASTER" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMASTER" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMASTER" ADD CONSTRAINT "PK_SERVICEMASTER" PRIMARY KEY ("SERVICEMASTERID") USING INDEX "PK_SERVICEMASTER"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE SERVICEMASTER
--------------------------------------------------------

  ALTER TABLE "SERVICEMASTER" ADD CONSTRAINT "FK_SERVICEMASTER_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "SERVICEMASTER" ADD CONSTRAINT "FK_SERVICEMASTER_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  COMMIT;