--------------------------------------------------------
--  DDL FOR TABLE SERVICEPLAN_SEQ
--------------------------------------------------------

CREATE SEQUENCE "SERVICEPLAN_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE SERVICEPLAN 
---------------------------------------


CREATE TABLE "SERVICEPLAN" 
(	"SERVICEPLANID" NUMBER(10,0) DEFAULT "SERVICEPLAN_SEQ"."NEXTVAL", 	
	"SERVICEMASTERID" NUMBER(10,0),
	"DESIGNCOMPONENTFAMILYID" NUMBER(19,0),
	"STATUS" NUMBER(5,0),
	"PLANNEDACTIVITYID" NUMBER(19,0),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
  
  --------------------------------------------------------
--  DDL FOR INDEX PK_SERVICEPLAN
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_SERVICEPLAN" ON "SERVICEPLAN" ("SERVICEPLANID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE SERVICEPLAN
--------------------------------------------------------
 
  ALTER TABLE "SERVICEPLAN" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "SERVICEPLAN" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "SERVICEPLAN" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "SERVICEPLAN" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "SERVICEPLAN" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "SERVICEPLAN" MODIFY ("PLANNEDACTIVITYID" NOT NULL ENABLE);
  ALTER TABLE "SERVICEPLAN" MODIFY ("SERVICEMASTERID" NOT NULL ENABLE);
  ALTER TABLE "SERVICEPLAN" MODIFY ("DESIGNCOMPONENTFAMILYID" NOT NULL ENABLE);
  ALTER TABLE "SERVICEPLAN" ADD CONSTRAINT "PK_SERVICEPLAN" PRIMARY KEY ("SERVICEPLANID") USING INDEX "PK_SERVICEPLAN"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE SERVICEPLAN
--------------------------------------------------------

  ALTER TABLE "SERVICEPLAN" ADD CONSTRAINT "FK_SERVICEPLAN_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "SERVICEPLAN" ADD CONSTRAINT "FK_SERVICEPLAN_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "SERVICEPLAN" ADD CONSTRAINT "FK_SERVICEPLAN_PLANNEDACTIVITIES_PLANNEDACTIVITYID" FOREIGN KEY ("PLANNEDACTIVITYID") REFERENCES "PLANNEDACTIVITIES" ("PLANNEDACTIVITYID") ENABLE;
  ALTER TABLE "SERVICEPLAN" ADD CONSTRAINT "FK_SERVICEPLAN_SERVICEMASTER_SERVICEMASTERID" FOREIGN KEY ("SERVICEMASTERID") REFERENCES "SERVICEMASTER" ("SERVICEMASTERID") ENABLE;
  ALTER TABLE "SERVICEPLAN" ADD CONSTRAINT "FK_SERVICEPLAN_DESIGNCOMPONENTFAMILIES_DESIGNCOMPONENTFAMILYID" FOREIGN KEY ("DESIGNCOMPONENTFAMILYID") REFERENCES "DESIGNCOMPONENTFAMILIES" ("DESIGNCOMPONENTFAMILYID") ENABLE;


  COMMIT;