
------------- New Rule for DA - PA
DROP SEQUENCE PLANNEDACTIVITYTYPESID_SEQ;

CREATE SEQUENCE  "PLANNEDACTIVITYTYPESID_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999 
INCREMENT BY 1 START WITH  34 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT"  ) 
VALUES ('AddNewCluster', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,1,0,0); 

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT"  ) 
VALUES ('Add/Remove Application from Cluster', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,1,0,0); 

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT"  ) 
VALUES ('Upgrade HardwareTypes', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,1,0,0);  

Commit;