--------  SCRIPT FOR APPSETTINGS---------------
INSERT INTO  "APPSETTINGS" (APPSETTINGID, DESCRIPTION, CREATIONUSER, MODIFICATIONUSER) VALUES ('3', N'ExodusOemFilter', '1', '1');
INSERT INTO "APPSETTINGS" (APPSETTINGID, DESCRIPTION, CREATIONUSER, MODIFICATIONUSER) VALUES ('4', N'ExodusPlatformFilter', '1', '1');
Commit;

--------  SCRIPT FOR APPSETTINGSCONFIGURATION---------------
INSERT INTO "APPSETTINGSCONFIGURATION" (APPSETTINGID, SETTINGSVALUE, CREATIONUSER, MODIFICATIONUSER) VALUES ('3', N'Broadcom', '1', '1');  
INSERT INTO "APPSETTINGSCONFIGURATION" (APPSETTINGID, SETTINGSVALUE, CREATIONUSER, MODIFICATIONUSER) VALUES ('4', N'Other NFVI', '1', '1');
INSERT INTO "APPSETTINGSCONFIGURATION" (APPSETTINGID, SETTINGSVALUE, CREATIONUSER, MODIFICATIONUSER) VALUES ('4', N'Other NFCI', '1', '1');
INSERT INTO "APPSETTINGSCONFIGURATION" (APPSETTINGID, SETTINGSVALUE, CREATIONUSER, MODIFICATIONUSER) VALUES ('4', N'VMWare NFVI', '1', '1');
INSERT INTO "APPSETTINGSCONFIGURATION" (APPSETTINGID, SETTINGSVALUE, CREATIONUSER, MODIFICATIONUSER) VALUES ('4', N'VMWare NFCI', '1', '1');
INSERT INTO "APPSETTINGSCONFIGURATION" (APPSETTINGID, SETTINGSVALUE, CREATIONUSER, MODIFICATIONUSER) VALUES ('4', N'VMWare CaaS', '1', '1');
Commit;