--------  SCRIPT FOR APPSETTINGS---------------
INSERT INTO "APPSETTINGS" (APPSETTINGID, DESCRIPTION, CREATIONUSER, MODIFICATIONUSER, DELETED) VALUES ('5', N'RestrictedOpco', '1', '1', '0');
Commit;

--------  SCRIPT FOR APPSETTINGSCONFIGURATION---------------
INSERT INTO "APPSETTINGSCONFIGURATION" (APPSETTINGID, SETTINGSVALUE, CREATIONUSER, MODIFICATIONUSER, DELETED) VALUES ('5', N'IT', '1', '1', '0');
INSERT INTO "APPSETTINGSCONFIGURATION" (APPSETTINGID, SETTINGSVALUE, CREATIONUSER, MODIFICATIONUSER, DELETED) VALUES ('5', N'ZZZ', '1', '1', '0');

Commit;
