----------ALTER SCRIPT FOR THE DAASSETMIGRATION--------------------------
 
ALTER TABLE DAASSETMIGRATION ADD PLATFORMID NUMBER(5,0);
ALTER TABLE DAASSETMIGRATION ADD PRODUCTNAMEID NUMBER(20,0);
 
ALTER TABLE "DAASSETMIGRATION" ADD CONSTRAINT "FK_DAASSETMIGRATION_PLATFORMS_PLATFORMID" FOREIGN KEY ("PLATFORMID") REFERENCES "PLATFORMS" ("PLATFORMID") ENABLE;
ALTER TABLE "DAASSETMIGRATION" ADD CONSTRAINT "FK_DAASSETMIGRATION_PRODUTNAME_PRODUCTNAMEID" FOREIGN KEY ("PRODUCTNAMEID") REFERENCES "PRODUCTNAME" ("PRODUCTNAMEID") ENABLE;


---Exodus_Platform_Productid update for DAAssetMigration table

MERGE INTO DAASSETMIGRATION dam
USING (
    SELECT DISTINCT
           pa.PLANNEDACTIVITYID,
           mb.PLATFORMID,
           dcf.PRODUCTNAMEID
    FROM PlannedActivities pa
    JOIN DesignComponentFamilies dcf
        ON pa.DESIGNCOMPONENTFAMILYID = dcf.DESIGNCOMPONENTFAMILYID
    JOIN DesignComponents dc
        ON pa.DESIGNCOMPONENTFAMILYID = dc.DESIGNCOMPONENTFAMILYID
    JOIN SystemTypes st
        ON dc.SYSTEMTYPEID = st.SYSTEMTYPEID
    JOIN SystemTypesMajorHardwareBuilds mh
        ON mh.SYSTEMTYPEID = st.SYSTEMTYPEID
       --AND mh.ISMAIN = 1
    JOIN MajorHardwareBuilds mb
        ON mh.MAJORHARDWAREID = mb.MAJORHARDWAREID
    JOIN MajorSoftwareBuilds msb
        ON msb.MAJORSOFTWAREBUILDSID = st.MAJORSOFTWAREBUILDSID
    JOIN BuildConstructions b
        ON b.BUILDCONSTRUCTIONID = mb.BUILDCONSTRUCTIONID
    JOIN OriginalEquipmentManufacturers oem
        ON oem.ORGEQPMANUFACTURERID = msb.ORGEQPMANUFACTURERID
) src
ON (dam.PLANNEDACTIVITYID = src.PLANNEDACTIVITYID)
WHEN MATCHED THEN
UPDATE SET
    dam.PLATFORMID    = src.PLATFORMID,
    dam.PRODUCTNAMEID = src.PRODUCTNAMEID;
	
Commit;
