
--------------------------------------------------------
--  DDL for Sequence TRANSIENTDESIGNCOMPONENTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE "TRANSIENTDESIGNCOMPONENTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

Commit;
  
  --------------------------------------------------------
--  DDL for Table TRANSIENTDESIGNCOMPONENTS
--------------------------------------------------------

 CREATE TABLE "TRANSIENTDESIGNCOMPONENTS" 
   (
	"TRANSIENTDESIGNCOMPONENTID" NUMBER(19,0) DEFAULT  "TRANSIENTDESIGNCOMPONENTS_SEQ"."NEXTVAL", 
	"SYSTEMTYPEID" NUMBER(19,0), 
	"GDPRRELEVANT" NUMBER(1,0), 
	"SUBNETWORKBOUNDARYID" NUMBER(19,0), 
	"DESIGNCOMPONENTFAMILYID" NUMBER(19,0),	
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
  
  Commit;
--------------------------------------------------------
--  DDL for Index TRANSIENTDESIGNCOMPONENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRANSIENTDESIGNCOMPONENTS_PK" ON "TRANSIENTDESIGNCOMPONENTS" ("TRANSIENTDESIGNCOMPONENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB" ;
  Commit;
--------------------------------------------------------
--  Constraints for Table TRANSIENTDESIGNCOMPONENTS
--------------------------------------------------------

  ALTER TABLE "TRANSIENTDESIGNCOMPONENTS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "TRANSIENTDESIGNCOMPONENTS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "TRANSIENTDESIGNCOMPONENTS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "TRANSIENTDESIGNCOMPONENTS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "TRANSIENTDESIGNCOMPONENTS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "TRANSIENTDESIGNCOMPONENTS" MODIFY ("SYSTEMTYPEID" NOT NULL ENABLE);
  ALTER TABLE "TRANSIENTDESIGNCOMPONENTS" MODIFY ("GDPRRELEVANT" NOT NULL ENABLE);
  ALTER TABLE "TRANSIENTDESIGNCOMPONENTS" MODIFY ("SUBNETWORKBOUNDARYID" NOT NULL ENABLE);
  ALTER TABLE "TRANSIENTDESIGNCOMPONENTS" ADD CONSTRAINT "TRANSIENTDESIGNCOMPONENTS_PK" PRIMARY KEY ("TRANSIENTDESIGNCOMPONENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;
  Commit;
--------------------------------------------------------
--  Ref Constraints for Table TRANSIENTDESIGNCOMPONENTS
--------------------------------------------------------

  ALTER TABLE "TRANSIENTDESIGNCOMPONENTS" ADD CONSTRAINT "FK_TRANSIENTDESIGNCOMPONENTS_SYSTEMTYPES_SYSTEMTYPEID" FOREIGN KEY ("SYSTEMTYPEID")
	  REFERENCES "SYSTEMTYPES" ("SYSTEMTYPEID") ENABLE;
  ALTER TABLE "TRANSIENTDESIGNCOMPONENTS" ADD CONSTRAINT "FK_TRANSIENTDESIGNCOMPONENTSS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "TRANSIENTDESIGNCOMPONENTS" ADD CONSTRAINT "FK_TRANSIENTDESIGNCOMPONENTS_DESIGNCOMPONENTFAMILIES_DESIGNCOMPONENTFAMILYID" FOREIGN KEY ("DESIGNCOMPONENTFAMILYID")
	  REFERENCES "DESIGNCOMPONENTFAMILIES" ("DESIGNCOMPONENTFAMILYID") ENABLE;
  ALTER TABLE "TRANSIENTDESIGNCOMPONENTS" ADD CONSTRAINT "FK_TRANSIENTDESIGNCOMPONENTS_SUBNETWORKBOUNDARIES_ID" FOREIGN KEY ("SUBNETWORKBOUNDARYID")
	  REFERENCES "SUBNETWORKBOUNDARIES" ("ID") ENABLE;
  ALTER TABLE "TRANSIENTDESIGNCOMPONENTS" ADD CONSTRAINT "FK_TRANSIENTDESIGNCOMPONENTS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
	  Commit;