using CAM.Entities.Mappers.Identity;
using CAM.Entities.Models.CBom;
using CAM.Entities.Models.FNT;
using OracleModels.DBModels;

namespace CAM.Entities.Mappers.Cbom
{
    public class TemsFntReportMapper
    {
        public static TemsFntReport GetTemsFntReportMapper(Temsfntreport model)
        {
            if (model == null)
                return null;
            var result = new TemsFntReport()
            {
                Temsfntreportid = model.Temsfntreportid,
                Hostname = model.Hostname,
                Serialnumberofhardwareasset = model.Serialnumberofhardwareasset,
                Locationofhardwareasset = model.Locationofhardwareasset,
                Hardwaretypeofhardwareasset = model.Hardwaretypeofhardwareasset,
                Vendor = model.Vendor,
                Ipaddressofhardwareasset = model.Ipaddressofhardwareasset,
                Market = model.Market,
                Hwendoflife = model.Hwendoflife,
                Hwendofsupport = model.Hwendofsupport,
                Hwendofsale = model.Hwendofsale,
                Hardwaremodules = model.Hardwaremodules,
                Softwareproducttype = model.Softwareproducttype,
                Softwareproductversion = model.Softwareproductversion,
                Softwareisvirtualized = model.Softwareisvirtualized,
                OperatingSystemofvirtualmachine = model.OperatingSystemofvirtualmachine,
                Applicationhostedonsoftware = model.Applicationhostedonsoftware,
                Uuidserialnumberofsoftware = model.Uuidserialnumberofsoftware,
                Softwarevendor = model.Softwarevendor,
                Locationofsoftware = model.Locationofsoftware,
                Servicetype = model.Servicetype,
                Swendoflife = model.Swendoflife,
                Swendofsupport = model.Swendofsupport,
                Swendofsale = model.Swendofsale,
                Verticalengineeringteam = model.Verticalengineeringteam,
                Verticalsubdomain = model.Verticalsubdomain,
                Platform = model.Platform,
                Riskcluster = model.Riskcluster,
                Operationscontactpoint = model.Operationscontactpoint,
                Assetcategory = model.Assetcategory,
                Assetclass = model.Assetclass,
                Assettype = model.Assettype,
                Assetdescription = model.Assetdescription,
                Productimportance = model.Productimportance,
                Operationsmaintenancecontract = model.Operationsmaintenancecontract,
                Vendorendofmaintenancedate = model.Vendorendofmaintenancedate,
                Identifiedaction = model.Identifiedaction,
                Descriptionofplannedaction = model.Descriptionofplannedaction,
                Plannedhwmodel = model.Plannedhwmodel,
                Businessservicename = model.Businessservicename,
                Opmaintenancecontractenddate = model.Opmaintenancecontractenddate,
                Incidentclass = model.Incidentclass,
                Occurrenceprobability = model.Occurrenceprobability,
                Meverticalresposible = model.Meverticalresposible,
                Assetstatus = model.Assetstatus,
                Typeofnetworkelement = model.Typeofnetworkelement,
                Localmarket = model.Localmarket,
                Application = model.Application,
                Cloud = model.Cloud,
                Physicalserverhostname = model.Physicalserverhostname,
                Physicalserveripaddress = model.Physicalserveripaddress,
                Physicalserverserialnumber = model.Physicalserverserialnumber,
                Physicalserverhwmodel = model.Physicalserverhwmodel,
                Physicalservervendor = model.Physicalservervendor,
                Virtualserverhostedon = model.Virtualserverhostedon,
                Virtualservermanufacturer = model.Virtualservermanufacturer,
                Virtualservertypeofdevice = model.Virtualservertypeofdevice,
                Virtualmachinetype = model.Virtualmachinetype,
                Virtualserveripaddress = model.Virtualserveripaddress,
                Virtualserverserialnumber = model.Virtualserverserialnumber,
                Virtualservertype = model.Virtualservertype,
                Osname = model.Osname,
                Osversion = model.Osversion,
                Osstartdate = model.Osstartdate,
                Osinstallationdate = model.Osinstallationdate,
                Osstatus = model.Osstatus,
                Softwarename = model.Softwarename,
                Version = model.Version,
                Release = model.Release,
                Manufacturer = model.Manufacturer,
                Language = model.Language,
                Hwopscontractstatus = model.Hwopscontractstatus,
                Hwopscontractenddate = model.Hwopscontractenddate,
                Swopscontractstatus = model.Swopscontractstatus,
                Swopscontractenddate = model.Swopscontractenddate,
                Hwoperationscontactpoint = model.Hwoperationscontactpoint,
                Swoperationscontactpoint = model.Swoperationscontactpoint,
                Physicalserverosname = model.Physicalserverosname,
                Physicalserverosversion = model.Physicalserverosversion,
                Physicalserverosstartdate = model.Physicalserverosstartdate,
                Physicalserverosinstallationdate = model.Physicalserverosinstallationdate,
                Physicalserverosstatus = model.Physicalserverosstatus,
                Model = model.Model,
                Deletiondate = model.Deletiondate,
                Deleted = model.Deleted.Value,
                CreationDate = model.Creationdate,
                CreationUser = model.Creationuser,
                ModificationDate = model.Modificationdate,
                ModificationUser = model.Modificationuser,
                CreationUserEntity = ApplicationUserMapper.GetApplicationUserMapper(model.CreationuserNavigation),
                ModificationUserEntity = ApplicationUserMapper.GetApplicationUserMapper(model.ModificationuserNavigation),
            };

            return result;
        }

        public static Temsfntreport SetTemsFntReportMapper(TemsFntReport model)
        {
            if (model == null)
                return null;
            var result = new Temsfntreport()
            {
                Temsfntreportid = model.Temsfntreportid,
                Hostname = model.Hostname,
                Serialnumberofhardwareasset = model.Serialnumberofhardwareasset,
                Locationofhardwareasset = model.Locationofhardwareasset,
                Hardwaretypeofhardwareasset = model.Hardwaretypeofhardwareasset,
                Vendor = model.Vendor,
                Ipaddressofhardwareasset = model.Ipaddressofhardwareasset,
                Market = model.Market,
                Hwendoflife = model.Hwendoflife,
                Hwendofsupport = model.Hwendofsupport,
                Hwendofsale = model.Hwendofsale,
                Hardwaremodules = model.Hardwaremodules,
                Softwareproducttype = model.Softwareproducttype,
                Softwareproductversion = model.Softwareproductversion,
                Softwareisvirtualized = model.Softwareisvirtualized,
                OperatingSystemofvirtualmachine = model.OperatingSystemofvirtualmachine,
                Applicationhostedonsoftware = model.Applicationhostedonsoftware,
                Uuidserialnumberofsoftware = model.Uuidserialnumberofsoftware,
                Softwarevendor = model.Softwarevendor,
                Locationofsoftware = model.Locationofsoftware,
                Servicetype = model.Servicetype,
                Swendoflife = model.Swendoflife,
                Swendofsupport = model.Swendofsupport,
                Swendofsale = model.Swendofsale,
                Verticalengineeringteam = model.Verticalengineeringteam,
                Verticalsubdomain = model.Verticalsubdomain,
                Platform = model.Platform,
                Riskcluster = model.Riskcluster,
                Operationscontactpoint = model.Operationscontactpoint,
                Assetcategory = model.Assetcategory,
                Assetclass = model.Assetclass,
                Assettype = model.Assettype,
                Assetdescription = model.Assetdescription,
                Productimportance = model.Productimportance,
                Operationsmaintenancecontract = model.Operationsmaintenancecontract,
                Vendorendofmaintenancedate = model.Vendorendofmaintenancedate,
                Identifiedaction = model.Identifiedaction,
                Descriptionofplannedaction = model.Descriptionofplannedaction,
                Plannedhwmodel = model.Plannedhwmodel,
                Businessservicename = model.Businessservicename,
                Opmaintenancecontractenddate = model.Opmaintenancecontractenddate,
                Incidentclass = model.Incidentclass,
                Occurrenceprobability = model.Occurrenceprobability,
                Meverticalresposible = model.Meverticalresposible,
                Assetstatus = model.Assetstatus,
                Typeofnetworkelement = model.Typeofnetworkelement,
                Localmarket = model.Localmarket,
                Application = model.Application,
                Cloud = model.Cloud,
                Physicalserverhostname = model.Physicalserverhostname,
                Physicalserveripaddress = model.Physicalserveripaddress,
                Physicalserverserialnumber = model.Physicalserverserialnumber,
                Physicalserverhwmodel = model.Physicalserverhwmodel,
                Physicalservervendor = model.Physicalservervendor,
                Virtualserverhostedon = model.Virtualserverhostedon,
                Virtualservermanufacturer = model.Virtualservermanufacturer,
                Virtualservertypeofdevice = model.Virtualservertypeofdevice,
                Virtualmachinetype = model.Virtualmachinetype,
                Virtualserveripaddress = model.Virtualserveripaddress,
                Virtualserverserialnumber = model.Virtualserverserialnumber,
                Virtualservertype = model.Virtualservertype,
                Osname = model.Osname,
                Osversion = model.Osversion,
                Osstartdate = model.Osstartdate,
                Osinstallationdate = model.Osinstallationdate,
                Osstatus = model.Osstatus,
                Softwarename = model.Softwarename,
                Version = model.Version,
                Release = model.Release,
                Manufacturer = model.Manufacturer,
                Language = model.Language,
                Hwopscontractstatus = model.Hwopscontractstatus,
                Hwopscontractenddate = model.Hwopscontractenddate,
                Swopscontractstatus = model.Swopscontractstatus,
                Swopscontractenddate = model.Swopscontractenddate,
                Hwoperationscontactpoint = model.Hwoperationscontactpoint,
                Swoperationscontactpoint = model.Swoperationscontactpoint,
                Physicalserverosname = model.Physicalserverosname,
                Physicalserverosversion = model.Physicalserverosversion,
                Physicalserverosstartdate = model.Physicalserverosstartdate,
                Physicalserverosinstallationdate = model.Physicalserverosinstallationdate,
                Model = model.Model,
                Physicalserverosstatus = model.Physicalserverosstatus,
                Deletiondate = model.Deletiondate,
                Deleted = model.Deleted,

            };
            return result;
        }
    }
}
