----------ROLLBACK SCRIPT FOR NFVISOFTWARECOMPATIBILITY AND CONFIG TABLES---------

DROP SEQUENCE  "NFVISOFTWARECOMPATIBILITY_SEQ";
DROP TABLE NFVISOFTWARECOMPATIBILITY; 

------------------------------END----------------------------------