CREATE TABLE ASPNETUSERS_BACKUP AS SELECT  * FROM ASPNETUSERS;
CREATE TABLE ASPNETUSERROLES_BACKUP AS SELECT  * FROM ASPNETUSERROLES;
CREATE TABLE SYSTEMTYPES_BACKUP AS SELECT  * FROM SYSTEMTYPES;   
CREATE TABLE SUBDOMAINSPOC_BACKUP AS SELECT  * FROM SUBDOMAINSPOC;
CREATE TABLE SYSTEMTYPESSUBDOMAINSPOC_BACKUP AS SELECT  * FROM SYSTEMTYPESSUBDOMAINSPOC;
CREATE TABLE LCMENGINEERINGSUBDOMAINSPOC_BACKUP AS SELECT  * FROM LCMENGINEERINGSUBDOMAINSPOC; 
CREATE TABLE LCMENGINEERINGEDUSPOC_BACKUP AS SELECT  * FROM LCMENGINEERINGEDUSPOC; 
CREATE TABLE DESIGNCOMPONENTS_BACKUP AS SELECT  * FROM DESIGNCOMPONENTS; 
CREATE TABLE DESIGNCOMPONENTFAMILIES_BACKUP AS SELECT  * FROM DESIGNCOMPONENTFAMILIES; 
CREATE TABLE NETWORKELEMENTASPLANNEDEDUSPOC_BACKUP AS SELECT  * FROM NETWORKELEMENTASPLANNEDEDUSPOC;
CREATE TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_BACKUP AS SELECT  * FROM NETWORKELEMENTASPLANNEDSUBDOMAINSPOC;


COMMIT;


