--------------------------------------------------------
--  DDL FOR SEQUENCE PRACTICE_SEQ
--------------------------------------------------------
 
CREATE SEQUENCE "PRACTICE_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;
 
 
 
--------------------------------------------------------
--  DDL FOR TABLE PRACTICE
--------------------------------------------------------

CREATE TABLE PRACTICE (
"PRACTICEID" NUMBER(10,0) DEFAULT "PRACTICE_SEQ"."NEXTVAL",
"PRACTICEDESCRIPTION" NVARCHAR2(50), 
"PRACTICEEMAILID"  NUMBER(10,0),
"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"DELETED" NUMBER(1,0) DEFAULT 0, 
"DELETIONDATE" TIMESTAMP (6)
)SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_PRACTICE
--------------------------------------------------------
 
CREATE UNIQUE INDEX "PK_PRACTICE" ON "PRACTICE" ("PRACTICEID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE PRACTICE
--------------------------------------------------------
 
ALTER TABLE "PRACTICE" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "PRACTICE" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "PRACTICE" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "PRACTICE" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "PRACTICE" ADD CONSTRAINT "PK_PRACTICE" PRIMARY KEY ("PRACTICEID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE PRACTICE
--------------------------------------------------------
 
ALTER TABLE "PRACTICE" ADD CONSTRAINT "FK_PRACTICE_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "PRACTICE" ADD CONSTRAINT "FK_PRACTICE_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "PRACTICE" ADD CONSTRAINT "FK_PRACTICE_ASPNETUSERS_PRACTICEEMAILID" FOREIGN KEY ("PRACTICEEMAILID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
 
COMMIT;

--------------------------------------------------------
-- INSERT QUERY FOR PRACTICE
--------------------------------------------------------
INSERT INTO PRACTICE (PRACTICEID,PRACTICEDESCRIPTION,PRACTICEEMAILID) VALUES(1,'C'||'&'||'S',1862);
COMMIT;
