--------------------------------------------------------
--  DDL FOR SEQUENCE MAJORSWBUIDLSDESIGNCONTACTS_SEQ
--------------------------------------------------------

CREATE SEQUENCE "MAJORSWBUIDLSDESIGNCONTACTS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;

--------------------------------------------------------
--  DDL for Table MAJORSWBUIDLSDESIGNCONTACTS
--------------------------------------------------------

  CREATE TABLE "MAJORSWBUILDSDESIGNCONTACTS" 
   (	
    "MAJORSWBUIDLSDESIGNCONTACTID" NUMBER(19,0) DEFAULT "MAJORSWBUIDLSDESIGNCONTACTS_SEQ"."NEXTVAL",
	"DESIGNCONTACTID" NUMBER(10,0),
	"MAJORSOFTWAREBUILDSID" NUMBER(19,0),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;

--------------------------------------------------------
--  DDL for Index PK_MAJORSWBUIDLSDESIGNCONTACTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_MAJORSWBUIDLSDESIGNCONTACTS" ON "MAJORSWBUILDSDESIGNCONTACTS" ("MAJORSWBUIDLSDESIGNCONTACTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table MAJORSWBUIDLSDESIGNCONTACTS
--------------------------------------------------------

  ALTER TABLE "MAJORSWBUILDSDESIGNCONTACTS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "MAJORSWBUILDSDESIGNCONTACTS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "MAJORSWBUILDSDESIGNCONTACTS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "MAJORSWBUILDSDESIGNCONTACTS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "MAJORSWBUILDSDESIGNCONTACTS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "MAJORSWBUILDSDESIGNCONTACTS" MODIFY ("DESIGNCONTACTID" NOT NULL ENABLE);
  ALTER TABLE "MAJORSWBUILDSDESIGNCONTACTS" MODIFY ("MAJORSOFTWAREBUILDSID" NOT NULL ENABLE);
  ALTER TABLE "MAJORSWBUILDSDESIGNCONTACTS" ADD CONSTRAINT "PK_MAJORSWBUIDLSDESIGNCONTACTS" PRIMARY KEY ("MAJORSWBUIDLSDESIGNCONTACTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAJORSWBUIDLSDESIGNCONTACTS
--------------------------------------------------------

ALTER TABLE "MAJORSWBUILDSDESIGNCONTACTS" ADD CONSTRAINT "FK_MAJORSWBUIDLSDESIGNCONTACTS_ORGANISATION_DESIGNCONTACTID" FOREIGN KEY ("DESIGNCONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "MAJORSWBUILDSDESIGNCONTACTS" ADD CONSTRAINT "FK_MAJORSWBUIDLSDESIGNCONTACTS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "MAJORSWBUILDSDESIGNCONTACTS" ADD CONSTRAINT "FK_MAJORSWBUIDLSDESIGNCONTACTS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "MAJORSWBUILDSDESIGNCONTACTS" ADD CONSTRAINT "FK_MAJORSWBUIDLSDESIGNCONTACTS_MAJORSOFTWAREBUILDS_MAJORSOFTWAREBUILDSID" FOREIGN KEY ("MAJORSOFTWAREBUILDSID") REFERENCES "MAJORSOFTWAREBUILDS" ("MAJORSOFTWAREBUILDSID") ENABLE;
COMMIT;