
---TRUNCATE DATA FOR ADDING EXACT JOINS FOR BUILDCONSTRUCTIONS
TRUNCATE TABLE MajorHWDesignContact_MIGTEMP;



--INSERT  FOR MIG TABLE  HARDWAREDESIGNCONTANCT

INSERT INTO MajorHWDesignContact_MIGTEMP (Systemtypeid,MajorHWBUILDID,DesignContact,ASPNETUSERID,VerticalResponsible)
Select Distinct st.SystemTypeId, MH.MAJORHARDWAREID, USR.EMAIL as Contact_ID, USR.ID, V.VerticalResponsible
from SystemTypes st JOIN SystemTypesSUBDomainSPOC STSDS ON st.SystemTypeId = STSDS.SystemTypeId
JOIN SYSTEMTYPESMAJORHARDWAREBUILDS HW ON st.SystemTypeId = HW.SystemTypeId 
JOIN MAJORHARDWAREBUILDS MH ON MH.MAJORHARDWAREID = HW.MAJORHARDWAREID
JOIN SubDomainSPOCS SDS ON SDS.SubDomainSPOCID = STSDS.SubDomainSPOCID
JOIN ASPNETUSERS USR ON upper(regexp_replace(USR.email,' ','')) = upper(regexp_replace(SDS.SubDomainSPOC,' ',''))
JOIN ASPNETUSERROLES UR on USR.ID = UR.USERID
JOIN VerticalResponsibles V ON v.VerticalResponsibleid = ST.VerticalResponsibleid
JOIN BUILDCONSTRUCTIONS BC ON BC.BUILDCONSTRUCTIONID = MH.BUILDCONSTRUCTIONID  WHERE BC.BUILDCONSTRUCTION NOT IN  ('BLUEPRINT NFVI', 'OTHER NFVI', 'BLUEPRINT NFCI', 'OTHER NFCI', 'VIRTUALISED'); 
COMMIT;
--Validation Script
Select SystemTypeId from SystemTypes where SystemTypeId not in (Select SystemTypeid from MajorHWDesignContact_MIGTEMP);



---PREVIOUSLY EXISTING TABLE DOESNOT HAVE A PRIMARYKEY COLUMN THAT WHY WE ADDED DROP AND INSERT AGAIN
DROP TABLE lcmengineeringsubdomainspoc_MIGTEMP;
DROP TABLE lcmengineeringEDUspoc_MIGTEMP;
DROP TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_MIGTEMP;
DROP TABLE NETWORKELEMENTASPLANNEDEDUSPOC_MIGTEMP;
COMMIT;


--DDL FOR MIG TABLE lcmengineeringsubdomainspoc
CREATE TABLE lcmengineeringsubdomainspoc_MIGTEMP(LCMENGINEERINGSUBDOMAINSPOCID NUMBER(19),LCMENGINEERINGID NUMBER(19),OPCOID  NUMBER(5), DESIGNCOMPONENTID  NUMBER(19), SubDomainSPOC NVARCHAR2(100),ASPNETUSERID NUMBER(19));

--INSERT QUERY FOR MIG TABLE lcmengineeringsubdomainspoc

INSERT INTO lcmengineeringsubdomainspoc_MIGTEMP (LCMENGINEERINGSUBDOMAINSPOCID,LCMENGINEERINGID,OPCOID,DESIGNCOMPONENTID,SubDomainSPOC,ASPNETUSERID)
Select lcmsds.LCMENGINEERINGSUBDOMAINSPOCID,LCM.LCMENGINEERINGID, LCM.OPCOID,LCM.DesignComponentID,USR.EMAIL as SubDomainSPOC, USR.ID as SubDomainSPOCID
FROM LCMENGINEERING LCM JOIN lcmengineeringsubdomainspoc lcmsds ON LCM.LCMENGINEERINGID = lcmsds.LCMENGEENERINGID
JOIN DesignComponents DC ON LCM.DESIGNCOMPONENTID = DC.DESIGNCOMPONENTID
JOIN SystemTypes ST ON ST.SYSTEMTYPEID = DC.SYSTEMTYPEID
JOIN SubDomainSPOCS SDS on SDS.SUBDOMAINSPOCID = lcmsds.SUBDOMAINSPOCID
JOIN VERTICALRESPONSIBLES v on v.VerticalResponsibleid = ST.VerticalResponsibleid
JOIN SubDomainResponsibles SDR on SDR.SUBDOMAINRESPONSIBLEID = ST.SUBDOMAINRESPONSIBLEID
JOIN ASPNETUSERS USR ON upper(regexp_replace(USR.email,' ','')) = upper(regexp_replace(SDS.SubDomainSPOC,' ',''));
COMMIT;

--Validation Script
Select LCMENGINEERINGID from LCMENGINEERING where LCMENGINEERINGID not in (Select LCMENGINEERINGID from lcmengineeringsubdomainspoc_MIGTEMP);
Select * from lcmengineeringsubdomainspoc_MIGTEMP where ASPNETUSERID IS NULL;

--DDL FOR MIG TABLE lcmengineeringeduspoc
CREATE TABLE lcmengineeringEDUspoc_MIGTEMP(LCMENGINEERINGEDUSPOCID NUMBER(19),LCMENGINEERINGID NUMBER(19),OPCOID  NUMBER(5), DESIGNCOMPONENTID NUMBER(19),EDUSPOC NVARCHAR2(100),ASPNETUSERID NUMBER(19),VerticalResponsible NVARCHAR2(50),VerticalResponsibleid NUMBER(19), SubDomainResponsible NVARCHAR2(50), SubDomainResponsibleID NUMBER(19));

--INSERT FOR MIG TABLE lcmengineeringeduspoc

INSERT INTO lcmengineeringEDUspoc_MIGTEMP (LCMENGINEERINGEDUSPOCID,LCMENGINEERINGID,OPCOID,DESIGNCOMPONENTID,EDUSPOC,ASPNETUSERID,VerticalResponsible,VerticalResponsibleid,SubDomainResponsible,SubDomainResponsibleID)
Select LCMSDS.LCMENGINEERINGEDUSPOCID,LCM.LCMENGINEERINGID, LCM.OPCOID,LCM.DesignComponentID,USR.EMAIL as EDUSPOC, USR.ID,v.VerticalResponsible,ST.VerticalResponsibleid, SDR.SubDomainResponsible, ST.SUBDOMAINRESPONSIBLEID
FROM LCMENGINEERING LCM JOIN LCMENGINEERINGEDUSPOC lcmsds ON LCM.LCMENGINEERINGID = lcmsds.LCMENGEENERINGID
JOIN DesignComponents DC ON LCM.DESIGNCOMPONENTID = DC.DESIGNCOMPONENTID
JOIN SystemTypes ST ON ST.SYSTEMTYPEID = DC.SYSTEMTYPEID
JOIN SubDomainSPOCS SDS on SDS.SUBDOMAINSPOCID = lcmsds.SUBDOMAINSPOCID
JOIN VERTICALRESPONSIBLES v on v.VerticalResponsibleid = ST.VerticalResponsibleid
JOIN SubDomainResponsibles SDR on SDR.SUBDOMAINRESPONSIBLEID = ST.SUBDOMAINRESPONSIBLEID
JOIN ASPNETUSERS USR ON upper(regexp_replace(USR.email,' ','')) = upper(regexp_replace(SDS.SubDomainSPOC,' ',''));
COMMIT;

--Validation Script
Select LCMENGINEERINGID from LCMENGINEERING where LCMENGINEERINGID not in (Select LCMENGINEERINGID from lcmengineeringsubdomainspoc_MIGTEMP); 
Select LCMENGINEERINGID FROM LCMENGINEERING WHERE LCMENGINEERINGID NOT IN (Select LCMENGINEERINGID FROM lcmengineeringEDUspoc_MIGTEMP);
Select LCMENGINEERINGID, ASPNETUSERID, EDUSPOC FROM lcmengineeringEDUspoc_MIGTEMP WHERE ASPNETUSERID IS NULL;


--DDL FOR MIG NETWORKELEMENTASPLANNEDSUBDOMAINSPOC
CREATE TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_MIGTEMP(NTKELEMENTASPLNSUBDOMAINSPOCID NUMBER(19),NETWORKELEMENTASPLANNEDID NUMBER(19),OPCOID  NUMBER(5),DESIGNCOMPONENTID NUMBER(19),SUBDOMAINSPOC NVARCHAR2(100),ASPNETUSERID NUMBER(19),VerticalResponsible NVARCHAR2(50),VerticalResponsibleid NUMBER(19), SubDomainResponsible NVARCHAR2(50), SubDomainResponsibleID NUMBER(19));

--INSERT FOR MIG NETWORKELEMENTASPLANNEDSUBDOMAINSPOC

INSERT INTO NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_MIGTEMP(NTKELEMENTASPLNSUBDOMAINSPOCID,NETWORKELEMENTASPLANNEDID,OPCOID,DESIGNCOMPONENTID,SUBDOMAINSPOC,ASPNETUSERID,VerticalResponsible,VerticalResponsibleid,SubDomainResponsible,SubDomainResponsibleID)
Select assetsds.NTKELEMENTASPLNSUBDOMAINSPOCID,asset.NETWORKELEMENTASPLANNEDID, asset.OPCOID,asset.DesignComponentID,USR.EMAIL as SubDomainSPOC, USR.ID, v.VerticalResponsible, ST.VerticalResponsibleid, SDR.SubDomainResponsible, ST.SUBDOMAINRESPONSIBLEID
FROM NETWORKELEMENTSASPLANNED asset JOIN NETWORKELEMENTASPLANNEDSUBDOMAINSPOC assetsds ON asset.NETWORKELEMENTASPLANNEDID = assetsds.NETWORKELEMENTASPLANNEDID
JOIN DesignComponents DC ON asset.DESIGNCOMPONENTID = DC.DESIGNCOMPONENTID
JOIN SystemTypes ST ON ST.SYSTEMTYPEID = DC.SYSTEMTYPEID
JOIN SubDomainSPOCS SDS on SDS.SUBDOMAINSPOCID = assetsds.SUBDOMAINSPOCID
JOIN VERTICALRESPONSIBLES v on v.VerticalResponsibleid = ST.VerticalResponsibleid
JOIN SubDomainResponsibles SDR on SDR.SUBDOMAINRESPONSIBLEID = ST.SUBDOMAINRESPONSIBLEID
JOIN ASPNETUSERS USR ON upper(regexp_replace(USR.email,' ','')) = upper(regexp_replace(SDS.SubDomainSPOC,' ',''));
COMMIT;

--Validation Script
Select NETWORKELEMENTASPLANNEDID from NETWORKELEMENTSASPLANNED where NETWORKELEMENTASPLANNEDID not in (Select NETWORKELEMENTASPLANNEDID from NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_MIGTEMP); 


--DDL FOR MIG NETWORKELEMENTASPLANNEDEDUSPOC
CREATE TABLE NETWORKELEMENTASPLANNEDEDUSPOC_MIGTEMP(NTKELEMENTASPLNEDUSPOCID NUMBER(19),NETWORKELEMENTASPLANNEDID NUMBER(19),OPCOID  NUMBER(5),DESIGNCOMPONENTID NUMBER(19),SUBDOMAINSPOC NVARCHAR2(100),ASPNETUSERID NUMBER(19),VerticalResponsible NVARCHAR2(50),VerticalResponsibleid NUMBER(19), SubDomainResponsible NVARCHAR2(50), SubDomainResponsibleID NUMBER(19));

--INSERT FOR MIG NETWORKELEMENTASPLANNEDSUBDOMAINSPOC

INSERT INTO NETWORKELEMENTASPLANNEDEDUSPOC_MIGTEMP(NTKELEMENTASPLNEDUSPOCID,NETWORKELEMENTASPLANNEDID,OPCOID,DESIGNCOMPONENTID,SUBDOMAINSPOC,ASPNETUSERID,VerticalResponsible,VerticalResponsibleid,SubDomainResponsible,SubDomainResponsibleID)
Select assetsds.NTKELEMENTASPLNEDUSPOCID,asset.NETWORKELEMENTASPLANNEDID, asset.OPCOID,asset.DesignComponentID,USR.EMAIL as SubDomainSPOC, USR.ID, v.VerticalResponsible, ST.VerticalResponsibleid, SDR.SubDomainResponsible, ST.SUBDOMAINRESPONSIBLEID
FROM NETWORKELEMENTSASPLANNED asset 
JOIN NETWORKELEMENTASPLANNEDEDUSPOC assetsds ON asset.NETWORKELEMENTASPLANNEDID = assetsds.NETWORKELEMENTASPLANNEDID
JOIN DesignComponents DC ON asset.DESIGNCOMPONENTID = DC.DESIGNCOMPONENTID
JOIN SystemTypes ST ON ST.SYSTEMTYPEID = DC.SYSTEMTYPEID
JOIN SubDomainSPOCS SDS on SDS.SUBDOMAINSPOCID = assetsds.SUBDOMAINSPOCID
JOIN VERTICALRESPONSIBLES v on v.VerticalResponsibleid = ST.VerticalResponsibleid
JOIN SubDomainResponsibles SDR on SDR.SUBDOMAINRESPONSIBLEID = ST.SUBDOMAINRESPONSIBLEID
JOIN ASPNETUSERS USR ON upper(regexp_replace(USR.email,' ','')) = upper(regexp_replace(SDS.SubDomainSPOC,' ','')); 
COMMIT;
--Validation Script
Select NETWORKELEMENTASPLANNEDID from NETWORKELEMENTSASPLANNED where NETWORKELEMENTASPLANNEDID not in (Select NETWORKELEMENTASPLANNEDID from NETWORKELEMENTASPLANNEDEDUSPOC_MIGTEMP); 



---UPDATE FOR NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_MIGTEMP	
		
		MERGE INTO NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_MIGTEMP TGT USING
(SELECT
            lsp.NTKELEMENTASPLNSUBDOMAINSPOCID,UR.ID
        FROM
                 NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_MIGTEMP lsp
            JOIN subdomainspocs sp ON upper(regexp_replace(lsp.SubDomainSPOC,' ','')) = upper(regexp_replace(sp.SubDomainSPOC,' ',''))
            JOIN (SELECT * FROM aspnetusers where id not in
(select id from (SELECT id ,EMAIL,ROW_NUMBER()OVER(PARTITION BY upper(regexp_replace(email,' ','')) ORDER BY ID ASC) rt
FROM aspnetusers) where rt ^=1))    ur ON upper(regexp_replace(sp.SUBDOMAINSPOC,' ','')) = upper(regexp_replace(ur.email,' ',''))
         ) SRC ON (TGT.NTKELEMENTASPLNSUBDOMAINSPOCID = SRC.NTKELEMENTASPLNSUBDOMAINSPOCID)
         WHEN MATCHED THEN UPDATE SET TGT.ASPNETUSERID = SRC.ID;
COMMIT;

--VALIDATION
SELECT * FROM NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_MIGTEMP where ASPNETUSERID is null;


---UPDATE FOR NETWORKELEMENTASPLANNEDEDUSPOC_MIGTEMP	
		MERGE INTO NETWORKELEMENTASPLANNEDEDUSPOC_MIGTEMP TGT USING
(SELECT
            lsp.NTKELEMENTASPLNEDUSPOCID,UR.ID
        FROM
                 NETWORKELEMENTASPLANNEDEDUSPOC_MIGTEMP lsp
            JOIN subdomainspocs sp ON upper(regexp_replace(lsp.SubDomainSPOC,' ','')) = upper(regexp_replace(sp.SubDomainSPOC,' ',''))
            JOIN (SELECT * FROM aspnetusers where id not in
(select id from (SELECT id ,EMAIL,ROW_NUMBER()OVER(PARTITION BY upper(regexp_replace(email,' ','')) ORDER BY ID ASC) rt
FROM aspnetusers) where rt ^=1))    ur ON upper(regexp_replace(sp.SUBDOMAINSPOC,' ','')) = upper(regexp_replace(ur.email,' ',''))
         ) SRC ON (TGT.NTKELEMENTASPLNEDUSPOCID = SRC.NTKELEMENTASPLNEDUSPOCID)
         WHEN MATCHED THEN UPDATE SET TGT.ASPNETUSERID = SRC.ID;
		 
COMMIT;

--VALIDATION
SELECT * FROM NETWORKELEMENTASPLANNEDEDUSPOC_MIGTEMP where ASPNETUSERID is null;

