
--INSERT FOR SOFTWAREDESIGN ONE TIME POPULATION
INSERT INTO MAJORSWBUILDSDESIGNCONTACTS (DESIGNCONTACTID, MAJORSOFTWAREBUILDSID,CREATIONUSER,MODIFICATIONUSER)  SELECT  ASPNETUSERID ,MajorSWBUILDID ,1 ,1  FROM  MajorSWDesignContact_MIGTEMP ; 
COMMIT;


--INSERT FOR HARDWAREDESIGN ONE TIME POPULATION
INSERT INTO MAJORHWBUILDSDESIGNCONTACTS (DESIGNCONTACTID, MAJORHARDWAREBUILDSID,CREATIONUSER,MODIFICATIONUSER)  SELECT  ASPNETUSERID ,MAJORHARDWAREID ,1 ,1  FROM  MajorHWDesignContact_MIGTEMP ; 
COMMIT;