
---ALTER SCRIPT FOR LCMENGINEERING EDUSPOC 
ALTER TABLE LCMENGINEERINGEDUSPOC ADD DESIGNCONTACTID NUMBER(10,0);
ALTER TABLE "LCMENGINEERINGEDUSPOC" ADD CONSTRAINT "FK_LCMENGINEERINGEDUSPOC_ASPNETUSERS_DESIGNCONTACTID" FOREIGN KEY ("DESIGNCONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;


---ALTER SCRIPT FOR LCMENGINEERING SUBDOMAINPOC
ALTER TABLE LCMENGINEERINGSUBDOMAINSPOC ADD DESIGNCONTACTID NUMBER(10,0);
ALTER TABLE "LCMENGINEERINGSUBDOMAINSPOC" ADD CONSTRAINT "FK_LCMENGINEERINGSUBDOMAINSPOC_ASPNETUSERS_DESIGNCONTACTID" FOREIGN KEY ("DESIGNCONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;

COMMIT;


-- AlTER SCRIPT FOR NETWORKELEMENTASPLANNED------

ALTER TABLE NETWORKELEMENTASPLANNEDEDUSPOC ADD DESIGNCONTACTID NUMBER(10,0);
ALTER TABLE "NETWORKELEMENTASPLANNEDEDUSPOC" ADD CONSTRAINT "FK_NETWORKELEMENTASPLANNEDEDUSPOC_ASPNETUSERS_DESIGNCONTACTID" FOREIGN KEY ("DESIGNCONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;

ALTER TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC ADD DESIGNCONTACTID NUMBER(10,0);
ALTER TABLE "NETWORKELEMENTASPLANNEDSUBDOMAINSPOC" ADD CONSTRAINT "FK_NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_ASPNETUSERS_DESIGNCONTACTID" FOREIGN KEY ("DESIGNCONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;

COMMIT;


--ALTER SCRIPT FOR ALL EDU AND SUBDOMAINSPOCS CHANGE TO NULLABLE COLUMN
ALTER TABLE LCMENGINEERINGSUBDOMAINSPOC MODIFY SUBDOMAINSPOCID  NULL;
ALTER TABLE LCMENGINEERINGEDUSPOC MODIFY SUBDOMAINSPOCID  NULL;
ALTER TABLE NETWORKELEMENTASPLANNEDEDUSPOC MODIFY SUBDOMAINSPOCID  NULL;
ALTER TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC MODIFY SUBDOMAINSPOCID  NULL;
COMMIT; 

-- AlTER SCRIPT FOR ALL EDU AND SUBDOMAINSPOCS -----------


ALTER TABLE LCMENGINEERINGEDUSPOC DROP CONSTRAINT "FK_LCMENGINEERINGEDUSPOC_SUBDOMAINSPOCS_SUBDOMAINSPOCID";
ALTER TABLE LCMENGINEERINGSUBDOMAINSPOC DROP CONSTRAINT "FK_LCMENGINEERINGSUBDOMAINSPOC_SUBDOMAINSPOCS_SUBDOMAINSPOCID";
ALTER TABLE NETWORKELEMENTASPLANNEDEDUSPOC DROP CONSTRAINT "FK_NETWORKELEMENTASPLANNEDEDUSPOC_SUBDOMAINSPOCS_SUBDOMAINSPOCID";
ALTER TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC DROP CONSTRAINT "FK_NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_SUBDOMAINSPOCS_SUBDOMAINSPOCID";
COMMIT;

