

--ONE TIME POPULATION FOR DESIGN CONTACT ID FOR EDU AND SUBDOMAIN SPOC
UPDATE LCMENGINEERINGSUBDOMAINSPOC ULCM SET DESIGNCONTACTID = (SELECT  DISTINCT ASPNETUSERID FROM lcmengineeringsubdomainspoc_MIGTEMP M WHERE M.LCMENGINEERINGID = ULCM.LCMENGEENERINGID 
AND ULCM.LCMENGINEERINGSUBDOMAINSPOCID = M.LCMENGINEERINGSUBDOMAINSPOCID);
COMMIT;

UPDATE LCMENGINEERINGEDUSPOC ULCM SET DESIGNCONTACTID = ( SELECT  DISTINCT ASPNETUSERID FROM   LCMENGINEERINGEDUSPOC_MIGTEMP LSP WHERE ULCM.LCMENGINEERINGEDUSPOCID = LSP.LCMENGINEERINGEDUSPOCID 
AND ULCM.LCMENGEENERINGID = LSP.LCMENGINEERINGID );
COMMIT;


UPDATE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC ULCM SET DESIGNCONTACTID = ( SELECT  DISTINCT ASPNETUSERID FROM   NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_MIGTEMP LSP  WHERE ULCM.NTKELEMENTASPLNSUBDOMAINSPOCID = LSP.NTKELEMENTASPLNSUBDOMAINSPOCID AND ULCM.NETWORKELEMENTASPLANNEDID = LSP.NETWORKELEMENTASPLANNEDID );
COMMIT;


UPDATE NETWORKELEMENTASPLANNEDEDUSPOC ULCM SET DESIGNCONTACTID = ( SELECT  ASPNETUSERID FROM   NETWORKELEMENTASPLANNEDEDUSPOC_MIGTEMP LSP  WHERE ULCM.NTKELEMENTASPLNEDUSPOCID = LSP.NTKELEMENTASPLNEDUSPOCID AND ULCM.NETWORKELEMENTASPLANNEDID = LSP.NETWORKELEMENTASPLANNEDID );
COMMIT;

