----------------------------------------------
-- AlTER SCRIPT FOR DynamicReports ------
ALTER TABLE DYNAMICREPORTS MODIFY ISSCHEDULED NUMBER(1,0) DEFAULT 0; 
COMMIT;

update DYNAMICREPORTS set ISSCHEDULED = null ;
commit;

ALTER TABLE "SYSTEMTYPES" DROP CONSTRAINT "FK_SYSTEMTYPES_VERTICALRESPONSIBLES_VERTICALRESPONSIBLEID";
ALTER TABLE "SYSTEMTYPES" DROP CONSTRAINT "FK_SYSTEMTYPES_SUBDOMAINRESPONSIBLES_SUBDOMAINRESPONSIBLEID";
ALTER TABLE "SYSTEMTYPES" DROP COLUMN "VERTICALRESPONSIBLEID";
ALTER TABLE "SYSTEMTYPES" DROP COLUMN "SUBDOMAINRESPONSIBLEID";
ALTER TABLE "SYSTEMTYPES" DROP COLUMN "SUBDOMAINSPOC";
COMMIT;


