--------------------------------------------------------
--  DDL FOR SEQUENCE SOFTWAREBUILDCOMPATIBILITY_SEQ
--------------------------------------------------------
 
CREATE SEQUENCE "SOFTWAREBUILDCOMPATIBILITY_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;
 
  
 
--------------------------------------------------------
--  DDL FOR TABLE SOFTWAREBUILDCOMPATIBILITY
--------------------------------------------------------
 
CREATE TABLE "SOFTWAREBUILDCOMPATIBILITY" 
("SOFTWAREBUILDCOMPATIBILITYID" NUMBER(19,0) DEFAULT "SOFTWAREBUILDCOMPATIBILITY_SEQ"."NEXTVAL", 
"MAJORSOFTWAREBUILDID" NUMBER(19,0) NOT NULL,
"BUNDLEMAJORSOFTWAREBUILDID" NUMBER(19,0) NOT NULL, 
"BUNDLETYPE" NUMBER(5,0) NOT NULL,  
"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"DELETED" NUMBER(1,0) DEFAULT 0, 
"DELETIONDATE" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
 
--------------------------------------------------------
--  DDL FOR INDEX PK_SOFTWAREBUILDCOMPATIBILITY
--------------------------------------------------------
 
CREATE UNIQUE INDEX "PK_SOFTWAREBUILDCOMPATIBILITY" ON "SOFTWAREBUILDCOMPATIBILITY" ("SOFTWAREBUILDCOMPATIBILITYID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE SOFTWAREBUILDCOMPATIBILITY
--------------------------------------------------------
 
ALTER TABLE "SOFTWAREBUILDCOMPATIBILITY" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "SOFTWAREBUILDCOMPATIBILITY" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "SOFTWAREBUILDCOMPATIBILITY" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "SOFTWAREBUILDCOMPATIBILITY" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "SOFTWAREBUILDCOMPATIBILITY" ADD CONSTRAINT "PK_SOFTWAREBUILDCOMPATIBILITY" PRIMARY KEY ("SOFTWAREBUILDCOMPATIBILITYID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE SOFTWAREBUILDCOMPATIBILITY
--------------------------------------------------------
 
ALTER TABLE "SOFTWAREBUILDCOMPATIBILITY" ADD CONSTRAINT "FK_SOFTWAREBUILDCOMPATIBILITY_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "SOFTWAREBUILDCOMPATIBILITY" ADD CONSTRAINT "FK_SOFTWAREBUILDCOMPATIBILITY_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "SOFTWAREBUILDCOMPATIBILITY" ADD CONSTRAINT "FK_SOFTWAREBUILDCOMPATIBILITY_MAJORSOFTWAREBUILDS_MAJORSOFTWAREBUILDID" FOREIGN KEY ("MAJORSOFTWAREBUILDID") REFERENCES "MAJORSOFTWAREBUILDS" ("MAJORSOFTWAREBUILDSID") ENABLE;
ALTER TABLE "SOFTWAREBUILDCOMPATIBILITY" ADD CONSTRAINT "FK_SOFTWAREBUILDCOMPATIBILITY_MAJORSOFTWAREBUILDS_BUNDLEMAJORSOFTWAREBUILDID" FOREIGN KEY ("BUNDLEMAJORSOFTWAREBUILDID") REFERENCES "MAJORSOFTWAREBUILDS" ("MAJORSOFTWAREBUILDSID") ENABLE; 
COMMIT; 
