--------------------------------------------------------
--  DDL FOR SEQUENCE SEVERITY_SEQ
--------------------------------------------------------
 
CREATE SEQUENCE "SEVERITY_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;
 
 
 
--------------------------------------------------------
--  DDL FOR TABLE SEVERITY
--------------------------------------------------------

CREATE TABLE SEVERITY (
"SEVERITYID" NUMBER(10,0) DEFAULT "SEVERITY_SEQ"."NEXTVAL",
"SEVERITYDESCRIPTION" NVARCHAR2(30),
"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"DELETED" NUMBER(1,0) DEFAULT 0, 
"DELETIONDATE" TIMESTAMP (6)
)SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_SEVERITY
--------------------------------------------------------
 
CREATE UNIQUE INDEX "PK_SEVERITY" ON "SEVERITY" ("SEVERITYID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE SEVERITY
--------------------------------------------------------
 
ALTER TABLE "SEVERITY" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "SEVERITY" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "SEVERITY" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "SEVERITY" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "SEVERITY" ADD CONSTRAINT "PK_SEVERITY" PRIMARY KEY ("SEVERITYID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE SEVERITY
--------------------------------------------------------
 
ALTER TABLE "SEVERITY" ADD CONSTRAINT "FK_SEVERITY_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "SEVERITY" ADD CONSTRAINT "FK_SEVERITY_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
 
COMMIT;

--------------------------------------------------------
--  INSERT COMMAND FOR TABLE SEVERITY
--------------------------------------------------------
INSERT INTO SEVERITY (SEVERITYID,SEVERITYDESCRIPTION) VALUES (1,'Low');
INSERT INTO SEVERITY (SEVERITYID,SEVERITYDESCRIPTION) VALUES (2,'Moderate');
INSERT INTO SEVERITY (SEVERITYID,SEVERITYDESCRIPTION) VALUES (3,'High');
INSERT INTO SEVERITY (SEVERITYID,SEVERITYDESCRIPTION) VALUES (4,'Extreme');

COMMIT;
