--------------------------------------------------------
--  DDL FOR SEQUENCE PROBLEMSCATEGORY_SEQ
--------------------------------------------------------
 
CREATE SEQUENCE "PROBLEMCATEGORY_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;
 
 
 
--------------------------------------------------------
--  DDL FOR TABLE PROBLEMSCATEGORY
--------------------------------------------------------

CREATE TABLE PROBLEMCATEGORY (
"PROBLEMCATEGORYID" NUMBER(19,0) DEFAULT "PROBLEMCATEGORY_SEQ"."NEXTVAL",
"PROBLEMCATEGORYDESCRIPTION" NVARCHAR2(200),
"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"DELETED" NUMBER(1,0) DEFAULT 0, 
"DELETIONDATE" TIMESTAMP (6)
)SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_PROBLEMCATEGORY
--------------------------------------------------------
 
CREATE UNIQUE INDEX "PK_PROBLEMCATEGORY" ON "PROBLEMCATEGORY" ("PROBLEMCATEGORYID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE PROBLEMCATEGORY
--------------------------------------------------------
 
ALTER TABLE "PROBLEMCATEGORY" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "PROBLEMCATEGORY" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "PROBLEMCATEGORY" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "PROBLEMCATEGORY" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "PROBLEMCATEGORY" ADD CONSTRAINT "PK_PROBLEMCATEGORY" PRIMARY KEY ("PROBLEMCATEGORYID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE PROBLEMCATEGORY
--------------------------------------------------------
 
ALTER TABLE "PROBLEMCATEGORY" ADD CONSTRAINT "FK_PROBLEMCATEGORY_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "PROBLEMCATEGORY" ADD CONSTRAINT "FK_PROBLEMCATEGORY_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
 
COMMIT;