--------------------------------------------------------
--  DDL FOR SEQUENCE SYSTEMVERIFICATIONPROBLEMS_SEQ
--------------------------------------------------------
CREATE SEQUENCE "SYSTEMVERIFICATIONPROBLEMS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE SYSTEMVERIFICATIONPROBLEMS
--------------------------------------------------------
CREATE TABLE SYSTEMVERIFICATIONPROBLEMS (
"SYSTEMVERIFICATIONPROBLEMID" NUMBER(19,0) DEFAULT "SYSTEMVERIFICATIONPROBLEMS_SEQ"."NEXTVAL",
"PROBLEMID" NVARCHAR2(50),
"OPCOID" NUMBER(5,0),
"SYSTEMTYPEID" NUMBER(19,0),
"ENVIRONMENTID" NUMBER(5,0),
"SUBNETWORK" NVARCHAR2(200),
"DATEFOUND" TIMESTAMP(6),
"PROBLEMCATEGORYID" NUMBER(19,0),
"PROBLEMDESCRIPTION" NVARCHAR2(2000),
"VENDORCSR" NVARCHAR2(200),
"MAINTENANCEREFERENCE" NVARCHAR2(300),
"SEVERITY" NUMBER(10,0),
"STATUS" NVARCHAR2(300),
"MITIGATION" NVARCHAR2(2000),
"SOLUTIONDESCRIPTION" NVARCHAR2(2000),
"PATCHREFERENCE" NVARCHAR2(300),
"PRODUCTUPGRADEREFERENCE" NVARCHAR2(300),
"SUPPLEMENTAL" NVARCHAR2(2000),
"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"DELETED" NUMBER(1,0) DEFAULT 0, 
"DELETIONDATE" TIMESTAMP (6)
)SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_SYSTEMVERIFICATIONPROBLEMS
--------------------------------------------------------
 
CREATE UNIQUE INDEX "PK_SYSTEMVERIFICATIONPROBLEMS" ON "SYSTEMVERIFICATIONPROBLEMS" ("SYSTEMVERIFICATIONPROBLEMID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE SYSTEMVERIFICATIONPROBLEMS
--------------------------------------------------------
 
ALTER TABLE "SYSTEMVERIFICATIONPROBLEMS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "SYSTEMVERIFICATIONPROBLEMS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "SYSTEMVERIFICATIONPROBLEMS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "SYSTEMVERIFICATIONPROBLEMS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "SYSTEMVERIFICATIONPROBLEMS" ADD CONSTRAINT "PK_SYSTEMVERIFICATIONPROBLEMS" PRIMARY KEY ("SYSTEMVERIFICATIONPROBLEMID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE SYSTEMVERIFICATIONPROBLEMS
--------------------------------------------------------
ALTER TABLE "SYSTEMVERIFICATIONPROBLEMS" ADD CONSTRAINT "FK_SYSTEMVERIFICATIONPROBLEMS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "SYSTEMVERIFICATIONPROBLEMS" ADD CONSTRAINT "FK_SYSTEMVERIFICATIONPROBLEMS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "SYSTEMVERIFICATIONPROBLEMS" ADD CONSTRAINT "FK_SYSTEMVERIFICATIONPROBLEMS_OPCOS_OPCOID" FOREIGN KEY ("OPCOID") REFERENCES "OPCOS" ("OPCOID") ENABLE;
ALTER TABLE "SYSTEMVERIFICATIONPROBLEMS" ADD CONSTRAINT "FK_SYSTEMVERIFICATIONPROBLEMS_ENVIRONMENTS_ENVIRONMENTID" FOREIGN KEY ("ENVIRONMENTID") REFERENCES "ENVIRONMENTS" ("ENVIRONMENTID") ENABLE;
ALTER TABLE "SYSTEMVERIFICATIONPROBLEMS" ADD CONSTRAINT "FK_SYSTEMVERIFICATIONPROBLEMS_SYSTEMTYPES_SYSTEMTYPEID" FOREIGN KEY ("SYSTEMTYPEID") REFERENCES "SYSTEMTYPES" ("SYSTEMTYPEID") ENABLE;
ALTER TABLE "SYSTEMVERIFICATIONPROBLEMS" ADD CONSTRAINT "FK_SYSTEMVERIFICATIONPROBLEMS_PROBLEMCATEGORY_PROBLEMCATEGORYID" FOREIGN KEY ("PROBLEMCATEGORYID") REFERENCES "PROBLEMCATEGORY" ("PROBLEMCATEGORYID") ENABLE;
ALTER TABLE "SYSTEMVERIFICATIONPROBLEMS" ADD CONSTRAINT "FK_SYSTEMVERIFICATIONPROBLEMS_SEVERITY_SEVERITY" FOREIGN KEY ("SEVERITY") REFERENCES "SEVERITY" ("SEVERITYID") ENABLE;

COMMIT;


