CREATE SEQUENCE "FUNCTIONAREA_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL for Table FUNCTIONAREA
--------------------------------------------------------

  CREATE TABLE "FUNCTIONAREA" 
   (	"FUNCTIONAREAID" NUMBER(20,0) DEFAULT "FUNCTIONAREA_SEQ"."NEXTVAL",
	"FUNCTIONID" NUMBER(20,0), 
	"AREANAME" NVARCHAR2(50),
	"APPLICATIONNAME" NVARCHAR2(50), 
	"BORDERGATEWAYFUNCTIONID" NVARCHAR2(50), 
	"CALLRETENTIONTIMER" NVARCHAR2(50), 
	"CAPACITYFORPRIORITYCALLS" NVARCHAR2(50), 
	"DATETIMEOFFSET" NVARCHAR2(50), 
	"DIRECTMEDIAROUTING" NVARCHAR2(50), 
	"DNPREFIX" NVARCHAR2(60), 
	"ENABLEONDEMANDSCALING" NVARCHAR2(50), 
	"EVSSUPPORTEDINMRF" NVARCHAR2(50), 
	"FAILOVERDETECTIONTIMER" NVARCHAR2(50), 
	"ID" NVARCHAR2(50), 
	"LOCALDATETIME" NVARCHAR2(50), 
	"LOCATIONNAME" NVARCHAR2(50), 
	"LOGICALNAME" NVARCHAR2(50), 
	"MANAGEDELEMENTID" NVARCHAR2(50), 
	"MANAGEDELEMENTTYPE" NVARCHAR2(50), 
	"MANAGEDELEMENTTYPELIST" NVARCHAR2(50), 
	"MEDIAIPVERSION" NVARCHAR2(50), 
	"MEDIARESOURCEFUNCTIONID" NVARCHAR2(50), 
	"MMASID" NVARCHAR2(50), 
	"MTASFUNCTIONBLACKLISTTIME" NVARCHAR2(50), 
	"MTASFUNCTIONFULLDISKPERCENTAGE" NVARCHAR2(50), 
	"MTASFUNCTIONINVALIDADDRESS" NVARCHAR2(50), 
	"MTASFUNCTIONMAXSESSIONDURATION" NVARCHAR2(50), 
	"MTASFUNCTIONMCCMNC" NVARCHAR2(50), 
	"MTASFUNCTIONNETTRACEVERSION" NVARCHAR2(50), 
	"MTASFUNCTIONRESTART" NVARCHAR2(50), 
	"MTASFUNCTIONVERSION" NVARCHAR2(50), 
	"NETWORKMANAGEDELEMENTID" NVARCHAR2(50), 
	"NETYPE" NVARCHAR2(50), 
	"PLATFORMTYPE" NVARCHAR2(50), 
	"RELEASE" NVARCHAR2(50), 
	"SCALEINTHRESHOLD" NVARCHAR2(50), 
	"SCALEOUTTHRESHOLD" NVARCHAR2(50), 
	"SCALINGMONITORINTERVAL" NVARCHAR2(50), 
	"SHUTTINGDOWNTIMER" NVARCHAR2(50), 
	"SIGNALINGLOCALPORT" NVARCHAR2(50), 
	"SIGNALINGVLANID" NVARCHAR2(50), 
	"SITEID" NVARCHAR2(50), 
	"SITELOCATION" NVARCHAR2(50), 
	"SLAACINUSE" NVARCHAR2(50), 
	"SWVERSION" NVARCHAR2(50), 
	"SYSTEMFUNCTIONSID" NVARCHAR2(50), 
	"TIMEZONE" NVARCHAR2(50), 
	"TRANSCODINGRETENTION" NVARCHAR2(50), 
	"TRANSPORTID" NVARCHAR2(50), 
	"USERDEFINEDSTATE" NVARCHAR2(50), 
	"USERLABEL" NVARCHAR2(400), 
	"VENDORNAME" NVARCHAR2(50), 
	"SITE" NVARCHAR2(50),
	"SPDH" NVARCHAR2(50),
	"IPOAMID" NVARCHAR2(50),
	"SACMODE" NVARCHAR2(50),
	"MIMINFO" NVARCHAR2(50),
	"MBACMODE" NVARCHAR2(50),
	"CODINGLAW" NVARCHAR2(50),
	"DSCPAUDIO" NVARCHAR2(50),
	"JAVACAFID" NVARCHAR2(50),
	"IPSYSTEMID" NVARCHAR2(50),
	"TFOIPEMODE" NVARCHAR2(50),
	"DSCPMARKING" NVARCHAR2(50),
	"EQUIPMENTID" NVARCHAR2(50),
	"PRODUCTNAME" NVARCHAR2(50),
	"PRODUCTTYPE" NVARCHAR2(50),
	"IPBCPT1TIMER" NVARCHAR2(50),
	"MBACTHRESHOLD" NVARCHAR2(50),
	"DDBFUNCTIONID" NVARCHAR2(50),
	"DSCFUNCTIONID" NVARCHAR2(50),
	"IPWORKSROOTID" NVARCHAR2(50),
	"PRODUCTNUMBER" NVARCHAR2(50),
	"DSCPMULTIMEDIA" NVARCHAR2(50),
	"LASTHWPICHANGE" NVARCHAR2(50),
	"LASTUPPICHANGE" NVARCHAR2(50),
	"MRFCFUNCTIONID" NVARCHAR2(50),
	"MRFPFUNCTIONID" NVARCHAR2(50),
	"MSPROCESSINGID" NVARCHAR2(50),
	"RTCPONNBACTIVE" NVARCHAR2(50),
	"SWITCHFABRICID" NVARCHAR2(50),
	"SWMANAGEMENTID" NVARCHAR2(50),
	"SWSERVERURLLIST" NVARCHAR2(50),
	"PRODUCTREVISION" NVARCHAR2(50),
	"FEATURESTATEG722" NVARCHAR2(50),
	"ISLSUPERVISIONID" NVARCHAR2(50),
	"LICENSESTATEG722" NVARCHAR2(50),
	"LICENSESTATEIPV6" NVARCHAR2(50),
	"LICENSESTATEMRFC" NVARCHAR2(50),
	"MGWAPPLICATIONID" NVARCHAR2(50),
	"MTASFUNCTIONFQDN" NVARCHAR2(50),
	"DOCLIBUSERDEFINED" NVARCHAR2(50),
	"SIGNALLINGPROXYID" NVARCHAR2(50),
	"HEALTHCHECKRESULT" NVARCHAR2(50),
	"ACCESSSIGNALLINGID" NVARCHAR2(50),
	"LICENSECAPACITYBGF" NVARCHAR2(50),
	"LICENSESTATEBGFEVS" NVARCHAR2(50),
	"LICENSESTATEMRFEVS" NVARCHAR2(50),
	"LOGONSERVERADDRESS" NVARCHAR2(50),
	"TRANSPORTNETWORKID" NVARCHAR2(50),
	"LICENSECAPACITYMRFP" NVARCHAR2(50),
	"LICENSESTATEBGFATGW" NVARCHAR2(50),
	"LICENSESTATEBGFIPV6" NVARCHAR2(50),
	"LICENSESTATEBGFSRTP" NVARCHAR2(50),
	"LICENSESTATEHDAUDIO" NVARCHAR2(50),
	"LICENSESTATEMRFIPV6" NVARCHAR2(50),
	"MBACLICENSINGSTATUS" NVARCHAR2(50),
	"MBACWEIGHTINGFACTOR" NVARCHAR2(50),
	"SERSUPERVISIONTIMER" NVARCHAR2(50),
	"HEALTHCHECKSCHEDULE" NVARCHAR2(50),
	"FEATURESTATEBGFSMSRP" NVARCHAR2(50),
	"LICENSECAPACITYVIDEO" NVARCHAR2(50),
	"LICENSESTATEBGFSMSRP" NVARCHAR2(50),
	"MANAGEDELEMENTDATAID" NVARCHAR2(50),
	"POWERSAVEMODEENABLED" NVARCHAR2(50),
	"SPEECHACTIVITYFACTOR" NVARCHAR2(50),
	"DOCUMENTSERVERADDRESS" NVARCHAR2(50),
	"FEATURESTATEBGFWEBRTC" NVARCHAR2(50),
	"LICENSESTATEBGFWEBRTC" NVARCHAR2(50),
	"MTASFUNCTIONMMTASNAME" NVARCHAR2(50),
	"MTASFUNCTIONSCCASNAME" NVARCHAR2(50),
	"ETHERNETSWITCHFABRICID" NVARCHAR2(50),
	"INTERACTIVEMESSAGINGID" NVARCHAR2(50),
	"MBACCONGESTIONDSCPMODE" NVARCHAR2(50),
	"PIUGROUPESCALATIONTYPE" NVARCHAR2(50),
	"SACLOWERTHRESHOLDALARM" NVARCHAR2(50),
	"SCCLOWERTHRESHOLDALARM" NVARCHAR2(50),
	"G711PACKETIZATIONTIMENB" NVARCHAR2(50),
	"G729LOWERTHRESHOLDALARM" NVARCHAR2(50),
	"MBACCONGESTIONDSCPVALUE" NVARCHAR2(50),
	"MBACMEASUREMENTINTERVAL" NVARCHAR2(50),
	"SACHIGHERTHRESHOLDALARM" NVARCHAR2(50),
	"SCCHIGHERTHRESHOLDALARM" NVARCHAR2(50),
	"VOIPLOWERTHRESHOLDALARM" NVARCHAR2(50),
	"POLICYCONTROLFUNCTIONID" NVARCHAR2(50),
	"AMRWBLOWERTHRESHOLDALARM" NVARCHAR2(50),
	"AUTOCONFIGURATIONALLOWED" NVARCHAR2(50),
	"G729HIGHERTHRESHOLDALARM" NVARCHAR2(50),
	"VOIPHIGHERTHRESHOLDALARM" NVARCHAR2(50),
	"APPLICATIONCONFIGURATION" NVARCHAR2(50),
	"MTASFUNCTIONNWFOIWASNAME" NVARCHAR2(50),
	"MTASFUNCTIONNWPRIWASNAME" NVARCHAR2(50),
	"AMRWBHIGHERTHRESHOLDALARM" NVARCHAR2(50),
	"LICENSECAPACITYVOICETRANS" NVARCHAR2(50),
	"MINIMUMHDVOLUMECFREESPACE" NVARCHAR2(50),
	"FEATURESTATECONTENTSHARING" NVARCHAR2(50),
	"INTERMITTENTFAULTTHRESHOLD" NVARCHAR2(50),
	"LICENSESTATECONTENTSHARING" NVARCHAR2(50),
	"MAXBANDWIDTHFORIPTRANSPORT" NVARCHAR2(50),
	"FEATURESTATEDTMFSUPPRESSION" NVARCHAR2(50),
	"FEATURESTATEMSCPOOLPROXYGSM" NVARCHAR2(50),
	"LICENSECAPACITYHDVOICETRANS" NVARCHAR2(50),
	"LICENSESTATEBGFPRIORITYCALL" NVARCHAR2(50),
	"LICENSESTATEMRFPRIORITYCALL" NVARCHAR2(50),
	"FEATURESTATEVOICETRANSCODING" NVARCHAR2(50),
	"RTCPBEARERSUPERVISIONTIMERMB" NVARCHAR2(50),
	"RTCPBEARERSUPERVISIONTIMERNB" NVARCHAR2(50),
	"CAPPERCENTRESERVEDFORWPSCALLS" NVARCHAR2(50),
	"FEATURESTATEMSCPOOLPROXYWCDMA" NVARCHAR2(50),	
	"EXPLICITCONGESTIONNOTIFICATION" NVARCHAR2(50),
	"MBACLOSTPACKETSCALCULATIONMODE" NVARCHAR2(50),
	"RTCPBEARERSUPERVISIONTIMERAOIP" NVARCHAR2(50),
	"RTCPBEARERSUPERVISIONTIMERVOIP" NVARCHAR2(50),

	"LICENSECAPACITYAUDIOCONFERENCE" NVARCHAR2(50),
	"LICENSECAPACITYVIDEOCONFERENCE" NVARCHAR2(50),
	"LICENSECAPACITYHDVIDOCONFERNCE" NVARCHAR2(50), 
	"MTAS_VTPADMIN_STATE" NVARCHAR2(50),
	"MTAS_FULLDISKPERCENTAGE" NVARCHAR2(50),
	"MTAS_ADMINISTRATIVESTATE" NVARCHAR2(50),
	"MTAS_MAXSESSIONDURATION" NVARCHAR2(50),
	"MTAS_NOTFULLDISKPERCENTAGE" NVARCHAR2(50),
	"MTAS_MAXNUMOFSESIONSACTION" NVARCHAR2(50),
	"MTAS_MAXNUMOFSESSIONS" NVARCHAR2(50),
	"MTAS_MAXNUMSUBSCRIPTSESION" NVARCHAR2(50),
	"MTAS_SCALINGTERMINATWAITIME" NVARCHAR2(50),
	"MTAS_ADMIN_STATEAFTERRESTRT" NVARCHAR2(50),
		
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp)
    
		
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";
--------------------------------------------------------
--  DDL for Index FUNCTIONAREAIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNCTIONAREAIDX" ON "FUNCTIONAREA" ("FUNCTIONAREAID")
   PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";
--------------------------------------------------------
--  Constraints for Table FUNCTIONAREA
--------------------------------------------------------
  ALTER TABLE "FUNCTIONAREA" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "FUNCTIONAREA" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "FUNCTIONAREA" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "FUNCTIONAREA" ADD CONSTRAINT "FUNCTIONAREA_PK" PRIMARY KEY ("FUNCTIONAREAID")
   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;
  
--------------------------------------------------------
--  Ref Constraints for Table FUNCTIONAREA
--------------------------------------------------------

  ALTER TABLE "FUNCTIONAREA" ADD CONSTRAINT "FK_FUNCTION" FOREIGN KEY ("FUNCTIONID")
	  REFERENCES "FUNCTION" ("FUNCTIONID") ENABLE;
  
 ALTER TABLE "FUNCTIONAREA"
 MODIFY("FUNCTIONAREAID"  DEFAULT "FUNCTIONAREA_SEQ"."NEXTVAL");