CREATE SEQUENCE "SUBFUNCTIONAREA2_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL FOR TABLE SUBFUNCTIONAREA2
--------------------------------------------------------

  CREATE TABLE "SUBFUNCTIONAREA2"
   (	"SUBFUNCTIONAREA2ID" NUMBER(20,0) DEFAULT "SUBFUNCTIONAREA2_SEQ"."NEXTVAL",
	"SUBFUNCTIONID" NUMBER(20,0), 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp),  	 	
	"TSACK" NVARCHAR2(50),
	"MAXINCOMINGSTREAM" NVARCHAR2(50),
	"HEARTBEATMAXBURST" NVARCHAR2(50),
	"POTENTIALLYFAILEDMAXRTX" NVARCHAR2(50),
	"MBUFFER" NVARCHAR2(50),
	"NPERCENTAGE" NVARCHAR2(50),
	"BUNDLINGTIMER" NVARCHAR2(50),
	"MINIMUMRTO" NVARCHAR2(50),
	"ALLOWEDINCREMENTCOOKIELIFE" NVARCHAR2(50),
	"MAXSHUTDOWNRTRATT" NVARCHAR2(50),
	"VALIDCOOKIELIFE" NVARCHAR2(50),
	"INITIALADRECWIN" NVARCHAR2(50),
	"MAXOUTGOINGSTREAM" NVARCHAR2(50),
	"NUMBEROFASSOCIATIONS" NVARCHAR2(50),
	"INITIALRTO" NVARCHAR2(50),
	"PATHSELECTION" NVARCHAR2(50),
	"BUNDLINGACTIVATED" NVARCHAR2(50),
	"SWITCHBACKMINTHRESHOLD" NVARCHAR2(50),
	"SWITCHBACKMAXTHRESHOLD" NVARCHAR2(50),
	"SCTPID" NVARCHAR2(50),
	"KEYCHANGEPERIOD" NVARCHAR2(50),
	"RTOALPHAINDEX" NVARCHAR2(50),
	"MAXUSERDATASIZE" NVARCHAR2(50),
	"HEARTBEATSTATUS" NVARCHAR2(50),
	"RTOBETAINDEX" NVARCHAR2(50),
	"MAXINITIALRTRATT" NVARCHAR2(50),
	"HEARTBEATPATHPROBINGINTERVAL" NVARCHAR2(50),
	"SCTPASSOCDELETETIMEOUT" NVARCHAR2(50),
	"PRIORITYDATADSCPSERVICE" NVARCHAR2(50),
	"INTERVALOOBPKTS" NVARCHAR2(50),
	"ASSOCIATIONMAXRTX" NVARCHAR2(50),
	"SWITCHBACKMODE" NVARCHAR2(50),
	"MAXIMUMRTO" NVARCHAR2(50),
	"NTHRESHOLD" NVARCHAR2(50),
	"PVALUELIMIT" NVARCHAR2(50),
	"DMAXLIMIT" NVARCHAR2(50),
	"CONSECUTIVEIDENTICALRESULTS" NVARCHAR2(50),
	"UPSENABLED" NVARCHAR2(50),
	"USERPLANESUPERVISIONID" NVARCHAR2(50),
	"CORBASECURITYACTIVE" NVARCHAR2(50),
	"CRLEARLYUPDATEINTERVAL" NVARCHAR2(50),
	"TARGETMONITORPORTACTIVE" NVARCHAR2(50),
	"LOCALAADBINSTALLATIONFAILURE" NVARCHAR2(50),
	"DEBUGPORTSACTIVE" NVARCHAR2(50),
	"WEBSERVER" NVARCHAR2(50),
	"TARGETMONITORPORT" NVARCHAR2(50),
	"LOGINDELAY" NVARCHAR2(50),
	"OPERATIONALSECURITYLEVEL" NVARCHAR2(50),
	"LOCALAUTHENTICATIONFILEVERSION" NVARCHAR2(50),
	"NOOFFAILEDLOGINATTEMPTS" NVARCHAR2(50),
	"TRUSTEDCERTIFICATEINSTALLFAIL" NVARCHAR2(50),
	"CERTEXPIRWARNTIME" NVARCHAR2(50),
	"REQUESTEDSECURITYLEVEL" NVARCHAR2(50),
	"FAILEDLOGINATTEMPTPERIOD" NVARCHAR2(50),
	"AUTHORIZATIONCACHETIMEOUT" NVARCHAR2(50),
	"USERLOCKOUTPERIOD" NVARCHAR2(50),
	"FILETRANSFERCLIENTMODE" NVARCHAR2(50),
	"LOCALAUTHORIZATIONFILEVERSION" NVARCHAR2(50),
	"USERAUTHENTICATIONANDAUTH" NVARCHAR2(50),
	"AUTOUPDATECERTENROLLMENTSERVER" NVARCHAR2(50),
	"TELNETANDFTPSERVERSACTIVE" NVARCHAR2(50),
	"INSTALLEDTRUSTEDCERTIFICATES" NVARCHAR2(50),
	"AASERVERIPADDRESSLIST" NVARCHAR2(50),
	"SECURITYID" NVARCHAR2(50),
	"CERTREVSTATUSCHECK" NVARCHAR2(50),
	"PERFORMANCEDATAVOLUME" NVARCHAR2(50),
	"MAXNOOFCOUNTERS" NVARCHAR2(50),
	"WARNINGALARMLIMITPERCENT" NVARCHAR2(50),
	"MINORALARMCEASINGDELTA" NVARCHAR2(50),
	"TRANSACTIONTIMEOUT" NVARCHAR2(50),
	"MAXNOOFPMFILES" NVARCHAR2(50),
	"WARNINGALARMCEASINGDELTA" NVARCHAR2(50),
	"PMSERVICEID" NVARCHAR2(50),
	"MAXNOOFMONITORS" NVARCHAR2(50),
	"AGENTIPADDRESS" NVARCHAR2(50),
	"SNMPID" NVARCHAR2(50),
	"AGENTPORT" NVARCHAR2(50),
	"MINIMUMSNMPVERSION" NVARCHAR2(50),
	"LOGSERVICEID" NVARCHAR2(50),
	"FILEFETCHERID" NVARCHAR2(50),
	"HTTPGETSUPERVISIONTIMER" NVARCHAR2(50),
	"PERFORMANCESUPERVISIONID" NVARCHAR2(50),
	"STATUS" NVARCHAR2(50),
	"NUMBEROFCOUNTERINSTANCES" NVARCHAR2(50),
	"PERFORMANCEINDICATORID" NVARCHAR2(50),
	"SCHEDULEINFO" NVARCHAR2(50),
	"EXECUTIONTYPE" NVARCHAR2(50),
	"SYSTEMCHECKID" NVARCHAR2(50),
	"CHECKRESULT" NVARCHAR2(50),
	"GPSTOUTCLEAPSECONDSCHANGEDATE" NVARCHAR2(50),
	"GPSTOUTCLEAPSECONDS" NVARCHAR2(50),
	"DAYLIGHTSAVINGTIMEENDRULE" NVARCHAR2(50),
	"TIMESETTINGID" NVARCHAR2(50),
	"DAYLIGHTSAVINGTIMEON" NVARCHAR2(50),
	"TIMEOFFSET" NVARCHAR2(50),
	"DAYLIGHTSAVINGTIMEOFFSET" NVARCHAR2(50),
	"DAYLIGHTSAVINGTIMESTARTRULE" NVARCHAR2(50),
	"DCGSTATE" NVARCHAR2(50),
	"DATACOLLECTIONGENERATIONID" NVARCHAR2(50),
	"PUSHPMFUNCTIONID" NVARCHAR2(50),
	"INTEGRATIONUNLOCKSTATEINFO" NVARCHAR2(50),
	"LASTLICENSINGPICHANGE" NVARCHAR2(50),
	"LICENSINGID" NVARCHAR2(50),
	"EMERGENCYSTATEINFO" NVARCHAR2(50),
	"DS0BUNDLEMOREFA" NVARCHAR2(50),
	"DS0BUNDLEMOREFB" NVARCHAR2(50),
	"TDMCROSSCONNECTIONID" NVARCHAR2(50),
	"CHID" NVARCHAR2(50),
	"CHRPUMOREF" NVARCHAR2(50),
	"BGFSMSRPSUPPORTEDTLSVERSIONS" NVARCHAR2(50),
	"USERPLANESECURITYID" NVARCHAR2(50),
	"NODECERTIFICATES" NVARCHAR2(50),
	"MESCRPUMOREF" NVARCHAR2(50),
	"MESCID" NVARCHAR2(50),
	"LOCALCONNSUPTHRESHOLD" NVARCHAR2(50),
	"IPCONNECTIVITYSUPERVISIONID" NVARCHAR2(50),
	"FEATURESTATEIPCONNSUP" NVARCHAR2(50),
	"REMOTEIPCONNCONSFAILURES" NVARCHAR2(50),
	"REMOTEIPCONNSUPACTIVE" NVARCHAR2(50),
	"LOCALIPCONNSUPACTIVE" NVARCHAR2(50),
	"REMOTESITESUPTRAFFICREDUCTION" NVARCHAR2(50),
	"REMOTESITETRAFFLEVACTIVE" NVARCHAR2(50),
	"LICENSESTATEIPCONNSUP" NVARCHAR2(50),
	"WEBSERVERID" NVARCHAR2(50),
	"NCLIID" NVARCHAR2(50)
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";
--------------------------------------------------------
--  DDL FOR INDEX SUBFUNCTIONAREAIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUBFUNCTIONAREA2IDX" ON "SUBFUNCTIONAREA2" ("SUBFUNCTIONAREA2ID")
   PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE SUBFUNCTIONAREA
--------------------------------------------------------
  ALTER TABLE "SUBFUNCTIONAREA2" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "SUBFUNCTIONAREA2" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "SUBFUNCTIONAREA2" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "SUBFUNCTIONAREA2" ADD CONSTRAINT "SUBFUNCTIONAREA2_PK" PRIMARY KEY ("SUBFUNCTIONAREA2ID")
   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE SUBFUNCTIONAREA
--------------------------------------------------------

   ALTER TABLE "SUBFUNCTIONAREA2" ADD CONSTRAINT "FK_SUBFUNCTION2" FOREIGN KEY ("SUBFUNCTIONID")
   REFERENCES "SUBFUNCTION" ("SUBFUNCTIONID") ENABLE;
   
 ALTER TABLE "SUBFUNCTIONAREA2"
 MODIFY("SUBFUNCTIONAREA2ID"  DEFAULT "SUBFUNCTIONAREA2_SEQ"."NEXTVAL");
