CREATE SEQUENCE "HARDWARECONFIGURATION_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL for Table HARDWARECONFIGURATION
--------------------------------------------------------

  CREATE TABLE "HARDWARECONFIGURATION" 
   (	"HARDWARECONFIGURATIONID" NUMBER(20,0) DEFAULT "HARDWARECONFIGURATION_SEQ"."NEXTVAL",
	"NETWORKELEMENTID" NUMBER(20,0), 
	"OPCO" NVARCHAR2(50),
	"OEM" NVARCHAR2(50),	
	"ELEMENTNAME" NVARCHAR2(50), 
	"HARDWARETYPE" NVARCHAR2(50), 
	"PRODUCTNAME" NVARCHAR2(50), 
	"PRODUCTNO" NVARCHAR2(50), 
	"PRODUCTREVISION" NVARCHAR2(50), 
	"SERIALNUMBER" NVARCHAR2(50), 
	"UNITLOCATION" NVARCHAR2(50), 
	"VENDOR" NVARCHAR2(50), 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp)    		
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";
--------------------------------------------------------
--  DDL for Index HARDWARECONFIGURATION_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "HARDWARECONFIGURATIONIDX" ON "HARDWARECONFIGURATION" ("HARDWARECONFIGURATIONID")
   PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";
--------------------------------------------------------
--  Constraints for Table HARDWARECONFIGURATION
--------------------------------------------------------
  ALTER TABLE "HARDWARECONFIGURATION" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "HARDWARECONFIGURATION" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "HARDWARECONFIGURATION" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "HARDWARECONFIGURATION" ADD CONSTRAINT "HARDWARECONFIGURATION_PK" PRIMARY KEY ("HARDWARECONFIGURATIONID")
   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HARDWARECONFIGURATION
--------------------------------------------------------

  ALTER TABLE "HARDWARECONFIGURATION" ADD CONSTRAINT "FK_NETWORKELEMENT3" FOREIGN KEY ("NETWORKELEMENTID")
	  REFERENCES "NETWORKELEMENT" ("NETWORKELEMENTID") ENABLE;
  
 ALTER TABLE "HARDWARECONFIGURATION"
 MODIFY("HARDWARECONFIGURATIONID"  DEFAULT "HARDWARECONFIGURATION_SEQ"."NEXTVAL");
