CREATE SEQUENCE "XML_PARSE_RUN_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL for Table XML_PARSE_RUN
--------------------------------------------------------

  CREATE TABLE "XMLPARSERUN" 
   (	"XMLPARSERUNID" NUMBER(20,0) DEFAULT "XML_PARSE_RUN_SEQ"."NEXTVAL",
	"FILENAME" NVARCHAR2(400), 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp)    		
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";
  --------------------------------------------------------
--  DDL for Index XMLPARSERUNIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "XMLPARSERUN_IDX" ON "XMLPARSERUN" ("XMLPARSERUNID")
   PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";
--------------------------------------------------------
--  Constraints for Table XMLPARSERUN
--------------------------------------------------------
  ALTER TABLE "XMLPARSERUN" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "XMLPARSERUN" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "XMLPARSERUN" ADD CONSTRAINT "XML_PARSE_RUN_PK" PRIMARY KEY ("XMLPARSERUNID")
   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table XMLPARSERUN
--------------------------------------------------------

 ALTER TABLE "XMLPARSERUN"
 MODIFY("XMLPARSERUNID"  DEFAULT "XML_PARSE_RUN_SEQ"."NEXTVAL");
