CREATE SEQUENCE "NODE_PARSE_HISTORY_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL for Table NODE_PARSE_HISTORY
--------------------------------------------------------

  CREATE TABLE "NODEPARSEHISTORY" 
   (	"NODEPARSEHISTORYID" NUMBER(20,0) DEFAULT "NODE_PARSE_HISTORY_SEQ"."NEXTVAL",
    "XMLPARSERUNID" NUMBER(20,0), 
    "OPCO" NVARCHAR2(50), 
	"OEM" NVARCHAR2(50), 
	"ELEMENTNAME" NVARCHAR2(50), 
	"PARSETYPE" NVARCHAR2(10),
	"UPDATEDROWS" NUMBER(5,0),
    "STATUS" NVARCHAR2(50),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp)    				
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";
--------------------------------------------------------
--  DDL for Index NODEPARSEHISTORYIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "NODEPARSEHISTORY_IDX" ON "NODEPARSEHISTORY" ("NODEPARSEHISTORYID")
   PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";
--------------------------------------------------------
--  Constraints for Table NODEPARSEHISTORY
--------------------------------------------------------
  ALTER TABLE "NODEPARSEHISTORY" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "NODEPARSEHISTORY" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "NODEPARSEHISTORY" ADD CONSTRAINT "NODE_PARSE_HISTORY_PK" PRIMARY KEY ("NODEPARSEHISTORYID")
   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;
  
--------------------------------------------------------
--  Ref Constraints for Table NODEPARSEHISTORY
--------------------------------------------------------

  ALTER TABLE "NODEPARSEHISTORY" ADD CONSTRAINT "FK_XML_PARSE_RUN" FOREIGN KEY ("XMLPARSERUNID")
 REFERENCES "XMLPARSERUN" ("XMLPARSERUNID") ENABLE;
 
 ALTER TABLE "NODEPARSEHISTORY"
 MODIFY("NODEPARSEHISTORYID"  DEFAULT "NODE_PARSE_HISTORY_SEQ"."NEXTVAL");
