CREATE SEQUENCE "AUDIT_HISTORY_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL for Table AUDITHISTORY
--------------------------------------------------------

   CREATE TABLE "AUDITHISTORY" 
(
    "AUDITHISTORYID" NUMBER(20,0) DEFAULT "AUDIT_HISTORY_SEQ"."NEXTVAL",
    "TABLENAME" NVARCHAR2(50), 
    "COLUMNNAME" NVARCHAR2(50), 
    "PRIMARYKEY" NUMBER(20,0), 
    "OLDVALUE" NVARCHAR2(1000), 
    "NEWVALUE" NVARCHAR2(1000), 
    "STATUS" NVARCHAR2(50), 
    "CREATIONUSER" NUMBER(10,0), 
    "CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
    "MODIFICATIONUSER" NUMBER(10,0), 
    "MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp)    		
 )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";
--------------------------------------------------------
--  DDL for Index AUDITHISTORYIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUDITHISTORYIDX" ON "AUDITHISTORY" ("AUDITHISTORYID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";
--------------------------------------------------------
--  Constraints for Table AUDITHISTORY
--------------------------------------------------------
  ALTER TABLE "AUDITHISTORY" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "AUDITHISTORY" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "AUDITHISTORY" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "AUDITHISTORY" ADD CONSTRAINT "AUDIT_HISTORY_PK" PRIMARY KEY ("AUDITHISTORYID")
   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;
  
--------------------------------------------------------
--  Ref Constraints for Table AUDITHISTORY
--------------------------------------------------------

 ALTER TABLE "AUDITHISTORY"
 MODIFY("AUDITHISTORYID"  DEFAULT "AUDIT_HISTORY_SEQ"."NEXTVAL");

