--Table content fix--
ALTER TABLE NETWORKELEMENT ADD ("DELETED" NUMBER(1,0) DEFAULT 0,
    "DELETIONDATE" TIMESTAMP (6));
ALTER TABLE SOFTWARECOMPONENT ADD ("DELETED" NUMBER(1,0) DEFAULT 0,
    "DELETIONDATE" TIMESTAMP (6));
ALTER TABLE COMPONENT ADD ("DELETED" NUMBER(1,0) DEFAULT 0,
    "DELETIONDATE" TIMESTAMP (6));
ALTER TABLE SOFTWARECONFIGURATION ADD ("DELETED" NUMBER(1,0) DEFAULT 0,
    "DELETIONDATE" TIMESTAMP (6));
ALTER TABLE HARDWARECONFIGURATION ADD ("DELETED" NUMBER(1,0) DEFAULT 0,
    "DELETIONDATE" TIMESTAMP (6));
ALTER TABLE FUNCTION ADD ("DELETED" NUMBER(1,0) DEFAULT 0,
    "DELETIONDATE" TIMESTAMP (6));
ALTER TABLE FUNCTIONAREA ADD ("DELETED" NUMBER(1,0) DEFAULT 0,
    "DELETIONDATE" TIMESTAMP (6));
ALTER TABLE SUBFUNCTION ADD ("DELETED" NUMBER(1,0) DEFAULT 0,
    "DELETIONDATE" TIMESTAMP (6));
ALTER TABLE SUBFUNCTIONAREA ADD ("DELETED" NUMBER(1,0) DEFAULT 0,
    "DELETIONDATE" TIMESTAMP (6));
ALTER TABLE SUBFUNCTIONAREA2 ADD ("DELETED" NUMBER(1,0) DEFAULT 0,
    "DELETIONDATE" TIMESTAMP (6));
ALTER TABLE AUDITHISTORY ADD ("DELETED" NUMBER(1,0) DEFAULT 0,
    "DELETIONDATE" TIMESTAMP (6));
ALTER TABLE NODEPARSEHISTORY ADD ("DELETED" NUMBER(1,0) DEFAULT 0,
    "DELETIONDATE" TIMESTAMP (6));
ALTER TABLE XMLPARSERUN ADD ("DELETED" NUMBER(1,0) DEFAULT 0,
    "DELETIONDATE" TIMESTAMP (6));
commit;