    ALTER TABLE "SOFTWARECOMPONENT" ADD CONSTRAINT "FK_SOFTWARECOMPONENT_NETWORKELEMENTID" FOREIGN KEY ("NETWORKELEMENTID")
  REFERENCES "NETWORKELEMENT" ("NETWORKELEMENTID") ENABLE;
    ALTER TABLE "SOFTWARECONFIGURATION" ADD CONSTRAINT "FK_SOFTWARECONFIGURATION_NETWORKELEMENTID" FOREIGN KEY ("NETWORKELEMENTID")
  REFERENCES "NETWORKELEMENT" ("NETWORKELEMENTID") ENABLE;
    ALTER TABLE "IDENTITIES" ADD CONSTRAINT "FK_IDENTITIES_NETWORKELEMENTID" FOREIGN KEY ("NETWORKELEMENTID")
  REFERENCES "NETWORKELEMENT" ("NETWORKELEMENTID") ENABLE;
      ALTER TABLE "HARDWARECONFIGURATION" ADD CONSTRAINT "FK_HARDWARECONFIGURATION_NETWORKELEMENTID" FOREIGN KEY ("NETWORKELEMENTID")
  REFERENCES "NETWORKELEMENT" ("NETWORKELEMENTID") ENABLE;
      ALTER TABLE "COMPONENT" ADD CONSTRAINT "FK_COMPONENT_SOFTWARECOMPONENTID" FOREIGN KEY ("SOFTWARECOMPONENTID")
  REFERENCES "SOFTWARECOMPONENT" ("SOFTWARECOMPONENTID") ENABLE;
      ALTER TABLE "FUNCTION" ADD CONSTRAINT "FK_FUNCTION_FUNCTIONID" FOREIGN KEY ("SOFTWARECONFIGURATIONID")
  REFERENCES "SOFTWARECONFIGURATION" ("SOFTWARECONFIGURATIONID") ENABLE;
      ALTER TABLE "FUNCTIONAREA" ADD CONSTRAINT "FK_FUNCTIONAREA_FUNCTIONAREA" FOREIGN KEY ("FUNCTIONID")
  REFERENCES "FUNCTION" ("FUNCTIONID") ENABLE;
      ALTER TABLE "SUBFUNCTION" ADD CONSTRAINT "FK_SUBFUNCTION_SUBFUNCTION" FOREIGN KEY ("FUNCTIONAREAID")
  REFERENCES "FUNCTIONAREA" ("FUNCTIONAREAID") ENABLE;
    ALTER TABLE "SUBFUNCTIONAREA" ADD CONSTRAINT "FK_SUBFUNCTIONAREA_SUBFUNCTIONID" FOREIGN KEY ("SUBFUNCTIONID")
  REFERENCES "SUBFUNCTION" ("SUBFUNCTIONID") ENABLE;
    ALTER TABLE "SUBFUNCTIONAREA2" ADD CONSTRAINT "FK_SUBFUNCTIONAREA2_SUBFUNCTIONID" FOREIGN KEY ("SUBFUNCTIONID")
  REFERENCES "SUBFUNCTION" ("SUBFUNCTIONID") ENABLE;
    ALTER TABLE "NODEPARSEHISTORY" ADD CONSTRAINT "FK_XMLPARSERUN_XMLPARSERUNID" FOREIGN KEY ("XMLPARSERUNID")
  REFERENCES "XMLPARSERUN" ("XMLPARSERUNID") ENABLE;