   ALTER TABLE "NETWORKELEMENT" ADD CONSTRAINT "FK_NETWORKELEMENT_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
  ALTER TABLE "NETWORKELEMENT" ADD CONSTRAINT "FK_NETWORKELEMENT_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
 ALTER TABLE "SOFTWARECOMPONENT" ADD CONSTRAINT "FK_SOFTWARECOMPONENT_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
  ALTER TABLE "SOFTWARECOMPONENT" ADD CONSTRAINT "FK_SOFTWARECOMPONENT_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;  
	  
  ALTER TABLE "COMPONENT" ADD CONSTRAINT "FK_COMPONENT_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
  ALTER TABLE "COMPONENT" ADD CONSTRAINT "FK_COMPONENT_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
 ALTER TABLE "SOFTWARECONFIGURATION" ADD CONSTRAINT "FK_SOFTWARECONFIGURATION_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
  ALTER TABLE "SOFTWARECONFIGURATION" ADD CONSTRAINT "FK_SOFTWARECONFIGURATION_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
   ALTER TABLE "FUNCTION" ADD CONSTRAINT "FK_FUNCTION_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
  ALTER TABLE "FUNCTION" ADD CONSTRAINT "FK_FUNCTION_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
 ALTER TABLE "FUNCTIONAREA" ADD CONSTRAINT "FK_FUNCTIONAREA_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
  ALTER TABLE "FUNCTIONAREA" ADD CONSTRAINT "FK_FUNCTIONAREA_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;  
	  
  ALTER TABLE "SUBFUNCTION" ADD CONSTRAINT "FK_SUBFUNCTION_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
  ALTER TABLE "SUBFUNCTION" ADD CONSTRAINT "FK_SUBFUNCTION_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
 ALTER TABLE "SUBFUNCTIONAREA" ADD CONSTRAINT "FK_SUBFUNCTIONAREA_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
  ALTER TABLE "SUBFUNCTIONAREA" ADD CONSTRAINT "FK_SUBFUNCTIONAREA_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE; 
	  
   ALTER TABLE "SUBFUNCTIONAREA2" ADD CONSTRAINT "FK_SUBFUNCTIONAREA2_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
  ALTER TABLE "SUBFUNCTIONAREA2" ADD CONSTRAINT "FK_SUBFUNCTIONAREA2_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
   ALTER TABLE "IDENTITIES" ADD CONSTRAINT "FK_IDENTITIES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
  ALTER TABLE "IDENTITIES" ADD CONSTRAINT "FK_IDENTITIES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;	

   ALTER TABLE "HARDWARECONFIGURATION" ADD CONSTRAINT "FK_HARDWARECONFIGURATION_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
  ALTER TABLE "HARDWARECONFIGURATION" ADD CONSTRAINT "FK_HARDWARECONFIGURATION_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
   ALTER TABLE "AUDITHISTORY" ADD CONSTRAINT "FK_AUDITHISTORY_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
  ALTER TABLE "AUDITHISTORY" ADD CONSTRAINT "FK_AUDITHISTORY_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;	

   ALTER TABLE "NODEPARSEHISTORY" ADD CONSTRAINT "FK_NODEPARSEHISTORY_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
	  
  ALTER TABLE "XMLPARSERUN" ADD CONSTRAINT "FK_XMLPARSERUN_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;	
	  