INSERT INTO "ACTIVITYSTATUSES" (CREATIONUSER, MODIFICATIONUSER, DELETED, ACTIVITYSTATUS, RULE, PROJECTSTATUSCOMBINATIONRULE) 
VALUES ('1', '1', '0', 'No Planned Activity', '0', '0');

INSERT INTO "PLANNINGACTIVITYSTATUSES" (CREATIONUSER, MODIFICATIONUSER, DELETED, PLANNINGACTIVITYSTATUS, PROJECTSTATUSCOMBINATIONRULE, DEFAULT_) 
VALUES ('1', '1', '0', 'No Planned Activity', '0', '0');
commit;