---need to run insert script
insert into SETTINGSUPDATEPLANNEDACTIVITY
( CREATIONUSER, MODIFICATIONUSER, PLANNINGACTIVITYSTATUSID, BUDGETAVAILABILITYID, DELIVERYSTATUSID, ORDER_, MAXORDER, LASTMODIFIED, RULE, RULEELEMENTCOUNT, LASTMODIFIEDBY, LOCALAPPROVAL, SETTINGSUPDATEPLNACTDES, PLANNEDACTIVITYRESOURCEID, SUCCESSORPLANNEDACTIVITYRESOURCEID, RULEFORSUCCESSORPLANNEDACTIVITYCREATION, PLANNEDACTIVITYTYPEFOR, SPECIFYDC)
SELECT  CREATIONUSER, MODIFICATIONUSER, PLANNINGACTIVITYSTATUSID,
BUDGETAVAILABILITYID, DELIVERYSTATUSID, ORDER_, MAXORDER, LASTMODIFIED, RULE,
RULEELEMENTCOUNT, LASTMODIFIEDBY, LOCALAPPROVAL, 'New Solution Deployment',
PLANNEDACTIVITYRESOURCEID, SUCCESSORPLANNEDACTIVITYRESOURCEID,
RULEFORSUCCESSORPLANNEDACTIVITYCREATION, PLANNEDACTIVITYTYPEFOR, SPECIFYDC
FROM SETTINGSUPDATEPLANNEDACTIVITY
WHERE UPPER(SETTINGSUPDATEPLNACTDES) IN ('WAITING FOR NEW DEPLOYMENT SOLUTION') AND plannedactivityresourceid in (SELECT plannedactivityresourceid FROM plannedactivityresources where RULELINKEDDC IN 14); 





--need to update start with max of order from table
UPDATE SETTINGSUPDATEPLANNEDACTIVITY SET ORDER_ = 106	WHERE UPPER(SETTINGSUPDATEPLNACTDES) IN ('WAITING FOR NEW DEPLOYMENT SOLUTION') AND plannedactivityresourceid in (SELECT plannedactivityresourceid FROM plannedactivityresources where RULELINKEDDC IN 14); 
UPDATE SETTINGSUPDATEPLANNEDACTIVITY SET ORDER_ = 107	WHERE UPPER(SETTINGSUPDATEPLNACTDES) IN ('NEW SOLUTION DEPLOYMENT') AND plannedactivityresourceid in (SELECT plannedactivityresourceid FROM plannedactivityresources where RULELINKEDDC IN 14); 
UPDATE SETTINGSUPDATEPLANNEDACTIVITY SET ORDER_ = 108	WHERE UPPER(SETTINGSUPDATEPLNACTDES) IN ('TRAFFIC MIGRATION STARTED') AND plannedactivityresourceid in (SELECT plannedactivityresourceid FROM plannedactivityresources where RULELINKEDDC IN 14); 
UPDATE SETTINGSUPDATEPLANNEDACTIVITY SET ORDER_ = 109	WHERE UPPER(SETTINGSUPDATEPLNACTDES) IN ('TRAFFIC FREE') AND plannedactivityresourceid in (SELECT plannedactivityresourceid FROM plannedactivityresources where RULELINKEDDC IN 14); 
UPDATE SETTINGSUPDATEPLANNEDACTIVITY SET ORDER_ = 110	WHERE UPPER(SETTINGSUPDATEPLNACTDES) IN ('LOGICAL DECOMMISSION SUCCESSFUL') AND plannedactivityresourceid in (SELECT plannedactivityresourceid FROM plannedactivityresources where RULELINKEDDC IN 14); 
UPDATE SETTINGSUPDATEPLANNEDACTIVITY SET ORDER_ = 111    WHERE UPPER(SETTINGSUPDATEPLNACTDES) IN ('POWERED OFF') AND plannedactivityresourceid in (SELECT plannedactivityresourceid FROM plannedactivityresources where RULELINKEDDC IN 14); 
UPDATE SETTINGSUPDATEPLANNEDACTIVITY SET ORDER_ = 112	WHERE UPPER(SETTINGSUPDATEPLNACTDES) IN ('EQUIPMENT UNINSTALLED/REPURPOSED') AND plannedactivityresourceid in (SELECT plannedactivityresourceid FROM plannedactivityresources where RULELINKEDDC IN 14); 


---Table COlumn
ALTER TABLE SETTINGSUPDATEPLANNEDACTIVITY ADD NEEDPLANNEDASSET NUMBER(1,0) DEFAULT 0;

--CUSTOMCOLUMN
update gridcustomcolumn
set deleted=1 ,deletiondate=SYS_EXTRACT_UTC(systimestamp) 
where deleted = 0 and classname='SettingsUpdatePlannedActivityDtoGrid';
commit;