CREATE TABLE VNFCLUSTERINFO_BKP AS SELECT VNFCLUSTERINFOID, HARDWARETYPE FROM VNFCLUSTERINFO;

Insert into VNFHARDWARE (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER) values  ('Broadwell',1,1);
Insert into VNFHARDWARE (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER) values  ('CascadeLake',1,1);
Insert into VNFHARDWARE (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER) values  ('SapphireRapids',1,1);
Insert into VNFHARDWARE (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER) values  ('SkyLake',1,1);
commit;

ALTER TABLE VNFCLUSTERINFO ADD HARDWARETYPEID NUMBER(19,0);
        
MERGE INTO VNFCLUSTERINFO t
USING VNFHARDWARE s
ON (t.HARDWARETYPE = s.DESCRIPTION)
WHEN MATCHED THEN UPDATE SET t.HARDWARETYPEID = s.VNFHARDWAREID;

ALTER TABLE VNFCLUSTERINFO MODIFY HARDWARETYPEID NOT NULL;

ALTER TABLE VNFCLUSTERINFO
ADD CONSTRAINT FK_VNFCLUSTERINFO_VNFHARDWARE_HARDWARETYPEID
FOREIGN KEY (HARDWARETYPEID)
REFERENCES VNFHARDWARE(VNFHARDWAREID);

ALTER TABLE VNFCLUSTERINFO DROP COLUMN HARDWARETYPE;