--------------------------------------------------------
--  DDL FOR SEQUENCE DATACENTER_SQE
--------------------------------------------------------

CREATE SEQUENCE "DATACENTER_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE DATACENTER
--------------------------------------------------------

CREATE TABLE DATACENTER 
   (	
    DATACENTERID NUMBER(19,0) DEFAULT DATACENTER_SQE.NEXTVAL  NOT NULL, 
	DESCRIPTION NVARCHAR2(50)  NOT NULL, 	
	OPCOID NUMBER(5,0) NOT NULL,
	ENVIRONMENTZONE NUMBER(1,0)  DEFAULT 0 NOT NULL,	
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_DATACENTER
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_DATACENTER" ON DATACENTER ("DATACENTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE DATACENTER MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE DATACENTER MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE DATACENTER MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE DATACENTER MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE DATACENTER ADD CONSTRAINT "PK_DATACENTER" PRIMARY KEY ("DATACENTERID")
USING INDEX "PK_DATACENTER"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE DATACENTER ADD CONSTRAINT "FK_DATACENTER_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE DATACENTER ADD CONSTRAINT "FK_DATACENTER_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;	  	
ALTER TABLE DATACENTER ADD CONSTRAINT "FK_DATACENTER_OPCOS_OPCOID" FOREIGN KEY ("OPCOID")
	  REFERENCES "OPCOS" ("OPCOID") ENABLE; 
COMMIT;

--------------------------------------------------------
--  DDL FOR SEQUENCE ASSETCLUSTERTYPE_SQE
--------------------------------------------------------

CREATE SEQUENCE "ASSETCLUSTERTYPE_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE ASSETCLUSTERTYPE
--------------------------------------------------------

CREATE TABLE ASSETCLUSTERTYPE 
   (	
    ASSETCLUSTERTYPEID NUMBER(19,0) DEFAULT ASSETCLUSTERTYPE_SQE.NEXTVAL  NOT NULL, 
	DESCRIPTION NVARCHAR2(50)  NOT NULL, 		
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_ASSETCLUSTERTYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ASSETCLUSTERTYPE" ON ASSETCLUSTERTYPE ("ASSETCLUSTERTYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE ASSETCLUSTERTYPE MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE ASSETCLUSTERTYPE MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE ASSETCLUSTERTYPE MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE ASSETCLUSTERTYPE MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE ASSETCLUSTERTYPE ADD CONSTRAINT "PK_ASSETCLUSTERTYPE" PRIMARY KEY ("ASSETCLUSTERTYPEID")
USING INDEX "PK_ASSETCLUSTERTYPE"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE ASSETCLUSTERTYPE ADD CONSTRAINT "FK_ASSETCLUSTERTYPE_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE ASSETCLUSTERTYPE ADD CONSTRAINT "FK_ASSETCLUSTERTYPE_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;	  	
COMMIT;

--------------------------------------------------------
--  DDL FOR SEQUENCE ASSETCLUSTER_SQE  
--------------------------------------------------------

CREATE SEQUENCE "ASSETCLUSTER_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE ASSETCLUSTER
--------------------------------------------------------

CREATE TABLE ASSETCLUSTER 
   (	
    ASSETCLUSTERID NUMBER(19,0) DEFAULT ASSETCLUSTER_SQE.NEXTVAL  NOT NULL, 
	DESCRIPTION NVARCHAR2(50)  NOT NULL, 		
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_ASSETCLUSTER
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ASSETCLUSTER" ON ASSETCLUSTER ("ASSETCLUSTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE ASSETCLUSTER MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE ASSETCLUSTER MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE ASSETCLUSTER MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE ASSETCLUSTER MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE ASSETCLUSTER ADD CONSTRAINT "PK_ASSETCLUSTER" PRIMARY KEY ("ASSETCLUSTERID")
USING INDEX "PK_ASSETCLUSTER"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE ASSETCLUSTER ADD CONSTRAINT "FK_ASSETCLUSTER_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE ASSETCLUSTER ADD CONSTRAINT "FK_ASSETCLUSTER_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;	  	
COMMIT;

--------------------------------------------------------
--  DDL FOR SEQUENCE ASSETHARDWAREANCILLARY_SQE   
--------------------------------------------------------

CREATE SEQUENCE "ASSETHARDWAREANCILLARY_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE ASSETHARDWAREANCILLARY
--------------------------------------------------------

CREATE TABLE ASSETHARDWAREANCILLARY 
   (	
    ASSETHARDWAREANCILLARYID NUMBER(19,0) DEFAULT ASSETHARDWAREANCILLARY_SQE.NEXTVAL  NOT NULL, 	
	NETWORKELEMENTASPLANNEDID NUMBER(19,0) NOT NULL,
	MAJORHARDWAREID NUMBER(19,0)  NULL,
	DATACENTERID NUMBER(19,0)  NULL,
	CLUSTERNAMEID NUMBER(19,0)  NULL,
	ASSETCLUSTERTYPEID NUMBER(19,0)  NULL,
	ASSETCLUSTERID NUMBER(19,0)  NULL,	
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_ASSETHARDWAREANCILLARY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ASSETHARDWAREANCILLARY" ON ASSETHARDWAREANCILLARY ("ASSETHARDWAREANCILLARYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE ASSETHARDWAREANCILLARY MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE ASSETHARDWAREANCILLARY MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE ASSETHARDWAREANCILLARY MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE ASSETHARDWAREANCILLARY MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE ASSETHARDWAREANCILLARY ADD CONSTRAINT "PK_ASSETHARDWAREANCILLARY" PRIMARY KEY ("ASSETHARDWAREANCILLARYID")
USING INDEX "PK_ASSETHARDWAREANCILLARY"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE ASSETHARDWAREANCILLARY ADD CONSTRAINT "FK_ASSETHARDWAREANCILLARY_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE ASSETHARDWAREANCILLARY ADD CONSTRAINT "FK_ASSETHARDWAREANCILLARY_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;

ALTER TABLE ASSETHARDWAREANCILLARY ADD CONSTRAINT "FK_ASSETHARDWAREANCILLARY_MAJORHARDWAREBUILDS_MAJORHARDWAREID" FOREIGN KEY ("MAJORHARDWAREID")
	  REFERENCES "MAJORHARDWAREBUILDS" ("MAJORHARDWAREID") ENABLE;
ALTER TABLE ASSETHARDWAREANCILLARY ADD CONSTRAINT "FK_ASSETHARDWAREANCILLARY_NETWORKELEMENTSASPLANNED_NETWORKELEMENTASPLANNEDID" FOREIGN KEY ("NETWORKELEMENTASPLANNEDID")REFERENCES "NETWORKELEMENTSASPLANNED" ("NETWORKELEMENTASPLANNEDID") ENABLE;

ALTER TABLE ASSETHARDWAREANCILLARY ADD CONSTRAINT "FK_ASSETHARDWAREANCILLARY_DATACENTER_DATACENTERID" FOREIGN KEY ("DATACENTERID")
	  REFERENCES "DATACENTER" ("DATACENTERID") ENABLE;
ALTER TABLE ASSETHARDWAREANCILLARY ADD CONSTRAINT "FK_ASSETHARDWAREANCILLARY_CLUSTERNAME_CLUSTERNAMEID" FOREIGN KEY ("CLUSTERNAMEID")
	  REFERENCES "CLUSTERNAME" ("CLUSTERNAMEID") ENABLE;
ALTER TABLE ASSETHARDWAREANCILLARY ADD CONSTRAINT "FK_ASSETHARDWAREANCILLARY_ASSETCLUSTERTYPE_ASSETCLUSTERTYPEID" FOREIGN KEY ("ASSETCLUSTERTYPEID")
	  REFERENCES "ASSETCLUSTERTYPE" ("ASSETCLUSTERTYPEID") ENABLE;
ALTER TABLE ASSETHARDWAREANCILLARY ADD CONSTRAINT "FK_ASSETHARDWAREANCILLARY_ASSETCLUSTER_ASSETCLUSTERID" FOREIGN KEY ("ASSETCLUSTERID")
	  REFERENCES "ASSETCLUSTER" ("ASSETCLUSTERID") ENABLE;	  
COMMIT;

--------------------------------------------------------
--  DDL FOR SEQUENCE ASSETCAPACITYINFO_SQE   
--------------------------------------------------------

CREATE SEQUENCE "ASSETCAPACITYINFO_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE ASSETCAPACITYINFO
--------------------------------------------------------

CREATE TABLE ASSETCAPACITYINFO 
   (	
    ASSETCAPACITYINFOID NUMBER(19,0) DEFAULT ASSETCAPACITYINFO_SQE.NEXTVAL  NOT NULL, 	
	ASSETHARDWAREANCILLARYID NUMBER(19,0) NOT NULL,
	PHYSICALSERVERHOSTNAME NVARCHAR2(500) NULL, 		
	PHYSICALSERVERIPADDRESS NVARCHAR2(100) NULL, 		
	PHYSICALSERVERSERIALNUMBER NVARCHAR2(500) NULL, 		
	NOOFINSTANCES NUMBER(19,0) NULL,
	VCPU NUMBER(19,0) NULL,
	MEMORY NUMBER(19,6) NULL,
	STORAGE NUMBER(19,6) NULL,
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_ASSETCAPACITYINFO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ASSETCAPACITYINFO" ON ASSETCAPACITYINFO ("ASSETCAPACITYINFOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE ASSETCAPACITYINFO MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE ASSETCAPACITYINFO MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE ASSETCAPACITYINFO MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE ASSETCAPACITYINFO MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE ASSETCAPACITYINFO ADD CONSTRAINT "PK_ASSETCAPACITYINFO" PRIMARY KEY ("ASSETCAPACITYINFOID")
USING INDEX "PK_ASSETCAPACITYINFO"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE ASSETCAPACITYINFO ADD CONSTRAINT "FK_ASSETCAPACITYINFO_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE ASSETCAPACITYINFO ADD CONSTRAINT "FK_ASSETCAPACITYINFO_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;

ALTER TABLE ASSETCAPACITYINFO ADD CONSTRAINT "FK_ASSETCAPACITYINFO_ASSETHARDWAREANCILLARY_ASSETHARDWAREANCILLARY" FOREIGN KEY ("ASSETHARDWAREANCILLARYID")REFERENCES "ASSETHARDWAREANCILLARY" ("ASSETHARDWAREANCILLARYID") ENABLE;   
COMMIT;
---------------------------

DELETE FROM GRIDCUSTOMCOLUMN  WHERE  CLASSNAME='NetworkElementAsPlannedDtoGrid';
COMMIT



