
ALTER TABLE tsrpassthrough ADD (
							col1_temp NVARCHAR2(50), 
                            col2_temp NVARCHAR2(50),
                            col3_temp NVARCHAR2(50),
                            col4_temp NVARCHAR2(50),
                            col5_temp NVARCHAR2(50),
                            col6_temp NVARCHAR2(50),
                            col7_temp NVARCHAR2(50),
                            col8_temp NVARCHAR2(50),
                            col9_temp NVARCHAR2(50)
							   );

UPDATE tsrpassthrough SET 
    col1_temp = TO_CHAR(VENDORHARDWAREENDOFSUPPORTDATE, 'YYYY-MM-DD HH24:MI:SS'),
    col2_temp = TO_CHAR(MAINTENANCEHARDWAREENDOFSUPPORTDATE, 'YYYY-MM-DD HH24:MI:SS'),
    col3_temp = TO_CHAR(DATEASSETMOVEDTOLIVESTATUS, 'YYYY-MM-DD HH24:MI:SS'),
    col4_temp = TO_CHAR(DATEASSETDECOMMISSIONED, 'YYYY-MM-DD HH24:MI:SS'),
    col5_temp = TO_CHAR(VENDORSOFTWAREENDOFSUPPORTDATE, 'YYYY-MM-DD HH24:MI:SS'),
    col6_temp = TO_CHAR(MAINTENANCESOFTWAREENDOFSUPPORTDATE, 'YYYY-MM-DD HH24:MI:SS'),
    col7_temp = TO_CHAR(LASTUPGRADEDATE, 'YYYY-MM-DD HH24:MI:SS'),
    col8_temp = TO_CHAR(LASTPENTESTDATE, 'YYYY-MM-DD HH24:MI:SS'),
    col9_temp = TO_CHAR(PROJECTENDDATE, 'YYYY-MM-DD HH24:MI:SS');   
    COMMIT;
 
ALTER TABLE tsrpassthrough DROP COLUMN VENDORHARDWAREENDOFSUPPORTDATE;
ALTER TABLE tsrpassthrough DROP COLUMN MAINTENANCEHARDWAREENDOFSUPPORTDATE;
ALTER TABLE tsrpassthrough DROP COLUMN DATEASSETMOVEDTOLIVESTATUS;
ALTER TABLE tsrpassthrough DROP COLUMN DATEASSETDECOMMISSIONED;
ALTER TABLE tsrpassthrough DROP COLUMN VENDORSOFTWAREENDOFSUPPORTDATE;
ALTER TABLE tsrpassthrough DROP COLUMN MAINTENANCESOFTWAREENDOFSUPPORTDATE;
ALTER TABLE tsrpassthrough DROP COLUMN LASTUPGRADEDATE;
ALTER TABLE tsrpassthrough DROP COLUMN PROJECTENDDATE;
ALTER TABLE tsrpassthrough DROP COLUMN LASTPENTESTDATE;

ALTER TABLE tsrpassthrough RENAME COLUMN col1_temp TO VENDORHARDWAREENDOFSUPPORTDATE;
ALTER TABLE tsrpassthrough RENAME COLUMN col2_temp TO MAINTENANCEHARDWAREENDOFSUPPORTDATE;
ALTER TABLE tsrpassthrough RENAME COLUMN col3_temp TO DATEASSETMOVEDTOLIVESTATUS;
ALTER TABLE tsrpassthrough RENAME COLUMN col4_temp TO DATEASSETDECOMMISSIONED;
ALTER TABLE tsrpassthrough RENAME COLUMN col5_temp TO VENDORSOFTWAREENDOFSUPPORTDATE;
ALTER TABLE tsrpassthrough RENAME COLUMN col6_temp TO MAINTENANCESOFTWAREENDOFSUPPORTDATE;
ALTER TABLE tsrpassthrough RENAME COLUMN col7_temp TO LASTUPGRADEDATE;
ALTER TABLE tsrpassthrough RENAME COLUMN col8_temp TO LASTPENTESTDATE;
ALTER TABLE tsrpassthrough RENAME COLUMN col9_temp TO PROJECTENDDATE;
ALTER TABLE tsrpassthrough ADD RECORDCLASSIFIER NUMBER(10,0);
COMMIT;
 
