--------------------------------------------------------
--  DDL FOR SEQUENCE TSRLOGS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE "TSRLOGS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 9261 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE TSRLOGS
--------------------------------------------------------

  CREATE TABLE TSRLOGS 
   (	
    "TSRLOGID" NUMBER(20,0) DEFAULT "TSRLOGS_SEQ"."NEXTVAL", 
	"TYPEOFOPERATION" NVARCHAR2(100), 
	"DOMAIN" NVARCHAR2(100), 
	"BATCHIDENTIFIER" NVARCHAR2(100), 
	"FILENAME" NVARCHAR2(100), 
	"TOTALRECORD" NUMBER(19,0), 
	"PROCESSEDRECORD" NUMBER(19,0),
    "STARTTIME" TIMESTAMP (6),
    "ENDTIME" TIMESTAMP (6),
    "STATUS" NVARCHAR2(100), 
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6),
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_AUDITLOGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TSRLOGS" ON TSRLOGS ("TSRLOGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE TSRLOGS MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE TSRLOGS MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE TSRLOGS MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE TSRLOGS MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE TSRLOGS ADD CONSTRAINT "PK_TSRLOGS" PRIMARY KEY ("TSRLOGID")
  USING INDEX "PK_TSRLOGS"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE TSRLOGS ADD CONSTRAINT "FK_TSRLOGS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE TSRLOGS ADD CONSTRAINT "FK_TSRLOGS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
COMMIT;