--------------------------------------------------------
--  DDL FOR TABLE ASPNETUSERPREFERENCES_SEQ
--------------------------------------------------------

CREATE SEQUENCE "ASPNETUSERPREFERENCES_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE ASPNETUSERPREFERENCES 
---------------------------------------


CREATE TABLE "ASPNETUSERPREFERENCES" 
(	"ASPNETUSERPREFERENCEID" NUMBER(10,0) DEFAULT "ASPNETUSERPREFERENCES_SEQ"."NEXTVAL",
	"USERID" NUMBER(10,0),
	"ASPNETMODULEID" NUMBER(10,0),
	"PERMISSION" NUMBER(5,0),
	"ORDER" NUMBER(10,0),
	"ISUSERPREFERENCE" NUMBER(1,0) DEFAULT (1),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
  
  --------------------------------------------------------
--  DDL FOR INDEX PK_ASPNETUSERPREFERENCES
-------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_ASPNETUSERPREFERENCES" ON "ASPNETUSERPREFERENCES" ("ASPNETUSERPREFERENCEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE ASPNETUSERPREFERENCES
--------------------------------------------------------
 
  ALTER TABLE "ASPNETUSERPREFERENCES" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSERPREFERENCES" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSERPREFERENCES" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSERPREFERENCES" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSERPREFERENCES" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "ASPNETUSERPREFERENCES" ADD CONSTRAINT "PK_ASPNETUSERPREFERENCES" PRIMARY KEY ("ASPNETUSERPREFERENCEID") USING INDEX "PK_ASPNETUSERPREFERENCES"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE ASPNETUSERPREFERENCES
--------------------------------------------------------

  ALTER TABLE "ASPNETUSERPREFERENCES" ADD CONSTRAINT "FK_ASPNETUSERPREFERENCES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "ASPNETUSERPREFERENCES" ADD CONSTRAINT"FK_ASPNETUSERPREFERENCES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "ASPNETUSERPREFERENCES" ADD CONSTRAINT"FK_ASPNETUSERPREFERENCES_ASPNETUSERS_USERID" FOREIGN KEY ("USERID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "ASPNETUSERPREFERENCES" ADD CONSTRAINT"FK_ASPNETUSERPREFERENCES_ASPNETMODULES_ASPNETMODULEID" FOREIGN KEY ("ASPNETMODULEID") REFERENCES "ASPNETMODULES" ("ASPNETMODULEID") ENABLE;
  COMMIT;