CREATE SEQUENCE VODAFONENAMES_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  COMMIT
  
  --------------------------------------------------------
--  DDL for Table VODAFONENAMES
--------------------------------------------------------

  CREATE TABLE "CAMSDBUSER"."VODAFONENAMES" 
   (	"ID" NUMBER(10,0) DEFAULT "CAMSDBUSER"."VODAFONENAMES_SEQ"."NEXTVAL", 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index VODAFONENAMES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMSDBUSER"."VODAFONENAMES_PK" ON "CAMSDBUSER"."VODAFONENAMES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table VODAFONENAMES
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."VODAFONENAMES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."VODAFONENAMES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."VODAFONENAMES" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."VODAFONENAMES" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."VODAFONENAMES" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."VODAFONENAMES" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."VODAFONENAMES" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."VODAFONENAMES" ADD CONSTRAINT "VODAFONENAMES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VODAFONENAMES
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."VODAFONENAMES" ADD CONSTRAINT "FK_VODAFONENAMES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."VODAFONENAMES" ADD CONSTRAINT "FK_VODAFONENAMES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;

  
  ALTER TABLE CAMSDBUSER.VODAFONENAMES
MODIFY(ID  DEFAULT "CAMSDBUSER"."VODAFONENAMES_SEQ"."NEXTVAL");
COMMIT