ALTER TABLE SOFTWAREAPPLICATIONTYPES
ADD "VODAFONENAMESID" NUMBER(10,0);

  ALTER TABLE "CAMSDBUSER"."SOFTWAREAPPLICATIONTYPES" ADD CONSTRAINT "FK_SOFTWAREAPPLICATIONTYPES_VODAFONENAMES_VODAFONENAMESID" FOREIGN KEY ("VODAFONENAMESID")
      REFERENCES "CAMSDBUSER"."VODAFONENAMES" ("ID") ENABLE;

