

ALTER TABLE SYSTEMTYPES
	ADD "VODAFONENAME" NUMBER(10,0);


ALTER TABLE "CAMSDBUSER"."SYSTEMTYPES" ADD CONSTRAINT "FK_SYSTEMTYPES_VODAFONENAMES_VODAFONENAMESID" FOREIGN KEY ("VODAFONENAME")
	REFERENCES "CAMSDBUSER"."VODAFONENAMES" ("ID") ENABLE;