ALTER TABLE plannedactivityresources
ADD "FORADDASSET" NUMBER(1,0);

ALTER TABLE plannedactivityresources
ADD "FOREDITASSET" NUMBER(1,0);
------------------------------------------


ALTER TABLE plannedactivityresources
ADD FORCREATEADDASSET NUMBER(1,0);

ALTER TABLE plannedactivityresources
ADD FOREDITADDASSET NUMBER(1,0);

ALTER TABLE plannedactivityresources
ADD RULEADDASSET NUMBER(10,0);

ALTER TABLE plannedactivityresources
ADD ADDASSETHARDWARE   NUMBER(1,0);

ALTER TABLE plannedactivityresources
ADD ADDASSETSOFTWARE   NUMBER(1,0);

ALTER TABLE plannedactivityresources
ADD ONBAREMETALADDASSET NUMBER(1,0);

ALTER TABLE plannedactivityresources
ADD ONVIRTUALIZEDADDASSET NUMBER(1,0);

ALTER TABLE plannedactivityresources
ADD ACTIVITYDETAILSADDASSET NVARCHAR2(2000);

ALTER TABLE plannedactivityresources
ADD BENEFITTEXTADDASSET NVARCHAR2(2000);

ALTER TABLE plannedactivityresources
ADD DRIVERTEXTADDASSET NVARCHAR2(2000);

ALTER TABLE plannedactivityresources
ADD ACTDETAILSFORVRTADDASSET NVARCHAR2(2000);

ALTER TABLE plannedactivityresources
ADD ADDASSETLABELSOFTWARE NVARCHAR2(2000);

ALTER TABLE plannedactivityresources
ADD ADDASSETLABELHARDWARE NVARCHAR2(2000);

ALTER TABLE plannedactivityresources
ADD RULEACTDETAILSADDASSET NUMBER(10,0);

ALTER TABLE plannedactivityresources
ADD PLANDESIGNCOMPREQADDASSET   NUMBER(1,0);

-------------------------------------

ALTER TABLE plannedactivityresources
ADD FORCREATEEDITASSET NUMBER(1,0);

ALTER TABLE plannedactivityresources
ADD FOREDITEDITASSET NUMBER(1,0);

ALTER TABLE plannedactivityresources
ADD RULEEDITASSET NUMBER(10,0);

ALTER TABLE plannedactivityresources
ADD EDITASSETHARDWARE  NUMBER(1,0);

ALTER TABLE plannedactivityresources
ADD EDITASSETSOFTWARE  NUMBER(1,0);

ALTER TABLE plannedactivityresources
ADD ONBAREMETALEDITASSET NUMBER(1,0);

ALTER TABLE plannedactivityresources
ADD ONVIRTUALIZEDEDITASSET NUMBER(1,0);

ALTER TABLE plannedactivityresources
ADD ACTIVITYDETAILSEDITASSET NVARCHAR2(2000);

ALTER TABLE plannedactivityresources
ADD BENEFITTEXTEDITASSET NVARCHAR2(2000);

ALTER TABLE plannedactivityresources
ADD DRIVERTEXTEDITASSET NVARCHAR2(2000);

ALTER TABLE plannedactivityresources
ADD ACTDETAILSFORVRTEDITASSET NVARCHAR2(2000);

ALTER TABLE plannedactivityresources
ADD EDITASSETLABELSOFTWARE NVARCHAR2(2000);

ALTER TABLE plannedactivityresources
ADD EDITASSETLABELHARDWARE NVARCHAR2(2000);


ALTER TABLE plannedactivityresources
ADD RULEACTDETAILSEDITASSET NUMBER(10,0);


ALTER TABLE plannedactivityresources
ADD PLANDESIGNCOMPREQEDITASSET   NUMBER(1,0);


-------------------------------------------------------


ALTER TABLE PLANNEDACTIVITYRESOURCEBENEFIT
ADD "FORADDASSET" NUMBER(1,0) DEFAULT 0;


ALTER TABLE PLANNEDACTIVITYRESOURCEBENEFIT
ADD "FOREDITASSET" NUMBER(1,0) DEFAULT 0;

ALTER TABLE PLANNEDACTIVITYRESOURCEDRIVER
ADD "FORADDASSET" NUMBER(1,0) DEFAULT 0;


ALTER TABLE PLANNEDACTIVITYRESOURCEDRIVER
ADD "FOREDITASSET" NUMBER(1,0) DEFAULT 0;

ALTER TABLE PLANNEDACTIVITYRESOURCEPLANNINGRISK
ADD "FORADDASSET" NUMBER(1,0) DEFAULT 0;


ALTER TABLE PLANNEDACTIVITYRESOURCEPLANNINGRISK
ADD "FOREDITASSET" NUMBER(1,0) DEFAULT 0;