ALTER TABLE MAJORSOFTWAREBUILDS
ADD "SOFTWAREAPPLICATIONTYPEID" NUMBER(20,0);


  ALTER TABLE "CAMSDBUSER"."MAJORSOFTWAREBUILDS" ADD CONSTRAINT "FK_MAJORSOFTWAREBUILDS_SOFTWAREAPPLICATIONTYPES_SOFTWAREAPPLICATIONTYPESID" FOREIGN KEY ("SOFTWAREAPPLICATIONTYPEID")
	  REFERENCES "CAMSDBUSER"."SOFTWAREAPPLICATIONTYPES" ("SOFTWAREAPPLICATIONTYPESID") ENABLE;

	  --need to migrate data from major sw to the new table and put the new ids in major sw

	  --update sw app types set values=select * distinct from major sw