
ALTER TABLE MAJORSOFTWAREBUILDS 
Add "CRITICALASSETTYPEID" Number(10,0) NULL;
commit;

-- check if need data migration

ALTER TABLE "CAMSDBUSER"."MAJORSOFTWAREBUILDS" ADD CONSTRAINT "FK_MAJORSOFTWAREBUILDS_CRITICALASSETTYPES_ID" FOREIGN KEY ("CRITICALASSETTYPEID")
REFERENCES "CAMSDBUSER"."CRITICALASSETTYPES" ("ID") ENABLE;




