ALTER TABLE SUBNETWORKBOUNDARIES
ADD "SOFTWAREAPPLICATIONTYPEID" NUMBER(20,0);


  ALTER TABLE "CAMSDBUSER"."SUBNETWORKBOUNDARIES" ADD CONSTRAINT "FK_SUBNETWORKBOUNDARIES_SOFTWAREAPPLICATIONTYPES_SOFTWAREAPPLICATIONTYPESID" FOREIGN KEY ("SOFTWAREAPPLICATIONTYPEID")
	  REFERENCES "CAMSDBUSER"."SOFTWAREAPPLICATIONTYPES" ("SOFTWAREAPPLICATIONTYPESID") ENABLE;