	ALTER TABLE DESIGNCOMPONENTFAMILIES
	ADD "SOFTWAREAPPLICATIONTYPEID" NUMBER(20,0);


	ALTER TABLE "CAMSDBUSER"."DESIGNCOMPONENTFAMILIES" ADD CONSTRAINT "FK_DESIGNCOMPONENTFAMILIES_SOFTWAREAPPLICATIONTYPES_SOFTWAREAPPLICATIONTYPESID"
	FOREIGN KEY ("SOFTWAREAPPLICATIONTYPEID")
	REFERENCES "CAMSDBUSER"."SOFTWAREAPPLICATIONTYPES" ("SOFTWAREAPPLICATIONTYPESID") 
	ENABLE;