----------------------------------------------------------
-- ROLLBACK SCRIPT FOR TABLE SWCONFIGFUNCTIONAREAS
----------------------------------------------------------
ALTER TABLE "SWCONFIGFUNCTIONAREAS" DROP CONSTRAINT "FK_SWCONFIGFUNCTIONAREAS_ASPNETUSERS_CREATIONUSER";
ALTER TABLE "SWCONFIGFUNCTIONAREAS" DROP CONSTRAINT "FK_SWCONFIGFUNCTIONAREAS_ASPNETUSERS_MODIFICATIONUSER";
ALTER TABLE "SWCONFIGFUNCTIONAREAS" DROP CONSTRAINT "FK_SWCONFIGFUNCTIONAREAS_FUNCTIOIN_FUNCTIONAREATESTID";
DROP SEQUENCE "SWCONFIGFUNCTIONAREA_SEQ";
DROP TABLE "SWCONFIGFUNCTIONAREAS";



COMMIT;