--------------------------------------------------------
--  DDL for Sequence PASSTHROUGHLCM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PASSTHROUGHLCM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table PASSTHROUGHLCM
--------------------------------------------------------

  CREATE TABLE "PASSTHROUGHLCM" 
   (	
    "PASSTHROUGHLCMID" NUMBER(19,0) DEFAULT "PASSTHROUGHLCM_SEQ"."NEXTVAL", 
    "NONTEMSVERTICAL" NUMBER(19,0) DEFAULT null, 
	"REPORTID" NVARCHAR2(50),
	"LOCALMARKET" NVARCHAR2(50),
	"VERTICALENGINEERINGTEAM" NVARCHAR2(50),
	"VERTICALSUBDOMAIN" NVARCHAR2(200),
	"ENGINEERINGCONTACTPOINT" NVARCHAR2(200),
	"SWOPERATIONSCONTACTPOINT" NVARCHAR2(200),
	"ASSETCATEGORY" NVARCHAR2(50),
	"ASSETCLASS" NVARCHAR2(50),
	"ASSETTYPE" NVARCHAR2(50),
	"ASSETDESCRIPTION" NVARCHAR2(50),
	"ASSETVIRTUALIZED" NVARCHAR2(50),
	"PRODUCTIMPORTANCE" NVARCHAR2(50),
	"SWVENDOR" NVARCHAR2(50),
	"HARDWAREMODEL" NVARCHAR2(50),
	"PRODUCTCODE" NVARCHAR2(50),
	"SOFTWAREVERSION" NVARCHAR2(50),
	"NUMBEROFNODES" NVARCHAR2(50),
	"HANDEDOVERTOOPERATION" NVARCHAR2(200),
	"SWOPERATIONSMAINTENANCECONTRACT" NVARCHAR2(200),
	"CONTRACTRENEWALPLAN" NVARCHAR2(200),
	"SWVENDORENDOFMAINTENANCEDATE" NVARCHAR2(200),
	"VENDORENDOFVULNERABILITYSECURITYSUPPORTDATE" NVARCHAR2(200),
	"LCMSTATUS" NVARCHAR2(200),
	"IDENTIFIEDACTION" NVARCHAR2(200),
	"DESCRIPTIONOFPLANNEDACTION" NVARCHAR2(200),
	"PLANNEDSOFTWAREVERSION" NVARCHAR2(200),
	"PROJECTSTATUS" NVARCHAR2(200),
	"REASONFORNOPLAN" NVARCHAR2(2000),
	"COMMENTONPROJECTSTATUS" NVARCHAR2(2000),
	"PROJECTENDDATE" NVARCHAR2(50),
	"RAGSTATUS" NVARCHAR2(50),
	"TRACKINGNUMBERPROJECTNAME" NVARCHAR2(50),
	"PROGRAM" NVARCHAR2(50),
	"WBSCODE" NVARCHAR2(50),
	"BPTID" NVARCHAR2(50),
	"PPMID" NVARCHAR2(50),
	"SCOPEOFSIMPLIFICATION" NVARCHAR2(50),
	"DATASOURCE" NVARCHAR2(50),
	"PROJECTOWNER" NVARCHAR2(50),
	"BUDGETESTIMATED" NVARCHAR2(50),
	"NOTES" NVARCHAR2(50),
	"BUNDLEBUDGET" NVARCHAR2(50),
	"BUNDLEID" NVARCHAR2(50),
	"ASSETSERVICEFUNCTIONALITY" NVARCHAR2(50),
	"PLATFORM" NVARCHAR2(50),
	"LCMSTATUSENGSOFTWARE" NVARCHAR2(50),
	"LCMSTATUSOPSSOFTWARE" NVARCHAR2(50),
	"SWOPSMAINTENANCECONRACTENDDATE" NVARCHAR2(50),
	"ENGRISKEVALUATION" NVARCHAR2(50),
	"ENGRISKEVALUATIONNOTES" NVARCHAR2(50),
	"OPSRISKEVALUATION" NVARCHAR2(50),
	"OPSRISKEVALUATIONNOTES" NVARCHAR2(50),
	"INCIDENTCLASS" NVARCHAR2(50),
	"OCCURRENCEPROBABILITY" NVARCHAR2(50),
	"NEWOPSRISKEVALUATION" NVARCHAR2(50),
	"OVERALLRISKEVALUATION" NVARCHAR2(50),
	"RISKCLUSTER" NVARCHAR2(50),
	"SECURITYRISKPOTENTIAL" NVARCHAR2(50),
	"VULNERABILITYSCORE" NVARCHAR2(50),
	"COMMENTS" NVARCHAR2(50),
	"QID" NVARCHAR2(50),
	"REQUESTID" NVARCHAR2(50),
	"VULNERABILITYRATING" NVARCHAR2(50),
	"SECURITYRISKEFFECTIVE" NVARCHAR2(50),
	"SECURITYMITIGATION" NVARCHAR2(50),
	"SECURITYRISKOVERALL" NVARCHAR2(50),
	"INCLUDEDINSECURITYSCANNING" NVARCHAR2(50),
	"RAID" NVARCHAR2(50),
	"LCMCUMULATIVERISKID" NVARCHAR2(50),
	"LCMCUMULATIVERISKLEVEL" NVARCHAR2(50),
	"CYBERRISKREQUESTID" NVARCHAR2(50),
	"CRITICALITY" NVARCHAR2(50),
	"ASSETSTATUS" NVARCHAR2(50),
	"GDPRRELEVANT" NVARCHAR2(50),
	"LASTSCANDATE" NVARCHAR2(50),
	"LASTUPGRADEDATE" NVARCHAR2(50),
	"ASSETOUTOFSCOPEFORREPORTINGPURPOSES" NVARCHAR2(200),
	"MAINORGANIZATION" NVARCHAR2(50),
	"ISEXTENDEDSUPPORTOFFEREDBYVENDOR" NVARCHAR2(50),
	"EOMCONTROL" NVARCHAR2(50),
	"ENGUPDATETRACKER" NVARCHAR2(50),
	"OPSUPDATETRACKER" NVARCHAR2(50),
	"TYPEOFNETWORKELEMENT" NVARCHAR2(50),
	"ENGKPI2" NVARCHAR2(50),
	"IPADDRESS" NVARCHAR2(50),
	"SERIALNUMBER" NVARCHAR2(50),
	"HOSTNAME" NVARCHAR2(50),
	"EXNETWORKS" NVARCHAR2(50),
	"ORIGINALLCMID" NVARCHAR2(200),
	"HWOPERATIONSCONTACTPOINT" NVARCHAR2(200),
	"HWVENDOR" NVARCHAR2(200),
	"HWOPERATIONSMAINTENANCECONTRACT" NVARCHAR2(200),
	"HWVENDORENDOFMAINTENANCEDATE" NVARCHAR2(200),
	"PLANNEDHWMODEL" NVARCHAR2(200),
	"HWOPSMAINTENANCECONTRACTENDDATE" NVARCHAR2(200),
	"LCMSTATUSENGHARDWARE" NVARCHAR2(200),
	"LCMSTATUSOPSHARDWARE" NVARCHAR2(200),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index PK_PASSTHROUGHLCM
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PASSTHROUGHLCM" ON "PASSTHROUGHLCM" ("PASSTHROUGHLCMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table PASSTHROUGHLCM
--------------------------------------------------------

  ALTER TABLE "PASSTHROUGHLCM" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "PASSTHROUGHLCM" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "PASSTHROUGHLCM" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "PASSTHROUGHLCM" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "PASSTHROUGHLCM" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "PASSTHROUGHLCM" ADD CONSTRAINT "PK_PASSTHROUGHLCM" PRIMARY KEY ("PASSTHROUGHLCMID")
  USING INDEX "PK_PASSTHROUGHLCM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PASSTHROUGHLCM
--------------------------------------------------------

  ALTER TABLE "PASSTHROUGHLCM" ADD CONSTRAINT "FK_PASSTHROUGHLCM_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "PASSTHROUGHLCM" ADD CONSTRAINT "FK_PASSTHROUGHLCM_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "PASSTHROUGHLCM" ADD CONSTRAINT "FK_PASSTHROUGHLCM_APPSETTINGSCONFIGURATION_NONTEMSVERTICAL" FOREIGN KEY ("NONTEMSVERTICAL")
	  REFERENCES "APPSETTINGSCONFIGURATION" ("APPCONFIGURATIONSETTINGID") ENABLE;
