--------------------------------------------------------
--  DDL FOR SEQUENCE MAJORHARDWAREBUILDASIS_SQE
--------------------------------------------------------

CREATE SEQUENCE "MAJORHARDWAREBUILDASIS_SQE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE MAJORHARDWAREBUILDASIS
--------------------------------------------------------

CREATE TABLE MAJORHARDWAREBUILDASIS 
   (	
    "MAJORHARDWAREBUILDASISID" NUMBER(19,0) DEFAULT "MAJORHARDWAREBUILDASIS_SQE"."NEXTVAL", 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC (SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC (SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6), 	
	"ORGEQPMANUFACTURERID" NUMBER(5,0) not null, 
	"HARDWARESOLUTION" NVARCHAR2(255), 
	"HARDWARESOLUTIONREOURCEID" NUMBER(5,0), 	 
	"PLATFORMID" NUMBER(5,0) not null,  
	"BUILDCONSTRUCTIONID" NUMBER(5,0) not null,  
	"HARDWARETYPE" NVARCHAR2(255) not null 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_MAJORHARDWAREASIS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_MAJORHARDWAREBUILDASIS" ON MAJORHARDWAREBUILDASIS ("MAJORHARDWAREBUILDASISID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE MAJORHARDWAREBUILDASIS MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE MAJORHARDWAREBUILDASIS MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE MAJORHARDWAREBUILDASIS MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE MAJORHARDWAREBUILDASIS MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE MAJORHARDWAREBUILDASIS ADD CONSTRAINT "PK_MAJORHARDWAREBUILDASIS" PRIMARY KEY ("MAJORHARDWAREBUILDASISID")
USING INDEX "PK_MAJORHARDWAREBUILDASIS"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE MAJORHARDWAREBUILDASIS ADD CONSTRAINT "FK_MAJORHARDWAREASIS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE MAJORHARDWAREBUILDASIS ADD CONSTRAINT "FK_MAJORHARDWAREASIS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;	
	   
ALTER TABLE "MAJORHARDWAREBUILDASIS" ADD CONSTRAINT "FK_MAJORHARDWAREBUILDASIS_PLATFORMS_PLATFORMID" FOREIGN KEY ("PLATFORMID")
	  REFERENCES "PLATFORMS" ("PLATFORMID") ENABLE;
  
ALTER TABLE "MAJORHARDWAREBUILDASIS" ADD CONSTRAINT "FK_MAJORHARDWAREBUILDASIS_ORIGINALEQUIPMENTMANUFACTURERS_ORIGINALEQUIPMENTMANUFACTURERID" FOREIGN KEY ("ORGEQPMANUFACTURERID")
REFERENCES "ORIGINALEQUIPMENTMANUFACTURERS" ("ORGEQPMANUFACTURERID") ENABLE;
	  
ALTER TABLE "MAJORHARDWAREBUILDASIS" ADD CONSTRAINT "FK_MAJORHARDWAREBUILDASIS_BUILDCONSTRUCTIONS_BUILDCONSTRUCTIONID" FOREIGN KEY ("BUILDCONSTRUCTIONID")
REFERENCES "BUILDCONSTRUCTIONS" ("BUILDCONSTRUCTIONID") ENABLE;
	  
ALTER TABLE "MAJORHARDWAREBUILDASIS" ADD CONSTRAINT "FK_MAJORHARDWAREBUILDASIS_HARDWARESOLUTIONRESOURCE_HARDWARESOLUTIONREOURCEID" FOREIGN KEY ("HARDWARESOLUTIONREOURCEID")
REFERENCES "HARDWARESOLUTIONRESOURCE" ("HARDWARESOLUTIONRESOURCEID") ENABLE;
-------------------------------------------	  
	  
ALTER TABLE ASSETHARDWAREANCILLARY ADD   MAJORHARDWAREBUILDASISID  NUMBER(19);
ALTER TABLE ASSETHARDWAREANCILLARY ADD CONSTRAINT "FK_ASSETHARDWAREANCILLARY_MAJORHARDWAREBUILDASIS_MAJORHARDWAREBUILDASISID"
FOREIGN KEY ("MAJORHARDWAREBUILDASISID")  REFERENCES "MAJORHARDWAREBUILDASIS" ("MAJORHARDWAREBUILDASISID") ENABLE;  
 
ALTER TABLE ASSETHARDWAREANCILLARY DROP COLUMN  MAJORHARDWAREID  ;
 