--------------------------------------------------------
--  DDL FOR TABLE ASSETMAPINFO_SEQ
--------------------------------------------------------

CREATE SEQUENCE "ASSETMAPINFO_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE ASSETOMCINTEGRATION 
---------------------------------------


CREATE TABLE "ASSETMAPINFO" 
(	"ASSETMAPINFOID" NUMBER(19,0) DEFAULT "ASSETMAPINFO_SEQ"."NEXTVAL", 
	"OMCASSETNAME" NVARCHAR2(250),
	"TEMSASSETNAME" NVARCHAR2(250),
	"ENMASSETNAME" NVARCHAR2(250),
	"SITE" NVARCHAR2(250),
	"DATASOURCENAME" NVARCHAR2(250),	
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
  
  --------------------------------------------------------
--  DDL FOR INDEX PK_ASSETMAPINFO
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_ASSETMAPINFO" ON "ASSETMAPINFO" ("ASSETMAPINFOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE ASSETMAPINFO
--------------------------------------------------------
 
  ALTER TABLE "ASSETMAPINFO" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASSETMAPINFO" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASSETMAPINFO" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASSETMAPINFO" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASSETMAPINFO" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "ASSETMAPINFO" ADD CONSTRAINT "PK_ASSETMAPINFO" PRIMARY KEY ("ASSETMAPINFOID") USING INDEX "PK_ASSETMAPINFO"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE ASSETMAPINFO
--------------------------------------------------------

  ALTER TABLE "ASSETMAPINFO" ADD CONSTRAINT "FK_ASSETMAPINFO_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "ASSETMAPINFO" ADD CONSTRAINT "FK_ASSETMAPINFO_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  COMMIT;