--------------------------------------------------------
--  DDL FOR TABLE ASSETASISSDIINFO_SEQ
--------------------------------------------------------

CREATE SEQUENCE "ASSETASISSDIINFO_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE ASSETSDIANICILLARYDATA 
---------------------------------------


CREATE TABLE "ASSETASISSDIINFO" 
(	"ASSETASISSDIINFOID" NUMBER(19,0) DEFAULT "ASSETASISSDIINFO_SEQ"."NEXTVAL", 
	"DATASOURCENAME" NVARCHAR2(250),
	"DATASOURCETYPE" NVARCHAR2(250),
	"SWVERSION" NVARCHAR2(250),
	"FIRMWAREVERSION" NVARCHAR2(250),
	"MANUFACTURER" NVARCHAR2(250),
	"MODEL" NVARCHAR2(250),
	"TSRMODEL" NVARCHAR2(250),
	"CREATIONUSER" NUMBER(10,0),
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
	"MODIFICATIONUSER" NUMBER(10,0),
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
	"DELETED" NUMBER(1,0) DEFAULT (0),
	"DELETIONDATE" TIMESTAMP (6)
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
  
  --------------------------------------------------------
--  DDL FOR INDEX PK_ASSETASISSDIINFO
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_ASSETASISSDIINFO" ON "ASSETASISSDIINFO" ("ASSETASISSDIINFOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE ASSETASISSDIINFO
--------------------------------------------------------
 
  ALTER TABLE "ASSETASISSDIINFO" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASSETASISSDIINFO" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASSETASISSDIINFO" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASSETASISSDIINFO" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASSETASISSDIINFO" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "ASSETASISSDIINFO" ADD CONSTRAINT "PK_ASSETASISSDIINFO" PRIMARY KEY ("ASSETASISSDIINFOID") USING INDEX "PK_ASSETASISSDIINFO"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE ASSETASISSDIINFO
--------------------------------------------------------

  ALTER TABLE "ASSETASISSDIINFO" ADD CONSTRAINT "FK_ASSETASISSDIINFO_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "ASSETASISSDIINFO" ADD CONSTRAINT "FK_ASSETASISSDIINFO_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  COMMIT;