--------------------------------------------------------
--  DDL FOR TABLE ASSETASISHWANCILLARYDATA_SEQ
--------------------------------------------------------

CREATE SEQUENCE "ASSETASISHWANCILLARYDATA_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE ASSETASISHWANCILLARYDATA 
---------------------------------------


CREATE TABLE "ASSETASISHWANCILLARYDATA" 
(	"ASSETASISHWANCILLARYDATAID" NUMBER(19,0) DEFAULT "ASSETASISHWANCILLARYDATA_SEQ"."NEXTVAL", 
	"NETWORKELEMENTASISID" NUMBER(19,0),
	"SITE" NVARCHAR2(19),
	"HOST" NVARCHAR2(100),
	"DATASOURCENAME" NVARCHAR2(100),
	"PROVIDER" NVARCHAR2(100),
	"PROVIDERTYPE" NVARCHAR2(100),
	"CONSUMER" NVARCHAR2(100),
	"CONSUMERTYPE" NVARCHAR2(100),
	"CONSUMERROLE" NVARCHAR2(100),
	"CLUSTERNAME" NVARCHAR2(100),
	"PARTNUMBER" NVARCHAR2(100),
	"SYSTEMTYPE" NVARCHAR2(100),
	"MANUFACTURER" NVARCHAR2(100),
	"BIOSVERSION" NVARCHAR2(100),
	"MODEL" NVARCHAR2(100),
	"SKU" NVARCHAR2(100),
	"CPUCAPACITY" NUMBER(10,0),
	"EPHEMERALSTORAGECAPACITY" NUMBER(10,0),
	"MEMORYCAPACITY" NUMBER(10,0),
	"PROCESSORSUMMARYMODEL" NVARCHAR2(100),
	"KUBERNETESNODETYPE" NVARCHAR2(250),
	"MANAGEMENTIP" NVARCHAR2(100),
	"KUBERNETESNODENAME" NVARCHAR2(250),
	"KUBELETVERSION" NVARCHAR2(100),
	"KUBERNETESNODEOS" NVARCHAR2(100),
	"KUBERNETESNODERESOURCETYPE" NVARCHAR2(100),
	"KUBERNETESNODESTATE" NVARCHAR2(100),
	"KUBERNETESNODESTATUSUPDATETIME" TIMESTAMP (6),
	"CHASSISDETAILS" CLOB,
	"CREATIONUSER" NUMBER(10,0),
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
	"MODIFICATIONUSER" NUMBER(10,0),
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
	"DELETED" NUMBER(1,0) DEFAULT (0),
	"DELETIONDATE" TIMESTAMP (6)
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
  
  --------------------------------------------------------
--  DDL FOR INDEX PK_ASSETASISHWANCILLARYDATA
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_ASSETASISHWANCILLARYDATA" ON "ASSETASISHWANCILLARYDATA" ("ASSETASISHWANCILLARYDATAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE ASSETASISHWANCILLARYDATA
--------------------------------------------------------
 
  ALTER TABLE "ASSETASISHWANCILLARYDATA" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASSETASISHWANCILLARYDATA" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASSETASISHWANCILLARYDATA" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASSETASISHWANCILLARYDATA" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASSETASISHWANCILLARYDATA" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "ASSETASISHWANCILLARYDATA" ADD CONSTRAINT "PK_ASSETASISHWANCILLARYDATA" PRIMARY KEY ("ASSETASISHWANCILLARYDATAID") USING INDEX "PK_ASSETASISHWANCILLARYDATA"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE ASSETASISHWANCILLARYDATA
--------------------------------------------------------

  ALTER TABLE "ASSETASISHWANCILLARYDATA" ADD CONSTRAINT "FK_ASSETASISHWANCILLARYDATA_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "ASSETASISHWANCILLARYDATA" ADD CONSTRAINT "FK_ASSETASISHWANCILLARYDATA_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;

  COMMIT;