--------------------------------------------------------
--  DDL FOR TABLE ASSETASISSDISWITCHINFO_SEQ
--------------------------------------------------------

CREATE SEQUENCE "ASSETASISSDISWITCHINFO_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE ASSETASISSDISWITCHINFO 
---------------------------------------


CREATE TABLE "ASSETASISSDISWITCHINFO" 
(	"ASSETASISSDISWITCHINFOID" NUMBER(19,0) DEFAULT "ASSETASISSDISWITCHINFO_SEQ"."NEXTVAL", 
	"DATASOURCENAME" NVARCHAR2(250),
	"SWITCHNAME" NVARCHAR2(250),
	"SWITCHID" NVARCHAR2(250),
	"SWITCHADMINSTATE" NVARCHAR2(250),
	"SWITCHUNIQUEID" NVARCHAR2(250),
	"SWITCHROLE" NVARCHAR2(250),
	"SWITCHRACK" NVARCHAR2(250),
	"SWITCHLABEL" NVARCHAR2(250),
	"SWITCHSERIALNUMBER" NVARCHAR2(250),
	"SWITCHOPSSTATE" NVARCHAR2(250),
	"SWITCHNETWORK" NVARCHAR2(250),
	"SWITCHMANUFACTURER" NVARCHAR2(250),
	"SWITCHMODEL" NVARCHAR2(250),
	"SWITCHIPADDRESS" NVARCHAR2(250),
	"SWITCHSWVERSION" NVARCHAR2(250),
	"CREATIONUSER" NUMBER(10,0),
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
	"MODIFICATIONUSER" NUMBER(10,0),
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
	"DELETED" NUMBER(1,0) DEFAULT (0),
	"DELETIONDATE" TIMESTAMP (6)
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
  
  --------------------------------------------------------
--  DDL FOR INDEX PK_ASSETASISSDISWITCHINFO
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_ASSETASISSDISWITCHINFO" ON "ASSETASISSDISWITCHINFO" ("ASSETASISSDISWITCHINFOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE ASSETASISSDISWITCHINFO
--------------------------------------------------------
 
  ALTER TABLE "ASSETASISSDISWITCHINFO" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASSETASISSDISWITCHINFO" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASSETASISSDISWITCHINFO" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "ASSETASISSDISWITCHINFO" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "ASSETASISSDISWITCHINFO" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "ASSETASISSDISWITCHINFO" ADD CONSTRAINT "PK_ASSETASISSDISWITCHINFO" PRIMARY KEY ("ASSETASISSDISWITCHINFOID") USING INDEX "PK_ASSETASISSDISWITCHINFO"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE ASSETASISSDISWITCHINFO
--------------------------------------------------------

  ALTER TABLE "ASSETASISSDISWITCHINFO" ADD CONSTRAINT "FK_ASSETASISSDISWITCHINFO_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "ASSETASISSDISWITCHINFO" ADD CONSTRAINT "FK_ASSETASISSDISWITCHINFO_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  COMMIT;