-------ALTER SCRIPT FOR PASSTHROUGH LCM ------
ALTER TABLE PASSTHROUGHLCM MODIFY NOTES NVARCHAR2(2000);
COMMIT;

-------UPDATE SCRIPT FOR EXCELTEMPLATECONFIGURATION------
UPDATE EXCELTEMPLATECONFIGURATION SET COLUMNHEADERNAME = UNISTR('N\00B0 Nodes') WHERE PROCESSNAME ='PassThroughLcmSoftware' and PROPERTYNAME = 'numberOfNodes';
UPDATE EXCELTEMPLATECONFIGURATION SET COLUMNHEADERNAME = UNISTR('N\00B0 Nodes') WHERE PROCESSNAME ='PassThroughLcmHardware' and PROPERTYNAME = 'numberOfNodes';
commit;