--------------------- ALTER SCRIPTS FOR ASPNETROLES ------------------------
ALTER TABLE ASPNETROLES ADD	"CREATIONUSER" NUMBER(10,0);
ALTER TABLE ASPNETROLES ADD	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC (SYSTIMESTAMP); 
ALTER TABLE ASPNETROLES ADD	"MODIFICATIONUSER" NUMBER(10,0); 
ALTER TABLE ASPNETROLES ADD	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC (SYSTIMESTAMP);
ALTER TABLE ASPNETROLES ADD	"DELETED" NUMBER(1,0) DEFAULT (0); 
ALTER TABLE ASPNETROLES ADD	"DELETIONDATE" TIMESTAMP (6);

UPDATE ASPNETROLES SET CREATIONUSER = 1 WHERE CREATIONUSER IS NULL;
UPDATE ASPNETROLES SET MODIFICATIONUSER = 1 WHERE MODIFICATIONUSER IS NULL;
COMMIT;

ALTER TABLE "ASPNETROLES" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "ASPNETROLES" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "ASPNETROLES" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "ASPNETROLES" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "ASPNETROLES" MODIFY ("DELETED" NOT NULL ENABLE);
  
ALTER TABLE "ASPNETROLES" ADD CONSTRAINT "FK_ASPNETROLES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "ASPNETROLES" ADD CONSTRAINT "FK_ASPNETROLES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
