--------------------------CLUSTERUPGRADESTATUS--------------------------------
ALTER TABLE CLUSTERUPGRADESTATUS ADD "HARDWARETYPE" NUMBER(19,0) DEFAULT NULL;
ALTER TABLE "CLUSTERUPGRADESTATUS" ADD CONSTRAINT "FK_CLUSTERUPGRADESTATUS_MAJORHARDWAREBUILDS_HARDWARETYPE" FOREIGN KEY ("HARDWARETYPE") REFERENCES "MAJORHARDWAREBUILDS" ("MAJORHARDWAREID") ENABLE;


