--------------------------------------------------------
--  DDL FOR TABLE SERVICEPLANDCFMAPPING_SEQ
--------------------------------------------------------

CREATE SEQUENCE "SERVICEPLANDCFMAPPING_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE SERVICEPLANDCFMAPPINGS 
---------------------------------------


CREATE TABLE "SERVICEPLANDCFMAPPINGS" 
(	"SERVICEPLANDCFMAPPINGID" NUMBER(10,0) DEFAULT "SERVICEPLANDCFMAPPING_SEQ"."NEXTVAL",
	"SERVICEPLANID" NUMBER(10,0),
	"DCFID" NUMBER(19,0),
	"STATUS" NUMBER(5,0),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
	) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
  
  --------------------------------------------------------
--  DDL FOR INDEX PK_SERVICEPLANDCFMAPPINGS
-------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_SERVICEPLANDCFMAPPINGS" ON "SERVICEPLANDCFMAPPINGS" ("SERVICEPLANDCFMAPPINGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE SERVICEPLANDCFMAPPINGS
--------------------------------------------------------
 
  ALTER TABLE "SERVICEPLANDCFMAPPINGS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "SERVICEPLANDCFMAPPINGS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "SERVICEPLANDCFMAPPINGS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "SERVICEPLANDCFMAPPINGS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "SERVICEPLANDCFMAPPINGS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "SERVICEPLANDCFMAPPINGS" ADD CONSTRAINT "PK_SERVICEPLANDCFMAPPINGS" PRIMARY KEY ("SERVICEPLANDCFMAPPINGID") USING INDEX "PK_SERVICEPLANDCFMAPPINGS"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE SERVICEPLANDCFMAPPINGS
--------------------------------------------------------

  ALTER TABLE "SERVICEPLANDCFMAPPINGS" ADD CONSTRAINT "FK_SERVICEPLANDCFMAPPINGS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "SERVICEPLANDCFMAPPINGS" ADD CONSTRAINT"FK_SERVICEPLANDCFMAPPINGS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "SERVICEPLANDCFMAPPINGS" ADD CONSTRAINT"FK_SERVICEPLANDCFMAPPINGS_SERVICEPLAN_SERVICEPLANID" FOREIGN KEY ("SERVICEPLANID") REFERENCES "SERVICEPLAN" ("SERVICEPLANID") ENABLE;
  ALTER TABLE "SERVICEPLANDCFMAPPINGS" ADD CONSTRAINT"FK_SERVICEPLANDCFMAPPINGS_DESIGNCOMPONENTFAMILIES_DESIGNCOMPONENTFAMILYID" FOREIGN KEY ("DCFID") REFERENCES "DESIGNCOMPONENTFAMILIES" ("DESIGNCOMPONENTFAMILYID") ENABLE;
  
  COMMIT;