CREATE TABLE SERVICEPLAN_BACKUP AS SELECT * FROM SERVICEPLAN;

COMMIT;

ALTER TABLE SERVICEPLAN DROP COLUMN DESIGNCOMPONENTFAMILYID;
ALTER TABLE SERVICEPLAN DROP COLUMN STATUS;
ALTER TABLE SERVICEPLAN DROP COLUMN PLANNEDACTIVITYID;

ALTER TABLE SERVICEPLAN ADD OPCOID NUMBER(5,0);

ALTER TABLE "SERVICEPLAN" ADD CONSTRAINT "FK_SERVICEPLAN_OPCOS_OPCOID" FOREIGN KEY ("OPCOID") REFERENCES "OPCOS" ("OPCOID") ENABLE;

ALTER TABLE PLANNEDACTIVITIES ADD SERVICEPLANID NUMBER(10,0);
ALTER TABLE "PLANNEDACTIVITIES" ADD CONSTRAINT "FK_PLANNEDACTIVITIES_SERVICEPLAN_SERVICEPLANID" FOREIGN KEY ("SERVICEPLANID") REFERENCES "SERVICEPLAN" ("SERVICEPLANID") ENABLE;