--ALTER TABLE VERTICALRESPONSIBLES MODIFY VERTICALRESPONSIBLE VARCHAR2(100);

ALTER TABLE VERTICALRESPONSIBLES RENAME COLUMN VERTICALRESPONSIBLE TO VERTICALRESPONSIBLETEMP;
ALTER TABLE VERTICALRESPONSIBLES Add VERTICALRESPONSIBLE VARCHAR2(100);
UPDATE VERTICALRESPONSIBLES SET VERTICALRESPONSIBLE=VERTICALRESPONSIBLETEMP;
ALTER TABLE VERTICALRESPONSIBLES DROP COLUMN VERTICALRESPONSIBLETEMP;
COMMIT;


ALTER TABLE SUBDOMAINRESPONSIBLES RENAME COLUMN SUBDOMAINRESPONSIBLE TO SUBDOMAINRESPONSIBLETEMP;
ALTER TABLE SUBDOMAINRESPONSIBLES Add SUBDOMAINRESPONSIBLE VARCHAR2(100);
UPDATE SUBDOMAINRESPONSIBLES SET SUBDOMAINRESPONSIBLE=SUBDOMAINRESPONSIBLETEMP;
ALTER TABLE SUBDOMAINRESPONSIBLES DROP COLUMN SUBDOMAINRESPONSIBLETEMP;
COMMIT;