--------ALTER SCRIPT FOR PA AND SETTINGSUPDATEPLANNEDACTIVITY-------------------
ALTER TABLE SETTINGSUPDATEPLANNEDACTIVITY ADD ISMILESTONE NUMBER(1,0) DEFAULT 0; 

UPDATE SETTINGSUPDATEPLANNEDACTIVITY SET ISMILESTONE = 0;
COMMIT;

ALTER TABLE PLANNEDACTIVITIES ADD PREBASELINEDATE TIMESTAMP (6);

--------ALTER SCRIPT FOR PROJECTSPLAN-------------------
ALTER TABLE PROJECTSPLAN ADD BASELINESTARTDATE TIMESTAMP (6);
ALTER TABLE PROJECTSPLAN ADD BASELINEENDDATE TIMESTAMP (6);

ALTER TABLE PROJECTSPLAN RENAME COLUMN STARTDATE TO PLANNINGSTARTDATE;
ALTER TABLE PROJECTSPLAN RENAME COLUMN ENDDATE TO PLANNINGENDDATE;
