CREATE SEQUENCE MAJORSOFTWAREBUILDNETWORKFUNCTION_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  COMMIT


  --------------------------------------------------------
--  DDL for Table MAJORSOFTWAREBUILDNETWORKFUNCTION
--------------------------------------------------------

  CREATE TABLE "MAJORSOFTWAREBUILDNETWORKFUNCTION" 
   (	"ID" NUMBER(19,0) DEFAULT "MAJORSOFTWAREBUILDNETWORKFUNCTION_SEQ"."NEXTVAL", 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"MAJORSOFTWAREBUILDID" NUMBER(19,0), 
	"NETWORKFUNCTIONID" NUMBER(10,0), 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index MAJORSOFTWAREBUILDNETWORKFUNCTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAJORSOFTWAREBUILDNETWORKFUNCTION_PK" ON "MAJORSOFTWAREBUILDNETWORKFUNCTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table MAJORSOFTWAREBUILDNETWORKFUNCTION
--------------------------------------------------------

  ALTER TABLE "MAJORSOFTWAREBUILDNETWORKFUNCTION" MODIFY ("MAJORSOFTWAREBUILDID" NOT NULL ENABLE);
  ALTER TABLE "MAJORSOFTWAREBUILDNETWORKFUNCTION" MODIFY ("NETWORKFUNCTIONID" NOT NULL ENABLE);
  ALTER TABLE "MAJORSOFTWAREBUILDNETWORKFUNCTION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MAJORSOFTWAREBUILDNETWORKFUNCTION" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "MAJORSOFTWAREBUILDNETWORKFUNCTION" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "MAJORSOFTWAREBUILDNETWORKFUNCTION" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "MAJORSOFTWAREBUILDNETWORKFUNCTION" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "MAJORSOFTWAREBUILDNETWORKFUNCTION" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "MAJORSOFTWAREBUILDNETWORKFUNCTION" ADD CONSTRAINT "MAJORSOFTWAREBUILDNETWORKFUNCTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAJORSOFTWAREBUILDNETWORKFUNCTION
--------------------------------------------------------

  ALTER TABLE "MAJORSOFTWAREBUILDNETWORKFUNCTION" ADD CONSTRAINT "FK_MAJORSOFTWAREBUILDNETWORKFUNCTION_MODIFIEDUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "MAJORSOFTWAREBUILDNETWORKFUNCTION" ADD CONSTRAINT "FK_MAJORSOFTWAREBUILDNETWORKFUNCTION_CREATEUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "MAJORSOFTWAREBUILDNETWORKFUNCTION" ADD CONSTRAINT "MAJORSOFTWAREBUILDNETWORKFUNCTION_FK1" FOREIGN KEY ("MAJORSOFTWAREBUILDID")
	  REFERENCES "MAJORSOFTWAREBUILDS" ("MAJORSOFTWAREBUILDSID") ENABLE;
  ALTER TABLE "MAJORSOFTWAREBUILDNETWORKFUNCTION" ADD CONSTRAINT "MAJORSOFTWAREBUILDNETWORKFUNCTION_FK2" FOREIGN KEY ("NETWORKFUNCTIONID")
	  REFERENCES "NETWORKFUNCTIONS" ("ID") ENABLE;

  
   ALTER TABLE MAJORSOFTWAREBUILDNETWORKFUNCTION
MODIFY(ID  DEFAULT "MAJORSOFTWAREBUILDNETWORKFUNCTION_SEQ"."NEXTVAL");
COMMIT



drop table designcomponentfamilynetworkfunction

ALTER TABLE majorsoftwarebuilds
Add "DESCRIPTION" NVARCHAR2(2000) DEFAULT (null) NULL ;
commit;