delete gridcustomcolumn where classname ='UserPreferenceDto' ;
Commit;

--------BACKUP SCRIPT FOR ASPNETUSERPREFERENCES---------------
CREATE TABLE ASPNETUSERPREFERENCES_BACKUP AS
SELECT *
FROM ASPNETUSERPREFERENCES;
--------DELETION SCRIPT FOR THE ASPNETUSERPREFERENCES-----------
DELETE FROM ASPNETUSERPREFERENCES;
Commit;