ALTER TABLE LCMANCILLARYDATA ADD ISPECN NUMBER(1,0) DEFAULT 0;
ALTER TABLE LCMANCILLARYDATA ADD ISPECS NUMBER(1,0) DEFAULT 0;
ALTER TABLE LCMANCILLARYDATA ADD ISSCF NUMBER(1,0) DEFAULT 0;
ALTER TABLE LCMANCILLARYDATA ADD ISNOF NUMBER(1,0) DEFAULT 0;

UPDATE LCMANCILLARYDATA
SET ISPECN = CASE 
WHEN LOWER(REGULATORYFIELDS) LIKE '%pecn%' THEN '1'
ELSE '0'
END,
ISPECS = CASE 
WHEN LOWER(REGULATORYFIELDS) LIKE '%pecs%' THEN '1'
ELSE '0'
END,
ISSCF = CASE 
WHEN LOWER(REGULATORYFIELDS) LIKE '%scf%' THEN '1'
ELSE '0'
END,
ISNOF = CASE 
WHEN LOWER(REGULATORYFIELDS) LIKE '%nof%' THEN '1'
ELSE '0'
END;
			 
ALTER TABLE LCMANCILLARYDATA DROP COLUMN REGULATORYFIELDS;


COMMIT;

