--------------------------------------------------------
--  DDL FOR TABLE TSRPASSTHROUGH_SEQ
--------------------------------------------------------

CREATE SEQUENCE "NETWORKELEMENTASPLANNEDPASSTHROUGH_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;

--------------------------------------------------------
--  DDL FOR TABLE NETWORKELEMENTPASSTHROUGH
--------------------------------------------------------
CREATE TABLE NETWORKELEMENTASPLANNEDPASSTHROUGH (
    "NETWORKELEMENTASPLANNEDPASSTHROUGHID" NUMBER(19, 0) DEFAULT "NETWORKELEMENTASPLANNEDPASSTHROUGH_SEQ"."NEXTVAL",
    "ELEMENTNAME" NVARCHAR2(50),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)	
) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_COMPONENTSOFTWAREBUILDBAGS
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_NETWORKELEMENTASPLANNEDPASSTHROUGH" ON "NETWORKELEMENTASPLANNEDPASSTHROUGH" ("NETWORKELEMENTASPLANNEDPASSTHROUGHID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE NETWORKELEMENTASPLANNEDPASSTHROUGH
--------------------------------------------------------
 
  ALTER TABLE "NETWORKELEMENTASPLANNEDPASSTHROUGH" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "NETWORKELEMENTASPLANNEDPASSTHROUGH" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "NETWORKELEMENTASPLANNEDPASSTHROUGH" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "NETWORKELEMENTASPLANNEDPASSTHROUGH" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "NETWORKELEMENTASPLANNEDPASSTHROUGH" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "NETWORKELEMENTASPLANNEDPASSTHROUGH" ADD CONSTRAINT "PK_NETWORKELEMENTASPLANNEDPASSTHROUGH" PRIMARY KEY ("NETWORKELEMENTASPLANNEDPASSTHROUGHID") USING INDEX "PK_NETWORKELEMENTASPLANNEDPASSTHROUGH"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE NETWORKELEMENTASPLANNEDPASSTHROUGH
--------------------------------------------------------

  ALTER TABLE "NETWORKELEMENTASPLANNEDPASSTHROUGH" ADD CONSTRAINT "FK_NETWORKELEMENTASPLANNEDPASSTHROUGH_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "NETWORKELEMENTASPLANNEDPASSTHROUGH" ADD CONSTRAINT "FK_NETWORKELEMENTASPLANNEDPASSTHROUGH_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  COMMIT;