ALTER TABLE "SETTINGSUPDATEPLANNEDACTIVITY" ADD "MILESTONESTAUS" NUMBER(10,0) DEFAULT 0;
ALTER TABLE "SETTINGSUPDATEPLANNEDACTIVITY" ADD "MILESTONESTATUSDURATION" NUMBER(10,0) DEFAULT 0;

DELETE GRIDCUSTOMCOLUMN WHERE CLASSNAME IN ('SettingsUpdatePlannedActivityDtoGrid');


COMMIT;