--------------------------------------------------------
--  DDL FOR TABLE TSRPASSTHROUGH_SEQ
--------------------------------------------------------

CREATE SEQUENCE "TSRPASSTHROUGH_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
COMMIT;
---------------------------------------
--  DDL FOR TABLE TSRPASSTHROUGH 
---------------------------------------
CREATE TABLE TSRPASSTHROUGH
(
	"TSRPASSTHROUGHID" NUMBER(19,0) DEFAULT "TSRPASSTHROUGH_SEQ"."NEXTVAL",
	"ASSETID" NVARCHAR2(250), 
	"VODAFONEUNIQUEIDENTIFIER" NVARCHAR2(50),
	"ASSETNAME" NVARCHAR2(250),
	"ASSETDESCRIPTIONORPURPOSE" NVARCHAR2(2000),
	"ASSETTYPE" NVARCHAR2(50),
	"BUSINESSOWNER" NVARCHAR2(250),
	"SUPPORTOWNER" NVARCHAR2(250),
	"SUPPORTTEAM" NVARCHAR2(250),
	"SUPPORTTEAMSPLACEINTHEORGANISATION" NVARCHAR2(250),
	"ASSETFUNCTION" NVARCHAR2(250),
	"DEPLOYMENTORLIFECYCLESTATUS" NVARCHAR2(250),
	"RELATEDRISKIDSFROMRISKREGISTERS" NVARCHAR2(250),
	"REGULATORYSCOPE" NVARCHAR2(50),
	"COUNTRYWHEREASSETISLOCATED" NVARCHAR2(50),
	"GEOLOCATION" NVARCHAR2(250),
	"INFRASTRUCTURE" NVARCHAR2(250),
	"UPSTREAMDEPENDENCIES" NVARCHAR2(2000),
	"DOWNSTREAMDEPENDENCIES" NVARCHAR2(2000),
	"CHANGESTOTHEASSETSINCEDEPLOYMENT" NVARCHAR2(50),
	"CLOUDHOSTEDASSET" NVARCHAR2(50),
	"CLOUDTYPE" NVARCHAR2(50),
	"CLOUDVENDOR" NVARCHAR2(50),
	"EQUIPMENTNAME" NVARCHAR2(250),
	"HOSTLOCATIONWITHINPHYSICALLOCATION" NVARCHAR2(50),
	"SOFTWAREVENDORNAME" NVARCHAR2(250),
	"MODEL" NVARCHAR2(50),
	"FIRMWAREVERSION" NVARCHAR2(50),
	"FIRMWAREVERSIONPATCHLEVEL" NVARCHAR2(50),
	"MAINTENANCESUPPORTSUPPLIER" NVARCHAR2(250),
	"VENDORHARDWAREENDOFSUPPORTDATE" TIMESTAMP (6),
	"MAINTENANCEHARDWAREENDOFSUPPORTDATE" TIMESTAMP (6),
	"DEPENDANTHARDWARE" NVARCHAR2(250),
	"INSTANCETYPE" NVARCHAR2(50),
	"OPERATINGSYSTEMNAME" NVARCHAR2(50),
	"OPERATINGSYSTEMSWVVERSION" NVARCHAR2(50),
	"OPERATINGSYSTEMSWVERSIONPATCHLEVEL" NVARCHAR2(50),
	"SYSTEMNAMEDNS" NVARCHAR2(50),
	"SYSTEMNAMEMANAGEMENTIPADDRESS" NVARCHAR2(250),
	"SYSTEMNAMENETBIOS" NVARCHAR2(50),
	"SYSTEMNAMEHOSTNAME" NVARCHAR2(50),
	"DATEASSETMOVEDTOLIVESTATUS" TIMESTAMP (6),
	"DATEASSETDECOMMISSIONED" TIMESTAMP (6),
	"HARDWAREVENDORNAME" NVARCHAR2(250),
	"MAINTENANCESUPPORTSUPPLIERSECOND" NVARCHAR2(250),
	"VENDORSOFTWAREENDOFSUPPORTDATE" TIMESTAMP (6),
	"MAINTENANCESOFTWAREENDOFSUPPORTDATE" TIMESTAMP (6),
	"DEPENDANTSYSTEMSOFTWARE" NVARCHAR2(50),
	"RESILIENCEMODEL" NVARCHAR2(50),
	"GEOGRAPHICSITERESILIENCE" NVARCHAR2(50),
	"LOCALSITERESILIENCE" NVARCHAR2(50),
	"NAMEOFPRODUCTSDEPENDANTONASSET" NVARCHAR2(250),
	"TECHNICALSERVICENAMES" NVARCHAR2(50),
	"CUSTOMER" NVARCHAR2(250),
	"PRIVILEGEDACCESSLOGGING" NVARCHAR2(50),
	"BOARDORMODULENAMECOMPONENTNAME" NVARCHAR2(2000),
	"BOARDORMODULETYPECOMPONENTSUBTYPE" NVARCHAR2(250),
	"BOARDORMODULETYPECOMPONENTVERSIONNUMBER" NVARCHAR2(250),
	"EXPOSEDEDGE" NVARCHAR2(50),
	"EXTERNALLYFACINGSYSTEM" NVARCHAR2(50),
	"MANAGEMENTPLANE" NVARCHAR2(50),
	"NETWORKOVERSIGHTFUNCTION" NVARCHAR2(50),
	"PECN" NVARCHAR2(50),
	"PECS" NVARCHAR2(50),
	"SECURITYCRITICALFUNCTION" NVARCHAR2(50),
	"PRODUCTIMPORTANCE" NVARCHAR2(50),
	"CRITICAL" NVARCHAR2(50),
	"CRITICALITYTYPE" NVARCHAR2(50),
	"SERIALNUMBER" NVARCHAR2(250),
	"PARTNUMBER" NVARCHAR2(50),
	"DESCRIPTIONOFPLANNEDACTION" NVARCHAR2(250),
	"IDENTIFIEDACTION" NVARCHAR2(50),
	"LASTUPGRADEDATE" TIMESTAMP (6),
	"PRODORLAB" NVARCHAR2(50),
	"LOCALMARKETOWNERSHIP" NVARCHAR2(50),
	"BUDGETESTIMATED" NVARCHAR2(50),
	"BUNDLEBUDGET" NVARCHAR2(50),
	"ASSURANCECALL" NVARCHAR2(250),
	"COMMENTONPROJECTSTATUS" NVARCHAR2(2000),
	"PROJECTENDDATE" TIMESTAMP (6),
	"PROJECTSTATUS" NVARCHAR2(50),
	"SERVICELEVEL" NVARCHAR2(50),
	"LASTPENTESTDATE" TIMESTAMP (6),
	"LASTPENTESTREFNO" TIMESTAMP (6),
	"PIDATA" NVARCHAR2(50),
	"ENCRYPTEDPIDATA" NVARCHAR2(50),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_COMPONENTSOFTWAREBUILDBAGS
--------------------------------------------------------
 
  CREATE UNIQUE INDEX "PK_TSRPASSTHROUGH" ON "TSRPASSTHROUGH" ("TSRPASSTHROUGHID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE TSRPASSTHROUGH
--------------------------------------------------------
 
  ALTER TABLE "TSRPASSTHROUGH" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "TSRPASSTHROUGH" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "TSRPASSTHROUGH" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "TSRPASSTHROUGH" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "TSRPASSTHROUGH" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "TSRPASSTHROUGH" ADD CONSTRAINT "PK_TSRPASSTHROUGH" PRIMARY KEY ("TSRPASSTHROUGHID") USING INDEX "PK_TSRPASSTHROUGH"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE TSRPASSTHROUGH
--------------------------------------------------------

  ALTER TABLE "TSRPASSTHROUGH" ADD CONSTRAINT "FK_TSRPASSTHROUGH_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "TSRPASSTHROUGH" ADD CONSTRAINT "FK_TSRPASSTHROUGH_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  COMMIT;