
ALTER TABLE LCMENGINEERING
	ADD "FULLORPARTIALSUPPORTHWID" NUMBER(5,0);


  ALTER TABLE "CAMSDBUSER"."LCMENGINEERING" ADD CONSTRAINT "FK_LCMENGINEERING_FULLORPARTIALRESOURCE_FULLORPARTIALHWSUPPORTID" FOREIGN KEY ("FULLORPARTIALSUPPORTHWID")
	  REFERENCES "CAMSDBUSER"."FULLORPARTIALRESOURCE" ("ID") ENABLE;