ALTER TABLE SUBNETWORKBOUNDARIES
Add "GDPRRELEVANT" Number(1,0) DEFAULT (null) NULL ;
commit;

ALTER TABLE SUBNETWORKBOUNDARIES
Add "INTERNETFACING" Number(1,0) DEFAULT (0) NULL ;
commit;

ALTER TABLE SUBNETWORKBOUNDARIES
Add "LCMPOLICY" NUMBER(5,0) DEFAULT (1) NULL ;
commit;

ALTER TABLE SUBNETWORKBOUNDARIES
Add "CRITICALITY" NVARCHAR2(2000) DEFAULT (null) NULL ;
commit;

ALTER TABLE SUBNETWORKBOUNDARIES
Add "SECURITYELEMENT" Number(1,0) DEFAULT (0) NULL;
commit

ALTER TABLE SUBNETWORKBOUNDARIES
Add "GDPRCLASSIFICATION" Number(10,0)  NULL  ;

ALTER TABLE SUBNETWORKBOUNDARIES
Add "PCI/SOX" Number(1,0) DEFAULT (0)  NULL	  ;

ALTER TABLE SUBNETWORKBOUNDARIES
Add "C3/C4" Number(1,0) DEFAULT (0) NULL ;


ALTER TABLE SUBNETWORKBOUNDARIES
Add "MISSIONCRITICAL" Number(1,0) DEFAULT (0) NULL ;


ALTER TABLE SUBNETWORKBOUNDARIES 
Add "CRITICALASSETTYPEID" Number(10,0) NULL;
commit

ALTER TABLE "CAMSDBUSER"."SUBNETWORKBOUNDARIES" ADD CONSTRAINT "FK_SUBNETWORKBOUNDARIES_CRITICALASSETTYPES_ID" FOREIGN KEY ("CRITICALASSETTYPEID")
REFERENCES "CAMSDBUSER"."CRITICALASSETTYPES" ("ID") ENABLE;



--------------------------------------------------------
--  DDL for Table SUBNETWROKBOUNDARYSYSTEMFUNCTION
--------------------------------------------------------
CREATE SEQUENCE SUBNETWORKBOUNDARYSYSTEMFUNCTION_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

  CREATE TABLE "CAMSDBUSER"."SUBNETWROKBOUNDARYSYSTEMFUNCTION" 
   (	"ID" NUMBER(19,0) DEFAULT "CAMSDBUSER"."SUBNETWORKBOUNDARYSYSTEMFUNCTION_SEQ"."NEXTVAL", 
	"SUBNETWROKBOUNDARYID" NUMBER(19,0), 
	"SYSTEMFUNCTIONID" NUMBER(5,0), 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (null), 
	"DELETEDDATE" TIMESTAMP (6) DEFAULT (null)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index SUBNETWROKBOUNDARYSYSTEMFUNCTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMSDBUSER"."SUBNETWROKBOUNDARYSYSTEMFUNCTION_PK" ON "CAMSDBUSER"."SUBNETWROKBOUNDARYSYSTEMFUNCTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table SUBNETWROKBOUNDARYSYSTEMFUNCTION
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."SUBNETWROKBOUNDARYSYSTEMFUNCTION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."SUBNETWROKBOUNDARYSYSTEMFUNCTION" MODIFY ("SUBNETWROKBOUNDARYID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."SUBNETWROKBOUNDARYSYSTEMFUNCTION" ADD CONSTRAINT "SUBNETWROKBOUNDARYSYSTEMFUNCTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBNETWROKBOUNDARYSYSTEMFUNCTION
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."SUBNETWROKBOUNDARYSYSTEMFUNCTION" ADD CONSTRAINT "FK_SUBNETWROKBOUNDARYSYSTEMFUNCTION_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."SUBNETWROKBOUNDARYSYSTEMFUNCTION" ADD CONSTRAINT "FK_SUBNETWROKBOUNDARYSYSTEMFUNCTION_SUBNETWORKBOUNDARY_SUBNETWORKBOUNDARYID" FOREIGN KEY ("SUBNETWROKBOUNDARYID")
	  REFERENCES "CAMSDBUSER"."SUBNETWORKBOUNDARIES" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."SUBNETWROKBOUNDARYSYSTEMFUNCTION" ADD CONSTRAINT "FK_SUBNETWROKBOUNDARYSYSTEMFUNCTION_SYSTEMFUNCTIONS_SYSTEMFUNCTIONID" FOREIGN KEY ("SYSTEMFUNCTIONID")
	  REFERENCES "CAMSDBUSER"."SYSTEMFUNCTIONS" ("SYSTEMFUNCTIONID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."SUBNETWROKBOUNDARYSYSTEMFUNCTION" ADD CONSTRAINT "FK_SUBNETWROKBOUNDARYSYSTEMFUNCTION_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;


ALTER TABLE CAMSDBUSER.SUBNETWROKBOUNDARYSYSTEMFUNCTION
MODIFY(ID  DEFAULT "CAMSDBUSER"."SUBNETWORKBOUNDARYSYSTEMFUNCTION_SEQ"."NEXTVAL");

COMMIT;


CREATE SEQUENCE SUBNETWORKBOUNDARYCUSTOMERWHEEL_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
  --------------------------------------------------------
--  DDL for Table SUBNETWORKBOUNDARYCUSTOMERWHEEL
--------------------------------------------------------

 --------------------------------------------------------
--  DDL for Table SUBNETWORKBOUNDARYCUSTOMERWHEEL
--------------------------------------------------------

  CREATE TABLE "CAMSDBUSER"."SUBNETWORKBOUNDARYCUSTOMERWHEEL" 
   (	"ID" NUMBER(19,0) DEFAULT "CAMSDBUSER"."SUBNETWORKBOUNDARYCUSTOMERWHEEL_SEQ"."NEXTVAL", 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0), 
	"DELETIONDATE" TIMESTAMP (6), 
	"SUBNETWORKBOUNDARYID" NUMBER(19,0), 
	"CUSTOMERWHEELID" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index SUBNETWORKBOUNDARYCUSTOMERWHEEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMSDBUSER"."SUBNETWORKBOUNDARYCUSTOMERWHEEL_PK" ON "CAMSDBUSER"."SUBNETWORKBOUNDARYCUSTOMERWHEEL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table SUBNETWORKBOUNDARYCUSTOMERWHEEL
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."SUBNETWORKBOUNDARYCUSTOMERWHEEL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."SUBNETWORKBOUNDARYCUSTOMERWHEEL" ADD CONSTRAINT "SUBNETWORKBOUNDARYCUSTOMERWHEEL_PK" PRIMARY KEY ("ID")
  USING INDEX "CAMSDBUSER"."SUBNETWORKBOUNDARYCUSTOMERWHEEL_PK"  ENABLE;
  ALTER TABLE "CAMSDBUSER"."SUBNETWORKBOUNDARYCUSTOMERWHEEL" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."SUBNETWORKBOUNDARYCUSTOMERWHEEL" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."SUBNETWORKBOUNDARYCUSTOMERWHEEL" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "CAMSDBUSER"."SUBNETWORKBOUNDARYCUSTOMERWHEEL" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SUBNETWORKBOUNDARYCUSTOMERWHEEL
--------------------------------------------------------

  ALTER TABLE "CAMSDBUSER"."SUBNETWORKBOUNDARYCUSTOMERWHEEL" ADD CONSTRAINT "FK_SUBNETWORKBOUNDARYCUSTOMERWHEEL_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."SUBNETWORKBOUNDARYCUSTOMERWHEEL" ADD CONSTRAINT "FK_SUBNETWORKBOUNDARYCUSTOMERWHEEL_CUSTOMERWHEELS_CUSTOMERWHEELID" FOREIGN KEY ("CUSTOMERWHEELID")
	  REFERENCES "CAMSDBUSER"."CUSTOMERWHEELS" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."SUBNETWORKBOUNDARYCUSTOMERWHEEL" ADD CONSTRAINT "FK_SUBNETWORKBOUNDARYCUSTOMERWHEEL_SUBNETWORKBOUNDARIES_SUBNETWORKBOUNDARYID" FOREIGN KEY ("SUBNETWORKBOUNDARYID")
	  REFERENCES "CAMSDBUSER"."SUBNETWORKBOUNDARIES" ("ID") ENABLE;
  ALTER TABLE "CAMSDBUSER"."SUBNETWORKBOUNDARYCUSTOMERWHEEL" ADD CONSTRAINT "SUBNETWORKBOUNDARYCUSTOMERWHEEL_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "CAMSDBUSER"."ASPNETUSERS" ("ID") ENABLE;

	  
ALTER TABLE CAMSDBUSER.SUBNETWORKBOUNDARYCUSTOMERWHEEL
MODIFY(ID  DEFAULT "CAMSDBUSER"."SUBNETWORKBOUNDARYCUSTOMERWHEEL_SEQ"."NEXTVAL");

COMMIT;


--------------------------------------------------------------------------------------------------------