-------------- CREATE UNIQUE KEY -COLUMN REPORTID IN PASSTHROUGHLCM TABLE
ALTER TABLE PASSTHROUGHLCM ADD CONSTRAINT UK_REPORTID UNIQUE (REPORTID);

-------------- IN PASSTHROUGH TABLE -DELETE RECORD IN WHICH VODAFONEUNIQUEIDENTIFIER HAS NO MATCHING DATA IN PASSTHROUGHLCM TABLE 
DELETE FROM PASSTHROUGH WHERE VODAFONEUNIQUEIDENTIFIER NOT IN (
SELECT distinct P.VODAFONEUNIQUEIDENTIFIER FROM PASSTHROUGH P INNER JOIN PASSTHROUGHLCM PL ON P.VODAFONEUNIQUEIDENTIFIER =PL.REPORTID);

-------------- CREATE FOREIGN KEY -COLUMN VODAFONEUNIQUEIDENTIFIER IN PASSTHROUGH TABLE
ALTER TABLE PASSTHROUGH
ADD CONSTRAINT "FK_PASSTHROUGH_PASSTHROUGHLCM_VODAFONEUNIQUEIDENTIFIER"
FOREIGN KEY ("VODAFONEUNIQUEIDENTIFIER")
REFERENCES "PASSTHROUGHLCM"(REPORTID)ENABLE;
COMMIT;