CREATE TABLE PLANNEDACTIVITYTYPES_BACKUP AS SELECT * FROM PLANNEDACTIVITYTYPES;

DROP SEQUENCE PLANNEDACTIVITYTYPESID_SEQ;

CREATE SEQUENCE  "PLANNEDACTIVITYTYPESID_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999 
INCREMENT BY 1 START WITH  21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPESID","PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT" ) 
VALUES (21,'Decommission Subnetwork', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,0,0,1);

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPESID","PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT" ) 
VALUES (22,'Hardware Reduction', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,0,0,1);

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPESID","PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT" ) 
VALUES (23,'Hardware Expansion', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,0,0,1);

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPESID","PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT" ) 
VALUES (24,'Traffic Migration', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,0,0,1);

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPESID","PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT" ) 
VALUES (25,'New Feature/Redesign', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,0,0,1);

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPESID","PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT" ) 
VALUES (26,'Rebalance Traffic Distribution', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,0,0,1);

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPESID","PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT" ) 
VALUES (27,'License Management', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,0,0,1);

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPESID","PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT" ) 
VALUES (28,'Add Node', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,0,0,1);

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPESID","PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT" ) 
VALUES (29,'Initial Network Deployment', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,0,0,1);

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPESID","PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT" ) 
VALUES (30,'Emergency Calls over IMS', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,0,0,1);

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPESID","PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT" ) 
VALUES (31,'New Roaming Service', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,0,0,1);

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPESID","PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT" ) 
VALUES (32,'New SIP Interconnect', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,0,0,1);

INSERT INTO PLANNEDACTIVITYTYPES ("PLANNEDACTIVITYTYPESID","PLANNEDACTIVITYTYPEDESCRIPTION",    "HWOEM",    "HWSOLUTION",    "HWPLATFORM",    "SWOEM",    "SWPRODUCTNAME",    "SWVERSION",   "SUBNETWORKSERVICE","LINKEDDCRULE",	"CREATIONUSER",  "MODIFICATIONUSER" ,"FORLCM","FORASSET","FORDESIGNASPECT" ) 
VALUES (33,'Ancillary HW Component Upgrade', 0, 0, 0, 0, 0, 0, 0, 0, 13, 13,0,0,1);
COMMIT;

-------------------------------

update PLANNEDACTIVITYTYPES set   FORLCM = 0,FORASSET = 0,FORDESIGNASPECT = 1 where PLANNEDACTIVITYTYPEDESCRIPTION = 'Decommission Subnetwork';
update PLANNEDACTIVITYTYPES set   FORLCM = 0,FORASSET = 1,FORDESIGNASPECT = 1 where PLANNEDACTIVITYTYPEDESCRIPTION = 'Hardware Reduction';
update PLANNEDACTIVITYTYPES set   FORLCM = 0,FORASSET = 1,FORDESIGNASPECT = 1  where PLANNEDACTIVITYTYPEDESCRIPTION = 'Hardware Expansion';
update PLANNEDACTIVITYTYPES set   FORLCM = 0,FORASSET = 0,FORDESIGNASPECT = 1  where PLANNEDACTIVITYTYPEDESCRIPTION = 'Traffic Migration';
update PLANNEDACTIVITYTYPES set   FORLCM = 0,FORASSET = 0,FORDESIGNASPECT = 1  where PLANNEDACTIVITYTYPEDESCRIPTION = 'New Feature/Redesign';
update PLANNEDACTIVITYTYPES set   FORLCM = 0,FORASSET = 0,FORDESIGNASPECT = 1  where PLANNEDACTIVITYTYPEDESCRIPTION = 'Rebalance Traffic Distribution';
update PLANNEDACTIVITYTYPES set   FORLCM = 0,FORASSET = 0,FORDESIGNASPECT = 1 where PLANNEDACTIVITYTYPEDESCRIPTION = 'License Management';
update PLANNEDACTIVITYTYPES set   FORLCM = 0,FORASSET = 1,FORDESIGNASPECT = 0  where PLANNEDACTIVITYTYPEDESCRIPTION = 'Add Node';
update PLANNEDACTIVITYTYPES set   FORLCM = 0,FORASSET = 1,FORDESIGNASPECT = 0  where PLANNEDACTIVITYTYPEDESCRIPTION = 'Initial Network Deployment';
update PLANNEDACTIVITYTYPES set   FORLCM = 0,FORASSET = 0,FORDESIGNASPECT = 1  where PLANNEDACTIVITYTYPEDESCRIPTION = 'Emergency Calls over IMS';
update PLANNEDACTIVITYTYPES set   FORLCM = 0,FORASSET = 0,FORDESIGNASPECT = 1   where PLANNEDACTIVITYTYPEDESCRIPTION = 'New Roaming Service';
update PLANNEDACTIVITYTYPES set  FORLCM = 0,FORASSET = 0,FORDESIGNASPECT = 1  where PLANNEDACTIVITYTYPEDESCRIPTION = 'New SIP Interconnect';
update PLANNEDACTIVITYTYPES set  FORLCM = 0,FORASSET = 0,FORDESIGNASPECT = 1  where PLANNEDACTIVITYTYPEDESCRIPTION = 'Ancillary HW Component Upgrade';

update PLANNEDACTIVITYTYPES set   FORLCM = 0,FORASSET = 1,FORDESIGNASPECT = 0 where PLANNEDACTIVITYTYPEDESCRIPTION = 'Decommision Node';

COMMIT;

--------------------------------------------------

update plannedactivityresources set rulelinkeddc = 21 where PLANNEDACTIVITYRESOURCE = 'Decommission Subnetwork';
update plannedactivityresources set rulelinkeddc = 22 where PLANNEDACTIVITYRESOURCE = 'Hardware Reduction';
update plannedactivityresources set rulelinkeddc = 23 where PLANNEDACTIVITYRESOURCE = 'Hardware Expansion';
update plannedactivityresources set rulelinkeddc = 24 where PLANNEDACTIVITYRESOURCE = 'Traffic Migration';
update plannedactivityresources set rulelinkeddc = 25 where PLANNEDACTIVITYRESOURCE = 'New Feature/Redesign';
update plannedactivityresources set rulelinkeddc = 26 where PLANNEDACTIVITYRESOURCE = 'Rebalance Traffic Distribution';
update plannedactivityresources set rulelinkeddc = 27 where PLANNEDACTIVITYRESOURCE = 'License Management';
update plannedactivityresources set rulelinkeddc = 28 where PLANNEDACTIVITYRESOURCE = 'Add Node';
update plannedactivityresources set rulelinkeddc = 29 where PLANNEDACTIVITYRESOURCE = 'Initial Network Deployment';
update plannedactivityresources set rulelinkeddc = 30 where PLANNEDACTIVITYRESOURCE = 'Emergency Calls over IMS';
update plannedactivityresources set rulelinkeddc = 31 where PLANNEDACTIVITYRESOURCE = 'New Roaming Service';
update plannedactivityresources set rulelinkeddc = 32 where PLANNEDACTIVITYRESOURCE = 'New SIP Interconnect';
update plannedactivityresources set rulelinkeddc = 33 where PLANNEDACTIVITYRESOURCE = 'Ancillary HW Component Upgrade';
COMMIT;
