ALTER TABLE PASSTHROUGHLCM ADD "APPLICATIONOPERATINGSYS" NVARCHAR2(2000);
ALTER TABLE PASSTHROUGHLCM ADD "EOFSDATE" NVARCHAR2(2000);
ALTER TABLE PASSTHROUGHLCM ADD "EOSLKPIDAILY" NVARCHAR2(2000);
ALTER TABLE PASSTHROUGHLCM ADD "EOSLKPIFROZEN" NVARCHAR2(2000);
ALTER TABLE PASSTHROUGHLCM ADD "EOSLKPIFORECAST" NVARCHAR2(2000);
ALTER TABLE PASSTHROUGHLCM ADD "PRODUCTIMPORTANCEHISTORY2" NVARCHAR2(2000);
ALTER TABLE PASSTHROUGHLCM ADD "NOTES" NVARCHAR2(2000);
