-------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------
-----------------PLEASE RUN BELOW QUERY IN QA NOT IN PROD
INSERT INTO VERTICALRESPONSIBLES (CREATIONUSER, MODIFICATIONUSER, VERTICALRESPONSIBLE)
SELECT 1, 1, 'Data Core' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM VERTICALRESPONSIBLES WHERE VERTICALRESPONSIBLE = 'Data Core');

COMMIT;
-------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------

-----------------ADD NEW COLUMN IN FOLLOWING TABLES
ALTER TABLE PASSTHROUGH ADD NONTEMSVERTICAL_TEMP NUMBER(10) NULL;
 
ALTER TABLE PASSTHROUGHLCM ADD NONTEMSVERTICAL_TEMP NUMBER(10) NULL;  

ALTER TABLE TSRPASSTHROUGH ADD NONTEMSVERTICAL_TEMP NUMBER(10) NULL;
  
COMMIT;

-----------------UPDATE NEW ID FOR DATACORE DOMAIN IN FOLLOWING TABLES
UPDATE PASSTHROUGH b set b.NONTEMSVERTICAL_TEMP=(SELECT a.VERTICALRESPONSIBLEID FROM VERTICALRESPONSIBLES a where a.VERTICALRESPONSIBLE='Data Core');

UPDATE passthroughlcm b set b.NONTEMSVERTICAL_TEMP=(SELECT a.VERTICALRESPONSIBLEID FROM VERTICALRESPONSIBLES a where a.VERTICALRESPONSIBLE='Data Core');

UPDATE TSRPASSTHROUGH b set b.NONTEMSVERTICAL_TEMP=(SELECT a.VERTICALRESPONSIBLEID FROM VERTICALRESPONSIBLES a where a.VERTICALRESPONSIBLE='Data Core');

COMMIT;

-----------------DROP OLD COLUMN IN FOLLOWING TABLES
ALTER TABLE PASSTHROUGH DROP COLUMN NONTEMSVERTICAL;

ALTER TABLE PASSTHROUGHLCM DROP COLUMN NONTEMSVERTICAL;

ALTER TABLE TSRPASSTHROUGH DROP COLUMN NONTEMSVERTICAL;

COMMIT;

-----------------RENAME COLUMN TO OLD COLUMN NAME IN FOLLOWING TABLES
ALTER TABLE PASSTHROUGH RENAME COLUMN NONTEMSVERTICAL_TEMP TO NONTEMSVERTICAL;

ALTER TABLE PASSTHROUGHLCM RENAME COLUMN NONTEMSVERTICAL_TEMP TO NONTEMSVERTICAL;

ALTER TABLE TSRPASSTHROUGH RENAME COLUMN NONTEMSVERTICAL_TEMP TO NONTEMSVERTICAL;

COMMIT;

-----------------ADD NEW FOREIGN KEY IN FOLLOWING TABLES
ALTER TABLE PASSTHROUGH
ADD CONSTRAINT "FK_PASSTHROUGH_VERTICALRESPONSIBLES_NONTEMSVERTICAL"
FOREIGN KEY ("NONTEMSVERTICAL")
REFERENCES "VERTICALRESPONSIBLES"(VERTICALRESPONSIBLEID)ENABLE;

ALTER TABLE PASSTHROUGHLCM
ADD CONSTRAINT "FK_PASSTHROUGHLCM_VERTICALRESPONSIBLES_NONTEMSVERTICAL"
FOREIGN KEY ("NONTEMSVERTICAL")
REFERENCES "VERTICALRESPONSIBLES"(VERTICALRESPONSIBLEID)ENABLE;

ALTER TABLE TSRPASSTHROUGH
ADD CONSTRAINT "FK_TSRPASSTHROUGH_VERTICALRESPONSIBLES_NONTEMSVERTICAL"
FOREIGN KEY ("NONTEMSVERTICAL")
REFERENCES "VERTICALRESPONSIBLES"(VERTICALRESPONSIBLEID)ENABLE;

COMMIT;