INSERT INTO "SOFTWAREAPPLICATIONTYPES" (SOFTWAREAPPLICATIONTYPESID, DESCRIPTION, CREATIONUSER, CREATIONDATE, MODIFICATIONUSER, MODIFICATIONDATE, DELETED, DELETIONDATE, VODAFONENAMESID)
SELECT PRODUCTNAMEID, DESCRIPTION, CREATIONUSER, CREATIONDATE, MODIFICATIONUSER, MODIFICATIONDATE, DELETED, DELETIONDATE, VODAFONENAMESID  
FROM "PRODUCTNAME"
