ALTER TABLE "SUBNETWORKBOUNDARIES" ADD CONSTRAINT "FK_SUBNETWORKBOUNDARIES_SOFTWAREAPPLICATIONTYPES_SOFTWAREAPPLICATIONTYPESID" FOREIGN KEY ("SOFTWAREAPPLICATIONTYPEID")
REFERENCES "SOFTWAREAPPLICATIONTYPES" ("SOFTWAREAPPLICATIONTYPESID") ENABLE;

ALTER TABLE "DESIGNCOMPONENTFAMILIES" ADD CONSTRAINT "FK_DESIGNCOMPONENTFAMILIES_SOFTWAREAPPLICATIONTYPES_SOFTWAREAPPLICATIONTYPESID" FOREIGN KEY ("SOFTWAREAPPLICATIONTYPEID")
REFERENCES "SOFTWAREAPPLICATIONTYPES" ("SOFTWAREAPPLICATIONTYPESID") ENABLE;

ALTER TABLE "MAJORSOFTWAREBUILDS" ADD CONSTRAINT "FK_MAJORSOFTWAREBUILDS_SOFTWAREAPPLICATIONTYPES_SOFTWAREAPPLICATIONTYPESID" FOREIGN KEY ("SOFTWAREAPPLICATIONTYPEID")
REFERENCES "SOFTWAREAPPLICATIONTYPES" ("SOFTWAREAPPLICATIONTYPESID") ENABLE;

