  ALTER TABLE ACTIVITYDETAILS
  DROP COLUMN ACTIVITYDETAILS;
  
  ALTER TABLE ACTIVITYDETAILS
  ADD DESCRIPTION Nvarchar2(2000) NULL;
  
  update ACTIVITYDETAILS
  set description = 'TESTPLANNEDACTIVITY_ACTDETAILS'
  where activitydetailsid =1 ;
  
  commit; 


    
  
  ALTER TABLE BUDGETAVAILABILITY
  ADD DESCRIPTION Nvarchar2(2000) NULL;
  
  update BUDGETAVAILABILITY
  set description = BUDGETAVAILABILITY;
  commit; 
  
  ALTER TABLE BUDGETAVAILABILITY
  DROP COLUMN BUDGETAVAILABILITY;