UPDATE NETWORKELEMENTSASPLANNED SET HWRESOURCEKEY = ''; 
UPDATE NETWORKELEMENTSASPLANNED SET SWRESOURCEKEY = '' ;
ALTER TABLE NETWORKELEMENTSASPLANNED MODIFY HWRESOURCEKEY NVARCHAR2(10);
ALTER TABLE NETWORKELEMENTSASPLANNED MODIFY SWRESOURCEKEY NVARCHAR2(10);
commit;


