CREATE SEQUENCE "DCFLIFECYCLE_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL for Table DCFLIFECYCLE
--------------------------------------------------------

  CREATE TABLE "DCFLIFECYCLE" 
   (	"DCFLIFECYCLEID" NUMBER(19,0) DEFAULT "DCFLIFECYCLE_SEQ"."NEXTVAL", 
	"DCFID" NUMBER(19,0), 
	"RESOURCEKEY" NVARCHAR2(15), 
	"PREVIOUSRESOURCEKEY" NVARCHAR2(255), 
	"OPCOID" NUMBER(5,0), 
	"DCID" NUMBER(19,0), 
	"EventID" NUMBER(5,0), 
	"EventName" VARCHAR2(255 BYTE), 	
	"Notes" NVARCHAR2(255), 
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index DCFLIFECYCLEIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "DCFLIFECYCLEIDX" ON "DCFLIFECYCLE" ("DCFLIFECYCLEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table DCFLIFECYCLE
--------------------------------------------------------

  ALTER TABLE "DCFLIFECYCLE" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "DCFLIFECYCLE" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "DCFLIFECYCLE" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "DCFLIFECYCLE" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "DCFLIFECYCLE" ADD CONSTRAINT "DCFLIFECYCLE_PK" PRIMARY KEY ("DCFLIFECYCLEID")
  USING INDEX "DCFLIFECYCLEIDX"  ENABLE;
  ALTER TABLE "DCFLIFECYCLE" MODIFY ("DCFID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DCFLIFECYCLE
--------------------------------------------------------

  ALTER TABLE "DCFLIFECYCLE" ADD CONSTRAINT "FK_DCFLIFECYCLE_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "DCFLIFECYCLE" ADD CONSTRAINT "FK_DCFLIFECYCLE_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "DCFLIFECYCLE" ADD CONSTRAINT "FK_DCFLIFECYCLE_LCMENGINEERING_OPCOS_OPCOID" FOREIGN KEY ("OPCOID")
	  REFERENCES "OPCOS" ("OPCOID") ENABLE;
  ALTER TABLE "DCFLIFECYCLE" ADD CONSTRAINT "FK_DCFLIFECYCLE_DESIGNCOMPONENTS_DESIGNCOMPONENTID" FOREIGN KEY ("DCID")
	  REFERENCES "DESIGNCOMPONENTS" ("DESIGNCOMPONENTID") ENABLE;
  ALTER TABLE "DCFLIFECYCLE" ADD CONSTRAINT "FK_DCFLIFECYCLE_DESIGNCOMPONENTFAMILIES_DESIGNCOMPONENTFAMILYID" FOREIGN KEY ("DCFID")
	  REFERENCES "DESIGNCOMPONENTFAMILIES" ("DESIGNCOMPONENTFAMILYID") ENABLE;
