ALTER TABLE RESOURCEKEYMASTER DROP COLUMN RESOURCELIFECYCLEID;
ALTER TABLE LCMENGINEERING MODIFY RESOURCEKEY NVARCHAR2(15);
ALTER TABLE RESOURCEKEYMASTER ADD ELEMENTNAME NVARCHAR2(2000);
update RESOURCEKEYMASTER SET KEYSTATUS =1 where KEYSTATUS is null;
ALTER TABLE RESOURCEKEYMASTER MODIFY KEYSTATUS DEFAULT 1;
drop table RESOURCELIFECYCLE;
drop sequence RESOURCELIFECYCLE_SEQ;
commit;