CREATE SEQUENCE "RESOURCETYPES_SEQ"
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
--------------------------------------------------------
--  DDL for Table RESOURCETYPES
--------------------------------------------------------
   CREATE TABLE "RESOURCETYPES" 
(
    "RESOURCETYPESID" NUMBER(19,0) DEFAULT "RESOURCETYPES_SEQ"."NEXTVAL",
    "NAME" NVARCHAR2(50),
    "DESCRIPTION" NVARCHAR2(300),    
    "CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
    "CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
    "MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
    "MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp),
    "DELETED" NUMBER(1,0) DEFAULT 0,
    "DELETIONDATE" TIMESTAMP(6)
)SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";
--------------------------------------------------------
--  DDL for Index RESOURCETYPESIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESOURCETYPESIDX" ON "RESOURCETYPES" ("RESOURCETYPESID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB";
--------------------------------------------------------
--  Constraints for Table RESOURCETYPES
--------------------------------------------------------
  ALTER TABLE "RESOURCETYPES" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "RESOURCETYPES" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "RESOURCETYPES" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "RESOURCETYPES" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "RESOURCETYPES" ADD CONSTRAINT "PK_RESOURCETYPES" PRIMARY KEY ("RESOURCETYPESID")
   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB"  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table RESOURCETYPES
--------------------------------------------------------
ALTER TABLE "RESOURCETYPES" ADD CONSTRAINT "FK_RESOURCETYPES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
REFERENCES "ASPNETUSERS" ("ID") ENABLE;	  
ALTER TABLE "RESOURCETYPES" ADD CONSTRAINT "FK_RESOURCETYPES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "RESOURCETYPES"
MODIFY("RESOURCETYPESID"  DEFAULT "RESOURCETYPES_SEQ"."NEXTVAL");