INSERT INTO "RESOURCETYPES" (NAME) VALUES ('SWASSET');
INSERT INTO "RESOURCETYPES" (NAME) VALUES ('HWASSET');
INSERT INTO "RESOURCETYPES" (NAME) VALUES ('LCM');
INSERT INTO "RESOURCETYPES" (NAME) VALUES ('IDENTITY');
commit;







