ALTER TABLE PLANNEDACTIVITIES DROP COLUMN PLANNEDACTIVITYCATEGORY;
ALTER TABLE DRIVERS ADD BPTDRIVERDETAILS NVARCHAR2(2000);


RENAME NETWORKELEMENTASPLANNEDPASSTHROUGH TO NONTEMSNWEASPLANNEDPASSTHROUGH;

ALTER TABLE NONTEMSNWEASPLANNEDPASSTHROUGH RENAME COLUMN NETWORKELEMENTASPLANNEDPASSTHROUGHID TO NONTEMSNWEASPLANNEDPASSTHROUGHID;

DROP SEQUENCE NETWORKELEMENTASPLANNEDPASSTHROUGH_SEQ;

CREATE SEQUENCE  "NONTEMSNWEASPLANNEDPASSTHROUGH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100000 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

ALTER TABLE NONTEMSNWEASPLANNEDPASSTHROUGH MODIFY (NONTEMSNWEASPLANNEDPASSTHROUGHID DEFAULT NONTEMSNWEASPLANNEDPASSTHROUGH_SEQ.NEXTVAL);

ALTER TABLE NONTEMSNWEASPLANNEDPASSTHROUGH DROP CONSTRAINT PK_NETWORKELEMENTASPLANNEDPASSTHROUGH;

DROP INDEX PK_NETWORKELEMENTASPLANNEDPASSTHROUGH;

CREATE UNIQUE INDEX "PK_NONTEMSNWEASPLANNEDPASSTHROUGH" ON "NONTEMSNWEASPLANNEDPASSTHROUGH" ("NONTEMSNWEASPLANNEDPASSTHROUGHID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
  
ALTER TABLE "NONTEMSNWEASPLANNEDPASSTHROUGH" ADD CONSTRAINT "PK_NONTEMSNWEASPLANNEDPASSTHROUGH" PRIMARY KEY ("NONTEMSNWEASPLANNEDPASSTHROUGHID") USING INDEX "PK_NONTEMSNWEASPLANNEDPASSTHROUGH"  ENABLE;

ALTER TABLE NONTEMSNWEASPLANNEDPASSTHROUGH RENAME CONSTRAINT FK_NETWORKELEMENTASPLANNEDPASSTHROUGH_ASPNETUSERS_CREATIONUSER TO FK_NONTEMSNWEASPLANNEDPASSTHROUGH_ASPNETUSERS_CREATIONUSER;
ALTER TABLE NONTEMSNWEASPLANNEDPASSTHROUGH RENAME CONSTRAINT FK_NETWORKELEMENTASPLANNEDPASSTHROUGH_ASPNETUSERS_MODIFICATIONUSER TO FK_NONTEMSNWEASPLANNEDPASSTHROUGH_ASPNETUSERS_MODIFICATIONUSER;

