--------------------------------------------------------
--  DDL FOR SEQUENCE PROGRAM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROGRAM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

--------------------------------------------------------
--  DDL FOR TABLE PROGRAM
--------------------------------------------------------

  CREATE TABLE "PROGRAM" 
   (	"PROGRAMID" NUMBER(19,0) DEFAULT "PROGRAM_SEQ"."NEXTVAL", 
	"PROGRAMDESCRIPTION" NVARCHAR2(2000), 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_PROGRAM
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROGRAM" ON "PROGRAM" ("PROGRAMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE PROGRAM
--------------------------------------------------------

  ALTER TABLE "PROGRAM" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "PROGRAM" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "PROGRAM" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "PROGRAM" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "PROGRAM" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "PROGRAM" ADD CONSTRAINT "PK_PROGRAM" PRIMARY KEY ("PROGRAMID")
  USING INDEX "PK_PROGRAM"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE PROGRAM
--------------------------------------------------------

  ALTER TABLE "PROGRAM" ADD CONSTRAINT "FK_PROGRAM_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "PROGRAM" ADD CONSTRAINT "FK_PROGRAM_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;

--------------------------------------------------------
--INSERT SCRIPT FOR PROGRAM
--------------------------------------------------------
SET DEFINE OFF;
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('1&1',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('2Africa Project',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('3G Shutdown',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('4GR',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('5G',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('5G - Advanced',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('5G Preparation',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('5G RAN',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('5G SA',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('5G Stand Alone',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('5GC',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('76xx Islands',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('AAA',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('AAA Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Access Network',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Access TX evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Alarming Services',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('ARGUS',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Artemis',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('ASI',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Automatic Device Detection',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Automation',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Autonomous Network',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('BAU',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('BNG Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Broadband Capacity',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Broadcom exit',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('BroadCom Exodus',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('BSC renewal',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('CaaS',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Call Center Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Capabilities',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Capacity',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Capacity & Enhancement',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('CCS on Cloud',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('CGNAT',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('CGNAT-Evolution Implementation',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Charging AI & Automation',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Charging Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Circuit Switch Core',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Cloud BNG',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Cloud CO',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Cloud Native-Cerebro/IMS Services Cloud Native',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Cloud Strategy',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('CMS',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Collaboration solution integration',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Commercialization',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Common Cloud Blueprint',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Contact Center',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Converged Backhauling',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Converged TN development',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Coperate Demands',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Core Network – Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Core Network – Principal',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('CPE Security Robustness',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Crowdcells/Analytics',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('CRS',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('CSB',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('CSDB consolidation',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('CT/CD',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Customer Experience Management',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Cyber Security Assessment',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Data Democratization Enablers',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Data PCRF',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Digital',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Digital and OSS Simplification',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Digital First',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Digital Home Projects (USP)',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Digital Testing',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Distribute BNG',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('DNS',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('DOCSIS 4.0',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('DSL Retirement',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('EDU BAU',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Emergency Call over IMS',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('ENERGY',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Energy efficiency',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Enterprise',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Enterprise Capacity',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Entitlement Server',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Equinix',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('EWL / Spring 5',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('EWL / Spring 6',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('External FTEs',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('FAE Catamaran',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('FAE Testing Strategy - Central & Local Testing',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Fixed Access Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Fixed Access LCM Projects',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Fixed Access Performance',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Fixed Backhauling',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Fixed Benchmarking & Performance Program',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Fixed Distributed Edge',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Fixed Enterprise',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Fixed Mobile Convergence',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Fixed Residential',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Fixed SDN Controller',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Fixed SDN-C Introduction',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('FLEX components',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Fulfilment',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Future of Cable Engineering and Roll-out',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('FWA',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('FWA through BNG',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Galileo',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Gamma',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('GenAI',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Geo-Resilience',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Gi DNS',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Gi LAN',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Gigabit Networks',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('GnGp DNS',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Growth & Transformation',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Home',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Huawei SWAP',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('IMS as a Primary Network',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('IMS Centralised Services',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('IMS Cloud Native',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('IMS Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('IMS on Cloud',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('IMS Services Cloud Native',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('IMS Services Virtualization',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('IMS Virtualization',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Innovation',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Integrated Radio Planning (IRP)',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Intelligence',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Interconnect',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Introduction of 1,8GHz in Cable Network',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('IP Core NW',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('IPED BAU',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('IPv6',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('IPX',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('IVC',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('LCM',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('LCM,Security&Regulatory',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Lifecycle',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Local Workstream',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Location services',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('LTC',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('M&A',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Market Demands',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Matrix',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('MEC',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('MESN Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Messaging Gw Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Microwave Capability',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Migration of Platform hosted in Spain',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('MMS Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Mobile Backhaul',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Mobile Backhauling',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Monetization & Charging Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('MPN',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('MultiGiga DS Launch',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('MultiGiga FTTH Readiness',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('NaaP',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('NaaP - APIS',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('NEF',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Netperform Enrichment',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Network Device Detection',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('New Coverage Enablement through Wholesale/Wholebuy/merge Agreement',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Not Assigned',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('NVI Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('NVI LCM',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('NVI Market Design',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Office',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Office LAN',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Office LAN Engg',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('One Number',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('OneNet Digitalization',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Open RAN',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Operating Model',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Operational Efficiency',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Optical Backhauling',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Optical Core Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Optical Core NW',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('ORAN',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Orchestration',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('OSS simplification - Cost to prolong',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('OSS simplification - LRP',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('OSS simplification - on top',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('OSS Transformation',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Other Data Platforms',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Packet Core DNS',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Peering & Caching',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Peripheral Network – Capacity',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Peripheral Network – Services',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Peripheral Network-Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Peripheral Network-Principal',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Physical BNG modernization',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('PMI',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Policy',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Productivity Tools',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('R4 renewal',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Redstream Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Redstream Optical Progression',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Repatriation Projects',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Resilience',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Resilience Improvement',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Routing Layer',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('SATELLITE',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('SD WAN for Corporat and SME',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('SDN',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('SDN Automation',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('SDWAN for Enterprise',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('SecureNet',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Security',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Security Gateway',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Service Layer LCM Projects',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Sharing Agreements',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('SIM Security',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('SIM-OTA',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Simplification',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Smart Devices',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('SMS Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('SMS Fraud - SMS Advanced Firewalling',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('SMSC VoLTE Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Software SRS',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('SON',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Spring 2',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Spring 2 Reload',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Spring 3',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Standards',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Strategic Voice Services Transformation',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Strategic Voice  Services Transformation',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Super Wifi',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Testing Evolution and Automation',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('TETRIS',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Thetis Project',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('TIM & WIN migration',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Tools',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Traffic Analytics',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Transformational',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Transport SDN',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('TSRs',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('TV',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('UC Cloud engineering',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('UK ASBR Colo',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('UK Messaging',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Ulysses',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Unallocated Challenge',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Undefined',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('UTIQ Enablement',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('VAS',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('VIPER',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Virtual OLT Program',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Virtualization',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Voice Innovation',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Voicemail Evolution',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('VoLTE',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('VoLTE Capacity',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('VOLTE for Business',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('VoLTE for MVNO',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('VoLTE Roaming',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('VTS upgrades',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('VTV',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Wifi6',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Wired-Wireless Convergence: Policy',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('Zero Touch Operation',1,1);
INSERT INTO PROGRAM (PROGRAMDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) VALUES ('ZTO',1,1);
SET DEFINE ON;
-----------------------------------------------------------
--CREATE THE Temp_PLANNEDACTIVITIES
-----------------------------------------------------------
CREATE TABLE Temp_PLANNEDACTIVITIES
AS
SELECT PLANNEDACTIVITYID, PROGRAM FROM PLANNEDACTIVITIES;

------------------------------------------------------------

ALTER TABLE PLANNEDACTIVITIES DROP COLUMN PROGRAM;
ALTER TABLE PLANNEDACTIVITIES ADD PROGRAMID NUMBER(19,0);
ALTER TABLE PLANNEDACTIVITIES ADD CONSTRAINT "FK_PLANNEDACTIVITIES_PROGRAM_PROGRAMID" FOREIGN KEY ("PROGRAMID") REFERENCES "PROGRAM" ("PROGRAMID") ENABLE;


--------------------------------------------------------
UPDATE DRIVERS SET BPTDRIVERDETAILS = DRIVER;
COMMIT;


ALTER TABLE budgetprojecttrackers MODIFY ARCHIVE NUMBER(1) DEFAULT 0;

----------------------------- Assign Program id to PA --
MERGE INTO PLANNEDACTIVITIES b
USING (
  SELECT rid, new_prgId,programdesc 
  FROM (
    SELECT b.ROWID AS rid,
            pn.PROGRAMid as new_prgId ,tpa.programdesc,
           ROW_NUMBER() OVER (PARTITION BY b.ROWID ORDER BY tpa.programdesc) AS rn
    FROM PLANNEDACTIVITIES b
    JOIN Temp_PLANNEDACTIVITIES tpa ON tpa.PLANNEDACTIVITYID  = b.PLANNEDACTIVITYID
    JOIN PROGRAM pn ON pn.PROGRAMDESCRIPTION  = tpa.programdesc
    where tpa.programdesc is not null 
  )
  WHERE rn = 1 
) src
ON (b.ROWID = src.rid)
WHEN MATCHED THEN
  UPDATE SET b.PROGRAMID = src.new_prgId where src.new_prgId is not null;
  
  Commit;