--------------------------------------------------------
--  DDL FOR SEQUENCE PROJECTSPLAN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJECTSPLAN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

--------------------------------------------------------
--  DDL FOR TABLE PROJECTSPLAN
--------------------------------------------------------

  CREATE TABLE "PROJECTSPLAN" 
   (	"PROJECTSPLANID" NUMBER(19,0) DEFAULT "PROJECTSPLAN_SEQ"."NEXTVAL", 	
	"PLANNEDACTIVITYID" NUMBER(19,0) NOT NULL,
	"SETTINGSUPDATEPLANNEDACTIVITYID" NUMBER(5,0) NOT NULL,
	"STARTDATE" TIMESTAMP (6),
	"ENDDATE" TIMESTAMP (6),
	"DESCRIPTION" NVARCHAR2(2000),
	"PROGRESS" NVARCHAR2(2000),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_PROJECTSPLAN
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROJECTSPLAN" ON "PROJECTSPLAN" ("PROJECTSPLANID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE PROJECTSPLAN
--------------------------------------------------------

  ALTER TABLE "PROJECTSPLAN" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "PROJECTSPLAN" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECTSPLAN" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "PROJECTSPLAN" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECTSPLAN" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "PROJECTSPLAN" ADD CONSTRAINT "PK_PROJECTSPLAN" PRIMARY KEY ("PROJECTSPLANID")
  USING INDEX "PK_PROJECTSPLAN"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE PROJECTSPLAN
--------------------------------------------------------

  ALTER TABLE "PROJECTSPLAN" ADD CONSTRAINT "FK_PROJECTSPLAN_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "PROJECTSPLAN" ADD CONSTRAINT "FK_PROJECTSPLAN_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "PROJECTSPLAN" ADD CONSTRAINT "FK_PROJECTSPLAN_PLANNEDACTIVITIES_PLANNEDACTIVITYID" FOREIGN KEY ("PLANNEDACTIVITYID")
	  REFERENCES "PLANNEDACTIVITIES" ("PLANNEDACTIVITYID") ENABLE;
  ALTER TABLE "PROJECTSPLAN" ADD CONSTRAINT "FK_PROJECTSPLAN_SETTINGSUPDATEPLANNEDACTIVITY_SETTINGSUPDATEPLNACTID" FOREIGN KEY ("SETTINGSUPDATEPLANNEDACTIVITYID")
	  REFERENCES "SETTINGSUPDATEPLANNEDACTIVITY" ("SETTINGSUPDATEPLNACTID") ENABLE;