ALTER TABLE aspnetuserroles DROP COLUMN TEMPCREATIONDATE;
ALTER TABLE "ASPNETUSERROLES" DROP CONSTRAINT "PK_ASPNETUSERROLES"; 
CREATE SEQUENCE  "ASPNETUSERROLEID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
ALTER TABLE ASPNETUSERROLES add aspnetuserroleid number DEFAULT "ASPNETUSERROLEID_SEQ"."NEXTVAL";
ALTER TABLE "ASPNETUSERROLES" ADD CONSTRAINT "PK_ASPNETUSERROLES" PRIMARY KEY ("ASPNETUSERROLEID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "CAMDB"  ENABLE;
CREATE UNIQUE INDEX "UK_ASPNETUSERROLES" ON "ASPNETUSERROLES" ("USERID", "ROLEID","OPCOID","VERTICALRESPONSIBLEID") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "CAMDB" ;
  
  