ALTER TABLE "ASPNETUSERS" ADD ACTIVE NUMBER(1,0) DEFAULT 1; 
ALTER TABLE	"ASPNETUSERS" ADD CREATIONUSER NUMBER(10,0); 
ALTER TABLE	"ASPNETUSERS" ADD CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp);
ALTER TABLE	"ASPNETUSERS" ADD MODIFICATIONUSER NUMBER(10,0); 
ALTER TABLE	"ASPNETUSERS" ADD MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp); 
ALTER TABLE	"ASPNETUSERS" ADD DELETED NUMBER(1,0) DEFAULT 0; 
ALTER TABLE	"ASPNETUSERS" ADD DELETIONDATE TIMESTAMP (6);