--------------------------------------------------------
--  DDL FOR SEQUENCE AUDITLOGS_SEQ
--------------------------------------------------------
 
CREATE SEQUENCE "AUDITLOGS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;
 
 
 
--------------------------------------------------------
--  DDL FOR TABLE AUDITLOGS
--------------------------------------------------------
 
CREATE TABLE "AUDITLOGS" 
("AUDITLOGID" NUMBER(20,0) DEFAULT "AUDITLOGS_SEQ"."NEXTVAL", 
"ENTITYNAME" NVARCHAR2(100),
"ENTITYFIELD" NVARCHAR2(100), 
"OLDVALUE" NVARCHAR2(2000),
"NEWVALUE" NVARCHAR2(2000),
"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"DELETED" NUMBER(1,0) DEFAULT 0, 
"DELETIONDATE" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
 
--------------------------------------------------------
--  DDL FOR INDEX PK_AUDITLOGS
--------------------------------------------------------
 
CREATE UNIQUE INDEX "PK_AUDITLOGS" ON "AUDITLOGS" ("AUDITLOGID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------
 
ALTER TABLE "AUDITLOGS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "AUDITLOGS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "AUDITLOGS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "AUDITLOGS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "AUDITLOGS" ADD CONSTRAINT "PK_AUDITLOGS" PRIMARY KEY ("AUDITLOGID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------
 
ALTER TABLE "AUDITLOGS" ADD CONSTRAINT "FK_AUDITLOGS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "AUDITLOGS" ADD CONSTRAINT "FK_AUDITLOGS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  
COMMIT;