--------------------------------------------------------
--  DDL FOR SEQUENCE AUDITTABLESANDCOLUMNS_SEQ
--------------------------------------------------------
 
CREATE SEQUENCE "AUDITTABLESANDCOLUMNS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;
 
--------------------------------------------------------
--  DDL FOR TABLE AUDITTABLESANDCOLUMNS
--------------------------------------------------------
 
CREATE TABLE "AUDITTABLESANDCOLUMNS" 
("AUDITTABLESANDCOLUMNID" NUMBER(20,0) DEFAULT "AUDITTABLESANDCOLUMNS_SEQ"."NEXTVAL",
"ENTITYNAME" NVARCHAR2(100), 
"ENTITYFIELD" NVARCHAR2(250),
"ENTITYID" NUMBER(19,0),
"ISLOGENABLED" NUMBER(1,0),
"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
"DELETED" NUMBER(1,0) DEFAULT 0, 
"DELETIONDATE" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
 
--------------------------------------------------------
--  DDL FOR INDEX PK_AUDITTABLESANDCOLUMNS
--------------------------------------------------------
 
CREATE UNIQUE INDEX "PK_AUDITTABLESANDCOLUMNS" ON "AUDITTABLESANDCOLUMNS" ("AUDITTABLESANDCOLUMNID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITTABLESANDCOLUMNS
--------------------------------------------------------
 
ALTER TABLE "AUDITTABLESANDCOLUMNS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "AUDITTABLESANDCOLUMNS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "AUDITTABLESANDCOLUMNS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "AUDITTABLESANDCOLUMNS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "AUDITTABLESANDCOLUMNS" ADD CONSTRAINT "PK_AUDITTABLESANDCOLUMNS" PRIMARY KEY ("AUDITTABLESANDCOLUMNID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITTABLESANDCOLUMNS
--------------------------------------------------------
 
ALTER TABLE "AUDITTABLESANDCOLUMNS" ADD CONSTRAINT "FK_AUDITTABLESANDCOLUMNS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "AUDITTABLESANDCOLUMNS" ADD CONSTRAINT "FK_AUDITTABLESANDCOLUMNS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
COMMIT;



