
--------------------------------------------------------
--  DDL for Sequence FEEDBACKLOOPAUDIT_SEQ
--------------------------------------------------------

CREATE SEQUENCE "FEEDBACKLOOPAUDIT_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;




--------------------------------------------------------
--  DDL for Table FEEDBACKLOOPAUDITS
--------------------------------------------------------

CREATE TABLE "FEEDBACKLOOPAUDITS" 
("FEEDBACKLOOPAUDITID" NUMBER(20,0) DEFAULT "FEEDBACKLOOPAUDIT_SEQ"."NEXTVAL", 
"OPCO" NVARCHAR2(50), 
"OEM" NVARCHAR2(50), 
"NODETYPE" NVARCHAR2(50),
"FILECOUNT" NUMBER(19,0),
"PROCESSSTARTTIME" TIMESTAMP(6) DEFAULT NULL,
"PROCESSENDTIME" TIMESTAMP(6) DEFAULT NULL,
"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
"DELETED" NUMBER(1,0) DEFAULT 0, 
"DELETIONDATE" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;

--------------------------------------------------------
--  DDL for Index PK_FEEDBACKLOOPAUDITS
--------------------------------------------------------

CREATE UNIQUE INDEX "PK_FEEDBACKLOOPAUDITS" ON "FEEDBACKLOOPAUDITS" ("FEEDBACKLOOPAUDITID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table FEEDBACKLOOPAUDITS
--------------------------------------------------------

ALTER TABLE "FEEDBACKLOOPAUDITS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "FEEDBACKLOOPAUDITS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "FEEDBACKLOOPAUDITS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "FEEDBACKLOOPAUDITS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "FEEDBACKLOOPAUDITS" ADD CONSTRAINT "PK_FEEDBACKLOOPAUDITS" PRIMARY KEY ("FEEDBACKLOOPAUDITID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FEEDBACKLOOPAUDITS
--------------------------------------------------------

ALTER TABLE "FEEDBACKLOOPAUDITS" ADD CONSTRAINT "FK_FEEDBACKLOOPAUDITS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "FEEDBACKLOOPAUDITS" ADD CONSTRAINT "FK_FEEDBACKLOOPAUDITS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
  REFERENCES "ASPNETUSERS" ("ID") ENABLE;

COMMIT;