ALTER TABLE XMLPARSERUN ADD FEEDBACKLOOPAUDITID NUMBER(20,0);
ALTER TABLE AUDITLOGS ADD ENTITYID NUMBER(19,0);
ALTER TABLE "XMLPARSERUN" ADD CONSTRAINT "FK_XMLPARSERUN_FEEDBACKLOOPAUDITS_FEEDBACKLOOPAUDITID" FOREIGN KEY ("FEEDBACKLOOPAUDITID") REFERENCES "FEEDBACKLOOPAUDITS" ("FEEDBACKLOOPAUDITID") ENABLE;
COMMIT;