ALTER TABLE NODEPARSEHISTORY ADD NODEPROCESSSTARTTIME TIMESTAMP(6) DEFAULT NULL; 
ALTER TABLE NODEPARSEHISTORY ADD NODEPROCESSENDTIME TIMESTAMP(6) DEFAULT NULL;
ALTER TABLE NODEPARSEHISTORY ADD NODETYPE NVARCHAR2(50);

ALTER TABLE XMLPARSERUN ADD FILEPROCESSSTARTTIME TIMESTAMP(6) DEFAULT NULL; 
ALTER TABLE XMLPARSERUN ADD FILEPROCESSENDTIME TIMESTAMP(6) DEFAULT NULL;
ALTER TABLE XMLPARSERUN ADD FEEDBACKLOOPAUDITID NUMBER(20,0);

ALTER TABLE "XMLPARSERUN" ADD CONSTRAINT "FK_XMLPARSERUN_FEEDBACKLOOPAUDITS_FEEDBACKLOOPAUDITID" FOREIGN KEY ("FEEDBACKLOOPAUDITID")
REFERENCES "FEEDBACKLOOPAUDITS" ("FEEDBACKLOOPAUDITID") ENABLE;

COMMIT;

 