--------RB SCRIPT FOR PA AND SETTINGSUPDATEPLANNEDACTIVITY-------------------
ALTER TABLE SETTINGSUPDATEPLANNEDACTIVITY DROP COLUMN ISMILESTONE; 
ALTER TABLE PLANNEDACTIVITIES DROP COLUMN PREBASELINEENDDATE;

--------RB SCRIPT FOR PROJECTSPLAN-------------------
ALTER TABLE PROJECTSPLAN DROP COLUMN BASELINESTARTDATE;
ALTER TABLE PROJECTSPLAN DROP COLUMN BASELINEENDDATE;

ALTER TABLE PROJECTSPLAN RENAME COLUMN PLANNINGSTARTDATE TO STARTDATE;
ALTER TABLE PROJECTSPLAN RENAME COLUMN PLANNINGENDDATE TO ENDDATE;
