/* eslint-disable @typescript-eslint/consistent-type-assertions */
/// <reference path="../Common/custom.d.ts" />
// tslint:disable
/**
 * Cam Vodafone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "../Common/configuration";
import { headerObj } from "../header";

import {
  DataRemediationDto,
  ResultDto,
  ResultDtoOfResultDataRemediationDto,
} from "../../Model/CommonModels";
import {
  BASE_PATH,
  FetchArgs,
  FetchAPI,
  RequiredError,
  FilterValueDto,
} from "../Common/CommonBusiness";
import { BaseAPI } from "../Common/CommonBusiness";
import {
  LcmEngineeringDtoCreate,
  LcmEngineeringDtoUpdate,
  QueryResultDtoOfLcmEngineeringDtoGrid,
} from "../../Model/LcmEngineering";
import { FileResult, ReturnFile } from "../../Model/Common";
import {
  QueryResultDtoOfTipologicaGridDto,
  QueryResultDtoOfTipologicaGridDtoRule,
  TipologicaGridDto,
  TipologicaGridDtoRule,
} from "../../Model/LookUp/LookUpGenericModel";
import {
  DeploymentStatusDto,
  QueryResultDtoOfDeploymentStatusDtoGrid,
} from "../../Model/LookUp/DeploymentStatus";

/**
 * DeploymentStatusApi - fetch parameter creator
 * @export
 */
export const DeploymentStatusApiFetchParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @param {DeploymentStatusDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusCreate(
      body: DeploymentStatusDto,
      options: any = {}
    ): FetchArgs {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling deploymentStatusCreate."
        );
      }
      const localVarPath = `/api/DeploymentStatus`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "POST" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"DeploymentStatusDto" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusDelete(id?: number, options: any = {}): FetchArgs {
      const localVarPath = `/api/DeploymentStatus/Delete`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign(
        { method: "DELETE" },
        options
      );
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (id !== undefined) {
        localVarQueryParameter["id"] = id;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusDeleteDeep(id?: number, options: any = {}): FetchArgs {
      const localVarPath = `/api/DeploymentStatus/DeleteDeep`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign(
        { method: "DELETE" },
        options
      );
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (id !== undefined) {
        localVarQueryParameter["id"] = id;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusGetCreateResourceDeploymentStatus(
      options: any = {}
    ): FetchArgs {
      const localVarPath = `/api/DeploymentStatus/Create`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {Array<number>} [deploymentStatusId]
     * @param {Array<string>} [deploymentStatusDescription]
     * @param {Array<number>} [rule]
     * @param {Array<string>} [plannedActivityResourceAllowed]
     * @param {Array<boolean>} [readOnlyPlannedActivity]
     * @param {Array<boolean>} [checkPlannedActivity]
     * @param {Array<boolean>} [defaultValue]
     * @param {string} [sortBy]
     * @param {boolean} [isSortAscending]
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {Date} [lastModifiedStartDate]
     * @param {Date} [lastModifiedEndDate]
     * @param {number} [principalId]
     * @param {boolean} [deleted]
     * @param {boolean} [orphan]
     * @param {Array<string>} [lastModifiedBy]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusGetDeploymentStatus(
      deploymentStatusId?: Array<number>,
      deploymentStatusDescription?: Array<string>,
      rule?: Array<number>,
      plannedActivityResourceAllowed?: Array<string>,
      readOnlyPlannedActivity?: Array<boolean>,
      checkPlannedActivity?: Array<boolean>,
      defaultValue?: Array<boolean>,
      sortBy?: string,
      isSortAscending?: boolean,
      page?: number,
      pageSize?: number,
      lastModifiedStartDate?: Date,
      lastModifiedEndDate?: Date,
      principalId?: number,
      deleted?: boolean,
      orphan?: boolean,
      lastModifiedBy?: Array<string>,
      options: any = {}
    ): FetchArgs {
      const localVarPath = `/api/DeploymentStatus`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (deploymentStatusId) {
        localVarQueryParameter["DeploymentStatusId"] = deploymentStatusId;
      }

      if (deploymentStatusDescription) {
        localVarQueryParameter["DeploymentStatusDescription"] =
          deploymentStatusDescription;
      }

      if (rule) {
        localVarQueryParameter["Rule"] = rule;
      }

      if (plannedActivityResourceAllowed) {
        localVarQueryParameter["PlannedActivityResourceAllowed"] =
          plannedActivityResourceAllowed;
      }

      if (readOnlyPlannedActivity) {
        localVarQueryParameter["ReadOnlyPlannedActivity"] =
          readOnlyPlannedActivity;
      }

      if (checkPlannedActivity) {
        localVarQueryParameter["CheckPlannedActivity"] = checkPlannedActivity;
      }

      if (defaultValue) {
        localVarQueryParameter["DefaultValue"] = defaultValue;
      }

      if (sortBy !== undefined) {
        localVarQueryParameter["SortBy"] = sortBy;
      }

      if (isSortAscending !== undefined) {
        localVarQueryParameter["IsSortAscending"] = isSortAscending;
      }

      if (page !== undefined) {
        localVarQueryParameter["Page"] = page;
      }

      if (pageSize !== undefined) {
        localVarQueryParameter["PageSize"] = pageSize;
      }

      if (lastModifiedStartDate !== undefined) {
        localVarQueryParameter["LastModified.StartDate"] = (
          lastModifiedStartDate as any
        ).toISOString();
      }

      if (lastModifiedEndDate !== undefined) {
        localVarQueryParameter["LastModified.EndDate"] = (
          lastModifiedEndDate as any
        ).toISOString();
      }

      if (principalId !== undefined) {
        localVarQueryParameter["PrincipalId"] = principalId;
      }

      if (deleted !== undefined) {
        localVarQueryParameter["Deleted"] = deleted;
      }

      if (orphan !== undefined) {
        localVarQueryParameter["Orphan"] = orphan;
      }

      if (lastModifiedBy) {
        localVarQueryParameter["LastModifiedBy"] = lastModifiedBy;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} [propertyName]
     * @param {string} [propertyFilter]
     * @param {Array<number>} [deploymentStatusId]
     * @param {Array<string>} [deploymentStatusDescription]
     * @param {Array<number>} [rule]
     * @param {Array<string>} [plannedActivityResourceAllowed]
     * @param {Array<boolean>} [readOnlyPlannedActivity]
     * @param {Array<boolean>} [checkPlannedActivity]
     * @param {Array<boolean>} [defaultValue]
     * @param {string} [sortBy]
     * @param {boolean} [isSortAscending]
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {Date} [lastModifiedStartDate]
     * @param {Date} [lastModifiedEndDate]
     * @param {number} [principalId]
     * @param {boolean} [deleted]
     * @param {boolean} [orphan]
     * @param {Array<string>} [lastModifiedBy]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusGetFilterResult(
      propertyName?: string,
      propertyFilter?: string,
      deploymentStatusId?: Array<number>,
      deploymentStatusDescription?: Array<string>,
      rule?: Array<number>,
      plannedActivityResourceAllowed?: Array<string>,
      readOnlyPlannedActivity?: Array<boolean>,
      checkPlannedActivity?: Array<boolean>,
      defaultValue?: Array<boolean>,
      sortBy?: string,
      isSortAscending?: boolean,
      page?: number,
      pageSize?: number,
      lastModifiedStartDate?: Date,
      lastModifiedEndDate?: Date,
      principalId?: number,
      deleted?: boolean,
      orphan?: boolean,
      lastModifiedBy?: Array<string>,
      options: any = {}
    ): FetchArgs {
      const localVarPath = `/api/DeploymentStatus/Filter`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (propertyName !== undefined) {
        localVarQueryParameter["propertyName"] = propertyName;
      }

      if (propertyFilter !== undefined) {
        localVarQueryParameter["propertyFilter"] = propertyFilter;
      }

      if (deploymentStatusId) {
        localVarQueryParameter["DeploymentStatusId"] = deploymentStatusId;
      }

      if (deploymentStatusDescription) {
        localVarQueryParameter["DeploymentStatusDescription"] =
          deploymentStatusDescription;
      }

      if (rule) {
        localVarQueryParameter["Rule"] = rule;
      }

      if (plannedActivityResourceAllowed) {
        localVarQueryParameter["PlannedActivityResourceAllowed"] =
          plannedActivityResourceAllowed;
      }

      if (readOnlyPlannedActivity) {
        localVarQueryParameter["ReadOnlyPlannedActivity"] =
          readOnlyPlannedActivity;
      }

      if (checkPlannedActivity) {
        localVarQueryParameter["CheckPlannedActivity"] = checkPlannedActivity;
      }

      if (defaultValue) {
        localVarQueryParameter["DefaultValue"] = defaultValue;
      }

      if (sortBy !== undefined) {
        localVarQueryParameter["SortBy"] = sortBy;
      }

      if (isSortAscending !== undefined) {
        localVarQueryParameter["IsSortAscending"] = isSortAscending;
      }

      if (page !== undefined) {
        localVarQueryParameter["Page"] = page;
      }

      if (pageSize !== undefined) {
        localVarQueryParameter["PageSize"] = pageSize;
      }

      if (lastModifiedStartDate !== undefined) {
        localVarQueryParameter["LastModified.StartDate"] = (
          lastModifiedStartDate as any
        ).toISOString();
      }

      if (lastModifiedEndDate !== undefined) {
        localVarQueryParameter["LastModified.EndDate"] = (
          lastModifiedEndDate as any
        ).toISOString();
      }

      if (principalId !== undefined) {
        localVarQueryParameter["PrincipalId"] = principalId;
      }

      if (deleted !== undefined) {
        localVarQueryParameter["Deleted"] = deleted;
      }

      if (orphan !== undefined) {
        localVarQueryParameter["Orphan"] = orphan;
      }

      if (lastModifiedBy) {
        localVarQueryParameter["LastModifiedBy"] = lastModifiedBy;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusGetRelatedRecords(
      id: number,
      options: any = {}
    ): FetchArgs {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          "id",
          "Required parameter id was null or undefined when calling deploymentStatusGetRelatedRecords."
        );
      }
      const localVarPath =
        `/api/DeploymentStatus/GetRelatedRecords{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(id))
        );
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusGetUpdateResourceDeploymentStatus(
      id: number,
      options: any = {}
    ): FetchArgs {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          "id",
          "Required parameter id was null or undefined when calling deploymentStatusGetUpdateResourceDeploymentStatus."
        );
      }
      const localVarPath = `/api/DeploymentStatus/Update{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id))
      );
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {DeploymentStatusDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusPut(
      body: DeploymentStatusDto,
      options: any = {}
    ): FetchArgs {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling deploymentStatusPut."
        );
      }
      const localVarPath = `/api/DeploymentStatus`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "PUT" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"DeploymentStatusDto" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * DeploymentStatusApi - functional programming interface
 * @export
 */
export const DeploymentStatusApiFp = function (configuration?: Configuration) {
  return {
    /**
     *
     * @param {DeploymentStatusDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusCreate(
      body: DeploymentStatusDto,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = DeploymentStatusApiFetchParamCreator(
        configuration
      ).deploymentStatusCreate(body, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusDelete(
      id?: number,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = DeploymentStatusApiFetchParamCreator(
        configuration
      ).deploymentStatusDelete(id, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusDeleteDeep(
      id?: number,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = DeploymentStatusApiFetchParamCreator(
        configuration
      ).deploymentStatusDeleteDeep(id, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusGetCreateResourceDeploymentStatus(
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<DeploymentStatusDto> {
      const localVarFetchArgs =
        DeploymentStatusApiFetchParamCreator(
          configuration
        ).deploymentStatusGetCreateResourceDeploymentStatus(options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {Array<number>} [deploymentStatusId]
     * @param {Array<string>} [deploymentStatusDescription]
     * @param {Array<number>} [rule]
     * @param {Array<string>} [plannedActivityResourceAllowed]
     * @param {Array<boolean>} [readOnlyPlannedActivity]
     * @param {Array<boolean>} [checkPlannedActivity]
     * @param {Array<boolean>} [defaultValue]
     * @param {string} [sortBy]
     * @param {boolean} [isSortAscending]
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {Date} [lastModifiedStartDate]
     * @param {Date} [lastModifiedEndDate]
     * @param {number} [principalId]
     * @param {boolean} [deleted]
     * @param {boolean} [orphan]
     * @param {Array<string>} [lastModifiedBy]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusGetDeploymentStatus(
      deploymentStatusId?: Array<number>,
      deploymentStatusDescription?: Array<string>,
      rule?: Array<number>,
      plannedActivityResourceAllowed?: Array<string>,
      readOnlyPlannedActivity?: Array<boolean>,
      checkPlannedActivity?: Array<boolean>,
      defaultValue?: Array<boolean>,
      sortBy?: string,
      isSortAscending?: boolean,
      page?: number,
      pageSize?: number,
      lastModifiedStartDate?: Date,
      lastModifiedEndDate?: Date,
      principalId?: number,
      deleted?: boolean,
      orphan?: boolean,
      lastModifiedBy?: Array<string>,
      options?: any
    ): (
      fetch?: FetchAPI,
      basePath?: string
    ) => Promise<QueryResultDtoOfDeploymentStatusDtoGrid> {
      const localVarFetchArgs = DeploymentStatusApiFetchParamCreator(
        configuration
      ).deploymentStatusGetDeploymentStatus(
        deploymentStatusId,
        deploymentStatusDescription,
        rule,
        plannedActivityResourceAllowed,
        readOnlyPlannedActivity,
        checkPlannedActivity,
        defaultValue,
        sortBy,
        isSortAscending,
        page,
        pageSize,
        lastModifiedStartDate,
        lastModifiedEndDate,
        principalId,
        deleted,
        orphan,
        lastModifiedBy,
        options
      );
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {string} [propertyName]
     * @param {string} [propertyFilter]
     * @param {Array<number>} [deploymentStatusId]
     * @param {Array<string>} [deploymentStatusDescription]
     * @param {Array<number>} [rule]
     * @param {Array<string>} [plannedActivityResourceAllowed]
     * @param {Array<boolean>} [readOnlyPlannedActivity]
     * @param {Array<boolean>} [checkPlannedActivity]
     * @param {Array<boolean>} [defaultValue]
     * @param {string} [sortBy]
     * @param {boolean} [isSortAscending]
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {Date} [lastModifiedStartDate]
     * @param {Date} [lastModifiedEndDate]
     * @param {number} [principalId]
     * @param {boolean} [deleted]
     * @param {boolean} [orphan]
     * @param {Array<string>} [lastModifiedBy]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusGetFilterResult(
      propertyName?: string,
      propertyFilter?: string,
      deploymentStatusId?: Array<number>,
      deploymentStatusDescription?: Array<string>,
      rule?: Array<number>,
      plannedActivityResourceAllowed?: Array<string>,
      readOnlyPlannedActivity?: Array<boolean>,
      checkPlannedActivity?: Array<boolean>,
      defaultValue?: Array<boolean>,
      sortBy?: string,
      isSortAscending?: boolean,
      page?: number,
      pageSize?: number,
      lastModifiedStartDate?: Date,
      lastModifiedEndDate?: Date,
      principalId?: number,
      deleted?: boolean,
      orphan?: boolean,
      lastModifiedBy?: Array<string>,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<Array<FilterValueDto>> {
      const localVarFetchArgs = DeploymentStatusApiFetchParamCreator(
        configuration
      ).deploymentStatusGetFilterResult(
        propertyName,
        propertyFilter,
        deploymentStatusId,
        deploymentStatusDescription,
        rule,
        plannedActivityResourceAllowed,
        readOnlyPlannedActivity,
        checkPlannedActivity,
        defaultValue,
        sortBy,
        isSortAscending,
        page,
        pageSize,
        lastModifiedStartDate,
        lastModifiedEndDate,
        principalId,
        deleted,
        orphan,
        lastModifiedBy,
        options
      );
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusGetRelatedRecords(
      id: number,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = DeploymentStatusApiFetchParamCreator(
        configuration
      ).deploymentStatusGetRelatedRecords(id, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusGetUpdateResourceDeploymentStatus(
      id: number,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<DeploymentStatusDto> {
      const localVarFetchArgs = DeploymentStatusApiFetchParamCreator(
        configuration
      ).deploymentStatusGetUpdateResourceDeploymentStatus(id, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {DeploymentStatusDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusPut(
      body: DeploymentStatusDto,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = DeploymentStatusApiFetchParamCreator(
        configuration
      ).deploymentStatusPut(body, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
  };
};

/**
 * DeploymentStatusApi - factory interface
 * @export
 */
export const DeploymentStatusApiFactory = function (
  configuration?: Configuration,
  fetch?: FetchAPI,
  basePath?: string
) {
  return {
    /**
     *
     * @param {DeploymentStatusDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusCreate(body: DeploymentStatusDto, options?: any) {
      return DeploymentStatusApiFp(configuration).deploymentStatusCreate(
        body,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusDelete(id?: number, options?: any) {
      return DeploymentStatusApiFp(configuration).deploymentStatusDelete(
        id,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusDeleteDeep(id?: number, options?: any) {
      return DeploymentStatusApiFp(configuration).deploymentStatusDeleteDeep(
        id,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusGetCreateResourceDeploymentStatus(options?: any) {
      return DeploymentStatusApiFp(
        configuration
      ).deploymentStatusGetCreateResourceDeploymentStatus(options)(
        fetch,
        basePath
      );
    },
    /**
     *
     * @param {Array<number>} [deploymentStatusId]
     * @param {Array<string>} [deploymentStatusDescription]
     * @param {Array<number>} [rule]
     * @param {Array<string>} [plannedActivityResourceAllowed]
     * @param {Array<boolean>} [readOnlyPlannedActivity]
     * @param {Array<boolean>} [checkPlannedActivity]
     * @param {Array<boolean>} [defaultValue]
     * @param {string} [sortBy]
     * @param {boolean} [isSortAscending]
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {Date} [lastModifiedStartDate]
     * @param {Date} [lastModifiedEndDate]
     * @param {number} [principalId]
     * @param {boolean} [deleted]
     * @param {boolean} [orphan]
     * @param {Array<string>} [lastModifiedBy]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusGetDeploymentStatus(
      deploymentStatusId?: Array<number>,
      deploymentStatusDescription?: Array<string>,
      rule?: Array<number>,
      plannedActivityResourceAllowed?: Array<string>,
      readOnlyPlannedActivity?: Array<boolean>,
      checkPlannedActivity?: Array<boolean>,
      defaultValue?: Array<boolean>,
      sortBy?: string,
      isSortAscending?: boolean,
      page?: number,
      pageSize?: number,
      lastModifiedStartDate?: Date,
      lastModifiedEndDate?: Date,
      principalId?: number,
      deleted?: boolean,
      orphan?: boolean,
      lastModifiedBy?: Array<string>,
      options?: any
    ) {
      return DeploymentStatusApiFp(
        configuration
      ).deploymentStatusGetDeploymentStatus(
        deploymentStatusId,
        deploymentStatusDescription,
        rule,
        plannedActivityResourceAllowed,
        readOnlyPlannedActivity,
        checkPlannedActivity,
        defaultValue,
        sortBy,
        isSortAscending,
        page,
        pageSize,
        lastModifiedStartDate,
        lastModifiedEndDate,
        principalId,
        deleted,
        orphan,
        lastModifiedBy,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {string} [propertyName]
     * @param {string} [propertyFilter]
     * @param {Array<number>} [deploymentStatusId]
     * @param {Array<string>} [deploymentStatusDescription]
     * @param {Array<number>} [rule]
     * @param {Array<string>} [plannedActivityResourceAllowed]
     * @param {Array<boolean>} [readOnlyPlannedActivity]
     * @param {Array<boolean>} [checkPlannedActivity]
     * @param {Array<boolean>} [defaultValue]
     * @param {string} [sortBy]
     * @param {boolean} [isSortAscending]
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {Date} [lastModifiedStartDate]
     * @param {Date} [lastModifiedEndDate]
     * @param {number} [principalId]
     * @param {boolean} [deleted]
     * @param {boolean} [orphan]
     * @param {Array<string>} [lastModifiedBy]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusGetFilterResult(
      propertyName?: string,
      propertyFilter?: string,
      deploymentStatusId?: Array<number>,
      deploymentStatusDescription?: Array<string>,
      rule?: Array<number>,
      plannedActivityResourceAllowed?: Array<string>,
      readOnlyPlannedActivity?: Array<boolean>,
      checkPlannedActivity?: Array<boolean>,
      defaultValue?: Array<boolean>,
      sortBy?: string,
      isSortAscending?: boolean,
      page?: number,
      pageSize?: number,
      lastModifiedStartDate?: Date,
      lastModifiedEndDate?: Date,
      principalId?: number,
      deleted?: boolean,
      orphan?: boolean,
      lastModifiedBy?: Array<string>,
      options?: any
    ) {
      return DeploymentStatusApiFp(
        configuration
      ).deploymentStatusGetFilterResult(
        propertyName,
        propertyFilter,
        deploymentStatusId,
        deploymentStatusDescription,
        rule,
        plannedActivityResourceAllowed,
        readOnlyPlannedActivity,
        checkPlannedActivity,
        defaultValue,
        sortBy,
        isSortAscending,
        page,
        pageSize,
        lastModifiedStartDate,
        lastModifiedEndDate,
        principalId,
        deleted,
        orphan,
        lastModifiedBy,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusGetRelatedRecords(id: number, options?: any) {
      return DeploymentStatusApiFp(
        configuration
      ).deploymentStatusGetRelatedRecords(id, options)(fetch, basePath);
    },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusGetUpdateResourceDeploymentStatus(
      id: number,
      options?: any
    ) {
      return DeploymentStatusApiFp(
        configuration
      ).deploymentStatusGetUpdateResourceDeploymentStatus(id, options)(
        fetch,
        basePath
      );
    },
    /**
     *
     * @param {DeploymentStatusDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deploymentStatusPut(body: DeploymentStatusDto, options?: any) {
      return DeploymentStatusApiFp(configuration).deploymentStatusPut(
        body,
        options
      )(fetch, basePath);
    },
  };
};

/**
 * DeploymentStatusApi - object-oriented interface
 * @export
 * @class DeploymentStatusApi
 * @extends {BaseAPI}
 */
export class DeploymentStatusApi extends BaseAPI {
  /**
   *
   * @param {DeploymentStatusDto} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DeploymentStatusApi
   */
  public deploymentStatusCreate(body: DeploymentStatusDto, options?: any) {
    return DeploymentStatusApiFp(this.configuration).deploymentStatusCreate(
      body,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {number} [id]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DeploymentStatusApi
   */
  public deploymentStatusDelete(id?: number, options?: any) {
    return DeploymentStatusApiFp(this.configuration).deploymentStatusDelete(
      id,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {number} [id]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DeploymentStatusApi
   */
  public deploymentStatusDeleteDeep(id?: number, options?: any) {
    return DeploymentStatusApiFp(this.configuration).deploymentStatusDeleteDeep(
      id,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DeploymentStatusApi
   */
  public deploymentStatusGetCreateResourceDeploymentStatus(options?: any) {
    return DeploymentStatusApiFp(
      this.configuration
    ).deploymentStatusGetCreateResourceDeploymentStatus(options)(
      this.fetch,
      this.basePath
    );
  }

  /**
   *
   * @param {Array<number>} [deploymentStatusId]
   * @param {Array<string>} [deploymentStatusDescription]
   * @param {Array<number>} [rule]
   * @param {Array<string>} [plannedActivityResourceAllowed]
   * @param {Array<boolean>} [readOnlyPlannedActivity]
   * @param {Array<boolean>} [checkPlannedActivity]
   * @param {Array<boolean>} [defaultValue]
   * @param {string} [sortBy]
   * @param {boolean} [isSortAscending]
   * @param {number} [page]
   * @param {number} [pageSize]
   * @param {Date} [lastModifiedStartDate]
   * @param {Date} [lastModifiedEndDate]
   * @param {number} [principalId]
   * @param {boolean} [deleted]
   * @param {boolean} [orphan]
   * @param {Array<string>} [lastModifiedBy]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DeploymentStatusApi
   */
  public deploymentStatusGetDeploymentStatus(
    deploymentStatusId?: Array<number>,
    deploymentStatusDescription?: Array<string>,
    rule?: Array<number>,
    plannedActivityResourceAllowed?: Array<string>,
    readOnlyPlannedActivity?: Array<boolean>,
    checkPlannedActivity?: Array<boolean>,
    defaultValue?: Array<boolean>,
    sortBy?: string,
    isSortAscending?: boolean,
    page?: number,
    pageSize?: number,
    lastModifiedStartDate?: Date,
    lastModifiedEndDate?: Date,
    principalId?: number,
    deleted?: boolean,
    orphan?: boolean,
    lastModifiedBy?: Array<string>,
    options?: any
  ) {
    return DeploymentStatusApiFp(
      this.configuration
    ).deploymentStatusGetDeploymentStatus(
      deploymentStatusId,
      deploymentStatusDescription,
      rule,
      plannedActivityResourceAllowed,
      readOnlyPlannedActivity,
      checkPlannedActivity,
      defaultValue,
      sortBy,
      isSortAscending,
      page,
      pageSize,
      lastModifiedStartDate,
      lastModifiedEndDate,
      principalId,
      deleted,
      orphan,
      lastModifiedBy,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {string} [propertyName]
   * @param {string} [propertyFilter]
   * @param {Array<number>} [deploymentStatusId]
   * @param {Array<string>} [deploymentStatusDescription]
   * @param {Array<number>} [rule]
   * @param {Array<string>} [plannedActivityResourceAllowed]
   * @param {Array<boolean>} [readOnlyPlannedActivity]
   * @param {Array<boolean>} [checkPlannedActivity]
   * @param {Array<boolean>} [defaultValue]
   * @param {string} [sortBy]
   * @param {boolean} [isSortAscending]
   * @param {number} [page]
   * @param {number} [pageSize]
   * @param {Date} [lastModifiedStartDate]
   * @param {Date} [lastModifiedEndDate]
   * @param {number} [principalId]
   * @param {boolean} [deleted]
   * @param {boolean} [orphan]
   * @param {Array<string>} [lastModifiedBy]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DeploymentStatusApi
   */
  public deploymentStatusGetFilterResult(
    propertyName?: string,
    propertyFilter?: string,
    deploymentStatusId?: Array<number>,
    deploymentStatusDescription?: Array<string>,
    rule?: Array<number>,
    plannedActivityResourceAllowed?: Array<string>,
    readOnlyPlannedActivity?: Array<boolean>,
    checkPlannedActivity?: Array<boolean>,
    defaultValue?: Array<boolean>,
    sortBy?: string,
    isSortAscending?: boolean,
    page?: number,
    pageSize?: number,
    lastModifiedStartDate?: Date,
    lastModifiedEndDate?: Date,
    principalId?: number,
    deleted?: boolean,
    orphan?: boolean,
    lastModifiedBy?: Array<string>,
    options?: any
  ) {
    return DeploymentStatusApiFp(
      this.configuration
    ).deploymentStatusGetFilterResult(
      propertyName,
      propertyFilter,
      deploymentStatusId,
      deploymentStatusDescription,
      rule,
      plannedActivityResourceAllowed,
      readOnlyPlannedActivity,
      checkPlannedActivity,
      defaultValue,
      sortBy,
      isSortAscending,
      page,
      pageSize,
      lastModifiedStartDate,
      lastModifiedEndDate,
      principalId,
      deleted,
      orphan,
      lastModifiedBy,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {number} id
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DeploymentStatusApi
   */
  public deploymentStatusGetRelatedRecords(id: number, options?: any) {
    return DeploymentStatusApiFp(
      this.configuration
    ).deploymentStatusGetRelatedRecords(id, options)(this.fetch, this.basePath);
  }

  /**
   *
   * @param {number} id
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DeploymentStatusApi
   */
  public deploymentStatusGetUpdateResourceDeploymentStatus(
    id: number,
    options?: any
  ) {
    return DeploymentStatusApiFp(
      this.configuration
    ).deploymentStatusGetUpdateResourceDeploymentStatus(id, options)(
      this.fetch,
      this.basePath
    );
  }

  /**
   *
   * @param {DeploymentStatusDto} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DeploymentStatusApi
   */
  public deploymentStatusPut(body: DeploymentStatusDto, options?: any) {
    return DeploymentStatusApiFp(this.configuration).deploymentStatusPut(
      body,
      options
    )(this.fetch, this.basePath);
  }
}
