/* eslint-disable @typescript-eslint/consistent-type-assertions */
/// <reference path="../Common/custom.d.ts" />
// tslint:disable
/**
 * Cam Vodafone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "../Common/configuration";
import { headerObj } from "../header";

import {
  DataRemediationDto,
  ResultDto,
  ResultDtoOfResultDataRemediationDto,
} from "../../Model/CommonModels";
import {
  BASE_PATH,
  FetchArgs,
  FetchAPI,
  RequiredError,
  FilterValueDto,
} from "../Common/CommonBusiness";
import { BaseAPI } from "../Common/CommonBusiness";
import {
  LcmEngineeringDtoCreate,
  LcmEngineeringDtoUpdate,
  QueryResultDtoOfLcmEngineeringDtoGrid,
} from "../../Model/LcmEngineering";
import { FileResult, ReturnFile } from "../../Model/Common";
import {
  QueryResultDtoOfTipologicaGridDto,
  TipologicaGridDto,
} from "../../Model/LookUp/LookUpGenericModel";
import {
  InterVMTypeDto,
  InterVMTypeQueryObjectGrid,
  QueryResultDtoOfInterVMTypeDtoGrid,
} from "../../Model/LookUp/InterVMType";
/**
 * InterVMTypeApi - fetch parameter creator
 * @export
 */
export const InterVMTypeApiFetchParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @param {InterVMTypeDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeCreate(body: InterVMTypeDto, options: any = {}): FetchArgs {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling InterVMTypeCreate."
        );
      }
      const localVarPath = `/api/InterVmType/Create`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "POST" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"InterVMTypeDto" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeDelete(id?: number, options: any = {}): FetchArgs {
      const localVarPath = `/api/InterVmType/DeleteDeep`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign(
        { method: "DELETE" },
        options
      );
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (id !== undefined) {
        localVarQueryParameter["id"] = id;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeDeleteDeep(id?: number, options: any = {}): FetchArgs {
      const localVarPath = `/api/InterVmType/DeleteDeep`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign(
        { method: "DELETE" },
        options
      );
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (id !== undefined) {
        localVarQueryParameter["id"] = id;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeGetCreatepage(options: any = {}): FetchArgs {
      const localVarPath = `/api/InterVmType/GetCreatepage`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} [propertyName]
     * @param {string} [propertyFilter]
     * @param {Array<number>} [id]
     * @param {Array<string>} [description]
     * @param {Array<number>} [opco]
     * @param {Array<number>} [locationType]
     * @param {string} [sortBy]
     * @param {boolean} [isSortAscending]
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {Date} [lastModifiedStartDate]
     * @param {Date} [lastModifiedEndDate]
     * @param {number} [principalId]
     * @param {boolean} [deleted]
     * @param {boolean} [orphan]
     * @param {Array<string>} [lastModifiedBy]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeGetFilterResult(
      propertyName?: string,
      propertyFilter?: string,
      interdescription?: Array<string>,
      intervmtypeid?: Array<number>,
      sortBy?: string,
      isSortAscending?: boolean,
      page?: number,
      pageSize?: number,
      lastModifiedStartDate?: Date,
      lastModifiedEndDate?: Date,
      principalId?: number,
      deleted?: boolean,
      orphan?: boolean,
      lastModifiedBy?: Array<string>,
      options: any = {}
    ): FetchArgs {
      const localVarPath = `/api/InterVmType/Filter`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "POST" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (propertyName !== undefined) {
        localVarQueryParameter["propertyName"] = propertyName;
      }

      if (propertyFilter !== undefined) {
        localVarQueryParameter["propertyFilter"] = propertyFilter;
      }

      if (interdescription) {
        localVarQueryParameter["interDescription"] = interdescription;
      }

      if (intervmtypeid) {
        localVarQueryParameter["interVmTypeId"] = intervmtypeid;
      }

      if (sortBy !== undefined) {
        localVarQueryParameter["SortBy"] = sortBy;
      }

      if (isSortAscending !== undefined) {
        localVarQueryParameter["IsSortAscending"] = isSortAscending;
      }

      if (page !== undefined) {
        localVarQueryParameter["Page"] = page;
      }

      if (pageSize !== undefined) {
        localVarQueryParameter["PageSize"] = pageSize;
      }

      if (lastModifiedStartDate !== undefined) {
        localVarQueryParameter["LastModified.StartDate"] = (
          lastModifiedStartDate as any
        ).toISOString();
      }

      if (lastModifiedEndDate !== undefined) {
        localVarQueryParameter["LastModified.EndDate"] = (
          lastModifiedEndDate as any
        ).toISOString();
      }

      if (principalId !== undefined) {
        localVarQueryParameter["PrincipalId"] = principalId;
      }

      if (deleted !== undefined) {
        localVarQueryParameter["Deleted"] = deleted;
      }

      if (orphan !== undefined) {
        localVarQueryParameter["Orphan"] = orphan;
      }

      if (lastModifiedBy) {
        localVarQueryParameter["LastModifiedBy"] = lastModifiedBy;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {InterVMTypeQueryObjectGrid} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeGet(
      body?: InterVMTypeQueryObjectGrid,
      options: any = {}
    ): FetchArgs {
      const localVarPath = `/api/InterVmType/Get`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "POST" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }
      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      const needsSerialization =
        <any>"InterVMTypeDto" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    // /**
    //  *
    //  * @param {number} id
    //  * @param {*} [options] Override http request option.
    //  * @throws {RequiredError}
    //  */
    // locationGetRelatedRecords(id: number, options: any = {}): FetchArgs {
    //   // verify required parameter 'id' is not null or undefined
    //   if (id === null || id === undefined) {
    //     throw new RequiredError(
    //       "id",
    //       "Required parameter id was null or undefined when calling locationGetRelatedRecords."
    //     );
    //   }
    //   const localVarPath = `/api/Location/GetRelatedRecords{id}`.replace(
    //     `{${"id"}}`,
    //     encodeURIComponent(String(id))
    //   );
    //   const localVarUrlObj = url.parse(localVarPath, true);
    //   const localVarRequestOptions = Object.assign({ method: "GET" }, options);
    //   const localVarHeaderParameter = { ...headerObj } as any;
    //   const localVarQueryParameter = {} as any;

    //   // authentication JWT required
    //   if (configuration && configuration.apiKey) {
    //     const localVarApiKeyValue =
    //       typeof configuration.apiKey === "function"
    //         ? configuration.apiKey("Authorization")
    //         : configuration.apiKey;
    //     localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
    //   }

    //   localVarUrlObj.query = Object.assign(
    //     {},
    //     localVarUrlObj.query,
    //     localVarQueryParameter,
    //     options.query
    //   );
    //   // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
    //   localVarUrlObj.search = null;
    //   localVarRequestOptions.headers = Object.assign(
    //     {},
    //     localVarHeaderParameter,
    //     options.headers
    //   );

    //   return {
    //     url: url.format(localVarUrlObj),
    //     options: localVarRequestOptions,
    //   };
    // },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeGetUpdatedPage(id: number, options: any = {}): FetchArgs {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          "id",
          "Required parameter id was null or undefined when calling InterVMTypeGetUpdatedPage."
        );
      }
      const localVarPath = `/api/InterVmType/GetUpdatedPage`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (id !== undefined) {
        localVarQueryParameter["id"] = id;
      }
      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {InterVMTypeDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeUpdate(body: InterVMTypeDto, options: any = {}): FetchArgs {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling InterVMTypeUpdate."
        );
      }
      const localVarPath = `/api/InterVmType/Update`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "PUT" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"InterVMTypeDto" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * InterVMTypeApi - functional programming interface
 * @export
 */
export const InterVMTypeApiFp = function (configuration?: Configuration) {
  return {
    /**
     *
     * @param {InterVMTypeDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeCreate(
      body: InterVMTypeDto,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = InterVMTypeApiFetchParamCreator(
        configuration
      ).InterVMTypeCreate(body, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeDelete(
      id?: number,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = InterVMTypeApiFetchParamCreator(
        configuration
      ).InterVMTypeDelete(id, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeDeleteDeep(
      id?: number,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = InterVMTypeApiFetchParamCreator(
        configuration
      ).InterVMTypeDeleteDeep(id, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeGetCreatepage(
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<InterVMTypeDto> {
      const localVarFetchArgs =
        InterVMTypeApiFetchParamCreator(configuration).InterVMTypeGetCreatepage(
          options
        );
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {string} [propertyName]
     * @param {string} [propertyFilter]
     * @param {Array<number>} [id]
     * @param {Array<string>} [description]
     * @param {Array<number>} [opco]
     * @param {Array<number>} [locationType]
     * @param {string} [sortBy]
     * @param {boolean} [isSortAscending]
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {Date} [lastModifiedStartDate]
     * @param {Date} [lastModifiedEndDate]
     * @param {number} [principalId]
     * @param {boolean} [deleted]
     * @param {boolean} [orphan]
     * @param {Array<string>} [lastModifiedBy]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeGetFilterResult(
      propertyName?: string,
      propertyFilter?: string,
      interdescription?: Array<string>,
      intervmtypeid?: Array<number>,
      sortBy?: string,
      isSortAscending?: boolean,
      page?: number,
      pageSize?: number,
      lastModifiedStartDate?: Date,
      lastModifiedEndDate?: Date,
      principalId?: number,
      deleted?: boolean,
      orphan?: boolean,
      lastModifiedBy?: Array<string>,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<Array<FilterValueDto>> {
      const localVarFetchArgs = InterVMTypeApiFetchParamCreator(
        configuration
      ).InterVMTypeGetFilterResult(
        propertyName,
        propertyFilter,
        interdescription,
        intervmtypeid,
        sortBy,
        isSortAscending,
        page,
        pageSize,
        lastModifiedStartDate,
        lastModifiedEndDate,
        principalId,
        deleted,
        orphan,
        lastModifiedBy,
        options
      );
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {InterVMTypeQueryObjectGrid} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeGet(
      body?: InterVMTypeQueryObjectGrid,
      options?: any
    ): (
      fetch?: FetchAPI,
      basePath?: string
    ) => Promise<QueryResultDtoOfInterVMTypeDtoGrid> {
      const localVarFetchArgs = InterVMTypeApiFetchParamCreator(
        configuration
      ).InterVMTypeGet(body, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    // /**
    //  *
    //  * @param {number} id
    //  * @param {*} [options] Override http request option.
    //  * @throws {RequiredError}
    //  */
    // locationGetRelatedRecords(
    //   id: number,
    //   options?: any
    // ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
    //   const localVarFetchArgs = InterVMTypeApiFetchParamCreator(
    //     configuration
    //   ).locationGetRelatedRecords(id, options);
    //   return (
    //     fetch: FetchAPI = isomorphicFetch,
    //     basePath = BASE_PATH
    //   ) => {
    //     return fetch(
    //       basePath + localVarFetchArgs.url,
    //       localVarFetchArgs.options
    //     ).then((response) => {
    //       if (response.status >= 200 && response.status < 300) {
    //         return response.json();
    //       } else {
    //         throw response;
    //       }
    //     });
    //   };
    // },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeGetUpdatedPage(
      id: number,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<InterVMTypeDto> {
      const localVarFetchArgs = InterVMTypeApiFetchParamCreator(
        configuration
      ).InterVMTypeGetUpdatedPage(id, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {InterVMTypeDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeUpdate(
      body: InterVMTypeDto,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = InterVMTypeApiFetchParamCreator(
        configuration
      ).InterVMTypeUpdate(body, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
  };
};

/**
 * InterVMTypeApi - factory interface
 * @export
 */
export const InterVMTypeApiFactory = function (
  configuration?: Configuration,
  fetch?: FetchAPI,
  basePath?: string
) {
  return {
    /**
     *
     * @param {InterVMTypeDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeCreate(body: InterVMTypeDto, options?: any) {
      return InterVMTypeApiFp(configuration).InterVMTypeCreate(body, options)(
        fetch,
        basePath
      );
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeDelete(id?: number, options?: any) {
      return InterVMTypeApiFp(configuration).InterVMTypeDelete(id, options)(
        fetch,
        basePath
      );
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeDeleteDeep(id?: number, options?: any) {
      return InterVMTypeApiFp(configuration).InterVMTypeDeleteDeep(id, options)(
        fetch,
        basePath
      );
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeGetCreatepage(options?: any) {
      return InterVMTypeApiFp(configuration).InterVMTypeGetCreatepage(options)(
        fetch,
        basePath
      );
    },
    /**
     *
     * @param {string} [propertyName]
     * @param {string} [propertyFilter]
     * @param {Array<number>} [id]
     * @param {Array<string>} [description]
     * @param {Array<number>} [opco]
     * @param {Array<number>} [locationType]
     * @param {string} [sortBy]
     * @param {boolean} [isSortAscending]
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {Date} [lastModifiedStartDate]
     * @param {Date} [lastModifiedEndDate]
     * @param {number} [principalId]
     * @param {boolean} [deleted]
     * @param {boolean} [orphan]
     * @param {Array<string>} [lastModifiedBy]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeGetFilterResult(
      propertyName?: string,
      propertyFilter?: string,
      interdescription?: Array<string>,
      intervmtypeid?: Array<number>,
      sortBy?: string,
      isSortAscending?: boolean,
      page?: number,
      pageSize?: number,
      lastModifiedStartDate?: Date,
      lastModifiedEndDate?: Date,
      principalId?: number,
      deleted?: boolean,
      orphan?: boolean,
      lastModifiedBy?: Array<string>,
      options?: any
    ) {
      return InterVMTypeApiFp(configuration).InterVMTypeGetFilterResult(
        propertyName,
        propertyFilter,
        interdescription,
        intervmtypeid,
        sortBy,
        isSortAscending,
        page,
        pageSize,
        lastModifiedStartDate,
        lastModifiedEndDate,
        principalId,
        deleted,
        orphan,
        lastModifiedBy,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {InterVMTypeQueryObjectGrid} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeGet(body?: InterVMTypeQueryObjectGrid, options?: any) {
      return InterVMTypeApiFp(configuration).InterVMTypeGet(body, options)(
        fetch,
        basePath
      );
    },
    // /**
    //  *
    //  * @param {number} id
    //  * @param {*} [options] Override http request option.
    //  * @throws {RequiredError}
    //  */
    // locationGetRelatedRecords(id: number, options?: any) {
    //   return InterVMTypeApiFp(configuration).locationGetRelatedRecords(
    //     id,
    //     options
    //   )(fetch, basePath);
    // },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeGetUpdatedPage(id: number, options?: any) {
      return InterVMTypeApiFp(configuration).InterVMTypeGetUpdatedPage(
        id,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {InterVMTypeDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    InterVMTypeUpdate(body: InterVMTypeDto, options?: any) {
      return InterVMTypeApiFp(configuration).InterVMTypeUpdate(body, options)(
        fetch,
        basePath
      );
    },
  };
};

/**
 * InterVMTypeApi - object-oriented interface
 * @export
 * @class InterVMTypeApi
 * @extends {BaseAPI}
 */
export class InterVMTypeApi extends BaseAPI {
  /**
   *
   * @param {InterVMTypeDto} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof InterVMTypeApi
   */
  public InterVMTypeCreate(body: InterVMTypeDto, options?: any) {
    return InterVMTypeApiFp(this.configuration).InterVMTypeCreate(
      body,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {number} [id]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof InterVMTypeApi
   */
  public InterVMTypeDelete(id?: number, options?: any) {
    return InterVMTypeApiFp(this.configuration).InterVMTypeDelete(id, options)(
      this.fetch,
      this.basePath
    );
  }

  /**
   *
   * @param {number} [id]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof InterVMTypeApi
   */
  public InterVMTypeDeleteDeep(id?: number, options?: any) {
    return InterVMTypeApiFp(this.configuration).InterVMTypeDeleteDeep(
      id,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof InterVMTypeApi
   */
  public InterVMTypeGetCreatepage(options?: any) {
    return InterVMTypeApiFp(this.configuration).InterVMTypeGetCreatepage(
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {string} [propertyName]
   * @param {string} [propertyFilter]
   * @param {Array<number>} [id]
   * @param {Array<string>} [description]
   * @param {Array<number>} [opco]
   * @param {Array<number>} [locationType]
   * @param {string} [sortBy]
   * @param {boolean} [isSortAscending]
   * @param {number} [page]
   * @param {number} [pageSize]
   * @param {Date} [lastModifiedStartDate]
   * @param {Date} [lastModifiedEndDate]
   * @param {number} [principalId]
   * @param {boolean} [deleted]
   * @param {boolean} [orphan]
   * @param {Array<string>} [lastModifiedBy]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof InterVMTypeApi
   */
  public InterVMTypeGetFilterResult(
    propertyName?: string,
    propertyFilter?: string,
    interdescription?: Array<string>,
    intervmtypeid?: Array<number>,
    sortBy?: string,
    isSortAscending?: boolean,
    page?: number,
    pageSize?: number,
    lastModifiedStartDate?: Date,
    lastModifiedEndDate?: Date,
    principalId?: number,
    deleted?: boolean,
    orphan?: boolean,
    lastModifiedBy?: Array<string>,
    options?: any
  ) {
    return InterVMTypeApiFp(this.configuration).InterVMTypeGetFilterResult(
      propertyName,
      propertyFilter,
      interdescription,
      intervmtypeid,
      sortBy,
      isSortAscending,
      page,
      pageSize,
      lastModifiedStartDate,
      lastModifiedEndDate,
      principalId,
      deleted,
      orphan,
      lastModifiedBy,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {InterVMTypeQueryObjectGrid} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof InterVMTypeApi
   */
  public InterVMTypeGet(body?: InterVMTypeQueryObjectGrid, options?: any) {
    return InterVMTypeApiFp(this.configuration).InterVMTypeGet(body, options)(
      this.fetch,
      this.basePath
    );
  }

  //   /**
  //    *
  //    * @param {number} id
  //    * @param {*} [options] Override http request option.
  //    * @throws {RequiredError}
  //    * @memberof InterVMTypeApi
  //    */
  //   public locationGetRelatedRecords(id: number, options?: any) {
  //     return InterVMTypeApiFp(this.configuration).locationGetRelatedRecords(
  //       id,
  //       options
  //     )(this.fetch, this.basePath);
  //   }

  /**
   *
   * @param {number} id
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof InterVMTypeApi
   */
  public InterVMTypeGetUpdatedPage(id: number, options?: any) {
    return InterVMTypeApiFp(this.configuration).InterVMTypeGetUpdatedPage(
      id,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {InterVMTypeDto} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof InterVMTypeApi
   */
  public InterVMTypeUpdate(body: InterVMTypeDto, options?: any) {
    return InterVMTypeApiFp(this.configuration).InterVMTypeUpdate(
      body,
      options
    )(this.fetch, this.basePath);
  }
}
