/* eslint-disable @typescript-eslint/consistent-type-assertions */
/// <reference path="../Common/custom.d.ts" />
// tslint:disable
/**
 * Cam Vodafone
 * No vmtypedescription provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "../Common/configuration";
import { headerObj } from "../header";

import {
  DataRemediationDto,
  ResultDto,
  ResultDtoOfResultDataRemediationDto,
} from "../../Model/CommonModels";
import {
  BASE_PATH,
  FetchArgs,
  FetchAPI,
  RequiredError,
  FilterValueDto,
} from "../Common/CommonBusiness";
import { BaseAPI } from "../Common/CommonBusiness";
import {
  LcmEngineeringDtoCreate,
  LcmEngineeringDtoUpdate,
  QueryResultDtoOfLcmEngineeringDtoGrid,
} from "../../Model/LcmEngineering";
import { FileResult, ReturnFile } from "../../Model/Common";
import {
  QueryResultDtoOfTipologicaGridDto,
  TipologicaGridDto,
} from "../../Model/LookUp/LookUpGenericModel";
import {
  VMTypeNameDto,
  VMTypeNameQueryObjectGrid,
  QueryResultDtoOfVMTypeNameDtoGrid,
} from "../../Model/LookUp/VMTypeName";
/**
 * VMTypeNameApi - fetch parameter creator
 * @export
 */
export const VMTypeNameApiFetchParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @param {VMTypeNameDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameCreate(body: VMTypeNameDto, options: any = {}): FetchArgs {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling VMTypeNameCreate."
        );
      }
      const localVarPath = `/api/VmTypeName/Create`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "POST" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"VMTypeNameDto" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameDelete(id?: number, options: any = {}): FetchArgs {
      const localVarPath = `/api/VmTypeName/DeleteDeep`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign(
        { method: "DELETE" },
        options
      );
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (id !== undefined) {
        localVarQueryParameter["id"] = id;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameDeleteDeep(id?: number, options: any = {}): FetchArgs {
      const localVarPath = `/api/VmTypeName/DeleteDeep`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign(
        { method: "DELETE" },
        options
      );
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (id !== undefined) {
        localVarQueryParameter["id"] = id;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameGetCreatepage(options: any = {}): FetchArgs {
      const localVarPath = `/api/VmTypeName/GetCreatepage`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} [propertyName]
     * @param {string} [propertyFilter]
     * @param {Array<number>} [id]
     * @param {Array<string>} [description]
     * @param {Array<number>} [opco]
     * @param {Array<number>} [locationType]
     * @param {string} [sortBy]
     * @param {boolean} [isSortAscending]
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {Date} [lastModifiedStartDate]
     * @param {Date} [lastModifiedEndDate]
     * @param {number} [principalId]
     * @param {boolean} [deleted]
     * @param {boolean} [orphan]
     * @param {Array<string>} [lastModifiedBy]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameGetFilterResult(
      propertyName?: string,
      propertyFilter?: string,
      vmtypedescription?: Array<string>,
      vmtypenameid?: Array<number>,
      vnfName?: Array<string>,
      vnfnameid?: Array<number>,
      sortBy?: string,
      isSortAscending?: boolean,
      page?: number,
      pageSize?: number,
      lastModifiedStartDate?: Date,
      lastModifiedEndDate?: Date,
      principalId?: number,
      deleted?: boolean,
      orphan?: boolean,
      lastModifiedBy?: Array<string>,
      options?: any
    ): FetchArgs {
      const localVarPath = `/api/VmTypeName/Filter`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "POST" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (propertyName !== undefined) {
        localVarQueryParameter["propertyName"] = propertyName;
      }

      if (propertyFilter !== undefined) {
        localVarQueryParameter["propertyFilter"] = propertyFilter;
      }

      if (vmtypedescription) {
        localVarQueryParameter["vmTypeDescription"] = vmtypedescription;
      }

      if (vmtypenameid) {
        localVarQueryParameter["vmTypeNameId"] = vmtypenameid;
      }

      if (vnfName) {
        localVarQueryParameter["vnfName"] = vnfName;
      }

      if (vnfnameid) {
        localVarQueryParameter["vnfNameId"] = vnfnameid;
      }

      if (sortBy !== undefined) {
        localVarQueryParameter["SortBy"] = sortBy;
      }

      if (isSortAscending !== undefined) {
        localVarQueryParameter["IsSortAscending"] = isSortAscending;
      }

      if (page !== undefined) {
        localVarQueryParameter["Page"] = page;
      }

      if (pageSize !== undefined) {
        localVarQueryParameter["PageSize"] = pageSize;
      }

      if (lastModifiedStartDate !== undefined) {
        localVarQueryParameter["LastModified.StartDate"] = (
          lastModifiedStartDate as any
        ).toISOString();
      }

      if (lastModifiedEndDate !== undefined) {
        localVarQueryParameter["LastModified.EndDate"] = (
          lastModifiedEndDate as any
        ).toISOString();
      }

      if (principalId !== undefined) {
        localVarQueryParameter["PrincipalId"] = principalId;
      }

      if (deleted !== undefined) {
        localVarQueryParameter["Deleted"] = deleted;
      }

      if (orphan !== undefined) {
        localVarQueryParameter["Orphan"] = orphan;
      }

      if (lastModifiedBy) {
        localVarQueryParameter["LastModifiedBy"] = lastModifiedBy;
      }

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {VMTypeNameQueryObjectGrid} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameGet(
      body?: VMTypeNameQueryObjectGrid,
      options: any = {}
    ): FetchArgs {
      const localVarPath = `/api/VmTypeName/Get`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "POST" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }
      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      const needsSerialization =
        <any>"VMTypeNameDto" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    // /**
    //  *
    //  * @param {number} id
    //  * @param {*} [options] Override http request option.
    //  * @throws {RequiredError}
    //  */
    // locationGetRelatedRecords(id: number, options: any = {}): FetchArgs {
    //   // verify required parameter 'id' is not null or undefined
    //   if (id === null || id === undefined) {
    //     throw new RequiredError(
    //       "id",
    //       "Required parameter id was null or undefined when calling locationGetRelatedRecords."
    //     );
    //   }
    //   const localVarPath = `/api/Location/GetRelatedRecords{id}`.replace(
    //     `{${"id"}}`,
    //     encodeURIComponent(String(id))
    //   );
    //   const localVarUrlObj = url.parse(localVarPath, true);
    //   const localVarRequestOptions = Object.assign({ method: "GET" }, options);
    //   const localVarHeaderParameter = { ...headerObj } as any;
    //   const localVarQueryParameter = {} as any;

    //   // authentication JWT required
    //   if (configuration && configuration.apiKey) {
    //     const localVarApiKeyValue =
    //       typeof configuration.apiKey === "function"
    //         ? configuration.apiKey("Authorization")
    //         : configuration.apiKey;
    //     localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
    //   }

    //   localVarUrlObj.query = Object.assign(
    //     {},
    //     localVarUrlObj.query,
    //     localVarQueryParameter,
    //     options.query
    //   );
    //   // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
    //   localVarUrlObj.search = null;
    //   localVarRequestOptions.headers = Object.assign(
    //     {},
    //     localVarHeaderParameter,
    //     options.headers
    //   );

    //   return {
    //     url: url.format(localVarUrlObj),
    //     options: localVarRequestOptions,
    //   };
    // },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameGetUpdatedPage(id: number, options: any = {}): FetchArgs {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          "id",
          "Required parameter id was null or undefined when calling VMTypeNameGetUpdatedPage."
        );
      }
      const localVarPath = `/api/VmTypeName/GetUpdatedPage`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      if (id !== undefined) {
        localVarQueryParameter["id"] = id;
      }
      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {VMTypeNameDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameUpdate(body: VMTypeNameDto, options: any = {}): FetchArgs {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling VMTypeNameUpdate."
        );
      }
      const localVarPath = `/api/VmTypeName/Update`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "PUT" }, options);
      const localVarHeaderParameter = { ...headerObj } as any;
      const localVarQueryParameter = {} as any;

      // authentication JWT required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === "function"
            ? configuration.apiKey("Authorization")
            : configuration.apiKey;
        localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"VMTypeNameDto" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * VMTypeNameApi - functional programming interface
 * @export
 */
export const VMTypeNameApiFp = function (configuration?: Configuration) {
  return {
    /**
     *
     * @param {VMTypeNameDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameCreate(
      body: VMTypeNameDto,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = VMTypeNameApiFetchParamCreator(
        configuration
      ).VMTypeNameCreate(body, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameDelete(
      id?: number,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = VMTypeNameApiFetchParamCreator(
        configuration
      ).VMTypeNameDelete(id, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameDeleteDeep(
      id?: number,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = VMTypeNameApiFetchParamCreator(
        configuration
      ).VMTypeNameDeleteDeep(id, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameGetCreatepage(
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<VMTypeNameDto> {
      const localVarFetchArgs =
        VMTypeNameApiFetchParamCreator(configuration).VMTypeNameGetCreatepage(
          options
        );
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {string} [propertyName]
     * @param {string} [propertyFilter]
     * @param {Array<number>} [id]
     * @param {Array<string>} [description]
     * @param {Array<number>} [opco]
     * @param {Array<number>} [locationType]
     * @param {string} [sortBy]
     * @param {boolean} [isSortAscending]
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {Date} [lastModifiedStartDate]
     * @param {Date} [lastModifiedEndDate]
     * @param {number} [principalId]
     * @param {boolean} [deleted]
     * @param {boolean} [orphan]
     * @param {Array<string>} [lastModifiedBy]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameGetFilterResult(
      propertyName?: string,
      propertyFilter?: string,
      vmtypedescription?: Array<string>,
      vmtypenameid?: Array<number>,
      vnfName?: Array<string>,
      vnfnameid?: Array<number>,
      sortBy?: string,
      isSortAscending?: boolean,
      page?: number,
      pageSize?: number,
      lastModifiedStartDate?: Date,
      lastModifiedEndDate?: Date,
      principalId?: number,
      deleted?: boolean,
      orphan?: boolean,
      lastModifiedBy?: Array<string>,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<Array<FilterValueDto>> {
      const localVarFetchArgs = VMTypeNameApiFetchParamCreator(
        configuration
      ).VMTypeNameGetFilterResult(
        propertyName,
        propertyFilter,
        vmtypedescription,
        vmtypenameid,
        vnfName,
        vnfnameid,
        sortBy,
        isSortAscending,
        page,
        pageSize,
        lastModifiedStartDate,
        lastModifiedEndDate,
        principalId,
        deleted,
        orphan,
        lastModifiedBy,
        options
      );
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {VMTypeNameGetCreatepage} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameGet(
      body?: VMTypeNameQueryObjectGrid,
      options?: any
    ): (
      fetch?: FetchAPI,
      basePath?: string
    ) => Promise<QueryResultDtoOfVMTypeNameDtoGrid> {
      const localVarFetchArgs = VMTypeNameApiFetchParamCreator(
        configuration
      ).VMTypeNameGet(body, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    // /**
    //  *
    //  * @param {number} id
    //  * @param {*} [options] Override http request option.
    //  * @throws {RequiredError}
    //  */
    // locationGetRelatedRecords(
    //   id: number,
    //   options?: any
    // ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
    //   const localVarFetchArgs = VMTypeNameApiFetchParamCreator(
    //     configuration
    //   ).locationGetRelatedRecords(id, options);
    //   return (
    //     fetch: FetchAPI = isomorphicFetch,
    //     basePath = BASE_PATH
    //   ) => {
    //     return fetch(
    //       basePath + localVarFetchArgs.url,
    //       localVarFetchArgs.options
    //     ).then((response) => {
    //       if (response.status >= 200 && response.status < 300) {
    //         return response.json();
    //       } else {
    //         throw response;
    //       }
    //     });
    //   };
    // },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameGetUpdatedPage(
      id: number,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<VMTypeNameDto> {
      const localVarFetchArgs = VMTypeNameApiFetchParamCreator(
        configuration
      ).VMTypeNameGetUpdatedPage(id, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @param {VMTypeNameDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameUpdate(
      body: VMTypeNameDto,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<ResultDto> {
      const localVarFetchArgs = VMTypeNameApiFetchParamCreator(
        configuration
      ).VMTypeNameUpdate(body, options);
      return (fetch: FetchAPI = isomorphicFetch, basePath = BASE_PATH) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
  };
};

/**
 * VMTypeNameApi - factory interface
 * @export
 */
export const VMTypeNameApiFactory = function (
  configuration?: Configuration,
  fetch?: FetchAPI,
  basePath?: string
) {
  return {
    /**
     *
     * @param {VMTypeNameDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameCreate(body: VMTypeNameDto, options?: any) {
      return VMTypeNameApiFp(configuration).VMTypeNameCreate(body, options)(
        fetch,
        basePath
      );
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameDelete(id?: number, options?: any) {
      return VMTypeNameApiFp(configuration).VMTypeNameDelete(id, options)(
        fetch,
        basePath
      );
    },
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameDeleteDeep(id?: number, options?: any) {
      return VMTypeNameApiFp(configuration).VMTypeNameDeleteDeep(id, options)(
        fetch,
        basePath
      );
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameGetCreatepage(options?: any) {
      return VMTypeNameApiFp(configuration).VMTypeNameGetCreatepage(options)(
        fetch,
        basePath
      );
    },
    /**
     *
     * @param {string} [propertyName]
     * @param {string} [propertyFilter]
     * @param {Array<number>} [id]
     * @param {Array<string>} [description]
     * @param {Array<number>} [opco]
     * @param {Array<number>} [locationType]
     * @param {string} [sortBy]
     * @param {boolean} [isSortAscending]
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {Date} [lastModifiedStartDate]
     * @param {Date} [lastModifiedEndDate]
     * @param {number} [principalId]
     * @param {boolean} [deleted]
     * @param {boolean} [orphan]
     * @param {Array<string>} [lastModifiedBy]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameGetFilterResult(
      propertyName?: string,
      propertyFilter?: string,
      vmtypedescription?: Array<string>,
      vmtypenameid?: Array<number>,
      vnfName?: Array<string>,
      vnfnameid?: Array<number>,
      sortBy?: string,
      isSortAscending?: boolean,
      page?: number,
      pageSize?: number,
      lastModifiedStartDate?: Date,
      lastModifiedEndDate?: Date,
      principalId?: number,
      deleted?: boolean,
      orphan?: boolean,
      lastModifiedBy?: Array<string>,
      options?: any
    ) {
      return VMTypeNameApiFp(configuration).VMTypeNameGetFilterResult(
        propertyName,
        propertyFilter,
        vmtypedescription,
        vmtypenameid,
        vnfName,
        vnfnameid,
        sortBy,
        isSortAscending,
        page,
        pageSize,
        lastModifiedStartDate,
        lastModifiedEndDate,
        principalId,
        deleted,
        orphan,
        lastModifiedBy,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {VMTypeNameGetCreatepage} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameGet(body?: VMTypeNameQueryObjectGrid, options?: any) {
      return VMTypeNameApiFp(configuration).VMTypeNameGet(body, options)(
        fetch,
        basePath
      );
    },
    // /**
    //  *
    //  * @param {number} id
    //  * @param {*} [options] Override http request option.
    //  * @throws {RequiredError}
    //  */
    // locationGetRelatedRecords(id: number, options?: any) {
    //   return VMTypeNameApiFp(configuration).locationGetRelatedRecords(
    //     id,
    //     options
    //   )(fetch, basePath);
    // },
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameGetUpdatedPage(id: number, options?: any) {
      return VMTypeNameApiFp(configuration).VMTypeNameGetUpdatedPage(
        id,
        options
      )(fetch, basePath);
    },
    /**
     *
     * @param {VMTypeNameDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    VMTypeNameUpdate(body: VMTypeNameDto, options?: any) {
      return VMTypeNameApiFp(configuration).VMTypeNameUpdate(body, options)(
        fetch,
        basePath
      );
    },
  };
};

/**
 * VMTypeNameApi - object-oriented interface
 * @export
 * @class VMTypeNameApi
 * @extends {BaseAPI}
 */
export class VMTypeNameApi extends BaseAPI {
  /**
   *
   * @param {VMTypeNameDto} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VMTypeNameApi
   */
  public VMTypeNameCreate(body: VMTypeNameDto, options?: any) {
    return VMTypeNameApiFp(this.configuration).VMTypeNameCreate(body, options)(
      this.fetch,
      this.basePath
    );
  }

  /**
   *
   * @param {number} [id]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VMTypeNameApi
   */
  public VMTypeNameDelete(id?: number, options?: any) {
    return VMTypeNameApiFp(this.configuration).VMTypeNameDelete(id, options)(
      this.fetch,
      this.basePath
    );
  }

  /**
   *
   * @param {number} [id]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VMTypeNameApi
   */
  public VMTypeNameDeleteDeep(id?: number, options?: any) {
    return VMTypeNameApiFp(this.configuration).VMTypeNameDeleteDeep(
      id,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VMTypeNameApi
   */
  public VMTypeNameGetCreatepage(options?: any) {
    return VMTypeNameApiFp(this.configuration).VMTypeNameGetCreatepage(options)(
      this.fetch,
      this.basePath
    );
  }

  /**
   *
   * @param {string} [propertyName]
   * @param {string} [propertyFilter]
   * @param {Array<number>} [id]
   * @param {Array<string>} [description]
   * @param {Array<number>} [opco]
   * @param {Array<number>} [locationType]
   * @param {string} [sortBy]
   * @param {boolean} [isSortAscending]
   * @param {number} [page]
   * @param {number} [pageSize]
   * @param {Date} [lastModifiedStartDate]
   * @param {Date} [lastModifiedEndDate]
   * @param {number} [principalId]
   * @param {boolean} [deleted]
   * @param {boolean} [orphan]
   * @param {Array<string>} [lastModifiedBy]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VNFNameApi
   */
  public VMTypeNameGetFilterResult(
    propertyName?: string,
    propertyFilter?: string,
    vmtypedescription?: Array<string>,
    vmtypenameid?: Array<number>,
    vnfName?: Array<string>,
    vnfnameid?: Array<number>,
    sortBy?: string,
    isSortAscending?: boolean,
    page?: number,
    pageSize?: number,
    lastModifiedStartDate?: Date,
    lastModifiedEndDate?: Date,
    principalId?: number,
    deleted?: boolean,
    orphan?: boolean,
    lastModifiedBy?: Array<string>,
    options?: any
  ) {
    return VMTypeNameApiFp(this.configuration).VMTypeNameGetFilterResult(
      propertyName,
      propertyFilter,
      vmtypedescription,
      vmtypenameid,
      vnfName,
      vnfnameid,
      sortBy,
      isSortAscending,
      page,
      pageSize,
      lastModifiedStartDate,
      lastModifiedEndDate,
      principalId,
      deleted,
      orphan,
      lastModifiedBy,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {VMTypeNameGetCreatepage} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VMTypeNameApi
   */
  public VMTypeNameGet(body?: VMTypeNameQueryObjectGrid, options?: any) {
    return VMTypeNameApiFp(this.configuration).VMTypeNameGet(body, options)(
      this.fetch,
      this.basePath
    );
  }

  //   /**
  //    *
  //    * @param {number} id
  //    * @param {*} [options] Override http request option.
  //    * @throws {RequiredError}
  //    * @memberof VMTypeNameApi
  //    */
  //   public locationGetRelatedRecords(id: number, options?: any) {
  //     return VMTypeNameApiFp(this.configuration).locationGetRelatedRecords(
  //       id,
  //       options
  //     )(this.fetch, this.basePath);
  //   }

  /**
   *
   * @param {number} id
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VMTypeNameApi
   */
  public VMTypeNameGetUpdatedPage(id: number, options?: any) {
    return VMTypeNameApiFp(this.configuration).VMTypeNameGetUpdatedPage(
      id,
      options
    )(this.fetch, this.basePath);
  }

  /**
   *
   * @param {VMTypeNameDto} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VMTypeNameApi
   */
  public VMTypeNameUpdate(body: VMTypeNameDto, options?: any) {
    return VMTypeNameApiFp(this.configuration).VMTypeNameUpdate(body, options)(
      this.fetch,
      this.basePath
    );
  }
}
