ALTER TABLE LCMENGINEERING ADD ISRELEASEDETAILSKNOWN NUMBER(1, 0);
ALTER TABLE NETWORKELEMENTSASPLANNED ADD ISRELEASEDETAILSKNOWN NUMBER(1, 0);

--update dcf data
--UPDATE DCFID IN LCM
UPDATE LCMENGINEERING LCM
   SET (DESIGNCOMPONENTFAMILYID) = (SELECT DC.DESIGNCOMPONENTFAMILYID
                         FROM DESIGNCOMPONENTS DC
                        WHERE LCM.DESIGNCOMPONENTID = DC.DESIGNCOMPONENTID)
 WHERE EXISTS (
    SELECT DC.DESIGNCOMPONENTFAMILYID
                         FROM DESIGNCOMPONENTS DC
                        WHERE LCM.DESIGNCOMPONENTID = DC.DESIGNCOMPONENTID);
COMMIT;

-- UPDATE DCFID IN ASSETS
UPDATE NETWORKELEMENTSASPLANNED ASSET
   SET (DESIGNCOMPONENTFAMILYID) = (SELECT DC.DESIGNCOMPONENTFAMILYID
                         FROM DESIGNCOMPONENTS DC
                        WHERE ASSET.DESIGNCOMPONENTID = DC.DESIGNCOMPONENTID)
 WHERE EXISTS (
    SELECT DC.DESIGNCOMPONENTFAMILYID
                         FROM DESIGNCOMPONENTS DC
                        WHERE ASSET.DESIGNCOMPONENTID = DC.DESIGNCOMPONENTID);
COMMIT;

  ALTER TABLE SETTINGSUPDATEPLANNEDACTIVITY ADD " CREATEORDONOTCREATEDCF " NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE;
  ALTER TABLE SETTINGSUPDATEPLANNEDACTIVITY ADD "SPECIFYDC" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE;
  ALTER TABLE SETTINGSUPDATEPLANNEDACTIVITY DROP COLUMN CREATEORDONOTCREATEDCF;
   ALTER TABLE SETTINGSUPDATEPLANNEDACTIVITY DROP COLUMN INCREAMENTORSWAPRESOURCEKEYS;
   ALTER TABLE SETTINGSUPDATEPLANNEDACTIVITY DROP COLUMN DCRULE;
