
--------------------------------------------------------
--  DDL for Sequence TEAMMEMBERS_SEQ
--------------------------------------------------------

CREATE SEQUENCE "TEAMMEMBERS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP NOSCALE  GLOBAL ;




--------------------------------------------------------
--  DDL for Table TEAMMEMBERS
--------------------------------------------------------

CREATE TABLE "TEAMMEMBERS" 
("TEAMMEMBERID" NUMBER(10,0) DEFAULT "TEAMMEMBERS_SEQ"."NEXTVAL", 
"TEAMID" NUMBER(10,0), 
"USERID" NUMBER(10,0),
"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
"DELETED" NUMBER(1,0) DEFAULT 0, 
"DELETIONDATE" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;

--------------------------------------------------------
--  DDL for Index PK_TEAMMEMBERS
--------------------------------------------------------

CREATE UNIQUE INDEX "PK_TEAMMEMBERS" ON "TEAMMEMBERS" ("TEAMMEMBERID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table TEAMMEMBERS
--------------------------------------------------------

ALTER TABLE "TEAMMEMBERS" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE "TEAMMEMBERS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE "TEAMMEMBERS" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE "TEAMMEMBERS" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE "TEAMMEMBERS" ADD CONSTRAINT "PK_TEAMMEMBERS" PRIMARY KEY ("TEAMMEMBERID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "CAMDB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEAMMEMBERS
--------------------------------------------------------

ALTER TABLE "TEAMMEMBERS" ADD CONSTRAINT "FK_TEAMMEMBERS_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "TEAMMEMBERS" ADD CONSTRAINT "FK_TEAMMEMBERS_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "TEAMMEMBERS" ADD CONSTRAINT "FK_TEAMMEMBERS_TEAMS_TEAMID" FOREIGN KEY ("TEAMID")
REFERENCES "TEAMS" ("TEAMID") ENABLE;
ALTER TABLE "TEAMMEMBERS" ADD CONSTRAINT "FK_TEAMMEMBERS_ASPNETUSERS_USERID" FOREIGN KEY ("USERID")
REFERENCES "ASPNETUSERS" ("ID") ENABLE;

COMMIT;