--------------------------------------------------------
--  DDL FOR SEQUENCE EXODUSMILESTONEANDACTIVITIES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EXODUSMILESTONEANDACTIVITIES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


--------------------------------------------------------
--  DDL FOR TABLE EXODUSMILESTONEANDACTIVITIES
--------------------------------------------------------

  CREATE TABLE "EXODUSMILESTONEANDACTIVITIES" 
   (	"EXODUSMILESTONEANDACTIVITYID" NUMBER(19,0) DEFAULT "EXODUSMILESTONEANDACTIVITIES_SEQ"."NEXTVAL", 
	"ACTIVITIES" NVARCHAR2(500), 
	"ACTIVITIESORDER" NUMBER(10,0), 
	"MILESTONES" NVARCHAR2(500), 
	"ACTUALCOLUMNNAMES" NVARCHAR2(500), 
	"CREATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"MODIFICATIONUSER" NUMBER(10,0) DEFAULT 1, 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX EXODUSMILESTONEANDACTIVITIESIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "EXODUSMILESTONEANDACTIVITIESIDX" ON "EXODUSMILESTONEANDACTIVITIES" ("EXODUSMILESTONEANDACTIVITYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE EXODUSMILESTONEANDACTIVITIES
--------------------------------------------------------

  ALTER TABLE "EXODUSMILESTONEANDACTIVITIES" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "EXODUSMILESTONEANDACTIVITIES" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "EXODUSMILESTONEANDACTIVITIES" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "EXODUSMILESTONEANDACTIVITIES" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "EXODUSMILESTONEANDACTIVITIES" ADD CONSTRAINT "PK_EXODUSMILESTONEANDACTIVITIES" PRIMARY KEY ("EXODUSMILESTONEANDACTIVITYID") USING INDEX "EXODUSMILESTONEANDACTIVITIESIDX"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE EXODUSMILESTONEANDACTIVITIES
--------------------------------------------------------

ALTER TABLE "EXODUSMILESTONEANDACTIVITIES" ADD CONSTRAINT "FK_EXODUSMILESTONEANDACTIVITIES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE "EXODUSMILESTONEANDACTIVITIES" ADD CONSTRAINT "FK_EXODUSMILESTONEANDACTIVITIES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
COMMIT;

--------------------------------------------------------
--  INSERT VALUES TO THE TABLE EXODUSMILESTONEANDACTIVITIES
--------------------------------------------------------

SET DEFINE OFF;
INSERT INTO Exodusmilestoneandactivities ( Activities,Activitiesorder,Milestones,Actualcolumnnames,CREATIONUSER, MODIFICATIONUSER) VALUES (N'x-BoM Submission', 1,N'xBOM Submitted', N'Bomsubmitteddate', 1, 1);
INSERT INTO Exodusmilestoneandactivities ( Activities,Activitiesorder,Milestones,Actualcolumnnames,CREATIONUSER, MODIFICATIONUSER) VALUES (N'HW delivery', 2,N'HW PO Raised', N'Hwporaiseddate', 1, 1);
INSERT INTO Exodusmilestoneandactivities ( Activities,Activitiesorder,Milestones,Actualcolumnnames,CREATIONUSER, MODIFICATIONUSER) VALUES (N'HW Installation & Integration', 3,N'Hardware Arrived', N'Hwpoarriveddate', 1, 1);
INSERT INTO Exodusmilestoneandactivities ( Activities,Activitiesorder,Milestones,Actualcolumnnames,CREATIONUSER, MODIFICATIONUSER) VALUES (N'RFO Preparation', 4,N'VEC infra ready /CNIS -Workload cluster config', N'Vecdate', 1, 1);
INSERT INTO Exodusmilestoneandactivities ( Activities,Activitiesorder,Milestones,Actualcolumnnames,CREATIONUSER, MODIFICATIONUSER) VALUES (N'App Integration', 5,N'RFO', N'Rfodate', 1, 1);
INSERT INTO Exodusmilestoneandactivities ( Activities,Activitiesorder,Milestones,Actualcolumnnames,CREATIONUSER, MODIFICATIONUSER) VALUES (N'App Integration', 5,N'Start of app Integration', N'Startofappintegration', 1, 1);
INSERT INTO Exodusmilestoneandactivities ( Activities,Activitiesorder,Milestones,Actualcolumnnames,CREATIONUSER, MODIFICATIONUSER) VALUES (N'TACC && FACC', 6,N'RFA', N'Rfadate', 1, 1);
INSERT INTO Exodusmilestoneandactivities ( Activities,Activitiesorder,Milestones,Actualcolumnnames,CREATIONUSER, MODIFICATIONUSER) VALUES (N'Migration', 7,N'RFS', N'Rfsdate', 1, 1);
INSERT INTO Exodusmilestoneandactivities ( Activities,Activitiesorder,Milestones,Actualcolumnnames,CREATIONUSER, MODIFICATIONUSER) VALUES (N'Migration', 7,N'Migration Start', N'Migrationstart', 1, 1);
INSERT INTO Exodusmilestoneandactivities ( Activities,Activitiesorder,Milestones,Actualcolumnnames,CREATIONUSER, MODIFICATIONUSER) VALUES (N'Migration Complete', 8,N'Migration Complete', N'Migrationcompletiondate', 1, 1);
COMMIT;