ALTER TABLE "SUBNETWORKBOUNDARIES" ADD CONSTRAINT "FK_SUBNETWORKBOUNDARIES_PRODUCTNAME_PRODUCTNAMEID" FOREIGN KEY ("PRODUCTNAMEID")
REFERENCES "PRODUCTNAME" ("PRODUCTNAMEID") ENABLE;

ALTER TABLE "DESIGNCOMPONENTFAMILIES" ADD CONSTRAINT "FK_DESIGNCOMPONENTFAMILIES_PRODUCTNAME_PRODUCTNAMEID" FOREIGN KEY ("PRODUCTNAMEID")
REFERENCES "PRODUCTNAME" ("PRODUCTNAMEID") ENABLE;

ALTER TABLE "MAJORSOFTWAREBUILDS" ADD CONSTRAINT "FK_MAJORSOFTWAREBUILDS_PRODUCTNAME_PRODUCTNAMEID" FOREIGN KEY ("PRODUCTNAMEID")
REFERENCES "PRODUCTNAME" ("PRODUCTNAMEID") ENABLE;