--------------------------------------------------------
--  File created - Thursday-june-1-2023   
--------------------------------------------------------

CREATE SEQUENCE BUSINESSCONTINUITYMETHOD_SEQ
 START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
COMMIT;
  CREATE TABLE "BUSINESSCONTINUITYMETHOD" 
   (	"ID" NUMBER(10,0) DEFAULT "BUSINESSCONTINUITYMETHOD_SEQ"."NEXTVAL", 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6), 
	"DESCRIPTION" NVARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
  COMMIT;
--------------------------------------------------------
--  DDL for Index PK_BUSINESSCONTINUITYMETHOD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_BUSINESSCONTINUITYMETHOD" ON "BUSINESSCONTINUITYMETHOD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  COMMIT;
--------------------------------------------------------
--  Constraints for Table BUSINESSCONTINUITYMETHOD
--------------------------------------------------------

  ALTER TABLE "BUSINESSCONTINUITYMETHOD" ADD CONSTRAINT "PK_BUSINESSCONTINUITYMETHOD" PRIMARY KEY ("ID")
  USING INDEX "PK_BUSINESSCONTINUITYMETHOD"  ENABLE;
  ALTER TABLE "BUSINESSCONTINUITYMETHOD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUSINESSCONTINUITYMETHOD" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "BUSINESSCONTINUITYMETHOD" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "BUSINESSCONTINUITYMETHOD" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "BUSINESSCONTINUITYMETHOD" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "BUSINESSCONTINUITYMETHOD" MODIFY ("DELETED" NOT NULL ENABLE);
  COMMIT;
--------------------------------------------------------
--  Ref Constraints for Table BUSINESSCONTINUITYMETHOD
--------------------------------------------------------

  ALTER TABLE "BUSINESSCONTINUITYMETHOD" ADD CONSTRAINT "FK_BUSINESSCONTINUITYMETHOD_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "BUSINESSCONTINUITYMETHOD" ADD CONSTRAINT "FK_BUSINESSCONTINUITYMETHOD_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
COMMIT;
ALTER TABLE BUSINESSCONTINUITYMETHOD
MODIFY(ID  DEFAULT "BUSINESSCONTINUITYMETHOD_SEQ"."NEXTVAL");
COMMIT;
--------------------------------------------------------
--  Copy data from georesilience to BUSINESSCONTINUITYMETHOD
--------------------------------------------------------
insert into BUSINESSCONTINUITYMETHOD ( select ID ,
CREATIONUSER ,
CREATIONDATE ,
MODIFICATIONUSER ,
MODIFICATIONDATE ,
DELETED ,
DELETIONDATE ,
DESCRIPTION  from GEORESILIENCE);
COMMIT;

-----------------------------------------------------------------
-- Create new column in design aspects called BusinessContinuityMethodId
-----------------------------------------------------------------

ALTER TABLE DESIGNASPECTS 
ADD BUSINESSCONTINUITYMETHODID Number(10,0) NULL;
commit;


ALTER TABLE "DESIGNASPECTS" ADD CONSTRAINT "FK_DESIGNASPECTS_BUSINESSCONTINUITYMETHOD_BUSINESSCONTINUITYMETHODID" FOREIGN KEY ("BUSINESSCONTINUITYMETHODID")
REFERENCES "BUSINESSCONTINUITYMETHOD" ("ID") ENABLE;
------------------------------------------------------------------------
--Copy data from georesilenceid to businessContinuityId
------------------------------------------------------------------------
UPDATE DESIGNASPECTS SET BUSINESSCONTINUITYMETHODID = GEORESILIENCEID;
COMMIT;

------------------------------------------------------------------------
--DROP column georisilienceId from design aspects
------------------------------------------------------------------------
ALTER TABLE DESIGNASPECTS 
DROP COLUMN GEORESILIENCEID;
commit;
------------------------------------------------------------------------
--DROP GEORESILIENCE table
------------------------------------------------------------------------
DROP TABLE GEORESILIENCE CASCADE CONSTRAINTS;
commit;
------------------------------------------------------------------------
--DROP GEORESILIENCE_SEQ
------------------------------------------------------------------------
DROP SEQUENCE GEORESILIENCE_SEQ;
Commit;

