ALTER TABLE LCMANCILLARYDATA ADD REGULATORYFIELDS NVARCHAR2(50);

UPDATE LCMANCILLARYDATA
SET REGULATORYFIELDS = 
CASE 
WHEN ISPECN = '1' THEN ' PECN' 
ELSE '' 
END || 
CASE 
WHEN ISPECS = '1' THEN ' PECS' 
ELSE '' 
END || 
CASE 
WHEN ISSCF= '1' THEN ' SCF' 
ELSE '' 
END || 
CASE 
WHEN ISNOF = '1' THEN ' NOF' 
ELSE '' 
END;
	
ALTER TABLE LCMANCILLARYDATA DROP COLUMN ISPECN;
ALTER TABLE LCMANCILLARYDATA DROP COLUMN ISPECS;
ALTER TABLE LCMANCILLARYDATA DROP COLUMN ISSCF;
ALTER TABLE LCMANCILLARYDATA DROP COLUMN ISNOF;

COMMIT;
