--------------------------------------------------------
--  DDL FOR SEQUENCE SITEID_SEQ
--------------------------------------------------------
CREATE SEQUENCE "SITES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE SITES
--------------------------------------------------------
CREATE TABLE SITES (
    SITEID           NUMBER(10, 0) DEFAULT SITES_SEQ.NEXTVAL NOT NULL,
    LOCATIONID       NUMBER(5) NOT NULL,
    SITECODE         NVARCHAR2(50),
    SITECATEGORY     NVARCHAR2(50) NOT NULL,
    REGION           NVARCHAR2(50) NOT NULL,
    CREATIONUSER     NUMBER(10, 0) DEFAULT 1,
    CREATIONDATE     TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    MODIFICATIONUSER NUMBER(10, 0) DEFAULT 1,
    MODIFICATIONDATE TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    DELETED          NUMBER(1, 0) DEFAULT 0,
    DELETIONDATE     TIMESTAMP(6)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "CAMDB";
  
--------------------------------------------------------
--  DDL FOR INDEX PK_SITEID
--------------------------------------------------------
CREATE UNIQUE INDEX "PK_SITES" ON
    sites (
        "SITEID"
    )
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "CAMDB";
 --------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE SITES MODIFY ("CREATIONUSER" NOT NULL ENABLE);
ALTER TABLE SITES MODIFY ("CREATIONDATE" NOT NULL ENABLE);
ALTER TABLE SITES MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
ALTER TABLE SITES MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
ALTER TABLE SITES ADD CONSTRAINT "PK_SITES" PRIMARY KEY ("SITEID")
USING INDEX "PK_SITES"  ENABLE;
  
  --------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

ALTER TABLE sites ADD CONSTRAINT "FK_SITES_LOCATIONS_LOCATIONID" FOREIGN KEY ( "LOCATIONID" ) REFERENCES "LOCATIONS" ( "LOCATIONID" ) ENABLE;
ALTER TABLE sites ADD CONSTRAINT "FK_SITES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
ALTER TABLE sites ADD CONSTRAINT "FK_SITES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER") REFERENCES "ASPNETUSERS" ("ID") ENABLE;

COMMIT;
