
--------------------------------------------------------
--  DDL FOR SEQUENCE VNFNAME_SEQ
--------------------------------------------------------

   CREATE SEQUENCE "VNFNAME_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE VNFNAME
--------------------------------------------------------

  CREATE TABLE VNFNAME 
   (	
    VNFNAMEID NUMBER(19,0) DEFAULT VNFNAME_SEQ.NEXTVAL  NOT NULL, 
	VNFDESCRIPTION NVARCHAR2(50)  NOT NULL, 
	PRODUCTID NUMBER(20,0)  NOT NULL, 	 
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_VNFNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_VNFNAME" ON VNFNAME ("VNFNAMEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE VNFNAME MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE VNFNAME MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE VNFNAME MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE VNFNAME MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE VNFNAME ADD CONSTRAINT "PK_VNFNAME" PRIMARY KEY ("VNFNAMEID")
  USING INDEX "PK_VNFNAME"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE VNFNAME ADD CONSTRAINT "FK_VNFNAME_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE VNFNAME ADD CONSTRAINT "FK_VNFNAME_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE VNFNAME ADD CONSTRAINT "FK_VNFNAME_PRODUCTNAME_PRODUCTID" FOREIGN KEY ("PRODUCTID")
	  REFERENCES "PRODUCTNAME" ("PRODUCTNAMEID") ENABLE;
	  
COMMIT;
--------------------------------------------------------
--  DDL FOR SEQUENCE CLUSTERNAME_SEQ
--------------------------------------------------------

   CREATE SEQUENCE "CLUSTERNAME_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE CLUSTERNAME
--------------------------------------------------------

  CREATE TABLE CLUSTERNAME 
   (	
    CLUSTERNAMEID NUMBER(19,0) DEFAULT CLUSTERNAME_SEQ.NEXTVAL NOT NULL, 
	CLUSTERDESCRIPTION NVARCHAR2(50) NOT NULL, 
	CLUSTERTYPE NUMBER(5) NOT NULL, 	 
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_CLUSTERNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CLUSTERNAME" ON CLUSTERNAME ("CLUSTERNAMEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE CLUSTERNAME MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE CLUSTERNAME MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE CLUSTERNAME MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE CLUSTERNAME MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE CLUSTERNAME ADD CONSTRAINT "PK_CLUSTERNAME" PRIMARY KEY ("CLUSTERNAMEID")
  USING INDEX "PK_CLUSTERNAME"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE CLUSTERNAME ADD CONSTRAINT "FK_CLUSTERNAME_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE CLUSTERNAME ADD CONSTRAINT "FK_CLUSTERNAME_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  
COMMIT;
--------------------------------------------------------
--  DDL FOR SEQUENCE VMTYPENAME_SEQ
--------------------------------------------------------

   CREATE SEQUENCE "VMTYPENAME_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE VMTYPENAME
--------------------------------------------------------

  CREATE TABLE VMTYPENAME 
   (	
    VMTYPENAMEID NUMBER(19,0) DEFAULT VMTYPENAME_SEQ.NEXTVAL NOT NULL, 
	VNFNAMEID NUMBER(19,0) NOT NULL, 
	VMTYPEDESCRIPTION NVARCHAR2(10) NOT NULL, 	 
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_VMTYPENAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_VMTYPENAME" ON VMTYPENAME ("VMTYPENAMEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE VMTYPENAME MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE VMTYPENAME MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE VMTYPENAME MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE VMTYPENAME MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE VMTYPENAME ADD CONSTRAINT "PK_VMTYPENAME" PRIMARY KEY ("VMTYPENAMEID")
  USING INDEX "PK_VMTYPENAME"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE VMTYPENAME ADD CONSTRAINT "FK_VMTYPENAME_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE VMTYPENAME ADD CONSTRAINT "FK_VMTYPENAME_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
   ALTER TABLE VMTYPENAME ADD CONSTRAINT "FK_VMTYPENAME_VNFNAME_VNFNAMEID" FOREIGN KEY ("VNFNAMEID")
	  REFERENCES "VNFNAME" ("VNFNAMEID") ENABLE; 
COMMIT;


--------------------------------------------------------
--  DDL FOR SEQUENCE VNFINFO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE "VNFINFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE VNFINFO
--------------------------------------------------------

  CREATE TABLE VNFINFO 
   (	
    VNFINFOID NUMBER(19,0) DEFAULT VNFINFO_SEQ.NEXTVAL NOT NULL, 
	VNFNAMEID NUMBER(19,0) NOT NULL, 
	CLUSTERID NUMBER(19,0) NOT NULL, 
	VMTYPENAMEID NUMBER(19,0) NOT NULL, 
	NSXT NUMBER(1,0) NOT NULL, 
	INTRAVMTYPE NVARCHAR2(10) NOT NULL, 
	INTERVMTYPE NVARCHAR2(50) NOT NULL,
    VMWORKLOADTYPE NVARCHAR2(100) NOT NULL,
    VMSTORAGEBLOCKSIZE NVARCHAR2(50),  
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_AUDITLOGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_VNFINFO" ON VNFINFO ("VNFINFOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE VNFINFO MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE VNFINFO MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE VNFINFO MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE VNFINFO MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE VNFINFO ADD CONSTRAINT "PK_VNFINFO" PRIMARY KEY ("VNFINFOID")
  USING INDEX "PK_VNFINFO"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE VNFINFO ADD CONSTRAINT "FK_VNFINFO_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE VNFINFO ADD CONSTRAINT "FK_VNFINFO_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE VNFINFO ADD CONSTRAINT "FK_VNFINFO_VNFNAME_VNFNAMEID" FOREIGN KEY ("VNFNAMEID")
	  REFERENCES "VNFNAME" ("VNFNAMEID") ENABLE;
  ALTER TABLE VNFINFO ADD CONSTRAINT "FK_VNFINFO_CLUSTERNAME_CLUSTERID" FOREIGN KEY ("CLUSTERID")
	  REFERENCES "CLUSTERNAME" ("CLUSTERNAMEID") ENABLE;
  ALTER TABLE VNFINFO ADD CONSTRAINT "FK_VNFINFO_VMTYPENAME_VMTYPENAMEIDD" FOREIGN KEY ("VMTYPENAMEID")
	  REFERENCES "VMTYPENAME" ("VMTYPENAMEID") ENABLE;
COMMIT;



--------------------------------------------------------
--  DDL FOR SEQUENCE VNFVMINSTANCES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE "VNFVMINSTANCES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE VNFINFO
--------------------------------------------------------

  CREATE TABLE VNFVMINSTANCES 
   (	
    VNFVMINSTANCEID NUMBER(19,0) DEFAULT VNFVMINSTANCES_SEQ.NEXTVAL NOT NULL, 
	VNFINFOID NUMBER(19,0) NOT NULL, 
	OPCOID NUMBER(5) NOT NULL, 
	LOCATIONID NUMBER(5) NOT NULL, 
	NOOFVNFINSTANCES NUMBER(19) NOT NULL, 
	NOOFVMSPERTYPE NUMBER(19) NOT NULL, 
	NUMA NUMBER(1),
    SOCKET NVARCHAR2(250),    
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_AUDITLOGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "VNFVMINSTANCES" ON VNFVMINSTANCES ("VNFVMINSTANCEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE VNFVMINSTANCES MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE VNFVMINSTANCES MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE VNFVMINSTANCES MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE VNFVMINSTANCES MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE VNFVMINSTANCES ADD CONSTRAINT "PK_VNFVMINSTANCES" PRIMARY KEY ("VNFVMINSTANCEID")
  USING INDEX "VNFVMINSTANCES"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE VNFVMINSTANCES ADD CONSTRAINT "FK_VNFVMINSTANCES_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE VNFVMINSTANCES ADD CONSTRAINT "FK_VNFVMINSTANCES_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE VNFVMINSTANCES ADD CONSTRAINT "FK_VNFVMINSTANCES_VNFINFO_VNFINFOID" FOREIGN KEY ("VNFINFOID")
	  REFERENCES "VNFINFO" ("VNFINFOID") ENABLE;
  ALTER TABLE VNFVMINSTANCES ADD CONSTRAINT "FK_VNFVMINSTANCES_OPCOS_OPCOID" FOREIGN KEY ("OPCOID")
	  REFERENCES "OPCOS" ("OPCOID") ENABLE;
  ALTER TABLE VNFVMINSTANCES ADD CONSTRAINT "FK_VNFVMINSTANCES_LOCATIONS_LOCATIONID" FOREIGN KEY ("LOCATIONID")
	  REFERENCES "LOCATIONS" ("LOCATIONID") ENABLE;
COMMIT;


--------------------------------------------------------
--  DDL FOR SEQUENCE VNFVMCAPACITY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE "VNFVMCAPACITY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE VNFINFO
--------------------------------------------------------

  CREATE TABLE VNFVMCAPACITY 
   (	
    VNFVMCAPACITYID NUMBER(19,0) DEFAULT VNFVMCAPACITY_SEQ.NEXTVAL NOT NULL, 
	VNFVMINSTANCEID NUMBER(19,0) NOT NULL, 
	FINANCIALYEAR NUMBER(5) NOT NULL,  
	VCPUPERVM NUMBER(19) NOT NULL, 
	RXTXCPUCOUNT NUMBER(1), 
	 RAMPERVM NUMBER(19) NOT NULL,
    DATADISK NVARCHAR2(19) NOT NULL, 
    OSDISK NUMBER(19), 
	IOPSRUNNING  NVARCHAR2(50), 
	IOPSLOADING NVARCHAR2(50),
    VMWORKLOADDISTRIBUTION NVARCHAR2(250), 
	 NORTHSOUTHBOUNDBANDWIDTH NVARCHAR2(250), 
	EASTWESTBOUNDBANDWIDTH NVARCHAR2(250), 
	 OTHERREQUIREMENTS NVARCHAR2(250), 
	BACKUPREQUIRED NUMBER(1), 
	  PROBINGREQUIRED  NUMBER(1), 
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_AUDITLOGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "VNFVMCAPACITY" ON VNFVMCAPACITY ("VNFVMCAPACITYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE VNFVMCAPACITY MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE VNFVMCAPACITY MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE VNFVMCAPACITY MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE VNFVMCAPACITY MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE VNFVMCAPACITY ADD CONSTRAINT "PK_VNFVMCAPACITY" PRIMARY KEY ("VNFVMCAPACITYID")
  USING INDEX "VNFVMCAPACITY"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE VNFVMCAPACITY ADD CONSTRAINT "FK_VNFVMCAPACITY_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE VNFVMCAPACITY ADD CONSTRAINT "FK_VNFVMCAPACITY_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE VNFVMCAPACITY ADD CONSTRAINT "FK_VNFVMCAPACITY_VNFVMINSTANCESO_VNFVMINSTANCEID" FOREIGN KEY ("VNFVMINSTANCEID")
	  REFERENCES "VNFVMINSTANCES" ("VNFVMINSTANCEID") ENABLE;
 
--------------------------------------------------------
--  LOCATIONS TABLE  
--------------------------------------------------------


ALTER TABLE LOCATIONS ADD SHORTDESCRIPTION NVARCHAR2(10);


--------------------------------------------------------
--  Refresh LOCATIONS TABLE  data
--------------------------------------------------------

delete gridcustomcolumn where  classname ='LocationDtoGrid';
 
COMMIT;
