--------------------ALTER SCRIPT FOR BUILDCONSTRUCTIONS-------------------------

ALTER TABLE  BUILDCONSTRUCTIONS  ADD  CLOUDTYPE NVARCHAR2(500);

----------------------------------------------------------------------------------

--------------------ALTER SCRIPT FOR LCMANCILLARYDATA-------------------------

ALTER TABLE  LCMANCILLARYDATA  ADD LASTSCANREFNUMBER NVARCHAR2(500);
ALTER TABLE  LCMANCILLARYDATA  ADD LASTPENTESTREFERENCENUMBER NVARCHAR2(500);
ALTER TABLE  LCMANCILLARYDATA  ADD LASTPENTESTDATE TIMESTAMP(6);
----------------------------------------------------------------------------------

--------------------ALTER SCRIPT FOR LCMANCILLARYDATA-------------------------


ALTER TABLE  TSRPASSTHROUGH  MODIFY TECHNICALSERVICENAMES NVARCHAR2(2000);

ALTER TABLE tsrpassthrough ADD (temp1 NCLOB);
UPDATE tsrpassthrough SET temp1 = MODEL;
COMMIT;
ALTER TABLE tsrpassthrough DROP COLUMN MODEL;
ALTER TABLE tsrpassthrough RENAME COLUMN temp1 TO MODEL;

ALTER TABLE tsrpassthrough ADD (temp2 NCLOB);
UPDATE tsrpassthrough SET temp2 = FIRMWAREVERSION;
COMMIT;
ALTER TABLE tsrpassthrough DROP COLUMN FIRMWAREVERSION;
ALTER TABLE tsrpassthrough RENAME COLUMN temp2 TO FIRMWAREVERSION;

ALTER TABLE tsrpassthrough ADD (temp3 NCLOB);
UPDATE tsrpassthrough SET temp3 = BOARDORMODULETYPECOMPONENTSUBTYPE;
COMMIT;
ALTER TABLE tsrpassthrough DROP COLUMN BOARDORMODULETYPECOMPONENTSUBTYPE;
ALTER TABLE tsrpassthrough RENAME COLUMN temp3 TO BOARDORMODULETYPECOMPONENTSUBTYPE;

ALTER TABLE tsrpassthrough ADD (temp4 NCLOB);
UPDATE tsrpassthrough SET temp4 = BOARDORMODULETYPECOMPONENTVERSIONNUMBER;
COMMIT;
ALTER TABLE tsrpassthrough DROP COLUMN BOARDORMODULETYPECOMPONENTVERSIONNUMBER;
ALTER TABLE tsrpassthrough RENAME COLUMN temp4 TO BOARDORMODULETYPECOMPONENTVERSIONNUMBER;

ALTER TABLE tsrpassthrough ADD (temp5 NCLOB);
UPDATE tsrpassthrough SET temp5 = SERIALNUMBER;
COMMIT;
ALTER TABLE tsrpassthrough DROP COLUMN SERIALNUMBER;
ALTER TABLE tsrpassthrough RENAME COLUMN temp5 TO SERIALNUMBER;

----------------------------------------------------------------------------------