ALTER TABLE PLANNEDACTIVITIES
Add "ARCHIVED" Number(1,0) DEFAULT (0) NULL ;
commit;


ALTER TABLE PLANNEDACTIVITIES
Add ORIGINALLCMENGINEERINGID Number(19,0)  NULL ;
commit;

  ALTER TABLE "PLANNEDACTIVITIES" ADD CONSTRAINT "FK_PLANNEDACTIVITIES_LCMENGINEERING_ORIGINALLCMENGINEERINGID" FOREIGN KEY ("ORIGINALLCMENGINEERINGID")
	  REFERENCES "LCMENGINEERING" ("LCMENGINEERINGID") ENABLE;

	  commit;