
--Update Columns Datatype in DELIVERYTRACKINGS;
ALTER TABLE DELIVERYTRACKINGS MODIFY MS1EVENTTYPE NVARCHAR2(255);
ALTER TABLE DELIVERYTRACKINGS MODIFY MS2EVENTTYPE NVARCHAR2(255);
ALTER TABLE DELIVERYTRACKINGS MODIFY MS3EVENTTYPE NVARCHAR2(255);

COMMIT;