
--Add New Columns in SYSTEMVERIFICATIONPROBLEMS;
ALTER TABLE SYSTEMVERIFICATIONPROBLEMS ADD TESTREPORT NVARCHAR2(300);
ALTER TABLE SYSTEMVERIFICATIONPROBLEMS ADD STANDARDNIR NVARCHAR2(300);
ALTER TABLE SYSTEMVERIFICATIONPROBLEMS ADD ERICSSONSECREPORT NVARCHAR2(300);
ALTER TABLE SYSTEMVERIFICATIONPROBLEMS ADD SWANDSTENTRIES NVARCHAR2(300);
ALTER TABLE SYSTEMVERIFICATIONPROBLEMS ADD PENTESTINGREPORT NVARCHAR2(300);

COMMIT;