
--------------------------------------------------------
--  Ref Constraints for Table PLANNEDACTIVITYRESOURCES
--------------------------------------------------------

  ALTER TABLE "PLANNEDACTIVITYRESOURCES" ADD CONSTRAINT "FK_PLANNEDACTIVITYRESOURCES_PLANNEDACTIVITYTYPES_RULELINKEDDC" FOREIGN KEY ("RULELINKEDDC")
	  REFERENCES "PLANNEDACTIVITYTYPES" ("PLANNEDACTIVITYTYPESID") ENABLE;

COMMIT;