<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Version>1.30.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<!--<PackageReference Include="Aspose.Cells" Version="22.3.0" />-->
		<PackageReference Include="ClosedXML" Version="0.95.3" />
		<PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="2.3.2" />
		<PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1000" />
		<PackageReference Include="NPOI" Version="2.6.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CAM.DataAttributes\CAM.DataAttributes.csproj" />
		<ProjectReference Include="..\CAM.DataTransferObjects\CAM.DataTransferObjects.csproj" />
		<ProjectReference Include="..\CAM.Infrastucture\CAM.Infrastucture.csproj" />
	</ItemGroup>

</Project>
