--------------------------------------------------------
--  ALTER SCRIPT for TABLE PLANNEDACTIVITIES
--------------------------------------------------------

ALTER TABLE PLANNEDACTIVITIES ADD PROJECTDESCRIPTION NVARCHAR2(100);

--------------------------------------------------------
--  DDL for Sequence DAPLANNEDACTIVITYDCF_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DAPLANNEDACTIVITYDCF_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table DAPLANNEDACTIVITYDCF
--------------------------------------------------------

  CREATE TABLE "DAPLANNEDACTIVITYDCF" 
   (	"DAPLANNEDACTIVITYDCFID" NUMBER(19,0) DEFAULT "DAPLANNEDACTIVITYDCF_SEQ"."NEXTVAL", 
	"PLANNEDACTIVITYID" NUMBER(19,0), 
    "DESIGNCOMPONENTFAMILYID" NUMBER(19,0),
    "DCFSTATUS" NUMBER(1,0),
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETIONDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index DAPLANNEDACTIVITYDCFIDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "DAPLANNEDACTIVITYDCFIDX" ON "DAPLANNEDACTIVITYDCF" ("DAPLANNEDACTIVITYDCFID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table DAPLANNEDACTIVITYDCF
--------------------------------------------------------

  ALTER TABLE "DAPLANNEDACTIVITYDCF" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "DAPLANNEDACTIVITYDCF" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "DAPLANNEDACTIVITYDCF" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "DAPLANNEDACTIVITYDCF" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "DAPLANNEDACTIVITYDCF" ADD CONSTRAINT "PK_DAPLANNEDACTIVITYDCF" PRIMARY KEY ("DAPLANNEDACTIVITYDCFID")
  USING INDEX "DAPLANNEDACTIVITYDCFIDX"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DAPLANNEDACTIVITYDCF
--------------------------------------------------------

  ALTER TABLE "DAPLANNEDACTIVITYDCF" ADD CONSTRAINT "FK_DAPLANNEDACTIVITYDCF_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "DAPLANNEDACTIVITYDCF" ADD CONSTRAINT "FK_DAPLANNEDACTIVITYDCF_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "DAPLANNEDACTIVITYDCF" ADD CONSTRAINT "FK_DAPLANNEDACTIVITYDCF_PLANNEDACTIVITIES_PLANNEDACTIVITYID" FOREIGN KEY ("PLANNEDACTIVITYID")
	  REFERENCES "PLANNEDACTIVITIES" ("PLANNEDACTIVITYID") ENABLE;
  ALTER TABLE "DAPLANNEDACTIVITYDCF" ADD CONSTRAINT "FK_DAPLANNEDACTIVITYDCF_DESIGNCOMPONENTFAMILIES_DESIGNCOMPONENTFAMILYID" FOREIGN KEY ("DESIGNCOMPONENTFAMILYID")
	  REFERENCES "DESIGNCOMPONENTFAMILIES" ("DESIGNCOMPONENTFAMILYID") ENABLE;
