CREATE TABLE VNFINFO_backup AS SELECT * FROM VNFINFO;
CREATE TABLE VNFVMINSTANCES_backup AS SELECT * FROM VNFVMINSTANCES;
CREATE TABLE VNFVMCAPACITY_backup AS SELECT * FROM VNFVMCAPACITY;

DROP SEQUENCE VNFINFO_SEQ;
DROP TABLE VNFINFO  CASCADE CONSTRAINTS PURGE ;

DROP SEQUENCE VNFVMINSTANCES_SEQ;
DROP TABLE VNFVMINSTANCES CASCADE CONSTRAINTS PURGE ;

DROP SEQUENCE VNFVMCAPACITY_SEQ;
DROP TABLE VNFVMCAPACITY CASCADE CONSTRAINTS PURGE ;

-- SEQUENCE
CREATE SEQUENCE INTRAVMTYPE_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE
NOKEEP NOSCALE GLOBAL;

-- TABLE
CREATE TABLE INTRAVMTYPE (
    INTRAVMTYPEID    NUMBER(19, 0) DEFAULT INTRAVMTYPE_SEQ.NEXTVAL NOT NULL,
    INTRADESCRIPTION NVARCHAR2(50) NOT NULL,
    CREATIONUSER     NUMBER(10, 0) DEFAULT 1 NOT NULL,
    CREATIONDATE     TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    MODIFICATIONUSER NUMBER(10, 0) DEFAULT 1 NOT NULL,
    MODIFICATIONDATE TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    DELETED          NUMBER(1, 0) DEFAULT 0,
    DELETIONDATE     TIMESTAMP(6)
)
TABLESPACE CAMDB PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT );

-- UNIQUE INDEX
CREATE UNIQUE INDEX PK_INTRAVMTYPE ON
    INTRAVMTYPE (
        INTRAVMTYPEID
    )
        TABLESPACE CAMDB PCTFREE 10 INITRANS 2 MAXTRANS 255
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT );

-- PRIMARY KEY CONSTRAINT
ALTER TABLE INTRAVMTYPE
    ADD CONSTRAINT PK_INTRAVMTYPE PRIMARY KEY ( INTRAVMTYPEID )
        USING INDEX PK_INTRAVMTYPE
    ENABLE;

-- FOREIGN KEYS
ALTER TABLE INTRAVMTYPE
    ADD CONSTRAINT FK_INTRAVMTYPE_ASPNETUSERS_CREATIONUSER FOREIGN KEY ( CREATIONUSER )
        REFERENCES ASPNETUSERS ( ID )
    ENABLE;

ALTER TABLE INTRAVMTYPE
    ADD CONSTRAINT FK_INTRAVMTYPE_ASPNETUSERS_MODIFICATIONUSER FOREIGN KEY ( MODIFICATIONUSER )
        REFERENCES ASPNETUSERS ( ID )
    ENABLE;
COMMIT;
--------------------------------------------------------
--  DDL FOR SEQUENCE INTERVMTYPE_SEQ
--------------------------------------------------------
-- SEQUENCE
CREATE SEQUENCE INTERVMTYPE_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE
NOKEEP NOSCALE GLOBAL;

-- TABLE
CREATE TABLE INTERVMTYPE (
    INTERVMTYPEID    NUMBER(19, 0) DEFAULT INTERVMTYPE_SEQ.NEXTVAL NOT NULL,
    INTERDESCRIPTION NVARCHAR2(50) NOT NULL,
    CREATIONUSER     NUMBER(10, 0) DEFAULT 1 NOT NULL,
    CREATIONDATE     TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    MODIFICATIONUSER NUMBER(10, 0) DEFAULT 1 NOT NULL,
    MODIFICATIONDATE TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    DELETED          NUMBER(1, 0) DEFAULT 0,
    DELETIONDATE     TIMESTAMP(6)
)
TABLESPACE CAMDB PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT );

-- UNIQUE INDEX
CREATE UNIQUE INDEX PK_INTERVMTYPE ON
    INTERVMTYPE (
        INTERVMTYPEID
    )
        TABLESPACE CAMDB PCTFREE 10 INITRANS 2 MAXTRANS 255
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT );

-- PRIMARY KEY CONSTRAINT
ALTER TABLE INTERVMTYPE
    ADD CONSTRAINT PK_INTERVMTYPE PRIMARY KEY ( INTERVMTYPEID )
        USING INDEX PK_INTERVMTYPE
    ENABLE;

-- FOREIGN KEYS
ALTER TABLE INTERVMTYPE
    ADD CONSTRAINT FK_INTERVMTYPE_ASPNETUSERS_CREATIONUSER FOREIGN KEY ( CREATIONUSER )
        REFERENCES ASPNETUSERS ( ID )
    ENABLE;

ALTER TABLE INTERVMTYPE
    ADD CONSTRAINT FK_INTERVMTYPE_ASPNETUSERS_MODIFICATIONUSER FOREIGN KEY ( MODIFICATIONUSER )
        REFERENCES ASPNETUSERS ( ID )
    ENABLE;
COMMIT; 
--------------------------------------------------------
--  DDL FOR TABLE VMWORKLOADTYPE_SEQ
--------------------------------------------------------

-- SEQUENCE
CREATE SEQUENCE VMWORKLOADTYPE_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE
NOKEEP NOSCALE GLOBAL;

-- TABLE
CREATE TABLE VMWORKLOADTYPE (
    VMWORKLOADTYPEID    NUMBER(19, 0) DEFAULT VMWORKLOADTYPE_SEQ.NEXTVAL NOT NULL,
    DESCRIPTION NVARCHAR2(50) NOT NULL,
    CREATIONUSER     NUMBER(10, 0) DEFAULT 1 NOT NULL,
    CREATIONDATE     TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    MODIFICATIONUSER NUMBER(10, 0) DEFAULT 1 NOT NULL,
    MODIFICATIONDATE TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    DELETED          NUMBER(1, 0) DEFAULT 0,
    DELETIONDATE     TIMESTAMP(6)
)
TABLESPACE CAMDB PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT );

-- UNIQUE INDEX
CREATE UNIQUE INDEX PK_VMWORKLOADTYPE ON
    VMWORKLOADTYPE (
        VMWORKLOADTYPEID
    )
        TABLESPACE CAMDB PCTFREE 10 INITRANS 2 MAXTRANS 255
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT );

-- PRIMARY KEY CONSTRAINT
ALTER TABLE VMWORKLOADTYPE
    ADD CONSTRAINT PK_VMWORKLOADTYPE PRIMARY KEY ( VMWORKLOADTYPEID )
        USING INDEX PK_VMWORKLOADTYPE
    ENABLE;

-- FOREIGN KEYS
ALTER TABLE VMWORKLOADTYPE
    ADD CONSTRAINT FK_VMWORKLOADTYPE_ASPNETUSERS_CREATIONUSER FOREIGN KEY ( CREATIONUSER )
        REFERENCES ASPNETUSERS ( ID )
    ENABLE;

ALTER TABLE VMWORKLOADTYPE
    ADD CONSTRAINT FK_VMWORKLOADTYPE_ASPNETUSERS_MODIFICATIONUSER FOREIGN KEY ( MODIFICATIONUSER )
        REFERENCES ASPNETUSERS ( ID )
    ENABLE;
COMMIT; 

--------------------------------------------------------
--  DDL FOR SEQUENCE VNFCLUSTERINFO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE "VNFCLUSTERINFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE VNFCLUSTERINFO
--------------------------------------------------------

  CREATE TABLE VNFCLUSTERINFO 
   (	
    VNFCLUSTERINFOID NUMBER(19,0) DEFAULT VNFCLUSTERINFO_SEQ.NEXTVAL NOT NULL, 	 
	OPCOID NUMBER(5) NOT NULL, 
	LOCATIONID NUMBER(5) NOT NULL, 
    CLUSTERNAMEID NUMBER(19,0)  NOT NULL,
	NOOFBLADES NUMBER(5) NOT NULL,
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_AUDITLOGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "VNFCLUSTERINFO" ON VNFCLUSTERINFO ("VNFCLUSTERINFOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE VNFCLUSTERINFO MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE VNFCLUSTERINFO MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE VNFCLUSTERINFO MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE VNFCLUSTERINFO MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE VNFCLUSTERINFO ADD CONSTRAINT "PK_VNFCLUSTERINFO" PRIMARY KEY ("VNFCLUSTERINFOID")
  USING INDEX "VNFCLUSTERINFO"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE VNFCLUSTERINFO ADD CONSTRAINT "FK_VNFCLUSTERINFO_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE VNFCLUSTERINFO ADD CONSTRAINT "FK_VNFCLUSTERINFO_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE VNFCLUSTERINFO ADD CONSTRAINT "FK_VNFCLUSTERINFO_CLUSTERNAME_CLUSTERNAMEID" FOREIGN KEY ("CLUSTERNAMEID")
	  REFERENCES "CLUSTERNAME" ("CLUSTERNAMEID") ENABLE;
  ALTER TABLE VNFCLUSTERINFO ADD CONSTRAINT "FK_VNFCLUSTERINFO_OPCOS_OPCOID" FOREIGN KEY ("OPCOID")
	  REFERENCES "OPCOS" ("OPCOID") ENABLE;
  ALTER TABLE VNFCLUSTERINFO ADD CONSTRAINT "FK_VNFCLUSTERINFO_LOCATIONS_LOCATIONID" FOREIGN KEY ("LOCATIONID")
	  REFERENCES "LOCATIONS" ("LOCATIONID") ENABLE;
COMMIT;

--------------------------------------------------------
--  DDL FOR SEQUENCE VNFINFO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE "VNFINFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE VNFINFO
--------------------------------------------------------

  CREATE TABLE VNFINFO 
   (	
    VNFINFOID NUMBER(19,0) DEFAULT VNFINFO_SEQ.NEXTVAL NOT NULL, 
	VNFNAMEID NUMBER(19,0) NOT NULL, 
	VNFCLUSTERINFOID NUMBER(19,0) NOT NULL, 
	VNFVMTYPENAMEID NUMBER(19,0) NOT NULL, 
	
	NSXT NUMBER(1,0) NOT NULL, 
	INTRAVMTYPEID NUMBER(19,0) NOT NULL, 
	INTERVMTYPEID NUMBER(19,0) NOT NULL,
    VMWORKLOADTYPEID NUMBER(19,0) NOT NULL,
    VMSTORAGEBLOCKSIZE NVARCHAR2(50),  
	
	NOOFVNFINSTANCES NUMBER(19) NOT NULL, 
	NOOFVMSPERTYPE NUMBER(19) NOT NULL, 
	NUMA NUMBER(1),
    SOCKET NVARCHAR2(250), 
	
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_AUDITLOGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_VNFINFO" ON VNFINFO ("VNFINFOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE VNFINFO MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE VNFINFO MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE VNFINFO MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE VNFINFO MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE VNFINFO ADD CONSTRAINT "PK_VNFINFO" PRIMARY KEY ("VNFINFOID")
  USING INDEX "PK_VNFINFO"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE VNFINFO ADD CONSTRAINT "FK_VNFINFO_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE VNFINFO ADD CONSTRAINT "FK_VNFINFO_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE VNFINFO ADD CONSTRAINT "FK_VNFINFO_VNFNAME_VNFNAMEID" FOREIGN KEY ("VNFNAMEID")
	  REFERENCES "VNFNAME" ("VNFNAMEID") ENABLE;
  ALTER TABLE VNFINFO ADD CONSTRAINT "FK_VNFINFO_VMTYPENAME_VMTYPENAMEID" FOREIGN KEY ("VNFVMTYPENAMEID")
	  REFERENCES "VMTYPENAME" ("VMTYPENAMEID") ENABLE;

  ALTER TABLE VNFINFO ADD CONSTRAINT "FK_VNFINFO_VNFCLUSTERINFO_VNFCLUSTERINFOID" FOREIGN KEY ("VNFCLUSTERINFOID")
	  REFERENCES "VNFCLUSTERINFO" ("VNFCLUSTERINFOID") ENABLE;
	  
  ALTER TABLE VNFINFO ADD CONSTRAINT "FK_VNFINFO_INTRAVMTYPE_INTRAVMTYPEID" FOREIGN KEY ("INTRAVMTYPEID")
	  REFERENCES "INTRAVMTYPE" ("INTRAVMTYPEID") ENABLE;
  ALTER TABLE VNFINFO ADD CONSTRAINT "FK_VNFINFO_INTERVMTYPE_INTERVMTYPEID" FOREIGN KEY ("INTERVMTYPEID")
	  REFERENCES "INTERVMTYPE" ("INTERVMTYPEID") ENABLE;
  ALTER TABLE VNFINFO ADD CONSTRAINT "FK_VNFINFO_VMWORKLOADTYPE_VMWORKLOADTYPEID" FOREIGN KEY ("VMWORKLOADTYPEID")
	  REFERENCES "VMWORKLOADTYPE" ("VMWORKLOADTYPEID") ENABLE;
COMMIT;

 
--------------------------------------------------------
--  DDL FOR SEQUENCE VNFVMCAPACITY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE "VNFVMCAPACITY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL FOR TABLE VNFINFO
--------------------------------------------------------

  CREATE TABLE VNFVMCAPACITY 
   (	
    VNFVMCAPACITYID NUMBER(19,0) DEFAULT VNFVMCAPACITY_SEQ.NEXTVAL NOT NULL, 
	VNFINFOID NUMBER(19,0) NOT NULL, 
	FINANCIALYEAR NUMBER(5) NOT NULL,  
	
	VNFCPUPERVM NUMBER(19) NOT NULL, 
	RXTXCPUCOUNT NUMBER(1), 
	 RAMPERVM NUMBER(19) NOT NULL,
    DATADISK NUMBER(19) NOT NULL, 
    OSDISK NUMBER(19), 
	IOPSRUNNING  NVARCHAR2(50), 
	IOPSLOADING NVARCHAR2(50),
    VMWORKLOADDISTRIBUTION NVARCHAR2(250), 
	 NORTHSOUTHBOUNDBANDWIDTH NVARCHAR2(250), 
	EASTWESTBOUNDBANDWIDTH NVARCHAR2(250), 
	 OTHERREQUIREMENTS NVARCHAR2(250), 
	BACKUPREQUIRED NUMBER(1), 
	  PROBINGREQUIRED  NUMBER(1), 
	CREATIONUSER NUMBER(10,0) DEFAULT 1, 
	CREATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	MODIFICATIONUSER NUMBER(10,0) DEFAULT 1, 
	MODIFICATIONDATE TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	DELETED NUMBER(1,0) DEFAULT 0, 
	DELETIONDATE TIMESTAMP (6),
	FINANCIALVERSION NUMBER(8) NOT NULL   
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL FOR INDEX PK_AUDITLOGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "VNFVMCAPACITY" ON VNFVMCAPACITY ("VNFVMCAPACITYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE VNFVMCAPACITY MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE VNFVMCAPACITY MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE VNFVMCAPACITY MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE VNFVMCAPACITY MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE VNFVMCAPACITY ADD CONSTRAINT "PK_VNFVMCAPACITY" PRIMARY KEY ("VNFVMCAPACITYID")
  USING INDEX "VNFVMCAPACITY"  ENABLE;
--------------------------------------------------------
--  REF CONSTRAINTS FOR TABLE AUDITLOGS
--------------------------------------------------------

  ALTER TABLE VNFVMCAPACITY ADD CONSTRAINT "FK_VNFVMCAPACITY_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE VNFVMCAPACITY ADD CONSTRAINT "FK_VNFVMCAPACITY_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE VNFVMCAPACITY ADD CONSTRAINT "FK_VNFVMCAPACITY_VNFINFO_VNFINFOID" FOREIGN KEY ("VNFINFOID")
	  REFERENCES "VNFINFO" ("VNFINFOID") ENABLE;
  

-------------------------------

Insert into intravmtype (INTRADESCRIPTION,CREATIONUSER,MODIFICATIONUSER) values  ('AAF',1,1);
Insert into intravmtype (INTRADESCRIPTION,CREATIONUSER,MODIFICATIONUSER) values ('AFF',1,1);
Insert into intravmtype (INTRADESCRIPTION,CREATIONUSER,MODIFICATIONUSER) values ('AMS',1,1);
Commit;


Insert into intervmtype (INTERDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) values  ('AFF { any other VNF}',1,1);
Insert into intervmtype (INTERDESCRIPTION,CREATIONUSER,MODIFICATIONUSER) values ('AAF { vBGF I-SBC }',1,1); 

Commit;

Insert into vmworkloadtype (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER) values  ('Management',1,1);
Insert into vmworkloadtype (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER) values ('Signalling Plane',1,1); 
Insert into vmworkloadtype (DESCRIPTION,CREATIONUSER,MODIFICATIONUSER) values ('Data Plane',1,1); 

Commit;