insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','requestType','Request Type','0','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','vnfNameDescritpion','VNF Name','1','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','vmTypeNameDescription','VM Type Name','2','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','siteLocation','Site Name','3','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','nsxt','NSX-T','4','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','intraVmType','AFFINITY RULES - ''INTRA VM Type''','5','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','interVmType','AFFINITY RULES - ''INTER VM Type''','6','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','vmWorkLoadType','VM Workload type ','7','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','vmStorageBlockSize','Storage Block Size','8','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME , CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','financialYear','FY 24/25','9','1','1','0','2','TEMS_XBOM_Export_Draft.xlsx',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','noOfVnfInstances','Number Of VNF Instances','9','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','noOfVmsPerType','Number of 
VMs per type ','10','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','numa','NUMA
(Accepted Vlaues: TRUE, FALSE, empty cell)','11','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','socket','Socket
(Wil only consider if NUMA is TRUE)','12','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);
 
 insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','vcpuPerVm','Number of
 vCPU per VM','13','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);
 
 insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','rxTxCpuCount','RX/TX'' CPU INCLUDED IN vCPU  Count ? ','14','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','ramPerVm','RAM (GB) 
per VM','15','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','dataDisk','Storage (GB) per VM
 - Data Disk','16','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);
 
 insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','osDisk','Storage (GB) per VM
 - OS disk','17','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);
 
 insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','iopsRunning','Storage IOPS 
per VM 
- Running ','18','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);

 insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','iopsLoading','Storage IOPS 
per VM
 - Loading ','19','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);
 
 
insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','vmWorkLoadDistribution','Storage Read/Write VM workload distribution (%/%)','20','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','northDouthBoundBandWidth','North/South 
bandwidth 
requirement per VM (Mbit/s)','21','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','eastWestBoundBandWidth','East/West  bandwidth requirement per VM (Mbit/s)','22','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','otherRequirements','Onboarding Date / Other requirements?','23','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','backupRequired','BACKUP REQUIRED','24','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);

insert into exceltemplateconfiguration (PROCESSNAME,PROPERTYNAME,COLUMNHEADERNAME, COLUMNORDER,ISIMPORTFIELD ,ISEXPORTFIELD ,ROWSTARTING,HEADERROWSTARTING, TEMPLATEFILENAME ,MAPPINGREFERENCE, CREATIONUSER, MODIFICATIONUSER) values  ('VBOM','probIngRequired','Probing Required?','25','1','1','4','3','TEMS_XBOM_Export_Draft.xlsx','YES',1,1);

Commit;