UPDATE MAJORSOFTWAREBUILDS  SET ISVMWARE = 1 WHERE MAJORSOFTWAREBUILDSID IN (SELECT MSB.MAJORSOFTWAREBUILDSID FROM MAJORSOFTWAREBUILDS MSB JOIN ORIGINALEQUIPMENTMANUFACTURERS OEM ON OEM.ORGEQPMANUFACTURERID = MSB.ORGEQPMANUFACTURERID WHERE UPPER(OEM.ORIGINALEQUIPMENTMANUFACTURER) = 'VMWARE');

COMMIT;

