
alter table SUPPORTEDSERVICES
add "DEFAULT" NUMBER(1,0) DEFAULT 0; 

commit;

Insert into CAMSDBUSER.SUPPORTEDSERVICES 
(CREATIONUSER,CREATIONDATE,MODIFICATIONUSER,MODIFICATIONDATE,DESCRIPTION,"DEFAULT") values 
(177,to_timestamp(CURRENT_DATE,'DD-MON-RR HH.MI.SSXFF AM'),177,to_timestamp(CURRENT_DATE,'DD-MON-RR HH.MI.SSXFF AM'),'Supported All Services',1);

commit;


alter table SUBNETWORKBOUNDARIES
add "SWAPPLICATIONNAME"  NVARCHAR2(2000); 
commit;