--------------------------------------------------------
--  DDL for Sequence REPORTSCHEDULER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE "REPORTSCHEDULER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table REPORTSCHEDULER
--------------------------------------------------------

  CREATE TABLE "REPORTSCHEDULER" 
   (	
   "REPORTSCHEDULERID" NUMBER DEFAULT "REPORTSCHEDULER_SEQ"."NEXTVAL",  
	"REPORTNAME" NVARCHAR2(2000),
	"ISSCHEDULED" NUMBER(1,0) DEFAULT 0, 
    "OPCOID" NVARCHAR2(2000), 
    "REPORTVERTICAL" NVARCHAR2(2000), 
	"EXPORTFILEPATH" NVARCHAR2(2000), 
	"EXPORTFILEFORMAT" NVARCHAR2(100), 
	"SCHEDULEDDATE" NUMBER(10,0),
	"SCHEDULEDDAYINWEEK" NVARCHAR2(50), 
	"CREATIONUSER" NUMBER(10,0), 
	"CREATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"MODIFICATIONUSER" NUMBER(10,0), 
	"MODIFICATIONDATE" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(systimestamp), 
	"DELETED" NUMBER(1,0) DEFAULT (0), 
	"DELETIONDATE" TIMESTAMP (6) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  DDL for Index REPORTSCHEDULER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REPORTSCHEDULER_PK" ON "REPORTSCHEDULER" ("REPORTSCHEDULERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAMDB" ;
--------------------------------------------------------
--  Constraints for Table REPORTSCHEDULER
--------------------------------------------------------

  ALTER TABLE "REPORTSCHEDULER" ADD CONSTRAINT "REPORTSCHEDULER_PK" PRIMARY KEY ("REPORTSCHEDULERID")
  USING INDEX "REPORTSCHEDULER_PK"  ENABLE;
  ALTER TABLE "REPORTSCHEDULER" MODIFY ("REPORTSCHEDULERID" NOT NULL ENABLE);
  ALTER TABLE "REPORTSCHEDULER" MODIFY ("CREATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "REPORTSCHEDULER" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "REPORTSCHEDULER" MODIFY ("MODIFICATIONUSER" NOT NULL ENABLE);
  ALTER TABLE "REPORTSCHEDULER" MODIFY ("MODIFICATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "REPORTSCHEDULER" MODIFY ("DELETED" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table REPORTSCHEDULER
--------------------------------------------------------
  ALTER TABLE "REPORTSCHEDULER" ADD CONSTRAINT "FK_REPORTSCHEDULER_ASPNETUSERS_MODIFICATIONUSER" FOREIGN KEY ("MODIFICATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
  ALTER TABLE "REPORTSCHEDULER" ADD CONSTRAINT "FK_REPORTSCHEDULER_ASPNETUSERS_CREATIONUSER" FOREIGN KEY ("CREATIONUSER")
	  REFERENCES "ASPNETUSERS" ("ID") ENABLE;
