
--TAKE BACKUP TABLE FOR DESIGNCOMPONENTFAMILIES
CREATE TABLE DESIGNCOMPONENTFAMILIES_TEMP AS SELECT DESIGNCOMPONENTFAMILYID,SUBNETWORKBOUNDARYID,DESCRIPTION FROM DESIGNCOMPONENTFAMILIES ;
COMMIT;

--UPDATE DESCRIPTION COLUMN IN DESIGNCOMPONENTFAMILIES FROM SUBNETWORKBOUNDARIES -
MERGE INTO DESIGNCOMPONENTFAMILIES DCF
USING (
  SELECT DCFBK.DESIGNCOMPONENTFAMILYID,
         DCFBK.SUBNETWORKBOUNDARYID,
         SNB.ALIAS,
         SNB.DESCRIPTION
  FROM DESIGNCOMPONENTFAMILIES_TEMP DCFBK
  JOIN SUBNETWORKBOUNDARIES SNB
    ON DCFBK.SUBNETWORKBOUNDARYID = SNB.ID
 where DCFBK.DESCRIPTION is null
) SNB_DESC
ON (SNB_DESC.DESIGNCOMPONENTFAMILYID=DCF.DESIGNCOMPONENTFAMILYID)
WHEN MATCHED THEN UPDATE SET DCF.DESCRIPTION   = CASE WHEN SNB_DESC.ALIAS IS NOT NULL THEN SNB_DESC.ALIAS ELSE SNB_DESC.DESCRIPTION END;
COMMIT;

--DROP BACKUP TABLE
Drop Table DESIGNCOMPONENTFAMILIES_TEMP;


-----DELETE RECORD BELONG TO CLASSNAME-ReportSoftwareDtoGrid FROM TABLE-GRIDCUSTOMCOLUMN
DELETE FROM GRIDCUSTOMCOLUMN WHERE CLASSNAME='ReportSoftwareDtoGrid';
COMMIT;


  
    

