-------------RB SCRIPTS FOR TSRPASSTHROUGH-----------------
ALTER TABLE TSRPASSTHROUGH DROP COLUMN PRODUCTNAME;
ALTER TABLE TSRPASSTHROUGH DROP COLUMN SOFTWAREVERSION; 
ALTER TABLE TSRPASSTHROUGH DROP COLUMN SUBDOMAINRESPONSIBLE;
ALTER TABLE TSRPASSTHROUGH DROP COLUMN ISSORTINGALLOWED;