 
 
ALTER TABLE ASPNETMODULES DROP COLUMN  MENU  NVARCHAR2(250); 
ALTER TABLE ASPNETMODULES RENAME COLUMN MODULEPATH  TO ALIASNAME; 
ALTER TABLE REPORTSCHEDULER ADD ISACTIVE NUMBER(1,0) DEFAULT 0;

ALTER TABLE GRIDCUSTOMCOLUMN RENAME COLUMN MESSAGINGDATE TO ACHIEVEMENTDATE;
ALTER TABLE GRIDCUSTOMCOLUMN ADD  SIGNPOSTDATE  NUMBER(10); 
 
COMMIT; 
 