---DROP TABLE MAJORHARDWAREBUILDSBACKUP;
---DROP TABLE MAJORSOFTWAREBUILDSBACKUP;
---DROP TABLE SOFTWAREBUILDCOMPATIBILITYBACKUP;
---DROP TABLE SYSTEMTYPESBACKUP;
---DROP TABLE SYSTEMTYPESMAJORHARDWAREBUILDSBACKUP;
---DROP TABLE SYSTEMTYPESSUBDOMAINSPOCBACKUP; 
---DROP TABLE LCMENGINEERINGBACKUP; 
---DROP TABLE LCMENGINEERINGSUBDOMAINSPOCBACKUP; 
---DROP TABLE DESIGNCOMPONENTSBACKUP; 
---DROP TABLE DESIGNCOMPONENTFAMILIESBACKUP; 
---DROP TABLE DESIGNASPECTSBACKUP; 
---DROP TABLE PLANNEDACTIVITIESBACKUP;
---DROP TABLE NETWORKELEMENTSASPLANNEDBACKUP;
---DROP TABLE NETWORKELEMENTASPLANNEDEDUSPOCBACKUP;
---DROP TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOCBACKUP;
---DROP TABLE ASPNETUSERSBACKUP;
---DROP TABLE ASPNETUSERROLESBACKUP; 


ALTER TABLE ASPNETUSERS   RENAME TO ASPNETUSERS_ROLLBACKUP;
ALTER TABLE ASPNETUSERS_BACKUP   RENAME TO ASPNETUSERS;

ALTER TABLE ASPNETUSERROLES   RENAME TO ASPNETUSERROLES_ROLLBACKUP;
ALTER TABLE ASPNETUSERROLES_BACKUP   RENAME TO ASPNETUSERROLES;
 
ALTER TABLE SYSTEMTYPES   RENAME TO SYSTEMTYPES_ROLLBACKUP;
ALTER TABLE SYSTEMTYPES_BACKUP   RENAME TO SYSTEMTYPES;

ALTER TABLE SYSTEMTYPESSUBDOMAINSPOC   RENAME TO SYSTEMTYPESSUBDOMAINSPOC_ROLLBACKUP;
ALTER TABLE SYSTEMTYPESSUBDOMAINSPOC_BACKUP   RENAME TO SYSTEMTYPESSUBDOMAINSPOC;

ALTER TABLE LCMENGINEERINGSUBDOMAINSPOC   RENAME TO LCMENGINEERINGSUBDOMAINSPOC_ROLLBACKUP;
ALTER TABLE LCMENGINEERINGSUBDOMAINSPOC_BACKUP   RENAME TO LCMENGINEERINGSUBDOMAINSPOC;

ALTER TABLE LCMENGINEERINGEDUSPOC   RENAME TO LCMENGINEERINGEDUSPOC_ROLLBACKUP;
ALTER TABLE LCMENGINEERINGEDUSPOC_BACKUP   RENAME TO LCMENGINEERINGEDUSPOC;

ALTER TABLE NETWORKELEMENTASPLANNEDEDUSPOC   RENAME TO NETWORKELEMENTASPLANNEDEDUSPOC_ROLLBACKUP;
ALTER TABLE NETWORKELEMENTASPLANNEDEDUSPOC_BACKUP   RENAME TO NETWORKELEMENTASPLANNEDEDUSPOC;

ALTER TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC   RENAME TO NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_ROLLBACKUP;
ALTER TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_BACKUP   RENAME TO NETWORKELEMENTASPLANNEDSUBDOMAINSPOC;

 
 ALTER TABLE organisation   RENAME TO organisation_ROLLBACKUP;
ALTER TABLE organisation_BACKUP   RENAME TO organisation;
 
COMMIT;
 



