-----RB SCRIPTS FOR MAINORGANISATION-----
DROP SEQUENCE "MAINORGANISATION_SEQ";
DROP TABLE MAINORGANISATION;
COMMIT; 

-----RB SCRIPTS FOR PRACTICE-----
DROP SEQUENCE "PRACTICE_SEQ";
DROP TABLE PRACTICE;
COMMIT; 

-----RB SCRIPTS FOR ORGANISATION-----
--DROP SEQUENCE "ORGANISATION_SEQ";
--DROP TABLE ORGANISATION;
--COMMIT; 

DROP SEQUENCE "MAJORSWBUIDLSDESIGNCONTACTS_SEQ";
DROP TABLE MAJORSWBUILDSDESIGNCONTACTS;
COMMIT; 

DROP SEQUENCE "MAJORHWBUIDLSDESIGNCONTACTS_SEQ";
DROP TABLE MAJORHWBUILDSDESIGNCONTACTS;
COMMIT; 