ALTER TABLE "NETWORKELEMETSASIS" DROP COLUMN "PLATFORMTYPE";
ALTER TABLE "NETWORKELEMETSASIS" DROP COLUMN "HARDWARETYPE";
ALTER TABLE "NETWORKELEMETSASIS" DROP COLUMN "SOFTWARERELEASEINFORMATION";
COMMIT;