--ALTER TABLE "LCMENGINEERING" DROP COLUMN "VERTICALRESPONSIBLEID";
--ALTER TABLE "LCMENGINEERINGEDUSPOC" DROP COLUMN "DESIGNCONTACTID";
--ALTER TABLE "LCMENGINEERINGSUBDOMAINSPOC" DROP COLUMN "DESIGNCONTACTID";
 
--ALTER TABLE "NETWORKELEMENTASPLANNEDEDUSPOC" DROP COLUMN "DESIGNCONTACTID";
--ALTER TABLE "NETWORKELEMENTASPLANNEDSUBDOMAINSPOC" DROP COLUMN "DESIGNCONTACTID";

--ALTER TABLE "LCMENGINEERING" DROP CONSTRAINT "FK_LCMENGINEERING_VERTICALRESPONSIBLES_VERTICALRESPONSIBLEID";
--ALTER TABLE "LCMENGINEERINGEDUSPOC" DROP CONSTRAINT "FK_LCMENGINEERINGEDUSPOC_ASPNETUSERS_DESIGNCONTACTID";
--ALTER TABLE "LCMENGINEERINGSUBDOMAINSPOC" DROP CONSTRAINT "FK_LCMENGINEERINGSUBDOMAINSPOC_ASPNETUSERS_DESIGNCONTACTID";
 
--ALTER TABLE "NETWORKELEMENTASPLANNEDEDUSPOC" DROP CONSTRAINT "FK_NETWORKELEMENTASPLANNEDEDUSPOC_ASPNETUSERS_DESIGNCONTACTID";
--ALTER TABLE "NETWORKELEMENTASPLANNEDSUBDOMAINSPOC" DROP CONSTRAINT "FK_NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_ASPNETUSERS_DESIGNCONTACTID";
 

ALTER TABLE LCMENGINEERINGSUBDOMAINSPOC MODIFY SUBDOMAINSPOCID  Not NULL;
ALTER TABLE LCMENGINEERINGEDUSPOC MODIFY SUBDOMAINSPOCID Not NULL;
ALTER TABLE NETWORKELEMENTASPLANNEDEDUSPOC MODIFY SUBDOMAINSPOCID Not NULL;
ALTER TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC MODIFY SUBDOMAINSPOCID Not NULL;

COMMIT; 