
--DROP SEQUENCE "MAJORHWBUIDLSDESIGNCONTACTS_SEQ";
--DROP TABLE MAJORHWBUILDSDESIGNCONTACTS;


--DROP SEQUENCE "MAJORSWBUIDLSDESIGNCONTACTS_SEQ";
--DROP TABLE MAJORSWBUILDSDESIGNCONTACTS;
  
--COMMIT; 