----------------------------------------------
-- AlTER SCRIPT FOR MAJORHARDWAREBUILDS ------
ALTER TABLE MAJORHARDWAREBUILDS DROP COLUMN DESIGNCONTACTID;
ALTER TABLE MAJORHARDWAREBUILDS DROP CONSTRAINT "FK_MAJORHARDWAREBUILDS_ASPNETUSERS_DESIGNCONTACT";
COMMIT;
---------------------------------------------- 
-- AlTER SCRIPT FOR MAJORSOFTWAREBUILDS ------
ALTER TABLE MAJORSOFTWAREBUILDS DROP COLUMN DESIGNCONTACTID;
ALTER TABLE MAJORSOFTWAREBUILDS DROP CONSTRAINT "FK_MAJORSOFTWAREBUILDS_ASPNETUSERS_DESIGNCONTACT";
COMMIT;