----------------------------------------------
-- AlTER SCRIPT FOR MAJORHARDWAREBUILDS ------
--ALTER TABLE MAJORHARDWAREBUILDS ADD DESIGNCONTACTID NUMBER(10,0);
--ALTER TABLE MAJORHARDWAREBUILDS ADD CONSTRAINT "FK_MAJORHARDWAREBUILDS_ASPNETUSERS_DESIGNCONTACT" FOREIGN KEY ("DESIGNCONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
--COMMIT;
---------------------------------------------- 
-- AlTER SCRIPT FOR MAJORSOFTWAREBUILDS ------
--ALTER TABLE MAJORSOFTWAREBUILDS ADD DESIGNCONTACTID NUMBER(10,0);
--ALTER TABLE MAJORSOFTWAREBUILDS ADD CONSTRAINT "FK_MAJORSOFTWAREBUILDS_ASPNETUSERS_DESIGNCONTACT" FOREIGN KEY ("DESIGNCONTACTID") REFERENCES "ASPNETUSERS" ("ID") ENABLE;
--COMMIT;

--ALTER TABLE LCMENGINEERING ADD VERTICALRESPONSIBLEID NUMBER(10,0);
--ALTER TABLE LCMENGINEERING ADD CONSTRAINT "FK_LCMENGINEERING_VERTICALRESPONSIBLES_VERTICALRESPONSIBLEID" FOREIGN KEY ("VERTICALRESPONSIBLEID") REFERENCES "VERTICALRESPONSIBLES" ("VERTICALRESPONSIBLEID") ENABLE;
--COMMIT;

----------------------------------------------------------
-- AlTER SCRIPT FOR ALL EDU AND SUBDOMAINSPOCS -----------


--ALTER TABLE LCMENGINEERINGEDUSPOC ADD CONSTRAINT "FK_LCMENGINEERINGEDUSPOC_SUBDOMAINSPOCS_SUBDOMAINSPOCID";
--ALTER TABLE LCMENGINEERINGSUBDOMAINSPOC ADD CONSTRAINT "FK_LCMENGINEERINGSUBDOMAINSPOC_SUBDOMAINSPOCS_SUBDOMAINSPOCID";
----ALTER TABLE NETWORKELEMENTASPLANNEDEDUSPOC ADD CONSTRAINT "FK_NETWORKELEMENTASPLANNEDEDUSPOC_SUBDOMAINSPOCS_SUBDOMAINSPOCID";
ALTER TABLE NETWORKELEMENTASPLANNEDSUBDOMAINSPOC ADD CONSTRAINT "FK_NETWORKELEMENTASPLANNEDSUBDOMAINSPOC_SUBDOMAINSPOCS_SUBDOMAINSPOCID";
--COMMIT;