----------RB SCRIPTS FOR THE ASPNETROLES-----------
ALTER TABLE ASPNETROLES DROP COLUMN	"CREATIONUSER";
ALTER TABLE ASPNETROLES DROP COLUMN	"CREATIONDATE"; 
ALTER TABLE ASPNETROLES DROP COLUMN	"MODIFICATIONUSER"; 
ALTER TABLE ASPNETROLES DROP COLUMN	"MODIFICATIONDATE";
ALTER TABLE ASPNETROLES DROP COLUMN	"DELETED"; 
ALTER TABLE ASPNETROLES DROP COLUMN	"DELETIONDATE";