ALTER TABLE SERVICEPLAN ADD DESIGNCOMPONENTFAMILYID;
ALTER TABLE SERVICEPLAN ADD STATUS;
ALTER TABLE SERVICEPLAN ADD PLANNEDACTIVITYID;

ALTER TABLE SERVICEPLAN DROP COLUMN OPCOID;

ALTER TABLE PLANNEDACTIVITIES DROP COLUMN SERVICEPLANID;