ALTER TABLE LCMENGINEERING ADD DESIGNCOMPONENTFAMILYID NUMBER(19, 0);
ALTER TABLE LCMENGINEERING ADD CONSTRAINT "FK_LCMENGINEERING_DESIGNCOMPONENTFAMILIES_DESIGNCOMPONENTFAMILYID" FOREIGN KEY ("DESIGNCOMPONENTFAMILYID")
	  REFERENCES "DESIGNCOMPONENTFAMILIES" ("DESIGNCOMPONENTFAMILYID") ENABLE;
      
ALTER TABLE NETWORKELEMENTSASPLANNED ADD DESIGNCOMPONENTFAMILYID NUMBER(19, 0);
ALTER TABLE NETWORKELEMENTSASPLANNED ADD CONSTRAINT "FK_NETWORKELEMENTSASPLANNED_DESIGNCOMPONENTFAMILIES_DESIGNCOMPONENTFAMILYID" FOREIGN KEY ("DESIGNCOMPONENTFAMILYID")
	  REFERENCES "DESIGNCOMPONENTFAMILIES" ("DESIGNCOMPONENTFAMILYID") ENABLE;