-------------ALTER SCRIPTS FOR TSRPASSTHROUGH-----------------
ALTER TABLE TSRPASSTHROUGH ADD PRODUCTNAME NVARCHAR2(2000);
ALTER TABLE TSRPASSTHROUGH ADD SOFTWAREVERSION NVARCHAR2(2000);
ALTER TABLE TSRPASSTHROUGH ADD SUBDOMAINRESPONSIBLE NVARCHAR2(2000);
ALTER TABLE TSRPASSTHROUGH ADD ISSORTINGALLOWED NUMBER(1,0);

-----RESET MANAGETABLE CONTENT SCRIPT---------------
update gridcustomcolumn set deleted=1 ,deletiondate=SYS_EXTRACT_UTC(systimestamp) where deleted = 0 and classname='TsrPassThroughDtoGrid';
commit;