 
 
ALTER TABLE ASPNETMODULES ADD  MENU  NVARCHAR2(250); 
ALTER TABLE ASPNETMODULES RENAME COLUMN ALIASNAME TO MODULEPATH;
ALTER TABLE REPORTSCHEDULER DROP COLUMN ISACTIVE  ;

ALTER TABLE GRIDCUSTOMCOLUMN RENAME COLUMN ACHIEVEMENTDATE TO MESSAGINGDATE;
ALTER TABLE GRIDCUSTOMCOLUMN DROP COLUMN SIGNPOSTDATE  ;

COMMIT; 